### ISSUE TITLE
Removed parens in spread JSX expression introduces ambiguity

### ISSUE THREAD

**Issue by jonathanewerner** [prettier/prettier#1000]
```diff
- <div {...((foo || foo === null) ? {foo} : null)} />
+ <div {...foo || foo === null ? { foo } : null} />;
```
This probably doesn't introduce a semantic change, but makes the code really unclear, as you need to know about operator precedence of the spread operator.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%20%7B...((foo%20%7C%7C%20foo%20%3D%3D%3D%20null)%20%3F%20%7Bfoo%7D%20%3A%20null)%7D%20%2F%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Woah, crazy. Yeah, we definitely need to add parenthesis there, the precedence rules are very unclear there

**Comment by rattrayalex** [comment]
Does this also apply to normal spreads?

**Comment by vjeux** [comment]
Looks like this issue is only about JSX spread

```js
a = {...foo || foo === null ? { foo } : null}
```

outputs

```js
a = { ...(foo || foo === null ? { foo } : null) };
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22a%20%3D%20%7B...foo%20%7C%7C%20foo%20%3D%3D%3D%20null%20%3F%20%7B%20foo%20%7D%20%3A%20null%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D
