### ISSUE TITLE
Prettier formats text strange when using AngularJs code brackets

### ISSUE THREAD

**Issue by jisuo** [prettier/prettier#10078]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeADgPgDpQAR7DB4DkACgDZwCGAznHpFAGYCWATgLZ4wAW1MPAE8IAVzwB3MRQAmeCqwDWDGBDwy4VeI2gxqYGCTwAfHu2pRaFAQwC+t3AVS0Y7aAHNHBPJiJ4AJAbsFAB0THoGIWzsLgD6UNScdraExIGuoeH6MCHWcQlJePaoAPQublCe+D64pVggADQgEOgwrNC0yKDU7G4SZD0InSjUFBLUQp1NAEbmYMowAMro+qyVyK6icE1wnNNwMhoyADIW7qLU7nAAYhBcAm3rI6KqjSC8MJwUAOq8rPC0FZgOCLIb-VgAN3+QmQ4FoUxAa3o7BgZHM7k41GQzFG9CaACtaAAPABCcwWi0ScGOazg2Nx2xAhKJizW7ioAEVRBB4PSKHiQCsYnB2LDptR9hQ3uh2GsYN9WDI+MgABwABiaMog9G+5nQsJlcGRELpTQAjtz4GiWsMQHQALRQOAHA5vdhwC0cOBoy6YvkC+icVgbdhbJq0Nmcy10pA4-mMvTTBVK3jIABMTVc1FYCkqAGEIJw-SgjQBWN6iegAFQlwzjAohWwAklANLBFmBZa0AIKtxYwIRUf1wexAA)

(playground complains about SyntaxError: Unexpected token (2:61))

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
<p>
  {{ 'Please confirm that you would like to delete contact' | translate }}
  <strong>{{ $ctrl.contact.first_name }} {{ $ctrl.contact.last_name }}</strong>
</p>
```

**Output:**

```jsx
<p>
  {{ 'Please confirm that you would like to delete contact' | translate }}
  <strong
    >{{ $ctrl.contact.first_name }} {{ $ctrl.contact.last_name }}</strong
  >
</p>
```

**Expected behavior:**
I guess like this?

```jsx
<p>
  {{ 'Please confirm that you would like to delete contact' | translate }}
  <strong>{{ $ctrl.contact.first_name }} {{ $ctrl.contact.last_name }}</strong>
</p>
```

**Comment by jisuo** [comment]
Setting --parser: angular in the playground fixes the error and formats correctly, but in the repo with Prettier 2.2.1 and file names like *.component.html it formats incorrectly.

**Comment by brodybits** [comment]
You can also use the `--parser` option on the command line to get what you want.

**Comment by jisuo** [comment]
Changing to --html-whitespace-sensitivity: "ignore" in the playground makes it format correctly.

Is this needed or is it a bug?

**Comment by thorn0** [comment]
The output similar to yours can be achieved if we increase the indentation by wrapping the code in another tag.

I'm closing the issue since this works as expected:

* The code wrapped because it hits the `printWidth` limit.
* The `<strong>` tag is broken because it's an inline element in CSS by default. The lack of whitespace around its content is significant. That's how [whitespace-sensitive formatting](https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting) works. 

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UqADgVAATnDDkDkACgDZwCGAznOZFAGaYBOAW3IwAFixjkAnhACu5AO5zG6co0wBrTjAjl0cZvC7QYLMDFrkAPiP4sobRhM4BfF4Uqo2MftADmHpTkuNTkACTm-IwAdNym5tF8-N4A+lAsgq4uVDQRPjFxZjDRTqnpmeRuqAD03r5QARTBhDWkLdVYeCAANCAQxDCY0GzIoCz8vgr04wgjKCyMCixSI70ARnZgWjAAysRmmA3IPrJwvXCCa3Do+ugAMvZ+six+cABiEEISg0fzsjo9ECiGCCRgAdVEmHgbH2YDgO1mUJwUKkyHAbFWIEOHH4MHodj8ghYyB4Cw4vQAVmwAB4AIU22x2GTgd0OcBJZLOICp1J2hz8zAAirIIPAOYxySB9sk4Pw0Y9ZE45b1iPxDjAwZh0GJkAAOAAMKt8HDBdmIaNVcBx2HZvQAjiL4Pj+nMQOwALRQODXa6A-hwB0COD4l5E8WSjiCTDHfinXpsflCx3spCkiVc0xrTXa0TIABMvR8LEw6gaAGEIIIwygrQBWQGyDgAFRYazmacl2FOAEkoPpYDswGqBgBBPs7GBSZjhuBuIA)
```sh
--parser angular
```

**Input:**
```html
<div>
<p>
  {{ 'Please confirm that you would like to delete contact' | translate }}
  <strong
    >{{ $ctrl.contact.first_name }} {{ $ctrl.contact.last_name }}</strong
  >
</p>
</div>
```

**Output:**
```html
<div>
  <p>
    {{ "Please confirm that you would like to delete contact" | translate }}
    <strong
      >{{ $ctrl.contact.first_name }} {{ $ctrl.contact.last_name }}</strong
    >
  </p>
</div>

```
