### ISSUE TITLE
Platform: Beyond pretty-printing.

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#1020]
This may be a bit early but it would be awesome if we could explore an extension API for prettier. If the goal of prettier is to bring a consistent code style to JavaScript, then we shouldn't stop at what prettier does now. I strongly believe that a consistent code base written by a team significantly helps with how approachable it is. It should look like it was written by a single person and it goes beyond basic syntax. Prettier is well-situated to execute on this.

Here are a few concrete ideas of what I'd like to customize through plugins:
* sort-keys: on Jest, we use sort-keys to keep all object shapes consistent and alphabetically sorted. This cannot be a default because it may change the behavior of code with side-effects. In practice this has never been an issue for me but I don't think something like this would ever become a default. This is a good use case for a plugin.
* require/import/import type sort order. This is about grouping and printing beyond a single node. There are different preferences here and I see no reason why prettier should impose one over the others, another good use case for a plugin.
* convert function keyword to const/arrow-functions: I may want to pretty-print an older code base and update it to use arrow functions. A plugin could do this for me. As you can see, this actually takes prettier into an "automated-codemod" territory:
* React components as classes or functions: a plugin could convert all React class components that only have a render function into a stateless component.

Note, while this is very similar to configuration, I think it serves a different purpose: this isn't about making it possible to select any personal standard but rather to make the output of code stricter than what is currently provided by prettier. The idea is that running prettier without plugins on a codebase that uses prettier with plugins will have no (little) effect on the result.

**Comment by cpojer** [comment]
Thinking more about this, this could work with babel-plugin-like API that exposes recast/prettier's printing methods.

**Comment by vjeux** [comment]
Yes!

So, one the constraint that prettier has is that it does not transform the ast. It takes an ast and prints it in order to generate the same ast back. This part is really hard to write correctly.

What I want is to have a way to put ast transforms in front of prettier as plugins which look very similar to eslint plugins. Text -> ast -> sort-imports -> function-to-arrow -> prettier -> text. Writing ast codemods is really easy with tools like jscodeshift.

This way we concentrate the complexity in the prettier lib itself and can expose an easy plugin api for people that want to customize it.

**Comment by chrisui** [comment]
Think this is an awesome idea! Providing these plugins are enforced to be **pre** prettier (prettier^2 ???) it doesn't seem this goes against the original no-config goals of the project. I believe that is what @vjeux is implying so 👍 

Some more supportive examples off the top of my head:

- Ensuring props are typed and destructured consistently across all of our components.
- Run eslint --fix as a pre step? :thinking:

**Comment by kentcdodds** [comment]
> Run eslint --fix as a pre step? 🤔

There's `prettier-eslint`, (which ribs it as a post-step) but it'd be sweet to see whether there were a way to hook them up at the AST-level so we could avoid double-parsing :)

**Comment by mxstbr** [comment]
It'd be awesome if we could write a plugin to format `styled-components` CSS! (which are in a template literal and thus currently don't get touched at all)

**Comment by KyleAMathews** [comment]
Older discussion on plugin support for template literals https://github.com/prettier/prettier/issues/251

**Comment by hzoo** [comment]
> So, one the constraint that prettier has is that it does not transform the ast. It takes an ast and prints it in order to generate the same ast back. This part is really hard to write correctly.

Right this part is where jscodeshift/babel comes in because they are already made to do this exact use case. Babel already takes it any parser and outputs an AST and you can already use prettier as the printer for Babel itself as a config.

From that I don't see what really needs to be done then other than better integration; we have the tools to do the AST transforms and prettier is just a printer for the transforms? Correct me if I'm just thinking about this incorrectly but isn't this just about codemods but with prettier doing the output instead of recast?

**Comment by fkling** [comment]
^ This.

At least for jscodeshift, since the output of a transform is just a string, instead of doing

```
return something.print(...)
```

you could already do

```
return prettier(something.getAst()); // or similar
```

inside the transform.

---

But to take this further, the coding style is something that is specific to a project, not a transform. So Babel and jscodeshift should provide a way to specify a printer. I guess Babel already does that and jscodeshift needs to find a way to decouple printing from the transform.

**Comment by vjeux** [comment]
I would love for someone to use prettier as the end of an ast-based transformation pipeline! I'm going to close this issue as it's not very actionable but if someone is interested in working on this, that would be awesome!

**Comment by hzoo** [comment]
Yeah @fkling you just change the parserOpts.parser and generatorOpts.generator methods (a string or function) as described in https://babeljs.io/blog/2016/09/28/6.16.0#new-feature.

@eventualbuddha made https://github.com/square/babel-codemod already and it's easy to switch it out. https://github.com/square/babel-codemod/blob/ba6b8d7839e0005ce47089b597d807f487c89f64/src/TransformRunner.ts#L75-L107

**Comment by eventualbuddha** [comment]
I would entertain the idea of adding post-processing to babel-codemod so that prettier could be automatically applied to processed files, should anyone wish to submit a ticket at https://github.com/square/babel-codemod with a description of how it should work.

**Comment by kentcdodds** [comment]
Filed: https://github.com/square/babel-codemod/issues/20
