### ISSUE TITLE
scss mixin breaks on format if name is "selector"

### ISSUE THREAD

**Issue by DavidVollmers** [prettier/prettier#10291]
If a SCSS mixin is named "selector" (maybe other keywords also) and has a default value for a parameter, each format removes the last character of the default value.

**Prettier 2.2.1**

```sh
# Options:
--single-quote
--trailing-comma all
--no-semi
--print-width 120
```

**Input:**

```scss
@mixin selector($param: 'value') {
}
```

**Output:**

```scss
@mixin selector($param: 'value) {
}
```

**Expected behavior:**
Don't remove the last character of the default value...

**Comment by tpraxl** [comment]
Just FYI: There seems to be a workaround: Add a space between closing quote and closing parenthesis.

I started analyzing the bug with the following test:

```scss
@mixin selector($param: 'value') {
}
@mixin selector($param: 'value' ) {
}
@mixin selector($param: "value") {
}
@mixin selector( $param: "value" ) {
}
@mixin selector2($param: 'value') {
}
@mixin elector($param: 'value') {
}
```

Which resulted in the following transformations:

```scss
@mixin selector($param: 'value) {
}
@mixin selector($param: 'value') {
}
@mixin selector($param: "value) {
}
@mixin selector($param: "value") {
}
@mixin selector2($param: "value") {
}
@mixin elector($param: "value") {
}
```

Since I'm not used to this project, I couldn't find the proper location to fix the issue within reasonable time. So someone else has to fix this (or point me to the right direction).

**Comment by fisker** [comment]
Maybe here https://github.com/prettier/prettier/blob/7d84c0a5a419d7fa3e65407b03e0ea55f45c1182/src/language-css/printer-postcss.js#L491
