### ISSUE TITLE
Avoid last-argument-hugging for number-only arrays

### ISSUE THREAD

**Issue by stasm** [prettier/prettier#10515]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLKBnGBDWrvwAUA5tgLZwA0ABANoA6U11MATrhgGYStmG0BaAAwA6AOw1RAVkkBdAJSVGzVggAmcVgH1IAGx5w1Wtak6cArhjglycEQFkCm-LoAipi1ZqkKDuBgALfwYQMmgAazgATy1OXQJ6EFkaWgBGGnTqUQBmDIUlKAUAbhBKEAgABxhUaAxkUGxWVggAdwAFRoQ6lGxdFuwourKAI3YwSJgAZQrsMHRiZDZzKhA4MmHDDTUAGVxic2xiOAAxHjICaqgFnvMYCFKQAJgyXQB1ANR4DBmwOEmuz6oABunyiyHAGCGaEwmhgbXYxHOyE4vS8IAAVhgAB4AITGE0mtm26DgyNRK0xWMm810cAAiuYIPAybo0TNWFZWODhtgNroHhVmlZXuwKuDBf5NEDSWUAI6M+DwyrdEDYDACKBwQyGB6qeWoVTww5IpAo1krKxkVCLVjLMoYGn0hWk03kso4YavVBqGABZAAJnd7FQunmAGEIGQTasMFIHpY4AAVXndM1ooHLACSUA0sEmYFYqCqAEEc5MYFFaSy2YXYF6fX6kAAOIQAX1bQA)

```sh
--parser babel
```

**Input:**

```jsx
instantiate(game, [
  transform([-0.7, 0.5, 0]),
  render_colored_diffuse(game.MaterialDiffuse, game.Meshes["monkey_flat"], [1, 1, 0.3, 1]),
]);
```

**Output:**

```jsx
instantiate(game, [
  transform([-0.7, 0.5, 0]),
  render_colored_diffuse(game.MaterialDiffuse, game.Meshes["monkey_flat"], [
    1,
    1,
    0.3,
    1,
  ]),
]);
```

I'd like to suggest that Prettier prefer to break lines in outermost AST nodes. That is, if the line width requirement can be satisfied by breaking the the call to `render_colored_diffuse` above, I'd expect Prettier to not break the `[1, 1, 0.3, 1]` array which is just an argument to that call.

**Expected behavior:**
```jsx
instantiate(game, [
  transform([-0.7, 0.5, 0]),
  render_colored_diffuse(
    game.MaterialDiffuse,
    game.Meshes["monkey_flat"],
    [1, 1, 0.3, 1]
  ),
]);
```

**Comment by thorn0** [comment]
Formatting function calls without placing every argument on a separate line has a long tradition in JavaScript, and this was taken into account when Prettier was created. In Prettier's codebase, this style is called "hugging" because the call parentheses kind of hug the arguments instead of letting them go to own lines.

Your "expected behavior" shows how much we're used to this formatting. You didn't notice that if you indeed wanted to "break at the outermost AST node", you'd have this:

```js
instantiate(
  game,
  [
    transform([-0.7, 0.5, 0]),
    render_colored_diffuse(
      game.MaterialDiffuse,
      game.Meshes["monkey_flat"],
      [1, 1, 0.3, 1]
    ),
  ]
);
```

Prettier uses a series of empirically found heuristics to decide whether this formatting should be applied, and they work very well most of the time, but issues like this one show there is still room for improvement. Apparently, it's better to avoid the the last-argument-hugging formatting for number-only arrays.

**Comment by stasm** [comment]
These are some good point, thanks @thorn0. And thanks for the reference to _hugging_, I wasn't aware it was called that.

Perhaps the original title of the issue, in which I used the word _outermost_, was a bit misleading. If it's really _the outermost_, then as you rightly point out, some quite common calls would have to be formatted over multiple lines. I agree that it would likely be surprising to many users.

Without knowing how the formatting algorithm works, I imagined a potential solution could be to choose to break as shallow in the AST as possible, but not earlier. In my example, if breaking at the arguments to `instantiate` doesn't satisfy the line width requirement, maybe Prettier could undo that break and try to break at the arguments to `render_colored_diffuse` rather than going straight for the array argument?

Then again, I can see how that could lead to other potentially confusing scenarios. Improving the formatting for number-only arrays sounds like a great first step, and also one with a significantly smaller chance of breaking other people's habits :) Thanks for suggesting it!
