### ISSUE TITLE
Glimmer parser breaks numeric HTML entities

### ISSUE THREAD

**Issue by jpike88** [prettier/prettier#10542]
try formatting this:

```
<span class="stampFont" style="font-family: 'stampfont'">&#xf000;</span>
```

That entity is valid HTML and shouldn't be stripped... but it gets changed to this:

```
<span class="stampFont" style="font-family: 'stampfont'">
  
</span>
```

**Comment by thorn0** [comment]
On the playground, it can be seen that it comes already unescaped in the AST, so this should be fixed in the parser.

**Prettier pr-10290**
[Playground link](https://deploy-preview-10290--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwBkAxAB4BmADFQNyoD0WueIANCBJjAJbTrKjYAToIgB3AApCEfFNgA2o7AE8+bAEaDsYANZwYAZRxguUAObIYggK5w2cALZq4AE2cuAMrlNXspuADEIQXtsGG4zZBBsKxgIVhAACxh7OQB1BK54RjA4fWlMrgA3TKVIsHRVEBN0OEEYcU1TEOQyeRq2ACt0EgAhTR09fWx7OHcTOBa22xAukn0TUzk4AEUrCHhJuXaQHEEawUjFrnsRg7ZMQRMYVK5nGATkAA4Kc5Ea1M1MSIu4fcKJtgARzW8AaHBkUXQAFooHAXC54oI4MCuEiGr5mkhWltpjV7FwLNZcQslqt1hMsVM2DBsGobncHkgAEzUzRcOQLADCEBO2EivwArPErDUACq0mTY7aFGwASSgblg+jAl04AEEFfoYEolpsagBffVAA)

```sh
--parser glimmer
```

**Input:**

```hbs
<span>&#xf000;</span>
```

**Output:**

```hbs
<span></span>
```

**Comment by lifeart** [comment]
![image](https://user-images.githubusercontent.com/1360552/111172585-0091da00-85b7-11eb-896d-93712e2a409d.png)
https://astexplorer.net/#/gist/76b2a4b4311e55ff44090a546e821ff1/8665c9b878e4ed011f6fc4e533402569c737b29a

may be an parsing-time issue

**Comment by rwjblue** [comment]
The fix in `@glimmer/syntax` has been released in https://github.com/glimmerjs/glimmer-vm/releases/tag/v0.77.2.

**Comment by jpike88** [comment]
@thorn0 are we able to get a release out with the updated parser?

**Comment by thorn0** [comment]
Sure
