### ISSUE TITLE
Passing an AST as parameter to Prettier

### ISSUE THREAD

**Issue by wcastand** [prettier/prettier#1059]
Hi, 
Would it be possible to pass an AST to prettier ?

I like how prettier works but i prefer standard for personal reason (not here for a debate :))
At work, we use prettier and standard (depending on who make the project and work on it)
I have this idea of separating the representation of code from the code versioned on git. 

The idea is:

- I open a file on VSCode
- I format to an AST, store this AST somewhere
- pass it to whatever formatter i want (prettier or standard)
- show this in my editor (so i have the representation i like)
- when i hit save or close the file, is transform to an AST again
- check if this is the same AST
    - if not i save the AST with the formatter used on the project
    - if it's the same then i don't overwrite the file (to avoid git diff on untouched file after double formatting)

This way, everyone get his favorite representation and the project keep a consistent formatting at the end.

I think it could be done with the text, but we must format with prettier and then fix with standard or eslint and i'm not sure we can avoid the rewriting of the file every time we open it without the AST :/
Plus if convert the text into AST twice, which is not optimal.

Correct me if i'm wrong and if i missed something :)

And thanks for reading :)

**Comment by jlongster** [comment]
There is a `formatAST` option but I just realized it's under the ` __debug` internal API. Probably because we don't officially support it yet because there are a few places we inspect the original source, so we need to change all those places to handle the case where the original source doesn't exist.

We do several things like keep the blank lines from the original source. This lets you group code how you want and prettier will maintain that grouping. If you're just formatting an AST, we don't have this info so code won't be grouped (will be collapsed together). We could try to implement some logic for where to put blank lines, but you probably won't be very happy with it. If you go the AST approach though, that's the only option.

**Comment by wcastand** [comment]
Ok, thanks for the answer.

I think i'll try to use the source for now, i discussed with a friend and we think we can use the source without messing with the git diff :-) 

I'll close this for now, thanks :)
