### ISSUE TITLE
Formatting of TypeScript class with extends and implements not not matching snapshot tests

### ISSUE THREAD

**Issue by francium** [prettier/prettier#10664]
**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwtDAE7pgwDKcqcVAltAOqMAmA5nDDnAB7wo7XACU4lGADoSAWwAO0BDAA8ANwgcANDnzFSFKrXpNWHbjAAKZCPMwAVAvLg6NHAHw5GC+rOW5qCD8YAAtGKE4AGXQybhxgAB0oXWCQiHYACgBKeIBfJPyoJLAMbBwAEUZMeQwCAHkAIwArBhgARiTdASERHABXGEZUTCkAUTVlUdlGGHgyTq8fOD9YXHC5yWYoAH0ASVg4Q0GJ+xiLeIKk4tLcSuraxpaqACY+QQRegaGR8cnp2cOC28NWW-i8ByOWz2EM2JzOPAuUEK1ywtyqNXQ9WarQAzG8ergvsMxhNYFMZnMgUsVjA1jDTDt9hsmHDYjwtAtdJggjwwhFRsM4NtAn46qFDvY+ZwOcldDhualwpwBZg4ABBTjocLbUR9KBQJV1AZ1ABmADl0H5cIkkVcoCVURV0Q9sVQACz4j6EwbE35k-5zRYgml05mDaDQsOMVnnYCFB1lcTodjoBr0T3CXBwUm0kl-CmHIO+MFm9JwABS1B1EhTabg1HIElkeRRZX2eGWEDIBDV8mcwkL3S9OFQEE4bqa6DUWDAZEY8mkvf77ELwOLqxwuyIlBCcHYkTHHew6G41ggag4hbjdoTuAAYhAIBnertZLIBqn6FJxJAyJkbbo87JuwZBwNgSA4AA5JBMq5DkAFePIwGgeB8rkEqADclxFFAAiKGQvC3jgABqVT2N4dDhHAciKLhsBXIM1JgmqJpzKRcAAO77DMOh1FARAhOgERgbxUDlGB5AQAQiKFHhXaETcJFkRRqBUTRSiwM8DFrqCG4sWxjCcdxMCiQJQncJgoniZgkkEDoarCCKvJKkmqCoAQrnuQeEQySAWggLY4ZQJgyCgDENgcZYMQICFKDoKgHGYiF-kNIYADWPDUEhYBKsg5B9C4IDLA0e4rvu5l9CecAPmQsjoLMuVxQMEB+SAIQwLIqAsGE8DVJQ9YxTM0YzAQyDgNgrXhKqBHWCedXICa8Wqv5TSYPwABC6WZZacCRFRC1LYVq38NQSr0AAin0EDwAdgr+UhZDTWNMBOGBs7zjArXyHOsBsOwoTIAAHAADPdNiqiwFDyGN31gYcEytQAjld8BnnYY1YAAtLhe57q1oHI4woGzZw81IItd0gKq0x5WQBX+ZgZ1wJd11wLdy0gDAqZ-QDSDPP55BaqpERyGTRWYAArK1fSqqcDSxRTHNqAV+wrrA1DvQuDnsA2BD0OzcC5LkQA)

**Input:**
Taken from https://github.com/prettier/prettier/blob/main/tests/typescript/classes/__snapshots__/jsfmt.spec.js.snap#L9

```typescript
class MyContractSelectionWidget extends React.Component<void,  MyContractSelectionWidgetPropsType, void> implements SomethingLarge {
  method() {}
}
```

**Output (test snapshot):**
https://github.com/prettier/prettier/blob/main/tests/typescript/classes/__snapshots__/jsfmt.spec.js.snap#L46

```typescript
class MyContractSelectionWidget
  extends React.Component<void, MyContractSelectionWidgetPropsType, void>
  implements SomethingLarge
{
  method() {}
}
```

**Output (test playground):**

```typescript
class MyContractSelectionWidget
  extends React.Component<void, MyContractSelectionWidgetPropsType, void>
  implements SomethingLarge {
  method() {}
}
```

**Expected behavior:**
The formatting of the snapshot and the playground are different. What's the reasoning behind this?
The change was made in [this PR](https://github.com/prettier/prettier/pull/10085/files), but I can't get Prettier to format my code like this when I run it through playground or locally

**Comment by fisker** [comment]
Because #10085 is not released yet.

You can try [playground with that change](https://deploy-preview-10085--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwtDAE7pgwDKcqcVAltAOqMAmA5nDDnAB7wo7XACU4lGADoSAWwAO0BDAA8ANwgcANDnzFSFKrXpNWHbjAAKZCPMwAVAvLg6NHAHw5GC+rOW5qCD8YAAtGKE4AGXQybhxgAB0oXWCQiHYACgBKeIBfJPyoJLAMbBwAEUZMeQwCAHkAIwArBhgARiTdASERHABXGEZUTCkAUTVlUdlGGHgyTq8fOD9YXHC5yWYoAH0ASVg4Q0GJ+xiLeIKk4tLcSuraxpaqACY+QQRegaGR8cnp2cOC28NWW-i8ByOWz2EM2JzOPAuUEK1ywtyqNXQ9WarQAzG8ergvsMxhNYFMZnMgUsVjA1jDTDt9hsmHDYjwtAtdJggjwwhFRsM4NtAn46qFDvY+ZwOcldDhualwpwBZg4ABBTjocLbUR9KBQJV1AZ1ABmADl0H5cIkkVcoCVURV0Q9sVQACz4j6EwbE35k-5zRYgml05mDaDQsOMVnnYCFB1lcTodjoBr0T3CXBwUm0kl-CmHIO+MFm9JwABS1B1EhTabg1HIElkeRRZX2eGWEDIBDV8mcwkL3S9OFQEE4bqa6DUWDAZEY8mkvf77ELwOLqxwuyIlBCcHYkTHHew6G41ggag4hbjdoTuAAYhAIBnertZLIBqn6FJxJAyJkbbo87JuwZBwNgSA4AA5JBMq5DkAFePIwGgeB8rkEqADclxFFAAiKGQvC3jgABqVT2N4dDhHAciKLhsBXIM1JgmqJpzKRcAAO77DMOh1FARAhOgERgbxUDlGB5AQAQiKFHhXaETcJFkRRqBUTRSiwM8DFrqCG4sWxjCcdxMCiQJQncJgoniZgkkEDoarCCKvJKkmqCoAQrnuQeEQySAWggLY4ZQJgyCgDENgcZYMQICFKDoKgHGYiF-kNIYADWPDUEhYBKsg5B9C4IDLA0e4rvu5l9CecAPmQsjoLMuVxQMEB+SAIQwLIqAsGE8DVJQ9YxTM0YzAQyDgNgrXhKqBHWCedXICa8Wqv5TSYPwABC6WZZacCRFRC1LYVq38NQSr0AAin0EDwAdgr+UhZDTWNMBOGBs7zjArXyHOsBsOwoTIAAHAADPdNiqiwFDyGN31gYcEytQAjld8BnnYY1YAAtLhe57q1oHI4woGzZw81IItd0gKq0x5WQBX+ZgZ1wJd11wLdy0gDAqZ-QDSDPP55BaqpERyGTRWYAArK1fSqqcDSxRTHNqAV+wrrA1DvQuDnsA2BD0OzcC5LkQA)
