### ISSUE TITLE
MDX Comments don't seem to work

### ISSUE THREAD

**Issue by jeffreymeng** [prettier/prettier#10706]
It seems like prettier isn't parsing MDX comments properly (instead, it seems to parse the `*This is a comment*` part separately as italicized text.

(This isn't a spec, but here's where it seems to say that this type of comment should be supported: https://github.com/mdx-js/mdx/issues/1042)

**Prettier 2.2.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABACTgGxxAGnQHUIAnHAEwEIAdKdde4AegCoAVACwEsBndP3QBDdJAC24hDHRsWAXxAEQEAA4we0PslDCyZCAHcACnoTaUwnIeEBPbcoBGZYWADWcGAGVVrnlABzZBgyAFc4ZThxRzhKSliAGWFA0OEAuAAxcnFhGA1A5BBhUJgIJRAuGHEcYl54Pl8wOC9zHg0ANzbbQrA+BxB-PjgyGGMXAJzkADMrIeUAKz4ADwAhF3dPL2EpBP84admIkEWlr38AnDgARVCIeAOcOZBfMiGyQvFKJfLVMn8YYg8SgwLjIAAcAAZlL8IENiC5VIVfnA3u19soAI63eBjNQWIp8AC0UDgsVi5TIcCxPEpYzSkyQM0eRyG4h4wTCLPOlxud32jMOyhgwkcgOBoKQACYhS4eDhzgBhCCSYSFFEAVnKoSGHBFFiZT3a4QAklB4rAvGA-uoAIJmrwwWyXB5DeTyIA)

```sh
--parser mdx
```

**Input:**

```mdx
# Hello, World!
  
{/*This is a comment */}
```

**Output:**

```mdx
# Hello, World!

{/_This is a comment _/}

```

**Expected behavior:**
Input should already be properly formatted, and should not be modified.

**Comment by thorn0** [comment]
Tried your example on the MDX playground https://mdxjs.com/playground and it's rendered as italics there, but it might be using an older version of MDX.

**Comment by jeffreymeng** [comment]
Hmm that's interesting. The syntax highlighting on the playground also grays out the source code, as if it was a comment.

**Comment by thecodingwizard** [comment]
[xdm](https://github.com/wooorm/xdm) treats `{/* */}` as a comment. I believe mdx v2 will also treat `{/* */}` as a comment (the playground may run on MDX v1, which might not consider that as a comment).

Also, it seems unlikely that anybody would actually write `{/* ... */}` with the intention of italicizing the text :P

**Comment by kentcdodds** [comment]
Another use case for this: https://github.com/wooorm/xdm/issues/61

**Comment by ericclemmons** [comment]
For others blocked by this, you can use `{/** ... **/}` 🙏

**Comment by kentcdodds** [comment]
> For others blocked by this, you can use `{/** ... **/}` 🙏

Thanks for chiming in @ericclemmons. Unfortunately [that workaround doesn't work for me](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwD0AqDACADgJzhhgEs58BaEgcygkOyzQF8AdKAAy4CsBndyFF4xsAQ2wBebADNRAG15wB0YdgBGkmfMXKhIsJpj4ArkqiDVAE03iAZLfXYAPk+xh2XDuxAAaEBFxSFWRQUXx8CAB3AAUwhF5kEFEANwgSS18QNXxRMABrIgBlXFySKGpkWQU4PzgAWzU4S0smgBlRcuNRajgAMXo60WIyipRRYxgITIALGDq5AHVpknheErA4QviVkmSVgE9EsF4EvzLFfBhonOpByu0akD4ADwAhHPyi0Tq4VrK4e7VPwvQojORwACKxgg8EBij8JXwF0Sg3weUsUSgmQIZRgC3SMGmyAAHAAGBERRQLHK4RLySKifanEAAR2h8GuAQSY14FCgcCaTUyhDZJEI126dyQVXhIEUdRIcMevDBkPZAKQRlMfhgojU+MshOQACYdTkSHIRgBhCB1KVJORyTLGRQAFT13Jlj2SpgAklAWrBCmB8CRAgBBAOFGD7cFK5jMIA).

**Comment by kimbaudi** [comment]
@jeffreymeng - as @thecodingwizard already pointed out, the MDX playground is running on MDX v1. You can check this yourself by entering HTML comments (i.e., `<!--hello-->`) into the playground and the mdx compiler will treat it as a comment. Since MDX v2 doesn't support HTML comments, it would treat the HTML comment as invalid JSX and throw an error like the following:

```shell
Unexpected character `!` (U+0021) before name, expected a character that can start a name, such as a letter, `$`, or `_` (note: to create a comment in MDX, use `{/* text */}`)
```

Although it seems like MDX comments are not working in the playground, I think it is working as expected

**Comment by kimbaudi** [comment]
although xdm and mdx v2 treats `{/* */}` as a jsx comment, mdx v1 and md does not. also, prettier is merely formatting **bold** and _italic_ text in markdown by simply replacing `__bold__` with `**bold**` and `*italic*` with `_italic_`. This is why prettier changes `{/*comment*/}` to `{/_comment_/}` and also changes `{/__comment__/}` to `{/**comment**/}`. see [prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBJABAKwK4GcboA2EAbnOgPoUBGEhAJuvAB4xUB0AOlN6jAIaEAlmCEAvOIxYEhuJgAtyAKjD8YAcjkBbOBADuSrjyjAA9CohadsAIxLTAX27czVSFYQwATFUfcQADQgEAAOMELQuMig-ABOsfoACnEIUSiCevwAnlFB1LH8YADWcDAAyiGFQlAA5sgwsdhwQXBa1JL0kgAy-LXY-DVwAGIQsVpq4bXIIPzYMBCBIPIwWoQA6vJC8LiVYHBlqVtCJFtZ02C4uSDVuHCxMIkFNePIAGaCt0GYuMwAQgXFUplfg6LrVOBvD7NEDfZhlao1QhwACK2Ag8EhhE+IEqsVusWmWnozEWIVi1RgayE9Bg8mQAA4AAxBMkQW5rAohaZkuD4siLACOaPgj1CaRmuAAtFA4JJJItYnAhUJFY8Bi8kO8sdDblohPVGjqEUjUeiIZqoUEBNQqTS6UgvFaCkJhLUAMKWDUgXkAVkWeDgABV+NQ0lrsSQmqgoJ1YGUwOSwgBBGNlGBZJGY24OBxAA).

If/when mdx v2 gets finalized and released, prettier will need to treat `{/* */}` as a jsx comment, but in the meantime this is expected behavior and the `{/** ... **/}` workaround would have to do.

**Comment by pomber** [comment]
This now works (Prettier v2.5.0):

~~~md
{/* prettier-ignore */}
```js
console.log("no" 
	+ " " 
	+ "touching")
```
~~~
[Prettier Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKBiABACTgG3wnXWAHoAqLABwCc4YYBLOWgWiYHMoJ6sKyAX3QADMQCsAzukhRJEfHAB0RTgApUIHpqwkYAal0gjuqKgNGYEAK5gAFkyidNASlFiQAGhARqzaJLIoACGtLQQAO4ACqEIgSjB+BHBAJ6B3gBGtMFgANYMAMrBALZwADKOcMgAZomScJnZeYXUOY6cyDC01g0gcMUZcAAmQ8NlwU7WwZxwAGK8xcGM7cggwdZWXiB2MMX4AOoO8JKtYHAFcUzMAG5XKatgkukgjvW0MFHZnIs1db1SAA8Cu1FABFawQeC-fD1bytWhvVbFIYArZ0RwwfZMIYwOzIAAcAAY4eF6vtstRVnQ4G9rlVvABHCHwT6+eJrSRsKBwYbDLb0JlMeifaY-JC1GG9erFJidbpSkFwcGQqriv7eGDBDJYnF4pAAJg12SY+HaAGEIMUxX1JABWLbWeoAFS18QlsJA1x6AEkoKNYAUwLQmH4AIJ+gowFKKaH1QSCIA)

**Comment by alexander-akait** [comment]
Solved, feel free to feedback
