### ISSUE TITLE
Provide way to use single quotes in jsx

### ISSUE THREAD

**Issue by trotzig** [prettier/prettier#1080]
I read [this comment](https://github.com/prettier/prettier/issues/73#issuecomment-271953751) saying that "I've never seen anyone write `<div className='a' />`". Well, here's someone 👋 

The same way `trailingComma` accepts a string, we could let `singleQuote` do as well. 
- `'all'` would use single quotes in js as well as jsx
- `'js'` (or `true`) would use single quotes in js but not in jsx
- `'jsx'` would use single quotes in jsx but not in js

**Comment by Pajn** [comment]
Here's someone else!
We currently use tslint with auto fixes which also changes all `"` in jsx to `'` so I guess people which use singlequotes and tslint is used to them in jsx too.

**Comment by trotzig** [comment]
@Pajn Seems fitting that we're both from Sweden, the [land of single households](http://sverigesradio.se/sida/artikel.aspx?programid=2054&artikel=5722944) 🇸🇪

**Comment by iansinnott** [comment]
Same here! I actually thought it was some sort of config mistake on my end when I saw it replace single quotes with double quotes.

**Comment by jlongster** [comment]
We really, really don't want to add any more configuration options. Ideally when commas at the end of function parameter lists we can deprecate the options to trailing comma and just accept a single `--trailing-comma` option. The only reason we can't right now is because function arg trailing commas aren't valid JS, but people can use them with a babel transform.

I think the only option here is to decide if JSX should respect the quote option or not. This is the first I've heard someone complain about it which makes me think you're a small minority (sorry!). I think makes sense the way we currently do it since using double-quotes is a very strong style with HTML an that's why JSX applies the same practice.

It's worth having the discussion though. What do you think @rattrayalex and anyone else?

**Comment by trotzig** [comment]
I understand and support the desire to keep configuration options down. I was actually surprised to see `singleQuote` as an option when I first started using the tool, I thought the majority had switched over to single quotes already.

I could see a solution where we just keep whatever quotes are used in jsx. I don't know how well that rhymes with the philosophy of prettier however.

**Comment by rattrayalex** [comment]
My impression is JSX style strongly encourages double-quotes; @trotzig I'm curious why you prefer single-quotes for JSX? Could double-quotes be acceptable?

**Comment by trotzig** [comment]
Hi @rattrayalex! 

Double quotes are definitely acceptable. It's a style thing we started doing a few years back, and I don't have strong feelings for or against it. I guess you could argue that single quotes makes it more obvious that we're not technically dealing with raw html (must use `className` instead of `class` etc). But yeah, we could fall into the mainstream here without much pain.

**Comment by jlongster** [comment]
I always feel bad saying no but I think it's good for the long-term health of the project. Thanks for being open to changing your style! It would be really easy for our config to get really complicated if we catered to a lot of the existing styles. I think it's going to be really valuable for the JS community if a large portion of the styles are decided on.

**Comment by joshma** [comment]
Hm I know you just closed this, but I wanted to make a push for consistency - for the same reason that `--single-quote` is a flag, someone who uses single quotes as a stylistic choice would want to use that for JSX as well. (That's certainly the case for us - we just see JSX as a nice wrapper around `React.createElement`.)

Can we consider having the JSX behavior match non-JSX behavior?

**Comment by rattrayalex** [comment]
@joshma I think most requests for options need a pretty strong use case at this point. Pure style preference usually isn't enough; part of the goal of the project is to rally the community around a single "style preference" (which, of course, nobody will be perfectly happy with – including the project maintainers). 

Would the status quo be usable for your team, or a blocker from using prettier?

**Comment by joshma** [comment]
@rattrayalex just to be clear, I'm not requesting another option, just that the JSX behavior matches the existing `--single-quote` option. (My claim is that most people are consistent between JSX and non-JSX code, although that could be wrong.)

It'd be a blocker somewhat, in the sense that I wouldn't switch our team over 😛 . I want to introduce prettier to reduce style discussions and encourage consistency, but in doing so we'd have to either convert our entire codebase (and in some sense create a lot of discussion) or accept inconsistency between "prettier" code and legacy code (which seems worse than what we have now).

FWIW, I totally accept that this project is allowed to make its own opinions on what's valuable for the JS community, but the value to my team is consistency in *some* style, not consistency in following a global style. And I think that's doable with the community at large also - you use whatever prettier config the codebase you're contributing to uses, and that's that.

Maybe we'll drift towards prettier's default config over time, but it seems better to gradually change things.

**Comment by rattrayalex** [comment]
Hmm, interesting. Thanks for sharing @joshma !

> most people are consistent between JSX and non-JSX code, although that could be wrong.

that's not what I've seen – which is a strong majority using the recommended `"` in JSX, despite many using `'` elsewhere – but part of what makes this hard is that there isn't data anywhere, and everyone has different experiences 😕

**Comment by joshma** [comment]
Interesting, it that just so it matches common HTML style?

**Comment by rattrayalex** [comment]
It may also be because you can't escape a quote within JSX:
http://eslint.org/docs/rules/jsx-quotes

but, yes, I think the typical answer is that: https://github.com/airbnb/javascript/tree/master/react#quotes

>  Regular HTML attributes also typically use double quotes instead of single, so JSX attributes mirror this convention.

This question, like most others of similar import, is not without its controversy: https://github.com/airbnb/javascript/issues/269#issuecomment-134990455  and https://github.com/airbnb/javascript/issues/629

**Comment by iansinnott** [comment]
Totally agree maintainers can do what they think is best. 

I would just point out that @joshma is definitely not alone. This is also the reason my team uses single quote everywhere: consistency. In our case it's also simpler to tell new team members "single quote everywhere" rather than "single quote everywhere _**except**_ JSX".

**Comment by lydell** [comment]
It's the simplest to tell new team members that they don't need to care about which quotes they type. prettier takes care of it ;)

**Comment by iansinnott** [comment]
Fair point @lydell

**Comment by audiolion** [comment]
I ran into this today, I thought it was a bug in prettier because I had set `singleQuote: true` and then arrived at this thread. I think it the comments for single quote in default settings should specific you only apply the option to `.js` and not `.jsx` if you are going to enforce this.

For me I can use prettier, and run `eslint assets --ext .jsx --fix` to convert all the double quotes prettier puts in back to single quotes, but I believe that either the docs or your idea is wrong in that

```
// If true, will use single instead of double quotes
"singleQuote": true,
```

should do what it says on the tin, and not have an undocumented exception for jsx

**Comment by rattrayalex** [comment]
@audiolion that makes sense! Care to submit a PR?

**Comment by audiolion** [comment]
Sure, wont be till Monday with Easter tomorrow, cheers!

**Comment by jamesgpearce** [comment]
A big +1 for single quotes in JSX - or rather, a consistent application of the flag. It seems strange to that people would prefer one in JSX and the other in JS.

FWIW, in Babel, the transformed code appears to result in single quotes regardless:

```
import React from 'react';
const foo = (<Foo prop1="double" prop2='single' />);
```

becomes

```
import React from 'react';
const foo = React.createElement(Foo, { prop1: 'double', prop2: 'single' });
```

;)

**Comment by audiolion** [comment]
Oh man, I completely forgot about this! I will get this PR up today

**Comment by shinzui** [comment]
@audiolion are you still planning a PR?

**Comment by audiolion** [comment]
Hah, yes, I am so sorry this keeps slipping my mind, it is on my Trello board now

**Comment by lipis** [comment]
Where do we raise the voice for the `singleQuote` for all (js, jsx) or at least have that option #1084?!

**Comment by audiolion** [comment]
I think the discussion here indicates that they want to force a style on the entire community to get codebases mostly uniform, and less config options is better. I found that I can run prettier and then afterwards run `eslint <dir> --ext .jsx --fix` and my eslint rules will replace all double quotes with single quotes that prettier adds. It isn't perfect but I think if you are in the minority and want this functionality, you need to have your own post-processor as Henrik's fantastic PR didn't make it in.

**Comment by lydell** [comment]
@audiolion See also [prettier-eslint](https://github.com/kentcdodds/prettier-eslint).

**Comment by shinzui** [comment]
@lydell, @audiolion  `prettier-eslint` is unfortunately really slow if you want to run it every time you save a file. It would be great if it's supported directly by prettier.

**Comment by audiolion** [comment]
My suggestion is run it once before you commit your files so it passes linting

**Comment by kshestakov** [comment]
I also want to place a link to gaearon's (Redux creator) comment about single and double quotes in .jsx:
https://github.com/airbnb/javascript/issues/269#issuecomment-134990455

**Comment by levithomason** [comment]
Please reconsider allowing consistency.  Why?

- This issue has `21` 👍  and `0` 👎  reactions
- No new options are being proposed
- Consistency, JSX is written in JS
- The overwhelming majority of reactions to comments on all issues where this is discussed is to support single quotes and maintain JSX/JS consistency
- There are notable real world projects that use consistent JS/JSX quotes, like [Semantic UI React](https://github.com/Semantic-Org/Semantic-UI-React)
- There are other issues for this, such as #656
- It has confused many that `prettier` prints certain lines and columns of JS/JSX files differently with `--single-quote`: `<User bar="baz" rab={'zab?'} />`

Comments and support for this since have been largely dismissed as far back as https://github.com/prettier/prettier/issues/73#issuecomment-272014988, however, I see very few who agree that `--single-quote` should behave differently between JSX and JS.

Regarding:
>This is the first I've heard someone complain about it which makes me think you're a small minority (sorry!)

Though there were already 3 individuals in support when this comment was made, there are now within this issue alone:
- `@trotzig`
- `@Pajn`
- `@iansinnott`
- `@joshma`
- `@audiolion`
- `@jamesgpearce`
- `@shinzui`
- `@kshestakov`
- `@lipis`
- `@levithomason`

`@gaearon` is one of the most influential and respected in the React community.  Though he has spoken his peace and given up the bikeshedding, he had made good arguments for single quotes [here](https://github.com/airbnb/javascript/issues/269#issuecomment-134990455) and [here](https://github.com/airbnb/javascript/issues/269#issuecomment-135201861).  Again community reactions were 100% in favor, `18` total 👍 `0` 👎 .  He links several React issues supporting his statement:
>I always liked using single quotes in JSX precisely to highlight this isn't HTML.

***

My peace is spoken, would love to have more consistent and community accepted `--single-quote` behavior.  In either case, long live `prettier`.

**Comment by dzearing** [comment]
FWIW, maybe this will help give some additional understanding on why people might use single quotes in JSX. In [office-ui-fabric-react](https://github.com/officedev/office-ui-fabric-react) we are using single quotes everywhere, and this has been an issue in consuming prettier. In our line of thinking, the context difference is not a good enough reason to special case usage.

This seems completely inconsistent. It's all JavaScript. We aren't in HTML. Why suddenly abandon conventions because we're in jsx? It's just confusing and adds more mental cycles.

```jsx
<div 
  className={ 'class name inside of squigglies should be single quoted' } 
  bar="attribute value should be... double... unless you need to concat something, then switch back"
/>
```

We had a similar conversation about spaces in between curly brackets. Most of the community would accept this:

```ts
import { Foo } from 'bar';
const thing = { foo: 'bar' };
```

But then most JSX out there abandons the spacing for some reason, probably to reduce the line lengths:

```tsx
<div className={foo} />
```

Similar convention would be in back-tick strings:

```tsx
const name = `My name is ${displayName}.`;
```

So... why deviate in specific contexts? It makes the rules complicated and special cased. If you pick one or the other and stick with it, there are less special cases to explain. If you like shorter line lengths, no spaces inside curlies anywhere. 

Likewise, if you like single quotes, use them everywhere (assuming you're still in JavaScript and not writing JSON or HTML which changes the entire styling context.)

I love prettier because it can ensure whatever rule is picked is what is checked in. I don't really have an issue with adding config settings, as long as the default are generally what's accepted.

But the current design making the quotes configurable, while in the context of jsx not configurable, is an unpredictable halfway design that creates confusion and frustration. Pick single quotes or double quotes everywhere, or don't let it be configurable at all. Pick spaces or no spaces, or don't let it be configurable at all. 

Or, make everything configurable (like estlint / tslint / vscode formatting), complete with contextual scenarios (`jsxSingleQuotes`, `backTickSpacesInsideCurlies`), make the defaults echo the general community direction (path of least resistance becomes the default approach), and make everyone happy, even the odd person out that has some alternative insight on the problem space.

**Comment by rattrayalex** [comment]
The :+1:/:-1: ratio here is compelling to me, along with the statements from `@gaearon` and others whose work I respect. There's also already a flag for quotes (we just need to add another option to it, which in this case would not be very expensive to implement). So I will reopen this issue and mark it as seeking PR's. 

I will leave it up to other maintainers (probably @vjeux ) to decide whether to merge a PR, and I hope that the community will understand if the choice is to not merge. 

If that occurs, I would urge you to either: 

1) Use `double` if you just want consistency between js and jsx.
2) Use eslint (eg; via https://github.com/prettier/prettier-eslint) to override prettier where you disagree with it.
3) Give in 😜 

There isn't much more to be said on the topic and it seems this is going in loops, so I will close this issue to comments. Feel free to message me privately if you think this is in error.

**Comment by josephfrazier** [comment]
For reference, there's some more discussion on this in https://github.com/prettier/prettier/issues/3437

**Comment by j-f1** [comment]
How about printing single quotes in JSX and JS if `singleQuote` is `true`, printing single quotes in JS but not JSX if `singleQuote` is `"js"`, printing single quotes in JSX but not JS if `singleQuote` is `"jsx"`, and not printing single quotes if `singleQuote` is `false` (strings containing single/double quotes will continue to avoid escapes)?

**Comment by suchipi** [comment]
@j-f1 if we choose to extend that option for this (which is still somewhat up in the air), then that implementation sounds fine to me.

Also, for reference, @duailibe raises an important point here that could affect implementation details and/or decision(s): https://github.com/prettier/prettier/issues/3437#issuecomment-351209905

**Comment by j-f1** [comment]
Should this issue be unlocked to allow people to 👍?

**Comment by j-f1** [comment]
Unlocking :key: to allow people to :+1:/:-1:.

**Please don’t comment unless you have something to add that hasn’t already been said, and please don’t comment** +1 **or** 👍 **and instead use the 👍 reaction button to indicate your support.**

**Comment by ljharb** [comment]
@j-f1 to clarify, we should react to which comment, exactly? The OP?

**Comment by karlwilbur** [comment]
The [Rational](https://prettier.io/docs/en/rationale.html) clearly says:
> JSX always uses double quotes. JSX takes its roots from HTML, where the dominant use of quotes for attributes is double quotes. Browser developer tools also follow this convention by always displaying HTML with double quotes, even if the source code uses single quotes.

However, the (X)HTML/SGML standard(s), as long as I have been writing HTML (over 20 years) have been to allow both single and double quotes for attributes.

## HTML5
* https://www.w3.org/TR/2012/WD-html-markup-20120320/syntax.html#syntax-attributes
* https://www.w3.org/TR/2011/WD-html5-20110113/tokenization.html#attribute-value-double-quoted-state

## HTML 4
* https://www.w3.org/TR/html4/intro/sgmltut.html#attributes

## HTML 3.2
* https://www.w3.org/TR/2018/SPSD-html32-20180315/

The "convention" has *always* been to allow both. That someone *feels* that one is preferred over the other is completely arbitrary. There are reasons to use one over the other and *both* are valid.

The statement that "dominant use of quotes for attributes is double quotes" seems to be entirely untrue. There is no evidence at all to support that claim. From my own personal experience, I always use single quotes for strings unless there is a reason to use double quotes, this includes HTML attributes. I know that most of my peers also use the same convention. Clearly **actual** HTML standards should drive specification, not someone's **feeling** that something is "dominant" or "typical", and certainly when there is no evidence to support such a claim of dominance.

I am adding this comment because no one has mention that supporting both is the **actual HTML standard**.

**Comment by ljharb** [comment]
A dominant convention is a defacto standard.

**Comment by smirea** [comment]
bump.
i know there's a comment above saying not to +1, but the original comment has 62 👍 already and this issue has been stale for a month now

**Comment by j-f1** [comment]
@smirea Feel free to open a PR! (Perhaps [my suggestion](https://github.com/prettier/prettier/issues/1080#issuecomment-378567278) would make a good starting point?)

**Comment by smirea** [comment]
sure thing! I thought there already was a PR for this but I guess I miss-remembered

@j-f1 [this is a working proof of concept based on your suggestion](https://github.com/smirea/prettier/commit/d1fa72e3a240d9e78e7e3e73c930e545bbbb0335), seems pretty straightforward but want to make sure I'm not overlooking something

```bash
cat <<CODE > /tmp/test-prettier.js && echo '------' && ./bin/prettier.js /tmp/test-prettier.js --single-quote=all
const a = 'foo';
const b = 'bar\nbar';

const jsx = (
  <div style='color:red' this-should='stay the same'>
    some quotes "that should not" change
  </div>
);
CODE
```

if it looks good I can go ahead and write some tests and open a PR

**Comment by j-f1** [comment]
That looks great!

**Comment by bovas85** [comment]
Anyone here can review/approve that PR please?

**Comment by konpikwastaken** [comment]
Gentle ping to maintainer on this PR - can anyone take a look?

**Comment by trotzig** [comment]
@konpikwastaken I opened this PR over a year ago and have since moved on to using double quotes. I have no desire to pick it up.

**Comment by bovas85** [comment]
well we can't really approve this, but someone should.

If you are not drowning, it doesn't mean everyone else isn't.
