### ISSUE TITLE
Weird object lookup formatting on long line

### ISSUE THREAD

**Issue by jonathanglasmeyer** [prettier/prettier#1083]
Minimal:
```diff
- o['foooooooooooooooooo'] = 'baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar'
+ o[
+  "foooooooooooooooooo"
+ ] = "baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar";
```
[Repro](https://prettier.github.io/prettier/#%7B%22content%22%3A%22o%5B'foooooooooooooooooo'%5D%20%3D%20'baaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaar'%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

I found this approach strange in the following real world example:
```diff
- testGroups.reduce(
-   (o, testGroup): Object => {
-     o[`${baseScript}:${testGroup}`] = `npm run ${baseScript} -- --group ${testGroup}`;
-     return o;
-   },
-   {},
- );
+ testGroups.reduce(
+   (o, testGroup): Object => {
+     o[
+       `${baseScript}:${testGroup}`
+     ] = `npm run ${baseScript} -- --group ${testGroup}`;
+     return o;
+   },
+   {}
+ );
```

[Repro](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20generateGroupTestScripts%20%3D%20(baseScript)%20%3D%3E%5Cn%20%20testGroups.reduce(%5Cn%20%20%20%20(o%2C%20testGroup)%3A%20Object%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20o%5B%60%24%7BbaseScript%7D%3A%24%7BtestGroup%7D%60%5D%20%3D%20%60npm%20run%20%24%7BbaseScript%7D%20--%20--group%20%24%7BtestGroup%7D%60%3B%5Cn%20%20%20%20%20%20return%20o%3B%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%7D%2C%5Cn%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D)

The line with the object lookup exceeds 80 chars, so its split up -- i just find the decision to split up lines in the object lookup less readable then splitting after the `=`. Is there a specific rationale for this?

**Comment by vjeux** [comment]
Right now prettier isn't able to print the following form:

```js
variable =
  `template`;
```

So the only thing it can do is to break on `[]`. We may want to teach it this form.

**Comment by jonathanewerner** [comment]
Are you saying that this depends on the template string? Because the break on `[]` is [happening with a normal string as well](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20generateGroupTestScripts%20%3D%20(baseScript)%20%3D%3E%5Cn%20%20testGroups.reduce(%5Cn%20%20%20%20(o%2C%20testGroup)%3A%20Object%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20o%5B%60%24%7BbaseScript%7D%3A%24%7BtestGroup%7D%60%5D%20%3D%20'npm%20run%20%24%7BbaseScript%7D%20--%20--group%20%24%7BtestGroup%7D'%3B%5Cn%20%20%20%20%20%20return%20o%3B%5Cn%20%20%20%20%7D%2C%5Cn%20%20%20%20%7B%7D%2C%5Cn%20%20)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D).

**Comment by vjeux** [comment]
No, we don't encode the fact that if the right side of `=` doesn't fit in the same line, we can add a new line and indent it.

**Comment by vjeux** [comment]
This is something that's indeed strange but I don't really have a good solution for it, so I'm going to close this issue. If someone has a good idea on how to fix this, please let me know :)
