### ISSUE TITLE
Inline jsx expressions templates

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1090]
```js
    <style jsx>{`
      p {
        color: red;
      }
    `}</style>
```

Styled components use this way of writing css. I've also in the past used this form for stuffing some markdown inside of a tag. I think we should print jsx tags with a single child which is a jsx expression which contain only a single template literal (or tagged) inline like the example.

**Comment by jlongster** [comment]
See https://github.com/prettier/prettier/issues/1014#issuecomment-289595971

**Comment by vjeux** [comment]
@jlongster I just sent #1144 which fixes this case. I don't think that this one has anything to do with measurement, it's more adding a special case on how we print template literals in JSX.

**Comment by jlongster** [comment]
It has to do with how we process template literals anywhere, even inside of JSX. Here it is without my fix:

```js
<style jsx>
  {
    `
  p {
    color: red;
  }
`
  }
</style>;
```

And here it is with my tweak:

```js
<style jsx>{`
  p {
    color: red;
  }
`}</style>;
```

The problem is that by converting `\n` within template literals, we force it to break all parents.

I'd like to talk more about if we should apply my fix before merging your PR, as we don't need it if we apply my fix. But my fix is a tradeoff regarding correctness. Perhaps we could try it for a release cycle and see if anyone runs into problems?

**Comment by vjeux** [comment]
>  Perhaps we could try it for a release cycle and see if anyone runs into problems?

sgtm!

**Comment by jlongster** [comment]
Actually I realized where that will still fail. What the printer will be doing is measuring the entire template literal as if it were on one line, so if the literal is greater than 80 chars it'll still break it:

```js
<style jsx>
  {
    `
  p {
    color: red;
    color: red;
    color: red;
    color: red;
    color: red;
  }
`
  }
</style>;
```

We may have to take a more "formal" approach. Maybe we could change the behavior of `literalline` so that it doesn't break it parents, but always forces a newline no matter what. That way at least the measurement would always be correct, but there still might be some funny styles you run into. I think the styles would be a lot better by default though.

**Comment by vjeux** [comment]
Is there a way to tweak the measurement such that only the first and last line of the template literal are being accounted for? Maybe a max of the two?

**Comment by bakkot** [comment]
+1 for `literalline` not breaking parents.

The odd case which immediately springs to mind is 

```js
foo(a, `b
bbbb
`, c);
```

but I can't think of any good way to style that anyway, so I'm not terribly concerned.
