### ISSUE TITLE
Support Undo in idea

### ISSUE THREAD

**Issue by axetroy** [prettier/prettier#1093]
recover the code from last format.

``CRTL+Z`` didn't work at all.

**Comment by vjeux** [comment]
Can you tell us what IDE you used. It works for me in the Nuclide integration.

**Comment by axetroy** [comment]
@vjeux 
sorry, I didn't express clearly. 

JetBrains, Webstorm.

**Comment by jlongster** [comment]
This also works in Emacs. I think we should close this issue and a bug should be filed in whatever editor integration you are using.

**Comment by h-taylor** [comment]
I am using Intellij with the same problem. I was able to find a work around: http://stackoverflow.com/questions/8106126/intellij-idea-cannot-undo . Essentially you can look at your local change history to get the previous version. Is there another command besides --write we could use? I think that is were the problem is happening.

**Comment by vjeux** [comment]
This is very unfortunate, but I don't think that there's much we can do. If someone has a reasonable way to fix it, we should document it. I'm going to close this issue for now.
