### ISSUE TITLE
Option to sort object keys

### ISSUE THREAD

**Issue by cdlewis** [prettier/prettier#1096]
Would you be open to a pull request to add the option for prettier to sort object keys? Currently I'm linting on this but having Prettier take care of it would be neat. E.g.

Before:

```
{
  b: {},
  a: {},
}
```

After:

```
{
  a: {},
  b: {},
}
```

**Comment by lydell** [comment]
Unfortunatley, this would have execution order issues.

```js
({
  b: prepareLunch(),
  a: eatLunch()
})
```
→
```js
({
  a: eatLunch(),
  b: prepareLunch()
})
```

Similar issue: #323

**Comment by vjeux** [comment]
Thanks for opening this issue. This is currently out of scope for this project as is, but we want to be able to add plugins at some point to tweak the AST as a pre-processing phase such that someone can implement this.

**Comment by hsingh23** [comment]
@lydell This is not a relevant example. In an js object (not jsx props) the keys don't really decide the iteration order. http://2ality.com/2015/10/property-traversal-order-es6.html

**Comment by lydell** [comment]
@hsingh23 This has nothing to do with traversal order. `({b: console.log(1), a: console.log(2)})` logs "1" and then "2" because that’s the order the `console.log`s are run when the object is created.

**Comment by hsingh23** [comment]
I can't think of a time where I'd ever want to do that. Perhaps if this was an optional feature...

**Comment by lydell** [comment]
> I can't think of a time where I'd ever want to do that.

Me neither! But it could happen by mistake. Prettier has to make the promise that it will never ever change the meaning of your program, so people can run it confidently.

**Comment by vjeux** [comment]
The sad truth is that given a big enough codebase, the probability of it happening is close to 1. And, when it does, it changes things in extremely subtle ways, it's a nightmare trying to debug what happens.

Working on projects like prettier, babel or any widely used piece of js infrastructure at Facebook is challenging because all those extremely unlikely things that you brush off as "nah, no one would rely on it", well, people are (intentionally or not) and you have to deal with it.

So it's sometimes easier to just say: no we're not going to change the semantics to avoid having to deal with the downfall.
