### ISSUE TITLE
Idea: max-expression length

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1099]
When people try setting the line width to more than 80 columns, it ends up being a bad experience because prettier tries to push too much content into a single line. I've also observed multiple times and had many people complaining that prettier didn't break expressions when it "should" have when code was on a single level of indentation, but worked better when code was in a deeply nested context.

I've talked about this problem with many people at Facebook and had a realization. I don't think that trying to push as much content as possible within 80 columns is the best heuristic to model how people are writing code. A potentially better one would be to have a maximum expression length.

If we have a max-expression length of 70, this means that an expression would break the same way for up to 5 levels of indentation given a tab width of 2 and 80 columns limit.

I think that it's going to be a subtle, but positive, change for 80 columns and would have a big impact if you increase that column count. I want to implement it and see how it feels but figured that I would post it first to get feedback.

**Comment by jlongster** [comment]
I guess I don't understand why people would complain that a maximum line length allows code to flow to that length. They specified a larger length, so they asked for it ;) What are they wanting a line length of 80 to do that it doesn't do right now?

> If we have a max-expression length of 70, this means that an expression would break the same way for up to 5 levels of indentation given a tab width of 2 and 80 columns limit.

I don't understand how this is different than just a normal 80 columns limit. The same thing would happen for that expression: it would break the same for up to 5 levels of indentation because the whole line is under 80.

The wonderful things about prettier's max line length, unlike eslint's, is that it's just a suggestion. We'll still gladly put a really long string on one line and let it go to column 500, and let things run off when we can't break them. But there is not linting error or anything like that that you have to worry about.

**Comment by vjeux** [comment]
If you have an expression that is 76 characters long, it's going to fit in one line for the first two levels of indentation and then break for the following. If you put a max expression width of 70, then it's always going to break no matter if you are at one level of indentation or 5.

I think that the 80 columns limit works well in practice because it makes expressions at roughly around 70 characters in width. More than that, then it's harder to read because the expression starts becoming too complex.

With 80 columns, trying to cram as much as possible works well because it finds this sweet spot of expression width. But if you make it larger, a lot of expressions are getting a lot wider. Which is not how people actually write code with 110 characters line length. My intuition is that the biggest reason people go past 80 columns is when there are many levels of indentation, expressions break way more often than lower levels of indentation and that's not visually pleasing.

If we have two controls: max line width and max expression width, then we can prevent expressions from being too long at low indentation level and allow people to have expressions not break so often at high indentation levels.

Just to make it clear, my proposal is additive, I still want prettier to respect the max line width. But it has the ability to break groups more often without having to hit the max line width at low indentation levels.

**Comment by jlongster** [comment]
Main thing I worry about is it's just hard to understand. It's taking me a while to figure out what this would do, and it would require you to understand how those two options play together. I'm not sure it's worth it, but feel to play with it. I can see people asking why a simple expression in the online editor broke before reaching the max line length and having to explain this... it's a subtle different that is kinda confusing.

**Comment by SimenB** [comment]
I like the idea. I have had changes since using prettier where I had stuff nice and aligned, and prettier one-lined it. I don't really care about max width of a single line (up to a point of about 150), but I want to be able to easily read the expression, so I set it lower in order for prettier to break more aggressively. From what I can gather from the OP, that's the thing it aims to do something about.

**Comment by jlongster** [comment]
@SimenB This will not solve that all the time. Sure, you could try to apply it to solve one file, but then you'll run into it elsewhere with different expressions. The whole point of prettier is to expand and collapse stuff where possible, so that's core to this project. Trying to add things to avoid that is going to be a long fight. It's best to give up special alignment :)

**Comment by SimenB** [comment]
It wasn't the alignment itself that was lost; it was over multiple lines, but would be within the max-line if one-lined, so prettier did that (rightfully). I would think this new option would have "saved" me.

> My intuition is that the biggest reason people go past 80 columns is when there are many levels of indentation, expressions break way more often than lower levels of indentation and that's not visually pleasing.

This rings true for me

**Comment by svenanders** [comment]
Sounds like a good idea, especially if you take chainable statements into consideration. I wind up setting the line length to less than what I ideally want just to prevent prettier from one-lining expressions & functional code chains. For instance:

```
const calculateTotal = item =>
  getBasePrice(item)
    .chain(applyDiscount)
    .chain(addTax)
    .fold(logError, displayTotal);
``

The above is the result when I set the width to 80. A higher width (say 120) would have prettier one-line it.

**Comment by SimenB** [comment]
Seems like it's mostly for chained stuff, so what about something like eslint's `newline-per-chained-call`? http://eslint.org/docs/rules/newline-per-chained-call
Might be an easier heuristic to understand, while still fulfilling the same purpose

**Comment by KyleAMathews** [comment]
We could call this the "callback hell" rule :-)

**Comment by xtuc** [comment]
I'm wondering why you couldn't break a long string on one line.

Could the following example be possible:

in:
```js
log("ffooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo");
```

out:
```js
log(
  "ffooooooooooooooooooooooooooooooo"
  + "oooooooooooooooooooooooooooooo";
)
```

**Comment by svenanders** [comment]
You mean like this?

![cb hell](http://icompile.eladkarako.com/wp-content/uploads/2016/01/icompile.eladkarako.com_callback_hell.gif)

No formatting tool will help sort out this kind of code.

**Comment by KyleAMathews** [comment]
Haha I love that gif :-)

I didn't mean to imply prettier could solve call back hell (or world peace for that matter) just that prettier isn't very useful right now for people stuck in callback hell due to the reasons @vjeux describes.

**Comment by AndrewIngram** [comment]
I think expression length (rather than line length) may also help with the issues i've been having with Ramda:

https://gist.github.com/AndrewIngram/552b335922c2b67aef92b315b2a94820

**Comment by vjeux** [comment]
I'm going to close this as we're unlikely going to implement this or make any drastic changes to the way prettier formats code.
