### ISSUE TITLE
namespaced gql should trigger graphql formatting

### ISSUE THREAD

**Issue by onichandame** [prettier/prettier#11392]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlAwgCQFEBZAQUwF5NSAHCAG3ol3oEsEYA6AcwEd6ABgB0omTLwCucAE4BPTAEMarTMCUrgIsdsysAJlu0BfQyagCA3CAA0ICDRit0yUAunSIAdwAKbhGmQQBXpPBVkA2wAjaQUwAGs4GGwaWNYobmQYaSlbOABbSLg9PSKAGQV0iQVuOAAxCGk8hRhHdMCFCRgIGxAACxg8+gB1XtZ4NBSwOGx-MdYANzHZQLA0CJA0tBkYbxjuJuQAM2Ct2wArNAAPACEY+MTsBTy4UrS4I5O4c6vsNO56OAARQkEHgH3opxAKWkW2kgRgshocDQYGkrAcPRoaNgQ30MF6yAAHAAGWxYiBbIYxGiBLHImTzd62SSguC7ewBFAKNAAWigcCKRR60jgklYIt21QOSGOEK+IC2eVYmWy8rQfwBwNZ4MhMAUkVxenxyAATLYsgpWGx0rgIHlpSBkQBWHoSLYAFX1nNlkPmUgAklASrBsKj0TBSEHsAiATq4EYjEA)

```sh
--parser typescript
```

**Input:**

```tsx
const SCHEMA = ApolloClient.gql`
  query api {api {
      id
    }
  }
`;
```

**Output:**

```tsx
const SCHEMA = ApolloClient.gql`
  query api {api {
      id
    }
  }
`;

```

**Expected behavior:**
```tsx
const SCHEMA = ApolloClient.gql`
  query api {
    api {
      id
    }
  }
`;
```

**Comment by sosukesuzuki** [comment]
To enable formatting for embedded GraphQL, you should use `gql` instead of `AplloClient.gql`.

**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBlAwgCQFEBZAQUwF5MBzARwBsADAHSk01oFc4AnAT0wBDAA4BLTMBHjgrdnMyiAJrLkBfFeqiMA3CAA0ICMJij0yUIJ48IAdwAKlhGmQhB9G4L7ODAIx6CwAGs4GGxhANEoamQYHm4DOABbHzhFRVSAGUEozkFqOAAxCB5EwRgTKJdBThgIfRAACxhE+gB1BtF4NHCwOGwnTtEAN06+FzA0bxBItF4YO39qUuQAMzdZgwArNAAPACF-IJDsQUS4DMi4VfW4Ld3sSOp6OABFTgh4a-oNkHCeWZ4LhgfGEcDQYB4omM9WEkNgrSUMAayAAHAAGAywiCzVr+YQuWFg3hDK4GLgfOALIzOFCCNAAWigcFSqXqPDgXFE7IWeWWSDW31uIFmiVEMTiQrQj2ebwpXx+MEEPgRiiRyAATAZYoJRPRHrgIIk+SAwQBWeqcWYAFSVNIFPyG3AAklB0rBsBCoTBSK7sMDnvK4KpVEA)

```sh
--parser typescript
```

**Input:**

```tsx
const SCHEMA = gql`
  query api {api {
      id
    }
  }
`;
```

**Output:**

```tsx
const SCHEMA = gql`
  query api {
    api {
      id
    }
  }
`;

```

**Comment by onichandame** [comment]
@sosukesuzuki Why so? Was there any discussion about the decision here? I mean from a user's perspective, whether calling a function by its name only or as part of a namespace makes no actual difference and prettier as the formatter should also treat them equally.

**Comment by sosukesuzuki** [comment]
I don't remember exactly, but I think there was some discussion about that. I'll look into it.

**Comment by fisker** [comment]
See #7573 #7576
