### ISSUE TITLE
Precommit script issues

### ISSUE THREAD

**Issue by Andreyco** [prettier/prettier#1146]
**Actual behaviour**
1. modify file
1. stage only several hunks/lines, leave some of changes not staged.
1. commit
1. **whole file is formatted and commited**

Expected behaviour
1. modify file
1. stage only several hunks/lines, leave some of changes not staged.
1. commit
1. **only staged hunkes/lines should be formatter and commited**

Probably this is not direct issue with `prettier`, but I think example should provide solution for formatting staged code only.

Please, correct me if you don't share same opinion.

**Comment by yuchi** [comment]
I was implementing the suggested configuration and stopped because I realized this would happen with partially staged files.

While your procedure to reproduce the issue is right there’s a waaay more common one:

1. Modify a file
2. Add it to stage (fully)
3. Modify the file **again**
4. Commit
5. **whole file is formatted and commited**

**Comment by leipert** [comment]
For reference:
https://github.com/okonet/lint-staged/issues/62

**Comment by vjeux** [comment]
Prettier works on full files only, not partially. This is the intended behavior.

**Comment by JLHwung** [comment]
Prettier can work on `range` now: https://github.com/prettier/prettier/blob/3f6a232cea56f60f1ba50cbae2d56f78b36a7699/README.md#range

**Comment by yuchi** [comment]
Unfortunately that doesn't solves the issue since that would format the ranges as standalone ASTs.
