### ISSUE TITLE
Superfluous parens: `a.push((b += c));`

### ISSUE THREAD

**Issue by MarkKahn** [prettier/prettier#11471]
**Prettier 2.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAdABwK4GcAWAFAEYAEA1ALylgCUA3CADQgSYwCW0uyoqATvwgB3AAoCEPFKgA2w1AE8eLYv1RgA1nBgBlTOo5QA5shj9scFnAC2xOABN7DgDKpj2VEbgAxCP2uoMJzGyGjYMBDMIPgw1jIA6vgc8Lj6YHA6kskcAG7JCqFguMoghrhw-DCiakYByABmsuUsAFa4AB4AQmqa2jqo1nDOhnANTZYgbe06hkYycACK2BDwYzLNIPr85fyhxKh2MlGY-IYw8Rz2MPjIABwADCwnEOXxapihJ3A7OaMsAI7LeDVNhSNC4AC0UDgDgcUX4cEBHAR1U8dSQjXWE3K1g4pnM2Nm8yWK1GGPGLBgBwuVxuSAATJS1BwZLMAMIQazokDfACsUTwcAAKgcpJiNjkLABJKBOWA6MCndgAQVlOhgCnma3KAF8dUA)

```sh
--parser babel
```

**Input:**

```jsx
a.push(b += c);
```

**Output:**

```jsx
a.push((b += c));

```

**Expected behavior:**

no extra parens, they're pointless here

**Comment by bakkot** [comment]
This is intentional: it draws the reader's attention to the fact that this is a side-effecting assignment which is appearing as part of a larger statement rather than as a statement by itself, which is an unusual thing to encounter. We do the same thing for e.g. `if (x = y) {...}`.

See #5070, #5591, etc.

**Comment by MarkKahn** [comment]
That should be the responsibility of linters though
