### ISSUE TITLE
CRLF around JSXText outputs wrong "whitespace" with flow

### ISSUE THREAD

**Issue by CiGit** [prettier/prettier#1168]
_Prettifying_ with flow parser JSX with `\r\n` before or after text outputs a whitespace.
This issue was originally reported on esbenp/prettier-vscode#63.

### Input
settings: 
- `crlf` line endings
- flow parser
```js
<div>
 Text
</div>
```
### Actual
```js
<div>
  {" "}
  Text{" "}
</div>;
```
### Expected
```js
<div>
  Text
</div>;
```
### Reproduction
I was unable to reproduce it in the online tool due to line endings normalization.
```bash
echo -e '<div>\r\nText\r\n</div>' | prettier --parser flow
```

### Notes
It _prettifies_ as expected with `lf` line endings or with babylon parser.

**Comment by lydell** [comment]
Pro tip: You have to pass the `-e` flag to `echo` in order to interpret escapes.

```
$ echo -e '<div>\r\nText\r\n</div>' | prettier --parser flow
<div>
  {" "}
  Text{" "}
</div>;
```

(Tested using latest master.)

**Comment by CiGit** [comment]
@lydell Thanks for the tip. I'll update original post accordingly.
I've tested with `prettier@0.22.0` for the record.

**Comment by vjeux** [comment]
Flow: `"value":"\r\nText\r\n","raw":"\r\nText\r\n"`
Babylon: `"rawValue":"\nText\n","raw":"\r\nText\r\n"},"value":"\nText\n"`

Looks like babylon removes `\r` more aggressively than flow. I'm not really sure which is the right behavior but they are different and it seems like the current implementation doesn't work properly with `\r`.

**Comment by rattrayalex** [comment]
Should we open a corresponding bug in the flow parser?

**Comment by vjeux** [comment]
@rattrayalex I was hoping that you could tell which one is expected, the flow one or the babylon one. And then, yeah we should open an issue.

**Comment by rattrayalex** [comment]
According to [the draft spec](https://github.com/facebook/jsx) of JSX...

> **Whitespace and Comments**
> JSX uses the same punctuators and braces as ECMAScript. WhiteSpace, LineTerminators and Comments are generally allowed between any punctuators.

So it seems `\r\n` should probably be an allowed character to pass through as JSXText. Probably not worth filing as a bug on either project, since passing only `\n` through as the value is surely acceptable as well.

FWIW, it looks like `esprima-fb`, which may have been the original(?), [preserves](https://github.com/facebookarchive/esprima/blob/fb-harmony/esprima.js#L6908) `\r` in `\r\n`. Looks like that was added here, https://github.com/facebookarchive/esprima/commit/e44ee1bf836658fd1b6ba653115d38251b3ba00d though primarily for the purpose of any handling of `\r`, and not necessarily to specifically pass it through as a value.
