### ISSUE TITLE
[docs] Add note to installation instructions about PowerShell defaulting to UTF-16

### ISSUE THREAD

**Issue by humphd** [prettier/prettier#11751]
The [installation docs](https://prettier.io/docs/en/install.html) make the following suggestion for creating an empty prettier config file:

```sh
echo {}> .prettierrc.json
```

This is a useful suggestion in most cases, but breaks for people using Windows and PowerShell, which ["uses the Unicode UTF-16LE encoding by default"](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_character_encoding?view=powershell-7.1#character-encoding-in-windows-powershell).

I gave students a lab this week, and asked them to set up prettier. A number of them struggled with errors that they couldn't make sense of--all of them were encoding related, and all of the people affected were on Windows and PowerShell.

It looks like this has been [discussed in the past](https://github.com/prettier/prettier/issues/8815#issuecomment-671222957), but the suggestions then seem to be "convert the file to UTF8."

I wonder if it would be better to suggest another method for doing this (there's nothing sacred about using the `echo` style above) and/or add a note about PowerShell and the need for UTF8 in JSON.

**Comment by ChrisCrossCrash** [comment]
I think this is the only way to achieve the same results in PowerShell:

```powershell
"{}" | out-file -encoding UTF8 -noNewLine deleteme.txt
```

I also ran into this issue recently. I'm using PyCharm, which recently changed the default Windows terminal from CMD to PowerShell. All of the JetBrains IDEs are pretty similar, so I wouldn't be surprised if that's what happened to all of them.

### A couple of ideas:
1. Make another "Note" section in the documentation for PowerShell users.
2. This error message isn't super helpful, especially since the text content of the file is correct, just not the encoding:
    ```
    [error] Invalid configuration file `src\App.css`: JSON Error in C:\Users\Chris\MyProject\.prettierrc.json:
    [error] LinesAndColumns$1 is not a constructor
    ```
    Perhaps we could provide a hint to the user telling them to check the encoding?
3. Just have prettier work as expected, even if the encoding isn't UTF8 (easier said than done? I have no idea.)

**Comment by fisker** [comment]
I thought about this before, maybe it will be simplier if  we can just support `prettier init` in cli. Only problem is we don't support sub-command. Maybe we can use `prettier --init`.

**Comment by fisker** [comment]
I thought about this before, maybe it will be simplier if  we can just support `prettier init` in cli. Only problem is we don't support sub-command. Maybe we can use `prettier --init`.

**Comment by humphd** [comment]
`pretter --init` is what [eslint does](https://eslint.org/docs/user-guide/getting-started#installation-and-usage), and many people are going to be doing both.  That might make sense.
