### ISSUE TITLE
prettier parser, difference between `babylon` and `flow`

### ISSUE THREAD

**Issue by svipben** [prettier/prettier#1180]
Hello,

what is difference between `babylon` and `flow` in `parser` setting? Can you provide me some examples to understand it better?

Which one is better to use?

Thanks!

**Comment by yamafaktory** [comment]
Hi @svipben,

Babylon generates an AST according to the Babel AST format and is powered by JavaScript, whereas Flow is an OCAML static typechecker for JavaScript. Babylon is the default parser for Prettier, as mentioned in the [readme](https://github.com/prettier/prettier#language-support).

The question is not which one is the better to use but which one will fulfill your needs, i.e. if you want to benefit of type annotations then use Flow otherwise Babylon is totally fine ^^.

**Comment by svipben** [comment]
@yamafaktory I'm using Flow in my client side and I'm also thinking to use it on server side too. So I think it will be better for me to use Flow parser as far as I understand? I'm correct?

Thanks.

**Comment by existentialism** [comment]
Small nit, but Babylon actually [supports flow type annotations](https://prettier.github.io/prettier/#%7B%22content%22%3A%22declare%20module%20'redux'%20%7B%5Cn%5Ctdeclare%20type%20State%20%3D%20any%3B%5Cn%5Ctdeclare%20type%20Action%20%3D%20Object%3B%5Cn%5Ctdeclare%20type%20AsyncAction%20%3D%20any%3B%5Cn%5Ctdeclare%20type%20Reducer%3CS%2C%20A%3E%20%3D%20(state%3A%20S%2C%20action%3A%20A)%20%3D%3E%20S%3B%5Cn%5Ctdeclare%20type%20BaseDispatch%20%3D%20(a%3A%20Action)%20%3D%3E%20Action%3B%5Cn%5Ctdeclare%20type%20Dispatch%20%3D%20(a%3A%20Action%20%7C%20AsyncAction)%20%3D%3E%20any%3B%5Cn%5Ctdeclare%20type%20ActionCreator%20%3D%20(...args%3A%20any)%20%3D%3E%20Action%20%7C%20AsyncAction%3B%5Cn%5Ctdeclare%20type%20MiddlewareAPI%20%3D%20%7B%20dispatch%3A%20Dispatch%2C%20getState%3A%20()%20%3D%3E%20State%20%7D%3B%5Cn%5Ctdeclare%20type%20Middleware%20%3D%20(api%3A%20MiddlewareAPI)%20%3D%3E%20(next%3A%20Dispatch)%20%3D%3E%20Dispatch%3B%5Cn%5Ctdeclare%20type%20Store%20%3D%20%7B%5Cn%5Ct%5Ctdispatch%3A%20Dispatch%2C%5Cn%5Ct%5CtgetState%3A%20()%20%3D%3E%20State%2C%5Cn%5Ct%5Ctsubscribe%3A%20(listener%3A%20()%20%3D%3E%20void)%20%3D%3E%20()%20%3D%3E%20void%2C%5Cn%5Ct%5CtreplaceReducer%3A%20(reducer%3A%20Reducer%3Cany%2C%20any%3E)%20%3D%3E%20void%5Cn%5Ct%7D%3B%5Cn%5Ctdeclare%20type%20StoreCreator%20%3D%20(reducer%3A%20Reducer%3Cany%2C%20any%3E%2C%20initialState%3A%20%3FState)%20%3D%3E%20Store%3B%5Cn%5Ctdeclare%20type%20StoreEnhancer%20%3D%20(next%3A%20StoreCreator)%20%3D%3E%20StoreCreator%3B%5Cn%5Ctdeclare%20type%20ActionCreatorOrObjectOfACs%20%3D%20ActionCreator%20%7C%20%7B%20%5Bkey%3A%20string%5D%3A%20ActionCreator%20%7D%3B%5Cn%5Ctdeclare%20type%20Reducers%20%3D%20%7B%20%5Bkey%3A%20string%5D%3A%20Reducer%3Cany%2C%20any%3E%20%7D%3B%5Cn%5Ctdeclare%20class%20Redux%20%7B%5Cn%5Ct%5CtbindActionCreators%3CactionCreators%3A%20ActionCreatorOrObjectOfACs%3E(actionCreators%3A%20actionCreators%2C%20dispatch%3A%20Dispatch)%3A%20actionCreators%3B%5Cn%5Ct%5CtcombineReducers(reducers%3A%20Reducers)%3A%20Reducer%3Cany%2C%20any%3E%3B%5Cn%5Ct%5CtcreateStore(reducer%3A%20Reducer%3Cany%2C%20any%3E%2C%20initialState%3F%3A%20State%2C%20enhancer%3F%3A%20StoreEnhancer)%3A%20Store%3B%5Cn%5Ct%5CtapplyMiddleware(...middlewares%3A%20Array%3CMiddleware%3E)%3A%20StoreEnhancer%3B%5Cn%5Ct%5Ctcompose(...functions%3A%20Array%3CFunction%20%7C%20StoreEnhancer%3E)%3A%20Function%3B%5Cn%5Ct%7D%5Cn%5Ctdeclare%20var%20exports%3A%20Redux%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22doc%22%3Afalse%7D%7D) too!

There are, however, some small inconsistencies that we're actively working on fixing.

**Comment by svipben** [comment]
Prettier parser use format style for specified parser for e.g. for Flow it will be better formatting if I'm using Flow in my project. I get it right?

**Comment by yamafaktory** [comment]
@existentialism I feel somehow guilty to have answered that Babylon was not the *de facto* tool to benefit of type annotations as I am using it myself on a small project mentioning the Flow support (https://github.com/yamafaktory/shrimpit)... 😄

**Comment by yamafaktory** [comment]
@svipben Prettier should print the same formatted code for Flow / Babylon. It's reading the AST produced by one or the other parser. But as mentioned by @existentialism, Babylon can potentially introduce some inconsistencies, but I'll let him answer that as he's one of the core contributors of the project.

**Comment by vjeux** [comment]
Sorry this is confusing and not well documented. Both the flow and babylon parser support the full JavaScript language as well as Flow types, JSX and many es6 proposals. The reason we have both is to hedge our bets in case one parser falls behind rather than something that you should have to care about as a user.

At this point, babylon is the most complete and bug-less parser (and also the default).

Flow has some issues where utf8 characters are not properly located which lead to some objects to be incorrectly expanded and will output flow types as comments as real flow types (note that babylon will not print them in the right location, so it's not working either).

Both have various (and different) crazy edge cases that were found by fuzzing that are not correctly parsed, but they shouldn't really affect anything you write in practice.

There are some various very edge cases like \r\n not being reported the same way between the two parsers but prettier takes care of it and both work the same as the user is concerned.

**Comment by svipben** [comment]
@vjeux Thank you very much for such information, so I will use the default parser.

**Comment by vjeux** [comment]
I added a comment on the README, hopefully it should be clearer.

**Comment by jackson-sandland** [comment]
An example would go far here...

**Comment by j-f1** [comment]
@jackson-sandland Are you encountering errors when using the Flow parser? If not, you should probably use the Babylon parser.
