### ISSUE TITLE
Sh : no parser

### ISSUE THREAD

**Issue by Gadgetroch** [prettier/prettier#11837]
- Prettier Version: 2.4.1
- Running Prettier via: CLI
- Runtime: NodeJS v12.22.5
- Operating System: Debian 11
- Prettier plugins (if any): SH

**Steps to reproduce:**

`prettier -w file.sh`

**Expected behavior:**

Formatting file

**Actual behavior:**

`[error] No parser could be inferred for file: file.sh`

prettier-plugin-sh installed.

**Comment by kachkaev** [comment]
Please use the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md). If the problem is related to a plugin, the issue needs to be opened in another repo. I guess that it’s https://github.com/rx-ts/prettier for https://www.npmjs.com/package/prettier-plugin-sh

**Comment by JounQin** [comment]
See https://github.com/rx-ts/prettier/pull/138

It has been fixed.
