### ISSUE TITLE
print-width does not respect comments or strings

### ISSUE THREAD

**Issue by deltaskelta** [prettier/prettier#1185]
I have only tested it with comments or strings so far and I wanted to get some input from someone more experienced than myself....

It seems that a long array will get broken up if it exceeds the print-width, but a long comment or a long string will not. I am wondering if this is by design or not?

**Comment by dodekeract** [comment]
@deltaskelta I'd assume it's by design so that JSDoc comments etc. aren't broken.

**Comment by jlongster** [comment]
Yes, we are not going to actually modify the AST and break up "atomic" expressions. That could lead to potentially breaking lots of little things. The maximum line length in reality is just a suggestion. If someone wants to embed a long URL, it would be terrible for us to break it up since it would make it a lot harder to read, copy/paste, etc.
