### ISSUE TITLE
Formatting of DSL-like coding styles

### ISSUE THREAD

**Issue by AndrewIngram** [prettier/prettier#1187]
I have a project in which I'm using Ramda, and have code that looks like this:

```javascript
  const productResolvers = {
    comments: cond([
      [notFirstPage, run((obj, args) => getCommentsForProduct({id: obj.id, ...args}))],
      [T, loader('commentsForProduct', (obj, args) => ({key: obj.id, params: args}))],
    ]),
    category: cond([
      [obj => !obj.category, () => null],
      [T, loader('productCategory', obj => obj.category)],
    ]),
  };
```

Each line of the `cond` calls is formatted this way so that it reads a bit like pattern matching in functional languages. So it's pairs of `[conditionCheckFn, resultIfMatchedFn]`.  The lines are written in this way to maximise legibility of what is otherwise a very syntactically-heavy block of code.

When I run this through prettier (line length 80), I get this:

```javascript
const productResolvers = {
  comments: cond([
    [
      notFirstPage,
      run((obj, args) => getCommentsForProduct({id: obj.id, ...args})),
    ],
    [
      T,
      loader('commentsForProduct', (obj, args) => ({
        key: obj.id,
        params: args,
      })),
    ],
  ]),
  category: cond([
    [obj => !obj.category, () => null],
    [T, loader('productCategory', obj => obj.category)],
  ]),
};
````

Note how inconsistent the formatting has become. One could play with the line length option to try and find a value that works well, but I'd imagine it's impossible to find something that always works, and 80 is a pretty decent value to otherwise be using.

Are these kind of intentional formatting patterns identifiable at the AST level, or are we better off using `// prettier-ignore`?

**Comment by vjeux** [comment]
Thanks for explaining this so clearly. The fundamental way prettier works is by formatting your code such that it stays under 80 columns as this is a heuristic that matches the way most people write their code.

It seems like for your use case, you decided that it is okay to transgress that rule when you're inside of a `cond()` call.

I have two questions for you:
- In this case, the longer line is 88 columns, so pretty close to 80. Would you accept it running way longer than this? Like 200 characters. At some point you'd likely expand it to multiple lines no?
- If you do, how would you format it? The way prettier expanded it looks reasonable to me, but if you brought this issue up, it's likely that you had something else in mind.

**Comment by AndrewIngram** [comment]
If I increase the line length, I end up with it collapsing these cond blocks to a single line, which is also undesirable. If I reached the conclusion that these lines were too long, i'd probably opt to manually pull out some of the functions so I can reference them by name instead, rather than letting code-formatting solve the problem for me.

What might work is the ability to tell prettier I want line-breaks to remain unchanged, but to apply other formatting rules. Eg `// prettier-preserve-line-breaks`

**Comment by vjeux** [comment]
The real goal of prettier is for you to not care about how code is formatted anymore. If you have to add comments with subtle meanings like `// prettier-preserve-line-breaks` and do a lot of work to get it to format code the way you want it, then not only does it defeats the purpose of the project but also will confuse people working with you on the project.

Given the example you gave me, I do not think that prettier is doing a bad job as it is. You can clearly see the two cases and the two arguments are well separated. It is not how you would have written the code and you are not used to seeing it written this way, but it seems acceptable to me.

Since it's unclear how to improve prettier to accommodate your use case, I have three suggestions for you:
- Do not use prettier. It's totally fine if you are not satisfied with the way it prints things :)
- Use prettier and add `// prettier-ignore` for all the `cond([` blocks.
- Use prettier and give it 5 minutes. For this specific case, you are likely going to get used to seeing it the expanded way and find it natural after some time.

**Comment by jlongster** [comment]
I've heard someone else say that Ramda does not work as well under prettier, and I guess it is because of the arrays. I guess it would help if we kept arrays expanded if they were in the original source like we do objects, and then they could increase the line length some. We've been hesitant to do that before as that kind of stuff is non-intuitive sometimes and tends to lead to "unstable" behavior.

**Comment by vjeux** [comment]
We are now past 1.0 and unlikely going to change this. I'm going to go ahead and close this issue to keep them actionable. Sorry we can't accommodate Ramda library very well :x
