### ISSUE TITLE
Option to configure indentation for "continuation indents/wrapped lines"

### ISSUE THREAD

**Issue by dvlato** [prettier/prettier#11897]
Many style guides set a different indentation (eg. *2 tabWidth) for wrapped lines/ continuation indents; however it seems impossible to configure prettier for that.  Could we please add an option for continuation indents? As an example, IntelliJ  IDEA allows setting it as a value (instead of 2X normal), which would be enough for me:

![image](https://user-images.githubusercontent.com/25137038/144232804-7ac04792-2f2c-483a-bc4a-a8ac7505392d.png)

See the prettier example, where I would like "this.line.is.very.long()" and "bodyOfBlock()" to have different indentation (configurable, of course!).

**Prettier 2.5.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQwBaoDOAdADapRzFHEBucATgJ5nQDm2AlADpSaYAyAZgC2EBlUgATKnkZxsDAK5QoFNpgDUmCEpgAaHegCSMgIaFDAdwZmADgEFSEs1KadOmYL34AjCG4A8ugAQqQQYADWXADcvAC+vJBQhDCYhKgiqKRmDNlMDoSESllQbAAy7ABquahmvqRwAHJmInCEmAC8PukQbTWkSnAxIPogEHYwqNCEyKC5DBBWAAq5CLMoZrQQqFKjIL62UXAwAMp2ZmDqyDDKcGN4MCKkAOoE8IQXYHCn66hTtH+TGQ4CK+wohEYMGWtjYIjMyHQZlIkLGACtCAAPEJHSInU6tODlChwRHI1EgDGY07qRoARSUEHgZJR9xAFwYkIYIN89SY4Sg+zseVgL12+GQAA4AAxjYUQSEvWx2EHC9qMej7CQARyUqAkMLMcIRSCRrLGkKyNzuFtpcAZTNJpvJbJg9TFUglSAATGNbmZsuoAMJ9eEgqDQUljJSQgAq9Q2Zsh8XiQA)

```sh
--parser babel
--arrow-parens avoid
--trailing-comma none
```

**Input:**

```jsx
if (this.line.is.very.long()
  && more.code.here(running + out, ofIdeas, wrapAlready)) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames =
  someValue;
```

**Output:**

```jsx
if (
  this.line.is.very.long() &&
  more.code.here(running + out, ofIdeas, wrapAlready)
) {
  bodyOfBlock();
}
const similarilyAssumingLongVariableNames = someValue;

```

**Expected behavior:**
if (
    this.line.is.very.long() &&
    more.code.here(running + out, ofIdeas, wrapAlready)
) {
  bodyOfBlock();
}

**Comment by alexander-akait** [comment]
Sorry, we don't want to add more options, please read https://prettier.io/docs/en/option-philosophy.html

**Comment by James-Richardson** [comment]
The Google Style Guide says that continuation indents should be 4 spaces: https://google.github.io/styleguide/jsguide.html#formatting-indent.

And in my experience, having a continuation indent that's twice the normal indent is common enough that I considered it a de facto standard.

**Can you please explain why Prettier necessarily sets the continuation indent to 2 spaces instead of 4?**

Is it a preference of Prettier users?

Is the industry as a whole moving to 2 space continuation indents?

Is it an oversight in Prettier that has gone uncorrected for so long that it is now too late to change it?

Or does no one know why the continuation indent in Prettier is 2 spaces, it just is?
