### ISSUE TITLE
Prefer line split on preceeding array literal instead of chained methods

### ISSUE THREAD

**Issue by pomle** [prettier/prettier#11940]
```sh
# Options (if any):
```

**Input:**

```jsx
const myParam1 = "x";
const myParam2 = "y";
const myParam3 = "z";
const myParam4 = "a";

const targetUri = [
  "recording", 
  myParam1, 
  myParam2, 
  myParam3, 
  myParam4
].join(":");

```

**Output:**

```jsx
const myParam1 = "x";
const myParam2 = "y";
const myParam3 = "z";
const myParam4 = "a";

const targetUri = ["recording", myParam1, myParam2, myParam3, myParam4].join(
  ":"
);
```

**Expected behavior:**
Prettier should prefer line splitting the array literal instead of the function args when line becomes too long.

**Comment by kachkaev** [comment]
Please follow the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md), which includes the Playground link.

If you want to enforce new lines in your example, you can use [`prettier-ignore`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngBQEMAnQ7ARkwF5MAdEAD3oG5apIoMcCSyAmanRC4WbDlzxFS2AMyD6AL1Ht0WSb2wAWeSELKxqzDBIBzODACqxAJaCA2m0xDicSMQAm1qCfoAaOlBO6tLk-o7cUvxhgREaMtFBPNLaAPQpmIC8G4ACO0YAFtZomJDY2AhYAA4uaHDEAG5whQA2XnCYAEYuhADWaGwAugB0AFYQXgAU9Ej0AJTMIL4gEOUw1ujIoCTEEADuUghoyLqN24S4BwsdhGBd5gDKZHAAMi3IAGaEjdUXpNd35VdeEzIGDEACucAWcGwbTg7ncsMehG8oMIZgAYhBiNhCDAVt5DoRQTAIPMQLkYNhGgB1fLwND-MBwW77awrWqs3CHMBoc4gLzVYgwfCkEzYt4fL4gIZoBi3QGNOAARVBEHg4s+EJA-2IAsObUIMMapMqXhgVOs7hguWQAA4AAwLSoQapU0jlQ6VBo1eqkgCOKvgwqWBxQhDQAFooHBYbDSS5-dYXMLUWKkO8NQtqthrMCwZq0PKlQG4OrJcY2ubLdakHwFiDCNZmt4AMIQEqEQ4NACspNB1QAKgaQ+nJbVwQBJKDw2C3MA2ZYAQSntxguAVpbgAF9N0A).

```ts
const myParam1 = "x";
const myParam2 = "y";
const myParam3 = "z";
const myParam4 = "a";

const targetUri = [
  "recording", 
  myParam1, 
  myParam2, 
  myParam3, 
  myParam4 // 👀 this comment preserves line breaks
].join(":");
```

In my opinion, the best option here is to not bother about the spacing and focus on the app logic instead. See [_Why Prettier?_](https://prettier.io/docs/en/why-prettier.html).

**Comment by pomle** [comment]
@kachkaev what makes you think I didn't follow the issue template?

Sorry, I don't understand your feedback. I use prettier to make the code prettier without having to make decisions. When prettier makes the wrong decision it has defeated it's own purpose.

**Comment by kachkaev** [comment]
@pomle the issue was missing the link to the [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngBQEMAnQ7ARkwF5MAdEAD3oG5apIoMcCSyAmanRC4WbDlzxFS2AMyD6AL1Ht0WSb2wAWeSELKxqzDBIBzODACqxAJaCA2m0xDicSMQAm1qCfoAaOlBO6tLk-o7cUvxhgREaMtFBPNKabAC6AHQAVhBeABT0SPQAlMwgviAQAA4w1ujIoCTEEADuUghoyLoANs2EuB3lAEakYADW5gDKZHAAMl5wyABmhF1ocEMj4zATlYRgXibIMMQArusgcNiDcO7uNzOE3ieEZgBiEMTYhDA13p2EJxgEDKIAAFjBsF0AOqg6zwNC7MBwCbtOHWABucNwnTAaAGIC8a2IMHwpBMXyWKzW5UyaAYEwOXTgAEUThB4JTVuddsQiZ1BoRrl0QZUbLAodZ3DBQcgABwABnKoogayhpEqnVFcCJ6IW5QAjmz4KSqh0UIQ0ABaKBwG43EEuQ3WFykl4UpDLLnlNbYaxHU7nNCMllGhYeqnnYyDCVSmVIPjlY6EaxdA4AYQg2HdFzQAFYQSc1gAVQVmz3UkDos4ASSgd1gEzANmqAEE6xMYLgmZy1gBfXtAA), which is a mandatory part of the [template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md). Expected output is usually a code block, unless it says something unambiguous like ‘same as input’.

The goal of Prettier is not to make the code look aesthetically perfect but rather to make it look _good enough_ and _the same for everyone_. This is what [_Why Prettier?_](https://prettier.io/docs/en/why-prettier.html) page is trying to communicate.

The result of formatting _usually_ looks prettier, but this is not guaranteed for every edge case. I agree with you that the new lines in your specific example are better than a standalone `":"`, but if we step back and think, is this worth the discussion time?

If you are bothered enough by the formatting, you can try creating a PR with a new test case that is failing. We can then explore what to change in order for your test to pass and see what other tests are now failing. If there are no major regressions for the updated logic, I guess it can be released 🙂

**Comment by pomle** [comment]
@kachkaev, thanks. I'll let you know if I find a solution.
