### ISSUE TITLE
[html][angular] ugly format output for mulity attr and long text

### ISSUE THREAD

**Issue by ecuplxd** [prettier/prettier#12161]
**Prettier 2.5.1**

```shell
--parser angular
```

**Input:**

```html
<label
  nz-checkbox
  class="class"
  formControlName="formControlName"
>long long long text</label>
```

**Output:**

```html
<label nz-checkbox class="class" formControlName="formControlName"
  >long long long text</label
>
```

**Expected behavior:**

```html
<label nz-checkbox class="class" formControlName="formControlName">
  long long long text
</label>
```

or

```html
<label nz-checkbox class="class" formControlName="formControlName">long long long text</label>
```

**Comment by duailibe** [comment]
This is the expected behavior. Prettier can't change `>long` to `>\n   long` because those aren't equivalent. See https://prettier.io/docs/en/options.html#html-whitespace-sensitivity

You can set `--html-whitespace-sensitivity ignore` if this transformation is safe in your case.

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QHSgAIioAvAWjAAs4wBrbCAD0JLCwGdOBefcLp35siAMwgAnALYBhaDAkR0AOUxS4fEOOlzYilWrjCoAPnTQA5kXNQrNq-GYxUAeiy50JkABoQEAA4wAJbQnMigmBKKAO4ACpEIYSiYAG4QQQAmPiDYEpgMcDAAyoYAMkFQcMiimOiccL65+fSFRf75FRbICgCuDSBwUrgZGXAZpZi2PZgWcABiklKYMMG2yCCYPTAQ2dQwUugA6tRB8JztYHBFiadBKacAnutBFlCSVb4V9RIwsXkWS2qtXqvgAVpxmEVOug4ABFHoQeBAur9doSb7rSYWHpYCTZfwSCowQ6ZGDUZAADgADL4CRB6oc8v51gS4N8Uh8QABHBHwP4BJIbTgUSpjMbZCRwHlBSV-GaApA1FG+epSILdCR9FXQuG8qqK4H9GA4EkZMnIABMvgUmCC6E6cikCpAb0q2R69QAKjgkkqQSAUn0AJJQUawIpgQmBACCoaKMAeMOR-vBzAAQnkCsUyhV9X64ABfAtAA)

```sh
--parser angular
--html-whitespace-sensitivity ignore
```

**Input:**

```html
<label
  nz-checkbox
  class="class"
  formControlName="formControlName"
>long long long text</label>
```

**Output:**

```html
<label nz-checkbox class="class" formControlName="formControlName">
  long long long text
</label>

```
