### ISSUE TITLE
Default 80 character line limit is too limiting

### ISSUE THREAD

**Issue by sarthakgaur** [prettier/prettier#12424]
I think it's really time that the default print width should be changed. I find the 80 character line width too limiting. I would recommend you guys to read this article [80-characters-per-line limits should be terminal, says Linux kernel chief Linus Torvalds](https://www.theregister.com/2020/06/01/linux_5_7/).

If Linus Torvalds is not in favor of 80 character limit in C, we should seriously consider changing this. Also, keep in mind that in C, people tend to write very short variable names. And, we should not write JavaScript like we write C. If I have a variable called `permission`, I should not rename it to `perm` just to make sure I do not go beyond the 80 character line limit.

I just want to add that I take code quality very seriously. I refactor my code very often. I follow most of the tips given by Robert C. Martin. I keep my argument list short, my functions small, and avoid deep nesting. I also indent my code by only 2 spaces. And, even after doing this I hit the character line limit very often. My only remaining option is to shorten my variable names. Which is something I don't like doing. I think variable names should be as explicit as possible.

I know I can change the Prettier configuration to my needs. But, that's not the point. It's about changing conventions. It's 2022, not 1980's. We should stop following these conventions and recommending these to people. I think setting the limit to at least 90 characters should be considered.

**Comment by Josh-Cena** [comment]
I down-voted because 80-character still has its values.

- The print width is a target, not a limit. Print width of `120` leads to huge chunks of text that doesn't look very lean and neat.
  - See Prettier's explanation: https://prettier.io/docs/en/options.html#print-width
- GitHub diff viewer still wraps around 80 characters (85, to be exact). Using `120` means the lines don't line up cleanly.
- Linus is also fond of 8-space indents (IIRC) which is why 80 characters width would be terrible for him.

**Comment by sarthakgaur** [comment]
@Josh-Cena

> The print width is a target, not a limit. Print width of 120 leads to huge chunks of text that doesn't look very lean and neat.

I am not sure why you are using 120 print width in your comment. I suggested a limit of at least 90 characters. So, 90-95 looks fine to me. But, 120 will not look good. Counter to your argument, excessive line breaks are bad. In Prettier, if a function call takes 81 characters, it will split it into multiple lines. So, now it ends up taking 5 lines because of 1 extra character. This doesn't look clean at all and is difficult to read.

> Linus is also fond of 8-space indents (IIRC) which is why 80 characters width would be terrible for him.

We don't have to agree with every single thing he says or does. But, his reasoning on this topic is really good.

**Comment by Josh-Cena** [comment]
Suggesting 80 -> 90 width makes even less sense than 80 -> 120. The truth is, the arbitrarily-drawn line is always there. If you configure `"printWidth": 80`, a function taking 81 characters is split into multiple lines. If you configure`"printWidth": 90`, a function taking 91 characters is split into multiple lines. Is there evidence that there are a significant number of function calls that are exactly between 80 characters and 90 characters long?

A lot of people argue that the width should be widened to 120 characters because on a high-resolution wide screen 120 characters would make two windows stack side-by-side pretty nicely. But if the only arguments are (a) aesthetic aversion to excessive line breaks and (b) Linus dislikes it as well, I can't see how Prettier is able to line up everyone's aesthetic preferences.

**Comment by fisker** [comment]
You can config a wider `printWidth` throw config file.

**Comment by sarthakgaur** [comment]
@Josh-Cena The problem is that the number 80 is being touted as some magical number that is perfect. Then there are tools that are designed around that number. If in the 1980's, the width of the terminals were 70 characters, then that would become the standard.

> Suggesting 80 -> 90 width makes even less sense than 80 -> 120. The truth is, the arbitrarily-drawn line is always there.

It's difficult to decide what the new number should be. Should it be 90 or 100 or 120? Many factors should be taken into consideration when deciding this. What's the average resolution of the monitors that are currently being bought? How many multiple windows does a programmer open side-by-side on average? When does a line become so long that it becomes difficult to read and follow? There could many other factors that could be taken into account.

No, it's not an arbitrarily-drawn line. If the standard is backed by reason and data. I went with the number 90 as it's a small increment from the current standard. But, if the data gives us a different number, then I would go with that. The point is the standard should change according to time.

> If you configure "printWidth": 80, a function taking 81 characters is split into multiple lines. If you configure"printWidth": 90, a function taking 91 characters is split into multiple lines.

Yes, you can run into this problem with any number. But, then I won't be following some magical number.

> Is there evidence that there are a significant number of function calls that are exactly between 80 characters and 90 characters long?

The JavaScript (not TypeScript) code I have written so far I very rarely go beyond the 90 character limit. I refactor my code very often, and follow most of the good coding practices. But, I am finding it difficult to keep my lines shorter than 80 characters. As I said before, my only option is to shorten my variable names. Which is not a good solution.

> A lot of people argue that the width should be widened to 120 characters because on a high-resolution wide screen 120 characters would make two windows stack side-by-side pretty nicely. But if the only arguments are (a) aesthetic aversion to excessive line breaks and (b) Linus dislikes it as well, I can't see how Prettier is able to line up everyone's aesthetic preferences.

I have the problem with the number 80. Is that number backed by any data? Does that data consider the hardware people are currently using? The commonly used programming languages that programmers use these days?

No, I am not saying this because Linus says so. There are plenty of things he has said that I disagree with. I am saying his reasoning for objecting to this standard sounds very reasonable. Did you read the article?

**Comment by Josh-Cena** [comment]
I gave one concrete case where 80-character is desirable: the GitHub diff viewer, which wraps at 80 characters. 90 characters look just as terrible as 120, maybe even worse because of that tiny overhang. In the end, if you are unsatisfied with the default, you can always give an option. The Prettier documentation is already very clear on why 80 characters is chosen, and it unfortunately has nothing to do with terminals. No-one here is talking about terminals.

**Comment by sarthakgaur** [comment]
> I gave one concrete case where 80-character is desirable: the GitHub diff viewer, which wraps at 80 characters.

Again, this is just an example of a tool that is designed around that magical number.

> 90 characters look just as terrible as 120, maybe even worse because of that tiny overhang.

Again, I went with 90 characters just as a guess. The actual number should be backed by data and research.

> The Prettier documentation is already very clear on why 80 characters is chosen, and it unfortunately has nothing to do with terminals. No-one here is talking about terminals.

Yes, I have read that. It doesn't say much. Where did the 80 number come from?

**Comment by Josh-Cena** [comment]
> Again, this is just an example of a tool that is designed around that magical number.

Persuade the other tools to change that number first, then. Again, you can already configure this in Prettier, if you never use those tools and something longer than 80 works for you—it doesn't work for the rest of us, who are hopelessly bound to these tools that rely on 80-character width. It's not like I don't like keeping my stuff on the same line, but you have to make compromises with other things.

> The actual number should be backed by data and research.

What kind of research? For whatever limit you set, there will be a significant fraction of code that wraps just above that line, and that fits just below. Given the amount of JavaScript existing out there, it's safe to assume that `Ord({x | Lines with width > x}) → ∞` for all `x > 80`. Just settle on something good for you, and move on. The maintainer has already closed the issue and I think that's a clear enough position.

> Yes, I have read that. It doesn't say much. Where did the 80 number come from?

It's implied: style guides and eslint's `max-len` can require max width 120, because writers can choose to wrap code that doesn't hit that limit even when on the same line. Prettier has no choice, and the far majority (I've talked to a lot of developers about print width settings before) think that on a regular laptop screen, 120 characters just look too dense. (Again, 80 vs. 120 is the only meaningful discussion because 80 vs. 90 has virtually no contrast and looks just as arbitrary)

**Comment by fisker** [comment]
I'm going to lock this issue, since we are not going to change the default value this discussion is meaningless.
