### ISSUE TITLE
Bad format when a link has very long text in vue file

### ISSUE THREAD

**Issue by kuoruan** [prettier/prettier#12555]
**Prettier 2.6.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmpYnkWV6EAqAFgJYDOZHZeZAbnABOAT35DRAkWKmSJ46XJnzZCsjmgBzNaygBrVAHoGAOlJ1KB6qUOZcBOIRAAaEBCwxW0dslB5BgiAB3AAU-BG8UPBxAvGFvFwAjQTwwXTgYAGU8DDgAGR04ZAAzKPY4ROTU9IysFJ0NZBhBAFdykDgMBLgAE26e3LwoDWa8DTgAMQhBDAIPIeQQPGaYCGcQZhgMHAB1Nnh2WrA4DPDWDz4z4QWwdniQHTLBGGDkjRni0raAK3YADwz6jg4ABFZoQeAfHBlFy1QSPBZ8VprLCCHQwbasbowZjIAAcAAYYQEyttklgFii4I8BGsAI5g+AvNwRRbsAC0UDgPR6a0EcHprD5L1G7yQJShbTKGFYjRaksBIIZhTFnxcMDwCQxWJxSAATGrkqwcPUAMIQDCi9rsACsa2aZUYGoi4uhIERcAAklA+rAMmBUe4AILejIwYRAyFlAC+UaAA)

**Input:**

```vue
<template>
  <p>
    <a>This is a very very very very very very very very very very very long link</a>.
    </p>
</template>
```

**Output:**

```vue
<template>
  <p>
    <a
      >This is a very very very very very very very very very very very long
      link</a
    >.
  </p>
</template>
```

**Expected behavior:**

```vue
<template>
  <p>
    <a>
      This is a very very very very very very very very very very very long link
    </a>
    .
  </p>
</template>
```

**Comment by fisker** [comment]
The "expected behavior" adding space to text.

**Comment by kachkaev** [comment]
@kuoruan in HTML, unlike in JSX, extra spacing around `<>` do count. Try displaying `hello<span>world</span>!` next to `hello<span> world </span>!` (or replace spaces with new lines). The result will be different.

Prettier aims to keep the result, hence it needs to print `>This` and `link</a` instead of `>[newline or space]This` and `link[newline or space]</a`.
