### ISSUE TITLE
Function argument output is different, depending on object block formatting

### ISSUE THREAD

**Issue by joecritch** [prettier/prettier#1273]
In this scenario, the output of the code is actually dependent on the code itself; rather than just Prettier's config options. Is this a feature, or...?

_Reproduced with `prettier 1.1.0`. (And possibly the same in older versions.)_

When the `{ a }` object has its braces their own lines (like below), Prettier doesn't reformat:

```javascript
class App {
  method(a) {
    this.setState(
      {
        a
      },
      () => cb()
    );
  }
}

```

However, when the `{ a }` is all on the same line...

```javascript
class App {
  method(a) {
    this.setState(
      { a },
      () => cb()
    );
  }
}
```

Prettier reformats all arguments to be on the same line:

```javascript
class App {
  method(a) {
    this.setState({ a }, () => cb());
  }
}
```

**Comment by demoneaux** [comment]
Prettier tries to maintain some consistency in terms of newlines within arrays and objects. If you have an object with braces on it own lines, it keeps them expanded, while if the object is defined in 1 line and does not hit the line length limit, it will keep it in the same line.

**Comment by jlongster** [comment]
This is, unfortunately, one rare case where prettier respects the original formatting. If an object in the original source is expanded already (there's any newline in it) we will keep it expanded. And if the object is expanded, it expands all parents too.

This is needed because objects in JS are used for too many things. There are a lot of times where you have a list of lots of little objects and for consistency you keep them all expanded. We had too many complaints by always collapsing them (even if I prefer it).

The unfortunate side effect is that it's not quite as deterministic. But this is expected behavior!
