### ISSUE TITLE
chaining / functional programming not so pretty

### ISSUE THREAD

**Issue by uriva** [prettier/prettier#1275]
compare

```
const contactsMap = contacts
  .filter(c => c.phoneNumbers.length)
  .reduce((map, contact) => {
    contact.phoneNumbers
      .filter(entry => entry.number)
      .forEach(entry => {
        const countryCode = entry.number.startsWith('+') ? '' : defaultCountryCode;
        const normalizedPhone = phoneLib(entry.number, countryCode)[0];
        if (normalizedPhone) {
          map[normalizedPhone] = { ...contact };
          map[normalizedPhone].label = entry.label;
        }
      });
    return map;
  }, {});
```

and

```
const contactsMap = contacts.filter(c => c.phoneNumbers.length).reduce((
  map,
  contact
) => {
  contact.phoneNumbers.filter(entry => entry.number).forEach(entry => {
    const countryCode = entry.number.startsWith('+')
      ? ''
      : defaultCountryCode;
    const normalizedPhone = phoneLib(entry.number, countryCode)[0];
    if (normalizedPhone) {
      map[normalizedPhone] = { ...contact };
      map[normalizedPhone].label = entry.label;
    }
  });
  return map;
}, {});
```

**Comment by jlongster** [comment]
Hm, do you mind trying version 0.22? We have special logic for this type of pattern and I thought that it should keep your original style. I'm curious if this is a regression with 1.0.

**Comment by demoneaux** [comment]
This is probably due to an older version of Prettier. Testing in the online demo which runs the latest Prettier ([link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20contactsMap%20%3D%20contacts%5Cn%20%20.filter(c%20%3D%3E%20c.phoneNumbers.length)%5Cn%20%20.reduce((map%2C%20contact)%20%3D%3E%20%7B%5Cn%20%20%20%20contact.phoneNumbers%5Cn%20%20%20%20%20%20.filter(entry%20%3D%3E%20entry.number)%5Cn%20%20%20%20%20%20.forEach(entry%20%3D%3E%20%7B%5Cn%20%20%20%20%20%20%20%20const%20countryCode%20%3D%20entry.number.startsWith('%2B')%20%3F%20''%20%3A%20defaultCountryCode%3B%5Cn%20%20%20%20%20%20%20%20const%20normalizedPhone%20%3D%20phoneLib(entry.number%2C%20countryCode)%5B0%5D%3B%5Cn%20%20%20%20%20%20%20%20if%20(normalizedPhone)%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20map%5BnormalizedPhone%5D%20%3D%20%7B%20...contact%20%7D%3B%5Cn%20%20%20%20%20%20%20%20%20%20map%5BnormalizedPhone%5D.label%20%3D%20entry.label%3B%5Cn%20%20%20%20%20%20%20%20%7D%5Cn%20%20%20%20%20%20%7D)%3B%5Cn%20%20%20%20return%20map%3B%5Cn%20%20%7D%2C%20%7B%7D)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)) seems to work fine.

**Comment by uriva** [comment]
latest version indeed is good
thanks and keep this holy work
