### ISSUE TITLE
Additional indentation in object props inside ternary

### ISSUE THREAD

**Issue by yamafaktory** [prettier/prettier#1280]
```js
const a = test > 1337
  ? 'yeah'
  : {
    b: 'foo',
    c: 'bar'
  }
```

is turned into

```js
const a = test > 1337
  ? 'yeah'
  : {
      b: 'foo',
      c: 'bar'
    }
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20a%20%3D%20test%20%3E%201337%5Cn%20%20%3F%20'yeah'%5Cn%20%20%3A%20%7B%5Cn%20%20%20%20b%3A%20'foo'%2C%5Cn%20%20%20%20c%3A%20'bar'%5Cn%20%20%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by bakkot** [comment]
Incidentally, this looks related to https://github.com/prettier/prettier/issues/1271. (Not a dupe, they're just related.)

**Comment by jlongster** [comment]
I think it is a dupe. This is intentional for the same reasons as described in that issue. Aligning the end brackets with `:` and `?` make the structure less clear, but I'm not really that opinionated about it.

We're going to experiment with different ways of formatting ternaries though, so this is likely going to be voided by that.

**Comment by vjeux** [comment]
I'm going to close this and concentrate all the ternary discussions in #1271
