### ISSUE TITLE
[MemberExpression] chained methods on single line

### ISSUE THREAD

**Issue by highflying** [prettier/prettier#1282]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20somePromise%20%3D%20promise%5Cn%20%20.resolve()%5Cn%20%20.then(console.log)%5Cn%20%20.catch(err%20%3D%3E%20%7B%5Cn%20%20%20%20console.log(err)%5Cn%20%20%20%20return%20null%5Cn%20%20%7D)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Trying to understand how this:

```js
const somePromise = promise.resolve().then(console.log).catch(err => {
  console.log(err)
  return null
})
```

is considered more readable than this:

```js
const somePromise = promise
  .resolve()
  .then(console.log)
  .catch(err => {
    console.log(err)
    return null
  });
```

Doesn't feel like it matches up with how clean code should be (based on the Clean Code and Code Complete books)

**Comment by SimenB** [comment]
Might be kinda related to #1099?

**Comment by vjeux** [comment]
Thanks for reporting this. It's indeed harder to read. This one is a bug that's going to be tricky to fix.

The rule we have is that if the expression is more than 80 columns, then expand. Unfortunately, we use a special implementation for last argument expansion where we "hide" the body (things inside of `{}`) so the parent only sees

```js
const somePromise = promise.resolve().then(console.log).catch(err => 
```

which fits in 80 columns, so we display it as is.

I may have some idea though, I'll see if it works.

**Comment by jlongster** [comment]
I think at some point we just have to say that we're doing applying bandaids. If we keep trying to fix every specific situation with member expressions we're going to be juggling some very fragile code. This code in my opinion is readable enough in the original version that I think we should just accept it.

**Comment by SimenB** [comment]
I would like to see some formatting applied to chained methods. I think that might help a few cases where today's one-lining (as seen in this issue) makes things less readable.

Eslint rule: http://eslint.org/docs/rules/newline-per-chained-call

**Comment by mo** [comment]
https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20myStr%20%3D%20originalStr.trim().toLowerCase()%3B%5Cn%5Cnconst%20usedAndLinked%20%3D%20allMyitems%5Cn%20%20%20%20%20%20%20%20%20%20.filter(item%20%3D%3E%20_.includes(someList%2C%20item.id))%5Cn%20%20%20%20%20%20%20%20%20%20.map(item%20%3D%3E%20item.price)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A120%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Given the 2 examples in the link I'm pasting, I lean towards wanting a single line for the .trim().toLowerCase() but I do want chaining for the .filter() plus .map() expression even if both are shorter than my line length of 120 chars. I think this is because .map() and .filter() with fat arrows usually have a bit more complexity in them so that's why I prefer to keep them on separate lines.

Spawning some ideas here, maybe prettier could use "one line per invocation if at least one parameter to one of the chained calls is a fat arrow or anonymous function"?

Or maybe its better to default to one line per chained function invocation, and then say "prettier can put the entire chain one a single line if and only if A) the entire chain is shorter than LINE_LENGTH, and also B) all function invocations in the chain take 0 arguments". That would at least solve the basic case for getting foo.trim().toLowercase() on a single line.

If you really want to avoid complexity, I think I would rather have it always do "one line per invocation" even for foo.trim().toLowerCase() compared to the existing behavior.

**Comment by vjeux** [comment]
@mo I highly recommend using 80 columns for prettier. The way it works is by trying to cram as much content in the max width. It usually looks good for 80 columns but as you increase the limit, it starts looking bad with many issues like the one you are reporting.

**Comment by btoast** [comment]
This chaining is preventing adoption for us.  The line limit is the simple compromise but more intelligence to new lines wouldn't be bad either.

**Comment by xixixao** [comment]
Some more examples:
```es6
const M = {
  updateOptimizationOption(placementID: FBID, option: string): Promise<Object> {
    return SomeRanAPI.get(module.id)
      .object('somePlacement', placementID)
      .post({fancy_setting: option});
  },
}
```
output:
```es6
const M = {
  updateOptimizationOption(placementID: FBID, option: string): Promise<Object> {
    return SomeRanAPI.get(module.id).object("somePlacement", placementID).post({
      fancy_setting: option,
    });
  },
};
```
^ should be fixable.


And very simple:
```es6
SomeNiceAPI.get(module.id)
  .object('app', appID)
  .edge('some_placements');
```
out:
```es6
SomeNiceAPI.get(module.id).object("app", appID).edge("some_placements");
```
^ That's probably just correct. But looking at our API files if I format them, they do become slightly harder to read. I guess that's the classic "alignment" trick, which prettier won't be able to to replicate (while being objective).

**Comment by rattrayalex** [comment]
Is there a pr link where the special behavior @vjeux mentioned was added? Might be curious to take a dig at this.
