### ISSUE TITLE
Are any plugins while use d3.js ?

### ISSUE THREAD

**Issue by litinskii** [prettier/prettier#1283]
Are any plugins while use d3.js ?

**Comment by vjeux** [comment]
Hey, I'm not really sure what you have in mind with d3? Could you expand.

**Comment by finetype** [comment]
My guess would be that when one is writing d3, which features function chaining very heavily, one might desire slightly different formatting.

**Comment by vjeux** [comment]
Going to close this as it's not actionable.

**Comment by Peeja** [comment]
[Here's an example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAYgJwgWwwAsYYAHAZyXQCM4YBDAOghorhwDcGaAbOIgEcmkfKgAC+GhAowIYANaoA5r1YNeAWnj4yHBjACuOONpNQAJhQA6UW8FsYMkKLIwVOyjAF4MFgMxM7PxgMAAUACIA8gCyQZ5hAO4AlhYwRAA0xHDJyiQAlPkA3I4YpR7KTAxkepZh1iDKDfmlTk4iGrxhAB4Agt3JFMWl5Z5VNQgW9Y3NrW0dvF0Anv2Dw1BOo5XVtVMNTSAtG23tBjA407J4CnANWQ0AxAAML7PHJ1WkFw1XEDeaEDIDDAyRgSzuGCeTAATEcPsE4KFeotpiCcGB+G8PhYDAwwjjGHD5gh4Bd8uNdqjkujMYc5qcvqjuhCLD4AHwYbr4pgEuCFekYT7nVHgkBZVneDlLbncXiGPlEj5nb4gABmyUWLPZGAAXjKNPL+e95srpjgIdCmABWdabY4mIw4DYVJhQCAWOBhdYAXzFIEBMGS0AoyFADBweESAAVwwgQygGJwIKk-QxZMhVRp2BkQDQcMCbjAAMpAkFQZTIc7ynMWeQZrNwHPJVwcGBR-PKfAMeu8bMgABWFG6ACF84p6EWGPg4AAZZtwHt9iCGcgr6GLxsgIE4dg4ZC5nhLNRQP1kHDNmAAdVS6WQAA4njmzzI4Jf82R92e4LvOAucyZBEMak4HbBhO27JBM17Td2HwZJKxwasQAoZtVDgABFQwIHgDcc0YGhrzSIhkGhPD8w1VCAGECC7fc3SgP8QEMdgABUeHjKD2G9b0gA):

```js
// From https://beta.observablehq.com/@mbostock/global-temperature-trends

{
  const svg = d3.select(DOM.svg(width, height));
  
  svg.append("g")
      .call(xAxis);
  
  svg.append("g")
      .call(yAxis);
  
  svg.append("g")
      .attr("stroke", "#000")
      .attr("stroke-opacity", 0.2)
    .selectAll("circle")
    .data(data)
    .enter().append("circle")
      .attr("cx", d => x(d.date))
      .attr("cy", d => y(d.value))
      .attr("fill", d => z(d.value))
      .attr("r", 2.5);
  
  return svg.node();
}
```

It's idiomatic in d3 to use indentation to signify the nesting as you descend into specific contexts, but that structure isn't reflected in the structure of the JavaScript AST. You have to understand the chaining API and which methods should cause a change in indentation.

It would be handy if a plugin of some sort could specify that behavior. It would also help you check your work, if you thought you were at a different point in the tree than you meant to be (because the indentation would be different from what you expected). But I can also imagine that this style of indentation might be out of scope for Prettier.

**Comment by vjeux** [comment]
There is a similar request for `h(` in order to write JSX without it.

**Comment by 1wheel** [comment]
I'd be okay dropping the indention convention if there was a way to prevent a new line after `d3.`

This:
```
d3.scaleLinear()
  .domain([1950, 1980])
  .range([0, width])

d3.select('body')
  .append('circle')
  .at({width: 30, fill: '#f0f'})
  .st({fontWeight: 600})
```

goes to this, which looks blah:

```
d3
  .scaleLinear()
  .domain([1950, 1980])
  .range([0, width])

d3
  .select('body')
  .append('circle')
  .at({ width: 30, fill: '#f0f' })
  .st({ fontWeight: 600 })
```

**Comment by j-f1** [comment]
How about not breaking after the identifier if it’s shorter than `tabWidth`?

**Comment by suchipi** [comment]
We could also add "d3" to the logic which detects factory functions.

**Comment by 1wheel** [comment]
Special casing `d3` seems a little arbitrary; I made a pull request implementing @j-f1's suggestion.

**Comment by thorn0** [comment]
Closing in favor of #4424
