### ISSUE TITLE
CLI run with --write deletes file

### ISSUE THREAD

**Issue by jeresig** [prettier/prettier#1287]
A side effect of #1250 is that I discovered an issue where files are sometimes accidentally deleted when the CLI is aborted mid-run.

To reproduce I ran the CLI with `--write` against ~130 files. I intentionally made a change in the first file that would be fixed by prettier. I then let the script run but hit `Ctrl^C` part-way through (aborting before completion). Looking at the file that changed I see that the entire contents of the file have been removed (although the file is still there).

Seemingly the contents of the file are removed once a change is detected - however the new contents aren't written out until after all of the files are processed. This seems like it might causes problems as it could potentially result in lost data. (Once I figured out what was happening it was an easy fix to just re-checkout the code from Git and run prettier again - although I suppose that may not be the case for everyone!)

**Comment by jeresig** [comment]
Ah, looking at the code now I see that all of the file reads happen synchronously whereas all of the writes happen asynchronously! This seems tricky for a couple reasons: when the `writeFile` is run the contents of the file are removed however the new contents aren't written until the synchronous operation ends, additionally this leaves a descriptor open to the underlying file. If this was run across many hundreds of files I'd imagine that it would result in an EMFILE error.

The easy solution would be to make the write synchronous but perhaps there are other issues at play that I don't understand. Let me know if you'd like a PR to that effect!

**Comment by vjeux** [comment]
The original code was all asynchronous and someone accidentally ran it across the entire node modules folder and ran out of file descriptors. So we switched to making the read asynchronous.

Since prettier is CPU bound and not IO bound, we're not really getting anything from having any of them asynchronous. Also performance isn't a huge concern. If making them synchronous fixes the issue, we should do that.

Otherwise, I'm not sure if we can catch SIGINT signal in node. If we can, we could stop any new files from being processed and wait until all the writes have been done. But that doesn't seem trivial.

**Comment by umidbekkarimov** [comment]
I also faced this issue from day one. But it's really really hard to replicate. 
And i'm using webstorm ide which has it's own technique of saving files, so I thought it's maybe integration problem.

**Comment by umidbekkarimov** [comment]
> But it's really really hard to replicate.

I guess it was true because of async read+write, now it's only async write and it's really easy to replicate this bug.

**Comment by jeresig** [comment]
I've put up a PR to fix this issue in #1292, feedback most welcome!
