### ISSUE TITLE
Adds Unnecessary Brackets in JSX arrow function

### ISSUE THREAD

**Issue by dodekeract** [prettier/prettier#1291]
```javascript
const Component = () =>
	<div>
		Example!
	</div>

const WhyNotHere = () =>
	'some long string so that we reach the maximum width of the line.........................................................'
```

Gets converted to:

```javascript
const Component = () => (
	<div>
		Example!
	</div>
)

const WhyNotHere = () =>
	'some long string so that we reach the maximum width of the line.........................................................'
```

I'm assuming this is a bug, otherwise, it's definitely inconsistent code-style.

*Note: I'd prefer if prettier doesn't add any brackets here. Second best is when it always adds brackets. I don't think being inconsistent makes sense at all.*

**Comment by Haroenv** [comment]
I’m pretty sure that this is on purpose, see https://github.com/prettier/prettier/issues/73

**Comment by dodekeract** [comment]
@Haroenv I agree - it looks intentional. I have no idea why that intention exists though.

Prettier removes a lot of unnecessary brackets, especially in Boolean expressions. Why insert some here where it's obvious?

**Comment by vjeux** [comment]
For parenthesis around JSX, it is actually a long story.

It all starts with JavaScript automatic-semi-colon insertion and `return`. Most people don't know that the following

```js
return
  <div>
  </div>;
```

is going to be evaluated as

```js
return;
<div>
</div>;
```

by JavaScript.

In practice, in normal JavaScript, it is very unlikely to write code that will trigger this rule. However, for JSX it's actually very common. The way a lot of people chose to write their return statements with JSX is in the following way:

```js
return (
  <div>
  </div>
);
```

Another option would be to write

```js
return <div>
  </div>;
```

but it's way less common.

Because those parenthesis are unusual, a lot of people get confused and think that they are actually required for JSX and write variable assignment like this:

```js
var elem = (
  <div>
  </div>
);
```

even though those parenthesis are not required. I wasn't very happy about this but most of the codebases we looked at used this form so we are encoding this inside of prettier.

In order to be consistent with this pattern, we're also doing this for arrow functions:

```js
var f = props => (
  <div>
  </div>
);
```

This is not awesome in my opinion but I can live it.

Also, for reference, airbnb style guide enforces () around every single multi-line arrow function, but I think it's overkill. https://github.com/airbnb/javascript#arrows--paren-wrap

I hope that it gives you a good historical background behind this. I don't think that either way makes a big difference so I'm not very keen on changing this past 1.0.

**Comment by xixixao** [comment]
I'd argue that we should look at this from first principles: JSX is no different from other expressions (that's it's strength).

The parens come from
```jsx
return (
  <div>
  </div>
)
```
But JSX is not special here. You would need the same for
```es6
return (
  f(
    a,
    b,
  )
)
```
or
```es6
return (
  x
    ? a
    : b
)
```
But you can see that we are not wrapping wrapping these expressions when using `const` or `=>`.

So, we have this deeply entrenched preference for 
```jsx
return (
  <div>
  </div>
)
```
over
```jsx
return <div>
  </div>
```
This makes sense, because unlike calls or ternaries, the JSX is a pair, and **we would like the starting and closing tags to be on the same indent**.

> **we would like the starting and closing tags to be on the same indent**

^ to stress.

But `const` and `=>` don't have the problem of the return statement, and we can use them without parens, while keeping the opening and closing tag at the same indent.
```es6
const x =
  <div>
  </div>
const Y = props =>
  <div>
  </div>
```
Hence there is no need to add spurious control characters that around brains need to parse. Less is better here. (note that prettier already adopts this in the case of JSX inside ternaries)

**Comment by dodekeract** [comment]
@xixixao Couldn't have said it better, thanks.

**Comment by matthewwithanm** [comment]
imo this is kind of missing the point. In what other situations does prettier put `return` on its own line? Parens here make it consistent.

```js
return {
  // ...
}

return [
  // ...
];

return someReallyLongFunctionThatTheoreticallyWouldWrap(
  // ...
);
```

If we were to follow the convention, yeah, we would do this:

```js
return <div>
</div>;
```

But there's an even stronger convention for XML opening tags to be at the same level as their closing tag. Obviously the parens aren't necessary but they allow us to abide by this (very strong) XML convention, but still maintain the same visual pattern used with other natural JS groupings.

And, honestly, I wouldn't be surprised if the assertions that "people think they're necessary" are exaggerated.

**Comment by vjeux** [comment]
It's been updated with the suggestion, so closing this. Note that we're likely going to revert it though.

**Comment by dodekeract** [comment]
@vjeux Why revert it?

**Comment by azz** [comment]
@dodekeract see the discussion in #1733.
