### ISSUE TITLE
TypeScript missing nodes

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1306]
I ran prettier through all the typescript tests are here are all the typescript-specific nodes that we are not printing yet:

- [ ] TSAbstractClassDeclaration
- [ ] TSAbstractMethodDefinition
- [ ] TSConstructorType
- [ ] TSEnumDeclaration
- [ ] TSFirstTypeNode
- [ ] TSImportEqualsDeclaration
- [ ] TSIndexedAccessType
- [ ] TSInterfaceDeclaration
- [ ] TSIntersectionType
- [ ] TSLastTypeNode
- [ ] TSMappedType
- [ ] TSMethodSignature
- [ ] TSModuleDeclaration
- [ ] TSNamespaceExportDeclaration
- [ ] TSNeverKeyword
- [ ] TSNonNullExpression
- [ ] TSParameterProperty
- [ ] TSSymbolKeyword
- [ ] TSThisType
- [ ] TSTypeOperator
- [ ] TSUndefinedKeyword

If you are interested in helping out with TypeScript, feel free to pick one and start implementing it :)

Here's a full test run: https://gist.githubusercontent.com/vjeux/916791f8489f85035add34ae30e6d30b/raw/82ec3d28f7cd15a3016f43e1d952cf566c67d813/typescript.js (warning, very big)

**Comment by Quantumplation** [comment]
I'd love to try contributing, but I'm a bit lost as to where to start.  Do you have any guidance?

**Comment by O4epegb** [comment]
Me too, any advice for beginners?

**Comment by cypherq** [comment]
@vjeux 👍 - I'm willing to contribute but it would be great if you can leave few tips.

**Comment by vjeux** [comment]
I'll write up something tonight :)

**Comment by JLarky** [comment]
first step is that you can't use `--format typescript` since `bin/prettier.js` checks parser value, so you have to change it to `  if (value === "flow" || value === "babylon" || value === "typescript") {` in order for it to even try working with typescript :)

**Comment by Quantumplation** [comment]
Updating with the things I've learned from poking around, in case it helps anyone else:

 - Needed to make the change that JLarky pointed out.  If someone wants, I can get that change up as a pull request, I don't see much harm in enabling the `--parser typescript` option?
 - The command that vjeux ran to try this out relies on Typescript being cloned adjacent to the prettier repo
 - Here's a little one-liner I put together to get me the distinct unrecognized nodes, so that I could see of my implementation handled it:
```bash
(find ../TypeScript/tests/ -name '*.ts' | grep -v "'" | xargs ./bin/prettier.js --parser typescript --debug-check) 2>&1 | grep -o 'Error: unknown type: ".*"' | sort | uniq
```
- Here's my vscode configuration settings for debugging the existing unit tests:
```json
        {
            "type": "node",
            "request": "launch",
            "name": "Debug Tests",
            "program": "${workspaceRoot}/node_modules/jest-cli/bin/jest.js",
            "args": ["--runInBand"]
        }
```

Things I'm still trying to figure out:
 - The general code flow.  There's a giant switch statement in printer.js starting on line 146, I assume this is where we implement the missing node types?
 - How to write tests for the typescript nodes
 - How to run only a given subdirectory of tests (i.e. so i'm not running 3000 unit tests all the time)
 - What I actually need to *implement* for each node! :sweat_smile:

**Comment by vjeux** [comment]
Sorry for the lack of update, I looked into it and it's a bit more complicated. We are missing "ast-types" definitions for typescript so it throws earlier. We need to get that sorted first before we can actually print the nodes themselves.

cc @Pajn, @ChristopherBiscardi and @JamesHenry who have done more work on TypeScript than I did.

**Comment by ChristopherBiscardi** [comment]
With respect to ast-types, @Pajn has some work in an [Issue](https://github.com/benjamn/ast-types/issues/213) and [branch](https://github.com/Pajn/ast-types/commit/2e2a468e4283e69e1d11c71c25e2e61c4b4ee1cf). Not sure what he's intending to do with that right now though.

As for what [keys](https://github.com/eslint/typescript-eslint-parser/blob/dd57f811e23369cb6e18455d23babd2bdde315d2/lib/ast-converter.js#L1091-L1102) to include in a parsed TS SyntaxKind, that seems almost arbitrary. For example, it's hard to reconcile [class properties](https://github.com/eslint/typescript-eslint-parser/blob/dd57f811e23369cb6e18455d23babd2bdde315d2/lib/ast-converter.js#L1091-L1102) with something in the ESTree spec. Especially when you have to look through N files to find all the extensions.

**Comment by JamesHenry** [comment]
@ChristopherBiscardi In cases where there is no precedent in ESTree, Flow's equivalent AST will have been used as inspiration.

There are, of course, cases where neither Flow nor ESTree have a precedent. For those, it will have either been a likely subjective, but hopefully logical best-guess, and/or a straight copy from the original "TSNode".

**Comment by despairblue** [comment]
Just a heads up on what is happening. I'm in the process of adding simple printer implementations for the nodes that `ast-types` knows about already. Those are accompanied with really simple test cases. After most of them are done I plan to use prettier on our code base at work (not big, but uses most of the arcane type features like `Pick` or `keyof`) and iron out the corner cases I missed (I don't understand half the AST at the moment).

There are a handful of nodes that cannot be supported by prettier for now since the implementation in `ast-types` is missing. 

If someone wants to add the missing nodes to `ast-types` that would be pretty awesome, especially `TSInterfaceDeclaration` is one that is used fairly often.

Also adding printer implementations is pretty straightforward. Have a look at the PRs, if anyone wants to take on one of the other nodes, just drop a line here so we don't duplicate the effort :) 


## Missing Printer Implementation

* [ ] TSAbstractClassDeclaration
* [ ] TSAbstractMethodDefinition
* [x] TSConstructorType (not merged yet #1367)
* [x] TSFirstTypeNode (#1332)
* [x] TSIndexedAccessType (#1370)
* [ ] TSIntersectionType
* [x] TSLastTypeNode (#1370)
* [ ] TSMappedType
* [ ] TSMethodSignature
* [ ] TSNamespaceExportDeclaration
* [x] TSNeverKeyword (#1331)
* [x] TSNonNullExpression
* [ ] TSParameterProperty
* [x] TSSymbolKeyword (#1331)
* [x] TSThisType (#1331)
* [ ] TSTypeOperator
* [x] TSUndefinedKeyword (#1331)


## Missing in `ast-types`
 
* [ ] TSEnumDeclaration
* [ ] TSImportEqualsDeclaration
* [ ] TSInterfaceDeclaration
* [ ] TSModuleDeclaration

**Comment by Quantumplation** [comment]
Awesome, thanks despairblue! After work today I'll pick one and start working on it! :D

**Comment by azz** [comment]
I have implemented:

  * [x] `TSParameterProperty`
  * [x] `TSAbstractMethodDefinition`
  * [x] `TSAbstractClassDeclaration`

**Comment by frederickfogerty** [comment]
@despairblue most of those in your comment above are done now that #1459 is closed, right?

**Comment by vjeux** [comment]
Closing this one. Next steps are in #1480 :)
