### ISSUE TITLE
Option for retaining blank lines

### ISSUE THREAD

**Issue by ViRuSTriNiTy** [prettier/prettier#13301]
Hi there,

I am having the same issue as #554. Pettier pretty much glues lines in a block into an unreadable mess. Empty lines are often used by me to allow for easier skimming. If one (like me) would read and review a huge mount of code each day the one would surely agree. 

Since #554 was auto closed and thumbs up cannot be assigned anymore I needed to create a new issue to vote for a new option, also because of

> Remember, when a new option is suggested, I'd say it will be rejected 99 times out of 100. After a couple of months of 👍s, **a few miles of GitHub comments and a bunch of duplicate issues, then it might be added**

So lonG

**Comment by thorn0** [comment]
Without any code examples, it's not clear what you mean. Prettier does retain blank lines.

**Comment by kachkaev** [comment]
Please see https://prettier.io/docs/en/rationale.html#empty-lines. You can find [a few more related discussion](https://github.com/prettier/prettier/search?q=%22https%3A%2F%2Fprettier.io%2Fdocs%2Fen%2Frationale.html%23empty-lines%22&type=issues) via search.

**Comment by danielrlc** [comment]
+1 for "retaining more a single blank line". This is the formatting decision in Prettier that's being questioned:

"Prettier collapses multiple blank lines into a single blank line."

I don't think Prettier should have any opinion on this at all. Like @ViRuSTriNiTy, I like to leave 3-line gaps between important sections of code to make it easier to parse. For some, this is clearly not remotely important, but for me, it's hugely important. It makes the code far, far easier for me to read.

I'm not alone. These excellent CSS Guidelines by Mr "CSS Wizardry" Harry Roberts advocate 5-line gaps between major sections: https://cssguidelin.es/. Not quite ready to step up to 5 lines myself - strictly for the pros that one, I think. ;)

**Comment by kachkaev** [comment]
Sorry folks I am going to close this issue. You can refer to links [in the above comment](https://github.com/prettier/prettier/issues/13301#issuecomment-1219702306) for details. Feel free to read Prettier’s [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html) doc as well for additional background on this decision.

**Comment by danielrlc** [comment]
Well we tried @ViRuSTriNiTy :) Thanks @kachkaev for replying and clarifying Prettier's position and pointing to older discussions on the topic. I'm a huge fan of Prettier and agree very strongly with all its other opinions, but still think this is completely the wrong call here, even after reading all the older discussions about it. That said, let's agree to disagree, as they say. :)

**Comment by saminton** [comment]
> 

I agree. While I understand that the rest of the code is formatted and should stay opinionated. Overriding intentional line spacing feels more like an accessibility flaw. I have a hard time reading code that is all bunched up. The main reason for me using prettier is to make the code more readable and accelerate my work process, I often find remove my line breaks does the contrary and I have to take extra time figuring out which bunch of code is doing what.

A prime example is in Vue files where I intentionally add space between each language.

![191584579-a0f6a885-fdf3-4581-9bbf-3191f9e1f97f](https://user-images.githubusercontent.com/15970757/191801711-1420db62-18e2-4085-a049-3c783c6774e5.png)

I do see a problem where, if we had the option to disable it, coworkers could lines all over the place and slightly defeat the purpose on prettier. But on the other hand, prettier in ment to make code more accessible and fails to do so here imo.

I do think a flat out NO is rather unfair considering this keeps popping up as a feature request and that this deserves at least some thought before being ruled out.

Maybe a better solution would be to have some sort of way of adding additional intentional new lines at specific points ? Or have it do it automatically ? While rather simple in the case of Vue files, I imagine that would be a lot harder to implement in other cases, what counts as a "section" of code ?

**Comment by Nicitaa** [comment]
No way to add spaces
![image](https://github.com/prettier/prettier/assets/39565703/58a34a41-e9a4-4fa1-b5c7-04d65c37f29b)
And output like this
![image](https://github.com/prettier/prettier/assets/39565703/2c818abb-828c-4b94-9dec-bf2f7d542993)

**Comment by efkz** [comment]
Prettier can't tell whether a blank line is intentional ("semantic") or just sloppiness. So as a middle ground, Prettier doesn't dare remove them completely but also tries to keep things tidy. That's the rationale. Use comments as multi-line separators as they're unanimously intentional. Ideally, Prettier shouldn't have used the input formatting for printing blank lines at all, but an algorithmic way of deciding where to insert blank lines is a really tricky problem to solve (see https://github.com/prettier/prettier/issues/2068).

_Originally posted by @thorn0 in https://github.com/prettier/prettier/issues/12086#issuecomment-1240600183_
            

Okay, it's clear. But can we just add an Option so that Prettier can tell that the blank line is intentional?
