### ISSUE TITLE
Flow parser add escapes to regexes and normalizes flags

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1334]
```js
/[/]/ig;
```

outputs

```js
/[\/]/gi;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F%5B%2F%5D%2Fig%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by bakkot** [comment]
I actually kind of like normalizing flags! Less sure about normalizing escapes, since it's going to be harder to find consensus on which subset to normalize.

**Comment by vjeux** [comment]
If we do normalize flags, we should do it consistently between babylon and flow :)

**Comment by lydell** [comment]
I think we need to dig into the ECMAScript spec here :)

### normalizing escapes

I thought we couldn't do that because of `String.raw` and `.source`? Remember #522, #562 and #574?

Interestingly, V8 and Spidermonkey differ here:

```js
# Chrome and Node.js:
> r = /[/]/; [r.source, r.toString()]
[ '[\\/]', '/[\\/]/' ]

# Firefox:
> r = /[/]/; [r.source, r.toString()]
[ "[/]", "/[/]/" ]
```

I would have expected Chrome and Node.js to behave like Firefox. Not sure what the spec says.

### normalizing flags

Both V8 and SpiderMonkey seem to sort the flags alphabetically.

```js
# Chrome:
> r = /a/uymig; [r.flags, r.toString()]
["gimuy", "/a/gimuy"]

# Firefox:
> r = /a/uymig; [r.flags, r.toString()]
[ "gimuy", "/a/gimuy" ]
```

Not sure what the spec says. If we can safely do it, I would not be opposed to sorting regex flags alphabetically in Prettier.

**Comment by bakkot** [comment]
Right, I forgot about `.source` even after [having gone into it previously](https://github.com/prettier/prettier/pull/562#issuecomment-276882937) :|

It's technically [slightly implementation dependent](https://tc39.github.io/ecma262/#sec-escaperegexppattern) ("S may or may not be identical to P"), but since that algorithm specifies "Multiple calls to this abstract operation using the same values for P and F must produce identical results.", it can't be semantics-preserving to modify at all.

---

[`RegExp.prototype.toString`](https://tc39.github.io/ecma262/#sec-regexp.prototype.tostring) defers to [`RegExp.prototype.flags`](https://tc39.github.io/ecma262/#sec-get-regexp.prototype.flags), which emits them in the order `gimuy`.

I don't think the original order of flags is observable, excepting of course by calling `.toString` on the containing function, which prettier is already going to mess with.

So, I vote for normalizing flags and leaving source alone.
