### ISSUE TITLE
TypeScript: use comma as interface delimiter

### ISSUE THREAD

**Issue by distinctdan** [prettier/prettier#13347]
Prettier should use commas for typescript interfaces because it makes it easier to copy/paste the interface when creating a new object. Many people have asked for this before, so I wanted to add my use case, since copy pasting is an objective reason that commas are slightly better than semicolons here. 

**Input:**

```jsx
interface Car {
  make: string,
  model: string,
}
```

**Output:**

```jsx
interface Car {
  make: string;
  model: string;
}
```

**Expected behavior:**

```jsx
interface Car {
  make: string,
  model: string,
}
```

**Comment by fisker** [comment]
This maybe related https://github.com/prettier/prettier/commit/59ec4f2ef4aef37c10a265aa7fc568c596fb4427#r76035657

**Comment by thorn0** [comment]
Semicolons make it easier to copy/paste the interface when creating a new class.

**Comment by thorn0** [comment]
Unlike the copy/paste-to-class use case, if you copy/paste an interface to an object literal, you'll have to replace the part after `:` for every property anyway, so I'm going to close this issue as this "objective reason" in fact doesn't look objective at all.

**Comment by thorn0** [comment]
What do you mean? We have a lot of tests with interfaces in `tests/format/typescript`, don't we?

**Comment by fisker** [comment]
I haven't checked, but if we already have tests why suddenly changed docs when releasing v2.7.0 https://github.com/prettier/prettier/commit/59ec4f2ef4aef37c10a265aa7fc568c596fb4427#r76035657

**Comment by thorn0** [comment]
Because that code wasn't valid in older versions of TS. Check the AST [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAEmA2BDKAcwFc9C4BnJTAQQCc68BPAHnS20wDMIJqKYdAJZEA3Bk6YARnjr9BIwuI4BfAHwYVIADQgIABxhDoFZKFl0IAdwAKshKZR4cV5qd1TGYANZwYAZTwAWzgAGRE4ZC5nCjgPL18A-TwwRWRBYjiQOCCpOAATfILQghIyOAAxCDogvBgjImQQPGIYCB0QAAsYIJwAdU6heApksDh-ByGhADchpiawCncQEVi6GBtGQlqomKyAKwoAD39FHDgARWIIeF2cWN1kujWmmCZ9SjBhQw79YVg+kJ8jBOsgABwABkellifUY+iaf0ocDo00iugAjtd4JsDI5mhQALRQOAFAodOhwLFCSmbMg7JDRe5ZWJBITpOiZXQUM6XbGRRl7XQwPBSQHA0FIABMwsYQhwigAwhAggzshQAKwdYixAAqoscTIeIGmmQAklAirB-F8hIYaJb-G9zndYioVEA).

**Comment by fisker** [comment]
Didn't know it's a label... Thank you!
