### ISSUE TITLE
[Bug Report] typescript parser throws error with left-shift operator and GTE operator

### ISSUE THREAD

**Issue by meteorlxy** [prettier/prettier#13440]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA8gaQwdwEsYALDAGQBUBRDCABzgCcBDGCJgHSkIDMAKXhAgYAPKIwBGMQF4MAIxZMAlBmDcMGdBgB0e7gF9u3bdQBKZrGYLEyAcRp1Grdlx4ChI8VIwA+OYoqahpamHo6htwgADQgDDCE0ADOyKBKTBD4AApKCCkoLAA2+CwAnimx8qxgANZwMADKLAC2cOSEUHDIvEVJcJXVdY30LGAdAObIMEwArv0gcM3ycAAmK6vkLFDjMyzjcABiHM1sCdvIICwz7DEgJDDNhQDqJMRwSSNgcA15xIQAbsRShcwEkKiAOn0mDAsqxxidur15gArJIADwaE0KcAAijMIPBEYU+rERkwoRcYKVGEkwExCPQYLd6PTYE9CCtSMgABwABlJGT6T1Y9AuLPezH+XViAEd8fBYQx8pckgBaTqrVa3JhwOWEHWwvYIpA9YnzPrNQhTWbmrG4+VdE1I2IwFjydmckjIABMLtYhEKEwAwhBmsaFkkAKy3GZ9Shu-Kmkkgf5zACSUHWsAadIZMAAgpmGlTsUS+gYDEA)

**Input:**

```ts
// OK with LTE operator
if(foo << 1 <= bar) {
  // ...
}

// ERROR with GTE operator
if(foo << 1 >= bar) {
  // ...
}
```

**Output:**

```bash
SyntaxError: Type parameter declaration expected. (7:11)
```

**Expected behavior:**

No error.

**Comment by thorn0** [comment]
This has been fixed in `next` (upcoming v3 release):

**Prettier pr-9583**
[Playground link](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEB6VACA8gaQwdwEsYALDAGQBUBRDCABzgCcBDGCJgHSkIDMAKXhAgYAPKIwBGMQF4MAIxZMAlBmDcMGdBgB0e7gF9u3bdQBKZrGYLEyAcRp1Grdlx4ChI8VIwA+OYoqahpamHo6hiAANCAMMITQAM7IoEpMEPgACkoIySgsADb4LACeyTHyrGAA1nAwAMosALZw5IRQcMi8hYlwFVW1DfQsYO0A5sgwTACufSBwTfJwACbLK+QsUGPTLGNwAGIcTWzxW8ggLNPs0SAkME0FAOokxHCJw2Bw9bnEhABuxBK5zAiXKIHavSYMEyrDGxy6PTmACtEgAPerjApwACK0wg8ARBV6MWGTEh50USwKN3oTHaMEehGWpGQAA4AAwk9K9R6sejnWlvZh-ToxACOePgMIYeQuiQAtB0Visbkw4BLCGqYbt4UhukS5r0moRJjNDZicZLOnrETEYCx5IzmSRkAAmO2sQgFcYAYQgTV1FwK1Ji016lAdeX1xJAf1mAEkoGtYPUwHT6DAAIJJ+owEpYwm9AwGIA)

```sh
--parser babel
```

**Input:**

```jsx
// OK with LTE operator
if(foo << 1 <= bar) {
  // ...
}

// ERROR with GTE operator
if(foo << 1 >= bar) {
  // ...
}
```

**Output:**

```jsx
// OK with LTE operator
if (foo << 1 <= bar) {
  // ...
}

// ERROR with GTE operator
if (foo << 1 >= bar) {
  // ...
}

```

**Comment by fisker** [comment]
[Correct link](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEB6VACA8gaQwdwEsYALDAGQBUBRDCABzgCcBDGCJgHSkIDMAKXhAgYAPKIwBGMQF4MAIxZMAlBmDcMGdBgB0e7gF9u3bdQBKZrGYLEyAcRp1Grdlx4ChI8VIwA+OYoqahpamHo6hiAANCAMMITQAM7IoEpMEPgACkoIySgsADb4LACeyTHyrGAA1nAwAMosALZw5IRQcMi8hYlwFVW1DfQsYO0A5sgwTACufSBwTfJwACbLK+QsUGPTLGNwAGIcTWzxW8ggLNPs0SAkME0FAOokxHCJw2Bw9bnEhABuxBK5zAiXKIHavSYMEyrDGxy6PTmACtEgAPerjApwACK0wg8ARBV6MWGTEh5xgJUYiTATEI9BgN3odNgj0Iy1IyAAHAAGEnpXqPVj0c7Mt7MP6dGIARzx8BhDDyF0SAFoOisVjcmHBZYRtTDdvCkN0iXNek1CJMZmbMTi5Z1jYiYjAWPI2RySMgAEzO1iEArjADCECaRouBQKN2mvUorryJuJID+swAklA1rB6rT6TAAILp+qUrGE3oGAxAA)  (With typescript parser)
