### ISSUE TITLE
Add parentheses for `TSTypeQuery` in some case

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#13546]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDABKgzugFDATwAc4IAzdKCAEzgDowALASwBtqAnBASgG0oArgFsARnA4BdADpQZGbHkIlylGvSZtOPXtNlR5OXPmKkKVWgxbsuUPoNHiJfCSAA0ICERjNoWZKFQODggAdwAFQIQ-FFRWENQCP3cRDlQwAGs4GABlVCE4ABlmKDhkMlisOGTUjKzsojTigHNkGA4BKpA4B2paagLUKCaBVCa4ADEIDiFUGG8h5DQBGAg3EEYYIVYAdRZ4LAawOGyo5m8ANzOCRbAsJJBiyo4YMNSmmbKKzoArLAAPbLNVhwACKAgg8E+rEq7gaHCeiyUcCwYA4zC8ayIaNg22Y1BgjGQAA4AAyw4KVbapIiLLHI8TnUruACO4Pgr080TQWAAtCU4H01lxWcwuK9Rh8kOVoZ1KkJmK12rKgaC2aUpV93DBUCJcfjCUgAExa1JsZoAYQgQklXSwAFY1gJKgAVHXRaUwkDnDoASSgtFg2VR6JgAEF-dlCMCoZUAL6xoA)

```sh
--parser typescript
```

**Input:**

```tsx
a as (typeof node.children)[number]

a as (typeof node.children)[]

a as ((typeof node.children)[number])[]
```

**Output:**

```tsx
a as typeof node.children[number];

a as typeof node.children[];

a as typeof node.children[number][];

```

**Expected behavior:**

Same as input

**Comment by thorn0** [comment]
```ts
a as ((typeof node.children)[number])[]
```
This one is too many parens. It looks fine and unambiguous without the outer ones:
```ts
a as (typeof node.children)[number][]
```
Otherwise, I don't think any discussion is needed here. It's a regression in 1.19.

**Comment by fabioStori** [comment]
@thorn0 the goal is to make the input 
a as ((typeof node.children)[number])[]
result in
a as (typeof node.children)[number][]
right?

**Comment by fisker** [comment]
Yes, `a as (typeof node.children)[number][]` is expected.

**Comment by fabioStori** [comment]
@fisker Thank you for the confirmation.
Just to understand better the motivation, can you explain the reasoning behind the logic of maintaining the parentheses around the `typeof node.children` in the scenario `a as ((typeof node.children)[number])[] `, but removing it in the `a as (typeof node.children)[number]` scenario? 
I understand that, in this first example, the outer parentheses can make the code look ambiguous, but in this second one the reason is still not clear to me.

I have another question, based on a scenario I encountered while working on this.
If the input is something like `a as typeof node.children[number][];`, should the parentheses be added, resulting in `a as (typeof node.children)[number][];`?

**Comment by fisker** [comment]
> can you explain the reasoning

https://github.com/prettier/prettier/issues/13546#issuecomment-1265543962

> If the input is something like a as typeof node.children[number][];

Yes.

**Comment by fisker** [comment]
Fixed by #14042

**Comment by zomars** [comment]
Do we have an option to disable this?

**Comment by mikedidomizio** [comment]
Between this thread and the PR itself, what was the exact reason for this?  It’s not very clear to me, and they both point to each other.  I want to bump prettier up in my project but I’m locked into doing a format fix to make everything happy, of a change I'm not sure I want.

Because this is a bug fix within Prettier itself and not a feature, I assume it was causing problems?

**Comment by demc** [comment]
Please either make this rule optional or revert. Thank you
