### ISSUE TITLE
Prettier formatting of ternary expressions breaks functionality

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [prettier/prettier#13544]
Taken from https://prettier.io/docs/en/rationale.html:

> Correctness
The first requirement of Prettier is to output valid code that has the exact same behavior as before formatting. Please report any code where Prettier fails to follow these correctness rules — that’s a bug which needs to be fixed!

This is unfortunately the case here, see code snippets below.

**Prettier 2.7.1**
The Prettier playground was unable to handle the code, so I had to enter it manually.

```sh
# Options (if any):
{
  "printWidth": 120,
  "tabWidth": 2,
  "singleQuote": true,
  "semi": true,
  "trailingComma": "es5",
  "bracketSpacing": true,
  "bracketSameLine": true,
  "arrowParens": "always"
}
```

**Input:**

```
baseURL:
  process.env.server === 'dev'
  ? `https://web.dev/.${AWS_BASEURL}`
  : process.env.server === 'dev1'
  ? 'https://dev1.some.url/'
  : process.env.server === 'dev2'
  ? 'https://dev2.some.url/'
  : process.env.server === 'dev3'
  ? 'https://dev3.some.url/'
  : process.env.server === 'prod'
  ? 'https://www.some.url/'
  : process.env.server === 'blackpearl'
  ? `https://web.some.env/.${AWS_BASEURL}`
  : process.env.server === 'gary'
  ? `https://web.some.env/.${AWS_BASEURL}`
  : process.env.server === 'karen'
  ? `https://web.some.env/.${AWS_BASEURL}`
  : process.env.server === 'plankton'
  ? `https://web.some.env/.${AWS_BASEURL}`
  : process.env.server === 'sandy'
  ? `https://web.some.env/.${AWS_BASEURL}`
  : `https://web.dev/.${AWS_BASEURL}`,
```

**Output:**

```
baseURL:
  process.env.server === 'dev'
    ? `https://web.dev/.${AWS_BASEURL}`
    : process.env.server === 'dev1'
    ? 'https://dev1.some.url/'
    : process.env.server === 'dev2'
    ? 'https://dev2.some.url/'
    : process.env.server === 'dev3'
    ? 'https://dev3.some.url/'
    : process.env.server === 'prod'
    ? 'https://www.some.url/'
    : process.env.server === 'blackpearl'
    ? `https://web.some.env/.${AWS_BASEURL}`
    : process.env.server === 'gary'
    ? `https://web.some.env/.${AWS_BASEURL}`
    : process.env.server === 'karen'
    ? `https://web.some.env/.${AWS_BASEURL}`
    : process.env.server === 'plankton'
    ? `https://web.some.env/.${AWS_BASEURL}`
    : (process.env.server = 'sandy' ? `https://web.some.env/.${AWS_BASEURL}` : `https://web.dev/.${AWS_BASEURL}`),
```

**Expected behavior:**
Prettier should not add the parenthesis around the `sandy` option and the default option. This leads to the `sandy` environment being treated as the default option, which breaks the intended functionality.

It is unclear where that parenthesis is even coming from, I couldn't find a prettier rule that would do that, so it seems like a bug to me.  
If not, please specify which rule causes this erroneous behaviour so I can turn it off.  
If there is no rule for it yet, please add a rule so this can be prevented at least.

**Comment by epidemian** [comment]
There's a comma at the end of your input that [causes a syntax error](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhgZzgVQEoAySAOlAARkAOAThGHJpgHQIBuT21rc1ZAvALIByACZxWQ0hQD8ZAAYALGDEqYkAenUB3OKiZjW6pgBJgAQQDqAZQD6AITNWAovgIBfOVLJIqteoxYodk5uXgE+YQMARklyMlkhJRU1TWiOCABbOCYAV2oAG3VYih8aOgZmNg4eUP5BUXEAJmL44STVDXUDRvSs3IKir1K-CsDgmp46iIbWAGYWhPaUrvFZ3uy8wpbh8oCqkMnw4TKRBbblDs0ta-X+raHfXcqg6q5D+tR89DAAa0o4dAFM6KC7LHR6TCZbJsIymSy2BzOVweB5lfzPcZvML1ADmgIAnsClp1wbcYSZzNZ7I4XIQUXEduixq9akchD9AQgiaCSboyUFYZSETTkZ4GY8mfsJtjppQvlAfjBoNzkryIVCxoL4dSkXSxSUJaMpVipsJMOgoCJCV5ZCDVVc+ZC+uS4VTEbT3PrvPJiQ69AYtW6RXqADQgMMQSgwACW0EwyFAgNoWgACpyoPGUOh8lp0Pj42HUNRvj84DArOgsgRo1A4MgAGbZ7CF4u-MtWSjfGs45Awag5OBhuAZVBwERiEQEC04nLoHFwABiEGoGXQym7yBA6BySvDICUGXyFgU0fgmE79CsCEwp+jrFP+M3YEYe5rnBgKeLONXDabg5AABWmAAB5WN2+RwAAijkEDwL++TNiAnbUJwm4YKO+R7jQNYwBY0YiDACjIAAHAADGGZTYBYxaUJuNAMBMe4AI4wfAn6RpmW6YAAtLWY5jnu1BwCx0ZCZ+c4-kgjYIf+2AZNGvb9rJ4FQaxdZSX+YYwOgqB4QRRFII0WnFtG+TdgAwpkkkgAwACse45NgAAqOmZtJiGsAOACSloIOWYDUNGUZmJaVgwPiEHwdgbhuEAA). If you remove that comma the error goes away and the code [is formatted as expected](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjAhgZzgVQEoAySAOlAARkAOAThGHJpgHQIBuT21rc1ZAvALIByACZxWQ0hQD8ZAAYALGDEqYkAenUB3OKiZjW6pgBJgAQQDqAZQD6AITNWAovgIBfOVLJIqteoxYodk5uXgE+YQMARklyMlkhJRU1TWiOCABbOCYAV2oAG3VYih8aOgZmNg4eUP5BUXEAJmL44STVDXUDRvSs3IKir1K-CsDgmp46iIbWAGYWhPaUrvFZ3uy8wpbh8oCqkMnw4TKRBbblDs0ta-X+raHfXcqg6q5D+tR89DAAa0o4dAFM6KC7LHR6TCZbJsIymSy2BzOVweB5lfzPcZvML1ADmgIAnsClp1wbcYSZzNZ7I4XIQUXEduixq9akchD9AQgiaCSboyUFYZSETTkZ4GY8mfsJtjppQvlAfjBoNzkryIVCxoL4dSkXSxSUJaMpVipsJMOgoCJCV5ZCDVVc+ZC+uS4VTEbT3PrvPJiQ69AYtW6RXqQAAaEAQSgwACW0EwyFAgNoWgACpyoPGUOh8lp0Pj4+HUNRvj84DArOgsgRo1A4MgAGbZ7CF4u-MtWSjfGs45Awag5ODhuAZVBwERiEQEC04nLoHFwABiEGoGXQym7yBA6BySrDICUGXyFgU0fgmE79CsCEwp+jrFP+M3YEYe5rnBgKeLONXDabg5AABWmAAB5WN2+RwAAijkEDwL++TNiAnbUJwm4YKO+R7jQNYwBY0YiDACjIAAHAADOGZTYBYxaUJuNAMBMe4AI4wfAn6RpmW6YAAtLWY5jnu1BwCx0ZCZ+c4-kgjYIf+2AZNGvb9rJ4FQaxdZSX+4YwOgqB4QRRFII0WnFtG+TdgAwpkkkgAwACse45NgAAqOmZtJiGsAOACSloIOWYDUNGUZmJaVgwPiEHwdgbhuEAA).

Is the code listing on your input example the whole code that you're having problems with? Because there's a `baseUrl:` label there that looks suspicious. Maybe the snippet is part of bigger object expression or something. You can try the [Prettier playground](https://prettier.io/playground/) page to reproduce the error and share a link to a working example :)

**Comment by thorn0** [comment]
> process.env.server = 'sandy'

Didn't you mean to use `===` here? Prettier adds parens around such assignment expressions to make them more distinguishable from comparisons and prevent accidental usage of `=` instead of `===`.

**Comment by azad-derakhshani-GS** [comment]
> There's a comma at the end of your input that causes a syntax error
> Is the code listing on your input example the whole code that you're having problems with?

It's part of the config file - which is much larger - of our Playwright project (you can find a shorter example [here](https://playwright.dev/docs/test-configuration#basic-options)). 
The comma actually belongs there, there'd be a syntax error without it. 
If I had pasted the entire file's code in here (or in a playground link), it would've become much more difficult for anyone to find the affected part of the code there, so I only included that part of the code.

> > process.env.server = 'sandy'
> 
> Didn't you mean to use `===` here? 

Yes indeed, it should've been `===` like in all the other lines there, my bad! 🤦‍♂️

> Prettier adds parens around such assignment expressions to make them more distinguishable from comparisons and prevent accidental usage of `=` instead of `===`.

But imho that is a very bad and unintuitive approach. If anything, prettier should've corrected it to `===` instead of adding parens. And adding parens **does not** prevent accidental usage of `=` instead of `===` as is evident by the fact that the `=` was still there after reformatting (I later fixed that myself btw, without the 'help' of prettier).

Anyway, I've had to completely change the implementation to prevent Prettier from breaking our code, which honestly doesn't inspire confidence in it. From what I understand, Prettier should only improve code formatting, not change the functionality in the code, so I would suggest changing that behaviour.
But since I solved my problem in a different way, we can close this ticket now.

**Comment by thorn0** [comment]
Adding parens doesn't change the meaning of the code. Please learn JS before writing stuff like this.

**Comment by azad-derakhshani-GS** [comment]
Yes it does, that's the whole problem.

`: (process.env.server = 'sandy' ? `https://web.some.env/.${AWS_BASEURL}` : `https://web.dev/.${AWS_BASEURL}`),`

Prettier added a parenthesis the sandy option and the default option, which made the whole content of the parenthesis the default option of the ternary expression. That changed the functionality of the code to always use the sandy option as the default.

What Prettier should've done - according to your logic - is this, then it wouldn't have changed the functionality:

`: (process.env.server = 'sandy' ? `https://web.some.env/.${AWS_BASEURL}`) : `https://web.dev/.${AWS_BASEURL}`,`

Notice the different position of the closing parenthesis and you'll see what Prettier did wrong.

Please learn JS before making wrong claims like this.

**Comment by thorn0** [comment]
This works as intended. Please don't reopen the issue
