### ISSUE TITLE
Formatting breaks with complex typescript instantiation expression

### ISSUE THREAD

**Issue by bschlenk** [prettier/prettier#13688]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwhtgDwAqAfDsAL4A6UTkUmM+BAygA5xgBLdKhJZcAXk6jyUAK4BbAEZwATjgA+OdioFQA5lRalcXCPLgB5GAAtV03PRAAaEBB4wB0TMlDoVKiAB3AAU-BG8UYUD0Am8XRRV0MABrOBgudHMAGV04ZAAzYUw4eMSUtN4k3T1kGBVZEpA4JTgAE1a2rPR9WXQ9OAAxCBV5dBgPfWQQdFkYCGcQaxh5VAB1awF4TB4kuC5wzYEAN02CKbBsBd1ilRhgxL1RgqLGgCtMAA8uatQ4AEVZBB4M9UMUXDsVDcpop0MpUAseDpYKsBK0bMgABwABnBAWKq0SPCmiLgNyOeRcAEdAfB7m4ItNMABaKBwNptBYqODUgRc+59J5IQqgxrFeQCWr1UU-f40vJCl4uGCwlFo6zIABMSsSAlQ1SIZkFTUwAFYFrJihRYRFhWCQEcGgBJKAdWBcMA6dwAQRdXBgBF+IOKdDoQA)

```sh
--parser babel
```

**Input:**

```jsx
class MyClass<T> {}

const MySpecialClass = MyClass<number | string>
class SomeOtherClass {}
```

**Output:**

```jsx
class MyClass<T> {}

const MySpecialClass = (MyClass < number) | (string > class SomeOtherClass {});

```

**Expected behavior:**

I would expect prettier not to change anything here. This is valid typescript, running it through tsc generates:

```js
// tsc --target esnext

class MyClass {
}
const MySpecialClass = (MyClass);
class SomeOtherClass {
}
```

Typescript instantiation expressions: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#instantiation-expressions

**Comment by thorn0** [comment]
Thanks for reporting. This has been fixed in the `next` branch. Will be released in Prettier 3.0 (no ETA, sorry).

**Prettier pr-9583**
[Playground link](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgLICeAwhtgDwAqAfDsAL4A6UTkUmM+BAygA5xgBLdKhJZcAXk6jyUAK4BbAEZwATjgA+OdioFQA5lRalcXCPLgB5GAAtV03PRAAaEBB4wB0TMlDoVKiAB3AAU-BG8UYUD0Am8XRRV0MABrOBgudHMAGV04ZAAzYUw4eMSUtN4k3T1kGBVZEpA4JTgAE1a2rPR9WXQ9OAAxCBV5dBgPfWQQdFkYCGcQaxh5VAB1awF4TB4kuC5wzYEAN02CKbBsBd1ilRhgxL1RgqLGgCtMAA8uatQ4AEVZBB4M9UMUXDsVDcpjACHxMGAdO4FjwdLBVgJWjZkAAOAAM4ICxVWiR4UxRcBuRzyLgAjoD4Pc3BFppgALRQOBtNoLFRwOkCXn3PpPJCFUGNYryAS1eoSn7-el5UUvFwwdCKdGY6zIABMqsSAlQ1SIZhF01QqAWsmKFHVETFYJARwaAEkoB1YFwEQJ3ABBd1cGG-EHFOh0IA)

```sh
--parser typescript
```

**Input:**

```tsx
class MyClass<T> {}

const MySpecialClass = MyClass<number | string>
class SomeOtherClass {}
```

**Output:**

```tsx
class MyClass<T> {}

const MySpecialClass = MyClass<number | string>;
class SomeOtherClass {}

```
