### ISSUE TITLE
Emotion's `keyframes` are not getting formatted

### ISSUE THREAD

**Issue by KimiyaHajizadeh** [prettier/prettier#13774]
**Prettier 2.7.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAED4CcDScAngGa4CGAtnJgLyYDWxZVcaABgDpSaacz9+ZCJUzBuvXhAAO5MAEsYRJJgAMAOgBMAbgmYAvnpgQxeqbIVKVGgKy6eB7u3sgANCBkx56ZKHK5cCAB3AAV-BDRkEHIAGyDyIkj3ACMKMCYYAGVWABl5KDhkEli0OBS0jMyLfIBzZBhcAFcykDhKZLgAE06unPIoGsbyGrgAMQhcSnIYLwGo8kbjNxAACxhKGIB1FcU2CzhMiMV5ADdFIiiwNCSQfNLcGBCKGqmikpaAKzQAD0zamLgAEVGhB4G8YqV3LJcPcoslyB0YstpLh8jBNvJOjAVsgAByqKGBUqbCjSKIothwXAnQruACOIPgTxkkRQ5DQAFoCl0ustcHAGfJ+U9hq8kMUIS1SpR5PUmlL-kDGYVxe93DAERisTikJp1RR5DFagBhERi1poGzLRqlAAqCNZEshIBOzQAklAerBMmBUdIYABBT2ZJQA8GlfT6IA)

```sh
--parser babel
```

**Input:**

```jsx
const enterKeyframe = keyframes`
  			from {
    opacity: 0.2;
  }
  to {
    opacity: 0.5;
  }
`;

```

**Output:**

```jsx
const enterKeyframe = keyframes`
  			from {
    opacity: 0.2;
  }
  to {
    opacity: 0.5;
  }
`;

```

**Expected behavior:**
 ```jsx
const enterKeyframe = keyframes`
  from {
    opacity: 0.2;
  }
  to {
    opacity: 0.5;
  }
`;
```

**Comment by kachkaev** [comment]
Supporting these cases is quite challenging because there may be another library with `keyframes` in which formatting is not desired. See 

- https://github.com/prettier/prettier/issues/5588
- https://github.com/prettier/prettier/pull/9025
- https://github.com/prettier/prettier/issues/11196

Possible solution (still requires discussion):
- https://github.com/prettier/prettier/issues/4424
