### ISSUE TITLE
Support for es5 variable declarations?

### ISSUE THREAD

**Issue by kaylieEB** [prettier/prettier#1399]
Hello! Would it be possible to preserve the line breaks for es5 variable declarations? It's going against our eslint rule http://eslint.org/docs/rules/one-var-declaration-per-line

```
// current behavior
var a = 'bacon',
    b = function() {},
    c,
    d,
    e;

// formats to 
var a = 'hello', b = function() {}, c, d, e;
```

**Comment by lydell** [comment]
Just turn off the ESLint rule? ¯\\_(ツ)_/¯

**Comment by vjeux** [comment]
As mentioned in https://github.com/prettier/prettier/issues/1607, I think we should do what you suggest since almost no one writes those in a single line. I'm going to close this issue as it's tracked there. If you would like to see it happen, feel free to send a PR :)

Thanks for raising this issue and sorry for the super late reply.
