### ISSUE TITLE
[RFC] Lenient parser / mode

### ISSUE THREAD

**Issue by xixixao** [prettier/prettier#1402]
`prettier` saves JS devs time by removing the need to format their code. But there are still cases of easily inferable syntax, which the programmer has to manually fix before they can run `prettier`.

#### commas in array literals
```es6
const x = [
  1,
  2 // <- syntax error
  3,
];
```

#### commas in object literals
```es6
const Module = {
  method() {
    ...
  } // <- syntax error

  methodTwo() {
    ...
  },
};
```

#### semicolon in Flow union type
```es6
type T =
  | A; // <- syntax error
  | B
```

#### arrow function returning object literals
```es6
const f = () => {a: 1, b: 2} // <- needs wrapping in parens
```

#### comma in JSX
```es6
const x =
  <div>
    <span />, // likely you're making a mistake or should use `{','}` instead
  </div>
```

#### duplicate separators
```es6
const x = [
  1,, // Formats to `const x = [1, , 2];`
  2,
];
```

The  Syntax Errors part is technically not related to `prettier`, as it assumes a parser gives it a valid AST. But with `prettier`, which ~~could be~~ will be run automatically, we could get to a writing efficiency of some other programming languages while keeping the readability of JS syntax.

I am interested in what others think, and whether people can come up with other cases besides the ones above (which could give us a sense of scope) and any issues. Are there any existing tools which perform similar transformations on JS already?

**Comment by vjeux** [comment]
You should try to run those with the flow parser. It does error recovery and tries to parse those.

**Comment by vjeux** [comment]
cc @rattrayalex

**Comment by rattrayalex** [comment]
This is pretty interesting. Depending on flow parser's error recovery it could be tractable. 

Is there a broader stance on AST modification? This gets into things like breaking up long strings with `+`, wrapping single-statement if's in blocks, etc. 

I wonder if it's possible to think about these things from the POV of a plugin system or something. 

I believe @thejameskyle is thinking about adapting Babylon for error recovery as well, iirc. Not sure where that is on his roadmap.

**Comment by thejameskyle** [comment]
Yeah I want to work on this in Babylon in the future in two parts:

- Error Recovery (https://github.com/babel/babylon/issues/347)
- Template Mode (https://github.com/babel/babylon/issues/343)

Error Recovery would allow prettier to continue formatting the valid parts of the program while there are invalid parts. Then prettier can power editor integrations that run as you type.

Template Mode would allow prettier to run on sections of the code without formatting the entire program. Then editor integrations for prettier can run on blocks, statements, and expressions with a much faster feedback loop (otherwise reformatting large programs would be interruptive).

However, I'd argue against formatting the areas of code that are invalid. We can infer a "good-enough" AST, but we shouldn't assume we got it right because getting it wrong can be really interruptive. That being said, all of the stuff above still applies.

It's a pretty large project, and if there are any companies that want to make it happen they can sponsor the development through [Thinkmill](https://www.thinkmill.com.au/).

**Comment by vjeux** [comment]
I'm going to close this issue as it's not actionable, but the concept sounds great, I'd love exploration in this space.
