### ISSUE TITLE
"prettier.printWidth: xx" - not-working

### ISSUE THREAD

**Issue by stevanantic** [prettier/prettier#14225]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected behavior:**

**Comment by stevanantic** [comment]
Hi, "prettier.printWidth: 140" property not working in settings.json and UI

**Comment by kachkaev** [comment]
👋 @stevanantic! I believe that your issue is related to the VS Code extension, so is out of this repo‘s scope. We only track bugs and feature requests for Prettier Core here. You might be able to get help by creating a [discussion](https://github.com/prettier/prettier-vscode/discussions) in [prettier/prettier-vscode](https://github.com/prettier/prettier-vscode) or by asking a question on StackOverflow. It is useful to provide steps to reproduce the unexpected behavior, including how you enable the extension, what file you are trying to format and so on. Cheers!
