### ISSUE TITLE
"Prettier Ignore" entire File?

### ISSUE THREAD

**Issue by natdm** [prettier/prettier#1428]
I work with code generation and some of it isn't conforming to my "prettier" settings. 

Instead of a huge diff where Prettier fixes it every time it's re-generated, is there/could there be a way to ignore an entire file?

**Comment by ndresx** [comment]
Was also looking for such an option today. Would be handy to have something like this, maybe similar to what ESLint provides `/* eslint-disable */` => `/* prettier-disable */`?

However, I then just applied auto-formatting and I wasn't caring about it anymore. :P

**Comment by vjeux** [comment]
We're not looking into adding such option. If you are using eslint, you can do `/* eslint-disable prettier */` or remove that file from the list of file you run prettier through in your lint/commit scripts.

**Comment by rattrayalex-stripe** [comment]
There is now a `.prettierignore` file

**Comment by suchipi** [comment]
You can also leverage the --require-pragma option, maybe with --insert-pragma, too (it's a whitelist, though, not a blacklist). https://prettier.io/docs/en/options.html#require-pragma

**Comment by jasonkuhrt** [comment]
I would love if `// prettier-ignore` at file top would disable prettier for the file. This is handy for ad-hoc situations.

**Comment by RReverser** [comment]
Markdown has `prettier-ignore-start`. Could we maybe extend it to arbitrary files? Then one could just put `// prettier-ignore-start` on top of a file and it would ignore everything till the end.

I know about `.prettierignore` but it's not sustainable in presence of hundreds/thousands of files, since you need to keep file names in sync, whereas comment can reliably disable formatting for a specific file across moves/renames/deletions.

**Comment by RReverser** [comment]
I see there is a newer issue https://github.com/prettier/prettier/issues/3634#issuecomment-364308981.
