### ISSUE TITLE
dependency postcss-less CssSyntaxError: Unknown word, request  upgrade to v5+

### ISSUE THREAD

**Issue by malei0311** [prettier/prettier#14326]
**Environments:**

- Prettier Version: 2.8.4
- Running Prettier via: CLI
- Runtime: NodeJS v16.15.1
- Operating System: macOS

**Steps to reproduce:**

test.less
```
@prefix: foo;

@{prefix}-title{
  color: red;
}
```

```
prettier -c -w test.less
```

**Expected behavior:**

no Css SyntaxError

**Actual behavior:**

SyntaxError: CssSyntaxError: Unknown word 

postcss-less has fix the issue at postcss-less@5 

![image](https://user-images.githubusercontent.com/1538613/218015814-d4f7ef4e-4943-45ff-8730-097df922f252.png)

upgrade prettier dependencies **postcss-less@3** -> **postcss-less@5** can fix the bug.

details: https://github.com/shellscape/postcss-less/pull/159

**Comment by fisker** [comment]
postcss-less already updated in `next` branch, and your issue is fixed. [1](https://deploy-preview-9583--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEABADgJzgMwJYAeSABDhBANwA6UNqwWuhAvgLQx4wA2cwNxxSFwiYS2ACbUozEABoQEdB2gBnZKACGmTBADuABS0I1KDV10aAnmvkAjTBrABrODADKGgLZwAMnihwyDhmKnB2Ds6ubuiO-gDmyDCYAK5hIHCetnDi4tk+GlBxyRpxcABiIp4aMByFyCAayTAQciAAFjCeXADqbZxwKjFgcG7GnHgAbpyW9WAqNiD+oZgw+g5xVUEhaQBWKgRu8TwAiskQ8FtcofIxmMv1PPOtWP4w3XjiMG3IABwADDcdKFug50PVGMsJoF5ABHM7wNaKEwNFSsALZbKtbBwvDYNYlTZIYJXNKhTx4RIpUlHOAAQRqmDwtiacH0cEwfgCl2uIBUNNO50CRO28hgGls70+3yQACZRQ48Fx4gBhCCeQkNLhcVrJUIAFXFJmJPImqQAklBcrA3GBGUpaZa3DBLDxuXBmMwgA)

**Comment by malei0311** [comment]
When will v3 be released, I'm in a hurry

**Comment by fisker** [comment]
Tests added in #14330
