### ISSUE TITLE
No-semi is too agressive with JSX

### ISSUE THREAD

**Issue by yamafaktory** [prettier/prettier#1433]
When using the no-semi option, some unnecessary semi-colons are inserted : https://prettier.github.io/prettier/#%7B%22content%22%3A%22%3Cdiv%3E%5Cn%20%20%7B%5Cn%20%20%20%20do%20%7B%5Cn%20%20%20%20%20%20%3Cdiv%3Etest%3C%2Fdiv%3E%5Cn%20%20%20%20%7D%5Cn%20%20%7D%7D%5Cn%3C%2Fdiv%3E%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by yamafaktory** [comment]
Do we need that all JSXElements get the ASI protection https://github.com/prettier/prettier/blob/master/src/printer.js#L3529?

**Comment by lydell** [comment]
This is also mentioned in #1244. This is a really good question, actually.

What if Prettier _didn’t_ add that semicolon:

```js
<div>
  {
    do {
      <div>test</div>
    }
  }}
</div>
```

... and somebody makes the following change:

```diff
 <div>
   {
     do {
+      console.log("Does this do-thing even work??")
       <div>test</div>
     }
   }}
</div>
```

Now, you’ve accidentally written a syntax error:

```
SyntaxError: Unterminated regular expression (5:17)
  3 |     do {
  4 |       console.log("Does this do-thing even work??")
> 5 |       <div>test</div>
    |                  ^
  6 |     }
  7 |   }}
  8 | </div>
```

I have never used do-expressions, so I don’t know how likely this is. Perhaps it is more generally useful to _not_ print the unnecessary semicolon here, than trying to prevent the user from accidental errors.

**Comment by yamafaktory** [comment]
I'll also go that way, printing if necessary. Trying to prevent something is IMHO already too much.

**Comment by lydell** [comment]
> Trying to prevent something is IMHO already too much.

I strongly disagree. But I think JSX might be an exception.

**Comment by yamafaktory** [comment]
If you add another expression upfront, like you did in your previous post, then the parser will complain about that anyway.

**Comment by lydell** [comment]
> If you add another expression upfront, like you did in your previous post, then the parser will complain about that anyway.

Good point! 👍 

Unlike the other cases, the JSX cases give quick syntax errors instead of subtle runtime errors, such as here:

```js
console.log('test')
[1, 2, 3].forEach(n => console.log(n))
```

I think that’s a strong argument for removing unnecessary semicolons before JSX.

**Comment by yamafaktory** [comment]
Maybe @rattrayalex should be involved in the loop for his JSX expertise (and also because he's the one that implemented the no-semi option).

**Comment by rattrayalex** [comment]
Thanks for the ping @yamafaktory 😄 

I agree that JSX should be exempted from the "always add a semicolon, not just when it's needed" rule, but only because it will "give quick syntax errors instead of subtle runtime errors", as @lydell sagely mentioned. 

Unfortunately I think it's the only case where this is true. Also unfortunately, it doesn't buy most people very much, since I think do-expressions are just about the only scenario in which JSX expressions are likely to start a line (though that should definitely not be special-cased in the implementation). 

Happy to help; are either of you guys planning to implement?

**Comment by rattrayalex** [comment]
By the way, a much more radical proposal (which I don't necessarily think is a good idea): 

We could use a fork of babylon which incorporates [the ASI fixes](www.lightscript.org/docs/#automatic-semicolon-insertion) I've incorporated into LightScript. As it stands, I believe they would properly interpret all output of `prettier` without semicolons (the fixes rely on style conventions which prettier adheres to, like `-1` instead of `- 1` for positive numbers). Regexes are an exception.

If we did that, we could add the `;` only when absolutely needed, and maybe even add them at the end rather than the beginning of the line. 

This approach would also enable conveniences like those suggested in https://github.com/prettier/prettier/issues/1402 by @xixixao . Obviously, this feature would be a step beyond prettier's core mission, but would also make for a much more convenient coding experience for many developers, especially more junior ones, and could even constitute "expected behavior" to many users.

Or, of course, people could just use LightScript 😜 which is built to solve this whole class of problems and more.

I assume this is 👎 (feel free to react as such) but if there's interest I'll submit an [RFC] issue.

**Comment by bakkot** [comment]
> the JSX cases give quick syntax errors instead of subtle runtime errors

That's not... *necessarily* the case...

```js
let x = do {
  console.log()
  <div>
    foo
  </div>.length/g
}
```

The above is valid syntax. It contains no JSX. ([Spoilers.](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20x%20%3D%20do%20%7B%5Cn%20%20console.log()%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20foo%5Cn%20%20%3C%2Fdiv%3E.length%2Fg%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D))

Admittedly this is kinda contrived. But, well, no-semi edge cases are often very subtle, and part of the point of rules like "before every risky start-of-line character, no matter what comes before it" is so that you don't have to remember the subtle edge cases.

**Comment by bakkot** [comment]
Perhaps more compelling is the fact that the error the parser gives you will not be in a useful position.

Consider:

```js
let x = do {
  console.log()
  <div>
    foo
    <span>
      bar
    </span>
  </div>
}
```

The [parse error](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20x%20%3D%20do%20%7B%5Cn%20%20console.log()%5Cn%20%20%3Cdiv%3E%5Cn%20%20%20%20foo%5Cn%20%20%20%20%3Cspan%3E%5Cn%20%20%20%20%20%20bar%5Cn%20%20%20%20%3C%2Fspan%3E%5Cn%20%20%3C%2Fdiv%3E%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) here is at `</span>`, and the error is `Unterminated regular expression`. I don't think it's at all clear from this, if you don't know the details of the JavaScript grammar and expect no-semi to "just work", that the error in that program is a missing semicolon after `console.log()`.

**Comment by rattrayalex** [comment]
The parse error position sounds like a compelling reason not to adopt this suggestion, especially since few people are probably aware of this ASI failure.

**Comment by bakkot** [comment]
For completeness, you can also get at least two other misleading syntax errors:


```js
let x = do {
  console.log()
  <div> foo <span> bar </span> </div>
}
```
[gives](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20x%20%3D%20do%20%7B%5Cn%20%20console.log()%5Cn%20%20%3Cdiv%3E%20foo%20%3Cspan%3E%20bar%20%3C%2Fspan%3E%20%3C%2Fdiv%3E%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) `Invalid regular expression flag` at `/span` (although in fact the invalid flag is the `d` in `div`; babylon could maybe use a more precise error location here), and

```js
let x = do {
  console.log()
  <i> foo <span> bar </span> </i>
}
```
[gives](https://prettier.github.io/prettier/#%7B%22content%22%3A%22let%20x%20%3D%20do%20%7B%5Cn%20%20console.log()%5Cn%20%20%3Ci%3E%20foo%20%3Cspan%3E%20bar%20%3C%2Fspan%3E%20%3C%2Fi%3E%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D) `Unexpected token` on the closing `}`.

So there's at least three different errors you'd need to learn to recognize as "you forgot a semicolon after an earlier line".

**Comment by lydell** [comment]
@bakkot’s examples are very convincing. Perhaps better to leave things the way they are then, and link people to these examples when they ask about the semicolons :)

**Comment by yamafaktory** [comment]
@bakkot Thanks for the in-depth exploration. @lydell you're right, let's close it!
