### ISSUE TITLE
<script> (as a string) breaks Prettier

### ISSUE THREAD

**Issue by Bernard-Borg** [prettier/prettier#14361]
**Prettier 2.8.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwARkwQwGdCBeAHREwEtCYBaAExrGwFtM6BGABm3gA96rBmwZIB9TAHM2AIzoBmCgD4yUbBuypqygGro42BdgAUAYQisADhEJUYVaNgCCABQCS2AO72AFlsIrfHU8IlIKADNoIWgICmxaAE9MOHJwCEwIACckbABiTjgAVm5ZJRBlYGBsAANUQjAsqisYBLgYdCtlGuwAX17UAHpA4OVsAGpsVyooKnwJ7F17OABKIZ01TS0dABV8KkwfKAYzAGVT9apVdU1tK4A6ADkAUR3sCyzDADZL66GsZQgAA0IAgLUcUEIyFA+CyWQgXlcsIQUJQ+EO+ESUJBsiy+DAAGt2qd8Kw4AAZGZwZARdGEOA4vGE4lBMAzKTIGBZAwguCsWRwBgMQXk4JSdD4KRwABi2VY+BgDigHLR6BgEGBIF8MHYAHVfMsRmA4KcUfYqAA3eyJZDgYiamb0rIwVx4qTyml0hkgABWhH4p3ZKQAiugIPBPZh6SCglknbbZPgBZhNVYmrBdVQGDBfMhOAAmbgx+H03V4qy2tNwJ0W6kggCOYfgrrBqJARDoUDggsFms+jaon1dko9SFpUe99NYVE53MnQbgzkVTVkargrjgWUpXcj0ZAdmVIab1LHXpBMCTmezuaQABZz3iDuyLKxRyAoNA6yB0PS9rJUeOe4WgY7jHAgMCnI0zQwM4xynDAyQnoBcD9EAA)

```sh
--parser babel
--print-width 120
--tab-width 4
--trailing-comma none
```

**Input:**

```jsx
<ul class="list-disc ml-10 text-md md:text-lg mb-3">
    <li>Vue 3 (Composition API with <span class="font-mono" style="color: #1e50b3">{{ `<script setup>` }}</span> + Pinia + Vite)</li>
    <li>TailwindCSS</li>
    <li>.NET Core 6</li>
</ul>
```

**Output:**

```jsx
SyntaxError: Unexpected token (2:87)
  1 | <ul class="list-disc ml-10 text-md md:text-lg mb-3">
> 2 |     <li>Vue 3 (Composition API with <span class="font-mono" style="color: #1e50b3">{{ `<script setup>` }}</span> + Pinia + Vite)</li>
    |                                                                                       ^
  3 |     <li>TailwindCSS</li>
  4 |     <li>.NET Core 6</li>
  5 | </ul>
```

**Expected behavior:**

Currently, that sequence (basically, an unclosed script tag in a string) breaks prettier (and even my code highlighter). I believe that should not be the case. The code is in a Vue 3 SFC (in the <template> tag).  I had to escape `<script setup>` because otherwise the Vue compiler would pick it up as a script tag.

**Comment by Josh-Cena** [comment]
That's because you are using the Babel parser, which parses this as JSX. If you [change the parser to Vue](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwARkwQwGdCBeAHREwEtCYBaAExrGwFtM6BGABm3gA96rBmwZIB9TAHM2AIzoBmCgD4yUbBuypqygGro42BdgAUAYQisADhEJUYVaNgCCABQCS2AO72AFlsIrfHU8IlIKADNoIWgICmxaAE9MOHJwCEwIACckbABiTjgAVm5ZJRBlYGBsAANUQjAsqisYBLgYdCtlGuwAX17UAHpA4OVsAGpsVyooKnwJ7F17OABKIZ01TS0dABV8KkwfKAYzAGVT9apVdU1tK4A6ADkAUR3sCyzDADZL66GsZQgAA0IAgLUcUEIyFA+CyWQgXlcsIQUJQ+EO+ESUJBsiy+DAAGt2qd8Kw4AAZGZwZARdGEOA4vGE4lBMAzKTIGBZAwguCsWRwBgMQXk4JSdD4KRwABi2VY+BgDigHLR6BgEGBIF8MHYAHVfMsRmA4KcUfYqAA3eyJZDgYiamb0rIwVx4qTyml0hkgABWhH4p3ZKQAiugIPBPZh6SCglknbaLQZNVYmrBdVQGDBfMhOAAmbgx+H03V4qy2lNwJ0W6kggCOYfgrrBqJARDoUDggsFms+9aon1dko9SFpUe99NYVE53PHQbgzkVTVkargrjgWUpHcj0ZAdmVIYb1JHXpBMHwsnTmezSAALKe8Qd2RZWMOQFBoDWQOh6XtZKjRzuiZwO4xwIDApyNM0MDOMcpwwMkR4AXA-RAA), it works.
