### ISSUE TITLE
Prettier wrongly changes indentation of markdown list item content (breaking)

### ISSUE THREAD

**Issue by ssbarnea** [prettier/prettier#14515]
When including multi-line list items, it is required to use 4 char indentation as otherwise markdown parsers will wrongly parse it reset that numbering on list items.

As seen in screenshot below, prettier decides to replace the 4 char identation with 3 chars, and that is changing the meaning of the text.

![](https://sbarnea.com/ss/Screen-Shot-2023-03-16-11-56-15.05.png)

**Prettier 2.5.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgGYQgHSkMxMwAMKAjAQwGcALY0uMeiTVAJgGYmSKyfQpyw0AToRAAaEBAAOMAJbRayUNTFiIAdwAKGhKpTUANtuoBPVTMpjqYANZwYAZWoBbOABlFUOMmxTWjgbO0dnFzl7XwBzZBgxAFcQkDh3SjgAE0ysr2ooGMTqGLgAMQgxd2oYJQLkEGpEmAhpEHoYdxMAdXpFeFoosDgXQz7FADc+i3qwWmsQX2CxGF07GKqAoJSAK1oADxdYkzgARUSIeE2TYJkosSX6qrEHTJ0oVrkxXxguxUyYejIAAcAAZblpgl07HJ6p84Etxv4ZABHc7wVbyIwNWgAWj8WSyrTEcFRimJq2KGyQgWuKWC7kU8SSdKOpzR-mpWxkMGolF+-0BSE43LsihMsQAwhB3FTUrQAKytRLBAAqvKMNJuIHGyQAklAcrAXGAvgoAIIGlwwCzHK7BAC+9qAA)

```sh
--parser markdown
```

**Input:**

````markdown
1. foo

    ```bash
    echo 123
    ```
   
2. bar

````

**Output:**

````markdown
1. foo

   ```bash
   echo 123
   ```

2. bar

````

**Expected behavior:**

Please note that having 4 characters indentation for all the lines inside the list entry is essential for proper parsing, especially for code blocks, which would not end-up being recognized as part of the numbered list entry, and reset the numbering.

Please read https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list which is explaining in more detail what is happening, note the the selected answer has almost 1000 upvotes.

Sadly this is a breaking bug in prettier markdown implementation and not a cosmetic one. I guess that those affected by it should disable prettier for .md files until we find a better solution.

**Comment by kachkaev** [comment]
👋 @ssbarnea! What do you mean by “markdown parsers will wrongly parse it reset that numbering on list items“?

I tried your example in the Playground and got the same AST (syntax tree) with both three and four spaces before the code blocks:

**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAgGYQgHSkMxIANyAjAQwGcALYkmOgJzjkxoAcqw4bGmcqUKEATFmotRUEmUq0GsubgCuLTjz4Dl8kUSgBmSVQBeIADQgIXGAEtoNZKCosWEAO4AFVwicoqABsPKgBPJysKFl4AazgYAGUqAFs4ABk7KDhkbCCaOEjosDjErUyAc2QYFlUCkDhkijgAE2aWtKooctUqcrgAMQgWZKoYey7kECpVGAhLEDoYZMCAdTo7eG5eOAS-DbsANw3QybAaCJBM-JYYL2jykZy8uoArGgAPBIrAuABFVQg8CegXyVh4LGukxGLBizU8UHmXBYmRgKzszWYyAAHAAGMHufIraJcSZI-hwFgHbJWACOAPgdxs-imNAAtFkWi15mw6XY2Hdeo8kLkQXV8sk7FUamLvnAAIJjZEUGZwLwUjJZYGgkA0WX-QHZYXPKwwKgUNEYujIMQm6J2QIVADCEGSQvqNAArPNVPkACpm-wi7UHWoASSgbVgCTAyNscojCRgoR+WrgAF800A)

```sh
--parser markdown
```

**Input:**

````markdown
1. foo

   ```bash
   three spaces
   ```

2. bar

    ```bash
    four spaces
    ```

3. baz
````

**Output:**

````markdown
1. foo

   ```bash
   three spaces
   ```

2. bar

   ```bash
   four spaces
   ```

3. baz

````

Using four spaces instead of three has benefits, but they are not universal. The original Prettier’s behavior was using four spaces in all numbered lists, but this changed after a discussion in https://github.com/prettier/prettier/issues/4114. 

Some people find two spaces after `1.` confusing, so the current version of Prettier _maintains_ one or two spaces – whatever is used in the first list item. This produces an indent of three of four spaces, respectively.

I personally prefer enforcing four spaces in ordered lists, exactly for the same reason as you do: code blocks. This enforcement is out of Prettier’s scope, so I am using [Markdownlint](https://www.npmjs.com/package/markdownlint) for achieve four spaces everywhere. You can see an example setup in [kachkaev/njt](https://github.com/kachkaev/njt) (this is a personal side project).

In particular I enable `"list-marker-space": { "ol_multi": 2, "ol_single": 2 }` which gives me two spaces after `1.`. I also use `"ol-prefix": { "style": "one" }` to make sure that all list are numbered ad `1. 1. ... 1.` instead of `1. 2. ... 10.`

Does the usage of Markdownlint solve your problem?
