### ISSUE TITLE
valid TS format error

### ISSUE THREAD

**Issue by avin** [prettier/prettier#14550]
**Prettier 2.8.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgAVMIAHAZwB4AVAMVTgBsATANV2YFc5LC4AD3hRW-Riw5delAHwAdKIQHCEYwgHkAtqhjVFy5QBIAoszhaEMUhRowAnuTgRshALK5KAawCSUctx6DExsnDx8srIANAaGAORanl4a5DCo0JRxscqyhMCx5AAW0HAe3gD8SISUMJjoAOYA3IoAviBRIBRpGciguJhkAO7E-QiUyCBcg7j24x0ARpj4XnAwAMq4lgAy6HDIeMyUcAtLYCvr5PgNyLW8HRbzcKysT1u4UPXcuPVw9BCYiRgaQ+E1wgQg7RAhRgWmYAHVCro+JcCGsxrpUAA3XT2CZgShzNBQI6YaxLeqJfZcI4dABWlEEawa5gAitwIPAqYdjiBLpgSRN5rhHsxIeQ6rA4ahWDBCsgABwABg64ogRzhS3IE3FfCwmL2HQAjuz4DYqKDKABaKBwJ5PSGYODG1CO0jfSlIA40kBHHQ3TB3H3MuAAQSBdXmgTgxCwOxtXO9lGDbI5e091J5MGFUplcqQACYOrVcKhmA0AMIQLQekB8ACskO4R1owvG6e5HUxvD8L1gazAdVSIdEawc5gTcBaLSAA)

```sh
--parser babel
```

**Input:**

```jsx
interface Props<TFieldValues extends FieldValues>
  extends Omit<
    $ElementProps<typeof MaskInput<TFieldValues>>,
    'maskOptions'
    > {
  phoneMask?: string;
}
```

**Output:**

```jsx
SyntaxError: Unexpected token, expected "," (1:30)
> 1 | interface Props<TFieldValues extends FieldValues>
    |                              ^
  2 |   extends Omit<
  3 |     $ElementProps<typeof MaskInput<TFieldValues>>,
  4 |     'maskOptions'
```

**Expected behavior:**

**Comment by kachkaev** [comment]
This example works with `babel-ts` and `typescript` parsers. Still a bug I guess, because other TS syntax I have tried works in `babel` parser. Please correct me if I wrong.

---

**Prettier 2.8.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgAVMIAHAZwB4AVAMVTgBsATANV2YFc5LC4AD3hRW-Riw5delAHwAdKIQHCEYwgHkAtqhjVFy5QBIAoszhaEMUhRowAnuTgRshALK5KAawCSUctx6DExsnDx8srIANAaGAORanl4a5DCo0JRxscqyhMCx5AAW0HAe3gD8SISUMJjoAOYA3IoAviBRIBRpGciguJhkAO7E-QiUyCBcg7j24x0ARpj4XnAwAMq4lgAy6HDIeMyUcAtLYCvr5PgNyLW8HRbzcKysT1u4UPXcuPVw9BCYiRgaQ+E1wgQg7RAhRgWmYAHVCro+JcCGsxrpUAA3XT2CZgShzNBQI6YaxLeqJfZcI4dABWlEEawa5gAitwIPAqYdjiBLpgSRN5rhHswALQwQnkOqwOGoVgwQrIAAcAAYOlKIEc4UtyBMpXwsJi9h0AI7s+A2KigyiiqBwJ5PSGYOBm1DO0jfSlIA40kBHHQ3TB3P3MuAAQSBdXmgTgxCwOztXN9lFDbI5e291J5MGFsvliqQACYOrVcKhmA0AMIQLRekB8ACskO4R1owvGme5HUxvD8L1gazAdVSYdEawc5iTcBaLSAA)

```sh
--parser babel-ts
```

**Input:**

```tsx
interface Props<TFieldValues extends FieldValues>
  extends Omit<
    $ElementProps<typeof MaskInput<TFieldValues>>,
    'maskOptions'
    > {
  phoneMask?: string;
}
```

**Output:**

```tsx
interface Props<TFieldValues extends FieldValues>
  extends Omit<$ElementProps<typeof MaskInput<TFieldValues>>, "maskOptions"> {
  phoneMask?: string;
}

```

---

**Prettier 2.8.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLWcBOAzAhmOAAgAVMIAHAZwB4AVAMVTgBsATANV2YFc5LC4AD3hRW-Riw5delAHwAdKIQHCEYwgHkAtqhjVFy5QBIAoszhaEMUhRowAnuTgRshALK5KAawCSUctx6DExsnDx8srIANAaGAORanl4a5DCo0JRxscqyhMCx5AAW0HAe3gD8SISUMJjoAOYA3IoAviBRIBRpGciguJhkAO7E-QiUyCBcg7j24x0ARpj4XnAwAMq4lgAy6HDIeMyUcAtLYCvr5PgNyLW8HRbzcKysT1u4UPXcuPVw9BCYiRgaQ+E1wgQg7RAhRgWmYAHVCro+JcCGsxrpUAA3XT2CZgShzNBQI6YaxLeqJfZcI4dABWlEEawa5gAitwIPAqYdjiBLpgSRMHE5KGA6qlIeQ6rA4ahWDBCsgABwABg6kogRzhS3IE0lfCwmL2HQAjuz4DYqKDKABaKBwJ5PSGYOCm1DO0jfSlIA40kBHHQ3TB3P3MuAAQSBdXmgTgxCwOztXN9lFDbI5e291J5MFw8xlcoVSAATB1arhUMwGgBhCBaL0gPgAVkh3COtFz40z3I6mN4fhesDWotQqTDojWDnMSbgLRaQA)

```sh
--parser typescript
```

**Input:**

```tsx
interface Props<TFieldValues extends FieldValues>
  extends Omit<
    $ElementProps<typeof MaskInput<TFieldValues>>,
    'maskOptions'
    > {
  phoneMask?: string;
}
```

**Output:**

```tsx
interface Props<TFieldValues extends FieldValues>
  extends Omit<$ElementProps<typeof MaskInput<TFieldValues>>, "maskOptions"> {
  phoneMask?: string;
}

```

**Comment by fisker** [comment]
> because other TS syntax I have tried works in babel parser. Please correct me if I wrong.

Because we support Flow syntax in babel, and we already removed support in `next` branch. And the example is not valid js/flow code.

**Comment by fisker** [comment]
@avin Please use the correct parser.
