### ISSUE TITLE
End tags are not line feeds and are not aligned

### ISSUE THREAD

**Issue by AprildreamMI** [prettier/prettier#14763]
**I want the input effect, not the output, how do I configure it?**

![image](https://user-images.githubusercontent.com/31964372/234536905-95d5230a-82b8-4b11-9264-462831c672ae.png)

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwCUIBXeHABRwgDdUATOHfAX3wDNb18ByHHACGYGAFpaFFmMYR0fADpQM2PPkmUuPfgAEA9BpaLlWXASpCA5nADKmVFC1z+AOj2RTUBDADOei9Z2DsacZFCiqND4AIKYmAAUAJSESvjqcDBkOI7xqWn4ADykUtS0DMw4efnq5JQAvMCGOGxV+ZxCADYdAEYiANYAoh1w6N4NBQG29o56AHxss60FesWUNPRMLIuO+IlKLVBKcAAeqgTM7WQdBLGYSiAANCAQmDCRUD7IoEI4tADuFkEH2QIE6fyEAE9Pk9ujh+hkbEJRgAZBxwZAwHBkOAwuFgPoIzAiByWDFYnEgEbdOCMZiMZFCKCWMhWOAAMVw6CEMDeTJBQgoEEeIAAFjB0B0AOoi1DwHxEsC2BA+WWoBgwCEgsA+aFoD4sGA0Kxc5DtDo+CkAKx8xxsJOGAEUyBB4KbOhankScBacCDetSOsLMDgHDBJUwYCLkAAOAAMntoFslcMwIODcB9dHRTwAjs74OtMJ8UEIfGIvDSacLBHnUIIjZYTUgzR6QBb0KgydiniqmcNojyQ90pFQWKivF2Kb3LI78+jm+6KTAhN1w4xI8gAExPTFCVAdEkAYTkTcpPgArMKyBaACor4stil0bEASSgzFgNjAIde0XfNg1YY3XNOA2DYIA)

```sh
--parser babel
--bracket-same-line
--single-attribute-per-line
```

**Input:**

```jsx
import { RouterProvider } from 'react-router-dom'
import router from '@/router'
import PageSpin from './components/PageSpin'
function App() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}>
    </RouterProvider>
  )
}

export default App

```

**Output:**

```jsx
import { RouterProvider } from "react-router-dom";
import router from "@/router";
import PageSpin from "./components/PageSpin";
function App() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}></RouterProvider>
  );
}

export default App;

```

**Expected behavior:**

**Comment by fisker** [comment]
What do you expected?

**Comment by AprildreamMI** [comment]
I want the effect of input, don't want to be formatted

```
function App() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}>
    </RouterProvider>
  )
}
```

**Comment by kachkaev** [comment]
If I understand correctly, @AprildreamMI prefers the original formatting to the one that Prettier produced. The purpose of Prettier is to offload any thinking about formatting from us (developers), so that we can focus on the meaning of our code, not its look. In your case the resulting formatting is not as perfect as a human would craft, but it’s good enough to move on.

Neverheless, here are a couple of variants for you as a workaround. `</RouterProvider>` will go to a new line if you add some `children`. You can also use a self-closing JSX tag.

**Prettier 2.8.8**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEA8gE44DmOUAhgDYAUAlPsADpT77FwzrHt1sOHADwAlCOnjEACsQgA3HABM4xQUI5zJqgLzAtUgL7qNqWjQBGVMAGsAojTgBbBDD3DpVMnADKAB0p8AHoAPkMQk3xhIPFtGTlFFWII9nwGNmMoNgwsXAIAdRwYAAsAYWKcGiUuKEZmdS4ePnwBVJFYqVkFZVVIzQkpPQNVTI0OMxpLa3tHF1h3T29-QNDwvvwAZwgXfDAKqprI6I7VLsTVFI50qEzszGw8dkKSnzgaVFKaCA3KMgAVLx1VipRq8fhHE7xbpJdbDYhDAYjdYTKa2BzOVwLLy+ALsVbBS5pDJsEAAGhAED8eSgG2QoCoxDkAHdPDVaShaEyqABPWnkizEabcHxUFwAGUocGQMGI6Dg-MFtmFfmsv2lsvlIGcFjgShUSjFVCgZHQ2IAYhBiE4qDBcMbkCAqJIIGSQMUYE4aPkKvANiqwL4ED9cIoYNyHWANnyQJQNqoYLIvNbkBM4+SAFYbAAePl+jgAiugIPAU7Q0yAVcQ48QHVYdTRXX5SLBCkoSsgABwABnJTe+cHygr8DqbcGr8il5IAjkX4F0-OzHRsALRQOC63WurgznBcRNkZNIVOauNOHDquXkn7GxwAQVtpAs2mkqgla4vJ7zcELxalR7LmowFQFitu2SAAEzkjKVCVL8pTbIeWobAArK66BxgCFjsse5LyHKACSUAqLAPhgKQVK3kRPhho4pY0HGhiGEAA)

```sh
--parser babel
--bracket-same-line
--single-attribute-per-line
```

**Input:**

```jsx
function Original() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}>
    </RouterProvider>
  )
}

function WithChildren() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}>
      some children
    </RouterProvider>
  )
}

function WithSelfClosingTag() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />} />
  )
}

```

**Output:**

```jsx
function Original() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}></RouterProvider>
  );
}

function WithChildren() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}>
      some children
    </RouterProvider>
  );
}

function WithSelfClosingTag() {
  return (
    <RouterProvider
      router={router}
      fallbackElement={<PageSpin />}
    />
  );
}

```

Feel free to close the issue if this solves your problem. You can also read a couple of pages in the _About_ section of the doc for background: https://prettier.io/docs/en/why-prettier.html
