### ISSUE TITLE
Why are keys in an object always output on a separate line?

### ISSUE THREAD

**Issue by jharris4** [prettier/prettier#1479]
This:
```
let anObject = {
  keyA, keyB, keyC, keyD, keyE, keyF, keyG, keyH
};
```

Gets output as this:
```
let anObject = {
  keyA,
  keyB,
  keyC,
  keyD,
  keyE,
  keyF,
  keyG,
  keyH
};
```

Apologies if this was already discussed, but I'm curious to know why prettier doesn't pack as many of these as will fit on one line (up to the printWidth count) ?

I just tried running prettier on one of my projects, and the line count exploded, and it makes it a bit hard to navigate. In my mind, this could/should be synonymous to how function arguments with object destructuring are treated.

For example, this doesn't get wrapped:

```
function({ keyA, keyB, keyC, keyD, keyE, keyF, keyG, keyH }) {

}
```

**Comment by vjeux** [comment]
For objects, we had to make a trade-off where if there's any \n between `{}`, then we're going to keep the object expanded.

So, if you write

```js
let anObject = {
  keyA, keyB, keyC, keyD, keyE, keyF, keyG, keyH
};
```

it's going to be expanded. But if you write

```js
let anObject = { keyA, keyB, keyC, keyD, keyE, keyF, keyG, keyH };
```

it is not.

This is not ideal but the best we could find to work with all the use cases objects are used for.

**Comment by jharris4** [comment]
Oh that sounds sensible. Thanks for taking the time to respond, I'll consider using this syntax when I can to keep things from getting wrapped:

```
let anObject = { keyA, keyB, keyC, keyD, keyE, keyF, keyG, keyH };
```

**Comment by alexrqs** [comment]
Maybe the same policy can apply to destructuring and arrays (right now only when the array content goes over the max-print-width changes to multiline), when I use multiline with trailing comma, there is a reason: keep git changes to the minimum, so we easily track who did the changes and the diffs will only show one word/variation when is added or removed, but right now shows like all the line was a change.

Right now with prettier:
```diff
- import {
-   Foo,
-   Bar,
-   Baz, 
- } from './Qux'
+ import { Foo, Bar, Baz } from './Qux'
```  
so any change after will show: 
```diff
- import { Foo, Bar, Baz } from './Qux'
+ import { Foo, Bar } from './Qux'
```
and for our team we find more useful
```diff
import {
  Foo,
  Bar,
-  Baz, 
}
```
That's why I think square brackets on and curly brackets on different lines should generate multiline, not only for objects(as right now) but also for destructuring and arrays.

Thanks for the good work :)

**Comment by vjeux** [comment]
I'm going to close this as we do not intend to make changes here, sorry :(
