### ISSUE TITLE
Ignoring `.gitignore`ed files by default is overkill. 

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#14831]
I previously approved https://github.com/prettier/prettier/pull/14731, but I have since changed my mind.

I believe that this should not be enabled by default.

I think there are files that are `.gitignore`d, but not necessarily intended to be ignored by Prettier.

The files that you don't want to be under version control and the files you don't want to be the target of a code formatter are not always the same.

Therefore, I propose to introduce a CLI option like the following.

```console
prettier --ignore-gitignore .
```

I know we can work around it with `--ignore-path=.prettierignore`, but I still thought it would have a significant impact.

**Comment by sosukesuzuki** [comment]
@fisker @Divlo WDYT?

**Comment by fisker** [comment]
Can't image who else need format .gitignored file except ourself https://github.com/prettier/prettier/issues/8048#issuecomment-1430297131

**Comment by sosukesuzuki** [comment]
Outside of Prettier development, I occasionally experiment with writing small scripts in .gitignored files. I don't think most people follow that style of development, but I don't think there are too few of them to ignore.

**Comment by Divlo** [comment]
The best default behavior is the behavior used by the majority of the users.
I can be mistaken, but there are fewer people that want prettier in  git ignored files than people that want to ignore these files.

Also adding `--ignore-gitignore` defeat the purpose, before that PR we could use `--ignore-path .gitignore`.

> I occasionally experiment with writing small scripts in .gitignored files. 

Out of curiosity, why are you doing that?
Version contral and branches are meant do such things?
If just want to experiment, create a new branch?

**Comment by nicolo-ribaudo** [comment]
@sosukesuzuki I often write small scripts in files ignored by git, however I started using `.git/info/exclude` instead of `.gitignore` for that. The advantage is that I don't have to commit a filename/folder in the .gitignore file just to satisfy my personal workflow.

You may try doing something similar, so that they are not listed by .gitignore and thus not affected by that PR :)

**Comment by lukeshiru** [comment]
100% agree with this issue!

I have TypeScript projects that I compile before publishing, and then I run prettier over the generated files so the distributed code is formatted nicely (using tabs instead of spaces and leaving minification to consumers)

Committing the compiled "/dist" code doesn't make sense, so it's obviously in my `.gitignore` file, and prettier ignoring whatever is in my `.gitignore` file is not only something unwanted but is something that came as a surprise. Why would a formatting tool such as Prettier care about what I have on my `.gitignore` file? If I wanted to ignore something, I would put it in `.prettierignore` :/

Even if the team doesn't want to undo this weird new default, there should be documentation about "how to ignore `.gitignore`" somewhere.

**Comment by tats-u** [comment]
Files like `.env.js` and `localSettings.json` needs to be ignored but can be formatted.

**Comment by sosukesuzuki** [comment]
Now that Prettier 3.0 has been released, I've changed my mind. This issue is no longer needed.

**Comment by pascalr** [comment]
Ignoring .gitignore files by default is such a bad idea.

This is my first time using prettier. I install it, I try to use it "npx prettier someFile.built.js".

It tells me no bad message, it just outputs the same file. I don't know the tool. I guess it's processing because it outputs text right? Nope.

I waste an hour until I find this issue to understand that "*.built.js" files are excluded in my .gitignore file.

.gitignore says it in the name, it is for git. I don't expect a tool to use this especially since nowhere in the docs have I seen that written anywhere.

Also, the ignoring should only be done when using a glob path. If I give it a specific filename, I expect it to work. Or at least give a warning or an error message.
