### ISSUE TITLE
Lint like CI integration

### ISSUE THREAD

**Issue by arnarthor** [prettier/prettier#150]
I've been using scalafmt at work which has a feature that you can enable to prevent it from compiling the code if it's not properly formatted. This prevents code from going through CI if it's not properly formatted.

Obviously this is a huge feature which would require first of all the ability to run prettier on a directory instead of a single file at a time, but I think it could be a great addition.

Humans are known to be bad code formatters, so code will get through review even if it's not formatted properly. My dream is that this could replace eslint (code formatting rules), and in order to do that I feel like it would have to have some linting mechanism that it could break CI if it's not formatted on commit.

Maybe I'm reaching way to far here, just wanted to put the idea out there.

**Comment by BLamy** [comment]
I'm going to reach even further.

I imagine a workflow where prettier is run using something like a precommit hook. I check out the code from the repo. Prettier formats the code to whatever my preference is, then on commit it formats the code back to a common format for git diffing. 

For example, if my company's coding style requires I use semicolons but I personally don't like them. I can simply hide them when working on code in my editor.

**Comment by jlongster** [comment]
Yep! All of these are great ideas and what I envision this becoming. It actually shouldn't be too hard; we already support passing in multiple files (so people are doing `prettier src/**/*.js` to lint whole folders). We could easily make it "check" if all files are formatted instead of doing the actual formatting (a `--check` flag instead of `--write`).

> For example, if my company's coding style requires I use semicolons but I personally don't like them. I can simply hide them when working on code in my editor, but when I commit they will automagically be put back in and nobody's the wiser (especially git)

This is exactly the kind of thing this project empowers you to do, and it's a great idea. It's also why we won't ever have a project-wide config file; one of the reasons those exist is so things like editors can pick them up and automatically set the right formatting settings in your editor. But we don't care about that. You can format the code with whatever settings you personally like across *any* projects, and just make sure that the project reformats it with the project-specific settings before commit.

Tooling integration will be the next step after we fix all the show-stopping issues where we generate invalid JS code. That's higher priority right now, but we'll think through this soon.

**Comment by sokra** [comment]
I've done something like this for webpack. CI checks if source equals to beautified source (using js-beautify). If not CI fails and prints a diff (in patch format). Works great to ensure all source code is consistent.

**Comment by ezekielchentnik** [comment]
i like the idea of some kind of --check flag so that we can use it as a linter.  as in, run prettier on a build step (in npm scripts lint, or pre-commit, or CI build, etc. ) 

this way we have the flexability to use in multiple workflows:

- used as a linter, something like standard js where it will recognize that it is locally installed, get auto formatting for free, but allow control of when that happens
- used to migrate legacy codebases without blindly formatting. you can drop it in a project, lint, then fix as you go
- used for learning. if available as a linter, we can also print out proposed formatting changes that will be made without making the changes, this will help with better understanding of opinionated style and user can manually format if wanted
- used in more complex workflows accross multiple teams and tools where its not always feasible to use at IDE time

**Comment by pomber** [comment]
There is now a `--list-different` flag that can be used to detect files that are not using prettier format. See #854.  
I'm wrapping this in a new npm module [prettier-check](https://github.com/hexacta/prettier-check) in order to manage the verbosity. Here is a [failed travis build](https://travis-ci.org/pomber/prettier-check-test/jobs/207803076) sample.

**Comment by pablorsk** [comment]
CI works with return code of commands. When prettier return code 0, all it's ok. When prettier return a code <> 0, CI fails. `prettier` has this return codes.

For example:
* When we have pretty code `prettier prettier  --parser markdown --list-different` return a code 0.
* When we have NO pretty code `prettier prettier  --parser markdown --list-different` return a code 1.

Them, just need `--list-different` to you command on CI.

**Comment by pablorsk** [comment]
`--list-different` its great! but have a problem: TAKE MORE TIME :(

Check this:
```bash
$ prettier '**/*.{ts,sass,scss,md}' --write
[...]
src/test.ts 4ms
src/typings.d.ts 1ms
Done in 5.59s.
$ prettier '**/*.{ts,sass,scss,md}' --list-different
[...]
Done in 8.87s.
```
On CI, time is important. Then, if we use `--write` exit code allways is `0`. If we use no option, dump text is huge! :/

Any ideas for optimal prettier on CI?

**Comment by Dorian** [comment]
To make it return non-zero exit code when some files are different:

```
prettier --list-different src/** | ruby -e "exit 1 unless STDIN.each_line.to_a.join == ''"
```

**Comment by stevemao** [comment]
Would be great if it reports the differences similar to eslint-plugin-prettier:

https://github.com/prettier/eslint-plugin-prettier/blob/master/eslint-plugin-prettier.js#L120-L215

**Comment by SimenB** [comment]
There is https://github.com/ikatyang/prettylint
