### ISSUE TITLE
weird trailingComma:all cases

### ISSUE THREAD

**Issue by fabb** [prettier/prettier#15077]
I found 2 weird cases when applying prettier 3.0 with `trailingComma:all` to my code base. It compiles, so this is more of a code aesthetics question and if this is the desired formatting behavior.

**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AE8AzjABQCU+wAOlPvfgPSP4CGATuxAO74Za5oRfNxwwAFhHQx87ODHTs6E1jIBGc1gGt8OWBDb4ocXgBs9cfONYA3S63yQAtk4erC4ywgAmtBviIIJzgAMUxsPChSCnwAXgA+fD9-BgAFLiccIjgAOjlA0ztSYDYib1RWMoqqyvLa6vKAGlK6mrbWjorvImb6vvaGwfregf7O-ABfcmT6abok+fpmQyI9AHNTSwApAGUADXwABw5WYPh2fDX5YQdnVzYZCS8obwX-ORe4dgB1MXF0iA2HDeL5EUgzFIAHgAwnJvGIiN84KZnHAAGrAuAQaHQeAADxgOQBQJBFxsrFM6DgsWAJSyAFkIN4KQB5Q4IJB8CnZZpgUwQbKM5mmTlOCBgLTQ-mCpkU5oQdlQIUU0XirRshDK0yTCbxCEpBgwuEIpEooLozEGRh6xZQxiwuDwmCI5GojEg7G4uAEolcElfG3+OYTWggRogBWCKBEZCgDhcbipDgIGMoCncVgATxj4Y0rAl8h2pzgABkLMgKqYeSA8wWYDtjmB1sgYOwqeHspkK9y4B31psAIroCDwFtt3sgABWRDxO37cCHI7g3arE4AjsP4ADDqmQJUALTGR2OsMgVusHDmKBrHEuVjIPemUyn1bXzYAQRgrZwamkcFSXxlsYK7VuIMBOKY3ziGIcBEI2cA7CmYg4ECMCZg+YBEDmIA2FSACSnywDsYDsDghwwO+Lw7GhmwgROhxcNk3zsKwhwPgxsFfHYp56Nk7AwOkrBrK4dHhsc7B8Q+aisGoyKngxegwL83gSMgACMAAsAAM4ZyBuOByIJwn3kglbVjAMnKapSAaeG6DZAAKjJqZmROcBOLJ3ggt4JasNe6BCaEEDsK4X7Nmm0gQCAEwTEAA)

```sh
--parser babel
--print-width 140
--tab-width 4
--no-semi
--single-quote
```

**Input:**

```jsx
function test() {
    // arrow functions without return that break into a new line have a comma at the end
    someFunction(() => 
        Promise.resolve({ asdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdfasdfads, asdfasdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdf })
    )
  
    // a single JSX parameter gets a comma at the end 
    renderWithProviders(
        <CreditsWelcomeVideoContext.Provider value={{ isModalOpen: false, closeModal: mockCloseModal, openModal: mockOpenModal }}>
            <CreditsWelcomeVideo />
        </CreditsWelcomeVideoContext.Provider>
    )
}

```

**Output:**

```jsx
function test() {
    // arrow functions without return that break into a new line have a comma at the end
    someFunction(() =>
        Promise.resolve({ asdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdfasdfads, asdfasdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdf }),
    )

    // a single JSX parameter gets a comma at the end
    renderWithProviders(
        <CreditsWelcomeVideoContext.Provider value={{ isModalOpen: false, closeModal: mockCloseModal, openModal: mockOpenModal }}>
            <CreditsWelcomeVideo />
        </CreditsWelcomeVideoContext.Provider>,
    )
}

```

**Expected behavior:**

```jsx
function test() {
    // arrow functions without return that break into a new line might not need a comma at the end
    someFunction(() =>
        Promise.resolve({ asdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdfasdfads, asdfasdfasdfasdfasdfasdfasdf, asdfasdfasdfasdfasdf })
    )

    // a single JSX parameter might not need a comma at the end
    renderWithProviders(
        <CreditsWelcomeVideoContext.Provider value={{ isModalOpen: false, closeModal: mockCloseModal, openModal: mockOpenModal }}>
            <CreditsWelcomeVideo />
        </CreditsWelcomeVideoContext.Provider>
    )
}

```

**Comment by matt-mcmahon** [comment]
Prettier also adds unexpected trailing "," when using generics in TypeScript, but not in all cases. First observed in `*.vue` files, but tested in other situations.

- issue is with **arrow** functions that have exactly 1 generic argument; example output `const identity = <T,>(value: T): T => value`
- does **not** impact **anonymous** functions, **named** functions, or arrow functions **with multiple generics**; output in these cases is as expected [[playground link][3]]
- impacts `*.vue` files [[playground link][1]]
- impacts `--parser babel-ts` in playground; I assume these are `*.tsx` files? [[playground link][2]]
- does **not** impact normal `*.ts` TypeScript files when I tested locally; output is as expected in **all cases**
- setting `--trailing-comma none` in the playground does not fix this behavior

### Input
Minimal `example.vue` file [[playground link][3]]
```html
<script setup lang="ts">
const asArrowFunction = <T>(value: T): T => value
</script>
```

### Output
```html
<script setup lang="ts">
const asArrowFunction = <T,>(value: T): T => value
</script>
```

### Expected Behavior
```html
<script setup lang="ts">
const asArrowFunction = <T>(value: T): T => value
</script>
```


### Output `example.vue` with additional test cases [[playground link][1]]

```html
<template>
  <p> Why do arrow functions with a single generic have a trailing ","?</p>
</template>

<script setup lang="ts">
  // extra trailing "," after single generic type, `T`
  const asArrowFunction = <T,>(value: T): T => {
    return value
  }

  // is okay
  const asAnonymousFunction = function <T>(value: T): T {
    return value
  }

  // is okay
  function asNamedFunction<T>(value: T): T {
    return value
  }

  // is okay
  const arrowTwoGenerics = <X, Y>(x: X, y: Y): { x: X; y: Y } => {
    return { x, y }
  }
</script>
```

[1]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAjgDwEMBbABwBs4A6ANwFc4dsA+AHSlXjPMPjahw5UpZjgDqACwCeOACYQchAE5KIAdxwAzOlDAwAltADOONfpgTFOI-qgBzSjjsI4S-WBwTCNRoRwwlQn1yWzscVhAAGgiAflQAehF2BK4KXjh+ZKMwN1IYazgYOlIcHnsAXgiYIwj+QXj4vHwAvxbg0PCoiMVNeCVrUMdnKFd3fylSOEicAAMAFRn2QUgoI3zCIwBBFXUAMR09QwFyoTnmAAoaQnIGJBw5gEo7uZxy0WAlwRwlQrolASuNzgnwAvuxPg0cPoTBAANaEKSfFZrRRbKDQKTECB0Iz7XQGaCvLQHAkCVBnS7XW73J73HAfARfH5Ff44QEMUHgxmQ6E4OEIz7afFHVEAORIcFkeMO0HJF3ZcGetJeDK+31+rIVnKgEMavP5iMZyPWOzUczUEAA4i43GATCdUAANaYATQu+DuzpwUjuLtpwBwHpwjoA3N7fTgQa93p9BMy-gIA-hpjIwYy0wlsrkYPwoiAIHkjkZkKBlKo1AAFZQIYsoa5qBHFyIgABGgTAsMKAGUJQAZWxwZCaa5GKat9udmBd0iEMChZABBjN0fEfRDkdjmz2SgARToEHgC6US5AACsjPgu4M4HuD4OkMPyKPmwBHffwCuqUi1kAbTAjSVJTzNoQnsABhCBiGIQhkF-chyDzLcHDgTYYACfQWzoD9XH7EZ1yfMcJBgYhyEkcw4CMGcwDgLsa3MfQaHMKRYLtJsQHoOAAEkoFkBApxyfQ8k2HiuxgKRKHw58QFIVRRzEQJSFgmSKNcHw81sUclBgT9CDsaDJLHGclE02COLzGTbBgMR9FkCxkAARgAFgABmbH4330H4dL0mCHw3ZsYEIFtrNsiRkEc5scTgOYgtrR8pLgYgW0lXjZF7Qh7DoXS4F2CAlGgtD5zrLCIBAEEQSAA

[2]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDATriAdwDEBXKMGAS2gHko4BxBOXKsTAXkwB4ANAHwAKAB5JMfAJTi+XAZhEgANCAgAHaumSg8BQgAU8CNMhDYANoWwBPEyoBGubGADWcGAGVsAWzgAZKgZkADMLNDgHJ1d3DzVnQIBzZBhcUgiQcO8qELD0tETzOABFUgh4ZNT0gCs0EQ8C4tLypFDzcJUARya4fQI1ExRsNABaBjgAEwnlEBTsKnNEgGEIb29sUwtzafyoBMKAQRgUqntSeH1WAKCW3JUACxhvcwB1O6p4NDiwOA9jd6oAG7vaymMBoOwgAFpACSUEmsA8YDYGn2cI8MGshRybXSagI4WeTjUpjxcHCuABcGmgXJMF62ASa2x7RAcVw5NM9mw9jg5mGMAheMCMGeVHGMDuyAAjAAWAAMKlwcC6VCV9MZ6xuOJUMG5ovFkqQMpUpHCABVuQNWiy4N4eeNJuM-NhdqQGXBiBBcGsjokNmcICAAL5BoA

[3]: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzmATgSwA4wAE6cMArnoQDYCGUA5gLwA6IM6rAfM1JFOkRroAgliwQA7gDEyvGDmiFGhVABVOACgBuNKmThJCqgJSHVSzoR164PVAHpMuApxAAaEBAIL+yUDTFJAAUAhHRkEF0JGgBPcI8AIywaMABrUgBlGgBbOAAZHCg4ZAAzXRJE5LTMvBTC+mQYLH0PEmycUvK4VvqqOABFMgh4RubukAArdAAPDN6BoZGkMqoKkABHRbgg8TxwlCEAWiK4ABMz9zZknCp6gGEIbOyaCN0qS-R54RgmnASyeBBOBYApFTqrcYACxg2SoAHVITh4OhamA4BkwkicFokTEImB0PEQFp9ABJKDnWAZbD4GDCCkZGAxPrgtZ4cQkOHJPARdlwEhYLTFDyFAUwHY0ejPVnjWpYAUREnCkDswowOE4U4wSHIACMABYAAweLBwTY4U0SqUvZZdDwwGgJDVanVIfUeMgkVSO-YrNZwbIJM7nU55Oj0MiSuBSCBYZ4-eqvAEQEAAX1TQA

**Comment by so1ve** [comment]
If you are using tsx, a trailing comma after the single type parameter is required thus typescript parser can determine whether it's a tsx element or a generics. But yeah, it's pretty weird that a comma is added after the type parameter though the language is ts.

**Comment by guilhermehn** [comment]
It seems to be related to how prettier inserts trailing commas in functions' parameters when the last parameter is a function, whether it's an arrow function or not. Lowering the print width helps visualize the bug without very lengthy names nor strings.

[Playground example.](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDADugdAczjACgB0QB6DASxIBoACAgJzgEc6mBnASloF4A+WhywArdtALBaAE1QxUSWiQBmECACNUDErQC+nTgG4iUYxmwBXdnAKMWbOF14Cho8cD2HjpzLnwEA5OToFP50SuZQYDAU4kysgg7ckkww5gxQCewiYlASerrcINQgEOjR0OzIoJoMEADuAAqaCJUoqAA2dagAnpXFagyoYADW+ADKqAC2cAAyFFBwyEodVv2DI+PoQ-M4yDAM5nDFVpMUewdHIOw77XAAiuYQ8Esrl6IAHmM394-PSMvtVYgZi-OANWroVpodgAWgWcCkCKKIH2qAo7R2AGEIJNJqhkGh2u1kdcoDhbgBBGD7ChqczwBpwBhzBYvQGXAAWMEm7QA6hyKPB2FswHAxi1BRQAG6C7oEsDsPogKWHACSUERsDGYAYFDKFI1Yxg3VubKB6FqVl5g3QBItDiZUsWxXmVgYMHBqBweLNly2DDdBI0ajgxOKFvmMF5FCkMA5yAAzAninFzBQmJ7vfj-q9inI1NHY-GkAAmYqWOAAFVQalaAKBcEmIakiKkM1QZPMXrgADEIAw8dSdgTUPSICAdDogA)

### Input:

```js
app.get("/api", (req, res) => res.json({ data: "foobar" }));

app.use((req, res) => res.json({}));

app.get('/api', function(req, res) { return res.json({}) });
```
### Output:

```js
app.get("/api", (req, res) =>
  res.json({ data: "foobar" }),
);

app.use((req, res) =>
  res.json({}),
);

app.get(
  "/api",
  function (req, res) {
    return res.json({});
  },
);
```

### Expected output:



```js
app.get("/api", (req, res) =>
  res.json({ data: "foobar" })
);

app.use((req, res) =>
  res.json({})
);

app.get(
  "/api",
  function (req, res) {
    return res.json({});
  }
);
```

**Comment by so1ve** [comment]
@guilhermehn `trailingComma: es5` will solve your problem

**Comment by guilhermehn** [comment]
@so1ve Is that the intended behavior of `trailingComma: all` since version 3.0.0?

**Comment by so1ve** [comment]
@guilhermehn 😅 It's the intended behavior since prettier 2 if you use `trailingComma: all`, please read the blog post.

You don't want to change your config but expect `trailingComma: es5`'s output and you simply downvote my solution, what a shame.

**Comment by jon-a-nygaard** [comment]
I guess this issue could be closed?, as this seems to be the expected behavior with `trailingComma: all`.

For those interested here is a link to [the blog post for the Prettier 3.0.0 relase](https://prettier.io/blog/2023/07/05/3.0.0), which I assume is the blog post @so1ve is referring to.

The [blog post for the Prettier 2.0.0 release](https://prettier.io/blog/2020/03/21/2.0.0#change-default-value-for-trailingcomma-to-es5-6963httpsgithubcomprettierprettierpull6963-by-fiskerhttpsgithubcomfisker) gives the first hint of the change to  `trailingComma: all`, and is also referencing the article [Why you should enforce Dangling Commas for Multiline Statements](https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8) which is probably the motivation for the change of default behavior.

That said, neither the issue #11465 or [the blog post for the Prettier 3.0.0 relase](https://prettier.io/blog/2023/07/05/3.0.0) is saying much about the motivation behind the change, or explaining the benefits, which I personally find a bit lacking; Even though it apparently has been a desired change for a long time.

**Comment by sosukesuzuki** [comment]
https://github.com/prettier/prettier/issues/15077#issuecomment-1636342647 is different from the main topic of this issue.

I believe that what is being demonstrated in the main subject of this issue is Prettier's intended behavior.
