### ISSUE TITLE
Trailing comma added to TS type params in ES5 mode

### ISSUE THREAD

**Issue by jakes-space** [prettier/prettier#15142]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAbQB0pNNiQAVACwEs1MHMYa5MAzOgJw0wg4sA7hEwZudKAHNGMCKIA20KS1Fcs0FmzEBDALbsFk9gDozlADSlylMycw6oAEy3NmrdmjiRnJy6QBdAG5SHz4AT3xMAAprTCVpADl9OAAxCG5UgFcoMBg6aAAFHW4U+G4ARiRMACN5BThHKzJ45WSDdMycvIKoYtKDcoAmarqIBsdSAEp8AD5WpJTO7Nz8opKyuErMADIdhal2tIyVnvWBuGGQ3PQsAC8ogB44gBk2pYyqcIAHOH7N7ZwbDwZyMcSSKTNchvRYdT4-P4bQZbCqYIEgpxgmASaSkWaxFrfJFVTAww4fbhfX7-ZGVKGYIkDEak95wykImmXLZDaZzTAAAwAJMBGfoKgBfAC0wtFeiG4v51xAFhAEG+aygaGQoBK3AgQn6CC1KB0CiEOnCWpVNVKYAA1pcAMopF7GZAcU1ea22h0wR1EsAQ5DYrJwFVePR0YPcUPhiENACKWQg8HdnrDIAAVmhsI743Akym4GmFF6QABHZPwQp677GkA6NCSqBwOBONvKkDYnR0IzSADCED0eh0yBAcDQAFZO2h8wBBGDYug1LLVraulslss0GB6BQAdXo8DQAbgjqNdHyADdL+Ex2A0FaQFfQwBJZwIP1gCTqufOR0wOEDRbhm3x6l4+6lN8Y5gROWxXsWKqSF43AwDWOhSCOIEqoyKFjoBvxoN+dDqp2YGSDA+50E4rDIAAHAADCq3BwJWPB-KUmGjkgHqlhmMA6DUVE0TQyBDCqWReFQgnGrxZZwHoNRtu2TgvI4UhZBhxzcCOi5Biaq4QCA4rikAA)

```sh
--parser typescript
--trailing-comma es5
```

**Input:**

```tsx
const x = [
  "This is the first of two strings too long to fit on the same line ...",
  "... and this is the second.",
];
const y = (
  longNameForFunctionParameter1: boolean,
  longNameForFunctionParameter2: boolean
) => longNameForFunctionParameter1 && longNameForFunctionParameter2;
const z = <
  LongNameForTypeParameter1 extends string,
  LongNameForTypeParameter1 extends string
>(
  param1: LongNameForTypeParameter1,
  param2: LongNameForTypeParameter2
) => `${param1}-${param2}`;

```

**Output:**

```tsx
const x = [
  "This is the first of two strings too long to fit on the same line ...",
  "... and this is the second.",
];
const y = (
  longNameForFunctionParameter1: boolean,
  longNameForFunctionParameter2: boolean
) => longNameForFunctionParameter1 && longNameForFunctionParameter2;
const z = <
  LongNameForTypeParameter1 extends string,
  LongNameForTypeParameter1 extends string,
>(
  param1: LongNameForTypeParameter1,
  param2: LongNameForTypeParameter2
) => `${param1}-${param2}`;

```

**Expected behavior:**
No trailing comma added to the type parameters of `z`.

The [options documentation](https://prettier.io/docs/en/options.html#trailing-commas) reads:

`"es5" `- Trailing commas where valid in ES5 (objects, arrays, etc.). No trailing commas in type parameters in TypeScript.

If I'm reading that right, either the behavior or the documentation should be corrected.

**Comment by kachkaev** [comment]
If you are talking about `  LongNameForTypeParameter1 extends string,` this is expected behavior. `"es5"` only avoids trailing commas in JS syntax. Inside TS types though, the commas are added regardless of the option for convenience. See https://github.com/prettier/prettier/issues/3722 and for context.

**Comment by thillebrandt** [comment]
> 👋 @jakes-space! If you are talking about `LongNameForTypeParameter1 extends string,` this is expected behavior. `"es5"` only avoids trailing commas in JS syntax. Inside TS types though, the commas are added regardless of the option for convenience. See #3722 and #14085 for context.

Gonna have to latch on here.
No, this is _not_ expected behavior. Quoting the Prettier documentation (emphasis added):
> `es5` - Trailing commas where valid in ES5 (objects, arrays, etc.). **No trailing commas in type parameters in TypeScript.**

As such, trailing commas in type parameters are not expected, regardless if "es5 is technically not compatible with ts anyway".

Where is the option to turn on trailing commas for arrays and objects, but OFF for function parameters AND type parameters, please?

**Comment by sosukesuzuki** [comment]
@thillebrandt Thank you. According to the documentation you are right. I think we should fix it.

BTW, just out of curiosity, are there any specific use cases that would require such an option?

**Comment by Deckstar** [comment]
> @thillebrandt Thank you. According to the documentation you are right. I think we should fix it.
> 
> BTW, just out of curiosity, are there any specific use cases that would require such an option?

I can't comment for the author, but I can say that from my own point of view, this is just an annoying change since:
1. **It modifies potentially hundreds of files in the codebase.**
    I was hoping to upgrade to Prettier 3 seamlessly, and this was almost possible except for this detail. While we expected some changes, this creates too much noise in the git history. (We like to check commit-by-commit or even line-by-line changes in files sometimes).
2. **It makes, at least from my point of view, for cosmetically worse code.**
    Particularly with tuples: a comma at the end of a tuple type, which is supposed to _explicitly declare the number of elements_, looks dubiously uncommitted. From a practical standpoint, trailing commas might save me a couple of milliseconds when I want to add a new argument — but with tuples, I actually _want_ adding a new element to take longer, so I'd have that much more time to consider if adding it is really needed.

These are, of course, just my opinions 😄 But in my defence, I guess that it's hard to justify "use cases", since at the end of the day Prettier is a formatting library. Its results are inherently supposed cosmetic, or at least mostly so, and thus people are going to argue over what's "prettier" and what's not.

I suppose a separate option for "trailing commas in types" just allows satisfying more camps of people. I can vouch that, personally, I'd probably pick the `{ trailingCommas: "es5", typesTrailingCommas: "off" }` options, to match Prettier v2 as closely as possible. At least for the first year or so, until I start enough new projects with default settings to get used to the new defaults feeling "prettier" 😄

**Comment by sosukesuzuki** [comment]
Thank you for your thoughtful comment. However, we do not wish to add new options. For more details on our stance, please refer to [Option Philosophy](https://prettier.io/docs/en/option-philosophy). Therefore, we will be updating the documentation to reflect the actual behavior.
