### ISSUE TITLE
Prettier does not allow parens around typecasting in vue templates

### ISSUE THREAD

**Issue by Fuzzyma** [prettier/prettier#15197]
**Prettier 3.0.0**
[Playground link](https://prettier.io/playground/#.....)

```json
{
  "trailingComma": "es5",
  "arrowParens": "avoid",
  "printWidth": 120,
  "plugins": ["prettier-plugin-tailwindcss"],
  "singleQuote": true,
  "htmlWhitespaceSensitivity": "ignore"
}
```

**Input:**

```vue
<MyComponent :some-prop="(variable as boolean)">
```

**Output:**

```vue
<MyComponent :some-prop="variable as boolean">
```

**Expected behavior:**

Prettier removes the parentheses and that breaks syntax highlighting in vscode.
I am aware that this might not be a prettier issue in the end but maybe you can add an exception from the rule here to not remove the parentheses

**Comment by fisker** [comment]
Since the formatted code is valid in [Vue SFC playground](https://play.vuejs.org/#eNp9kD1PwzAQhv+KdXPVDN1CWglQBxgAAaMXJzmCi2NbvnOIVOW/YydqYECdbN374ed8hlvvt0NEKKGiJmjPwijb7SUwSRCEHP1B2sZZYjGooFVtUOwFh4g30lbFEkqWirH3RjGmuxBVHZmdFWWrKUfa1LjGFYnaOYPKSjgsxqpYzlxUrE2wSRjp7Q/dbU/kbKI853YJjeu9NhiePevEJqEUs5I1ZYz7fpxnGXNzmTef2Hz9Mz/RmGcSXgIShgElrBqr0CEv8vHtCcd0X8XetdEk9xXxFcmZmBkX2120bcL+45tpH3rvAmvbvdNxZLR0WSqDZuc0+9MfRry/svov7m67m3PSTjD9AFoAouY=), I'm going to close this issue.

Please ask vscode(or maybe plugin which provide the syntax hight support) to support it.

**Comment by Sinjhin** [comment]
While it may be valid, so is the code with the parenthesis: [Vue SFC Playground](https://play.vuejs.org/#eNp9kT1PwzAQhv+KdRNIVTt0C2klQB1gAASMXpzkCC6ObfnOIVKV/46dqIEBdbJ174efk09w6/26jwgFlFQH7VkYZdudBCYJgpCj30tbO0ssehW0qgyKneAQ8UbacjOHkqVk7LxRjOkuRFlFZmdF0WjKkSY1Xi15RaJyzqCy1xL2s7XczGeu2ixdsEog6fUP3a6P5GziPOV+CbXrvDYYnj3rRCehEJOSNWWM+36cZhl0dZ7Xn1h//TM/0pBnEl4CEoYeJSwaq9Aiz/Lh7QmHdF/EzjXRJPcF8RXJmZgZZ9tdtE3C/uObaB867wJr277TYWC0dF4qg2bnOPklpM+6v7D6L+52vZ1y0o4w/gAjl6M3)

Being that it is stated here: https://github.com/prettier/prettier/issues/15201#issuecomment-1664235050
"The prettier is responsible only for formatting, not for highlighting the code :)"

Why is it changing something like removing parenthesis when both are valid? That goes beyond just "formatting" and is causing problems for people.

**Comment by kouts** [comment]
@fisker maybe you can re-think this issue? This is currently what's keeping us from upgrading to prettier v3 as it breaks syntax highlighting, this used to work fine in prettier v2.
