### ISSUE TITLE
[Request] Print width should not break single attribute html tag into 3 lines

### ISSUE THREAD

**Issue by christhofer** [prettier/prettier#15199]
Using default `printWidth: 80`

I agree with turning multiple attributes into multiple lines
```diff
- <div id="categories" class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
+ <div
+   id="categories"
+   class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
+ >
```

But this doesn't make any sense to me. It is still over the `printWidth` values, doesn't really shorten the line, and adds 2 extra lines to the code.
```diff
- <div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
+ <div
+   class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
+ >
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJPoC8AOuAIbwDmEATpnAM6m5gA2ZDDJIAZq3AA988ALYMAtGATwauAFYBXBjEw8AnuIBGcGAHc4CXAwAOZKeIHiALLhoQFUdHHS5NtJ7M2VxugBaZ4XHgBGHEGEVIAPmIoXFwsPEhYaVxfOBo4GNQAegToqCyElnZObj5BYTgxSWl0+SUVdS0dfUMTMzgLa1t7R2dXdzqvH39A4NDwqJi4oqT4WFT0zKgcvJAAGhAIYxVoBmRQMho7XQAFI4R9lDJWXTI1fc3NGjMAax0AZTIROAAZTCgcGQPBuDDgTxeYHeMA+pjAAMoyBgNAU4JAYJEmCRKLRDAR-AAigoIPBgaC0XIGAIPvi4ESSUCkCDWGDNgBHYnwU52YxXEAccSA5zODYgZFkTCsBEAYQgIhEZGQ-NYrFFeKglH4AEEYMjMJoFFz0v9AWSWWjfDARKwAOqjRhwuAfS4BHABNRKsCcUXYVEAST6sA+YDoOy1jg+MDU-DNrJAxjsYJtL2MSoTjHS2CBmwBYJoMG5ZEoCtjaNMNDzSst1tFCYBMBtBBgvmQAA4AAybDIczAZQvFxVM8mbGBkTSN9DN5AAJk2SjgABUx1dmXGqtp0E50L8yBqFEW4AAxWgK3UIpVkQ0QEAAXxvQA)

I know Prettier is opinionated. But let's see what others think.

**Comment by kachkaev** [comment]
👋 @christhofer! Please see a notice on `printWidth` [in the docs](https://prettier.io/docs/en/options.html#print-width):

> Prettier’s printWidth option does not work the same way. It is not the hard upper allowed line length limit. It is a way to say to Prettier roughly how long you’d like lines to be. Prettier will make both shorter and longer lines, but generally strive to meet the specified printWidth.

**Comment by christhofer** [comment]
> You should be able to find a few previous discussions on this matter via search.

I can't find it. Thus I create this request.

![image](https://github.com/prettier/prettier/assets/13524958/73b76773-fe4b-4fc9-a832-7d853c0c32ec)
![image](https://github.com/prettier/prettier/assets/13524958/eb72f3f8-3e69-423b-a6fb-d6ece87716ab)

I don't see anything that mentions moving a single attribute to a separate line once it reached the `printWidth`.
I just don't think it's necessary to move the attribute down, so an exception and keeping the attribute on the same line looks better to me.

We're free to propose ideas, right?
And you're free to reject the requests. I'm fine either way.

**Comment by kachkaev** [comment]
👋 again @christhofer! I think I have slightly misunderstood your change request because it was not following the [issue template](https://github.com/prettier/prettier/blob/main/.github/ISSUE_TEMPLATE/formatting.md?plain=1).

If I understand your correctly now, here is what you are trying to say:

**Prettier 3.0.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJPoC8AOuAIbwDmEATpnAM6m5gA2ZDDJIAZq3AA988ALYMAtGATwauAFYBXBjEw8AnuIBGcGAHc4CXAwAOZKeIHiALLhoQFUdHHS5NtJ7M2VxugBaZ4XHgBGHEGEVIAPmIoXFwsPEhYaVxfOBo4GNQAegToqCyElnZObj5BYTgxSWl0+SUVdS0dfUMTMzgLa1t7R2dXdzqvH39A4NDwqJi4oqT4WFT0zKgcvJAAGhAIYxVoBmRQMho7XQAFI4R9lDJWXTI1fc3NGjMAax0AZTIROAAZTCgcGQPBuDDgTxeYHeMA+pjAAMoyBgNAU4JAYJEmCRKLRDAR-AAigoIPBgaC0XIGAIPvi4ESSUCkCDWGDNgBHYnwU52YxXEAccSA5zODYgZFkTCsBEAYQgIhEZGQ-NYrFFeKglH4AEEYMjMJoFFz0v9AWSWWjfDARKwAOqjRhwuAfS4BHABNRKsCcUXYVEAST6sA+YDoOy1jg+MDU-DNrJAxjsYJtL2MSoTjHS2CBmwBYJoMG5ZEoCtjaNMNDzSst1tFCYBMBtBBgvmQAA4AAybDIczAZQvFxVM8mbGBkTSN9DN5AAJk2SjgABUx1dmXGqtp0E50L8yBqFEW4AAxWgK3UIpVkQ0QEAAXxvQA)

```sh
--parser html
```

**Input:**

```html
<div id="categories" class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>

<div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>
```

**Output:**

```html
<div
  id="categories"
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>

<div
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>

```

**Expected behavior:**


```html
<div
  id="categories"
  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
>
  div content here
</div>

<div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
  div content here
</div>

```

I doubt there is much value in this. By breaking a long attribute into a new line, we reduce future diffs by a lot. When you decide to add `id` later on, you’ll see this:

```diff
 <div
+  id="categories"
   class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
 >
```

not this:

```diff
-<div class="flex items-center justify-between space-x-4 rounded border bg-white text-sm">
+<div
+  id="categories"
+  class="flex items-center justify-between space-x-4 rounded border bg-white text-sm"
 >
```

Did any of the class names change in the last code snippet? I can’t tell that easily.

Broadly speaking, one of the key values of Prettier is bringing consistent formatting to the whole community. Even if we imagine the current behaviour somewhat suboptimal, is it worth a change? There are millions of lines of code that are already written and changing something like you describe will create massive diffs for a lot of people. Imagine how much time would be spent, so for it to be justifiable, added value should be quite high.

**Comment by christhofer** [comment]
Sorry for not using the template
I was confused how to use the template and somehow missed this part `3. Press the "Report issue" button in the lower right`

> I think I have slightly misunderstood your change request
> If I understand your correctly now, here is what you are trying to say:

Yes, you explained it perfectly.

> I doubt there is much value in this. By breaking a long attribute into a new line, we reduce future diffs by a lot.

That's a solid argument, I agree with you on this.
My only argument is that it adds 2 extra lines, multiplied by the occurrences in one file, can significantly add extra mouse scroll.

> There are millions of lines of code that are already written and changing something like you describe will create massive diffs for a lot of people.

Didn't think changing this will format the class attribute back into the first line.
Now that you mention it, most Prettier formats are reversible.
