### ISSUE TITLE
Do not break on extends

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#1520]
```js
class Foo extends Immutable.Record({
  ipaddress: '',
}) {
  +ipaddress: string;
}
```

outputs

```js
class Foo
  extends Immutable.Record({
    ipaddress: ""
  }) {
  +ipaddress: string;
}
```

we should inline it.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Foo%20extends%20Immutable.Record(%7B%5Cn%20%20ipaddress%3A%20''%2C%5Cn%7D)%20%7B%5Cn%20%20%2Bipaddress%3A%20string%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by dmitrika** [comment]
Hello! I'm trying to get into prettier through this bug. So far by [similar example case](https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20a%20extends%20(%7Ba%5Cn%7D)%20%7B%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Atrue%7D%7D) I see, that when group became wrappedGroup, function propagateBreaks from doc-utils calls breakParentGroup, that's why group which includes "extends" breaks. 

First, I checked that just remove "line" before "extends" will not help.

I assume, that`propagateBreaks` function propagate, even if we already don't need breaks.
But, I don't have any ideas how we can check it during reccursion. Maybe you have any ideas?

Or another thought, that we can check this particular case with "extends" and "ObjectExpression" somehow...?

**Comment by azz** [comment]
@dmitrika 
>Or another thought, that we can check this particular case with "extends" and "ObjectExpression" somehow...?

That's the right direction. Start from here:
https://github.com/prettier/prettier/blob/master/src/printer.js#L897

If we disrespect the existing newline in the ObjectExpression in this particular case, we can pass `shouldBreak: false` to `group`.

**Comment by vjeux** [comment]
We should just remove the ability to break in the printer. It was introduced very early on when we didn't break on flow generics, but now that we do it's not useful anymore because the expression itself can break. Also, no one in practice does extends and implements at the same time.

**Comment by azz** [comment]
> Also, no one in practice does extends and implements at the same time.

```ts
export class DisplayObject extends utils.EventEmitter implements interaction.InteractiveTarget {
export class DataView<T extends Slick.SlickData> implements DataProvider {
export class Readable extends events.EventEmitter implements NodeJS.ReadableStream {
export class InMemoryAppender extends log4javascript.Appender implements ICachedLogMessageProvider {
```

It's super common in TypeScript (much to my dismay 😉)

**Comment by vjeux** [comment]
@azz do you know how people break this kind of code when it goes > 80 columns?

**Comment by dmitrika** [comment]
>We should just remove the ability to break in the printer. 

You mean get rid of post-factum `docUtils.propagateBreaks(doc);` and prevent from ability break parents group?

**Comment by azz** [comment]
@vjeux 
Both of these are common:


```ts
export class DisplayObject
  extends utils.EventEmitter 
  implements interaction.InteractiveTarget {
}
```
```ts
export class DisplayObject extends utils.EventEmitter 
  implements interaction.InteractiveTarget {
}
```

If there are multiple `implements`:

```ts
export class DisplayObject extends utils.EventEmitter 
  implements interaction.InteractiveTarget,
    somethingElse.SomeOtherThing,
    somethingElseAgain.RunningOutOfNames {
}
```
