### ISSUE TITLE
[v3] [error] Using pre-commit and a plugin I get: Cannot find package '{plugin}' imported from PROJECT_DIR/noop.js

### ISSUE THREAD

**Issue by benediktsatalia** [prettier/prettier#15388]
**Environments:**

- Prettier Version: 3.0.3
- Running Prettier via: pre-commit
- Runtime: pre-commit 3.4.0
- Operating System: Linux
- Prettier plugins (if any): prettier-plugin-java

**Steps to reproduce:**

I am trying to use prettier with pre-commit in a Java repository. It works for prettier v2, but not for v3. For a minimal example I modified a [Java hello world repository](https://github.com/benediktsatalia/hello-world-java/tree/prettier-v3) and added a pre-commit configuration once with prettier v3 and once with prettier v2.

1. [Install pre-commit](https://pre-commit.com/#install)
2. `git clone --branch prettier-v3 git@github.com:benediktsatalia/hello-world-java.git`
3. `cd hello-world-java`
4. `pre-commit run --all-files`

**Expected behavior:**

Correctly formatting the HelloWorld.java file and not printing any errors. You can have a look at the branch `prettier-v2` in the minimal example repository which only changes the version and can run the command `pre-commit run --all-files` successfully.

**Actual behavior:**

Doesn't format HelloWorld.java and prints an error: [error] Cannot find package 'prettier-plugin-java' imported from {PROJECT_DIR/hello-world-java/noop.js`

This might be related to issue #15085 but I didn't understand the answer there enough to see if this is the same issue or not.

**Comment by sosukesuzuki** [comment]
As explained in https://github.com/prettier/prettier/issues/15085#issuecomment-1636993346 , is it solved by having a .prettierrc configuration file and explicitly specifying plugins?

**Comment by benediktsatalia** [comment]
Ok I tried now around for quite a while until I figured, it doesn't work with `.prettierrc` but with `.prettierrc.js` and then also not all variants in the comment work but the following worked for me:

```
const config = {
  plugins:[
    require.resolve("prettier-plugin-java")
  ],
};

module.exports = config;
```

**Comment by sosukesuzuki** [comment]
Thank you. Same as https://github.com/prettier/prettier/issues/15085, I don't think this is a bug. But we can improve documentation.

**Comment by fisker** [comment]
I took a look into the issue with your repo https://github.com/benediktsatalia/hello-world-java/tree/prettier-v3, you use 

```
        additional_dependencies:
          - "prettier@3.0.3"
          - "prettier-plugin-java@2.3.1"
```

so `prettier` and `prettier-plugin-java` will be intalled at location like `~/.cache/pre-commit/repo97ymt72l/node_env-default/lib/node_modules`

then you use

```
        args:
          - --plugin=prettier-plugin-java
```

so the actual command is like `prettier --plugin=prettier-plugin-java` we'll try to load plugin from `<CWD>`(the dir where you clone `hello-world-java`), which is not possible.

So possible solutions:

1. Use an absolute path to the plugin, (I don't know if there is a way to programmably get it)

```js
        args:
          - --plugin=/home/<REPLACE_THIS_WITH_YOUR_USERNAME>/.cache/pre-commit/repo97ymt72l/node_env-default/lib/node_modules/prettier-plugin-java/dist/index.js
```

2. Install the plugin in your repo

Instead of using `additional_dependencies`, Run `npm install prettier-plugin-java` to install the plugin in your repo, then run with `--plugin=prettier-plugin-java` or put `plugins: ['prettier-plugin-java']` in your `.prettierrc` file.

---

It breaks in v3 because we removed plugin search feature.
In v2 when running Prettier, it will search `prettier-plugin-java` and it's next to `prettier` directory, so you don't even need `--plugin` argument to make it work.

Sorry that the solutions I offered are not easy to use, but I can't come up a better idea, and it's not really something that Prettier can do. I suggest ask `pre-commit` for help.

**Comment by fisker** [comment]
I'm not sure how eslint works, but it seems that ESLint can resolve the plugin. https://github.com/pre-commit/mirrors-eslint

Maybe something worth to take a look.
But ESLint it uses `require`, maybe `pre-commit` provide `NODE_ENV` to resolve the plugins? I don't know.

**Comment by benediktsatalia** [comment]
@fisker thanks for having a look, just for completeness: 
> 1. Use an absolute path to the plugin, (I don't know if there is a way to programmably get it)

problem here is that `pre-commit` generates this path dynamically, so cannot hard code as in your code example
> 2. Install the plugin in your repo

My repo is no `node` repo and in my opinion it would be weird for a pure Java project just to be able to use some formatter.

To be honest all those problems lead me to the thinking that prettier is just not meant to be used for a pure Java project, yes there is this plugin, but as soon as you want it to work with other tools it gets hard (I also couldn't get the Intellij Plugin set up for the Java project).

**Comment by benediktsatalia** [comment]
I think we can close this since there is a [solution to the problem](https://github.com/prettier/prettier/issues/15388#issuecomment-1717746872).

**Comment by flying-sheep** [comment]
I’d call that a workaround.

Not being able to use a declarative (JSON, YAML) config file as soon as one starts using plugins is pretty disruptive.

An actual solution would be that either prettier or the mirrors-prettier hook allow this to just work again.

**Comment by mon-jai** [comment]
npm somehow works for me but yarn PnP doesn't, even I unplugged the plugin.
