### ISSUE TITLE
Template Literal expression comments moving outside expression

### ISSUE THREAD

**Issue by josephfrazier** [prettier/prettier#1559]
This is one of the issues in https://github.com/prettier/prettier/pull/1553#issuecomment-300019071

To reproduce:

    AST_COMPARE=1 npm test -- tests/template -t comment

or:

    prettier --debug-check tests/template/comment.js

EDIT: This looks very similar to https://github.com/prettier/prettier/issues/623

**Comment by bakkot** [comment]
More readable repro:

```js
`${
0
// comment
}`;
```

([link](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%60%24%7B%5Cn0%5Cn%2F%2F%20comment%5Cn%7D%60%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D))

Prettier moves the comment to outside the `${...}`, which makes it a part of the template itself, rather than a comment.

**Comment by josephfrazier** [comment]
FWIW, the snapshot associated with this bug is currently incorrect (as you might expect from the AST comparison): https://github.com/prettier/prettier/blob/5cda955efc8ec7ecbd4ccf1d6f3e0fa2f9679178/tests/template/__snapshots__/jsfmt.spec.js.snap#L41-L69
