### ISSUE TITLE
Can't use @ inside a tag since v3

### ISSUE THREAD

**Issue by clebasc** [prettier/prettier#15660]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHxwAe2AtpgDZwACAJhCdgJZQB0kJqA9FrniADQgImGI2jpkobACdpEAO4AFGQgkps5edgCeEwQCNp2MAGs4MAMqk4AGWZxkAMw3o4Bo6fMWcYZgHNkGGkAVzcQVxJGQJCw9H9KAEVgiHgnFzCAK3RCC3i4JJSHJGdyV0EAR2T4RTlMNRBsdABaKDg4GnaBECCmcn8AYXoGZAbyci64qD9KAEEYIMZ9YOq4aTtWtNKwgAsYEnIAdW3GeB4wOAtVE8YANxPtEbB0PRAb0IBJKA7YCzBpRhEMy+Fhg2komzKIEwclcByMmBG0LgrmkNwcgmYKJgNWwfmGxXSghw0hRI1wfmC5BkXWhzBgB0YNBg22QAA4AAyCaRwSqMbk4vHYCFhGDYfQMpkspAAJkEwVcABUxWoSpC4CR9O0OjQbOTgri4AAxCDSBjzfxk5YQEAAXxtQA)

```sh
--parser angular
```

**Input:**

```html
<span>example@domain.com</span>
```

**Output:**

```html
SyntaxError: Incomplete block "domain". If you meant to write the @ character, you should use the "&#64;" HTML entity instead. (1:14)
> 1 | <span>example@domain.com</span>
    |              ^^^^^^^
```

**Expected behavior:**
It should not fail

**Comment by minijus** [comment]
This error is from Angular itself, see: https://stackblitz.com/edit/angular-wbkyse?file=src%2Fmain.ts 

I guess it could be that one is not yet using Angular v17, but trying to update to Prettier v3.1 would trigger exactly the same error because Prettier uses updated parser internally (?).

It should be enough to replace `@` with `&#64;`:
```
<span>example&#64;domain.com</span>
```

**Comment by clebasc** [comment]
Great thank you, i looked in more detail and indeed it is linked to the "block syntax" feature of angular v17
