### ISSUE TITLE
Formatting stuck in loop moving brace

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier#15744]
**Prettier 3.1.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAKYAdKACbBDAGmwHpitdSsBfJbAFQEpsBeAPmygFcAbbgbiwgCICAAcYAS2gBnZKDwAnBRADuABUUJZKPNxV4AnrOEAjBXjABrODADKeALZwAMhKhxkAM13S4p81Y2tqIWbgDmyDAKnH4gvg4SkdGxcAAeonAKEk6wunSZUIoScNre3L7C0uHccACKnBDwXj6xAFbSqbbVdQ1NSGUVIACOvXBqyqLaIHjSALTucAAmS0IgUXgS3OEAwhAODnjI07yrVVBhNQCCMFESJpzwapmu7s3lsQAWMA7cAOofEng0hCYDgti0gIkADdAQYjmBpMYQFCYgBJKDLWC2MBZcSXDG2GAGGpvQaiZS+X7mURHcklTJQjzCNy+BQwcZ4MIHUmxEIKVlHIkZaQ4iTiVbktwwX4SRYwD7IAAcAAZhAo4CMJOqOVzDv0WsIYHgTDK5QqkAAmYScXx0Y2lA0gOAOExLZaLZx4c6cTlwABiEAUBxu4SOeAeEBAVCoQA)

```sh
--parser typescript
```

**Input:**

```tsx
({
  a, //
  //
}: T) => null;

```

**Output:**

```tsx
({
  a, //
} //
: T) => null;

```

**Expected behavior:**

If we run formatting on the output above, it reverts back to the input above.

https://github.com/prettier/prettier/assets/921609/44f51d4d-16f3-47b4-87dc-3df25134bf2d

**Comment by fisker** [comment]
Fixed by #15708


**Prettier pr-15708**
[Playground link](https://deploy-preview-15708--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuEAKYAdKACbBDAGmwHpitdSsBfJbAFQEpsBeAPmygFcAbbgbhAEQEAA4wAltADOyUHgBO8iAHcACgoQyUebsrwBPGUIBG8vGADWcGAGU8AWzgAZcVDjIAZjqlwTZy9Y2IuauAObIMPKcviA+9uIRUTFwAB4icPLijrA6dBlQCuJwWl7cPkJSYdxwAIqcEPCe3jEAVlIpNlW19Y1IpeUgAI49cKpKIlogeFIAtG5wACaLgiCReOLcYQDCEPb2eMhTvCuVUKHVAIIwkeLGnPCqGS5uTWUxABYw9twA6u-i8CkwTAcBsmgB4gAbgD9IcwFIjCBIdEAJJQJawGxgTJiC7omwwfTVV4DERKHw-MwiQ5k4oZSHuISuHzyGBjPChfYkmLBeQsw6E9JSbHiMQrMmuGA-cQLGDvZAADgADEJ5HBhuI1ezOQc+s0hDA8MZpbL5UgAExCTg+OhGkr6kBwezGRZLBZOPBnTgcuAAMQg8n21zChzw9wgICoVCAA)

```sh
--parser typescript
```

**Input:**

```tsx
({
  a, //
  //
}: T) => null;
```

**Output:**

```tsx
({
  a, //
  //
}: T) => null;

```
