### ISSUE TITLE
Why Commas are replaced with semicolons when i format code with prettier

### ISSUE THREAD

**Issue by amalamalamal** [prettier/prettier#16075]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#.....)

```sh
# Options (if any):
--single-quote
```

**Input:**

```jsx
// code snippet
```

**Output:**

```jsx
// code snippet
```

**Expected output:**

```jsx
// code snippet
```

**Why?**

**Comment by amalamalamal** [comment]
Input:
data: {nom: string, prenom:string}
Output:
data:{nom:string; prenom:string}
Expected:
data:{nom:string, prenom:string}
Why?

**Comment by kachkaev** [comment]
The issue is somewhat obscure, so I’m not sure we can help with it. If you experience comma to semicolon conversion in typings, it’s expected behavior.

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOBbCTAXkwApsBDGCpTYTKCPWjAJwEsoBzAGkwAdWCJixgdumAL4BKYgD46AHSiZMkKGggAbOADotELuSoVpyycpA8QEfjHbpkoCq1YQA7gAUXCNMhAUWu4UAJ5+1gBGrBRgANZwMADKFHhwADKccMgAZoFocJHRcQmJ-DGcXMhiAK4FIPl47FWstdZwAB78cBypsIEAKt1QLuxwfki5WvnWaBU6AIrVEPA5eXUAVmjtiXNwi8tZE2vWAI5L8J5u-OMBaAC0UHBwuNhWIGIU7FoVAMJMeBR-IEtG9ZtwdABBGBidgRaoXboZR6rKZ1AAWMDwWgA6mj2PA0GUwHBEr58ewAG74kL+MBocIgCm1ACSUFwsESYA4dghbMSMBCOhR0xAggg+Wx0X4-kEY26FKy1k4+VYMEuFC4AOFdTKrBV-gFXTQXPYdjegk4MGx7GwMDRyAAHAAGaxCM7sITqzWAo6o6zUCLW232pAAJms1Xy-QoEXGkxF+AizxeaQo3GqGrgADEIKwAdCKkD4RAQJJJEA)

```sh
--parser typescript
```

**Input:**

```tsx
const demo = (data: { nom: string, prenom: string }) => {
  console.log(data)
}

```

**Output:**

```tsx
const demo = (data: { nom: string; prenom: string }) => {
  console.log(data);
};

```

---

**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOBbCTAXkwApsBDGCpTYTKCPWjAJwEsoBzAGkwAdWCJixgdumAL4BKYgD46AHSiZMkKGggAbOADotELuSoVpyycpA8QEfjHbpkoCq1YQA7gAUXCNMhAUWu4UAJ5+1gBGrBRgANZwMADKFHhwADKccMgAZoFocJHRcQmJ-DGcXMhiAK4FIPl47Dl5dXAAHvxwHKmwgQAqXVAu7HB+SLla+dZoFToAitUQ8M2TdQBWaG2Js3ALS1njLdYAjovwnm78YwFoALRQcHC42FYgYhTsWhUAwkx4FP5AlpXjNuDoAIIwMTsCLVc5dDIPFZTEAACxgeC0AHVUex4GgymA4IlfHj2AA3PEhfxgNDhEDk2oASSguFgiTAHDs4NZiRgIR0yLqggg+Sx0X4-kEoy65Ky1k4+VYMAuFC4-yF1jKrCV-n5nTQnPYdlegk4MCx7GwMFRyAAHAAGaxCU7sISq9UAw6razUCKW622pAAJms1XyfQoETGExR+AiT2eaQo3GqargADEIKx-lCKoC4RAQJJJEA)

```sh
--parser typescript
--no-semi
```

**Input:**

```tsx
const demo = (data: { nom: string, prenom: string }) => {
  console.log(data)
}

```

**Output:**

```tsx
const demo = (data: { nom: string; prenom: string }) => {
  console.log(data)
}

```
