### ISSUE TITLE
Simple template literal should break at all interpolations instead of exceeding the max line width

### ISSUE THREAD

**Issue by sxxov** [prettier/prettier#16114]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAA2wBJgA3OAJwE8A6S2h6+x1lugG2gHM6wAFtgCWUAL4AjMm2ZMZ8jtyh9BI8dI4K5mndr3t9sg8aOmtJ82d0XFvfkNFjCAbgA6USFAyYJ+TAHJsf0wAakxLCNtlezVQgIlgsMjDGSUVByg45JsU6ytcgpyi-OLsrjtVUTcod09vMD9ibGaW1rb2js6u7p6yHv6Bwe6ACgBKOgkx-imAEym4Mada9CwZv0Chza3txJxt-YPmqcnxsFn5serlryw4RrIAbUPWgBofCQ-Pr++fiTewAGAoHAwFvGbgiGQqHQmZvODwhGIpHwgC6dAAVhBRMN-P5Rk5qnUsAAzda7J7PZpvX40mn-EEMoFgmEs6Fw5EchFozHY3GjOK4q4eFaYHj3YDDMb4AB8e0p8v2o0WLmu3gEZLikv5eFlCr1WyV-LCgvcqqwwnFlMwADJre9aQ7fLbMIzXWACWbMOiNWErc7HY6bXa3YyBf53CAXiAIAAHGDCdDIUDYKhUCAAdwACimEGhkCBsJx09gaHmoxIqNgwABrOAwADK2AAtnAADKiODIYmFtBwcuVmt1+sxquiHjIGBUACufZAvabwgn09ncAAHjHqMIW7BCwAVahQFPCOB5pDdzi9qNoMecOAARSnEHgXZ7s-RaFX9Zv98fz7Pr6jABHX84EzNMY1PAs0AAWigeEZjgGZIxAScRE4McAGEICbJtsHzQtOGQ69lFvABBGBJ2ECQp3gTNqHbOCXwvWcBBgJtOAAdQEYR4DQEcwDgetcx44RyB4mh8zANAyxAcgZwASSgBDYHrMAqGEONSKU+sYBoW8mMvEAYzTXsOMrGN82Mk9qEoZDRF7KgYDA7AeFwgzZxHKgHPzCRsAkOBCKjYzRBgDjhBmGABGQAAOAAGKMqDgYDhES5zXLw-9mKjGA-LCiKoqQAAmKMp17Xc-NPc9DLgJt-PBRDW2wZQpxcuAADEICoXCKLHfCaIgEAxDEIA)

```sh
--parser babel
```

**Input:**

```jsx
const a = `a${very.very.very.very.very.long.chain}b${very.very.very.very.very.long.chain}${very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.long.chain}`;
const b = 'a' + very.very.very.very.very.long.chain + 'b' + very.very.very.very.very.long.chain + very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.long.chain;

const c = `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa().b().c().d().e()}`
const d = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' + aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa().b().c().d().e();

const e = `${[aaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccc, dddddddddddddddddddddd, eeeeeeeeeeeeeeeee].join('')}`;
const f = '' + [aaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccc, dddddddddddddddddddddd, eeeeeeeeeeeeeeeee].join('') + '';

const g = `${(() => aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)()}`;
const h = '' + (() => aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)() + '';

const i = `${aaaaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbbb && cccccccccccccccccc}`;
const j = '' + aaaaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbbb && cccccccccccccccccc + ''
```

**Output:**

```jsx
const a = `a${very.very.very.very.very.long.chain}b${very.very.very.very.very.long.chain}${very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.very.long.chain}`;
const b =
  "a" +
  very.very.very.very.very.long.chain +
  "b" +
  very.very.very.very.very.long.chain +
  very.very.very.very.very.very.very.very.very.very.very.very.very.very.very
    .very.very.very.very.very.very.very.very.very.very.long.chain;

const c = `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa().b().c().d().e()}`;
const d =
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa()
    .b()
    .c()
    .d()
    .e();

const e = `${[aaaaaaaaaaaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccc, dddddddddddddddddddddd, eeeeeeeeeeeeeeeee].join("")}`;
const f =
  "" +
  [
    aaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccc,
    dddddddddddddddddddddd,
    eeeeeeeeeeeeeeeee,
  ].join("") +
  "";

const g = `${(() => aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)()}`;
const h =
  "" +
  (() =>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)() +
  "";

const i = `${aaaaaaaaaaaaaaaaaaaaaaa && bbbbbbbbbbbbbbbbbbbbbb && cccccccccccccccccc}`;
const j =
  "" + aaaaaaaaaaaaaaaaaaaaaaa &&
  bbbbbbbbbbbbbbbbbbbbbb &&
  cccccccccccccccccc + "";

```

**Expected output:**

```jsx
const a = `a${
    very.very.very.very.very.long.chain
  }b${
    very.very.very.very.very.long.chain
  }${
    very.very.very.very.very.very.very.very.very.very.very.very.very.very.very
      .very.very.very.very.very.very.very.very.very.very.long.chain
  }`;
const b =
  "a" +
  very.very.very.very.very.long.chain +
  "b" +
  very.very.very.very.very.long.chain +
  very.very.very.very.very.very.very.very.very.very.very.very.very.very.very
    .very.very.very.very.very.very.very.very.very.very.long.chain;

const c = `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa${
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa()
    .b()
    .c()
    .d()
    .e()
  }`;
const d =
  "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" +
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa()
    .b()
    .c()
    .d()
    .e();

const e = `${
    [
      aaaaaaaaaaaaaaaaaaaaaaaaa,
      bbbbbbbbbbbbbbbbbbbbbbb,
      cccccccccccccccccc,
      dddddddddddddddddddddd,
      eeeeeeeeeeeeeeeee
    ].join("")
  }`;
const f =
  "" +
  [
    aaaaaaaaaaaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbbbbbbbb,
    cccccccccccccccccc,
    dddddddddddddddddddddd,
    eeeeeeeeeeeeeeeee,
  ].join("") +
  "";

const g = `${
    (() =>
      aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)()
  }`;
const h =
  "" +
  (() =>
    aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa)() +
  "";

const i = `${
    aaaaaaaaaaaaaaaaaaaaaaa &&
    bbbbbbbbbbbbbbbbbbbbbb &&
    cccccccccccccccccc
  }`;
const j =
  "" + aaaaaaaaaaaaaaaaaaaaaaa &&
  bbbbbbbbbbbbbbbbbbbbbb &&
  cccccccccccccccccc + "";

```

**Why?**

Having template literals overflow the defined line width makes them quite unreadable. I've got a few of these in my project that have `long.property.access.chains`, which cause a lot of horizontal scrolling. It also departs from the usual formatting prettier applies to the rest of your code.

The suggested expected output simply bases it from how prettier usually formats string concatenations.

EDIT: Changed title & content since I found the same behaviour for long arrays, objects, etc. (& couldn't find a duplicate 🥸)

EDIT: https://github.com/prettier/prettier/issues/16114#issuecomment-1960904927

**Comment by sxxov** [comment]
Nevermind, issa duplicate.

https://github.com/prettier/prettier/issues/5994#issuecomment-493156023

...even if this behaviour is really kind of crappy, especially if we're using tagged template literals & don't have the alternative of just using string concatenations. Would love to see the prettier team consider **breaking all interpolations** instead of letting it overflow.

**Comment by sxxov** [comment]
I'm going to leave this open to address the possibility of letting them break at every interpolation instead of overflowing. Thank you prettier team for your time in advanced!

**Comment by bakkot** [comment]
If you want to have linebreaks in more complex cases (arrays etc) you can [add a linebreak to the interpolation yourself](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAA2wBJgA3OAJwE8A6S2h6+x1lugG2gHM6wAFtgCWUAL4AjMm2ZMZ8jtyh9BI8dI4K5mndr3t9sg8aOmtJ82d0XFvfkNFjCAbgA6USFAyYJ+TAHJsf0wAakxLCNtlezVQgIlgsMjDGSUVByg45JsU6ytcgpyi-OLsrjtVUTcod09vMD9ibGaW1rb2js6u7p6yHv6Bwe6ACgBKOgkx-imAEym4Mada9CwZv0Chza3txJxt-YPmqcnxsFn5serlryw4RrJ3AG1D1oAaHwlPr++f34l3sCAoHAkFA94zCGQqHQmEzd5wBGIpHIhEAXToACsIKJhv5-KMnNU6lgAGbrXbPF7Nd5-Wm0gGgxnA8Gw1kw+EozmI9FYnF40ZxPFXDwrTA8e7AdzDMb4AB8eypiv2o0WLmu3gE5Li0oFeHlSoNWxVArCQvc6qwwgl7ipmAAZHaPnTnb4HZgmR6wISLZgMVqwra3S6XfbHZ6mYL-O4QK8QBAAA4wYToZCgbBUKgQADuAAV0wg0MgQNhOFnsDRC7GJFRsGAANZwGAAZWwAFs4AAZURwZAkktoOBVmv1xtN+O10Q8ZAwKgAV0HIAHreE07nC7gAA949RhO3YCWACrUKDp4RwQtIPucAextCTzhwACKs4g8F7-YXGLQG6b96fL7fS8P1jABHAC4BzTN4wvYs0AAWigBEZjgGYYxAGcRE4ScAGEIFbVtsCLEtODQu9lAfABBGAZ2ECRZ3gHNqC7RD32vBcBBgVtOAAdQEYR4DQccwDgJsC344RyH4mgizANBKxAch5wASSgZDYCbMAqGERMKNUpsYBoB9WJvEB40zAduJreMizM89qEoNDRAHKgYEg7AeAI4yF3HKhnKLCRsAkOASNjMzRBgbjhBmGABGQAAOAAGWMqDgMDhBStyPMIoC2NjGBAsi6LYqQAAmWNZwHA9AovK8TLgVsgohFCO2wZRZ3cuAADEICoAjqMnIj6IgEAxDEIA), and then Prettier will format it as usual. That doesn't work for simple expressions, but if that's a case you're actually running into we could consider making it work for those as well.

It used to have the behavior you're asking for, but I changed that in https://github.com/prettier/prettier/pull/15209 because [almost no one wanted that behavior](https://github.com/prettier/prettier/issues/3368), so this was the compromise.

**Comment by sxxov** [comment]
@bakkot I think having that escape hatch of just adding a line break in the source code to signal to prettier to break on simple expressions is a perfect workaround. I understand if it's a bit more of a niche use case because usually we'd want to keep interpolations on the same line as the string, but I'm working with interpolation-heavy, string-light tagged template literals (somewhat akin to example `a`), & the previous behaviour is exactly what would help make it more readable.

Thank you for your time & consideration! Would love to see this be proposed forward.

**Comment by bakkot** [comment]
OK, I've opened https://github.com/prettier/prettier/pull/16116. You can [try a playground with your sample](https://deploy-preview-16116--prettier.netlify.app/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDTBeTAA2wBJgAdKTazANzgCcBPAOnubcdfe65YBtoAcxZgAFtgCWUStQC+AIzKyaPThzWa+gqCPFSZVTHOVHqWjXwu9Ltm-fUPrjlTUyOPzr1Z92Bw0QlpFTlCAG5KSCgMTAV8FXIQbETMAGoVbz81HT0gqnSjRIUUgvNfJ3L-XUCDNIzKzIqshpbm5ld3Rs9WpoccmukIwyiYsHwibEmp6ZnZufmFxaXSCiNl9Y3N2YAKAEoOlgU9g7Bjs3cAEzO3Fjhr43DI9CwL+MKkrc+vzZKVb-+AfdqIcge5TvtziwrhCbnddkMntEsHBxoRTG4ANodagA6YAGmxsQUxJJpLJ5IUBPO1DAtLp9IZdKpbmoFzZ7I5nK5F2ZLLg-IFgqF-I6AF0WAArCDSbaJRIwh5DEZYABmb2ocpAdSMWPOuKmvOoFONxsNmEZFoZZu5Nu5ZuFDsFvPFUplmt22o1IESCKgyswQlR6Jo2z2+AAfIT9dGAbt7qElc9MGJ1ZhNZ7MKGPXhI3qY-mtnGPaU096QL7-ZIg6s3PrMAAyesdE0tkkNpvnS1dsAhR5+pMS1Pp1I4XHtlSt1vjozdy1pUs+yggPEgCAABxgknQyFA2AYDAgAHcAAp7hBoZBJfiH7BMC8rhQMbBgADWcBgAGVsABbOAAGWkOBkBVbB+DQOAHyfV93w-Ndn2kIRkBgBgAFcIJAcDv0kJDUPQuAAA810YSRf1gUCABVGCgPdJDgC8kBAsD0LQBD+DgABFFCIHgYDQPAlcJTQfCP1YjiuJ4hi+PQgBHcS4GPA813opI0AAWigfkLjgC5lxAZCpH4BCAGEIG-b9sEvUD+F0ljdDYgBBGBkMkBQUPgY9GAAjTeKYlcxBgb9+AAdTESR4DQOCwDgD9zzCyRaDCphLzANB7xAWg0IASSgLTYA-MAGEkDd7Jyj8YCYNifP4kA1wPcCgqfNdL1qujGHoXTpHAhgYAU7AhHMqr0LghgusvBRsAUOBrJXWrpBgILJAuGAxGQAAOAAGFcGDgWTJG23r+osyTfL0iaFqWlakAAJhXFDwPIib6MY6q4G-Sa2W0v9sF0FC+rgAAxCAGHMpyEMstyIBAOQ5CAA). Honestly it's still kind of weird, mostly because it still treats each interpolation individually, but it's closer to what you were asking for.

**Comment by sxxov** [comment]
I agree it does look kind of weird, I would've expected it to actually fit closer to the source you put in the playground, where it breaks at `${` & as specified by the user.

However otherwise, it's fabulous, I can feel my fingers rest at ease as the days of my horizontal scrolling come to an end.
