### ISSUE TITLE
Readability: Preserve existence of two or less blank lines between code chunks.

### ISSUE THREAD

**Issue by joslarson** [prettier/prettier#1613]
Prettier currently preserves single blank lines between code chunks, I'm proposing preserving existence of two blank or less lines between code chunks. It's fairly common to section off different parts within the same file with two blank lines for readability. As an example, in the following snippet, I'm grouping the external and local imports, separating those related chunks by one line. Then I'm separating all of those imports from the actual code in the file by two lines to show greater separation.

```js
import React from 'react';
import ReactDom from 'react-dom';

import App from './components/App';


ReactDom.render(<App />, document.getElementById('root'));
```

**Comment by gburtini** [comment]
See also #1610. 

I think I am against allowing any violations of the single line rule. For this particular use case, you can use a comment to delineate sections of your code.

**Comment by vjeux** [comment]
Thanks for raising this issue but we're not going to allow this, sorry :( We are trying to create a consistent formatter, preserving at most one empty line is a good heuristic that's simple to explain and works well in practice. It isn't perfect but reasonable. Allowing two lines in some places would be confusing.

I'm going to close this issue.

**Comment by joslarson** [comment]
@gburtini I'd like to push back here a bit, but feel free to ignore me if you need to :) My goal is just to contribute to the discussion.

I understand that opinionatedness is core to this project. That's what I love about it. I don't think this would get in the way of that. It would be a simple opinionated rule:

**"Collapse gaps >= 2 lines to exactly two lines and leave single line gaps as they are."**

And as far a minimal configurability goes, I might be missing something, but I can't think what extra configuration this feature would require. The rule above

I agree that comments are a good way to break up chunks of code, and I do that, but I think the use case I shared above shows there are situations where an explanation is not needed, and so a comment doesn't make sense.

**Comment by vjeux** [comment]
I do not want to ignore you, this is a valid use case that you presented.

The tricky thing is that because prettier is a total formatter, we need to make decisions for every single possible JavaScript that you could write. We haven't found a good heuristic for empty lines, so we made a concession by letting people control where empty lines are, but introduced some strong limitations:
- Can only have a single empty line
- Cannot have empty line at the beginning and end of blocks

We actually want to err on the side of being overly restrictive when we do those trade-offs because it chips away the value that prettier provides: a single keystroke to make your code look good.

The biggest value that prettier provides is when it is integrated in your editing workflow, you don't want to have to think about formatting and just write code in one ugly line and press the magic keystroke once in a while to get it look pretty. The more control we give to the programmer, the more they have to go back and make those small decisions, and teams have to agree on all those, where do you put two lines, how to enforce this...

So, in this case, it would be nice to allow two lines, but I don't think that it's a good trade-off for prettier as a whole.

I hope it gives you a clearer understanding of why I'm pushing back on this request :)

**Comment by joslarson** [comment]
@vjeux sounds good. Thanks for taking the time to reply. I appreciate it. And thanks for your great work on this.

**Comment by gmcdev** [comment]
I recognize that firm opinions are needed in maintaining convention. But vertical white-space is akin to a 2-space tab versus a 3-space tab. 

Vertical space (and comments) can be used wisely to suggest grouping and future modularity. The code may not be ready to divide, but we can communicate to future devs where the anticipated divisions lie.

I find it very off-putting that I cannot control this on a per-project level with `.prettierrc`. Please reconsider your assumptions.
