### ISSUE TITLE
prettier leaves "prettier-ignore" statements in code

### ISSUE THREAD

**Issue by Pomax** [prettier/prettier#16144]
**Prettier 3.2.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUwA5tXHLlM-gLz4A6IABalyggDT5W7eHV74A5IKq06ghZIDOOEghjzUAQxKa4k6AFkI6UwHkAbnGriAvgEp8wflG-58OVAYAQmkOHC43YDYYdGoofCh0MhcAbm9ffAB6TPwAB2jcJwBaHGYoGjgM3X1EgFt5C0MYIQA6VHIafAZG5pbqQyg6CFqGDwAqfABGAFEAagB2NxaYCABlGGpw5lG+uFySQzA4Bkz+fhazulnM0slBQTd0+Pxo2PiAHjoce3wwA81NAA5Qy1OA8BTEMiUGj0BT4XAwXQ8YAAAwAmtZ8IY2Ph7DhtCtqAl0LUAEZOfAAEmAxPqLhRLnwlmsdkc1GRzJscAcThcAD4nn4-O9NBtoMw+TTQpxmC1NCQcEcGPgAAySSb4JYrACquVyTgAwoZTKN8LMpGwwlw5QqlZMtRAADIQADuhuNxw8LnemVF1HFAuefhYlplLQQdE0FBwzQYEge+AA-AIQCn8Eh8CLcgN8KKAJ5I4DASDkagZpT8aR5hQufkSFM+zTZqB8-AuDLCuC1QP8GBS0NwOTtnwwH1dwNCzxdbS6WCPINC5OCC4gDtCjOCIKCYdrn1fex8tI+KAuEDiEAQXK4aCaZCgbH+l0ABWxCFvKGMLsMedv59J-TAABrDhVhBOBHXCOBkCMEwzBAf9DmAmBVmzMAtmQDZ0Dg0xahwDDqCw884AAD31TZQVgYwABUnCgbEcDgd8YNMc9tC4XQAEV0AgeBoOMFiQAAK00YjVi2TjuN4pBmLggBHSS4Cff1cnfEBjSKKB2DoQczxADZDB0LYDWGWpDGQNSyF0tjmF0ABBGANhwUl0HgJ8nAgzS+Ng88hBgWoSAoIQY0Y1C4FWN8Y2+GM83MsAAV0+wsIASUGPRVjATYr1swZ1gLKDpP4uD8ggUwKH6XJzPyRinEcXTwlMagYCUwxmFMryBOzagGvM0lDHJEhdPycIYGjOhmmQAAONUQDYeScDYZrWrMgrvL0vrRvGpAACZzy5Ki+qYwqiLJQdtLoR0BmYdAWrgAAxGhTIc9CPxciAQFrIA)

**Why?**

Based on https://prettier.io/docs/en/ignore.html#command-line-file-patterns, prettier can be told to ignore parts of a file, but there is nothing in the docs that tells you how to make prettier remove the ignore statements after it's done, leaving us with a decidedly "not pretty" result, so either this is a formatting bug where it needs to remove something that shouldn't be there, or there's a flag missing for cleaning up prettier instructions as part of the prettification pass.

**Comment by bakkot** [comment]
If the comment were removed then the next time you formatted the file it would format the thing that you were trying to have not formatted, so this doesn't really make sense. The comments need to stick around.

**Comment by Pomax** [comment]
You run prettier on your source. Either you pipe its output to different files, in which case the comments should get removed because you don't run prettier on those, or you use `--write` to update in place and then you've already accepted the responsibility for shooting yourself in the foot when prettier removes or changes things you didn't think it should remove or change. Either way: no, they shouldn't.

**Comment by bakkot** [comment]
Most people use `--write`, either explicitly or through their editor. The point of `// prettier-ignore` comments is that you have a specific part of the file you want prettier not to touch. It's true that sometimes you only find out that you don't like the formatting after running prettier, but that's what C-z and/or `git reset` are for. The usual flow is that you run prettier, decide you don't like the formatting of a specific part, revert, add `// prettier-ignore` to that part, and then re-run, and all future runs of prettier will correctly leave the formatting of that specific part alone. If prettier removed `// prettier-ignore` comments, that would not work.

There is not a feature for stripping comments when redirecting the output to a separate directory, since that's a very unusual thing to do. And since it's pretty easy to accomplish yourself with `sed` or whatever, it's unlikely to be added as a feature.

**Comment by sosukesuzuki** [comment]
@Pomax Thanks for reporting this. I think bakkot is right - Prettier wont accept this feature request.
