### ISSUE TITLE
Removal of parentheses breaks functionality

### ISSUE THREAD

**Issue by Tetheta** [prettier/prettier#1618]
Definitely an edge case we fixed by writing things out more explicitly, but was a frustrating bug to find.

We were importing then creating a server using: 
`new (require(__dirname))(CONFIG, server);`

The equivalent (explicit) javascript we changed it to is:
```
const Server = require(__dirname)
new Server(CONFIG, server)
```

However prettier formats it as:
`new require(__dirname)(CONFIG, server);`

Which is not the same functionality and caused our server to crash and burn.
Just figured you guys should be aware.

**Comment by existentialism** [comment]
@Tetheta have you tried the latest version?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22new%20(require(__dirname))(CONFIG%2C%20server)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

Should have been fixed by https://github.com/prettier/prettier/pull/1169

**Comment by Tetheta** [comment]
Ah shoot I thought we were on the latest, should've thought to check with that.
Sorry about that.

**Comment by existentialism** [comment]
@Tetheta no worries!
