### ISSUE TITLE
Eslint error

### ISSUE THREAD

**Issue by jbrodriguez** [prettier/prettier#1621]
This code

```javascript
const servers = found
	? state.servers.map(server => {
			if (server.NAME === action.payload.NAME) {
				return setAppDisplay(server, action.payload)
			}

			return server
		})
	: [...state.servers, action.payload]
```

is causing an eslint indent error, because it expects one tab indent less.

This is in vscode (but happens the same on atom), with these settings
```
	"prettier.printWidth": 120,
	"prettier.tabWidth": 4,
	"prettier.singleQuote": true,
	"prettier.trailingComma": "all",
	"prettier.semi": false,
	"prettier.useTabs": true,
```

Any thoughts ?

**Comment by lydell** [comment]
Hi! Thank you for your issue!

The extra indentation there is being discussed in #1280 and #1271.

Other than that, I'd say that it is completely unnecessary to use ESLint's indent rule if you use Prettier. It provides no benefit – only extra time spent. See also [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

I'm going to close this one since I think the other two mentioned issues cover this one.
