### ISSUE TITLE
Variable/others alignment

### ISSUE THREAD

**Issue by nmaxcom** [prettier/prettier#1622]
![image](https://cloud.githubusercontent.com/assets/8936090/26191246/725a737a-3bad-11e7-8cd3-c0ceed6cb08e.png)

I know this is an opinionated issue, but still, how is the formatted output easier on the eyes (prettier 😜 ) than the first one? 

Is it not worth making it available for the teams that want it at least?

**Comment by k15a** [comment]
You can always use `// prettier-ignore` to opt out of prettier. I don't think this is an option which will be added because the majority uses the second format and thus prettier should stay opinionated.

**Comment by josephfrazier** [comment]
It might not be too difficult to add [json-align](https://github.com/nylen/node-json-align) into the printing of `ObjectExpression`s (if they are multiline and parse as JSON (this part might be tricky, since object literal syntax isn't as strict as JSON syntax)). On second thought, it's probably easier and more flexible to directly manipulate the printing of `ObjectProperty` `Identifier`s.

Perhaps this would be a candidate for inclusion in [prettier-miscellaneous](https://github.com/arijs/prettier-miscellaneous)?

**Comment by rhengles** [comment]
@josephfrazier I would accept that 😃 👍 

Sorry for off-topic, but how did you make this spoiler-like box?

**Comment by k15a** [comment]
You can do this with details.

```html
<details>
<summary>Hello</summary>
World
</details>
```

**Comment by josephfrazier** [comment]
@nmaxcom, basic support for this formatting has been added to `prettier-miscellaneous` behind the `--align-object-properties` flag (see https://github.com/arijs/prettier-miscellaneous/pull/7), so you can use that if you'd like.

For reference, this issue was previously discussed at https://github.com/prettier/prettier/issues/350 and https://github.com/prettier/prettier/issues/188.

**Comment by azz** [comment]
I agree with Robert C Martin on this one. Extract from [Clean Code](https://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882), emphasis mine:

> When I was an assembly language programmer, I used horizontal alignment to accentuate
certain structures. When I started coding in C, C++, and eventually Java, I continued to try
to line up all the variable names in a set of declarations, or all the rvalues in a set of assignment
statements. My code might have looked like this:
>
> ```java
> public class FitNesseExpediter implements ResponseSender
> {
>     private   Socket          socket;
>     private   InputStream     input;
>     private   OutputStream    output;
>     private   Request         request;
>     private   Response        response;
>     private   FitNesseContext context;
>     protected long            requestParsingTimeLimit;
>     private   long            requestProgress;
>     private   long            requestParsingDeadline;
>     private   boolean         hasError;
>
>     public FitNesseExpediter(Socket          s,
>                              FitNesseContext context) throws Exception
>     {
>         this.context =            context;
>         socket =                  s;
>         input =                   s.getInputStream();
>         output =                  s.getOutputStream();
>         requestParsingTimeLimit = 10000;
>     }
> ```
> I have found, however, that this kind of alignment is not useful. The **alignment seems to
emphasize the wrong things and leads my eye away from the true intent**. For example, in
the list of declarations above you are tempted to read down the list of variable names without
looking at their types. Likewise, in the list of assignment statements you are tempted to
look down the list of rvalues without ever seeing the assignment operator. To make matters
worse, automatic reformatting tools usually eliminate this kind of alignment.
> 
> So, in the end, I don’t do this kind of thing anymore. Nowadays I prefer unaligned
declarations and assignments, as shown below, because they point out an important defi-
ciency. If I have long lists that need to be aligned, **the problem is the length of the lists, not
the lack of alignment**.

**Comment by Skywalker13** [comment]
Hi @josephfrazier, have you plan to add this feature to `prettier-miscellaneous` but for variable vertical assignments (and maybe declarations) too ?

**Comment by josephfrazier** [comment]
I don't currently have any plans to implement that, as it is much more complicated to determine how the assignments/declarations should be grouped, taking comments and empty lines into account. See https://github.com/prettier/prettier/issues/188#issuecomment-272627905 for more explanation.

**Comment by Matt-Hill-Harness** [comment]
I'd like to see  prettier allow integrations with existing alignment tools.
Once you start to align, it's hard to go back.

**Comment by mjw56** [comment]
It would be nice to have some type of way to handle this situation with prettier.

**Comment by Vincz** [comment]
I agree. Prettier is all about having pretty code auto-formatted. I know a lot of people are using vertical align as it really ease the reading. Working with Ember JS, all is about "extending" objects, and it really get messy without a proper vertical alignment.
Would be really great to add this to the pretty prettier.

**Comment by LinBoLen** [comment]
+1
