### ISSUE TITLE
"sanity timeout expired: Interrupted system call" on WSL2.  

### ISSUE THREAD

**Issue by ubaldot** [prettier/prettier#16249]
**Environments:**

- Prettier Version: cannot see because `prettier --version` hangs.
- Running Prettier via: WSL2 CLI
- Runtime: cannot see because prettier has been installed with snap. 
- Operating System: Ubuntu 22.04.3 on WSL2 on Windows10 
- Prettier plugins (if any): None

**Steps to reproduce:**

Install prettier with snap on WSL2 and run `prettier --version`

**Expected behavior:**

To get the prettier version number.

**Actual behavior:**

`sanity timeout expired: Interrupted system` call message

**Comment by kachkaev** [comment]
I’ve searched for this error and have found a few threads that are not specific to Prettier:
https://www.google.co.uk/search?q=%22sanity%20timeout%20expired%22%20%22Interrupted%20system%20call%22

I guess that this issue is unrelated to Prettier per se, so I’m going to close it. If you think that there is something we can change in Prettier code to resolve the situation, feel free to share some ideas and we will reopen this issue. Any additional info will help!
