### ISSUE TITLE
Odd ternary conditional formatting in template literals

### ISSUE THREAD

**Issue by TimonVS** [prettier/prettier#1626]
I'm trying to use Prettier in a project that uses Styled Components, Styled Components makes extensive use of template literals.

---

**Input:**

```js
const Bar = styled.div`
  color: ${props => (props.highlight.length > 0 ? palette(['text', 'dark', 'tertiary'])(props) : palette(['text', 'dark', 'primary'])(props))} !important;
`
```

**Prettier output:**

```js

const Bar = styled.div`
  color: ${props => (props.highlight.length > 0 ? palette([
                 'text',
                 'dark',
                 'tertiary'
               ])(props) : palette([
                 'text',
                 'dark',
                 'primary'
               ])(props))} !important;
`
```

**I'd expect the output to be:**

```js
const Bar = styled.div`
  color: ${props => 
    props.highlight.length > 0 
      ? palette(['text', 'dark', 'tertiary'])(props) 
      : palette(['text', 'dark', 'primary'])(props)} !important;
`
```

**Comment by vjeux** [comment]
Thanks for the bug report, it actually a combination of 3 issues:
- For the base indentation, I look at matching where the ${ starts but instead it should match only the whitespaces starting at that line.
- The ternary is in one line because it somehow doesn't detect that the [] did break. I'm not sure why the break propagation didn't work in this case.
- The ?: indents by 4 instead of 2 when the condition fits in one line.

Good news is, all those 3 problems are easily fixable and we can get to your expected output :)

**Comment by TimonVS** [comment]
@vjeux Thanks for your insightful reply. Can I help solve the issue? If so, could you give me some directions as I'm not familiar with the Prettier codebase :)

**Comment by vjeux** [comment]
Sorry for the slow answer.

How to repro:

- Create a file `test.js` at the root of the project and paste the code that doesn't work.
- Run `./bin/prettier.js test.js` to repro.

What to edit:
- For ${ alignment: https://github.com/prettier/prettier/blob/master/src/printer.js#L1653
- For ?: on a single line: https://github.com/prettier/prettier/blob/master/src/printer.js#L1071 (You'll probably need to use `ifBreak`
- The break issue is likely going to be harder to fix. I'm not sure where to look right now.

**Comment by TimonVS** [comment]
No problem, thanks for your insights. I'm going to look into it tomorrow morning!

**Comment by vjeux** [comment]
@josephfrazier and I sent two PRs to fix this. Now it looks great :)
