### ISSUE TITLE
Issue formating large HTML file

### ISSUE THREAD

**Issue by gsdev01** [prettier/prettier#16297]
Hi, 
I have a weird formating issue with vscode using prettier, when I format my document, my html is breaking. 
It's a large HTML file with deep nested HTML tags.
See below without formating and after formating using prettier :

![Capture2](https://github.com/prettier/prettier/assets/71656645/21b84ddc-9083-4f41-a8c0-477826a59407)
![Capture1$](https://github.com/prettier/prettier/assets/71656645/bd52726d-c4e9-46c5-ae37-88dc8108437a)

Any help would be appreciated, thanks for the great work !

**Comment by kachkaev** [comment]
👋 @gsdev01! Please follow the [issue template](https://github.com/prettier/prettier/tree/main/.github/ISSUE_TEMPLATE). It’s impossible to help based on screenshots because it’s unclear how to reproduce the issue.

If you are looking for help with Prettier in VS Code, please create a discussion in a different repo: https://github.com/prettier/prettier-vscode/discussions. This particular repo is for Prettier Core.
