### ISSUE TITLE
How to remove the automatic add {" "} ？

### ISSUE THREAD

**Issue by xinnian25** [prettier/prettier#16355]
Using vscode to write react jsx code, using the Prettier plugin, it will be automatically formatted after saving the prettier, it will automatically add {" "} How to remove the automatic add {" "}

Have no idea what to do with it

```
const App = () => {
  return (
    <div>
      <button> </button>{" "}
    </div>
  );
};
```

**Comment by suchipi** [comment]
I don't think this is a dupe of #5531; #5531 is about handling `{" "}`s which were present before the prettier run, but this is about prettier adding a `{" "}` which wasn't there before.

**Comment by suchipi** [comment]
@xinnian25 if you enable "automatic removal of trailing line whitespace" in your text editor, then this problem won't manifest. Or, you can delete these when they appear and they won't come back when you re-run Prettier. It's not safe for Prettier to remove trailing whitespace within JSX because the JSX spec treats that whitespace as significant, and Prettier doesn't know if it was significant *to you* or not, because there are various ways JSX can be used. So Prettier changes these implicit spaces to explicit ones to make you aware of the situation so that you can take proper action.
