### ISSUE TITLE
Doubled brackets in ifs and while loops with assignment

### ISSUE THREAD

**Issue by Aandrzejmi** [prettier/prettier#16412]
**Prettier 3.3.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEBLeBbAbgB0oTsAzTAClzj0wF5M8BDABwDoBzDKgcgDOEPHEwBrOAE8+AShmZyECDXwySJAO4ALbOmq16TFgCdjLSRzYQ2VOZmAlMmAEYmVdGcSgBfEABoQaxhsaAFkUBNjCA0ABRMEMJQWVA1zMIDnMzAJGABlFhEAGWwoOGRyZIE4DKyc3LYWMBKuZBhjAFdqkCq8bFaOrrgADzY4Y2wRWGSAFTGoE2w4RIrUKoCBZvQARXaIeH7OgIArASHczbgdvbKkFbWQAEdd+BiotkSQFgEAWlK4ABMAf4QG0WLpmgBhYSsZAgJYAVmBGygXHQAEEYG1sM52i8xsVSuVKl0tDA8KgAOo6eACBpgOC5BK4bAAN1wklhYAE6RALM6AEkoIDYLkwOM2DA0ULcjBJOgiasumwolUKWY2LDlUsxiyygESlVjDBXiwuDDbsSAg1jIbYbLRgIxdgJcDlSUYBTsP8YFpkAAOAAMAWMcCe2BDJrNLAV9xgLGcnu9vqQACYAu0qtN48tLXC8M4AYD-oUWCj2qa4AAxCDGViY5qwli4iAgbzeIA)

```sh
--parser typescript
--single-quote
--trailing-comma es5
```

**Input:**

```tsx
let item;

if (item = map.get('some key')) foo(item)

while (item = array.pop()) {
  bar(item);
}
```

**Output:**

```tsx
let item;

if ((item = map.get('some key'))) foo(item);

while ((item = array.pop())) {
  bar(item);
}

```

**Expected output:**

```tsx
let item;

if (item = map.get('some key')) foo(item);

while (item = array.pop()) {
  bar(item);
}

```

**Why?**
Prettier wrapping assignment operator with brackets double braces of conditional expression

**Comment by kachkaev** [comment]
This behavior is intentional. See https://github.com/prettier/prettier/issues/861 and https://github.com/prettier/prettier/pull/862 for context. Assignments inside `if`s and  loops can be easily confused with condition statements. Extra parentheses highlight the fact that something is off here, which helps developers pay some extra attention to the logic.

If you think that additional parentheses bring more confusion than benefits, I suggest starting a discussion first. There needs to be an agreement about pros and cons in a broader community for Prettier to follow.
