### ISSUE TITLE
Incorrect formatting of markdown table

### ISSUE THREAD

**Issue by bradzacher** [prettier/prettier#16949]
**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABGAFgQwE45jx7qoA6UGAtDbbaRRgAaA8G4M-7TDl6TgsAQA8AVygBLSABM4maDDwQANplx4AfJ3JQQAGhAQADjBHQAzslD45AdwAK+BKZQ55lnAE9TOgEYEwAazgwAMo4ALZwADIiUHDIAGZOxnBePv5BeoRRAObIsoJJIIkhIjl4eTpwAB56cHgiYbBOACo1UPgicA7x8ok6xlnycACKghDwcQn5AFbGFYH9QyNjSF09IACOi3DWcnoOIDjGVNFwkuLaILI4IvJZAMIQISE4yPvy8ud9UJkDAIIwsiJPIJ4NYapFouNuvksDAQvIAOpYETwYzpMBwQL2ZEiABuyNcLzAxg8IBxeQAklBJLBAmBagYflTAjBXANIas9HJEvCCHoXpyOjUcTEdFFEngYNscJknuz8uk8OKXk88L5xBBLJodJyojB4SJxDAsMgABwABh0eDgGxEVqlMueywmOhgOE8+sNxqQACYdIJEo03Z1nSA4CFPCdTuEcF9BNK4AAxCB4J7-LIvHDAiAgAC+OaAA)

```sh
--parser markdown
```

**Input:**

```markdown
| character |
| --------- |
| `🏳` |
| `‍<unicode control char>` |

```

**Output:**

```markdown
| character                 |
| ------------------------- |
| `🏳`                      |
| `‍<unicode control char>` |

```

**Expected output:**

```markdown
| character                 |
| ------------------------- |
| `🏳`                      |
| `‍<unicode control char>`  |
```

**Why?**

The non-emoji row should be the same width as the other non-emoji rows so it lines up

**Comment by kachkaev** [comment]
👋 @bradzacher! Let's track this issue in #15664. TLDR: Not sure if there is a simple fix because of different fonts, but open to suggestions 🙌

**Comment by bradzacher** [comment]
@kachkaev is it the same issue? The row in question doesn't have any special characters in it - they're all plain fixed width ascii.

**Comment by kachkaev** [comment]
I looked at your example again and found something interesting. Just keeping one row with `` `foo` `` is enough to produce something similar:

**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABGAFgQwE45jx7qoA6UGAtDbbaRRgAaCwBAGYQRMNQgA0ICAAcYAS2gBnZKHx4IAdwAK+BFJQ4ANvJwBPKQIBGBMAGs4MAMo4AtnAAyoqHGRtNEuIeNnLQwo4DmyDB4AK4eIO7WokGh4XAAHkJweKK2sJoAKslQ+KJwaq4a7gISARpwAIohEPAubuEAVhLxFmWV1bVIhcUgAI4dcIpyQmogOBJUTnAAJjP8IME4ohoBAMIQ1tY4yGMaGvOlUP7lAIIwwaIGIfCKyQ5OdUXhWDDWGgDqWKLwEr5gcBZVN9RAA3b46HZgCT6EAgsIASSgs1gFjAKREJyRFhgOnKjx6Qjk7neBCEO0J+WSIOcAkc7jwMCGOH8W3x4V8eHpOy2eBM0wUvAEhMcMHeommMCwyAAHAAGAR4OD9USKpks7ZdeoCGA4AxiiVSpAAJgEIXcGV1BS1IDg1gMM1m0zsOCOIWZcAAYhA8FtzgEdjhrhAQABfENAA)

```sh
--parser markdown
```

**Input:**

```markdown
| character |
| --------- |
| `‍foo` |

```

**Output:**

```markdown
| character |
| --------- |
| `‍foo`    |

```

I erased the last line and typed it in by hand, Prettier worked as expected:

**Prettier 3.4.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAfABGAFgQwE45jx7qoA6UGAtDbbaRRgAYBmEETDUIANCBAAcYAS2gBnZKHx4IAdwAK+BBJQ4ANrJwBPCXwBGBMAGs4MAMo4AtnAAywqHGQt1YuPsMnzAwvYDmyGDwAVzcQV0thAODQuAAPATg8YWtYdQAVRKh8YTgVZzVXPjE-NTgARSCIeCcXUIArMVizEvLK6qR8wpAARza4eRkBFRAcMSoHOAATKd4QQJxhNT8AYQhLSxxkEbU1WeKoX1KAQRhA4T0g+HlEuwcagtCsGEs1AHUsYXgxbzA4M2VPsIAG6fLRbMBiXQgIEhACSUGmsDMYCSQiOCLMMC0pXuXQEMlcrwIAi2+NyiSBjj49lceBgAxwvg2uNC3jwtK2GzwRkmcm4fHx9hgr2EkxgWGQAA4AAx8PBwXrCeUMpmbDq1PgwHB6EViiVIABMfCCrjS2ryGpAcEseim00mNhwByCjLgADEIHgNqc-FscJcICAAL5BoA)

```sh
--parser markdown
```

**Input:**

```markdown
| character |
| --------- |
| `foo` |

```

**Output:**

```markdown
| character |
| --------- |
| `foo`     |

```

It turned out that your backtick before `foo` was two Unicode symbols: `[U+0060](https://unicodeplus.com/U+0060)` and [U+200D](https://unicodeplus.com/U+200D). The latter had a width of zero which pushed `|` one character left.

Not sure we should handle _Zero Width Joiner_ in cases like yours as its presence is probably a mistake. Either way, it behaves similarly as emoji by rendering itself using less or more than one column in a fixed-width font.
