### ISSUE TITLE
CLI is not ignoring node_modules

### ISSUE THREAD

**Issue by Avcajaraville** [prettier/prettier#1707]
Whenever I run ````prettier --single-quote --trailing-comma es5 --write "./**/*.js"```` I get also my node_modules being "prettier". 

Im using node v6.10.3 on a Mac OS Sierra 10.12.5

Also, I find a lack of documentation on which globals library is using and a weird syntax.

Plus, column width values seems also to be ignored, since some files exceed it and got no warnings, no auto format or whatsoever.

**Comment by k15a** [comment]
There was a change recently which removed this behavior on master. Just needs to be released.

**Comment by Avcajaraville** [comment]
Shouldn't this be specified then on the documentation ? When is this release expected ?

And about the global syntax ? How can I ignore node_modules straight from the CLI ?

**Comment by lydell** [comment]
> Shouldn't this be specified then on the documentation ?

[It is](https://github.com/prettier/prettier/blob/0adeadb16ea5e70e18902bc700d0cce3260f962d/README.md#cli):

> Prettier CLI will ignore files located in `node_modules` directory. To opt-out from this behavior use `--with-node-modules` flag.

---

> And about the global syntax ?

I've added a link to the glob syntax to the readme now:

> The [glob syntax from the glob module](https://github.com/isaacs/node-glob/blob/master/README.md#glob-primer)
is used.

---

> How can I ignore node_modules straight from the CLI ?

In the upcoming version, you don't need to do anything at all. Prettier will ignore `node_modules` automatically. Until then, see #1358.

---

I'm going to close this issue since I don't think there's anything to do in it.

**Comment by Avcajaraville** [comment]
Great !! Amazing answer !! Thank you so much and keep on the amazing work :)

**Comment by jthegedus** [comment]
I just came across a problem where I read the docs and assumed it ignored the node_modules as it states, but as I've just learned this is because those actual changes are not yet released. It would be good if those things could be kept aligned in some manner. I know this is user error too as I did not change branch from master to the latest releases tag when loading the code tab, but GitHub doesn't help here either loading master. I won't make that mistake again.
