### ISSUE TITLE
Prettier reports strange errors through prettier-eslint

### ISSUE THREAD

**Issue by Magellol** [prettier/prettier#1889]
Hey guys,

I'm using `prettier` and `prettier-eslint`. Since `1.4.0` prettier started to complain about some weird errors we didn't have before. Downgrading it fixes the issue.

<img width="530" alt="screen shot 2017-06-02 at 2 46 35 pm" src="https://cloud.githubusercontent.com/assets/3819093/26740216/a7f4bdbe-47a2-11e7-83d7-3854db1000ec.png">

Basically here, it asks me to remove the parenthesis, although it didn't before and our ESLint rules enforce us to have them.

Let me know if you need anything more 👍

**Comment by k15a** [comment]
You have to remember that prettier isn't respecting your ESLint config. Prettier always prints the code with a default opinionated structure. prettier-eslint infers some Prettier config options (we only have a few) from the ESLint config. In you example, prettier removes the parentheses and ESLint complains about that. It seems that ESLint can't automatically fix this issue otherwise you didn't get this error.

**Comment by vjeux** [comment]
Hey, this is actually intended. We are no longer adding parenthesis for functional components that return JSX. I would recommend disabling the lint rule.

**Comment by Magellol** [comment]
Gotcha! All of that makes sense, thanks for the explanations.
