### ISSUE TITLE
TypeScript commas for types aliases instead of semicolons

### ISSUE THREAD

**Issue by calebmer** [prettier/prettier#1944]
Using semicolons to delimit fields in TypeScript classes and interfaces makes sense, but I’ve always found commas in TypeScript type aliases more attractive. Take for instance the following constructor which takes named arguments:

```ts
constructor({
  name,
  context,
  audio,
}: {
  name: string,
  context: AudioContext,
  audio: AudioNode | null,
}) { ... }
```

Prettier formats that to:

```ts
constructor({
  name,
  context,
  audio,
}: {
  name: string;
  context: AudioContext;
  audio: AudioNode | null;
}) { ... }
```

(Note the semicolons.)

I personally think it makes sense to use commas for TypeScript type aliases and semicolons in interfaces/classes, so using the following heuristic:

```ts
interface X {
  name: string;
  context: AudioContext;
  audio: AudioNode | null;
}

class X {
  name: string;
  context: AudioContext;
  audio: AudioNode | null;
}

type X = {
  name: string,
  context: AudioContext,
  audio: AudioNode | null,
};

const x: {
  name: string,
  context: AudioContext,
  audio: AudioNode | null,
};
```

Thoughts? Would you accept a PR making this change?

**Comment by vjeux** [comment]
We had `,` for the release instead of `;` and many people complained, so I reverted it to `;`. I'm not really sure what's the right thing to do :( https://github.com/prettier/prettier/pull/1918

**Comment by cloudkite** [comment]
+1 for using `,` if using typescript with no-semi it doesn't output a delimiter between type properties at all

ie 

```
type Thing = {
  stuff1: boolean,
  stuff2: boolean,
  cool: number;
}
```

becomes

```
type Thing = {
  stuff1: boolean
  stuff2: boolean
  cool: number
}
```

which feels super weird even though it compiles as valid typescript

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Thing%20%3D%20%7B%5Cn%20%20stuff1%3A%20boolean%2C%5Cn%20%20stuff2%3A%20boolean%2C%5Cn%20%20cool%3A%20number%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Afalse%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by mafredri** [comment]
I think it might be helpful to think of whatever is on the other side of `:` as an inline interface, in this regard, it makes most sense to keep `;` as a separator, not `,` which would indicate an object.

If we were to use [TypeScript docs: Interfaces](https://www.typescriptlang.org/docs/handbook/interfaces.html) as a reference, we would see that `;` is used, this should be reason enough to keep `;` IMO.

Considering the above, I agree with @calebmer on all points above, except the last:

```typescript
const x: {
  name: string,
  context: AudioContext,
  audio: AudioNode | null,
};
```

should be

```typescript
const x: {
  name: string;
  context: AudioContext;
  audio: AudioNode | null;
};
```

because we're dealing with an interface.

**Comment by mafredri** [comment]
@cloudkite type aliases are also formatted with `;` in the TypeScript docs, as we can see in the [Advanced Types](https://www.typescriptlang.org/docs/handbook/advanced-types.html) section. Since it's unique TypeScript syntax, I don't think it should be confused with objects, and thus using `,` would be misleading.

**Comment by azz** [comment]
Vote here! 

👍 to keep existing behaviour
👎 to change to commas

**Comment by mafredri** [comment]
I don't think this should be up for vote, I think we should follow correct TypeScript semantics. Even though `,` works (hey, this is JavaScript), doesn't mean it's correct.

As an example:

```javascript
(() => {return console.log(1), 2})();
```

comes to mind. This logs `1` and returns `2`, works because whatever comes before the comma is evaluated. Still, you wouldn't write this kind of code as it's super confusing.

Now, I must admit that I have *not* dived into the TypeScript language spec to figure this out, just what I can gather from the docs and how TypeScript is generally written.

**Comment by azz** [comment]
More context on the matter from @RyanCavanaugh:
https://stackoverflow.com/a/27994757/1280997

**Comment by mafredri** [comment]
Thanks for the link @azz, that opens up the playing field a bit.

I decided to take a look at the [TypeScript compiler source](https://github.com/Microsoft/TypeScript/tree/master/src/compiler) and they do indeed seem to be using `,` for these *inline interfaces*, or whatever you want to call them.

I guess this changes my stance a bit. I think interface definitions should remain as-is, but I have no strong opinion on the *inline* ones.

**Comment by jonaskello** [comment]
I just tried prettier on my code typescript code base (thanks for the typescript support 👍). Seems to work nicely except it uses semicolon on the interfaces. My code base uses a [tslint rule](https://github.com/jonaskello/tslint-divid#no-semicolon-interface) to consistently use commas everywhere including in interface declarations. It seems prettier is not configurable in this area. So I'm quite sad by this because it means prettier is incompatible with my linting rule and I cannot use prettier. Personally I think that using semicolons anywhere, like in interface declarations, or type declarations just introduces inconsistencies in the syntax compared to regular ES6 syntax, but that's just my opinion.

**Comment by azz** [comment]
@jonaskello There's no rationale in the document you provided. Can you turn the rule off if you moved to prettier?

**Comment by calebmer** [comment]
@mafredri

> I think it might be helpful to think of whatever is on the other side of `:` as an inline interface

The specification disagrees.

- [Type aliases](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#310-type-aliases) accept a *Type* after `=`.
- [Type annotations](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a1-types) are defined as `:` *Type*. (Scroll down to “*TypeAnnotation*:”)
- [Interface declarations](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#a5-interfaces) are, however, restricted to *ObjectType*. Not all *ObjectType*s are interfaces because interfaces add a bunch of extra features not available to object types such as interface extension and declaration merging.

Examples where *ObjectType*s are used right of a `:` but are clearly not interfaces:

```ts
const x: { a: number } & { b: number, c: number };
const x: ({ a: number } & { b: number, c: number });
const x: { a: number, b: number, c: number } | string;
```

If you look at the AST on [AST explorer](https://astexplorer.net/#/gist/a0a9e288a10b1ee513ce73be12fd2d83/4bb5b65eda121cde4b9c498a4560658024b755da) you may also clearly see that inline object types are defined completely differently from interfaces.

Interestingly enough unlike in Flow the types generated for classes in TypeScript are structural and not nominal, so saying class types are interfaces would be correct. However, saying an inline object type is an interface isn’t. All interfaces are object types, but not all object types are interfaces.

I apologize if any of this sounds combative, I saw your comment and had an immediate negative reaction 😊

I’m not going to follow up on this semantic difference.

* * *

RE: @RyanCavanaugh’s StackOverflow post it’s common practice to write inline object types on a single line (`{ a: number, b: number, c: number }`) just as it is practice to write objects on a single line (`{ a: 1, b: 2, c: 3 }`). Preserving symmetry between the value and the type is therefore the most aesthetically pleasing option: `{ a: 1, b: 2, c: 3 }: { a: number, b: number, c: number }`. Or in the more common declaration and destructure case: `{ a, b, c }: { a: number, b: number, c: number }`.

**Comment by jonaskello** [comment]
@azz Yes, there is no rationale in the doc for the rule. The rationale would be what I wrote above. Basically I think it looks better with comma since it is closer to regular JS syntax, for example compared to to regular object literals. You could argue both sides and say that it is better to have semicolon because it distinguishes it from object literals. 

Yes I could turn off the rule, and yes prettier would be able to reformat the code bases for all our teams. However there will still be debate in the teams about how this should be done. To me this debate seems very much like the never-ending tab vs. spaces debate. You could argue forever and still not find the "correct" way to do it. I see that prettier has an option for tabs vs spaces. Perhaps an option for semicolon vs comma could be added too (for the same reasons the tab vs spaces option was added). Perhaps if you are pro-semicolon you want to use semicolon where-ever possible, and if you are pro-comma you want to use that where-ever possible. In that case the option could be a simple boolean to either format as comma or semicolon in all cases where typescript allows you to choose.

**Comment by mafredri** [comment]
@calebmer thanks for correcting me and providing detailed into about the spec. My intent was not to insinuate that they are the same thing, just to give notice to the similarity. E.g. every `: { ... }` could be replaced by a named interface (thus similar). But as per my previous comments, my stance has since shifted.

After some more thought, I do agree that writing *anonymous object types* with commas feels most natural, especially when they fit on one line. I think I was thrown off a bit by the initial multi-line example(s) in @calebmer's original suggestion.

So as per authors original suggestion, maybe a mix of `;` and `,` could be the way to go. The `interface` declarations, similar to `class`, would use `;`, whereas other (unnamed) object types would use `,`.

---

@jonaskello 

> Perhaps an option for semicolon vs comma could be added too (for the same reasons the tab vs spaces option was added).

I think this would be a mistake. Ultimately, I think it's important to keep in mind that the purpose of prettier is to remove discussions about syntax and formatting from the equation, in this sense it's important to make the hard decisions and avoid introducing new options. Even if a person initially doesn't like the way prettier formats, the benefits of prettier should outweigh the cons, and eventually this person would grow to accept, perhaps even like, the new formatting.

We must be ready to let go of feelings and try to come up with a solution that makes most sense, e.g. by observing how this is being used in the wild. Beauty is in the eye of the beholder, in this sense, we cannot please everyone.

I, for one, have never come across interfaces written with `,`, on the other hand, the TypeScript sources seems to use a mix between `,` and `;` for anonymous object types. Angular seems to use `,` exclusively for anonymous object types. Are there other projects we could look to for guidance?

**Comment by jonaskello** [comment]
@mafredri I agree that not having options is the best way. And semicolon vs comma may be different from tabs vs spaces since the whitespace is not part of language syntax. My concern is just that finding the "correct" way to do it through discussion or looking at existing code bases will be a never-ending story.

So, if there is not going to be an option I guess there will be arguments here about how it should be done, so lets start that then  :-). So my question would be why would you want to have semicolon in some places and commas in others when you actually can be 100% consistent and use commas everywhere?

**Comment by mafredri** [comment]
@jonaskello we shouldn't be so fast to dismiss it, picking a few well known and established projects should be enough to make an educated choice.

Since you are arguing for `,` everywhere, I think it would be helpful if you presented some more evidence and reasoning behind this. As @calebmer already explained, interfaces are more powerful than object object types and in that sense, arguing for consistency seems a bit moot. I've presented some previous work that uses `;` over `,` (Angular, TypeScript). Where, in the wild, do we see interfaces written with `,`?

**Comment by jonaskello** [comment]
As I have mentioned a couple of times above my reasoning is (1) consistency within typescript, and (2) similarity with regular JS syntax. Sure `interface` can do more than `type`, and `type` can do some things `interface` cannot. But why would that mean they have to have inconsistent syntax, I don't quite follow that reasoning, could you elaborate?

I have no good examples of this in the wild but one idea would be to look at how it is done in flowtype. I think having consistency between typescript and flow would be interesting even if there is not a 1:1 relationship. In the docs page for flow, I see that `type` uses comma for all examples, but `interface` has a mix. For example [here](https://flow.org/en/docs/types/interfaces/#toc-interface-properties) it uses semicolon and [here](https://flow.org/en/docs/types/interfaces/#toc-interface-generics) it uses comma.

**Comment by jonaskello** [comment]
@mafredri If you are looking for arguments to support semicolon in `interface` I think the one you have about existing code-bases is valid. The only other one I can think of is that if you use `class` (I don't) then your `interace` would look closer to your `class` if it uses semicolon.

**Comment by azz** [comment]
Considering:

* The results from https://github.com/prettier/prettier/issues/1944#issuecomment-306039315 (+ the natural bias of results, epeople who want change generally seek it out)
* There have been no other issue or further comments here
* Prettier is allowed to be opinionated.
* It's a minor stylistic thing that doesn't really affect readability.

Let's call this one closed for now.

**Comment by SimpleCookie** [comment]
Actually, with TypeScript in React, the interface:
```
interface SomeRandomInterface {
  a: string;
  b: string,
}
```
does not compile. It is not valid. Removing the semicolon does not work either, the colon is essential for a valid compilation.

**Comment by j-f1** [comment]
@SimpleCookie Testing both the code you posted and a version without semicolons in [the TypeScript playground](http://www.typescriptlang.org/play/index.html#src=interface%20SomeRandomInterface%20%7B%0D%0A%20%20a%3A%20string%3B%0D%0A%20%20b%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20SomeOtherRandomInterface%20%7B%0D%0A%20%20a%3A%20string%0D%0A%20%20b%3A%20string%0D%0A%7D%0D%0A) leads to a successful compilation. Can you share a example that reproduces in the TypeScript playground?

**Comment by SimpleCookie** [comment]
@j-f1 Thank you for taking your time testing my issue.

Though, I'm not sure if it was a bug or not, but I managed to get it to work somehow after working more with it? I believe it may be because I defined the `"parser": "typescript"` in my `.prettierrc` file incase someone else has the same problem.
Forgive me if it's my lack of knowledge in the subject.
