### ISSUE TITLE
Flow comments will be turned into flow annotations

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#204]
The flow parser will parse the following two as the same AST ( https://flowtype.org/blog/2015/02/20/Flow-Comments.html ):

```js
function f(a/*: string*/) {}
function f(a: string/) {}
```

So, the first one will be turned into the second one with prettier and the flow parser. But will remain the first one with babylon.

I'm not sure which one is the wanted behavior but this is something to be aware of.

cc @samwgoldman

**Comment by jlongster** [comment]
I suppose if you want to use the comments you just have to use the babylon parser. I can't imagine the flow parser wanting an option to ignore the comments, since that parser's purpose is to extract out the type info.

**Comment by jokeyrhyme** [comment]
I currently prefer Flow comments syntax, because it allows me to enrich my workflow with static types without requiring a special parser or build process. I'm writing pure JavaScript the whole time, without any need to transpile, etc.

I can use prettier with the default babylon parser for the most part, which preserves my comments.

It would be ideal if I could have the Flow parser and eat my comment syntax cake, too, but I'm willing to accept that I might have diverged from the recommended path at this point.

**Comment by jokeyrhyme** [comment]
Related to #719 ?

**Comment by vjeux** [comment]
I want to support the comment syntax for flow. However, it's technically hard to do because comments are not part of the ast and placing them to the right position all the time is challenging.

I think that we can get it working with some amount of effort but it is not the priority right now.

**Comment by jokeyrhyme** [comment]
The annotations _do_ show up in the correct position using prettier in Flow mode.

What if there was a prettier option that toggled Flow comments syntax?

**Comment by vjeux** [comment]
#719 is trackig it
