### ISSUE TITLE
Saving source-map information through prettier

### ISSUE THREAD

**Issue by antonmedv** [prettier/prettier#2073]
Hi,

It will be cool if it will be possible to save source-map information while formatting code. 
For example i'm writing compiler which emits code with source-maps (via https://github.com/mozilla/source-map) and i want to format code using prettier, but also to same source-map to original source.

Is it possible to implement?

**Comment by vjeux** [comment]
This is something that should be possible but is not very high pri. If someone wants to implement it, that would be very welcome.

**Comment by josephfrazier** [comment]
Since Prettier doesn't change the AST, you could probably generate your sourcemap by parsing both the input code and the output code into their ASTs with location information, then traversing the trees together and building the source map from the location differences. Comments might be tricky, though, since Prettier moves those around (see [`massageAST`](https://github.com/prettier/prettier/blob/16db5971f02cb8506bf012a76dba9dedf7145021/src/clean-ast.js#L7-L164)).

**Comment by antonmedv** [comment]
No, this is a hard buggy way.

**Comment by antonmedv** [comment]
And this is simple impossible, your solution isn't working.

**Comment by j-f1** [comment]
@antonmedv Why did you close this issue?

**Comment by antonmedv** [comment]
Cleaning up :)

Recreate issue if you still going to implement this (but I think it's really difficult to implement and will not be implemented anyway, maybe by another project).

**Comment by j-f1** [comment]
Let’s keep this open to track the feature until it gets implemented. We’re not opposed to the feature, it just isn’t our priority.

**Comment by antonmedv** [comment]
Cool. Please `recreate`.

**Comment by josephfrazier** [comment]
One possibility that @antonmedv is using https://github.com/issues to keep track of outstanding issues they've opened, but they no longer care about this one and want it to be removed from the list.
