### ISSUE TITLE
Unnecessary parenthesis added around arrow function parameter when adjacent to a comment in TypeScript parser

### ISSUE THREAD

**Issue by fortes** [prettier/prettier#2146]
Input

```
o/*comment*/=>1
```

Becomes:

```
(o /*comment*/) => 1;
```

Repro: https://prettier.github.io/prettier/#%7B%22content%22%3A%22o%2F*comment*%2F%3D%3E1%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22all%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
This is actually intentional

**Comment by fortes** [comment]
@vjeux What's the rationale? I notice that there are no parens when the comment is removed.

I hit this issue due to it failing this TSLint rule: https://palantir.github.io/tslint/rules/arrow-parens/

**Comment by vjeux** [comment]
Sorry, I had to go so I just pressed comment.

Parenthesis are not part of the ast so we need to recreate them in a consistent way. All the examples I've seen of single arguments with comments have had parenthesis, so we're putting them in prettier.

I would recommend turning off that tslint rule since prettier reformats everything.

**Comment by fortes** [comment]
Not a showstopper for me, was just curious for rationale.
