### ISSUE TITLE
Vbscript support

### ISSUE THREAD

**Issue by koenvb** [prettier/prettier#2155]
I have to write quite some code in vbscript  lately and kinda miss the idea of prettier which could easily format my code on save in sublime. 

Which steps should I take to use something like prettier on vbscript code?
I am sure the demand for this is super low but was wondering, as an exercise for myself if that would be possible to add vbscript support to prettier?  Would that be even an option or not?

Similar things have been created but they are not based on validating/checking the code, they are mostly done based on keywords etc. 

eg, https://github.com/daansystems/vbsbeautifier 

Just wondering if it was an option and if I could try to do it myself :-) 

Thanks for the great software!

**Comment by azz** [comment]
While prettier has added support for a few new languages recently, they have all been web-focused, so it feels out of scope for prettier to support languages like VBScript.

In order to pretty-print a file the way prettier does, it needs to parse the code into an "abstract syntax tree" (prettier uses [babylon](https://github.com/babel/babylon) by default). I did a quick search, but I couldn't find such as parser for VBScript, probably because it is a proprietary language.

Going to close this issue as it's not something we'll be taking on right now, but you can definitely fork prettier if you find a parser, and have a go at trying to print it.
