### ISSUE TITLE
Why Prettier has Tab Width option, shouldn't it be dependent on the editor and specified there?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2162]

**Comment by mafredri** [comment]
Prettier cannot assume tab width from the editor because users could have different settings for it and this would result in different output depending on who is saving the file.

If you were to use `prettier --write --tab-width 2 --use-tabs` the result would be different from `prettier --write --tab-width 8 --use-tabs`, for example.

Say the user is has configured tabs to be `2` characters wide and prettier runs with tab as `8`. Given one level of indentaiton, prettier will actually, in practice, use column `74` instead of `80` for the line-limit when seen from the users perspective. This behavior is correct and the only way to guarantee that prettier always produces the same result.

**Comment by azz** [comment]
@mafredri is correct. In addition, tab width is used when `--use-tabs` is _not_ provided to determine how many spaces to use for indentation.
