### ISSUE TITLE
Keep original multiline named import / export formatting

### ISSUE THREAD

**Issue by panjiesw** [prettier/prettier#2166]
Somewhat related to #572, and [there](https://github.com/prettier/prettier/issues/572#issuecomment-282740340) mentioned that 

> If we have expanded an object, prettier will keep that object expanded now.

Right now, multiline named import / export is formatted into single line if there is still enough line width. Since they are similar to expanded objects, is it possible to treat them just like how prettier treat object?

**Comment by azz** [comment]
Objects only respect the input due to the complexity of coming up with a heuristic to break them or not. There are too many edge cases. However with named import/exports it is simple: if it fits in one line, print it on one line.

Consider this use case:

```js
import {
  someFunctionName,
  someOtherReallyLongFunctioName
} from "./my/functions";
```

You do some refactoring and remove the references to `someOtherReallyLongFunctioName`, delete it, and you would be left with:

```js
import {
  someFunctionName
} from "./my/functions";
```

Prettier will currently automatically print this as:

```js
import { someFunctionName } from "./my/functions";
```

Saving you from going back and deleting the two newline characters.

**Comment by panjiesw** [comment]
This is related to the issue I referenced in description, which is about consistency and code review.

Using your use case above:

```javascript
import {
  someFunctionName,
  someOtherReallyLongFunctioName, // also using --trailing-comma all
} from "./my/functions";
```

After refactoring and removal of `someOtherReallyLongFunctioName`, I'd be left with:

```javascript
import {
  someFunctionName,
} from "./my/functions";
```

If prettier preserve the formatting, the diff in those change will be minimal and ideal for code review. So we'll get this:

```diff
import {
  someFunctionName,
- someOtherReallyLongFunctioName,
} from "./my/functions";
```

instead of this:

```diff
-import {
-  someFunctionName,
-  someOtherReallyLongFunctioName,
-} from "./my/functions";
+import { someFunctionName } from "./my/functions";
```

The same case also applies to addition of import / export

**Comment by vjeux** [comment]
I understand the desire to want to minimize diffs but prettier has not been designed with that use case in mind: it doesn't have state. For a given ast it's going to output the same output, it doesn't look at the minimum set of changes it could do to keep the diff minimal (which it could but that would be a big departure from the existing architecture).

For objects, the reason why we keep it expanded or not is because objects can be used in many contexts in JavaScript: data, classes, hash table, ... and it's not easy to tell when it is used in which and where do we want to always expand vs use the max line to determine the expansion. So we rely on the heuristic, if there's an empty line, we maintain it.

The solution here would be to change import from using max len to always expand but I don't think that it is a good idea.

So unfortunately, we're not going to change anything here. Thanks for opening this issue though, it was very detailed!

**Comment by panjiesw** [comment]
Hi @vjeux thanks for your detailed reasoning of prettier design. Although it's unfortunate but I understand the decision.

I'm interested about the change of import from using max len to always expand, do you mind any code guidance (of prettier) to make the change? I still think i'd try to implement that in a fork to be used by my team.

**Comment by azz** [comment]
@panjiesw basically you want to always use `hardline` instead of `line` or softline here:
https://github.com/prettier/prettier/blob/master/src/printer.js#L684-L689

Start with something like this:

```patch
      group(
              concat([
                "{",
                indent(
                  concat([
-                   options.bracketSpacing ? line : softline,
+                   hardline,
-                   join(concat([",", line]), grouped)
+                   join(concat([",", hardline]), grouped)
                  ])
                ),
                ifBreak(shouldPrintComma(options) ? "," : ""),
-                options.bracketSpacing ? line : softline,
+                hardline,
                "}"
              ])
            )
```
