### ISSUE TITLE
Inconsistent function formatting when getting object property and method in function argument

### ISSUE THREAD

**Issue by marcelmokos** [prettier/prettier#2182]
We are using reselect in our project and when I run prettier on the project most annoying thing  is formatting of the selectors.

How we format selectors.
```js
export const selectVisibleAt = createSelector(
  selectChatDomain,
  (substate) => substate.get('visibleAt'),
);

export const selectHiddenAt = createSelector(
  selectChatDomain,
  (substate) => substate.hiddenAt,
);
```

Outcome for example with object property stays the same but when method is used selector arguments are put on same line.
```js
export const selectVisibleAt = createSelector(selectChatDomain, substate =>
  substate.get("visibleAt")
);
```

[Link to the example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20selectChatDomain%20%3D%20(state)%20%3D%3E%20state.get('chat')%3B%5Cn%5Cnexport%20const%20selectVisibleAt%20%3D%20createSelector(%5Cn%20%20selectChatDomain%2C%5Cn%20%20(substate)%20%3D%3E%20substate.get('visibleAt')%2C%5Cn)%3B%5Cn%5Cnexport%20const%20selectHiddenAt%20%3D%20createSelector(%5Cn%20%20selectChatDomain%2C%5Cn%20%20(substate)%20%3D%3E%20substate.hiddenAt%2C%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)

**Comment by azz** [comment]
Prettier formats it like that at [print width `74`](https://prettier.github.io/prettier/#%7B%22content%22%3A%22export%20const%20selectChatDomain%20%3D%20(state)%20%3D%3E%20state.get('chat')%3B%5Cn%5Cnexport%20const%20selectVisibleAt%20%3D%20createSelector(%5Cn%20%20selectChatDomain%2C%5Cn%20%20(substate)%20%3D%3E%20substate.get('visibleAt')%2C%5Cn)%3B%5Cn%5Cnexport%20const%20selectHiddenAt%20%3D%20createSelector(%5Cn%20%20selectChatDomain%2C%5Cn%20%20(substate)%20%3D%3E%20substate.hiddenAt%2C%5Cn)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A74%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D).

I'm not sure this is something we can change, because last-arg-is-a-function pattern is often a callback.

```js
it("does something", done => 
  done()
);

get("github.com", (err, result) =>
  err ? error(err) : success(result)
);
```

**Comment by vjeux** [comment]
Yeah, I agree this is not optimal but unfortunately I don't see a way where we could distinguish your use case against the more common expand last argument :( I'm going to close this issue, thanks for reporting it!
