### ISSUE TITLE
EOL comments break indentation

### ISSUE THREAD

**Issue by nwaywood** [prettier/prettier#2210]
With no EOL comment, prettier formats the following code like this:

```js
type Props = {
    history: Object,
    muiTheme: Object
}
```

But with an EOL comment, the formatting becomes:

```hs
type Props = {
  history: Object, // eslint-disable-line
    muiTheme: Object
}
```

The indentation of the `history` line changes to 2, but the indentation of the `muiTheme` line stays 4.

Note: I have configured prettier to have `tabWidth: 4`

**Comment by vjeux** [comment]
I can't reproduce on the playground. Is this because you are using prettier with eslint and you disable this line so the autofix doesn't get applied?

https://prettier.github.io/prettier/#%7B%22content%22%3A%22type%20Props%20%3D%20%7B%5Cn%20%20history%3A%20Object%2C%20%2F%2F%20eslint-disable-line%5Cn%20%20%20%20muiTheme%3A%20Object%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A4%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Going to close this since there's no response. Feel free to keep the discussion going :)

**Comment by nwaywood** [comment]
@vjeux Yes you are right. When I change it to specify the specific rule I want to ignore, it formats correctly:

```
type Props = {
    history: Object, // eslint-disable-line react/no-unused-prop-types
    muiTheme: Object
}
```

Thanks :)
