### ISSUE TITLE
Fix json files

### ISSUE THREAD

**Issue by zimme** [prettier/prettier#2290]
Awesome work with the json support, we've added it to prettier-eslint too now.

It would be nice if we could get automatic fixing of json files too.
Auto fix of quotes and removing of trailing commas comes to mind.

**Comment by vjeux** [comment]
As mentioned in the PR, I don't think that it's really prettier's job to do that. A lot of people are using normal js instead of strict json in their json files and we don't want to drop those extra pieces of information. I'd rather make it such that prettier throws when it's not valid than changing the code. Thanks for the suggestion though :)

**Comment by zimme** [comment]
I as a user of prettier actually expect some fixes to be done, like quotes and trailing commas. I get that stripping away comments and some other stuff like `Infinity` and some ranges, if I understood the PR correctly, isn't the best way to go.

However could we get some smaller fixes like quotes and trailing commas.
