### ISSUE TITLE
JSX text content moving to separate line

### ISSUE THREAD

**Issue by adamroyle** [prettier/prettier#2324]
In 1.5.0 (& 1.5.2) the following JSX

```jsx
<h3>{stage.title}</h3>
```
will be formatted as

```jsx
<h3>
  {stage.title}
</h3>
```
regardless of line length.

Is this regression from 1.4 intentional?

**Comment by karl** [comment]
@adamroyle This was an intentional change. 

There was some discussion about it in https://github.com/prettier/prettier/pull/1831#discussion_r119908824, https://github.com/prettier/prettier/pull/1831#issuecomment-310006792, and https://github.com/prettier/prettier/issues/2232

I'm very happy to hear if there are differing opinions on how to handle this!

**Comment by vjeux** [comment]
I'm going to close this as it is an intentional change. But feel free to get the discussion going :)

**Comment by adamroyle** [comment]
Thanks for the feedback. Although I don't understand the entire breadth of your challenges, here are some common forms I would consider acceptable being unchanged.

```jsx
<div>
  <button>{submitText}</button>
  <button>{cancelText}</button>
</div>

<p><a href={url}>{label}</a></p>

<div>
  {label && <label>{label}</label>}
</div>
```

These are currently formatted as:

```jsx
<div>
  <button>
    {submitText}
  </button>
  <button>
    {cancelText}
  </button>
</div>

<p>
  <a href={url}>
    {label}
  </a>
</p>

<div>
  {label &&
    <label>
      {label}
    </label>}
</div>
```

Which I feel is unnecessarily verbose.

I've run 1.5.2 over a few of my projects using and there were quite a few changes like the above.

If you could get it to work that would be great :)

BTW, I ran into the issue of weirdness of breaking on expressions far less (only 2 times in my projects AFAIK).

**Comment by karl** [comment]
Thanks for the examples @adamroyle!

I agree with you that the examples you've given above look better inline. That would be my preference for formatting as well. When working on JSX formatting there did seem to be a slight preference for not inlining single expression (https://github.com/prettier/prettier/pull/1831#discussion_r119908824) so I went with that.

Happy to change it if it turns out we made the wrong call! It would be a simple and quick change to make.

I'd like to leave this issue for a week or so see if there is any further discussion before making any changes.

**Comment by sgwilym** [comment]
Have to agree that this seems like a weird change, where many things that were very easy to scan and comprehend have blown up completely. Here's a good example diff:

<img width="393" alt="screen shot 2017-06-29 at 12 59 03" src="https://user-images.githubusercontent.com/579491/27684641-1e2f4336-5ccb-11e7-9884-aa14e0628290.png">

I thought that one of the main strengths of Prettier was breaking things apart depending on context?

**Comment by VladShcherbin** [comment]
It would be great to resolve this so that text could be inline as now prettier makes it look really bad.

**Comment by kristerkari** [comment]
I agree with the others about 1.5 changing the formatting to be too verbose, especially with bigger files.

**Comment by sgwilym** [comment]
@karl Now that some time has passed, what do you think? What's the best way for us to resolve this difference of opinion?

**Comment by karl** [comment]
I would be happy to change Prettier to use the more compact formatting.

I should have some time to look at it next week.

**Comment by karl** [comment]
Re-opened as I'm working on a fix for this.

**Comment by karl** [comment]
@rattrayalex @SimenB I have a PR that would alter the way we format JSX elements that contain a single expression, where it would inline these rather than making them multiline.

I know you both had some interest in how we formatted these, it would be great to get your opinions on this!

**Comment by rattrayalex** [comment]
Closing as your PR has been merged, thanks @karl !
