### ISSUE TITLE
Python plugin?

### ISSUE THREAD

**Issue by cosmith** [prettier/prettier#2326]
Not sure if this is completely stupid or not but would it be feasible / easy to add support for other languages? I know [yapf](https://github.com/google/yapf) is a thing but I'm mostly curious :)

I haven't looked at the source enough to really understand what's going on, would it practical to use a parser such as https://github.com/differentmatt/filbert and plug it in prettier?

**Comment by lydell** [comment]
So far, adding support for other languages than JavaScript seems to have been pretty smooth, and I don’t think Python would be any different. It wouldn’t be a _plugin,_ but simply yet one language that is supported. You are correct that the first step is to find a parser. filbert might be a good choice, or it might not – I can’t say because I’m not familiar with Python parsing (in JS).

**Comment by vjeux** [comment]
Supporting a fully fledged programming language is not a trivial task (compared to CSS, GraphQL, JSON...), it's likely going to take a few months to get everything right. So, if an existing project already exists, is well supported and works well, it's better to use it instead of reinventing the wheel.

As for the parser, I wouldn't go the route of finding a js implementation but try to get the official parser to compile to js. A pretty printer has an extremely high requirement for a parser: every single edge case needs to be handled correctly otherwise it's not going to print valid code. During the few months working on prettier, we found dozens of issues with all the parsers we are supporting, and they were already extremely well tested and used.

**Comment by vjeux** [comment]
I'm going to close this as we're not going to do it anytime soon, but I would encourage people to hack on it if you are interested :)

**Comment by j-f1** [comment]
Check out [prettier/prettier-python](https://github.com/prettier/prettier-python) — @azz added a plugin API to the Prettier core, and @patrick91 is working on the printer in `prettier/prettier-python`.
