### ISSUE TITLE
Inconsistent formatting

### ISSUE THREAD

**Issue by geuis** [prettier/prettier#2339]
We have this code:

```js
const startMon = months[
  new Date(period.first_acquired).getUTCMonth()
].slice(0, 3);

const endMon = months[
  new Date(period.last_acquired).getUTCMonth()
].slice(0, 3);
```

Which gets formatted to this:

```js
const startMon = months[
  new Date(period.first_acquired).getUTCMonth()
].slice(0, 3);

const endMon = months[new Date(period.last_acquired).getUTCMonth()].slice(
  0,
  3
);
```

Wat?

**Comment by josephfrazier** [comment]
https://prettier.io/#%7B%22content%22%3A%22const%20startMon%20%3D%20months%5B%5Cn%20%20new%20Date(period.first_acquired).getUTCMonth()%5Cn%5D.slice(0%2C%203)%3B%5Cn%5Cnconst%20endMon%20%3D%20months%5B%5Cn%20%20new%20Date(period.last_acquired).getUTCMonth()%5Cn%5D.slice(0%2C%203)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A74%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

It looks like you're using a `printWidth` of around 74. Since Prettier tries to squeeze as much as it can into a line, and the two lines are slightly different, that's why they're formatting differently. You could tweak your `printWidth`, or use `// prettier-ignore` comments to override formatting you dislike:

https://prettier.io/#%7B%22content%22%3A%22const%20startMon%20%3D%20months%5B%5Cn%20%20new%20Date(period.first_acquired).getUTCMonth()%5Cn%5D.slice(0%2C%203)%3B%5Cn%5Cn%2F%2F%20prettier-ignore%5Cnconst%20endMon%20%3D%20months%5B%5Cn%20%20new%20Date(period.last_acquired).getUTCMonth()%5Cn%5D.slice(0%2C%203)%3B%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A74%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Yeah, this is unfortunate, but right now we don't really know how to print it better :( We'll leave it like this until we find a solution.
