### ISSUE TITLE
How to use prettier with pre-commit module 

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2358]
With this https://github.com/observing/pre-commit?

**Comment by k15a** [comment]
Install lint-staged, prettier and pre-commit and then add the following to you package.json.

```json
"scripts": {
  "lint-staged": "lint-staged"
},
"lint-staged": {
  "*.js": [
    "prettier --write",
    "git add"
  ]
},
"pre-commit": [
  "lint-staged"
]
```

**Comment by jitendravyas** [comment]
lint-staged is a similar tool but not exactly pre-commit. I want to use pre-commit (for stylelint and Prettier both) instead lint-staged.

**Comment by k15a** [comment]
lint-staged serves another purpose then pre-commit. With lint-staged you only format changed files with prettier and don't touch unchanged files which makes it a lot faster. That's why you have to install both lint-staged and pre-commit.

If you want to format all files you can uninstall lint-staged and use pre-commit directly.

```json
"scripts": {
    "git-add": "git add",
    "prettier": "prettier --write \"**/*.js\""
},
"pre-commit": [
    "prettier",
    "git-add"
]
```

This shouldn't be to hard to configure if you read the Readme.

**Comment by jitendravyas** [comment]
Sorry for the confusion, it was my mistake. I'm actually trying to replace Husky with pre-commit not lint-staged. 

Because of this https://github.com/okonet/lint-staged/issues/200#issuecomment-309736989

> You can try pre-commit instead of husky since I believe it's a bit faster.

**Comment by k15a** [comment]
Now add:

```json
"pre-commit": [
  "precommit"
]
```

and it should work!
