### ISSUE TITLE
Is it ok to run prettier on all JS files of existing codebase blindly?

### ISSUE THREAD

**Issue by jitendravyas** [prettier/prettier#2370]
Will I need to test whether everything works as same as it was working before Prettier formation?

**Comment by azz** [comment]
This information is in the main README.

> If you're worried that Prettier will change the correctness of your code, add `--debug-check` to the command. This will cause Prettier to print an error message if it detects that code correctness might have changed. Note that `--write` cannot be used with `--debug-check`.

**Comment by lydell** [comment]
Prettier is now very stable and has lots of tests. Several big projects have adopted Prettier without their code breaking. Personally, I’ve never had a bug because of Prettier.

What can happen though, is that a comment is moved to a location that you don’t like. Or that ESLint doesn’t like (generally, `// eslint-disable-next-line` works better than `// eslint-disable-line`). So it is worth looking through for edge case formatting things.

As mentioned in the README, you can use the `--debug-check` flag as well:

> If you're worried that Prettier will change the correctness of your code, add `--debug-check` to the command. This will cause Prettier to print an error message if it detects that code correctness might have changed.

Finally, I guess some common sense is needed. You can rarely rely blindly on anything in real life can you?

(You seem to have a lot of questions. Perhaps it’s easier to stop by at https://gitter.im/jlongster/prettier ?)
