### ISSUE TITLE
I definitely cmopletely broke this somehow.?

### ISSUE THREAD

**Issue by bradennapier** [prettier/prettier#2371]
I have no idea how this happened - it has been working flawlessly , including on tihs file, now i randomly get atom-prettier failures on every save when this code is present:

```js
if (module && module.hot && module.hot.accept) {
  module.hot.accept();
  module.hot.accept('./routes', () =>
    import('./routes').then(newRoutes => RenderApp(Root, newRoutes.default)),
  );
  module.hot.accept('./root/Root', () =>
    Promise.all([import('./routes'), import('./root/Root')]).then(([newRoutes, newRoot]) =>
      RenderApp(newRoot.default, newRoutes.default),
    ),
  );
  module.hot.accept('./service-worker');
}
```

![image](https://user-images.githubusercontent.com/15365418/27760229-28eebd1a-5df7-11e7-951f-57264d58c241.png)

**Comment by bradennapier** [comment]
Yeah suddenly every file that uses dynamic import is failing -- it also is randomly formatting things completely differently... ugh

**Comment by bradennapier** [comment]
It also can not parse json at all... it fails completely on package.json

![image](https://user-images.githubusercontent.com/15365418/27760269-32afc456-5df8-11e7-9c69-7bfd74863567.png)

**Comment by bradennapier** [comment]
So it wants the json to use `;` instead of `:` --- if i change my json to

```
{
     "one"; "two",
     "three"; "four" 
}
```

it works fine - ... this is compeltely broken lolz wtf !?  I tried removing and re-installing to no avail

**Comment by azz** [comment]
> `Error: unknown type: "Import"`

Looks like you're using an old version of prettier. Can you upgrade to ~1.5.0 and check again?

**Comment by azz** [comment]
The JSON issue is explained in https://github.com/prettier/prettier-atom/issues/212#issuecomment-312214883

Since the JS code this works fine on `babylon`, `flow`, and `typescript` parsers on https://prettier.io, I'm closing this.

https://prettier.io/#%7B%22content%22%3A%22if%20(module%20%26%26%20module.hot%20%26%26%20module.hot.accept)%20%7B%5Cn%20%20module.hot.accept()%3B%5Cn%20%20module.hot.accept('.%2Froutes'%2C%20()%20%3D%3E%5Cn%20%20%20%20import('.%2Froutes').then(newRoutes%20%3D%3E%20RenderApp(Root%2C%20newRoutes.default))%2C%5Cn%20%20)%3B%5Cn%20%20module.hot.accept('.%2Froot%2FRoot'%2C%20()%20%3D%3E%5Cn%20%20%20%20Promise.all(%5Bimport('.%2Froutes')%2C%20import('.%2Froot%2FRoot')%5D).then((%5BnewRoutes%2C%20newRoot%5D)%20%3D%3E%5Cn%20%20%20%20%20%20RenderApp(newRoot.default%2C%20newRoutes.default)%2C%5Cn%20%20%20%20)%2C%5Cn%20%20)%3B%5Cn%20%20module.hot.accept('.%2Fservice-worker')%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22typescript%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%2C%22ast%22%3Afalse%7D%7D
