### ISSUE TITLE
Is there format specification? 

### ISSUE THREAD

**Issue by pqr** [prettier/prettier#2380]
Question: Is there any specification or formal description (set of rules) of result formatting?

I look at changelog https://github.com/prettier/prettier/releases/tag/1.4.0 and see a lot of changes in output (before/after), so Prettier have being constantly improving and output changed from version to version - it's fine. But is there any up-to-date formal description in English of current formatting rules similar to Airbnb (https://github.com/airbnb/javascript) code style or Standard (https://standardjs.com/rules.html)?

Why asking: I want the same formatting to be implemented by another tool: https://youtrack.jetbrains.com/issue/WEB-25077#comment=27-2288947

**Comment by vjeux** [comment]
There's https://github.com/prettier/prettier/blob/master/Rationale.md but it's very barebone. I want to have a more complete done.

**Comment by azz** [comment]
>  adjust WebStorm code style options to be compatible with Prettier default formatting style.

I don't think that's a reasonable goal. Especially if you're using `eslint-plugin-prettier`, which will error if a single character doesn't match the prettier output.

And as good as a set of rules written in English can be, they will be, by definition, inadequate to describe the full "rule-set" of prettier itself. 

I think the better course of action would be to do what other editors have done and have a plugin that uses prettier to format your code.

**Comment by prigara** [comment]
WebStorm has code style options that are applied when generating the code, autocompleting it or on typing. I understand that you can reformat all this new code later with Prettier (in the IDE or outside of it), but it seems that it would be better if the IDE produces the code that is valid or almost valid in the first place. Unlike an editor, WebStorm has a rather wide set of code style options, including many options for wrapping the code.
This is the approach WebStorm is following with the tools like ESLint and Standard: the IDE matches the rules defined by the linters to its own code style settings, all the other errors are fixed by the tool itself (if fixable) or manually.

**Comment by azz** [comment]
ESLint and Standard are linters, prettier is a full printer, there's a huge difference there. I don't think it is practical to maintain a styleguide alongside prettier, and kind of contradicts its own purpose: to let developers not worry about these kinds of things.

The best thing you could do is to generate code and pipe it through prettier on-the-fly.
