### ISSUE TITLE
Poor readability of destructuring wth default values

### ISSUE THREAD

**Issue by abrkn** [prettier/prettier#2418]
Prettier prefers this formatting, which in my opinion has poor readability because of the default value of `FETCH_INTERVAL`:

```
const { FETCH_INTERVAL = 30 * 1e3, GRAPHQL_URL, REDIS_URL } = process.env;
```

**Comment by lydell** [comment]
How would you write it?

**Comment by Andarist** [comment]
Just a side note - you should not destructure `process.env`. If you use webpack it will include by default a `process` polyfill because of it. If you use a simple form of `process.env.REDIS_URL` it will just replace this with its configured value (basically just a string replacement).

You can mitigate the issue with tweaks to your webpack config, webpack3 even brings `node: false` setting to simplify this.

**Comment by abrkn** [comment]
@lydell: I think it becomes difficult to read with default values and would split with per line:

```
const {
  FETCH_INTERVAL = 30 * 1e3,
  GRAPHQL_URL,
  REDIS_URL,
} = process.env;
```

**Comment by abrkn** [comment]
@Andarist: This is from a worker that runs on a server and does not use webpack.

**Comment by lydell** [comment]
I see. Do you follow this rule for functions too? For example, instead of:

```js
function work(graphqlUrl, redisUrl, fetchInterval = 30 * 1e3) {
  // ...
}
```

… you’d write:

```js
function work(
  graphqlUrl,
  redisUrl,
  fetchInterval = 30 * 1e3,
) {
  // ...
}
```

?

**Comment by abrkn** [comment]
Good question, @lydell. I'd write it the first way.

**Comment by lydell** [comment]
Isn’t that inconsistent? Isn’t the function just as unreadable?

**Comment by abrkn** [comment]
A function has positional arguments while the assignment in my example does not.

**Comment by lydell** [comment]
Sorry, I don’t understand how that makes a difference? :)

**Comment by azz** [comment]
I don't think we'll be changing this behaviour. You can always add `// prettier-ignore` on the line before it to keep it on multiple lines.
