### ISSUE TITLE
opts from tslint.json?

### ISSUE THREAD

**Issue by tomdavidson** [prettier/prettier#2447]
I can have a tslint.json with:
```json
  "rules": {
    "semicolon": [true, "never"]
  }
```
and I can use prettier with `--no-semi`, but can prettier use my tsconfig.json for such options?

**Comment by azz** [comment]
You mean `tslint.json`?

I don't think we'll be supporting this, as we don't do the same for `.eslintrc`.

**Comment by tomdavidson** [comment]
Ha! yes, tslint.json.

Since prettier is configurable, it seems a bit more than just nice to have one source of truth for the config. Tslint and eslint both have fix options (for fixable rules). Configuring in both places is simple enough but perhaps prone to error. 

Rather than Prettier respecting lint config, is running Prettier via the linter such as [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) considered better or does it circumvent Prettier's  write? The README.md suggest using eslint-plugin-prettier but then `prettier --write` in a pre-commit hook.

**Comment by aboyton** [comment]
Rather than having Prettier read the config from TSLint you should not have TSLint check this at all and instead have prettier worry about semicolons. There's no point slowing TSLint down for something Prettier is already doing.

While it doesn't matter quite as much for semicolons for things like quotes Prettier uses this as a guide and will say switch from single quotes to double quotes for a particular string of it means that you don't have to escape a single quote in it.

**Comment by tomdavidson** [comment]
doh! just dont even bother checking on the semicolons - easy way to absolve the conflict with standard js

thanks.
