### ISSUE TITLE
Support other non-js formats in template literals perhaps through plugins

### ISSUE THREAD

**Issue by KyleAMathews** [prettier/prettier#251]
Formats like graphql and everything that's getting put in template literals these days (CSS, markdown, etc.)

These often have sketchy editor support so an automated prettier would be very nice for encouraging the jsification of all things.

**Comment by KyleAMathews** [comment]
This issue was inspired by having to chase back and forth  Vim's autoformatting of an embedded graphql query :-)

**Comment by hzoo** [comment]
This is specifically for a js file that includes a template tag? I think currently there isn't any formatting applied to templates

This would change the way the simple flow works with parser -> printer given you need to check all tags and then add another parser for graphql, etc.

**Comment by KyleAMathews** [comment]
Yeah, a plugin of some sort could take over printing of an template literal AST node (or any other node I guess). To Prettier, nothing would change other than instead of printing the template literal itself, it'd print a string returned to it by the plugin.

**Comment by jlongster** [comment]
I'm against plugins that can arbitrarily override our printer, but allowing special printing of tagged strings is a really neat idea. Basically if we could format tagged strings, that would be pretty incredible for the user since it would reduce the annoyances of having data as big strings blobs (CSS, graphql, etc). It would give them a better connection to the code within the string blobs. I miss auto-indentation of CSS a lot more than syntax highlighting when I'm doing CSS in JS, honestly.

I see what @KyleAMathews is talking about: when we hit a tagged string template, if we have something to call to format that string, we'd just print it back out. The way those are printed are likely a lot simpler than what prettier does, so they wouldn't need access to our constraint-based solver, they could just format it one way without wrapping (think CSS: always emitting newlines and indenting is good enough).

I want to be very careful about hooking into any user code, though. This will likely be lower priority until we get the printer stable across all JS syntax, and that gives us time to think about it and get feedback for people. I don't know how the plugin system would work; right now it's ideal that we don't need to load any user-land code. But it's something to think about.

**Comment by vjeux** [comment]
I've started GraphQL ( https://github.com/prettier/prettier/pull/1642 ) and CSS ( https://github.com/prettier/prettier/pull/1636 ) integrations and prettier is very well positioned to support those. I'm going to close this issue as it's not very actionable, but I think that the goal is to have prettier handle more than just pure JS.
