### ISSUE TITLE
Trailing commas inconsistent on Arrays

### ISSUE THREAD

**Issue by ssylvia** [prettier/prettier#2510]
I'm using prettier with ESLint plugin and have the following rules in my eslint file:

```js
'prettier/prettier': ['error', {
  printWidth: 100,
  singleQuote: true,
  trailingComma: 'es5'
}],
```

Per the [docs](https://github.com/prettier/prettier#trailing-commas), it looks like trailing commas should be added to arrays.

If I create the following array:

```js
const test = [
  'test',
  'hello world',
  'foo bar',
  'Lorem ipsum dolor sit amet, consectetur.',
];
```

prettier throws an error and fixes it to:

```js
const test = ['test', 'hello world', 'foo bar', 'Lorem ipsum dolor sit amet, consectetur.'];
```

This also make it longer than the max line length.

If I add an object to an array, it allows the new lines and trailing commas:

```js
const test = [
  'test',
  {
    test: 'foo',
  },
  'foo bar',
  'Lorem ipsum dolor sit amet, consectetur.',
];
```

Is there a way to force new lines and trailing commas for array values?

**Comment by vjeux** [comment]
`const test = ['test', 'hello world', 'foo bar', 'Lorem ipsum dolor sit amet, consectetur.'];` is 93 lines so it's < 100 columns and will be inlined.

The reason we preserve the expansion of objects is that they can be used in many different contexts (classes, configuration, hash table, switch cases...) and we haven't found a good heuristic to figure out when it should be expanded vs when it shouldn't be, so we found the least bad trade-off to be to rely on users.

But arrays, like most other things in the language, don't have this ambiguity so we use the line length to determine when to break. If you think that it doesn't break often enough, I highly recommend you to switch to 80 columns instead of 100.
