### ISSUE TITLE
Commas vs semicolons in Flow typings (was: Invalid code produced for Flow typings)

### ISSUE THREAD

**Issue by Andreyco** [prettier/prettier#2593]
Having original Flow typings...
```js
declare class ConnectedComponent<OP, P, Def, St> extends React$Component<void, OP, void> {
  static WrappedComponent: Class<React$Component<Def, P, St>>;
  getWrappedInstance(): React$Component<Def, P, St>;
  static defaultProps: void;
  props: OP;
  state: void;
}
```

...invalid code  is printed(notice `,` instead of `;` after class properties)
```js
declare class ConnectedComponent<OP, P, Def, St> extends React$Component<
  void,
  OP,
  void
> {
  static WrappedComponent: Class<React$Component<Def, P, St>>,
  getWrappedInstance(): React$Component<Def, P, St>,
  static defaultProps: void,
  props: OP,
  state: void
}
```

**Comment by lydell** [comment]
As far a I can tell, the commas are not invalid, but I guess semicolons would be more expected here.

**Comment by huntie** [comment]
I'm getting the same warning when declaring method signatures in an interface file.

```js
// @flow

export interface PlayableAnimation {
  play(): void;
  reset(): void;
}
```

```
Replace `;` with `,` (prettier/prettier)
```

**Comment by lydell** [comment]
@huntie What warnings are you talking about?

**Comment by motiz88** [comment]
@huntie is referring to warnings generated `eslint-plugin-prettier` (we work together so I happen to know 🙂 )

As @lydell mentioned in https://github.com/prettier/prettier/issues/2593#issuecomment-327250277 this is about stylistic preference, not correctness; in other words - should Prettier follow the [Flow docs' style](https://flow.org/en/docs/types/interfaces/) for `interface` members or stick to the current comma-delimited style ([which Flow does accept](https://flow.org/try/#0KYDwDg9gTgLgBASwHY2FAZgQwMbDgBQBtMBPTAI0OAEEkEBbTGBCJOAbwCg44xiSAFAEoAXHABuEBABMANNzhRgAZ2AxhYyTM4BfTp2zFlyuLQaJ6fYPWAoTRUhSpnGzVh11A)) as with `type` declarations (Flow docs: [Type Aliases](https://flow.org/en/docs/types/aliases/)).

**Comment by vjeux** [comment]
@motiz88 looks like the flow docs are actually inconsistently using `;` or `,`. On the same doc page you linked. I just sent a PR to fix it: https://github.com/facebook/flow/pull/4951

**Comment by vjeux** [comment]
After talking to @calebmer from the flow team, we should use `;` for delimiters for `declare class` and `interface` instead of `,`. If someone is interested in fixing it in prettier, it should be pretty straightforward.

**Comment by lydell** [comment]
@motiz88 eslint-plugin-prettier does not warn about anything.

**Comment by huntie** [comment]
Had a look at implementing a fix and got here:

I believe the cause is in [**flow-parser**](https://www.npmjs.com/package/flow-parser). The body for an `Interface` node seems to be defined as a set of object properties in the AST [(source)](https://github.com/facebook/flow/blob/4a1ce749a9854566f62c006629f01a0c6816291f/src/parser/ast.ml#L381).

And in that project's test code, the body type for both of the relevant AST nodes is expected to be `ObjectTypeAnnotation`:

- `DeclareClass` [(source)](https://github.com/facebook/flow/blob/dd0603e9d8c9d5fb99a40f0b179a4d6a2b9e66b7/tests/type-printer/types.js#L1811).
- `InterfaceDeclaration` [(source)](https://github.com/facebook/flow/blob/dd0603e9d8c9d5fb99a40f0b179a4d6a2b9e66b7/tests/type-printer/types.js#L1926)

As such, when the AST enters *printer.js* in this project, it is interpreting the body as a set of annotated object properties, and thus decides to prints them as a list delimited with `,`.

Placing the code for the single interface I defined above in Prettier's playground tool, here is the structural overview of the AST object received:

```yaml
type: Program
body:
  - 
    type: ExportNamedDeclaration
    declaration:
      type: InterfaceDeclaration
    body:
      type: ObjectTypeAnnotation # Should be some "StatementList" equivalent
      properties:
        - type: ObjectTypeProperty
        - type: ObjectTypeProperty
```

Please correct me on any of these findings if incorrect.

**Comment by motiz88** [comment]
@alexhunt Not quite. Flow is correct; Interface bodies and object type bodies (and `declare class` bodies) parse the same because they are the same.

As an aside, this is also why Prettier has a choice here in the first place - its whole mandate is to preserve the AST while changing the surface form (I think there are very few exceptions to this, don't remember what they are at the moment).

Prettier has enough information to go on (as does Flow) because "`ObjectTypeAnnotation` occurring in the `body` of an `InterfaceDeclaration`" is unambiguous.

**Comment by huntie** [comment]
@motiz88 Right. I misunderstood the characteristics of `ObjectTypeAnnotation`.

**Clarifying behaviour to implement**

Here's three Flow constructs that all contain `ObjectTypeAnnotation`. On the left is what we expect to be reprinted unchanged by _Prettier_, and on the right, the output from the current version.

![image](https://user-images.githubusercontent.com/2547783/30772008-d36cbdd2-a04b-11e7-91f5-07c0cf4da30d.png)

Myself, I'm currently unsure how best to precisely signal these variations for the body of `DeclareClass` and `InterfaceDeclaration` within _printer.js_, and I may not be the right person to tackle this straight away.

**Comment by motiz88** [comment]
I'm working on a PR for this (Maintainers, feel free to assign the issue to me)

**Comment by motiz88** [comment]
Complication: https://github.com/babel/babylon/issues/733

With the patch I'm working on, the output in `{ semi: false }` mode becomes unparseable by Babylon. I'm assuming that pragmatically we would not want to ship this until Babylon is fixed?

**Comment by lydell** [comment]
Yeah, since this is not something critical I think it makes sense to wait for the Babylon fix.

**Comment by motiz88** [comment]
Ack! I was inattentive - Babylon is actually aligned with Flow on this (https://github.com/babel/babylon/issues/733#issuecomment-331853209). Which makes semicolons effectively mandatory here. I'll update my patch to emit them despite `{ semi: false }` in this case. (Can imagine a wilder scenario where `{ semi: false }` falls back to commas, but that is likely not desirable)

**Comment by zaynv** [comment]
Can't we just omit semicolons/commas altogether?

Something like:

```js
interface Person {
  name: string
  age: number
}
```

**Comment by vjeux** [comment]
@zaynv the first one is not valid in Flow

**Comment by SimpleCookie** [comment]
@vjeux neither of them are valid in pure `TS verison ^2.8.3`. I need the comma, else I cannot compile my project, i.e. I cannot use prettier as it seems now?

**Comment by lydell** [comment]
@SimpleCookie Please open a new issue!
