### ISSUE TITLE
Prettier formats type unions badly

### ISSUE THREAD

**Issue by jakubbarczyk** [prettier/prettier#2610]
Notice the pipe characters.

```
.switchMap(
      (
        action:
          | MyActions.Success
          | MyActions.Error
      ) => {
        // ...
      }
    )
```

Properly formatted code should look something like that:
```
.switchMap(
      (
        action: MyActions.Success
              | MyActions.Error
      ) => {
        // ...
      }
    )
```

**Comment by hawkrives** [comment]
See https://github.com/prettier/prettier/issues/28 and https://github.com/prettier/prettier/pull/67 for related discussion.

**Comment by lydell** [comment]
Prettier does not do such alignment, which is dependent on other code (the word "action" in this case), because of complexity and if you rename "action" several lines will be re-indented causing unnecessary diffs. There have been issues before about aligning stuff this way; feel free to go search for them.
