### ISSUE TITLE
"esc to close" is missing on error message

### ISSUE THREAD

**Issue by willnwhite** [prettier/prettier#2615]
![screen shot 2017-08-12 at 09 30 11](https://user-images.githubusercontent.com/8081877/29239206-e1420ec0-7f40-11e7-8cd9-cbd6b037712b.png)

I grew tired of closing these error messages using the mouse. Then I realised they could be closed with the escape key. I think the error message should say "esc to close".

**Comment by lydell** [comment]
Hi! This looks like an issue for [prettier-atom](https://github.com/prettier/prettier-atom), not prettier itself. So please go ahead and open an issue there :)

(Though personally I don’t think "esc to close" should be added there since that applies to _all_ such notifications in Atom (not just the notifications from prettier-atom), doesn’t it? And you could change the keyboard shortcut to something else?)
