### ISSUE TITLE
very long one line strings (like base64 or urls) in logical operators

### ISSUE THREAD

**Issue by nperichSYKES** [prettier/prettier#263]
Love the project! This is just noting a very minor observation, feel free to close.

Suppose you have an image component which takes a src url but provides a base64 fallback if it's missing. 

```
const SuperIcon = ({className, src}) => (
  <img
    className={className}
    src={src || "data:image/svg+xml;base64,PD94bWw.............and on and on and on..........."}
  />
)
```

Prettier will turn it into this:

```
<img
  className={className}
  src={
    src ||
    'data:image/svg+xml;base64,PD94bWw.............and on and on and on...........'
  }
/>
```

The JSX merely illustrates the use case to the extent it is reasonable (just wanting to keep an implicit return on a functional component and not store the base64 in a variable). 

There's the same effect of new lining the long string without JSX. 

```
const src = url ||
  'data:image/svg+xml;base64,PD94bWw.............and on and on and on...........';
```

(This really doesn't matter much at all, since my example would be "better" done by assigning the long string to a variable then putting two short variables around the connective. Maybe it's my habit that needs to change!)

EDIT: To the extent this is relevant, my expectation would be that if the last part of a logical expression is a long string (> 80 char) and the rest of the expression fit on one line, the long string shouldn't break to a new line. If the expression was breaking to multiple lines anyway, the long string should get it's own line. But again, I can see not wanting to do this, just throwing it out there.

Basically, the idea is if a string is going to overflow anyway, it shouldn't go to a new line just to overflow. It should just overflow on the first line.

**Comment by vjeux** [comment]
Thanks for raising this! A way to implement this would be to make the length of a very long string like this for the solver point of view to be small, like 10 characters.

I can see it being useful.

**Comment by jlongster** [comment]
Something like that might be possible, but it seems weird that if a long string is inside a deeply nested expression that it wouldn't break up the whole expression. There are only so many special cases we can do before this formatter because unpredictable and we're not sure anymore of how it's going to format something. The user should be able to learn the rules pretty quickly after using it for a bit. 

There are also certain cases where I'm more willing to tell the programmer to tweak their code before implementing more special cases. In this case I would recommend moving the string up as a variable instead of embedding a big thing:

```
var url = "data:image/svg+xml;base64,PD94bWw.............and on and on and on...........";
```

That allows you to embed a string as long as you want and it'll never break. I think it makes the JSX more readable anyway.

**Comment by vjeux** [comment]
We are unlikely going to implement this. Closing this issue for sake of keeping the issue list actionable.
