### ISSUE TITLE
Decimal formatting doesn't get all decimals in a rule.

### ISSUE THREAD

**Issue by itsgreggreg** [prettier/prettier#2712]
Current Prettier:
```shell
$ ./node_modules/prettier/bin/prettier.js -v
1.6.0
```

Create a file called test.css:
```css
$ echo ".test{margin: -.3rem .5rem .2px -.5vh;}" |> test.css
```

Run prettier:
```shell
$ ./node_modules/prettier/bin/prettier.js test.css
.test {
  margin: -.3rem 0.5rem 0.2px -0.5vh;
}
```

Notice that the first value (-.3rem) still does not have leading zero.

**Comment by lydell** [comment]
Sigh. The ad-hoc CSS parsing strikes again.

**Comment by lydell** [comment]
Just some random notes:

According to the CSS spec, a leading plus or minus sign can actually be part of the number token itself: https://www.w3.org/TR/css-syntax-3/#number-token-diagram

I guess the value parser tries to do that, but has trouble because it also wants to parse plus and minus signs as operators, resulting in somewhat inconsistent parsing.
