### ISSUE TITLE
JSX ternaries include parens

### ISSUE THREAD

**Issue by jasonLaster** [prettier/prettier#2729]
I just upgraded and noticed that JSX ternaries seem to always be including parens. I assume this is to support JSX. I think it would be nice to special case ternaries that have js function calls and avoid the parens.

![screen shot 2017-09-01 at 4 02 00 pm](https://user-images.githubusercontent.com/254562/29985901-08597db0-8f2f-11e7-8c6e-0e922fc394bf.png)

**Comment by vjeux** [comment]
Thanks, we need to fix it. Cc @azz

**Comment by vjeux** [comment]
Another issue: when using the pattern (a ? b ? c : d : e) instead of the usual (a ? b : c ? d : e), then the way it is printing is completely unreadable:

```js
class A {
  render() {
    return (
      <div>
        {properties.length > 1 ||
        (properties.length === 1 && properties[0].apps.size > 1)
          ? draggingApp == null || newPropertyName == null
            ? <MigrationPropertyListItem />
            : <MigrationPropertyListItem apps={Immutable.List()} />
          : null}
      </div>
    );
  }
}
```

outputs

```js
class A {
  render() {
    return (
      <div>
        {properties.length > 1 ||
        (properties.length === 1 &&
          properties[0].apps.size > 1) ? draggingApp == null ||
        newPropertyName == null ? (
          <MigrationPropertyListItem />
        ) : (
          <MigrationPropertyListItem apps={Immutable.List()} />
        ) : null}
      </div>
    );
  }
}
```

**Comment by vjeux** [comment]
cc @suchipi

**Comment by suchipi** [comment]
The formatted presented by @jasonLaster was intentional, but I've been seeing some weird stuff with it too lately, so I think it needs to be changed. I'm not sure what the best way of doing it would be, though.

The current rules for "should we print this ternary in JSX mode" are:
* The ternary is inside of a jsx expression container (the `{}`)
OR
* The ternary contains JSX elements

I'm thinking we should maybe drop the first check, and only care about it if JSX elements are inside the ternary. But the first check was there for this case:
```jsx
// Note: not necessarily how prettier would format it (the names aren't long
// enough to break), but I'm just trying to show the pattern

const Something = ({ answer }) => {
  const contentIfYes = (
    <div>
      {"...lots and lots of content"}
    </div>
  );

  const contentIfNo = (
    <div>
      {"...lots and lots and lots of content"}
    </div>
  );

  return (
    <div>
      {answer ? (
        contentIfYes
      ) : (
        contentIfNo
      )}
    </div>
  );
}
```
Often, I would pull some inline content out into a variable (or from a variable into inline content), and it's easy to move content around between the two places if the formatter treats a jsx element and an identifier that refers to one in the same way.

But you get weird stuff like what's seen here. I also saw it with string recently, and it was kinda awkward.

As an aside, I like that the JSX ternary style puts the ending `}` of the JSX expression container on its own line. But that might just be personal preference.

As far as the "(a ? b ? c : d : e)" thing @vjeux mentioned... Maybe we should change it to format like this?
```jsx
class A {
  render() {
    return (
      <div>
        {properties.length > 1 ||
        (properties.length === 1 && properties[0].apps.size > 1) ? (
          draggingApp == null || newPropertyName == null ? (
            <MigrationPropertyListItem />
          ) : (
            <MigrationPropertyListItem apps={Immutable.List()} />
          )
        ) : null}
      </div>
    );
  }
}
```

**Comment by lydell** [comment]
Possibly related: #2714

**Comment by vjeux** [comment]
For the initial issue, I've had multiple people at Facebook complain about it. All the cases where having an expression in the JSX attributes and not as children. `<Component someAttribute={a ? b : c} />` where in practice you're less often putting JSX there and more often just normal JavaScript.

The suggestion for "(a ? b ? c : d : e)" looks good to me.

**Comment by suchipi** [comment]
We could special-case the difference between a "children jsx container" and an "attribute jsx container", but I think it would be better to just change the rules for when to use "JSX-mode" ternaries from:

The ternary is inside of a jsx expression container (the {})
OR
The ternary contains JSX elements

to:

The ternary contains JSX elements

I don't think the use-case I'm trying to preserve is worth it. The logic is already pretty complex, and I'm worried about maintainability. Cutting the rules down to only the second case will simplify things; We can go back and look at special-casing the more fine-grained use-cases later, once the 95% is acceptable.

**Comment by vjeux** [comment]
Sounds good, I'm down with the proposed plan :)
