### ISSUE TITLE
Can you explain why is this happening?

### ISSUE THREAD

**Issue by johnunclesam** [prettier/prettier#2757]
**Prettier Version:** 1.6.1 / master

**Code**

Instead of this:

```js
assert.equal(this.$().text().trim(), true);
```

in VSCode I have this on prettify (LAlt + LShift + F):

```js
assert.equal(
  this.$()
    .text()
    .trim(),
  true
);
```

Why?

I think single line is better no?

I have all default. Latest versione (stable) of VScode and latest version of Prettier plugin for VScode.

**Comment by lydell** [comment]
Prettier 1.6 added the rule that as soon as you chain 3 or more methods, they are printed on separate lines. Though in this case I'm not sure if it's better.

**Comment by johnunclesam** [comment]
I would always look at the line limit. No?

**Comment by vjeux** [comment]
@johnunclesam we used to look at the line limit but there were a ton of edge cases where it didn't work great. In 1.6 we switched to always splitting up if there are 3 or more and overall it takes more lines and is not ideal for those examples but we found that it was a better trade-off.

**Comment by johnunclesam** [comment]
I don't like this. Looks bad bad bad.

**Comment by johnunclesam** [comment]
I think you shouldn't close the issue anyway. Maybe someone have a clue.

**Comment by vjeux** [comment]
Unfortunately, making a pretty printer that works perfectly in 100% of the cases is not possible in practice, so we have to make tradeoffs. We tried --really hard-- to make it work with line width but issues kept coming in with code that was very hard to understand because of it.

In case of those pieces of code that are very hard to print in a good way, we opted to err on the side of minimizing cases where the output looks terrible and makes the code harder to understand even though there are legit cases (like yours) where the code is going to look not optimal, but isn't the end of the world.

I'm closing it so quickly because it's not a new issue that hasn't had much thoughts put in. I probably spent a month full time trying to make chained method calls work great. We're unlikely going to be able to solve your use case, I'm afraid.
