### ISSUE TITLE
Add expected prettier version in config

### ISSUE THREAD

**Issue by slorber** [prettier/prettier#2762]
Hi,

I think it would be nice to be able to define a version in .prettierrc. 

The idea is that if you set `version= "^1.6.1"`  in .prettierrc, running Prettier 1.5 on the project would fail. 

This would prevent other team members with globally installed old versions of prettier to reformat the code in "the old way" when rules of prettier change across versions (see for example JSX formatting changes between 1.5 => 1.6)

**Comment by josephfrazier** [comment]
> The idea is that if you set version= "^1.6.1" in .prettierrc, running Prettier 1.5 on the project would fail.

This would only happen going forward. That is, Prettier 1.5 would continue to work, since it doesn't care about `.prettierrc`.

> This would prevent other team members with globally installed old versions of prettier to reformat the code in "the old way"

Is your goal to keep bad formatting changes out of your codebase, or to just remind people that they should upgrade prettier (or better yet, just use the version included in the project)?

**Comment by slorber** [comment]
Yes this will only work in the future and wouldn't prevent oldest versions to be run.

The motivation is that my coworker updated prettier version and reformatted all the code. I pulled and got the changes, but was unable to understand why my local config was formatting the code differently, producing a lot of unwanted changes. This was simply because I didn't run "npm install" to upgrade my local prettier, but this would have been helpful if prettier did fail fast due to version mismatch.

**Comment by suchipi** [comment]
It'd be nice if we could get this to work well with editor integrations, too; those seem like one of the more likely ways to accidentally run the wrong prettier version (compared to, say, a package.json script)

**Comment by josephfrazier** [comment]
Thanks for explaining the motivation, @slorber! I see the potential benefits of implementing this, but I'm concerned that it could make it more difficult for users to test newer versions of Prettier against their codebase (for example, if they were investigating whether to upgrade). If this were implemented, I think we should have an option that lets Prettier ignore the configured version.

Side note: Instead of adding a new property to `.prettierrc`, we could have Prettier read the version from `package.json`. Obviously, this would only work on projects with a `package.json`, but it has the additional benefit of not requiring users to edit their `.prettierrc` in order to opt-in to the new functionality.

**Comment by slorber** [comment]
using the version of package.json is fine to me

Anyway if user wants to test newer version he could simply remove the version line in .prettierrc (which is optional anyway)

**Comment by suchipi** [comment]
I think using the version specified in package.json is the way to go- that has a higher likelihood of helping catch this before it becomes a problem, since it's slightly less opt-in.

**Comment by azz** [comment]
Agreed.

**Comment by lydell** [comment]
Did I misunderstand the package.json proposal here? I thought it was about adding code to Prettier that reads package.json and checks if `"prettier": "..."` in there matches the version of Prettier that is running.

**Comment by azz** [comment]
Shouldn't `npm` or `yarn` be the tool responsible for checking that the contents of `package.json` matches what's in `node_modules`?

**Comment by lydell** [comment]
Ideally, yes, but they don't do that, do they?

**Comment by lydell** [comment]
I guess this could be solved by using one of those automatic git hook installers adding a "run `npm install`/`yarn` if package.json or package-lock.json/yarn.lock has changed after `git pull`".

**Comment by slorber** [comment]
@azz in my story [here](https://github.com/prettier/prettier/issues/2762#issuecomment-328172864) even if I was using local prettier with correct version in `package.json` I got screwed by simply forgetting to run `yarn install`. And it would have been the same problem if I was running a global version of prettier instead of a local one (which many people probably do)

**Comment by suchipi** [comment]
@lydell 
>Did I misunderstand the package.json proposal here? I thought it was about adding code to Prettier that reads package.json and checks if "prettier": "..." in there matches the version of Prettier that is running. So this shouldn't be closed?

That was my understanding as well

**Comment by lydell** [comment]
Re-opening.

@slorber It would be awesome if you could try out my git hook idea and see how it works for you! If successful, we could add a tip about it in the readme. If not successful, I guess we could move on with the idea of Prettier validating the version in package.json.

**Comment by slorber** [comment]
@lydell the git hook would not solve the problem for people with a global prettier installation. Many people still don't know that we can use `./node_modules/.bin/prettier` and use global install. Sometimes the correct version is only in project readme and when modified not communicated/updated immediately by the whole team.

I would not encounter the problem again using git hooks but some people probably will, so it's up to you to decide weither it's worth protecting these users or not ;)

**Comment by lydell** [comment]
@slorber Your original story was that you forgot to run `npm install` to update your local Prettier. We have not heard about anyone using a global Prettier install instead of the correct local version in real life yet. (You have only suggested that this _could_ be a problem.) The git hook would solve your story. Let's focus on the problems that we have actually encountered in the wild.

**Comment by slorber** [comment]
so I guess we can close because I don't actually have any problem that can't be fixed in userland

It's just others will probably make the same error and will not install git hook and/or use local version  until they encounter this problem. They'll probably not even report they encountered the problem here because they'll likely figure it out themselves. 

The point of this issue was not really to fix a problem, just to provide better DX
