### ISSUE TITLE
Do not add trailing comma at the end of function params

### ISSUE THREAD

**Issue by nhducit** [prettier/prettier#2788]
Prettier 1.6.1 (--trailing-comma: all) add trailing comma at the end of function params which cause `SyntaxError: Unexpected token )`

**Prettier Version:** 1.6.1 / master

**Code**

([playground](https://goo.gl/u1fvts))

```js
const checkVersion = ({ name, command, semVersion, updateCommand }) => {
  return new Promise((resolve, reject) => {
    exec(command, (err, stdout) => {
      const verion = semver.clean(stdout)
      if (err) {
        reject(err)
      } else if (!semver.satisfies(verion, semVersion)) {
        reject(
          `[ERROR]: You need ${name} version ${semVersion}. Run '${updateCommand}' to update latest version or ${semVersion}`
        )
      } else {
        resolve()
      }
    })
  })
}
```

**Expected behavior:**
```
        reject(
          `[ERROR: C Pro]: You need ${name} version ${semVersion}. Run '${updateCommand}' to update latest version or ${semVersion}` <=== without comma
        );
```
**Actual behavior:**
```
        reject(
          `[ERROR: C Pro]: You need ${name} version ${semVersion}. Run '${updateCommand}' to update latest version or ${semVersion}`, <=== comma
        );
```

**Comment by ikatyang** [comment]
Hi, it seems what you need is the `--trailing-comma es5` option, since `--trailing-comma all` is considered you're using node 8 or other JavaScript-variant that allowed trailing comma for function parameters, e.g. TypeScript, which won't cause SyntaxError.

---

### [Trailing Commas](https://github.com/prettier/prettier#trailing-commas)
Print trailing commas wherever possible when multi-line. (A single-line array,
for example, never gets trailing commas.)

Valid options:
 * `"none"` - No trailing commas.
 * `"es5"` - Trailing commas where valid in ES5 (objects, arrays, etc.)
 * `"all"` - Trailing commas wherever possible (including function arguments). This requires node 8 or a [transform](https://babeljs.io/docs/plugins/syntax-trailing-function-commas/).

Default | CLI Override | API Override
--------|--------------|-------------
`"none"` | <code>--trailing-comma <none&#124;es5&#124;all></code> | <code>trailingComma: "<none&#124;es5&#124;all>"</code>

**Comment by nhducit** [comment]
@ikatyang thank you for quick response.
