### ISSUE TITLE
removal of backslashes in string.

### ISSUE THREAD

**Issue by zeroEvidence** [prettier/prettier#2789]
**Prettier Version:** 1.5.2 & 1.6.2

**Code**
No playground, couldn't figure out how to get unique link for my sample.

```js
const decimalNumber = XRegExp('\d\.\d{3}', 'i');
```

**Expected behavior:**
```js
const decimalNumber = XRegExp('\d\.\d{3}', 'i');
```

**Actual behavior:**
```js
const decimalNumber = XRegExp('d.d{3}', 'i');
```

**Comment by ikatyang** [comment]
Hi, those backslashes does nothing there:

![image](https://user-images.githubusercontent.com/8341033/30276670-2353ce2a-9738-11e7-9d92-5e96ed488f84.png)

I'm not sure if you're attempting to write regex string (should use double backslashes, e.g. `'\\d\\.\\d{3}'`) or want to preserve those unnecessary backslashes?

**Comment by ikatyang** [comment]
For the playground link, all you have to do is to copy its url :)

![image](https://user-images.githubusercontent.com/8341033/30277536-adddf7bc-973a-11e7-9a0e-e3f9fbcae1b5.png)

**Comment by greypants** [comment]
@ikatyang this is a legit issue inside of template literals.

I'm using a markdown tagged template literal to output dome documentation, which happens to include the syntax for string interpolation (`${}`). I need to escape those characters so they're rendered directly instead of interpolated.

```js
markdown`
  const cssString = css\`
    background-color: \$\{color('base')\}
  \`;
`
```

But prettier is removing the escape backslashes.

Output: 
```js
markdown`
  const cssString = css\`background-color: ${color('base')}\`;
`;
```

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAhgJwNYBMIDuUABgDpQAEFkUAzjNbbQMoyYCWUA5hQLyO1SpMpSoUARujDYumCAFcouALSQANhExIKQgCRDg6zQAoA5JNpxTASiEBfclSHEA3OWIgANCAgAHGOzQtMigWHIEAApYCMEo6ABuEOy4XiDimFLYcDDMvlKcXMhs8nDenJaYMBEZXBjIAGboapbeAFa0AB4AQhnS2czoqHAAMpxwDU0tIHmYFchp6OIAnhpQqb4csADqyTAAFsgAHAAM3hsQllsZvvMbcBXx496YcACO8uwv1ei16BPNpRAllQ7CKmBK3loBTUcAAivIIPB-lMYIsdrh9sgAEzeNjodhqAoAYQgqDqKCg0CeIHklgAKotYo0AXY7EA)

**Comment by ikatyang** [comment]
Can you open a new issue for that? It seems unrelated to this issue, thanks!

**Comment by ndac-todoroki** [comment]
We fell in the similar problem.
When using [React Router `<Route>`](https://reacttraining.com/react-router/web/api/Route/path-string), it allows to pass strings which are:
> Any valid URL path that path-to-regexp understands.

For example, we pass a string `<Route exact path="/path/:id(\d+)" />` (It seems Prettier don't remove backslashes here).

Later in our code, we take out the `props.match.path` which shows to be the same string as above, and want to perform a `switch` with other path strings, which are all in an `Enum`. The deletion happens here.

```ts
enum Paths {
  Root = "/",
  Users = "/users",
  UserShow = "/users/:id(\d+)", // <- Prettier deletes the backslash here
}
```

I wish this could be prevented, because `switch` matches by the string as-is, not by its regex meanings.

**Comment by j-f1** [comment]
@ndac-todoroki although the `\d` in the JSX string is interpreted as the characters `\` and `d`, the `\d` in the regular string is just interpreted as `d`, and Prettier removes the now-unnecessary escape. You’ll find that even without running Prettier, the `UserShow` route won’t work — it’ll actually match `/users/ddddddd`. Changing it to `/users/:id(\\d+)` should fix the issue.

**Comment by ndac-todoroki** [comment]
You were right! Some how I didn't notice it wasn't working :(

**Comment by stclairdaniel** [comment]
I'm having a similar issue - I have a string like this:
`"matchRegexp:(^$)|(^[^!#$%&'\"()*+,/:;<=>?@[\]^`{|}~\\]+$)",`
and after saving with Prettier, it changes to:
`"matchRegexp:(^$)|(^[^!#$%&'\"()*+,/:;<=>?@[]^`{|}~\\]+$)",`

Note the missing backslash before the close brackets inside the character class. The backslash is being used to escape the close bracket. Without it, the close bracket will be interpreted as the end of the character class. I would just //prettier-ignore it, but I also need to //eslint-disable and I'm not sure how to do both for a single line.

**Comment by j-f1** [comment]
@stclairdaniel You need two slashes for that to work as you’d expect, and four where you currently have `\\`.

**Comment by stclairdaniel** [comment]
Sure enough! I couldn't tell if it was user error or not - thanks for the help.
