### ISSUE TITLE
Do not lowercase HTML attribute in CSS selector

### ISSUE THREAD

**Issue by maxime1992** [prettier/prettier#2828]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22md-form-field%20%5BmdPrefix%5D%20%7B%5Cn%20%20margin-right%3A%2010px%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22postcss%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```css
md-form-field [mdPrefix] {
  margin-right: 10px;
}
```

**Output:**
```css
md-form-field [mdprefix] {
  margin-right: 10px;
}
```

**Expected behavior:**
Keep the initial attribute with the uppercase: 

```css
md-form-field [mdPrefix] {
  margin-right: 10px;
}
```

The mdPrefix is an attribute needed by angular material but in general this might break things.

**Comment by lydell** [comment]
Hi! As far as I know, both HTML attributes and CSS attribute selectors are completely case insensitive. And when testing it, that seems to be true: https://jsfiddle.net/bdxxx30m/1/

How does this break things for you?

**Comment by maxime1992** [comment]
@lydell you're totally right! Forget about that with HTML :sweat_smile:

**Comment by maxime1992** [comment]
That said, I'm just wondering why prettier lower case that.
It kind of lost readability, doesn't it?

**Comment by lydell** [comment]
The use case I had in mind when doing the lowercasing stuff was this: `A[HREF] {COLOR: #FFF;}` → `a[href] {color: #fff;}`. I didn’t know that some frameworks use non-lowercase attribute names. Do you know of more examples than angular material?

**Comment by maxime1992** [comment]
No I do not. And I understand your point.
Indeed this : `A[HREF] {COLOR: #FFF;} → a[href] {color: #fff;}` is a good use case.

It just feel a bit weird with "customs" attributes.

Maybe it's better for now to let it like that and if other people feel the need to keep some names with uppercase in it, prettier might lowercase know (native) attributes `href`, `class`, `src`,.. and let the "customs" as they're written

**Comment by azz** [comment]
An alternate heuristic: only lowercase it if it's all uppercase.

**Comment by maxime1992** [comment]
Should I reopen this issue? So it gets more visibility and people might share different ideas?

**Comment by the-ult** [comment]
Would be great if there is a setting, which won't lowercase `[attribtue]` settings

**Comment by lydell** [comment]
@the-ult Would be great to hear the motivation as well! :)

**Comment by the-ult** [comment]
The same as @maxime1992 .
Using Angular (>2) a lot (with Angular  Material 2) They use camelcase naming convention for attributes like `mdSelect`
`mdInput` etc.
- https://angular.io/guide/styleguide#directive-selectors
- https://angular.io/guide/styleguide#custom-prefix-for-directives
- https://github.com/angular/angular/issues/866

Sometime you'll need these to override some css or for your own directives/custom-attributes.

When these are automatically made lowercase, the styling will brake.

**Comment by maxime1992** [comment]
@the-ult when you say: 
> When these are automatically made lowercase, the styling will brake

It's not true. Because as @lydell pointed out:
> both HTML attribute names and CSS attribute name selectors are completely case insensitive

But I agree that it's still pleasant to keep those attributes camel case :+1:

**Comment by renestalder** [comment]
What @the-ult wants to say is, that Angular directive decorators are case sensitive, which breaks the styling in his case. This is only one example. Prettier will false correct Angular templates, making them break completely in the simplest cases.

Example:

**Input:**
```html
<div *ngIf="expression">
</div>
```

**Output:**
```html
<div *ngif="expression">
</div>
```

Which then will show up as invalid Angular template, because the ngif decorator (lower case) doesn't exist.

**Comment by lydell** [comment]
We backed out lowercasing of attribute names in 1.9.0 due to it not being valid to do so in SVG, so this is not an issue anymore.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbAJgWgGYQE6o4CWcANugAQDaGACnnNkQB4C6FwAOlBRagIZ4A5kSiY8RIQAsYSCgEYADAAdmAbm4BfbiAA0ICMphFoAZ2ShlE2AHUi6GFOQAORfpj8ARnYdOkAJn1TUSFSOABFAFcIeGRsflJTOHc8fiJSEIBhCFQBZBAoaDg9EE9UsABrOBgAZWV+MBDkGDxI5JAAK1NmACFyqtr+VDgAGVFipHjE9vq8JLx8sFNzILhUImbW9sikgBUvc0mEpP1ReZh6fiE8o+n9BgBHSKIGS+v+OOOZvAgkm1TlPkSoIfgB3WiCBCHEAldAQMCfO4gfimGCIk4GSIwZRY-zouCaTRAA)
```sh
--arrow-parens 
--parser css
--prose-wrap 
```

**Input:**
```css
md-form-field [mdPrefix] {
  margin-right: 10px;
}

```

**Output:**
```css
md-form-field [mdPrefix] {
  margin-right: 10px;
}

```
