### ISSUE TITLE
CSS property names must not be lowercased in styled-components

### ISSUE THREAD

**Issue by antoniomika** [prettier/prettier#2850]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22const%20FormContainer%20%3D%20styled.div%60%5Cn%20%20%20%20maxWidth%3A%20500px%3B%5Cn%20%20%20%20margin%3A%200%20auto%3B%5Cn%20%20%20%20minHeight%3A%20calc(100vh%20-%2030px%20-%202rem%20-%2080px)%3B%5Cn%20%20%20%20padding%3A%2020px%2020px%2050px%2020px%3B%5Cn%60%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Atrue%2C%22tabWidth%22%3A4%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
# Options (if any):
--single-quote
--trailing-comma none
--tab-width 4 
```

**Input:**
```jsx
const FormContainer = styled.div`
    maxWidth: 500px;
    margin: 0 auto;
    minHeight: calc(100vh - 30px - 2rem - 80px);
    padding: 20px 20px 50px 20px;
`;
```

**Output:**
```jsx
const FormContainer = styled.div`
    maxwidth: 500px;
    margin: 0 auto;
    minheight: calc(100vh - 30px - 2rem - 80px);
    padding: 20px 20px 50px 20px;
`;
```

**Expected behavior:**
```jsx
const FormContainer = styled.div`
    maxWidth: 500px;
    margin: 0 auto;
    minHeight: calc(100vh - 30px - 2rem - 80px);
    padding: 20px 20px 50px 20px;
`;
```

The output for this should include the camelcase of the styled options. This is described in the [React documentation](https://titobouzout.github.io/react/tips/inline-styles.html).

**Comment by vjeux** [comment]
@mxstbr why is this even working!?

**Comment by thysultan** [comment]
@mxstbr I don't think this is a bug with styled-components, both `maxWidth` and `maxwidth` are invalid css. The oddity here is that prettier converts `camelCase` rules to lowercase.

**Comment by lydell** [comment]
@thysultan Lots of things, including property names, are case <strong>in</strong>sensitive in CSS. In 1.7.0 (which was released recently) we shipped case normalization (`A[HREF] {COLOR: #FFF;}` → `a[href] {color: #fff;}`). We weren’t aware that styled-components had case sensitive property names. Since that seems to be the case, we need to fix this. Either not lowercasing property names in “styled-components-CSS” or never lowercasing property names if they seem to camelcased.

**Comment by thysultan** [comment]
@lydell I meant that regardless of the prettier treatment of lowercasing `maxWidth`, it still wouldn't work. I think it's a documentation problem.

@antoniomika The document about the camleCase syntax used when targeting inline-styles does not apply here since styled-components does not use inline-styles.

**Comment by antoniomika** [comment]
@thysultan yes, you are correct. But in styled [pre-2.0 camelcase was supported](https://github.com/styled-components/styled-components/issues/787). We are currently locked to 1.4.6 in the [project](https://github.com/mhacks/mhacks-web/blob/master/yarn.lock#L6012) I am working on, but that could be changed.

**Comment by mxstbr** [comment]
Oh yeah, pre-2.0 we were a lot more lenient with the CSS we accepted. I'd highly recommend upgrading to 2.0, see the [announcement blogpost](https://medium.com/styled-components/announcing-v2-f01ef3766ac2) for more info!

**Comment by lydell** [comment]
@mxstbr So regular dash-cased CSS properties was supported as well in pre-2.0? If so, @antoniomika, you could stay on 1.4.6 but update from camel-case to standard dash-case.

**Comment by mxstbr** [comment]
Yep, of course, we just (for some reason I can't recall) supported `camelCase` pre v2, though it was never documented and more of an unintended sideeffect of some of our hacky code. (which is gone with v2)

**Comment by antoniomika** [comment]
Alright, upgrading sounds like a fine fix. Didn't know prettier required any such software/version for support however.

**Comment by vjeux** [comment]
JavaScript, TypeScript and GraphQL are well specified and it is relatively clear what is supposed to work and what isn't. CSS is the wild west in comparison, all the tooling on-top of it is based on hacks on-top of hacks and it's not clear if you print things a bit differently if things are going to break or not.

In this case, you wrote code in a way that wasn't supposed to work but happened to because of the implementation. We're trying to make reasonable decisions with prettier and this falls into something that we don't intend to support.

**Comment by lydell** [comment]
> JavaScript, TypeScript and GraphQL are well specified [...] CSS is the wild west in comparison, all the tooling on-top of it is based on hacks

(Just to be super clear here, the standard CSS specification is well specified, it's the tooling on-top that is the wild west.)

**Comment by mxstbr** [comment]
To give a bit of historical context and excuse this stupid behavior in styled-components:

v1 was a super wild hack where we basically took the Node version of PostCSS and made it run in the browser. (in fact, the very first actually published version of styled-components was like 120kb gzip 😅) We had no idea if anybody was going to like the API, so our main concern was quick exploration there and getting it out in front of folks.

v2 took what we learned in terms of the API, solidified it (and extended it a tiny bit) and we switched to a CSS parser made for the purpose (stylis by @thysultan above) rather than a hacked version of PostCSS. This is why this worked in v1, even though it totally shouldn't have and won't ever again.

Anyways, just a fun story for y'alls Monday pleasure. Hoping you have a great week and get some shit done! :v:

**Comment by antoniomika** [comment]
Awesome @mxstbr, thanks for the clarification! I definitely get the woes of the development cycle and this really didn't cause much pain! Most of the reason it was used was just keeping up with convention when the project first started (one of the issues with boilerplates, even if it's one that you create). I appreciate all of the feedback and we're definitely getting the right stuff together.

**Comment by iRoachie** [comment]
@mxstbr @thysultan @vjeux Is there a way to disable this through a flag? The code posted above is a valid styled component in react-native. So now this breaking codebases cause `maxWidth` is becoming `maxwidth` which is invalid code

**Comment by kumarharsh** [comment]
@iRoachie you'll have to replace `maxWidth` with `max-width`.

**Comment by dmueller39** [comment]
@mxstbr AFAICT 2.x styled components for react native accepts camelcase. I was hoping for a lint rule or something but it looks like there is none available.

**Comment by iRoachie** [comment]
@dmueller39 See the reason here https://github.com/prettier/prettier/issues/2897
