### ISSUE TITLE
Interaction between cosmiconfig and cli apps that use `--config`

### ISSUE THREAD

**Issue by beaugunderson** [prettier/prettier#2870]
When `prettier` added `cosmiconfig` support recently I started seeing 'Validation Warning' text in the console. The proximate cause is `cosmiconfig`'s parsing of `argv` for a `--config` option.

In our project we use:

- `webpack --config static/webpack.config.js`, which calls
- `eslint-loader`, which is setup to use
- `eslint-prettier-plugin`, which uses
- `prettier`, which uses`cosmiconfig` to provide configuration management...

the bug is that `cosmiconfig` uses our `--config static/webpack.config.js` as the configuration for `prettier`, hence we get thousands of lines like these:

![screenshot](https://i.imgur.com/hXuosKA.png)

**Comment by beaugunderson** [comment]
It looks like the next published release will already contain a fix for this issue due to upgrading cosmiconfig to [3.0.1](https://github.com/davidtheclark/cosmiconfig/blob/2dac2f9165c01a571f5c61648ff3c0079d4a4bee/CHANGELOG.md#300), which removes the parsing of `argv` for `--config`.  🎉

**Comment by ikatyang** [comment]
Hi, thanks for the issue. As you mentioned above, this issue was fixed by #2843 few days ago but haven't released yet, for now you can install the newest prettier from github as a temporary workaround:

```sh
npm install prettier/prettier
```

or if your tools support alias for the `--config` option (e.g. `-c`), using it can also solve the problem  since cosmiconfig only read the `--config` option.
