### ISSUE TITLE
Wrong comments formatting in functions or class methods

### ISSUE THREAD

**Issue by Alphapage** [prettier/prettier#2874]
**Prettier 1.7.0**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22function%20HelloWorld(%2F%2Fcomment%5Cn%7Bgreeting%20%3D%20%5C%22hello%5C%22%2C%20greeted%20%3D%20'%5C%22World%5C%22'%2C%20silent%20%3D%20false%2C%20onMouseOver%2C%7D)%2F%2Ffunction%20comment%5Cn%7B%5Cn%5Cn%7D%5Cn%5Cnfunction%20HelloWorld2(%2F%2Fcomment%5Cntest%2F%2Fanother%20comment%5Cn%2Ct)%2F%2Ffunction%20comment%5Cn%7B%5Cn%5Cn%7D%5Cn%5Cnclass%20c%20%7B%5Cn%20%20method(%2F%2Fcomment%5Cn%20%20test%20%2F%2Fanother%20comment%5Cn%20%20%2Ct%5Cn%20%20)%2F%2Ffunction%20comment%5Cn%20%20%7B%7D%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
function HelloWorld(//comment
{greeting = "hello", greeted = '"World"', silent = false, onMouseOver,})//function comment
{

}

function HelloWorld2(//comment
test//another comment
,t)//function comment
{

}

class c {
  method(//comment
  test //another comment
  ,t
  )//function comment
  {}
}
```

**Output:**
```jsx
function HelloWorld( //comment
  { greeting = "hello", greeted = '"World"', silent = false, onMouseOver } //function comment
) {}

function HelloWorld2( //comment
  test, //another comment
  t //function comment
) {}

class c {
  method(test, t) {} //comment //another comment //function comment
}

```

**Expected behavior:**
Identical as input: with comment lines at the right places

**Comment by duailibe** [comment]
IMO only the last is actually a problem and was fixed by #3441: [playground link](https://deploy-preview-3441--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUA9E5ALZsIwA6UwA5tThxcUfvgC8+biAAWpcjIA0+QcPh1J+AOQyqtOjO0qAzjhJctqAIYkTcFdACyEdPYDyANzjUlAXwBKFgwsXAJ2TlheYF5eP1ioEOw8KCIFShp6ACZmVggOLl54ExgWaygIGHlqfAjCqCUYIKYksNS6qL4E+KheMBJrExNa-BjU-E4qiEYWDp5x4ph8Moqqn1r8yPn8fEbeHebWlI2Czp3gHr8QJRAIAAc2k2RQa2pqCAB3AAVXhCeUayeCA4OjXECDGDIGx2BwgABG1GsYAA1iIAMp3JE4MTIGDUdCwugQMBQ2z2G7Y+zUGBfRH8NjWUkwm4AKxMAA8AEKIlHo6ycAAy2LgTPJt3QMDuEqyothmOoVOQ8OscIAnuQoGC7tRsTAKCCqsgABwABhu2og9goiLuSu1cCp3jBQgAjugcEJadZ6YykNCxfY2DhcfjYWYxBYAIroSoiv1k2EwFX6uiGpBZG546zmbH8ADCm19IAqUBFNzccAAKir-v64H4-EA)
