### ISSUE TITLE
1.7.1 Release

### ISSUE THREAD

**Issue by suchipi** [prettier/prettier#2887]
There have been a lot of CSS lowercase fixes and we are starting to get duplicate reports on some of them. We should probably publish a patch release containing those fixes.

**Comment by vjeux** [comment]
Sgtm

**Comment by ikatyang** [comment]
Notice that we should uncomment https://github.com/prettier/prettier/commit/68d1b56696005821178b45437629c439e9c110c1  before releasing.

**Comment by lydell** [comment]
Any objections to merging #2844 before 1.7.1?

**Comment by suchipi** [comment]
I think the only potential blocker on that would be the discussion in https://github.com/prettier/prettier/issues/2846, since the CLI arguments are part of the public API, so if we released #2844 and then changed the parser option, it'd be a breaking change.

**Comment by suchipi** [comment]
To clarify... #2846 would be a breaking change, too. I'm concerned about `--parser postcss-less` changing into `--parser less`

**Comment by vjeux** [comment]
By the way, I just want to mention that I'm heads down on my new team and won't have the time to be as involved in the next few months. I just clicked the "Unwatch" button, please cc me if anything needs my attention.

I trust @azz, @lydell, @suchipi and co to make the project move forward in a good way :)

**Comment by mitermayer** [comment]
Hi guys, 

What are your thoughts around including the `prettier` version on error messages on the CLI ?

This could give users of editor integrations a bit more context on why things may break, which  is important since we do CLI args validations. 

The current model of CLI args validation forces any editor integration that rely on the cli to do major releases (breaking changes) since by passing the new args it completely break compatibility with older prettier.

The reason I raised this discussion in here is due to the work that has been done around validation of CLI args to 1.7.1

**Comment by lydell** [comment]
@mitermayer Could you give an example? Prettier only warns about unknown options, so passing new options to an old Prettier should not be a problem? What work around the CLI are you talking about specifically?

**Comment by ikatyang** [comment]
@mitermayer 

We didn't add additional validations for CLI, just add missing validations for configs from `--config-precedence` option.

New flags will be always ignored and show warnings, so it shouldn't be a problem, the only breakings will be new choices since the old version didn't know what to do with it, e.g. `--parser <css|less|scss>`, but I don't know if we can do something for it.

**Comment by mitermayer** [comment]
The problem happens because, when prettier release new features we want to add support to it on editors. We do that by passing extra arguments to the cli. And the most common form of editor integration is by leveraging "stdin" and parsing the values of "stdout".

The error 'unknown arg blah' can cause things like this: https://github.com/prettier/vim-prettier/issues/53

Another possible solution is if there was a way to mute this errors from being printed when executing the CLI

**Comment by suchipi** [comment]
Unless there's something I don't understand, I'm not sure what the difference between that and including the version number in the error messages would be.

**Comment by lydell** [comment]
@mitermayer Can't you hide unwanted warnings?

**Comment by mitermayer** [comment]
@suchipi, running prettier again to get the version is an option but there are some problems with it lets imagine this scenario

1. user saves file and then we use this new extra 'arg' to pass to prettier
2. prettier does not understand that 'arg' and print that message
3. on the editor integration we treat any stdout that is not the file itself as errors
4. we now have to do another system call to prettier to get the version (which is expensive)

The above logic is not ideal for editor integrations for 2 reasons, have an extra version call to the client (which could in theory also fail) and also means that editor integrations would have to keep up to date on how prettier spits errors on the stdout in order to parse it correctly. (we already do that by handling syntax errors, having other types of errors like that just increase complexity)

My suggestion is if we could have either:

1. A fixed place where the prettier version would always be printed alongside any error message (we could then regex parse it) and any changes around it should be considered major release

or 

2. An extra argument that we can pass to the cli that would allow the validation args message to not be printed on 'stdout' example that 'unknown arg'

What are your thouhts around it ?

**Comment by ikatyang** [comment]
The warnings/errors are always printed to stderr, only valid output will be printed to stdout, and you can also catch the exit code to determine if it's an error.

Or maybe we can allow `--version` not to early exit.

**Comment by lydell** [comment]
> Another possible solution is if there was a way to mute this errors from being printed when executing the CLI

Redirect stderr to /dev/null

**Comment by suchipi** [comment]
@ikatyang so you're saying you could include `--version` with any run, and it would print version, and then do whatever else you asked for?

**Comment by ikatyang** [comment]
@suchipi Just like what `jest --debug` did, but I'm not sure if we should do that.

**Comment by ikatyang** [comment]
@suchipi Just like what `jest --debug` did, but I'm not sure if we should do that.

**Comment by suchipi** [comment]
@mitermayer Could we move this conversation to a new issue? I don't think it needs to block a patch/bugfix release.

**Comment by mitermayer** [comment]
@suchipi sounds good to me!

**Comment by lydell** [comment]
@suchipi Are you up for writing the change log again? Or should we look if anyone else is interested?

**Comment by suchipi** [comment]
I can do it. Since it's just a point release, I was thinking that something like [what we did for 1.6.1](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#161) would be enough, rather than a dedicated release document (like we did for 1.6.0 and 1.7.0). But I haven't reviewed all the merged PRs yet, so if there's enough stuff, maybe we should write a larger changelog doc.

My hope is to get the changelog done this evening and then publish the new release tomorrow morning. I could publish it in the evening, too, but last time around we published in the morning so that stuff wouldn't break while people were asleep; I think it'd be good to do it that way again.

**Comment by suchipi** [comment]
Okay, here's a proposed changelog and list of all the TODOs we left for ourselves to take care of post->1.7.0

Commits: https://github.com/prettier/prettier/compare/1.7.0...master

### Changelog (based on [this PR search](https://github.com/prettier/prettier/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E2017-09-14%20)):

* Enable cosmiconfig rcExtensions (#2749 by elektronik2k5)
* Keep original empty lines in argument list (#2763 by jackyho112)
* Upgrade prettier dependency to 1.7.0, fix lint (#2821 by josephfrazier)
* Fix different precedence binary expression when inlining (#2827 by duailibe)
* Bump Babylon (#2831 by existentialism)
* Don't lowercase Less variables when parsed with SCSS parser (#2833 by lydell)
* Don't lowercase `&class` in SCSS/Less selectors (#2834 by lydell)
* Add support for ClassPrivateProperty (#2837 by existentialism)
* Upgrade cosmiconfig to v3, remove hardcoded combinatoric problem (#2843 by azz)
* Split Less and SCSS parsing into different parsers (#2844 by lydell)
* feat: support detailed `--help` (#2847 by ikatyang)
* Update cosmiconfig to 3.0.1 to avoid memory leak (#2848 by danez)
* chore: add prettier-stylelint to the related projects (#2859 by hugomrdias)
* Don't lowercase SCSS placeholder selectors (#2876 by lydell)
* Fix line break in test declarations with 2nd argument as a function (#2877 by duailibe)
* Use semicolons in Flow interface-like bodies (#2593) (#2888 by motiz88)
* We do not need to have a reference to the toolbox-companion since we (#2892 by mitermayer)
* fix(cli): validate options for every `config-precedence` (#2894 by ikatyang)
* fix: do not print stack trace for invalid option (#2895 by ikatyang)
* refactor: use custom error (#2896 by ikatyang)
* fix(typescript): allow symbol type (#2899 by ikatyang)
* Support fit(), xit(), it.only(), etc (#2900 by azz)

### Prerelease action item: uncomment this
- [ ] [README.md#L702](https://github.com/prettier/prettier/commit/68d1b56696005821178b45437629c439e9c110c1) (Github doesn't let me link to a line in a markdown file, because there's no source preview for markdown files)

### Postrelease action items (things that need to be removed/uncommented):
- [ ] https://github.com/prettier/prettier/blob/3703cb5b07a158c507b49c23ef5f7b4abb8a41fe/website/pages/playground/index.html#L362
- [ ] https://github.com/prettier/prettier/blob/3703cb5b07a158c507b49c23ef5f7b4abb8a41fe/website/static/markdown.js#L52
- [ ] https://github.com/prettier/prettier/blob/3703cb5b07a158c507b49c23ef5f7b4abb8a41fe/website/static/playground.js#L241
- [ ] https://github.com/prettier/prettier/blob/3703cb5b07a158c507b49c23ef5f7b4abb8a41fe/website/static/worker.js#L105

I was hoping to get the release out in the morning, but I have to go into the doctor in the morning, so it will probably not go out until midday.

**Comment by lydell** [comment]
Hmm, actually, some of those `Remove "postcss"` comments might not be correct. We might want to keep some of them for backwards compatibility. Don't bother with them, and I can look over it once the release is out :=

**Comment by suchipi** [comment]
Okay, sounds good 👍 I'll just uncomment the one @ikatyang mentioned then (the yml thing in the README)

**Comment by suchipi** [comment]
Released: https://github.com/prettier/prettier/commit/c2bc33b3ad9882aa795a8fa8a15b5fd1629765da

**Comment by lydell** [comment]
I've done the postrelease stuff around postcss and the playground now, and it seems to work out.

**Comment by suchipi** [comment]
Cool, thank you for doing that @lydell
