### ISSUE TITLE
Skip formatting if config file not found (make prettier opt-in)

### ISSUE THREAD

**Issue by kuba-orlik** [prettier/prettier#2907]
Is there a way to make prettier *not* run if there's no config file in the file's project? It would make prettier setup much easier when a small percentage of projects a given person is working on does not use prettier.

**Comment by azz** [comment]
The question does not make sense in the context of `prettier` itself. Prettier will only run when it is run by some tool (be it CLI, editor on-save, etc), so it sounds like you're asking more of an editor integration question, in which case you should forward this question the repository of the editor you're using.

prettier-vscode: See https://github.com/prettier/prettier-vscode/issues/229 and https://github.com/prettier/prettier-vscode/issues/199. Or you can set `"editor.formatOnSave": false` in your user settings and `"editor.formatOnSave": true` in your project settings.

prettier-atom: Already supports `isDisabledIfNotInPackageJson`, see https://github.com/prettier/prettier-atom/issues/43.

**Comment by kuba-orlik** [comment]
@azz 

> The question does not make sense in the context of prettier itself.

I politely disagree. Making this change in `prettier` would make creating client applications much easier, and there's no other place to make that happen than `prettier` itself. It makes no sense to duplicate the logic for file config for each client application!

Currently if no config file is found, the defaults are being used. It would be nice to have a flag that when enabled makes the default behavior (when there's no config) not to format the files at all

**Comment by lydell** [comment]
@kuba-orlik You mean kinda like how ESLint works? No configuration, no linting. No defaults. I can see the appeal of that. At the same time we need to be careful with backwards compatibility. But perhaps behind a flag like you say. Might be worth dicussing more.

**Comment by ikatyang** [comment]
Possible under the `--require-config` flag similar to how `--require-pragma` work but for config file, but it looks a little weird if you just want to use default config:

(.prettierrc)

```yml
# nothing
```

**Comment by duailibe** [comment]
@ikatyang I believe the default is just running without `--require-config`?

**Comment by ikatyang** [comment]
If we implement the `--require-config` flag, we'll need to have a config file to trigger formatting, the key point here is that the position of the config file matters, e.g.

```sh
do-format/
  .prettierrc # if you just want to use default config
              # this file will be either empty (yml) or `{}` (json)
  formatted.js
do-not-format/
  unformatted.js
```

**Comment by suchipi** [comment]
I notice there is some similarity with the proposed `--require-config` and `--config-precedence prefer-file`. They're not the same functionality, but the use cases are similar. Is there any weird interaction between the two flags that we need to think about?

**Comment by ikatyang** [comment]
I think the proposed flag is just a trigger for formatting, it won't affect config merging, i.e. only format files that satisfies `resolveConfig(filePath) === null`.

NOTE: this flag can not be used with `--no-config`.

**Comment by suchipi** [comment]
If you use `--write` and `--require-config` together, it should not change the file contents, right?

**Comment by ikatyang** [comment]
Yeah, it shouldn't change the file contents that can't resolve the config file with `--require-config` + `--write`.

**Comment by azz** [comment]
Let me clarify why I thought it wasn't the right place for prettier to have this.

1. Prettier has such little configuration it seems a bit out of place to have a `--require-config` flag, and introducing it seems like it is going to cause complications with other options.

2. It also seems strange to me to have an application that does a thing, *unless* you give it a flag not to do that thing. Why not just not run the application in the first place?  There is already an API provided to find a config file, which makes it easy to build this functionality. 

3. Prettier generally recommends its default configuration, so to use this you'd end up with a config file of `{}` which has no obvious meaning without knowing this feature exists.

**Comment by azz** [comment]
> You mean kinda like how ESLint works? No configuration, no linting. 

I think eslint and prettier are fundamentally different applications. With eslint you are required to opt **in** to a set of rules, so it makes sense not to run it if there's no config. Prettier on the other hand is opinionated and designed to run with no configuration.

**Comment by suchipi** [comment]
I think @azz's argument makes a lot of sense, actually. The flag would be convenient from an editor integrator's perspective, but it's weird from a prettier's perspective. It's primarily nice for an editor integrator because it lets them be lazy, but we provide the primitives for them to implement that already.

I guess the only advantage to it being in prettier by default is that most editor integrations would then support this workflow, since they commonly have preferences for each of prettier "config-ish" flags.

**Comment by kuba-orlik** [comment]
I think that having this option would help with prettier's adoption. I know that the only thing holding some people back from using it is its viral all-or-nothing attitude. 

I think it would be great to have an option te easilly mark that a given project is using prettier and have all the clients automatically support it.

Our team considered using `//prettier-ignore` on all projects that are not using prettier for some reason, which made prettier look even more viral. 

I think more choice is better

**Comment by suchipi** [comment]
We recently added the [--require-pragma](https://github.com/prettier/prettier#require-pragma) option to ease with gradual or partial adoption; would this satisfy your use-case?

**Comment by kuba-orlik** [comment]
Unfortunately no, adding the comment to thousands of js files would be impractical. And it would be another thing to remember about when creating a file

**Comment by suchipi** [comment]
Maybe [using prettier via eslint](https://github.com/prettier/prettier#eslint)?

Ultimately, this *really* should be the responsibility of the editor integrations... the only reason I think we would put this in prettier itself would be to coerce the editor integrations to all support this workflow (planting the seeds of a pattern for others to replicate). But ultimately, it's up to them to add it, whether they would use that new option or not (and you can see that the vscode and atom integrations do currently have solutions for the use-case you're describing).

From the perspective of prettier, it's really weird to have an option that means "run it, but actually, don't run it, just bail".

---

In general in code, one-off boolean flags that tweak behavior "just slightly" are hard to maintain and grow into confusing and conflicting stuff. If you've ever read one of these before and tried to refactor it without breaking all the callsites, you know what I'm talking about:

```js
handleUserCreate(user, data, upsert = true, validate = true, save = false) {
  /* ...75 lines of code with interspersed checks to upsert, validate, and save */ 
}
```

*Usually* (not always), the use-cases they are trying to support can be solved in an easier-to-understand (and thereby, easier-to-maintain) way by pulling apart the building blocks that the different use-cases need:

```js
if (userExists(data)) {
  const isValid = validateUserDataForExistingUser(data, user);
  assert(isValid);
  updateUser(user, data);
  persistUser(user);
} else {
  const isValid = validateUserData(data, null);
  assert(isValid);
  const user = createUser(data);
  persistUser(user);
}
// or whatever
```

It's a hell of a lot more verbose, but it brings to the surface a lot of nuances in the program that weren't clear earlier. This is a good thing- code is more expensive to read than to write, and you'll spend more time trying to understand existing code than writing new code, so optimizing for readability is often wise.

In prettier's case, those nuances might differ from editor to editor, and we might not be the best people to try to write that, since we aren't familiar with those nuances. Because we don't know all the details yet, we are resistant to make a decision that we will regret later.

---

I'm not trying to use an abstract example to shut down this idea, just trying to illustrate why we are concerned about adding options that might be difficult to maintain, and why our preference is to provide composable building blocks for the editor integrators to use.

Even if the editor integrators all have to duplicate logic to achieve it, do we offer the building blocks needed for this use-case? If not, there might be something we need to add. But if so, you might be best off making feature requests to the various editor integrations.

**Comment by lydell** [comment]
What about ignoring _everything_ in .prettierignore?

**Comment by azz** [comment]
Yeah that's an option, just `echo * > .prettierignore`, done.

**Comment by kuba-orlik** [comment]
The .prettierignore option is not optimal, by principle. I imagine that if every code formatter used this as a way to opt-out, our projects would have to have `x` different files that say which formatters they *don't* use instead of just specifying the one they *do*.

Another semi-good solution to this problem would be to have an option for prettier to tell if it can find a config for a given file, then we would have something like

```
prettier --has-config $file && prettier --write $file
```

**Comment by azz** [comment]
You can already do exactly that!

```bash
prettier --find-config-path "$file" && prettier --write "$file"
```

**Comment by duailibe** [comment]
Is there anything else we should do here?

**Comment by thorn0** [comment]
Seems like editor integration users don't have problems with this anymore. Closing.
