### ISSUE TITLE
Globstar only matches 0 or 1 times and is not recursive

### ISSUE THREAD

**Issue by gpeal** [prettier/prettier#2947]
Using [node-glob](https://github.com/isaacs/node-glob) matching, you should be able to do something like `src/**/*.js` to recursively match all js files in a directory because it matches `zero or more times`. However, for me, it behaves like `0 or 1 times`.
I was successfully able to match all js files by doing something like `src/**/**/**/**/**/**/**/*.js`.

@lelandrichardson

**Comment by lydell** [comment]
Most likely, you didn't quote your globs:

```
$ prettier src/**/*.js
```

This means that your shell will try to expand the glob syntax, using its own rules. Your shell probably doesn't support the `**` glob, so it only sees two `*` globs after each other, which is equivalent to just a single `*`. So in effect, you're running this:

```
$ prettier src/*/*.js
```

For example, that could expand to:

```
$ prettier src/views/home.js src/views/product.js src/utils/index.js
```

So Prettier only receives those three file paths and has no chance to do any globbing on its own.

That explains why are not getting a recursive glob.

The solution is easy, and also mentioned in the readme:

> Don't forget the quotes around the globs! The quotes make sure that Prettier expands the globs rather than your shell, for cross-platform usage.

```
$ prettier "src/**/*.js"
```

If my guess at what your problem is turned out to be wrong, just tell me and we'll reopen!

**Comment by gpeal** [comment]
@lydell You are correct :) Thanks for the detailed explanation!
