### ISSUE TITLE
Is there a way to use eslint-plugin-import/order with prettier?

### ISSUE THREAD

**Issue by samlevin** [prettier/prettier#2989]
Prettier disables eslint formatting rules by default. Is there a way to override this to allow `import/order` to sort automatically when running `eslint --fix`?

My `.eslintrc` file:
```
{
  "env": {
    "node": true,
    "es6": true,
    "mocha": true
  },
  "parser": "babel-eslint",
  "parserOptions": {
    "ecmaFeatures": {
      "globalReturn": true,
      "generators": false,
      "objectLiteralDuplicateProperties": false,
      "experimentalObjectRestSpread": true
    },
    "ecmaVersion": 2017,
    "sourceType": "module"
  },
  "plugins": ["flowtype", "prettier"],
  "extends": [
    "airbnb-base",
    "plugin:flowtype/recommended",
    "plugin:import/errors",
    "prettier",
    "prettier/flowtype"
  ],
  "settings": {
    "import/core-modules": [],
    "import/extensions": [".js"],
    "import/imports-first": [ "warn", "DISABLE-absolute-first" ],
    "import/ignore": ["node_modules", "\\.(coffee|scss|css|less|hbs|svg|json)$"],
    "import/order": [ "error", {
      "groups": ["builtin", "external", "parent", "sibling", "index"]
    }],
    "import/resolver": {
      "node": {
        "extensions": [".js", ".json"]
      }
    }
  },
  "rules": {
    "prettier/prettier": "error"
  }
}
```

**Comment by lydell** [comment]
> Prettier disables eslint formatting rules by default.

No. Prettier knows nothing about ESLint at all. Perhaps you are confused by some editor integration or something you use to run Prettier?

There should be no problems at all letting ESLint sort your imports, and Prettier format your code. Can you clarify what your problem is and how to reproduce it?

**Comment by SimenB** [comment]
`import/order` is not fixable, I think you want something like https://github.com/prettier/prettier/issues/2931

**Comment by charlike** [comment]
that's why using blindly the *-config-prettier and -plugin-prettier is a terrible idea.

1. if u use Standard style u just only disable 10-15 rules that are explicitly defined by it (prettier config disable 120+)
2. if u use Airbnb style, there will be 2-3 conflicting rules

such things are the reason why dont use the eslint plugin, because im not sure what other crap may be done there. :)

**Comment by charlike** [comment]
Sorry, typing from phone. With "just only disable" I mean "just only need to". And really, Standard is pretty small config - around 100 rules.

**Comment by azz** [comment]
Those rules are disabled because prettier enforces them, not eslint.
