### ISSUE TITLE
() in chained assignments

### ISSUE THREAD

**Issue by tjvr** [prettier/prettier#2999]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22foo%20%3D%20bar%20%3D%201%5Cn%5Cnvar%20foo%20%3D%20this.foo%20%3D%202%5Cn%5Cnwhile%20(token%20%3D%20next())%20%7B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22%22%2C%22printWidth%22%3A80%2C%22semi%22%3Afalse%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser 
--no-semi
--trailing-comma 
```

**Input:**
```js
foo = bar = 1

var foo = this.foo = 2

while (token = next()) {
}
```

**Output:**
```js
foo = bar = 1

var foo = (this.foo = 2)

while ((token = next())) {}

```

**Expected behavior:**

Is there a reason for wrapping the assignment in parentheses in the latter two cases?
It looks like this was previously discussed in #1321.

Thanks! :-)

**Comment by lydell** [comment]
For the `var` case, I believe the parens are there to show you that only the `foo` variable is decalared. I mean, it is a mistake to do `var foo = bar = 0;` if `bar` wasn't declared before. It _looks_ like _both_ variables are declared, but in reality only `foo` is. `var foo = (bar = 0);` helps explain that. I guess.

For the `while` case, it is a common convention to wrap assignment expressions in unnecessary parens if they appear where you'd normally expect a condition, to make it clear that you actually intend using assignment instead of comparison (and didn't just forget a couple of `=` signs). `while (token === next()) {}` vs `while ((token = next())) {}`.

I think everything works as intended, but I'll leave this open for more contributors to confirm.

**Comment by suchipi** [comment]
I prefer the wrapping to not; it's kind of like a warning, similar to what happens if you do this:

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22(function()%20%7B%5Cn%20%20foo%3B%5Cn%7D)()%5Cn%5Cn(function()%20%7B%5Cn%20%20bar%3B%5Cn%7D)()%3B%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
(function() {
  foo;
})()

(function() {
  bar;
})();
```

**Output:**
```jsx
(function() {
  foo;
})()(function() {
  bar;
})();

```

The fact that prettier prints it this way gives you a hint that you wrote code that the engine will interpret differently than you expected (since you forgot a semicolon). So you fix it before running it, because you realize why it looks weird. This is a good UX. With the assignment operator, it's kind of the same thing: 

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22let%20destroyAllHumans%20%3D%20false%3B%5Cnif%20(destroyAllHumans%20%3D%20true)%20%7B%5Cn%20%20console.log(%5C%22whoops!%20we%20should%20have%20just%20pulled%20in%20the%20three%20laws%20of%20robotics%20from%20npm%5C%22)%3B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
let destroyAllHumans = false;
if (destroyAllHumans = true) {
  console.log("whoops! we should have just pulled in the three laws of robotics from npm");
}

```

**Output:**
```jsx
let destroyAllHumans = false;
if ((destroyAllHumans = true)) {
  console.log(
    "whoops! we should have just pulled in the three laws of robotics from npm"
  );
}

```

So I think the fact that the double-paren stuff looks weird, and forces the user to stop and think about it, is actually providing a better UX than not, because I think this typo made from an assignment operator is more common than normal use of the assignment operator.

**Comment by tjvr** [comment]
Okay. Thanks for clarifying! :-)
