### ISSUE TITLE
Long line-length require statements are awkwardly formatted.

### ISSUE THREAD

**Issue by adrianmcli** [prettier/prettier#303]
It seems that there's no concept of keeping require statements and its params as one unit. It's not very often that you'll get an extremely long string to pass in to the `require()` parens. There should be a preference for keeping the `require('./something')` as one unit.

### If I run prettier on this:

```js
const { one, two, thee, four, five, six, seven, eight, nine, ten } = require('./my-utils');
```

I get this:

```js
const { one, two, thee, four, five, six, seven, eight, nine, ten } = require(
  "./my-utils"
);
```

### When it should be:

```js
const { one, two, thee, four, five, six, seven, eight, nine, ten }
  = require('./my-utils');
```

or:

```js
const { 
  one, 
  two, 
  thee, 
  four, 
  five, 
  six, 
  seven, 
  eight, 
  nine, 
  ten } = require('./my-utils');
```

**Comment by vjeux** [comment]
This is tricky

```js
const { one, two, thee, four, five, six, seven, eight, nine, ten } = require('./my-utils');
const { one, two, thee, four, five, six, seven, eight, nine, ten, eleven } = require('./my-utils');
```

outputs

```js
const { one, two, thee, four, five, six, seven, eight, nine, ten } = require(
  "./my-utils"
);
const {
  one,
  two,
  thee,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven
} = require("./my-utils");
```

It is unclear if we should prioritize breaking on the first part of the expression or on the second one.

If I were to throw an heuristic in this case, it would be to break in the place where there's the biggest amount of code first.

**Comment by jlongster** [comment]
I'd say this is the expected behavior for "normal" expressions. Trying to figure out which one is bigger could possibly done, but we need to be really careful how many combinations of styles we try to detect before performance becomes a serious issue.

Also, I'd prefer for the format to be as consistent as possible. The above case, even if it's slightly awkward in rare cases, is consistent.

What we could do is specialize the `require` pattern specifically. This is what I talked about in [Respecting Patterns](http://jlongster.com/A-Prettier-Formatter#Respecting-Patterns). It's a very common pattern to destructure a large amount of imported properties, so we could specifically break it differently.

**Comment by jlongster** [comment]
Although, I'm actually a little confused. The destructuring param exists before the assigned expression... It should break first no matter what. Did we specifically break the right expression first?

**Comment by vjeux** [comment]
#841 fixes it.

**Comment by adrianmcli** [comment]
Awesome! Can't wait to see it merged in.
