### ISSUE TITLE
How to set PX not to convert to px ？

### ISSUE THREAD

**Issue by zhump** [prettier/prettier#3077]
```
.name{
 width:100PX;
}
```
prettier formatted this

```
.name{
 width:100px;
}
```

But I do not want PX to be converted 。
https://github.com/cuth/postcss-pxtorem#a-message-about-ignoring-properties

**Comment by lydell** [comment]
You'll have to use `/* prettier-ignore */` comments.

**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22a%20%7B%5Cn%20%20%2F*%20prettier-ignore%20*%2F%5Cn%20%20font-size%3A%2016PX%3B%5Cn%7D%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22css%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)
```sh
--parser css
```

**Input:**
```css
a {
  /* prettier-ignore */
  font-size: 16PX;
}
```

**Output:**
```css
a {
  /* prettier-ignore */
  font-size: 16PX;
}

```

In my opinion, postcss-pxtorem is doing the wrong thing. Instead of taking standard CSS as input, it is taking an arbitrary superset of CSS as input (not treating units case insensitively), which of course will cause problems with other tools that expect to be able work with standard CSS.

**Comment by azz** [comment]
I doubt we'll be making changes to workaround the limitations of another tool. Your best bet is to raise this with `postcss-pxtorem or use `/* prettier-ignore*/` comments.
