### ISSUE TITLE
don't include semi in JSX only code blocks in markdown 

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier#3196]
I'm using prettier with a project that uses react styleguidist to document components (docs here: https://react-styleguidist.js.org/docs/documenting.html)

when including just JSX in a codeblock it would be nice if prettier would exclude the leading (or following depending on your `--no-semi` setting) from the output

**Prettier 1.8.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADdArAzgHSgHgCEBXGGaAPgBsBDAIzivwHoSzK91UQAaECAA4wAltCzJQNLDGQAzGlSxw+dAE40wAazgwAygI3CoAc2QxVxZSAAmEMHIVK+2AB6F1WnbpoBbOABkjOAdFKwhSAVIAJhCnEANVJVVkEB8aVU1bAHcoXnjVIxgAdWFrGAALZAAOAAY+JR9hWKssI2MqOABFYgh4Zr4YehKyyqQogfVhKjaAYQgfNJSoaGC+YiUAFXpxJHlQgF99oA)
```sh
--parser markdown
--no-semi
```

**Input:**
````markdown
```js
<Button>label</Button>
```
````

**Output:**
````markdown
```js
;<Button>label</Button>
```

````

**Expected behavior:**
````markdown
```js
<Button>label</Button>
```

````

**Comment by azz** [comment]
I think this is a little more general. Do we want to detect when the code snippet is a single expression (i.e. not multiple statements), then omit semicolon accordingly?

**Comment by suchipi** [comment]
I guess the question would be if there are any situations where a user writes a single expression for which omitting the semicolon would be undesirable. I can't think of any off the top of my head.

**Comment by sapegin** [comment]
So do we have any conclusion here? Is this something you’d like to change? For both semi / no semi options?

**Comment by duailibe** [comment]
I believe it's something we want, but there's no one actively working on it to flesh out the details on this behavior (and of course, implement it later).

**Comment by suchipi** [comment]
Maybe this should be framed as a bug? Namely, when using no-semi, we shouldn't put a defensive prefixing semicolon in front of the first statement in the program.

I guess that could break stuff for users who are concatenating scripts together, though...

So maybe it should be:
When using no-semi, and the program is within a markdown code block, don't put a defensive prefixing semicolon in front of the first statement of the program.

But it'd be kinda annoying if you had single-JSX-element blocks interspersed with normal code blocks, and you wanted to use semicolons in the normal code blocks. Because you'd need no-semi just for the JSX element blocks, but you'd want it elsewhere...

So maybe we should special-case "markdown block whose program contains only one statement which is an ExpressionStatement whose expression is a JSXElement" specifically

**Comment by lydell** [comment]
@suchipi This isn't specific to the first statement of a program; it applies to _any_ statement starting with JSX. And it's not about concatenating scripts, it's about letting people move the line, or add new lines, without having to think about ASI. See https://github.com/prettier/prettier/issues/1433#issuecomment-297633655.

I do understand that it looks strange in documentation, though. It's a very tricky case, with no obvious solution. I guess we'll find one after some more discussion, though.

**Comment by lydell** [comment]
I think we may have gotten stuck a bit too much on the leading semi-colon, though. If you re-read this bit of the OP:

> when including just JSX in a codeblock it would be nice if prettier would exclude the leading (or following depending on your `--no-semi` setting) from the output

… you'll see that the actual request is to get rid of the semicolon _regardless of the what the semi option is set to._

In other words, the markdown code block is intended to show off just an expression, not a whole program. I guess the OP would want this expression without semicolon as well:

``````md
```js
1 + 2
```
``````

However, Prettier can't know the intention –  did the user intend to show just an expression or a whole program? We _could_ simply omit semicolons when there's just a single expression in a markdown code bloc, but then I'd bet we'd get issue reports about missing semicolons in those cases.

**Comment by suchipi** [comment]
@lydell I meant that we could treat "first statement" differently than other statements, so it would be a bug in the "first statement" case. I don't think that's the right approach after thinking it over, though.

Good to know about the editor story for moving lines around; hadn't thought about that.

Since this issue is about improving the experience when using react-styleguidist, I think the right approach is to omit semicolons when there's a single JSX element expression in code blocks (but not other kinds of expressions).

**Comment by suchipi** [comment]
To clarify- let's remove semicolons regardless of the semi option in that case, per @lydell

**Comment by lydell** [comment]
Spec:

Don’t output semicolon before or after a single ExpressionStatement inside a markdown code block, regardless of the `semi` option.

I think that will solve the problem. And if somebody complains about a missing semi-colon in that case, we’ll deal with that then. That’s a less worse problem to have than this issue.

**Comment by lydell** [comment]
A workaround for now could be to mark the code blocks as json:

````markdown
```json
<div>test</test>
```
````

That probably has other side effects, though.

**Comment by suchipi** [comment]
Why not:

Don't output semicolon before or after a single [ExpressionStatement whose expression is a JSXElement] inside a markdown code block, regardless of the semi option.

That would reduce the scope for the potential future "somebody complains about a missing semi-colon" case, and would solve this issue.

**Comment by lydell** [comment]
Yeah, that's also an option. Not sure what's best.
