### ISSUE TITLE
Support JSON file formatting?

### ISSUE THREAD

**Issue by ryancole** [prettier/prettier#322]
Not sure if it's a long shot or not, but would adding `.json` formatting be out of scope? Would it be difficult to add?

**Comment by vjeux** [comment]
for json formatting, I would recommend using `JSON.stringify(JSON.parse(file), null, 2)`. I don't think it needs its own project like prettier.

**Comment by lydell** [comment]
Shameless plug: https://github.com/lydell/json-stringify-pretty-compact

**Comment by vjeux** [comment]
@lydell that's even better!

**Comment by jlongster** [comment]
Agreed, JSON does not have types like functions or binary expressions and so a simpler formatting (that doesn't need the constraint-based solver here) works.

Although, I can see the case for wanting to use the same editor plugins to be formatting your `package.json` as you write it. The core issue is the top-level `{` problem. We'd need to disambiguate top-level blocks and force them into JS objects, which means we won't allow top-level objects.

Or we could check if the filename ends in `json` and special case it.

I can see the it being annoying typing cmd+alt+f (or whatever in the rest of your project) but not being able to in JSON files.

**Comment by ryancole** [comment]
Yea. That is what prompted me to throw this question out there. I was editing package.json and .eslintrc.json, etc, and found myself hitting format.

I can understand that there are likely many other ways to already format JSON via editors, though. It'd just be a question of whether or not it's low hanging enough for prettier to add or not. *shrug*

**Comment by jlongster** [comment]
I think it's a valid question, and makes sense in that workflow.

**Comment by sholladay** [comment]
My favorite lib for this is [json-align](https://npmjs.com/package/json-align). It has an API and CLI and has the prettiest output if you ask me. Would love to see something like that from `prettier`.

Since people are mentioning `package.json`, it's worth noting that there are some major caveats to formatting `package.json`. Any time `npm` touches `package.json`, it reformats it to its own liking. So you will end up with a war between `npm` and `prettier`. If you're not careful, you will end up with very noisy, unclear commit diffs. Such situations can [cause a lot of frustration](https://github.com/gruntjs/grunt/pull/1301). It is generally best to [let npm do its thing](https://github.com/sindresorhus/cat-names/blob/master/.editorconfig#L12) until someone can convince them to [respect its formatting](https://github.com/npm/npm/issues/5694).

**Comment by vjeux** [comment]
I'm going to close this as it is out of scope for prettier as it stands right now.

**Comment by thibaudcolas** [comment]
In case anyone stumbles upon this while trying to solve the formatting conflict in `package.json` between Prettier and npm, Prettier now supports [ignoring files](https://github.com/prettier/prettier#usage) 🎉 .
