### ISSUE TITLE
Template literal expression breaks make simple cases hard to read

### ISSUE THREAD

**Issue by nevir** [prettier/prettier#3236]
The expression line breaking behavior introduced in #3124 makes template literal wrapping hard to read for simple cases.  

For example, when generating error strings for exceptions or messages to log out, it's very common to include several values for context.  The new wrapping behavior formats the string by breaking on some expressions (e.g. the closest to the end of each line), and not others.  It makes it really hard to read such strings.

_Suggestion: Introduce a heuristic on the behavior, where it only breaks on expressions of sufficient length and/or complexity, otherwise it performs string concatenation._

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWAnCB3ABFOPAUQywwAoADAFTQEMZd0BLKAc1wE8IBXXAE2b9c2ZulwASYADNmALzkBfAPy5cAOQiM2ECPwCEagJq9cAayg4ANEzRxc0e6PFTpuxTakAjOhkW46KGFvOiVVXCM4OjQbMQByAGdbJyx2Jk4AB3sIaUlgFnZ-ZzRcBJgeaVzA4QK2BIA6SgBKAG4AHSgQKxAIDJhmaATkUDoy5Gk6ABsEuG6vDDowMzgYAGUMxdY2ZBgMHlmQfggwcamZ7tYZjBgABQW2AFs6U+mDgCsEgA8AIQWlldWdAecAAMqw4C9zj0eDAMjCAEyQg4bDBXZAgHxeTiTaBdEAZDCsGAAdSE6GQAA4AAzdAkQGbEhYZHZ7A4YOAARx4zHZdzoj2eSAmr26MwezBZ+1FW0mcAAijwtBChWcDjA6F5SfxyUh4d1dnRmJMtgBhCAPJ7oywEPE8GbUDVDFWvRSKIA)

**Input:**
```jsx
throw new Error(`That thing you did with ${fizz}?  Not good!  You know, the one with ${foo}, ${bar} and ${baz}?  Yeah, it's the wrong type of ${thing} with stuff and things.`);
```

**Output:**
```jsx
throw new Error(
  `That thing you did with ${fizz}?  Not good!  You know, the one with ${
    foo
  }, ${bar} and ${baz}?  Yeah, it's the wrong type of ${
    thing
  } with stuff and things.`
);
```

**Expected behavior:**

For cases with simple expressions like this, doing concatenation style line breaking is _much_ more readable:

```jsx
throw new Error(
  `That thing you did with ${fizz}?  Not good!  You know, the one with ` +
  `${foo}, ${bar} and ${baz}?  Yeah, it's the wrong type of ${thing} with ` +
  `stuff and things.`
);
```

**Comment by duailibe** [comment]
Hi there. Thanks for report.

First of all, changing a template literal to a string concatenation will never happen on Prettier because one of the core principles is to never change the AST (see: https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about)

As for the breaking, I'm not sure there's any other way to break this template literal. So you'll either have to change it to string concatenation manually or leave it in a single line using `// prettier-ignore`

Closing this since there's not much we can do but feel free to comment if you think there's something else to add!
