### ISSUE TITLE
Template strings with awkward line breaks

### ISSUE THREAD

**Issue by ismail-syed** [prettier/prettier#3280]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEaIFs4CqATgDYAqAFgIYwCSaAMtAOaYC8mABhTDAA5okAeiE58lAJZRmAOhjU6jFjMi4hCACZ8IUmEIAkwAGYQIAXyEB3CgE9KEAK7MKB4ACMqRCxIDicOjAAQg4wAOq2nADcADpQIAA0IBB8MBLoyKBUGMhGVCRocIluRFRgANb+AMp8pVLMyDBEDoUgGhBgOXkFiVIFRDAACiXMuFSd+S0AVmgAHoEl5VVU+AxScOPdSSF8IQBMGy01RH3IIB5uNiTQCSB8RLqhEhryyAAcAAyJdxAFoSV8DSaLSIcAAjg4JCChlQRmMkLkJokCrgJIDmki6iQ4ABFBwQeAHRIwKhuR7PCjIXZEkoSEh1ADCeFGpyg0HWiQcBTIJLQBzMZiAA)

**Input:**
```jsx
const someUrlThatIsLong = `https://someThing.thatIsLong.com/endpoint/${foo}/whyThough/${bar}/iGetItButWhy`;

```

**Output:**
```jsx
const someUrlThatIsLong = `https://someThing.thatIsLong.com/endpoint/${
  foo
}/whyThough/${bar}/iGetItButWhy`;

```

**Expected behavior:**
This doesn't feel right. Is this a side-effect or intentional?

**Comment by duailibe** [comment]
It's intentional, this is a template literal so we either break inside the expressions (i.e. between `{` and `}`) or don't break at all. The only other option is to change this to a string concatenation, but we won't it (that would change the AST, see [rationale](https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about), you'd need to do it manually.

I'm closing this because there's nothing we can do here, but thanks for the report and please comment if you think anything was not addressed.

**Comment by SimenB** [comment]
Fwiw, I'd _really_ prefer not breaking, it's much harder to read. I'd maybe understand it if there were a lot of function invocations or member expressions, but for simple cases like this prettier makes it way worse. The only places at work we use `prettier-ignore` is above template strings. 

Btw, the thing about not changing ast is not mentioned in the link. Prettier also changes the ast already for jsx, so not really sure it's such a big deal

**Comment by duailibe** [comment]
Yeah, template literals are really hard to get it right. There are cases you want to break, there are cases you maybe doesn't want to. In this case, I can understand how this case is better to not break in the OP, but not the case in #3286. So perhaps we should never break if the expression is an identifier? With this change, I can see this diff:

```diff
- const long = `long ${a.b.c.d.e} long longlong ${
-   loooooooooooooooooong
- } long longlong ${loooooooooooooooooong} long longlong ${
-   loooooooooooooooooong
- } long long`;
+ const long = `long ${
+   a.b.c.d.e
+ } long longlong ${loooooooooooooooooong} long longlong ${loooooooooooooooooong} long longlong ${loooooooooooooooooong} long long`;
```

I'm not opposed to this change but I have no preference either way. :-) 

As for not changing the AST, you're right it's not explicit in that link, but above in the same page it says something about correctness: https://prettier.io/docs/en/rationale.html#correctness

**Comment by suchipi** [comment]
Not breaking when the expressions are just identifiers sounds good to me. It'll also (probably) fix this:

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEATOBnMAnAlgIzgAoADDCAWzgAJUBPKAQwtzEYBt27qB3PGeFGrwMMamww0YAC0ZjZGao2oA3ONm7toAc2pMqSqKiXty1aDQgAzagBJgMzHAC+JADTUiASmoBeAHzUwAA6QtS4METBILiKPHC42MZaEADWuFC6eNrSYlAQPNFeANyhziWhIG4gEAAOMLjQGMigjKLIVhyS1fjYjGCpcDAAyrX9GdrIMNgArnDVqBBgHV3zMVCS2DAACn3aFIwrpmsAVhgAHgBCfQNDw8xwADIZcEfdNTMwtZ8ATG9rY2wm2QIHwjHwdC0UCqIFqeFgAHVcKgZMgABwABmqcIgkgRfVqU1ma2wcAAjjNEnBdox9ockJ1jtVJCwiXNmRN2HAAIozCDwf7VGDgpEo6TIH5Cvq4dgTADClAOIPyUFe1RmkgAKuDmgzVs5nEA)

**Input:**
```jsx
describe(`some dynamically written test case that has a very long name and also one of ${these}`, () => {
  it("is weird looking right now");
});

```

**Output:**
```jsx
describe(`some dynamically written test case that has a very long name and also one of ${
  these
}`, () => {
  it("is weird looking right now");
});

```

There are also probably other "simple" expressions that we can choose not to break on, that we might find more of over time.

**Comment by suchipi** [comment]
Also re: changing the AST... it's always felt scary to me that we change the AST with JSX, but in practice, it seems to always do what people want it to. But I think part of why is because we know
what JSX is used for, and because HTML collapses whitespace. For template literals, we can't always know that, but we can *sometimes* know it:

**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGBPANnAJgOgBEBLANwANIsIAnJABzgEMwALegVwDMuBuAAkGCARiwDWAcxoQOUXAFoqtBk3pMMTAO6ti9XuRAAaEBHoxi0VMlBN0yLkyyo4x4TXFwYAZTVhiUCWQYGg4XEFwIMHtHZ2N-ZxoYAAV3CQBbJminMIArVAAPACF3MDFPLyY0uAAZfzgs2JMOGE4YACYGsLUaBOQQUWFsaCMQehp-GAB1YlwYVmQADgAGYzGIZ0n3eiCQsJo4AEcOYn2UpnTMpAds42c04h3Q2-8JHABFDgh4TuMYJmFprN5kg2r93MQsC8AMIQNIZPpQaD1YwcZwAFX+ViuMTgAF9cUA)

**Input:**
```jsx
styled.Div`color:peachpuff;     background-color:papayawhip;`
```

**Output:**
```jsx
styled.Div`
  color: peachpuff;
  background-color: papayawhip;
`;

```
So maybe there are as-of-yet uncovered common tagged template strings that we can handle better.

(Also, this technically changes the AST from a JS perspective, but not from a multiparser perspective)

**Comment by duailibe** [comment]
> There are also probably other "simple" expressions that we can choose not to break on, that we might find more of over time.

Actually we are only breaking now for identifiers, member expressions and conditional expressions:
https://github.com/prettier/prettier/blob/cbed0f487f2f69b8f8a70ba73ec7115762556cfb/src/printer.js#L1990-L2000

**Comment by brentonklassen** [comment]
Breaking template strings into multiple lines is actually breaking pages in Facebook Messenger webviews

**Comment by suchipi** [comment]
@brentonklassen are you sure? we only add newlines around the expressions, within the `${}`. That should have no impact on code. Could you post an example of working unformatted code and non-working formatted code?

**Comment by brentonklassen** [comment]
@suchipi Ah, you're right, where you broke the lines is fine (in the variable expression) - the issue was with other line breaks not added by prettier - sorry for the false alarm.
