### ISSUE TITLE
Incorrect indentation with tab width = 4

### ISSUE THREAD

**Issue by rizoom** [prettier/prettier#3285]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAzTBeTAQwCdj8A+I0zAfiuIDoBbQgBwAp2BKCzYAHSiQoGTBjIEA5AHdi0AOaYAllAAmCLCswwAFkrSYARgBsIYANaSA3IOJwYAV2JQxMYjagBfHkkxQHxsZWIAA0IBCsMEroyKCEGMjYhMZocGGGxIQW9gDKrFkq8shuDmkgqmaJyalhKqnEMAAKmfIsVSllAFZoAB4AQpnZMDmETHAAMipw7TXhDjCs8wBMM2X5xPXIINim0qEgrMQqMADqSqq6yACMSwAMYYcQqSeZrMXEpWF2AI4OSnbNQitQirMKpJhKd6fEBoQrGOAARQcEHgoJAMEIhjOFx0yAALGE3IQlMZCgBhCBMNooZLGfYOVIAFUxaFWnk8QA)
```sh
--parser flow
--print-width 120
--tab-width 4
--trailing-comma all
```

**Input:**
```jsx
const f = arr => arr ? arr.map(() => {
const str = 'wrong indent in this block';
return str;
}) : null;
```

**Output:**
```jsx
const f = arr =>
    arr
        ? arr.map(() => {
              const str = "wrong indent in this block";
              return str;
          })
        : null;

```

**Expected behavior:**
Tab width is set to 4. The "wrong indent block" should be indented with 12 (or 16..?) spaces but we get 14 spaces.

Not sure about the expected result but my eslint complains (thus cannot pass my internal CI) :  
> ESLint: Expected indentation of 12 spaces but found 14. (indent)

**Comment by lydell** [comment]
This is expected. Prettier uses two spaces to align stuff inside the ternary on top of the regular indentation. (I don't like it personally, but that's the way it is, and, I believe, has always been).

Regarding ESLint, the recommendation is to turn off all rules that are unnecessary or might conflict with Prettier, such as the `indent` rule. It doesn't give you any benefit when using Prettier (the opposite, really). See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier) for more information.

If the ESLint issue is your only problem, please close this issue. Otherwise, this would need discussion. I don't think this is something that would be changed at this point. There must be previous discussions about this somewhere, but I couldn't find it right now.

**Comment by rizoom** [comment]
Thanks for these explanations.
I was already using _eslint-config-prettier_ as recommended but I didn't saw all the information in the repository. I'll look into it.
