### ISSUE TITLE
Single-line comment moved to next line

### ISSUE THREAD

**Issue by gnapse** [prettier/prettier#3294]
**Prettier 1.7.4**
[Playground link](https://prettier.io/playground/#%7B%22content%22%3A%22if%20(somethingGoesWrong)%20%7B%20%2F%2F%20Why%20this%20comment%20goes%20to%20the%20next%20line...%5Cn%20%20console.error('Something%20went%20wrong')%20%2F%2F%20...but%20this%20one%20doesn't%3F%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22ast%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%2C%22jsxBracketSameLine%22%3Afalse%2C%22output2%22%3Afalse%2C%22parser%22%3A%22babylon%22%2C%22printWidth%22%3A80%2C%22semi%22%3Atrue%2C%22singleQuote%22%3Afalse%2C%22tabWidth%22%3A2%2C%22trailingComma%22%3A%22none%22%2C%22useTabs%22%3Afalse%7D%7D)

**Input:**
```jsx
if (somethingGoesWrong) { // Why this comment goes to the next line...
  console.error('Something went wrong') // ...but this one doesn't?
}

```

**Output:**
```jsx
if (somethingGoesWrong) {
  // Why this comment goes to the next line...
  console.error("Something went wrong"); // ...but this one doesn't?
}

```

**Expected behavior:**

I suspect there's a reason for this, and that it is not an accident or considered a bug, but I raise this issue cause I'd expect the same treatment for both single-line comments.

**Comment by dperetti** [comment]
Was about to report the same issue.
It can be very annoying if you use some kind of marker in a comment, like a TODO that's specific to a line.
A comment should definitely remain on the line where it was set !

**Comment by duailibe** [comment]
@dperetti That unfortunately is not an easy task because the line the comment is in may not exist after Prettier reformats your code so our solution is to attach every comment to an AST node. That works very well for most of our cases except the ones we don't have one to attach to. For this case, we don't know if we should print the comment between `) {`, after `{` in the same line, or in the line below because they are all the same node, unless you resort to inspecting the original code in the printing phase.

It's a hard problem and we are tracking it on #807 so I'm closing this issue.
