### ISSUE TITLE
jsx multiline prop spacing

### ISSUE THREAD

**Issue by VinSpee** [prettier/prettier#3310]
**Prettier 1.8.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UGOh+MYANgIYDONAclQLZwC8+IpMZAYhQB4BzABQBGAJRcyAEWEAzSVDJkAEmIAM6gKSLlnKASgACI3IgRCqAPRY8pIra6VaDZm2AADKTD5Cxu7hhZBW81UU0dLg8AX0JDEzMLIhscQ2tbXBAAGhAIAAcYTGgaZFBaGGQ5KgoaOByAIwAnKjAAazgYAGU8lswoQWQYRoBXOpB0CDBK6tqcvtrGmAAFZsEmKmmasYArGn4AIWa2js63ABk+uE3Z3OGYPLuAJmuxnsaF5BB6qnqATwpoNkQHlGn0YAB1TDoGAAC2QAA51DkQRBauDmnlBiMxo04ABHYaYXErKhrDZIKpbHK1JiYLGjal9QQUOAARWGEHgLxyMB+kOhcKQjx5zUwFCZAGEIEx1p8oNArjlhrUACo-EoUmZwaLRIA)

**Input:**
```jsx
<div>
<div
	className="
		Flxg(1)
		D(f)
		H(100%)
	"
>
  foo
</div>

<div
	className={`
		Flxg(1)
		D(f)
		H(100%)
	`}
>
  foo
</div>
</div>
```

**Output:**
```jsx
<div>
  <div className="
		Flxg(1)
		D(f)
		H(100%)
	">foo</div>

  <div
    className={`
		Flxg(1)
		D(f)
		H(100%)
	`}
  >
    foo
  </div>
</div>;

```

**Expected behavior:**

Hi!

I would expect these `className` props to retain their spacing as entered.

Am I missing something?

**Comment by duailibe** [comment]
Hi, thanks for the report. Prettier doesn't do this kind of alignment because it would be too complex to handle this kind of stuff and it's really arbitrary (I have never seen this kind of alignment before), we chose to support the most common style of things.

See those issues for similar feature requests: #188, #350, #1622, #3062
