### ISSUE TITLE
Ternary: Turn of formatting for JSX and use JS instead?

### ISSUE THREAD

**Issue by Franatec** [prettier/prettier#3366]
When writing jsx Prettier formats ternary operators with unnecessary parentheses as follows:

```
{collection ? (
  <ProductComponent collection={collection.hero} type={'hero'} />
) : (
  <SectionLoading />
)}
```

Following a number of posts I can see where these decisions have been made - there's obviously been plenty of back and forth. However, in standard JS mode the formatting is closer to what I would personally prefer:

```
{collection
  ? <ProductComponent collection={collection.hero} type={'hero'} />
  : <SectionLoading />
}
```

Is there a way I can force prettier to use the latter, JS, formatting instead of the JSX formatting?

**Comment by duailibe** [comment]
As you said already we've been back and forth on this subject and I don't think we're gonna change it at this point. I'm afraid your options are:

- use `// prettier-ignore` to prevent prettier formatting it at all
- run `standard` after `prettier` (see https://github.com/sheerun/prettier-standard)

Closing this since I don't think there's anything we can do here. Feel free to comment if you think something was not addressed.
