### ISSUE TITLE
[Idea] Integrate Prettier into diff tool

### ISSUE THREAD

**Issue by JCB-K** [prettier/prettier#3435]
While staring at a diff partially generated by Prettier, I came up with an idea. I generally don't care about the diffs that Prettier generates: they're stylistic, and as such don't need to be reviewed manually. So if I change something in my code that triggers a style change (e.g. add an argument to a function so that the line is longer than printWidth), I want to only focus change that *I* made, not the change that Prettier made.

Would it be possible to hook Prettier into a diff tool, so that what you're diffing is based on the AST rather than the textual representation of it? Practical example:

Before: 
```diff
- foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis());
+foo(
+  reallyLongArg(),
+  omgSoManyParameters(),
+  IShouldRefactorThis(),
+  isThereSeriouslyAnotherOne()
);
```

```diff
- foo(reallyLongArg(), omgSoManyParameters(), IShouldRefactorThis());
foo(
 reallyLongArg(),
 omgSoManyParameters(),
 IShouldRefactorThis(),
+ isThereSeriouslyAnotherOne()
);
```

This seems very complicated, and might not even be compatible with the way diff tools work. But I wanted to bring it up since the potential is pretty cool.

**Comment by duailibe** [comment]
Take a look at: https://github.com/josephfrazier/prettier-diff

**Comment by josephfrazier** [comment]
Yep, this is essentially what `prettier-diff` tries to do! It's not clever enough to insert line breaks before/after changes in order to isolate them from the rest of the code, but you can fake it by decreasing `--print-width`. Compare the following:

* [`--print-width=80`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUAnOBDAGwIE8AZaAcwEFsLMBKAGgAIIBbCgZQgFk8piABTzY8bOPGwBnBiwCSnABYQArgQAmAJTio8YGBGwAVRQEsZ9egG4AOlDvosuQiXJRqtWaw7c+A4aLikhbySqoa2rr6hibmXuYmcLicSaaqUiRUUBAwikkA8lBwDNYgjCAQAA4waVBSyKAi2BAA7gEI9ShlIHhSMMi6BFJw5QBGomAA1hKclXqm7sgw2CojIOoQYAOEw+ULw9gwgqIUbHjbQ2sAVlIAHgBCE9MwnGJwpAtwF7sVKjCVfwATN81nNpElkCBRnhRsQCNBupVsAsYAB1UzqXLIAAcAAZykiIMNUaJKpCkXADgA3L7lXAARxUplwxzwp3OSEGP2GbFMSxWaykCwoBDgAEUVDkvpydmsYDD0ZjFMhAeVlnhTARhQBhdhnSHZIrdFTDIwwzpcuAAXytQA)
* [`--print-width=0`](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAUAnOBDAGwIE8AZaAcwEFsLMBKAGgAIIBbCgZQgFk8piABTzY8bOPGwBnBiwCSnABYQArgQAmAJTio8YGBGwAVRQEsZ9egG4AOlDvosuQiXJRqtWaw7c+A4aLikhbySqoa2rr6hibmXuYmcLicSaaqUiRUUBAwikkA8lBwDNYgjCAQAA4waVBSyKCV2KawAOqm6rnIAAzlMHgARu2disgATOVSLRQEcACKKjlwyLoEUnB9oqYE0wDC7Gx4yCDZRWUgA6JgANYSnJV608gw2CobIABWUgAeAEJXtxgnDEcFILWWSFW63KD2kSWOA0GxAI0HO6zYpmer3eKnWRkG9UhhGhIBa62wMEEogohxWxPeuAAjipTLgqXgaUciWt3k0IOtWqJKscmnByQA3ZblETYCAAdwCCEJIHO6ggYDpPOlUhgmpJqhglRUMDGergAF9zUA)

**Comment by duailibe** [comment]
I think there's no much we can do so I'm closing this. Pleas comment here if you think something was not addressed.

Thanks!
