### ISSUE TITLE
Can we enable the dangling comma on this project?

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3469]
Because even though one line was added, two were deleted and that's confusing when reviewing.

<img width="312" alt="screen shot 2017-12-13 at 11 39 30" src="https://user-images.githubusercontent.com/125676/33931987-5dfa3784-dffa-11e7-8193-6ba1e881638d.png">

Also if you would like to sort them, you would have to manually add the missing comma, because the there will be a syntax error if the last item will move in the middle.. (if someone will mention that these things are handled by Prettier 😃)

More reasons can be found here: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by azz** [comment]
Prettier should probably use Prettier's defaults...

**Comment by lipis** [comment]
That's what I thought.. but not really.. :) The default I guess comes based on popularity or what people wanted in a first place, but the world is evolving and maybe we can _teach_ them the _right_ way :P

Also if it's a hard requirement for this project to use the default values, let's change the default value :D Either case, having the dangling comma has more  pros than cons..

**Comment by bakkot** [comment]
Please don't change the defaults without making a major version bump.

I don't see much reason for Prettier to always stick with the defaults, though, except those reasons that would apply to any other project (e.g. "use prettier's defaults" is the easiest rule which minimizes style bikeshedding).

**Comment by lipis** [comment]
No I don't think that changing the default is the way to go.. Like I already mentioned.. there is no real need for Prettier to use the default.. we can adjust to what we want for the project.

**Comment by duailibe** [comment]
Trying to make it clear: @lipis wants to change the Prettier settings we use for the Prettier codebase (i.e. only an internal thing)

**Comment by lipis** [comment]
Yes! I (hopefully more) want to enable the following:

```yaml
trailingComma: all
```

**Comment by azz** [comment]
We certainly can't set it to `all` because we support node v4. 

Prettier should be configuration free by default. Running Prettier on Prettier with Prettier's own defaults seems like it has more advantages. Don't want people to look at the Prettier source as an example and think that a config file is required.

**Comment by josephfrazier** [comment]
> We certainly can't set it to `all` because we support node v4. 

For what it's worth, [node v4 will become EOL in April](https://github.com/nodejs/Release/tree/593a133b76fb8803b055716fd3aab7026a6cdf78#release-schedule), so I imagine this might not be a blocker at that point.

> Don't want people to look at the Prettier source as an example and think that a config file is required.

I'm not sure about the context of this, but Prettier did have it's own [`.prettierrc`](https://github.com/prettier/prettier/pull/3224/files#diff-f2e285fb35cc9694564cb6d2af099ad2) for a couple of weeks recently. This repo also has a `.eslintrc.js` that references prettier's rules. I'd (like to) think that new users would go to the website for guidance on how to get started with Prettier, rather than looking at this repo, especially since the README now links to the website instead of having the docs inline.

---

In general, I agree with @bakkot [above](https://github.com/prettier/prettier/issues/3469#issuecomment-351627493): we shouldn't change the defaults without a major version bump, but I don't see an intrinsic reason why Prettier itself should use them. On the other hand, the benefits of trailing commas are pretty well-described (as in [the OP](https://github.com/prettier/prettier/issues/3469#issue-281684439), for instance).

**Comment by lipis** [comment]
Prettier is already using the `proseWrap: never` instead of the default `preserve` :)

**Comment by ikatyang** [comment]
FYI, we changed back to use the default in #3395.

I don't mind to enable `--trailingComma es5` at this point, but using the default can avoid something like #3385 as we often test issues via `bin/prettier.js` and forgot we have a `.prettierrc` 😂.

**Comment by josephfrazier** [comment]
> I don't mind to enable `--trailingComma es5` at this point, but using the default can avoid something like #3385 as we often test issues via `bin/prettier.js` and forgot we have a `.prettierrc` 😂.

Those are good points: we could use "es5" as a way to have more trailing commas without losing node v4 compatibility; and having a `.prettierrc` complicates testing because the tests aren't isolated (I also encountered this problem in https://github.com/prettier/prettier/pull/3255#discussion_r154636388).

However, since we're using `eslint-plugin-prettier`, we can just put the `trailingComma` rule in `.eslintrc.js` without affecting the behavior of `bin/prettier.js` on files in the repository. PR coming shortly :)

**Comment by azz** [comment]
Don't use eslint-plugin-prettier's config, that should be considered deprecated as it breaks formatters like Prettier-VSCode and Prettier-Atom which use the `resolveConfig` API.

**Comment by azz** [comment]
I honestly think this is complete bikeshedding. I personally prefer trailing commas but that's not the point. The very reason this project exists is to remove discussion about code style, and this issue is doing the exact opposite on Prettier's own source code. Changing Prettier's own formatting to something that **isn't ** the default **will ** cause more discussion in other projects adopting Pretter. "Should we use the defaults or use Prettier's settings?"

**Comment by bakkot** [comment]
Alternative proposal: do nothing for now, and then when Node 4 hits EOL, change the default to `all` and do a major version bump. It sounds like we're mostly agreed that trailing commas are the right way to go, and that we want people to be able to use prettier and get good output with no configuration, so... that would be the right default, yes?

Downside is that it would mean people writing untranspiled code for non-current browsers and Node would start needing to configure prettier. And the major version bump, of course.

**Comment by azz** [comment]
Going to close this and recommend discussion in #3503
