### ISSUE TITLE
Support XML/HTML/SVG

### ISSUE THREAD

**Issue by alexkuz** [prettier/prettier#3491]
Not sure if it counts as a bug since prettier doesn't actually support XML formatting (or does it?), but still would be nice to fix. Or at least avoid unsupported file formatting. Came across it by (irresponsibly) running prettier on all source files, where it broke all SVGs:

**Prettier 1.9.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAFjAtgGwHwA6UABKWeeRnAIYAmhJZAzrdQGZ1Nu1NGmoB6dDXpFBmXHhAAaEBAAOMAJbQmyUNQBOmiAHcACloRqU1AG4QltGSGpMYyDjiZxZAI03UwAazgwAyvJeSlAA5sgwmgCuriC0EGCO1M6xIS6aMPqeoVjUSSmyAFZMAB4AQp4+fv7UWHAAMiFw+S6yEFEw8h0ATC2xQZrpyCBu1G4AnjjQNvKaITAA6lYw6MgAHAAMsrMQLgue8sOzcOlmzbKacACOUUqXWdQ5eUhOrSAuWEoR0bFMIaE4OAARSiEHgfVkMDGS1oK2Q3UhniUOH+AGEIFhcsMoNBziAoi4ACpjEyvOAAX3JQA)

**Input:**
```html
<html>
              <head>
    sdafadsfds
  </head>
</html>
```

**Output:**
```html
<html>
  <head>sdafadsfds</head>
</html>;

```

**Expected behavior:**
```html
<html>
  <head>sdafadsfds</head>
</html>

```

**Comment by alexkuz** [comment]
Sorry if I duplicated some issue, don't have time right now to read into other issues carefully :)

**Comment by ikatyang** [comment]
Prettier currently does not support HTML, and it's tracked in #1882.

The reason why there's an additional comma is that it's treated as JSX since the default parser is `babylon`, we have considered to remove the default parser to avoid confusing but unfortunately it'd be a breaking change, see #2884 for more info.
