### ISSUE TITLE
Shall we install dependabot to stay up to date with the dependencies?

### ISSUE THREAD

**Issue by lipis** [prettier/prettier#3582]
We are using [dependabot](https://dependabot.com) all over at [Wire](https://github.com/wireapp) and we are happy with it ([example](https://github.com/wireapp/wire-webapp/pulls?q=is%3Apr+label%3Adependencies+is%3Aclosed))

Once installed of course there will be bunch of new PRs for every outdated dependency, but over time everything will be fine.. For every PR if there are more things to take care of, we can easily make changes there, otherwise dependabot is smart enough to rebase, so all the tests will run again if master is updated.

Here is a screenshot of the outdated dependencies for the minor version..
<img width="528" alt="screen shot 2017-12-26 at 17 30 10" src="https://user-images.githubusercontent.com/125676/34359871-37a02ea8-ea64-11e7-8148-d1e4b8b9e96a.png">

WDYT?

**Comment by ikatyang** [comment]
If we're going to use bot to keep dependencies up to date, I'd recommend [renovate](https://renovateapp.com/) ([example](https://github.com/pulls?utf8=%E2%9C%93&q=user%3Aikatyang+author%3Aapp%2Frenovate)) as it can be configured to auto-merge specific semver level for specific package.

But I think we should not touch them unless it's necessary since we should aim to be stable, sometimes they'll introduce unexpected behavior that we don't have tests covered.

**Comment by lipis** [comment]
auto merges by bots are dangerous anyway.. we don't want that..

**Comment by suchipi** [comment]
I agree with @ikatyang, I think it's more stable to not bump dependency versions unless we have a good reason to

**Comment by lipis** [comment]
Sounds good!
