### ISSUE TITLE
Object literals with same structures are not formatted correctly inside array

### ISSUE THREAD

**Issue by Zzzen** [prettier/prettier#3637]
**Prettier 1.9.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkoGcaoG5wBOMAlmHFqgLyoDaAOlOusI88wB5KoAMANG3aoAntx6D0AXwFNmwVF158RY1JMEBdANwg+ICAAdS0LMlAHCJWAHUSAExgALZAA5+IGAEMARrYfOkACY9LCsAcwAbOABFAFcIeGQAM08IrDg9GEJPEgjwgGEIAFsiz2QQKGg4XRBvbLAAazgYAGUDTzBw5CzYjJAAKywOACF6ptbPIrgAGStqpBS0vvbCdMJy7x9hCOga9KKSbsJevVj0gBUfUwXU9L0rNZgABWyw0uTbvsI4AEdYkm+L08bzKNyWegsEHS1myBnKFgoRAINU8hEIEAA7k9UQhriBPHgIPYanYIGAPuD8TgKXd9LEYAZ6YEaXBJJIgA)

**Input:**
```jsx
  const vertices = [
    {
      x: 0,
      y: 0
    },
    { x: 0, y: 0 }
  ];
```

**Output:**
```jsx
const vertices = [
  {
    x: 0,
    y: 0
  },
  { x: 0, y: 0 }
];

```

**Expected behavior:**
```jsx
const vertices = [
  { x: 0, y: 0 },
  { x: 0, y: 0 }
];
// or
const vertices = [
  {
    x: 0,
    y: 0
  },
  {
    x: 0,
    y: 0
  }
];

```

**Comment by azz** [comment]
Prettier preserves the fact that the first item in the array has a line break. This is because there a lot of complex cases such as options objects and hash-maps where they way the code should be printed is not obvious. See https://prettier.io/docs/en/rationale#multi-line-objects for more info.

I'll close this issue redirect you to #2068
