### ISSUE TITLE
prettier-c++

### ISSUE THREAD

**Issue by Nauss** [prettier/prettier#3683]
I discovered prettier a few months ago and have been in love with it ever since !
I'm working with both Javascript and C++.
But now, the pain comes when I have to switch from Javascript to C++. Even having to add a tab to fix indentation seems to be sooo much work for actually nothing (with a prettier-like tool).

I've been looking around a bit but didn't find any c++ related content within the prettier world.

So, what do you think ? Is it something that _could_ be done ?

**Comment by azz** [comment]
Hi!

So the steps are:

1. Find a parser (preferably written in JavaScript, but if not that's fine, you can spawn a subprocess) to convert source code into an AST. 

2. Write a printer that converts the AST into a Prettier doc.

C++ is going to be a difficult one unfortunately, due to the nature of the language. http://www.yosefk.com/c++fqa/defective.html#defect-2

https://github.com/foonathan/cppast might be a good place to start.

**Comment by darahak** [comment]
@Nauss Maybe [ClangFormat](https://clang.llvm.org/docs/ClangFormat.html) could fit your needs.

**Comment by Nauss** [comment]
Thanks for the answers. I'll have a look into ClangFormat and cppast.
