### ISSUE TITLE
Prettier will format code to >80 cols

### ISSUE THREAD

**Issue by PastelDream** [prettier/prettier#3761]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEwA6UAE3PqzgvA4nIk87Mi63DG+0uh5ypl92-D7zAazgCeAOgAmcAG4BLMHAD6UAIYBbOJgC8mABRseugDIKARnAA2AVRiSTAZyHXTcMDAAiE6XAPGT2rrr-YxKRkAGkwAM0lTEWtgnX92AEo4+OoEgG5klJwAX0z-XN8-AqK8imL6cpJKzALskGCQCAAHS2hrZFAFACcuiAB3AAVuhHaUBXEISRF6kAVrGGQwhRs4BsMuhTB+GABlJs3JKABzZBgugFdVkBEIMEXl+wbD+y6YAY2jpQV7lYaAK2sAA8AEIbLZwXbKDyHOA-R6Nc4wJqIgBMcKu+y6L2QIEMRgEJmgMyaXUOMAA6lMYAALZAADgADA0SRB7OSNk0cSS4C9xLCGl04ABHc6SQXvBSfb5IJa-ED2JSSU4XK7WQ5HExwACK5wg8HRDRgRkpIhpyAALIaNlZ1QBhCBKL44qDQfkgc72AAqRlGsvs2WyQA)
```sh
--tab-width 4
```

**Input:**
```jsx
                                    key.device_name = (
                                        LabelUtils.selectDeviceLabel(
                                            device, fields,
                                        )
                                    );
```

**Output:**
```jsx
                                    key.device_name = LabelUtils.selectDeviceLabel(
                                        device,
                                        fields
                                    );
```

**Expected behavior:**
See Input. Shouldn’t result in lines longer than 80 columns. (I omitted the braces to get the correct indentation, but they’re present in the playground link.)

Thanks!

**Comment by j-f1** [comment]
Another version, with a lower `printWidth`:

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBrOBPAdAEzgNwEsw4B9KAQwFs4ACAXloAoAdKWj2gGQoCM4ANgFUYhAQGcs4wXDAwAIgWJwe-Aa3acteIiQA0tAGaFBOcXrZaAlGysBuNiD0gIAB1HRxyUBQBOviAB3AAU-BC8UCnwIQhwnEApxGGRDCgk4Z15fCjB0GABlVxzCKABzZBhfAFcMkBwIMBS06WcS6V8YYOzSqgom9OcAK3EADwAhbNy4AuoVErh+lpcqmFcVgCZF2qLfduQQXj4MAWh4118SmAB1WJgAC2QAFkfnc4hpK+zXffO4dvwFs5fHAAI5VQjAroUHp9JCpAYgaRUQgVaq1cQlUoCOAARSqEHgW2cMD4Nxw9yexOyYkxAGEIFRevsoNBASAqtIACp8CLw6QAX35QA)
```sh
--print-width 44
--tab-width 4
```

**Input:**
```jsx
key.device_name = (
    LabelUtils.selectDeviceLabel(
        device, fields,
    )
);

```

**Output:**
```jsx
key.device_name = LabelUtils.selectDeviceLabel(
    device,
    fields
);

```

**Comment by JesseRap** [comment]
I have another case...

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgCU4BDMAgMxwnXwHIdTy6BuAHSg4B4ATVANwB8HfPl4DhUUaPFCR0mXzlSF02ZNWr18zQu0rdWiJhipoOw6oDWcAJ4BeYAAMAJMADOccmagA6T97QAPpQAK7oAEZwOAC+ALRuAabQvvA46PGJXsl+tqSxTjEWltL8JAA2oXCOST7+2T4h4VGxxSX4nuXZcDyObe34YKE4jLAAyg3Q+ABk0-3tQyMIMBOBfrXBYZHR+PZ7HZPrh03bOPOGRQbtGgPSzllr9WsnLTFI+A85qdEZHx6HvjyJAKl1uYgA9MYcjcSlxwUoYbo4Qj5siJG00co9PD0SpMZJ8ewoCAADQgKE+dzIUDA6gAdwACsCEFSUCR+BBUDxSSAIjgyDYVpgyKgoABzZAwHBVMkACxg6HKAHVZah4O5hWA4BMoO41QI1bZkOB3FSyaLPHgGfyxegSMgKBVPGSAFbuAAeACF+WBBWMSOg4AAZUVwB1OuCuj1jUViroARVCEHg4fKzpAwpwluNERIUXKPMwOFFMCVXJgsuQAA4AAxkosQTxK-mYY1FuCW-hhskARyT8GtxlZIBI7jiUDgPR6PMYfdQjGtJFt9qQjrTkZAnnQqEl0o3evFCf7YdXEbJMDzZZ4FeQACZz-zUOVYwBhGh241QaDdkChTwAFTzVk108GIYiAA)
```sh
--parser babel
--print-width 80
```

**Input:**
```jsx
import React from 'react';

<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <option
                key={`${section.section_number}-${section.term}-${section.year}`}
                value={section.section_number}
                selected={
                  currentSection &&
                  currentSection.section_number === section.section_number
                }
              >
                {`${section.section_number}: ${section.term} ${section.year}`}
              </option>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>;

```

**Output:**
```jsx
import React from "react";

<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <option
                key={`${section.section_number}-${section.term}-${section.year}`}
                value={section.section_number}
                selected={
                  currentSection &&
                  currentSection.section_number === section.section_number
                }
              >
                {`${section.section_number}: ${section.term} ${section.year}`}
              </option>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>;

```

**Expected behavior:**
Something like this:
```jsx
import React from 'react';

<div>
  <div>
    <div>
      <div>
        <div>
          <div>
            <div>
              <option
                key={`${section.section_number}-${section.term}-${
                  section.year
                }`}
                value={section.section_number}
                selected={
                  currentSection &&
                  currentSection.section_number === section.section_number
                }
              >
                {`${section.section_number}: ${section.term} ${section.year}`}
              </option>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>;
```

**Comment by psypersky** [comment]
Another example on Javascript using Mocha

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBDNa4BOWAvJgXAI4CuAluQBQDku+RjAlADpTnV1xMAdIID0wsaPFoCYEQBsaAIxEBbaAHMIEfB27cAJnDRgCSgYwCqrTKwBuNMHEYAaTADMqUMDBrR67TGBuTExDY1NFcwBJNFC4OTgYbEUEl3dPb18of0DgkMwaGHo8-MxGAHUACwRMKAhQmjQAByp4WOxM2zgcKH1MAEYAVlDsAE9YxkwAahLSsuw3eAICqC6MGnVsH2gyIyo5GFjybH1Rl1mQ3FGvdK9t7ICgqDn8yCg0CATBOQh1JmxdM85gBfWZcIHA8F5MImMxMGK1CBYQwJJIpJyuDx3LI5J6lQpMKo1fSNFrwTAQJo1CDLAA8A2G+jG7UWhBWax8m3uuzQ+ywx1OaSuNyxmT8jwumDeHy+Pz+jEUgNKkLyKqgapAzhAlPuaGQoGwBAIEAA7gAFQ0IPUobC2CA0fSakCKAgdADWiQAyk0OjQoOpkDACFQ4FrKjAVHIqoUjD7HJ6rYUaPYYKNkOA8E6-awYGbXeoVNhkG5sHJ8FqAFZoAAeACFXWAPTBPdgVHAADJ+uDF0vlkBV6uev3qBIARSoSO7SBLZdDIB9BFY6cUyVGPygTqaplg5QdMEqyAAHAAGLVb7RwcquprprdGQhdJ3USd5ynWkC4AC0UDgcEMjq1XhaHIPNsALItp17Od8BUGhA2DaDhzHCd4B7WctTRXd9H3ZAACYMNdGgFH9ABhCAVELdM6h-J0qHwAAVZJrRnfBgWBIA)
```
--parser babel
--print-width 80
```

**Input**
```js
const assert = require('assert')
require('../../../../src/lib/mongoose')

describe('User service', function() {
  describe('Is deletable', function() {
    it(
      'When no disputes active and 15 days ' + // I do this to convince prettier to split them
        'after investigation results ready',
      async function() {
        console.log('a')
      }
    )
  })

  describe('Is not deletable', function() {
    it('When dispute open or < 15 days after investigation result ready', async function() {
      console.log('b')
    })
  })
})
```

**Output**
```js
const assert = require("assert");
require("../../../../src/lib/mongoose");

describe("User service", function() {
  describe("Is deletable", function() {
    it(
      "When no disputes active and 15 days " +
        "after investigation results ready",
      async function() {
        console.log("a");
      }
    );
  });

  describe("Is not deletable", function() {
    it("When dispute open or < 15 days after investigation result ready", async function() {
      console.log("b");
    });
  });
});

```

**Expected behavior**
No passing 80 lines

**Comment by j-f1** [comment]
@psypersky That behavior is intentional: https://prettier.io/docs/en/rationale.html#testing-functions

**Comment by j-f1** [comment]
In general, I like how the rationale [explains `printWidth`](https://prettier.io/docs/en/rationale.html#print-width):

> The `--print-width` is more of a guideline to Prettier than a hard rule. It generally means “try to make lines this long, go shorter if needed and longer in special cases.”
> There are some edge cases, such as really long string literals, regexps, comments and variable names, which cannot be broken across lines (without using code transforms which Prettier doesn’t do). Or if you nest your code 50 levels deep your lines are of course going to be mostly indentation :)
