### ISSUE TITLE
What about space or tab-delimited columns?

### ISSUE THREAD

**Issue by quitequinn** [prettier/prettier#3788]
This isn't necessarily a bug or ugly.. I'm just wondering why we aren't supporting space or tab-delimited columns.

Ex.

```
// Routes
app.all('/signin',               routes.views.signin);
app.all('/signout',              routes.views.signout);
app.all('/forgot-password',      routes.views.session['forgot-password']);
```

seems much more readable than

```
// Routes
app.all('/signin', routes.views.signin);
app.all('/signout', routes.views.signout);
app.all('/forgot-password', routes.views.session['forgot-password']);
```

**Comment by lydell** [comment]
Thanks for the suggestion, and for asking in such a nice way! 👍 

> I'm just wondering why we aren't supporting space or tab-delimited columns.

Because Prettier's code style is a compromise between readability and `git diff`:ability. In this case adding, removing or changing one `app.all(...)` call could cause _all_ of them to change. That makes your changes harder to remove, and more likely to cause merge conflicts.

I'm closing this since we've had several similar issues before asking for different kinds of alignment between lines, and the `git diff` argument has been our response for those.

Please comment if I missed something!

**Comment by quitequinn** [comment]
Thank you, good to know!
