### ISSUE TITLE
Markdown: Excessive escaping of underscore and asterisk

### ISSUE THREAD

**Issue by IvanGoncharov** [prettier/prettier#3836]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB9V8DOMA6UCsABAFSEBMIANCBAA4wCW0myoAhgE4cQDuACpwQsUbAG4QGAEyog22ZADM2AG0xxqAIw5swAazgwAyrR0MoAc2QwOAV3UhJEMIpVrqZtRxh9t5gLZsLqr2AFaYAB4AQtp6BoZsfnAAMmZwQW40NjC0WRRISsHUJhyeyCABHLqOPFAytBxmMADqUjAAFsgAHAAMRdxqTdq0ZfVwnqJp1BxwAI42DNM+bP6B+a72an4MVrYbZubKcACKNhDw6fYwbBotku3IZNTWbAzK+wDCEH4BZVDQkyAbGoACrXYQFNQAX0hQA)
```sh
--parser markdown
```

**Input:**
```markdown
__test
5 * 2
```

**Output:**
```markdown
\_\_test
5 \* 2
```

**Expected behavior:**
```markdown
__test
5 * 2
```

**Comment by ikatyang** [comment]
Hi, this is intended since it could prevent people from typing valid syntax but got unexpected behavior, e.g. 
- `__test`: `<p>__test</p>`
- `__test something long long__`: `<p><strong>test something long long</strong></p>`
- `\_\_test something long long__`: `<p>__test something long long__</p>`

And I personally would recommend to not use leading/trailing `__` since it's not easy to know if it's a literal `__` or `strong`, it'd be better to put it in an `` `inlineCode` ``.

**Comment by IvanGoncharov** [comment]
>` __test something long long__: <p><strong>test something long long</strong></p>`

Agreed 👍 

However, I strongly disagree about the asterisk since `a * b * c`  doesn't produce anything unexpected. I think having math formulas, glob and RegExp in readable form are very important.

**Comment by ikatyang** [comment]
Unfortunately, we're not able to support it since remark [did not parse it correctly](http://astexplorer.net/#/gist/457df890ff9a6d0d2bdeb43d648604e6/5f4a160737e651056eceafa2d448c4eea34fbd95), see remarkjs/remark#306.

**Comment by IvanGoncharov** [comment]
@ikatyang 😭 On a positive side remark author thinks it's a bug and should be fixed.
Should I open a separate issue for asterisk problem so it's documented somewhere?

**Comment by ikatyang** [comment]
Feel free to open a separate issue. 👍
