### ISSUE TITLE
Prettier mangles lists with mixed list syntaxes

### ISSUE THREAD

**Issue by bmcminn** [prettier/prettier#3871]
In reference to #3025, I'm a little annoyed by this because I've always used hyphens for lists, but in further testing I've discovered that Prettier does not handle mixed list syntaxes well at all.

This behavior is inconvenient at best and an option to override the "preferred" syntax would be ideal.

**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBZAngAgA4Cc4Bmcu+AJpgDYCWAzjJnehXADpRsC0mA7gIYEFmNTg3S4ArtjZsAggXi5MkKADdiNKtEy8o5AuNwwAFsUxxSVGFSgBzTLUylocJNKgAqHv0FxhH0RJSUFwwELx0bgB6mMZwmEbo2CZQvPDk1HT2NI7iALbY5vawENqYUHDclLT0yvAAHjAgADQgENhW0DTIoLwkENwACr0IXSi8KhBUpM0g4Y1IBLwUNHAtAEa4vGAA1nAwAMrYW9Y2yDASqyBOYMiLy5fWK4YDmza5vLdLKy0AVjR1ACFNjs9vteLk4AAZaxwT73FoQcQwbBIgBMcO+ICOuCeyBA71w2yc3CgMzw1hgAHUpsZkAAOAAMLTwEBWlM22DxeF8xDUM3wAEdxFR8C9eG8PgsvpcVrkqGcLi0NLZmABFcQQeAYy4wXhramkWlIAAsLXOvCo1FsAGEILl3nioM4ZuIVgAVPWjO4rAC+PqAA)

**Global settings**
```bash
--parser: markdown
--tab-width: 40
```

-----

My initial edits before Prettier conversion works as expected:

**Input:**
```md
- waffles
- syrup
    - tasty
    - viscous
```

**Output:**
```md
* waffles
* syrup 
    * tasty
    * viscous
```

-----

After conversion, I make further edits to my content, which results in the nested non-standard list items to be rendered differently, and also causes the non-standard root list node items to be rendered as a separate list, but still using the non-standard syntax:

** Input: **
```md
* waffles
* syrup
    * tasty
    * viscous
    - dark
* more waffles
* butter
- oj
- toast
```

** Output: **
```md
* waffles
* syrup
    * tasty
    * viscous
    - dark
* more waffles
* butter

- oj
- toast
```

There is a linebreak between the root list nodes where Prettier assumes the `*` and `-` list syntaxes are two different list contexts.

-----

**Expected behavior:**
I would expect it to automagically convert the hyphens to asterisks without issue.

**Comment by ikatyang** [comment]
Hi, this is actually what [CommonMark spec](http://spec.commonmark.org/0.28/#example-264) described, different prefixes meant different lists.

FYI, I personally use `-`-style list too, but I didn't run into this issue since there're some editor plugins that could append a new list item with same prefix by just pressing <kbd>Enter</kbd>, e.g. [Markdown All in One - list editing](https://github.com/neilsustc/vscode-markdown/blob/master/README.md#features), I guess there should be some similar plugins for other editors as well.

**Comment by virkt25** [comment]
Ran into the same issue. I think this should be treated as a bug since Prettier doesn't allow you to config a list prefix, so it should convert `-` to `*` since the intent is to write one list and everyone is used to `-` but can't use it since Prettier doesn't have a config option for this. Hence, it should convert all `-` to `*` and a new list can be started with a line break separating the lists.
