### ISSUE TITLE
Sort object literals/arrays [request/idea]

### ISSUE THREAD

**Issue by wmertens** [prettier/prettier#3926]
In some cases it would be nice if prettier could automatically keep an object or array sorted

**Input:**
```jsx
// prettier-sort
{
	z: 5,
	d: 3,
	e: 7,
	a: `
		multiline thing
	`,
	'quoted-key': 8,
}

// prettier-sort
['one-thing', 'another-thing', 'stuff']
```

**Output:**
```jsx
// prettier-sort
{
	a: `
		multiline thing
	`,
	e: 7,
	d: 3,
	'quoted-key': 8,
	z: 5,
}

// prettier-sort
['another-thing', 'one-thing', 'stuff']
```

Perhaps even with constants?
```js
// prettier-sort-start
export const FOO = 'foo'
export const BAR = 'bar'
// prettier-sort-end
```
becomes
```js
// prettier-sort-start
export const BAR = 'bar'
export const FOO = 'foo'
// prettier-sort-end
```

**Comment by lydell** [comment]
We’ve had a lot of issues requesting sorting stuff (imports, arrays, object keys, CSS properties): #2277 #3569 #3408 #3104 #2460 #2502 #1963 #1096 #949 #767

The difference in this issue is that the sorting would be opt-in via comments. Which is a really cool idea. However, Prettier attempts to be a 100% “safe” tool – you should always be able to run it without worrying that it might break your code. Even though these comments are opt-in and kind of “I know what I’m doing”-style, they would be a departure from that 100% safe goal. And also very different from the rest of Prettier in that you’d have to actively put these comments in the source code.

I’m going to close this since I doubt it is going to be part of Prettier. However, there seems to be a great interest in these types of code transforms (myself included). As mentioned in https://github.com/prettier/prettier/issues/2277#issuecomment-362839403 I wish some tool would take off that did these not-completely safe types of things.

**Comment by wmertens** [comment]
Understood, however I don't see how it could be part of anything but
prettier or something that does exactly what prettier does:


   - It needs to have a deep understanding of the code to be able to sort
   (multiline, quoted values) => parsing like prettier
   - It needs to run before committing => live in the editor, like
   prettier, or from cli, like prettier

So, respectfully, I request that this be reconsidered for inclusion…

**Comment by wmertens** [comment]
Just after sending I realized that eslint --fix can also do all of those
things, and there is even a rule for it, it is just missing a fix function:
https://github.com/eslint/eslint/blob/master/lib/rules/sort-keys.js

So if that had a fix function, it could be used with a /* eslint-enable
sort-keys:2 */ block - not super pretty, but it would work.

Hmm, I have no experience writing fix functions…

**Comment by lydell** [comment]
@wmertens As far as I know, ESLint only has 100% safe fixes, so they wouldn’t accept a PR for it. I encourage you to take another look at https://github.com/prettier/prettier/issues/2277#issuecomment-362839403, especially [prettier-transform](https://github.com/azz/prettier-transform). For now, Prettier is only concerned with printing code (not making code transformations) to limit its scope.

**Comment by suchipi** [comment]
You could also create your own eslint plugin with a copy of the sort-keys rule that has a fix function and use that rule instead of the builtin one.
