### ISSUE TITLE
Allow parentheses around mathematical operations

### ISSUE THREAD

**Issue by Floriferous** [prettier/prettier#3968]
There is so much noise in #187, that I decided to open a new issue around a topic that seems to have been discussed a lot already, but there is no place where this specific issue (and only this issue) is discussed. (#187 is not the answer, it is much broader)

To recap:
* We're all developers who understand mathematical operators, we all know elementary math, agreed. (https://github.com/prettier/prettier/issues/187#issuecomment-313229534)
* We're all humans too, and sometimes we mess things up, which a tool like prettier (IMHO) should help us avoid. (https://github.com/prettier/prettier/issues/187#issuecomment-350849520)

I think there are 3 options:
* Make prettier use parentheses for every math operation/different precedence (with configuration options) **_very unlikely_**
* Allow disabling the removal of parentheses and follow eslint config somehow **_unlikely_**
* Allow developer's custom`no-mixed-operators` to take precedence over prettier **_maybe?_**

The last option might just be me being confused between `eslint`/`eslint-prettier`/`prettier`/`eslint-config-prettier`/`eslint-plugin-prettier`. There are now so many different tools + `prettier`'s own config options in your IDE, that maybe this 3rd point is possible, but it unclear which magical combo of the above-mentioned tools will allow me to have a custom config live together with prettier.

To clarify this for people coming here because of [this](https://eslint.org/docs/rules/no-mixed-operators), [this](https://eslint.org/docs/rules/no-extra-parens) and/or [this](https://github.com/prettier/eslint-config-prettier#no-mixed-operators), is there a way to use `prettier` (or another combo of tools) **and** format math operations the way we want?

**Comment by suchipi** [comment]
First, a breakdown:
* eslint - a linting tool that has various rules which can be enabled and disabled based on a user's **eslint config**, which is usually found in a file called `.eslintrc`. Some rules are fixable (meaning that if you run `eslint --fix`, eslint will rewrite the code for you to be compliant with the rule), but most are not. Also, **eslint plugins** can extend eslint with additional rules.
* prettier - a code formatter that reads in your code and prints out formatted code. It can also tell you if code is not compliant with the formatting it would produce. It accepts configuration via a **prettier config**, which is usually found in a file called `.prettierrc`.
* prettier-eslint - a tool which runs prettier on your code, and then runs `eslint --fix` afterwards. If you have any fixable rules whose fixes differ from the formatting prettier produces, then this tool will produce different output than prettier alone. It is a good solution for when prettier is *almost* what you want.
* eslint-config-prettier - A shareable eslint config that you can mix in to your own eslint config which disables all formatting-related eslint rules which would conflict with the formatting prettier produces. You use this when you want prettier's formatting to win, and you don't want eslint to tell you prettier's formatting is wrong. It can be very useful when introducing prettier to a project with an existing eslint config, because it will let you keep the non-formatting rules from your eslint config enabled, but use prettier.
* eslint-plugin-prettier - An eslint plugin which adds a new rule to eslint called "prettier". It's a rule that warns whenever the user's code differs from what prettier would output, and it is fixable, so if the user runs `eslint --fix`, then their code gets formatted by prettier. This is almost the same as running prettier normally, but it adds prettier to your eslint pipeline instead of as a separate tool, which may work better with editor integrations or some CI environments, or it might just be easier to set up.

So to get parens around math operators, you would need to:
* Have an eslint config with a fixable rule that adds parens to math expressions enabled
* Use prettier-eslint, which will use prettier to format your code, and then run `eslint --fix` so that prettier's formatting gets overridden with the formatting caused by the fixable rule.

Unfortunately, the [no-mixed-operators](https://eslint.org/docs/rules/no-mixed-operators) rule is *NOT* fixable, so this solution will not work.

If someone made a PR to eslint which made this rule fixable, then prettier-eslint would get you point 3.

**Comment by suchipi** [comment]
One other thing... many editor integrations for prettier have an "eslint integration" option which causes the editor to use `prettier-eslint` instead of `prettier`.

**Comment by olsonpm** [comment]
@suchipi - if I'm understanding how this works correctly, I don't think your solution will work.  As `prettier-eslint` works like:

1. run code through prettier
2. Run `--fix` against prettier's output

Running fix against the output won't retain parentheses removed by prettier.  Prettier itself would need to keep parentheses.

It's a bummer parentheses are removed because they're not functionally necessary.  That really obfuscates the code.

**Comment by suchipi** [comment]
Yeah- sorry, I'm not sure if I was clear. I was not presenting a working solution, but was explaining why the current solution would not work, and what could be done to resolve it.

> Unfortunately, the no-mixed-operators rule is NOT fixable, so this solution will not work.
>
> If someone made a PR to eslint which made this rule fixable, then prettier-eslint would get you point 3.

That said, I'm in favor of prettier retaining/adding these parens anyway. A lot of people have asked for them and I think having them is more readable.

**Comment by olsonpm** [comment]
Ah sorry for my misunderstanding

**Comment by suchipi** [comment]
No worries

**Comment by jasperck** [comment]
Looks like [Make no-mixed-operators rule fixable](https://github.com/eslint/eslint/issues/8916) didn't get consensus from the ESLint team.

**Comment by kevin940726** [comment]
If anyone really want this and just cannot give up on the rule for now (like I do). I made a plugin `eslint-plugin-no-mixed-operators`(https://github.com/kevin940726/eslint-plugin-no-mixed-operators) to support the rule to be fixable via `--fix`. Feel free to use it as a drop-in replacement of `no-mixed-operators` rule. We've been using this on our project for some time now and it works fine 😄.

**Comment by duailibe** [comment]
@Floriferous @kevin940726 FYI we now add a few more parenthesis. I don't know if that fixes your issue (I don't know what `eslint-plugin-no-mixed-operators` does) but I thought you should know.

**Comment by kevin940726** [comment]
@duailibe This is awesome! But unfortunately this not quite fit our need. We want more control to it so that it can pass the eslint rule configuration. AFAIK prettier doesn't support formatting it with custom options. `eslint-plugin-no-mixed-operators` just try to support the developers who are using both `prettier` and `eslint` and depends on auto-fixing of eslint after prettier formatting. It's a bit of advanced usage 😅. Thanks for the notification though, good work!

**Comment by lydell** [comment]
@kevin940726 We recommend [turning off all conflicting ESLint rules](https://prettier.io/docs/en/eslint.html#turn-off-eslint-s-formatting-rules). See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier).

**Comment by kevin940726** [comment]
@lydell Yep I know that, just that for some reason (coding style policy, tooling policy, etc) we have to enable the rule for now. I'm not saying that everyone should use the plugin, for my own personal project I would also disable the rule too. Just to give those who can't another option so that we can all benefit from prettier. There are huge amount of debate on this and I don't want to bring that up again 😂, why not an optional solution which can hopefully end one or two of them 😉?

**Comment by Floriferous** [comment]
For those following this thread, with Prettier 1.13 I noticed parentheses were added for many operations! 💯 

Comes from #4407 ! Now I'm super happy about Prettier all the way 🥇
