### ISSUE TITLE
Plugin API not working with globally installed modules

### ISSUE THREAD

**Issue by czosel** [prettier/prettier#4000]
Currently, globally installed plugins don't seem to be discovered by the CLI:
```bash
npm install -g prettier @prettier/plugin-php
prettier --plugin=@prettier/plugin-php --parser=php test.php
# Error: Cannot find module '@prettier/plugin-php'

npm init --yes
npm install prettier @prettier/plugin-php
prettier --plugin=@prettier/plugin-php --parser=php test.php
# works
```
It seems that `read-pkg-up` is just looking for the closest `package.json` file, which doesn't work for global installs 
https://github.com/prettier/prettier/blob/1b61b819d7f58c645c97a89b26e86915cad3c1f1/src/common/load-plugins.js#L4

(in case you're wondering why i'm explicitly passing the plugin: There also seems to be an issue with automatic discovery, running the command without results in `SyntaxError: Unexpected token` (see https://github.com/prettier/plugin-php/issues/55))

**Comment by ikatyang** [comment]
One solution is to set [`cwd`](https://github.com/sindresorhus/read-pkg-up#cwd) to its own directory instead of `process.cwd()`, but I'm not sure if there's a side effect.

https://github.com/prettier/prettier/blob/1b61b819d7f58c645c97a89b26e86915cad3c1f1/src/common/load-plugins.js#L22-L24

**Comment by kachkaev** [comment]
@ikatyang looks like you're right – changing `cwd` helps indeed. I implemented a [quick patch with this change](https://github.com/kachkaev/prettier/commit/a5910f886d96cdaa748d2708da78de5a7d643d02) to check your theory and was able to get prettier working with locally installed modules inside Atom and VScode plugins (https://github.com/prettier/prettier-atom/issues/395 and https://github.com/prettier/prettier-vscode/issues/395).

Searching for packages in global modules is still not working because there is no package.json in `/usr/local/lib/` (where my global `node_modules` are). It feels like if Prettiers searches for `prettier-plugin-X`/`@prettier/plugin-x` _folders_ in `node_modules` rather than checking `package.json`, we can get a more universal solution, which can work for both local and global setups.

When `basedir` in my patch is not defined, `cwd` is `process.cwd()`, which equals to `/path/to/current/folder` for global prettier being executed from the command line. For some reason, it is equal to `/` inside Atom plugin.

I really wish I could submit a proper PR with a fix, but after spending a couple of hours on getting to where I am, I have to admit that I won't be able to lift it. Sorry for that and hope that my experiments help you with a proper fix! Happy to try something else if that's useful.

**Comment by ntkoopman** [comment]
This also breaks on non global installs when you invoke prettier from a parent directory.

**Comment by kachkaev** [comment]
@azz WDYT of searching plugins by scanning dirs in `node_modules` rather than the contents of `package.json`? See the above comments as context.

Pinging you as the author of https://github.com/prettier/prettier/pull/3536 and https://github.com/prettier/prettier/pull/3624

**Comment by azz** [comment]
I think it's an ok solution. The use case I was originally trying to avoid was where plugins could be loaded unexpectedly (due to being intalled via transitive deps), and thus not having a way to opt out of these plugins being loaded.

I wonder how parcel bundler handles this?

**Comment by kachkaev** [comment]
IMO supporting transitive deps is a nice feature, not a thing to avoid. Glad that you also don't mind them (if I understood you correctly).

I never used parcel, so unfortunately don't know how to help. Who would be a good candidate for trying to submit a PR in your opinion? 🙏

**Comment by kachkaev** [comment]
Looks like I was able to fix it in https://github.com/prettier/prettier/pull/4192! 🎉

**Comment by kachkaev** [comment]
For those who can't wait to use `prettier` plugins globally while #4192 is being discussed, feel free to use a custom build derived from that PR:

```bash
npm install --global \
  github:kachkaev/prettier#5e308113217638949cc6047527d0999fe4a30de6 \
  @prettier/plugin-a \
  prettier-plugin-b

cd /any/folder
prettier '**/*.(a,b)'
```

This worked for me in [`prettier-atom`](https://github.com/prettier/prettier-atom) and [`atom-mprettier`](https://github.com/t9md/atom-mprettier) to format code blocks in custom languages inside markdown files. Formatting of `.a` and `.b` via plugins is not yet supported (e.g. see https://github.com/prettier/prettier-atom/issues/395 and https://github.com/prettier/prettier-vscode/issues/395)

**Comment by j-f1** [comment]
Shorter install name: `kachkaev/prettier#fix-global-plugin-api`

**Comment by kachkaev** [comment]
Or `kachkaev/prettier#fix-global-plugin-api-dist` (with `-dist` in the end), this is the same as `5e308113217638949cc6047527d0999fe4a30de6` mentioned originally. In this case the package [contains](https://github.com/kachkaev/prettier/tree/5e308113217638949cc6047527d0999fe4a30de6) pre-built files and works better in Atom plugins. The sources in  `fix-global-plugin-api` branch contain `eval("require")` statements, which work pretty badly in Atom (https://github.com/prettier/prettier/issues/1895).
