### ISSUE TITLE
prettier-ignore might not be quite powerful enough

### ISSUE THREAD

**Issue by benwiley4000** [prettier/prettier#4022]
**Prettier 1.10.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACARnAZhAJzgB0oA3AQwIwFkBPAZQAcKw4MBeWxltjAH34ZgAXwDcpes1ZwAdPQDCAGwoBnVZwxgV67srUbgpDFuiqYBAK5gYhABQBKYcYzEYkKKohK5SiAHM7AHIASygQmABCIIcJKBMRFxcKKAgYAAs4AgBbOAyIABNHZ3jXdzNvXwDgyG9o2JdE0uSoApS0zIJio2byz0rZP0CggogmOHq4hKTS8xClFVSMrNz8oqcekzcPLx9B6qDwtlkYqYwm8VJSdAwKXHgCa8wMkI1IAvZRuFUoIJgMSyqdgAUQYADYMNlCpYfBovBgAO7sKBwOAFJ4YWyIggUJgYCCWahQgowuA+Mhk3CWKBgDBhW7xACSjIAYsDSHYqTSYCFoN1SFybLz4sTSeTKdSwPzSjsBkNghAxqpJqQmqRKNQpLx2FwtTIBEJRHE9cdFDoNFxtAY9OaSiYdhZrLYuhskn1dlVhmEItEADSQ6E+cVKQWOByNGYmdrLHJ5dKFaVbd1yg61JT1CPNUopNpLTqJsqyvbykZjCYxTNbWY8hbRzqrePrO2FirFg5HOQV0oXOIiByOOIgX0gMY8szIUBUAgQBEABSoCFUyBAFDIEBCBSHK-MyFwFCUQOHWBxYAA1nlpGAwv5kI64MPRmBd-vDyAwkCCDBZzj-NkKM+D3vEAACtVAADwAIRPc8YAYChcgAGTCOAANfAkYCYSwYAAJlQoCWAID9lywCgsDoPwoC3JgCDCGAAHUNwyZAAA4AAZh2oiAgTonEmGXajviyCktyIABHSwQiIb8KF-f8kD3QDhyBbIQlvKwgNUa8fAARUsNIUKQO9hxgUiGIKJikGw4ycXma8FAgbI-2XVIUS3QE4AAFVIpd5JfOARBEIA)
```sh
--single-quote
```

**Input:**
```jsx
// before
var MySpace = MySpace || {};
MySpace.MyClass = class MyClass {
  constructor() {
  	console.log('init!');
  }
  
  anothermethod() {
  	console.log('cool!');
  }
  
  andanother() {
  	console.log('dope!');
  }
  
  stillanothermethod() {
  	console.log('nice.');
  }
};

// after
// this code doesn't use ES6 modules so we need
// to wrap our modulelevelfunc in an IIFE
(function() {
function modulelevelfunc() {
  console.log('oops!');
}

var MySpace = MySpace || {};
MySpace.MyClass = class MyClass {
  constructor() {
  	console.log('init!', modulelevelfunc())
  }
  
  anothermethod() {
  	console.log('cool!')
  }
  
  andanother() {
  	console.log('dope!')
  }
  
  stillanothermethod() {
  	console.log('nice.')
  }
};
})();

```

**Output:**
```jsx
// before
var MySpace = MySpace || {};
MySpace.MyClass = class MyClass {
  constructor() {
    console.log('init!');
  }

  anothermethod() {
    console.log('cool!');
  }

  andanother() {
    console.log('dope!');
  }

  stillanothermethod() {
    console.log('nice.');
  }
};

// after
// this code doesn't use ES6 modules so we need
// to wrap our modulelevelfunc in an IIFE
(function() {
  function modulelevelfunc() {
    console.log('oops!');
  }

  var MySpace = MySpace || {};
  MySpace.MyClass = class MyClass {
    constructor() {
      console.log('init!', modulelevelfunc());
    }

    anothermethod() {
      console.log('cool!');
    }

    andanother() {
      console.log('dope!');
    }

    stillanothermethod() {
      console.log('nice.');
    }
  };
})();
// ^ giant diff
```

**Expected behavior:**
The fact prettier-ignore works on AST nodes makes a lot of sense but I've found at least one instance where that's an extreme nuisance. My particular case is a file in a codebase which does not use ES6 modules, where we are using Prettier. I want to add module-scope variables but the only way to do this is to wrap my entire file in an immediately-invoked function expression (IIFE).

While it's generally good practice to use indentation within functions, consideration toward version control makes me not want to indent my entire file, thereby making any `git blame` lookup in the file point to me instead of the person who actually authored the last *semantic* change.

Prettier offers me a way to ***not*** indent my whole file - add `//prettier-ignore` in the line before the beginning of my IIFE. The problem is that Prettier will then avoid checking my file at all, which isn't what I wanted - I just wanted Prettier to let me wrap my file in an IIFE without making a big mess in git.

**Comment by josephfrazier** [comment]
You might be interested in the `-w` option for `git diff` and `git blame`. It'll ignore whitespace changes.

**Comment by benwiley4000** [comment]
I didn't know that option was available for git blame! I still see what I've outlined as a shortcoming of prettier, but that tip will be useful for me, thanks. 🙂

**Comment by duailibe** [comment]
Actually `// prettier-ignore` *is* not powerful enough, that's a deliberate decision since it's meant to be an escape hatch for specific use cases (e.g. [a matrix](https://prettier.io/docs/en/ignore.html#javascript)), not exactly a feature of Prettier to format specific parts of your code. I understand what you mean by "messing" with `git blame`, but unfortunately there's nothing we can do, that's out of the scope of an automatic formatter.

Feel free to comment if you think something was not addressed and we can continue discussion and reopen if necessary.

**Comment by josephfrazier** [comment]
> While it's generally good practice to use indentation within functions, consideration toward version control makes me not want to indent my entire file, thereby making any git blame lookup in the file point to me instead of the person who actually authored the last semantic change.

To expand on this a little more: I created `prettier-diff` to help eliminate non-semantic changes from diffs, and it can be configured to work with `git blame`. See here for details: https://github.com/josephfrazier/prettier-diff/tree/f13c7c361b267b4786792815ec75597fe258529f#git-diff-integration

**Comment by benwiley4000** [comment]
@duailibe 

I'm not familiar enough with the architecture of Prettier to know whether this is feasible, but I guess what I would like is something like:

```js
// prettier-ignore-parent
(function() { // this does not get formatted

function hey() { // this and all child nodes *DO* get formatted
  console.log('hey!');
}

function ho() { // this and all child nodes *DO* get formatted
  console.log('ho!');
}

})();
```

If that's not possible, then I get it. 🙂

**Comment by duailibe** [comment]
@josephfrazier `prettier-diff` is great! Unfortunately, I don't think it helps in this case. It does a great job when you are just changing the options for Prettier, not really changing the semantics of the code (which is the case of OP).

@benwiley4000 I think it might be possible, probably really hard though.. But also it's not something we think it's worth the complexity.

**Comment by suchipi** [comment]
A lot of edge cases will emerge if we try to support something like that, because some parts of the code use information about their parents to determine how they should be printed (whether they need parens, how to do alignment, etc). ASI errors could be mistakenly introduced pretty easily. Also, it's ambiguous how many nodes an "ignore parent" comment should ignore- in your example, I believe there are 3 intermediate nodes between the outside of the IIFE and the function body. However, if someone wanted to prevent the same indentation for a named function that is not automatically invoked, there would only be 2 intermediate AST nodes. So we would either need to try to keep a lookup list of patterns (which wouldn't scale) or implement a heuristic (which could confuse users). With all these points in mind, I think trying to support such a complex feature for a relatively uncommon use-case is not worth it.

However, you can use range formatting to achieve what you want, albeit somewhat manually (most editors expose this via a "format selection" command).

**Comment by benwiley4000** [comment]
I considered the bit about intermediate ambiguity. One solution could be to have a `// prettier-unignore` which gets placed inside of a node whose children should all be formatted:
```js
// prettier-ignore
(function() {
  // prettier-unignore
  ...
})();
```
However that doesn't address the issue you mentioned re: some parts of the code relying on parent info.
