### ISSUE TITLE
Markdown ordered list has double space

### ISSUE THREAD

**Issue by ysds** [prettier/prettier#4114]
**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5TrwDOMAOlHQIwB06AZhBHQEwsBGedAMx9sALxAAaEBAAOMAJbRKyUHlykACngTKU2AG4R5hSSGzVkrbABtKcKb1zYw+ODADKM5-KgBzZDC4AK72IMRgljZ2Uj52uDAaTr4AttiRtqEAVpQAHgBCTi5u7tjJcAAyPnDp0dJBMDL1XDWhXrhxyCCpBMRkpjK4PjAA6sYwABbIABwADFIDEHbDTjKdA3Bx+tVSuHAAjkHyu4nYKWlIVhlSdsnyAcGhlD6+1nAAikEQ8C1SMNi8o0IE2QXF+Tnk1meAGEIMlUp0oNBtiAgnYACr-XSXOwAXxxQA)
```sh
--parser markdown
```

**Input:**
```markdown
# Markdown test

1. foo
2. bar
3. baz
```

**Output:**
```markdown
# Markdown test

1.  foo
2.  bar
3.  baz

```

**Expected behavior:**
```markdown
# Markdown test

1. foo
2. bar
3. baz
```

**Comment by suchipi** [comment]
Per @ikatyang this is intended behavior as of 1.11.0. However I don't really understand why.

**Comment by ikatyang** [comment]
It's for alignment and indenting experience, see #3990 and https://github.com/prettier/prettier/issues/3459#issuecomment-366382620.

```md
11. foo
1. bar
1. baz
```

```md
11. foo
1.  bar
1.  baz
```

**Comment by taylorham** [comment]
What about if you never have double digit labels?

This seems like a really odd choice to implement as a default.

Ordered lists (in my experience) seldom manually increment, and I've never seen a developer keep ordered list items aligned in the code.

Is there any room for discussion on this topic? I imagine I'm not the only one whose ToCs now look real funny.

**Comment by ysds** [comment]
Thanks. I solved by changing `tabWidth` in my config file:

```json
{
  "overrides": [
    {
      "files": "*.md",
      "options": {
        "tabWidth": 1
      }
    }
  ]
}
```

**Comment by SimenB** [comment]
Setting `tabWidth` for md overrides `tabWidth` in code fences inside of them though, which is sad

**Comment by ysds** [comment]
@SimenB Confirmed, thanks. I reopen this issue for more discussion.

**Comment by kachkaev** [comment]
@SimenB you're right, `tabWidth` for md overrides `tabWidth` in code fences, but that looks like a different issue. I started https://github.com/prettier/prettier/issues/4170, let's continue a discussion there.

This issue can be close IMO given that a [comment](https://github.com/prettier/prettier/issues/4114#issuecomment-371018029) from @ikatyang justifies the current behaviour and there [exists a solution](https://github.com/prettier/prettier/issues/4114#issuecomment-371705566) for those who can't stand double spaces in their markdowns 😃

**Comment by sapegin** [comment]
I really don’t understand the example by @ikatyang — the first is more readable for me :-/

**Comment by chrisdrackett** [comment]
if the reasoning behind the double spacing is to help with scanning, it is currently setup to only help when a list includes double digit numbers. If you have just single digit numbers you end up with odd double spaces and if you have triple digit numbers alignment breaks again (as the number is not only longer bug goes back to double spaced.)

I added a feature request on this here (https://github.com/prettier/prettier/issues/4281) as I wasn't sure if this issue is exactly the same.

**Comment by dawnmist** [comment]
I ran into this after MarkdownLint started yelling at me every time I saved the file with Prettier active:
https://github.com/DavidAnson/markdownlint/blob/v0.8.1/doc/Rules.md#md030

Having the output from Prettier not match the default settings in common linters, thus causing style violations, isn't ideal.

**Comment by j-f1** [comment]
@dawnmist We recommend disabling any lint rules that conflict with Prettier.

**Comment by ysds** [comment]
I feel uncomfortable in such double spaces when less than 10 list items. It is **NOT** beautiful.

**Comment by GandalfSaxe** [comment]
I can't understand this decision. You went against what literally all other markdown stylesguides/linters I've seen with this double space after unordered list symbols for what - slightly better aligned content for 10+ lists?

Did you consider what percentage of all lists in markdown are actually 10+ items? I'm guessing way less than 10%. Two spaces in front of unordered lists just looks very weird, non-standard and in no way pretty. Hope this can be reconsidered.

**Comment by ikatyang** [comment]
I implemented it mainly for better indenting experience (i.e., do not break the structure when indenting), the alignment is the side effect.

See https://github.com/prettier/prettier/issues/3459#issuecomment-366382620:

> Unfortunately, I also find the current indenting rules quite painful. After prettifying a markdown document that contains a very long numbered list with some setup instructions, **the structure got lost and I only noticed that a few days after publishing**.

and https://github.com/prettier/prettier/issues/4281#issuecomment-379526937:

> If there're multiline contents and you want to change their indent level, it'd be terrible especially for indented code blocks:
>
> ![image](https://user-images.githubusercontent.com/8341033/38464357-2b7766b0-3b3f-11e8-882f-b667d541da9d.gif)

I know it's a bit weird but I think the advantages of the current implementation should outweigh the disadvantages.

I'm open for ideas that can solve both issues without having unnecessary diffs (i.e., detecting if indented codeblock is in a list won't work, it'll cause large diffs when you insert/delete indented codeblock).

---

The similar thing goes to emphasis/strong, we always escape those marker characters (`*`/`_`) that is not considered emphasis/strong. Why? We hope you could type everything you want and you could get the expected output without having to look back to see if there's any marker character needs to be escaped.

**Comment by GandalfSaxe** [comment]
@ikatyang I think I better understand the issue with indented code blocks now.

I guess the ideal solution would be if prettier could analyze the list to see if there are any indented blocks, and if so, put in 2 spaces after the list symbol, otherwise keep it at 1. It sounds like non-trivial work, but that would make everybody happy right?

I can see the other side of the issue, but my main criticism remains the same: The issue with indented blocks have to be weighted against the fact that it's probably way less than 1% of all lists, and the by normal use case of lists is rendered very weird looking and very non-conventional and not pretty. It's not a little weird, it's _very_ weird.

Perhaps `prettier` should be changed here and now so that it simply doesn't format spacing in the lists for now? That way both camps can be happy for now, and leave more time for discussion on a better solution.

**Comment by GandalfSaxe** [comment]
By the way, I recently had a related discussion about number if spaces for sublist indentations with DavidAnson from `markdownlint`: https://github.com/DavidAnson/markdownlint/issues/137

And the same here in the `Markdown All in One" extension that is looking to adopt the 2/3 spaces behavior also: https://github.com/neilsustc/vscode-markdown/issues/241 (at least as an option).

So looking at the most popular markdown linter and most popular markdown package for automating list spaces, neither of them seem to embrace the idea of two spaces after sub symbols as default.

But perhaps if my proposal is feasible to implement (i.e. analyze the list to see if there are any indented blocks, and if so, put in 2 spaces after the list symbol, otherwise keep it at 1), others could be convinced to do the same since it would probably be the best of both worlds / keep everyone happy.

**Comment by suchipi** [comment]
> I'm open for ideas that can solve both issues without having unnecessary diffs (i.e., detecting if indented codeblock is in a list won't work, it'll cause large diffs when you insert/delete indented codeblock).

I don't think that a large diff when you add a codeblock to an ordered list is a big deal, because that happens a lot less often than users just writing ordered lists. Currently the formatting is optimized for the former case but the latter is more common.

**Comment by DavidAnson** [comment]
@dawnmist markdownlint's MD030 is configurable, so if you want to enforce 2 spaces, you can. But then it will require two spaces after both single- and double- digit numbers which is still inconsistent with prettier's behavior as I understand it.

@ikatyang If there is a change you'd like to see in markdownlint to get better cooperation, please let me know! For now, I'm just eating popcorn and watching the action. ;)

**Comment by GandalfSaxe** [comment]
@DavidAnson So in other words, it wouldn’t look like @ikatyang’s example from earlier:

```markdown
11. foo
1.  bar
1.  baz
```

but instead

```markdown
11.  foo
1.  bar
1.  baz
```

which is not so pretty.

I agree with @suchipi  that big diffs is not a big deal since this is just a rare use case of lists. A good diff viewer will be able to show not just what lines changed, but what changed within the lines as well.

**Comment by kachkaev** [comment]
If I have 10 items and I add a code block to one of them, would all items change indent from 3 to 4 or just one? The first scenario breaks git blame and the second makes things look inconsistent. Besides, it breaks _select & shift+tab_ in common text editors because tab size is usually 2 or 4, never 3.

IMO leaving things as they are is the best option despite a slightly unusual double space. This is source code after all, not something facing the clients.

**Comment by GandalfSaxe** [comment]
Sounds good to me. For an opinionated formatted as prettier, it’s generally preferable to enforce one single style but I think this is one case that warrants allowing more than one depending on use case 👍

**Comment by j-f1** [comment]
How about only aligning if at least one list element has something other than paragraphs inside it?
