### ISSUE TITLE
Break strings

### ISSUE THREAD

**Issue by Z3TA** [prettier/prettier#4123]
I think prettier should wrap long comments and split long strings.

The first stage could be basic wrapping. But it would then be nice if it would detect JS, HTML, SQL etc within the strings and comments.

**Comment by j-f1** [comment]
For comment wrapping, see #265.

For string splitting, we don’t want to change the AST, so we can’t split join strings with `+`.

**Comment by suchipi** [comment]
I know we've had a stance of not changing the AST for a long time, but we might want to revisit long strings. They're the only thing left that I have to manually format when coding, and we already do modify the AST for JSX (which is a similar concern).

Changing tagged template literals isn't safe, and changing template literals with line breaks in them could kill whitespace, but changing additions chains containing only strings and untagged template literals that are one line should always be safe:

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWAnCB3ABFOPAUQywwAoAdEAQRngFsAHeAE1xglwzgYgDc4uAIbc4ARwCuASx64wwgDaKOaYTFzZhAZ3wQN6IdIYM4raeqFg00xewgAzEbn7CMFgEaKhrOGEVu6tLQAHS4AJIwAOS6UPry3m64aDgcXB5w2ho8fIKqQjxSskLYaAi40tG6ktpmuKwAnlDCDNIKyg24itIA1kLo0toA3LhMibUcGMJQ2g4QGAz5o+pouAzTktQAlCAANCAQLMEzyKBuWNgACm4I2sggwvwQ0qx7D1nIDkq1+x5TYH0YABlJjCMDSKAAc2QMAwkjg+1YEDAn2+CJAENqGBglymkPWqMUPxAACttAAPABC-0BQJacAAMhC4ITiRBJDAmByAEys9GgjBY+4eYQeBqKaBvJjuWAAdRe6GQAA4AAz7aUQWqyqZMe7SzJwDCCN6FGQ8XHCfHCPn7WqtGFw9HaCGQ7wARUk+hZSC+RPRMFF8tYiqQ3P2sOEthdAGEICZrSg4gQ3jU4AAVUV3H1ogC+OaAA)

**Input:**
```jsx
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration. It's not clear how to best remove the require when it's used dynamically like this; please transform the path manually.")
```

**Output:**
```jsx
throw new Error(
  "Attempted to remove a require call that was not the immediate child of a variable declaration. It's not clear how to best remove the require when it's used dynamically like this; please transform the path manually."
);

```

**Expected Output:**
```jsx
throw new Error(
  "Attempted to remove a require call that was not the immediate child of a " +
    "variable declaration. It's not clear how to best remove the require " +
    "when it's used dynamically like this; please transform the path manually."
);

```

In the case of mixed content, we could format the pure-string chains within without touching other stuff:

```jsx
throw new Error(
  "Attempted to remove a require call that was not the immediate child of a " +
    "variable declaration. It's not clear how to best remove the require " +
    "when it's used dynamically like this; please transform the path " +
    "manually.\n" +
    getCodeFrame(path, state)
);

```

**Comment by lydell** [comment]
@Z3TA Breaking comments is discussed in #265.

**Comment by j-f1** [comment]
@lydell I mentioned that in my first comment :)

**Comment by Z3TA** [comment]
There is also line escapes. For example:

´´´´
var str = "\
hello \
world";
´´´´

maybe that won't touch the AST !?

Only problem is that indentation will be included in the string. So it could be a last resort if line width is set very low.

**Comment by suchipi** [comment]
Wow, I didn't know you could do that!

Yeah, those should be treated the same as multiline template literals.

**Comment by scottmas** [comment]
I agree that we should not change the AST. But what does turning 1 line into 3 really buy is in this case? 

Input
```
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration. It's not clear how to best remove the require when it's used dynamically like this; please transform the path manually.")
```

Output
```
throw new Error(
  "Attempted to remove a require call that was not the immediate child of a variable declaration. It's not clear how to best remove the require when it's used dynamically like this; please transform the path manually."
);
```

The second is arguably less readable and takes up way more vertical space. I understand that the general idea is to try as much as possible to stay beneath the min column width, but it really buys us nothing in this case. 

Why can't there be an exception in this case for long strings, where splitting it up doesn't save hardly any horizontal space? For example, in pseudo code:

**Comment by duailibe** [comment]
@scottmas I don't think that output you posted is pretty (it isn't); I just think this complexity doesn't belong in Prettier. It's simple to make the case of breaking a long string into several strings, but we need to take into account to concatenate them back together, or "reflow" if any of the "new" strings change the width and what not.

I don't think this complexity is worth the trouble (remember one of Prettier principles is correctness).

**Comment by hawkrives** [comment]
@duailibe I think that @scottmas was asking (or, if I'm wrong, then this is my original idea) that a single string argument to `Error` be always inlined, no matter the length of the string.

I.E., 

```
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration. It's not clear how to best remove the require when it's used dynamically like this; please transform the path manually.")
```

should never be split onto multiple lines, and neither should the following, even though it has some complex template substitutions… (that may be a separate request, but in my experience I like the break-property-access-after-three-dots in normal code but not in template strings.)

```
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration. ${error.message}, ${error.stack.join('\n')}")
```

**Comment by duailibe** [comment]
Sorry I misunderstood!

In that case I don't think either way is better.

**Comment by suchipi** [comment]
The current behavior actually looks slightly better when you have soft wrapping enabled in your editor:
![](https://puu.sh/zXxEt/951e0455d6.png)

**Comment by scottmas** [comment]
Hawkrives was correct about my meaning. 

That's an interesting point about soft wraps suchipi. I don't use soft wraps, and most developers I know don't - but I could be an anomaly. In my case, I just hate looking at those triple lines when it could just be one beautiful skimmable line. I think it's the percent increase in vertical space that kills me. With softwraps enabled, the prettier formatting changes it from 4 lines to 6 lines, a 50% increase in vertical space. Whereas without line wraps, the conversion changes it from 1 line to 3 lines, a 200% increase in vertical space. It's much more jarring. 

@duailibe That template string conversation is really interesting. I'm more in the camp that thinks they should never be broken up, but the resolved upon behavior seems pretty reasonable. 

Couldn't we create a heuristic to detect if a line with a long string should be broken into multiple lines or not? For example, if the characters that are NOT part of the string are less than 20? 

With a heuristic like that, the following would be true:

Input
```javascript
// 17 characters that are not part of the string
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration")

// 25 characters that are not part of the string
const error = new Error("Attempted to remove a require call that was not the immediate child of a variable declaration")
```

Output
```javascript
// 17 characters that are NOT part of the string
throw new Error("Attempted to remove a require call that was not the immediate child of a variable declaration")

// 25 characters that are NOT part of the string
const error = new Error(
  "Attempted to remove a require call that was not the immediate child of a variable declaration"
)
```

Rather than being a fixed number of non-string characters, it could also be some percent of allowed width. So if it were 25%, at a 80 character max, it would be 20 non-string characters. 

This seems to me to be the rough heuristic that most programmers end up using when formatting code by hand.

**Comment by brocoli** [comment]
Escaping the newline character messes up with the identation of the program, it's not really a good alternative.

Here's a censored example of a real test suite on one of our apps:

input:
```javascript
module.exports = function() {
    chai.use(chaiAsPromised);

    // before and after hooks, etc...

    it('someTestedAsyncFunction should throw a 40051 error because the increments have contribution violations', function(done) {
        const result = someTestedAsyncFunction();
        
        result.should.be
            .rejectedWith(
                'Found contribution violations per resourceId: {"mock-id-2":["This resource is locked","Increment Maximum 20 < Contribution 201","User Maximum 200 < User Total Contribution 201"],"mock-id-3":["Contribution -1 < Increment Minimum 0","User Total Contribution -1 < User Minimum 0"]}.'
            )
            .then(err => {
                someOtherFunction.should.not.have.been.called;
                // more assertions
            })
            .should.notify(done);
    });
```

If you use newline escaping, assuming lineWidth 80, it will probably become:
```javascript
module.exports = function() {
    chai.use(chaiAsPromised);

    // before and after hooks, etc...

    it('someTestedAsyncFunction should throw a 40051 error because the \
increments have contribution violations', function(done) {
        const result = someTestedAsyncFunction();
        
        result.should.be
            .rejectedWith(
                'Found contribution violations per resourceId: {"mock-id-2":[\
"This resource is locked","Increment Maximum 20 < Contribution 201","User \
Maximum 200 < User Total Contribution 201"],"mock-id-3":["Contribution -1 < \
Increment Minimum 0","User Total Contribution -1 < User Minimum 0"]}.'
            )
            .then(err => {
                someOtherFunction.should.not.have.been.called;
                // more assertions
            })
            .should.notify(done);
    });
```

The identation is completely messed up. The error message is pretty bad, but in particular the `function(done)` in the `it()` line is completely off.

(By the way, I tested this output in my setup, and Prettier doesn't change it, leaving the hanging `function(done)` where it is).


It's true that it's ECMAScript's fault for not having a way to split long strings into multiple lines like i.e. Python has with string literal juxtaposition. But that doesn't mean that we can't have well-formatted code because of it, since we can still use `'foo' + 'bar'` and `['foo', 'bar', 'baz'].join('')` to at least remedy the situation, even if it means modifying the AST in these very particular cases.
Joining concatenated string literals in the same line is a similar problem that comes to mind.


If there existed another project that was identical to Prettier except that it also had a setting to allow automatic joining and splitting of string literals with `+` or `Array.prototype.join('')`, I would prefer using it over Prettier, and I believe more people would as well, because a code formatter that requires you to modify things manually is, well, not very useful over one that doesn't.

Another idea is to have another project that does only these transformations that require modifying the AST, made to work on top of Prettier itself, but I think this is being a little too zealous on not touching the AST.

**Comment by brocoli** [comment]
By the way @scottmas breaking into multiple lines would at least allow the `it()` line in my input code to break away the `function(done) {` into a different line.

**Comment by JDansercoer** [comment]
What is the current status on this?

**Comment by thorn0** [comment]
I know that we don't, but in this case the AST change looks so harmless and yet potentially so convenient that I'm really not sure... Linters can't do what is requested here. It's a print width based transformation.

**Comment by evilebottnawi** [comment]
@thorn0 maybe plugin for prettier is a good solution here, I really think we don't need it, by default enable it is a bad idea, new options is also bad idea, there is no place for this.

**Comment by thorn0** [comment]
We already have the `--prose-wrap` option though.

**Comment by evilebottnawi** [comment]
@thorn0 It can be destructive for developers which already uses `--prose-wrap` and do not want this behavior

**Comment by thorn0** [comment]
At this point any change would be destructive (or rather _perceived_ as destructive) for somebody, just by the law of large numbers. But I really think this idea is not that bad. A bit unorthodox for Prettier, yes, but let's not dismiss it. Implementing it as a plugin, which requires implementing needed extensibility points first (#4424), is a good idea too.

**Comment by thorn0** [comment]
Closing this as it's definitely not going to happen in this project. A plugin would be a separate project.
