### ISSUE TITLE
Prettier doesn't support HTML style comments

### ISSUE THREAD

**Issue by jjant** [prettier/prettier#4148]
```js
<!-- throw new Error();
```

Is a javascript comment, but Prettier throws an "unexpected token" error on that line.

**Comment by lydell** [comment]
I think this might be out of scope, because this feature ([HTML-like Comments](https://tc39.github.io/ecma262/#sec-html-like-comments)) is listed under [Additional ECMAScript Features for Web Browsers](https://tc39.github.io/ecma262/#sec-additional-ecmascript-features-for-web-browsers) which says:

> The ECMAScript language syntax and semantics defined in this annex are required when the ECMAScript host is a web browser. The content of this annex is normative but optional if the ECMAScript host is not a web browser.
>
> This annex describes various legacy features and other characteristics of web browser based ECMAScript implementations. All of the language features and behaviours specified in this annex have one or more undesirable characteristics and in the absence of legacy usage would be removed from this specification. However, the usage of these features by large numbers of existing web pages means that web browsers must continue to support them. The specifications in this annex define the requirements for interoperable implementations of these legacy features.
>
> These features are not considered part of the core ECMAScript language. Programmers should not use or assume the existence of these features and behaviours when writing new ECMAScript code. ECMAScript implementations are discouraged from implementing these features unless the implementation is part of a web browser or is required to run the same legacy ECMAScript code that web browsers encounter.

A further complication is that these comments are not allowed in module mode:

> The syntax and semantics of 11.4 is extended as follows except that this extension is not allowed when parsing source code using the goal symbol Module

It could be argued that Prettier should support this when formatting `<script>` tags in Vue/HTML. But on the other hand – why do you use such comments in the first place? Can’t you just use a regular `//` comment? I think the [the ancient days of 1995](https://stackoverflow.com/a/808850/2010616) are well past the expiry date.
