### ISSUE TITLE
Markdown Unordered List Item Symbol 

### ISSUE THREAD

**Issue by ashfurrow** [prettier/prettier#4251]
Hello Prettier! I'm a big fan of using Prettier in my JavaScript projects, and I recommend it to all my friends an colleagues. I was really excited about the addition of Markdown formatting, until I found that unordered list items are delineated with `*` instead of `-` (see [this issue](https://github.com/prettier/prettier/issues/3025) for initial discussion).

I have never even seen `*` used for list items before Prettier started changing my markdown files. I think I knew it was part of the Markdown spec but I'd never seen it used in practice. I stopped using Prettier for Markdown as a result, and [I'm not the only one](https://github.com/strongloop/loopback-next/pull/1139). I do appreciate that Prettier is opinionated, but in this case the "opinion" was informed only by a measure of "what's more common" based on a [Big Data query](https://bigquery.cloud.google.com/savedquery/652929483875:69be015faec8444c8a2e7d055eeb32f8) that I can't seem to access (so I can't assess the quality of the data). I would argue that, absent an advocate from either side, this opinion lacks context. And even taking the data on face value, `-` use stood at 39%, which I believe is enough to warrant a discussion around an option to support it. 

Personally, `-` makes far more sense to me as a list item symbol because it matches the YAML notation for list items. It is also widely used in word processors to begin lists (type `- ` on a new line and both Word and Pages will automatically convert it into a list for you). Not so with `*`. 

A [popular Markdown style guide](http://www.cirosantilli.com/markdown-style-guide/#option-list-marker-hyphen) recommends `-` for list items because `*` can be confused for bold/italic markers. [Other style guides](https://github.com/carwin/markdown-styleguide) also recommend `-` (although I did [find one guide](https://github.com/google/styleguide/blob/gh-pages/docguide/style.md#lists) that _used_ `*` but did not explicitly recommending it).

Based on discussion [on the initial issue](https://github.com/prettier/prettier/issues/3025), there is strong interest in an option for `-`, and even interest in outright changing to `-` entirely. What do others think? Thanks for your consideration.

**Comment by evilebottnawi** [comment]
> Personally, - makes far more sense to me as a list item symbol because it matches the YAML notation for list items. It is also widely used in word processors to begin lists (type - on a new line and both Word and Pages will automatically convert it into a list for you). Not so with *.

> A popular Markdown style guide recommends - for list items because * can be confused for bold/italic markers. Other style guides also recommend - (although I did find one guide that used * but did not explicitly recommending it).

Fair enough. I am vote :+1: for `2.0` version.

**Comment by sapegin** [comment]
> It is also widely used in word processors to begin lists (type - on a new line and both Word and Pages will automatically convert it into a list for you). Not so with *.

This isn’t true: I’ve just tried Pages, Word for Mac and Google Docs — all convert `*` to unordered lists.

**Comment by lipis** [comment]
https://twitter.com/PrettierCode/status/981451100262936576

**Comment by cargath** [comment]
Both are part of the Markdown spec. Gruber did a poll last year, where `-` came out slightly ahead of `*`: https://daringfireball.net/2017/07/unordered_lists_in_markdown

**Comment by alloy** [comment]
I personally use `*` for top-level unordered lists, but don’t really care much about it vs `-`. What I _do_ care about, though, is that I alternate them when nesting lists, which to me makes the nested lists stand out more.

**Comment by joshbuchea** [comment]
I typically favor symbols that don’t require modifier keys: hyphen vs asterisk, single quote vs double quote, etc.

Hyphen for the win 💪

**Comment by evilebottnawi** [comment]
Looks `-` unconditionally win

**Comment by ikatyang** [comment]
[![image](https://user-images.githubusercontent.com/8341033/38364175-22c47562-390a-11e8-9446-2178fb40487d.png)](https://twitter.com/PrettierCode/status/981451100262936576)

hyphen `-` (59%)
asterisk `*` (41%)

Option 1: add an option for it in 1.x and change the default value in 2.0
Option 2: switch to hyphen completely in 2.0

Personally, I'd like to apply `Option 1` since there're still about 40%+ people use asterisk, but based on [the reaction from OP](https://github.com/prettier/prettier/issues/4251#issue-310943939), there's no any 👎s so I'm curious if it means "I do prefer asterisk but hyphen is acceptable too", if that's the case then `Option 2` should be the way to go.

@azz thoughts?

**Comment by duailibe** [comment]
@ikatyang I wasn't too involved in the markdown decisions, did we consider infer from original text?

**Comment by lipis** [comment]
I'm still not sure if the first investigation is correct about the number of files using asterisk over hyphen. I think it was counting the number of items and not the number of files. Because there must be cases that a huge list would ruin the actual stats.. while it should count as one entry.

Most polls are showing that people prefer hyphen.. and we don't want more options (we have already too many for an opiniated code formatter). 

I would go with option 2 and change it to hyphen.

**Comment by suchipi** [comment]
My vote goes towards "infer from original text" as long as we standardize lists with mixed symbols (unless those get parsed as different lists).

**Comment by ikatyang** [comment]
Did you mean using the list symbol which is used the most in that file? I personally would like to remove more original style as possible especially this one looks something like single/double quote in JS to me, it's weird to infer this kind of style from original source.

**Comment by suchipi** [comment]
I meant to use the list symbol which is used in each given list; these would both be unchanged:
```md
*  a
*  b
*  c

-  1
-  2
-  3
```

I usually feel the way you do about removing original style but I don't really think of markdown the same way I do code, so I'm willing to be more flexible there.

That said my opinion is not particularly strong one way or the other.

**Comment by lydell** [comment]
I vote for changing to `-` in Prettier 2.0. No options. No inferring.

**Comment by duailibe** [comment]
I really like the idea of respecting the original symbol, I don't like causing too much churn in people's diffs when adopting/upgrading Prettier.

**Comment by lydell** [comment]
PR review:

> Nit: Please use _insert whatever list item symbol here_ for unordered lists.

:cry:

**Comment by suchipi** [comment]
Fair point

**Comment by infotexture** [comment]
I'd vote for the [option to add an option](https://github.com/prettier/prettier/issues/4251#issuecomment-378921897), as this issue is probably (at least) as divisive among Markdown authors as the _single-quote/double-quote_ 🔥 war elsewhere:

> Option 1: add an option for it in 1.x and change the default value in 2.0

Also, please keep in mind that Prettier is not the first tool to consider this issue, and may not be the only tool in the chain that has an opinion on what's considered correct.

It would be helpful if Prettier could be configured for interoperability with linters:

* Markdownlint includes a dedicated rule for this purpose: [MD004 - Unordered list style](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md004), 
* See also [remark-lint-unordered-list-marker-style](https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-unordered-list-marker-style)

It would be a shame if Prettier insisted on bunnystomping  “cyclic sublist” styles that use a different marker at each level of nested lists, as this approach is common in complex documents and directly mimics the differentiation provided by browsers' default rendering of nested unordered list output in HTML:

```markdown
* Item 1
  + Item 2
    - Item 3
  + Item 4
* Item 4
  + Item 5
```

That may not need to be the default, but an option that ensures consistency on each level would permit this use case, and not forbid anyone from using hyphens, asterisks, or even plus signs on every level if they prefer.

**Comment by duailibe** [comment]
@lydell Fair point. It's still my preference though 🤷‍♂️

**Comment by lydell** [comment]
> It would be helpful if Prettier could be configured for interoperability with linters:

No. We recommend turning off any linting rules that conflict with Prettier.

**Comment by azz** [comment]
I only originally voted for `*` due to the results from the BigQuery. I am (always have been) in favour of using `-`. 

I'm happy with switching to `-` in Prettier 2.0. I'm not happy with adding an option for it.

**Comment by lipis** [comment]
Did we count the total number of `*` and `-` in the BigQuery query.. or the number of files that are using the `*` vs `-`. Because if there are files that have thousands of items with `*` for a list.. the results would be different :)

**Comment by azz** [comment]
Law of averages though, there are likely just as many files with thousands of `-`.

**Comment by lipis** [comment]
@azz sure.. but still :) If we want to make _real_ science.. we should count the files and not the items :)

(all that before the actual release of the Markdown for Prettier)

**Comment by j-f1** [comment]
[Counting the number of files](https://bigquery.cloud.google.com/results/testing-168521:US.bquijob_52f98a96_1633f9f696d?pli=1) gives this result:

| symbol | count  |
|-------:|--------|
|    `*` | `27 858` |
|    `-` | `21 290` |
|    `-` | ` 1 262` |

**Comment by azz** [comment]
So 61% `*` (by count) to 57% `*` (by file). No big shift as expected.

**Comment by j-f1** [comment]
@azz However, I have no way of telling what that statistic was like before we started formatting Markdown and changing the bullets to `*`.

**Comment by lipis** [comment]
We should still go ahead and change it to `-` :)
