### ISSUE TITLE
Escaped backticks in GraphQL descriptions prevents formatting

### ISSUE THREAD

**Issue by jaydenseric** [prettier/prettier#4258]
GraphQL description strings may contain markdown. Backticks for markdown inline code are escaped in the tagged template literal string using backslashes. Escaped backticks causes Prettier to not format the entire GraphQL string.

**Prettier 1.11.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBzAjgGwAYB0oAEBuIuu2AZhBGdgQLYCuMAhjAJbQEAOLAnpggsAJgDoS+IjD7c4BAGLUACv0EiCwSUWIwARiwBOSAgGUYB9lFRaAvvmwgANCAjcO0AM7JQhgxADuKgYIXigsAG4Q7MJOICweMMgULJgecM66BixgANZwMCa8YJaoyOaM6SDCEGBJKWnOlmkGMEpZqPQsdamVAFYeAB4AQlm5+SYs9HAAMpZw3Q0uzNzMAEwLlbwGzcgg+roC0LHcFrAA6tEwABbIABwADM4nEGlnWdy7J3DN4fPOWVY4ABRKAxJCPEAA1BwMyGRLg-5wdCMdjBNosDpdJDJHrONL0dhlAwVPElTBwACKjAg8A2zlYuguwmuyFW9Ky7EwJQAwhB6J1dlBoH8QIw0gAVFi6UI4tI2GxAA)

**Input:**
```jsx
gql`
  "\`foo\` mutation payload."
  type FooPayload {
    	bar: String
  }
`
```

**Output:**
```jsx
gql`
  "\`foo\` mutation payload."
  type FooPayload {
    	bar: String
  }
`;
```

**Expected behavior:**
```jsx
gql`
  "\`foo\` mutation payload."
  type FooPayload {
    bar: String
  }
`;
```

**Comment by evilebottnawi** [comment]
@jaydenseric Thanks for issue. Looks like bug

**Comment by jaydenseric** [comment]
@j-f1 I think that is the official recomendation: http://facebook.github.io/graphql/October2016/#sec-Documentation

**Comment by duailibe** [comment]
This bug happens because we pass the raw value to the GraphQL parser, i.e.:

```gql
"\`foo\` mutation payload."
type FooPayload {
  bar: String
}
```

And `` \` `` is not a valid escape sequence (see [playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdNqAGAzCFVYAEAtgK4wCGMAltIQA4UCeANhBQCYB06qsT9OIQBieAArM2nQsD6FCAIwoAnJIQDKMZdSgBzPgF8+IADQgI9GtADOyUCuUQA7hOUJbKCgDcI1DqZAKaxhkLVI4MwVlCjAAazgYdUYwHV1Q5XCzDggwZGwKFmsIkB0i5RgxaN1iCjyCorMAK2sADwAhaLiE9QpiOAAZHTg6wuKIcnpyACYRhpBGZTLkEF1o+gALAEcWAPptWAB1Pxh15AAOAAYzPYgig7Xlvbgyr2GzaL04AFEofyQrkAfXRwTQqEL-d5wTakahuSoUaq1JD5UZmIrEajpTIgaypFhwACKpAg8FmxUoCiOHBOyCmZi0FGoLFSAGEIMQassoNA3iBSEUACoUBQeFFFAwGIA))
