### ISSUE TITLE
Prettier, flow and eslint with Vue support on Atom

### ISSUE THREAD

**Issue by Extarys** [prettier/prettier#4393]
First, I'm sorry if this is not the proper repo, I'm quite lost, there are so many packages ! (See below)
Second, thanks for this, I discovered it yesterday and although I had a hard time configuring and understanding everything, now I love it (except for this issue haha)

Now I tried so many things, I might have too many packages, but I'll clean it up once it's working. Don't judge. :smile: 

**Goal: **
Have atom diagnostics report errors from vue/nuxt and js files as possible using Flow and Eslint
Automatically format and fix file on save with prettier

I can make flow and prettier works fine but once I've added Vue, only flow report on the Diagnostics (probably because of the extension)

Command-line works fine (`eslint --ext .js,.vue`), except that since I've added Vue, Flow stopped working in eslint, it only works in atom
```
  2:9   error    The template root requires an element rather than texts                  vue/valid-template-root
   4:1   warning  More than 2 blank lines not allowed                                      no-multiple-empty-lines
   8:11  error    'bar' is not defined                                                     no-undef
  10:5   error    'num' is assigned a value but never used                                 no-unused-vars
```
It seems that Vue is incompatible with Flow. Is there a way to make it work?

If this is the wrong repo, let me know, I'll open the issue on the appropriate one.

**packages.json**
```
    "eslint": "^4.19.1",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-babel": "^5.1.0",
    "eslint-plugin-flowtype": "^2.46.3",
    "eslint-plugin-html": "^4.0.3",
    "eslint-plugin-import": "^2.11.0",
    "eslint-plugin-node": "^6.0.1",
    "eslint-plugin-prettier": "^2.6.0",
    "eslint-plugin-promise": "^3.7.0",
    "eslint-plugin-vue": "^4.5.0",
    "prettier": "1.12.1",
    "prettier-eslint": "^8.8.1",
    "vue-eslint-parser": "^2.0.3"
```

**.eslintrc.js**
```
module.exports = {
  root: true,
  env: {
    node: true,
    es6: true,
    browser: true
  },
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 6,
    ecmaFeatures: {
      unicodeCodePointEscapes: true,
      globalReturn: true,
      jsx: true
    }
  },
  extends: [ 'plugin:vue/recommended' ],
  plugins: [ 'flowtype', 'vue', 'prettier' ],

  settings: {
    flowtype: {
      onlyFilesWithFlowAnnotation: false
    }
  },
  rules: {
    strict: [ 2, 'global' ], // PLUS a bunch of custom rules, none directed to plugins
  }
}
```

**Atom packages**
```
atom-ide-ui v0.11.1
ide-flowtype v0.22.1
ide-vue v0.1.8
linter-eslint v8.4.1
prettier-atom v0.53.0
> ESLint integration checked
> Format File on Save
```
Thanks for your time

**Comment by lydell** [comment]
Hi! Reading through your issue, you don’t seem to have any problems with Prettier? If so, this is the wrong repo. Unfortunately I can’t redirect you to the correct repo, because it is difficult to understand what your problem is.

This is what I’d do:

1. Take Atom out of the equation. Only use the CLI tools. Way less that can go wrong this way.
2. Temporarily remove plugins and config until your issue doesn’t happen anymore. Now it should be easier to figure out what goes wrong.
3. Once you’ve got everything working using the CLI tools, add in Atom again, one plugin at a time. If something goes wrong at this point you can be sure that there’s a problem with an Atom plugin.
4. Finally, find the combination of stuff that causes problems. This can be difficult, I know, but if you’re determined I’m sure you’ll work it out. Let it take a couple of days.

Closing since this does not seem to be an issue with Prettier, but feel free to comment here if you have further questions or if I missed something.

**Comment by Extarys** [comment]
Thank you very much for your help. I've spent two days on and off this issue, it's kind of driving me crazy but I'm persistant ;)

I'll update here once I figured it out just in case someone Google for it.

**Comment by Extarys** [comment]
For a follow-up, I opened an [issue on vuejs/eslint-plugin-vue](https://github.com/vuejs/eslint-plugin-vue/issues/467).
