### ISSUE TITLE
Encapsulated anonymous function 

### ISSUE THREAD

**Issue by esthercuan** [prettier/prettier#4623]
Hello Prettier Community 👋🏻
I found that Prettier is adding a semicolon to this encapsulate anonymous function 
```
  componentWillMount() {
    ;(function(d, s, id) {
      var js
      var fjs = d.getElementsByTagName(s)[0]
      if (d.getElementById(id)) return
      js = d.createElement(s)
      js.id = id
      js.src = '//connect.facebook.net/en_US/sdk.js'
      fjs.parentNode.insertBefore(js, fjs)
    })(document, 'script', 'facebook-jssdk')
  }
```
In the playground, it actually gives me a syntax error. 
**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVkC2AHaCYDqAlgDYkCyEArrABQCUqwAOlOurQGY1gxHS0AJgBpUAZ1FFBjFm3boAbgEMATqgBWY1vMWrUnTagC8qQQDoA5nBgBREnEz4xAIQCeAFSUWAckse0xegBtAAYAXW0dIk5UIUtrOwd8NwBJQVopekYVayoVKEj5QxNzMByleETHOkDC9k0zKWNUKTr0BrEVMGaAcgB6PsgoKDheM04lMDgAIwgIAGszEZg+hAB9AFUAZT6xQUXNHrb9BuxVfG8IQThGqDE4FRhnOE4IHNpNUQNauXQAX3oQggYCo1Rgoh6YjKRGwMB6EImU1mCwAtJo9vMevRIn8QMIQBBYfw7shQKoVBAAO4ABXOJJQSgUECkeJA0xUk3m1i2ZzARCgFmQMBUVDg+P590e1I5FkwSmQExI93xmgAHs4OWAuTAtn44AAZflwBVKJVikBnFSS5BspTTVwkaCs7AqfmEKQwAAWyAAHCF8S6IPcCBzsDaXXBJQpjficgBHKhEHLSrxyk1m-H3TBEIUi81ifkWewARSoEHg6eVIBgduIgi9yAATPjhUpSIWAMIQTBplBQPCsqj3TzTMSVuB-P5AA)
```sh
--parser babylon
```

**Input:**
```jsx
  componentWillMount() {
    (function(d, s, id) {
      var js
      var fjs = d.getElementsByTagName(s)[0]
      if (d.getElementById(id)) return
      js = d.createElement(s)
      js.id = id
      js.src = '//connect.facebook.net/en_US/sdk.js'
      fjs.parentNode.insertBefore(js, fjs)
    })(document, 'script', 'facebook-jssdk')
  }
```

**Output:**
```jsx
SyntaxError: Unexpected token, expected ";" (1:24)
> 1 |   componentWillMount() {
    |                        ^
  2 |     (function(d, s, id) {
  3 |       var js
  4 |       var fjs = d.getElementsByTagName(s)[0]
```

**Expected behavior:**

**Comment by evilebottnawi** [comment]
@esthercuan Thanks for issue :+1:

**Comment by suchipi** [comment]
The playground is giving you a syntax error because class methods can only occur in classes, not on their own:

**Prettier 1.13.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKYA2BDAzrgAgDEIIC4APeKAE0ICU5swYA6AYQgFsAHaBGAWDoCBSL36wA6gEtMmALIQArrAAUASiEjRBNQDNVLGdDU0ANAVyWZNLcKi7dAN2wAnAgCtcOp64-63gQAvAQ0rADmcDAAophwXAK4AEIAngAq2BEActiJargaANoADAC6vroy+nrhUbHxibBpAJI0arYaWm7Rym5QlaJBoeFgPdjwcQkCBRqDXristiEEtvPerLhuYCsA5AD0+5BQUHAsrPrMcABGpADWrKcw+wgA+gCqAMr7uDQP3rt5oFFjx3AJshAaHAllBcHA3DBknB9BAempvJZgXNHLoAL4aMwQMDKJowSy7XBjGQ8GC7cmXMA3e4AWm8vzuu2xolx6FxIHMIAgNJMsOQoHcbggAHcAApg0UobDOCC2fkga5uZh3aKfUFgGRQCLIGBuZRwAUGuEImWaiJcbDIS6YOEC7wUZKasDamCfPJwAAyBrgjuwzvNIFBbityHV2GuqUw0DVPDcBpgshoMAAFsgABwlAUpiBwqSangxlNwK3OYMCnoAR2UMh6Nqy9pDYYFcK4Mg7LpAuANEXiAEVlBB4H3wzA4xns8gAEwCk3YORDzhcdsoKD8NXKOGZa64Ke43FAA)
```sh
--parser babylon
--no-semi
```

**Input:**
```jsx

class Foo extends React.Component {
  componentWillMount() {
    (function(d, s, id) {
      var js
      var fjs = d.getElementsByTagName(s)[0]
      if (d.getElementById(id)) return
      js = d.createElement(s)
      js.id = id
      js.src = '//connect.facebook.net/en_US/sdk.js'
      fjs.parentNode.insertBefore(js, fjs)
    })(document, 'script', 'facebook-jssdk')
  }
}
```

**Output:**
```jsx
class Foo extends React.Component {
  componentWillMount() {
    ;(function(d, s, id) {
      var js
      var fjs = d.getElementsByTagName(s)[0]
      if (d.getElementById(id)) return
      js = d.createElement(s)
      js.id = id
      js.src = "//connect.facebook.net/en_US/sdk.js"
      fjs.parentNode.insertBefore(js, fjs)
    })(document, "script", "facebook-jssdk")
  }
}

```

The added semicolon in the front is intended; it's to protect from ASI. See https://prettier.io/docs/en/rationale.html#semicolons
