### ISSUE TITLE
Something wrong with Prettier+VueJS. Can you help me? Thanks!

### ISSUE THREAD

**Issue by dragon-yuan** [prettier/prettier#4629]
**Input:**
```jsx
viewReceiverAddCityPicker(datas) {
	let _this = this;
	let param = {};
	datas.toProvinceCode ? param.province = {
      code: datas.toProvinceCode,
      keyword: 'province',
      title: datas.toProvinceName
    } : null;
    datas.toCityCode ? param.city = {
      code: datas.toCityCode,
      keyword: 'city',
      title: datas.toCityName
    } : null;
}
```

**Output:**
```jsx
datas.toProvinceCode
	? (param.province = {
                  code: datas.toProvinceCode,
                  keyword: 'province',
                  title: datas.toProvinceName
    })
    : null;
datas.toCityCode
	? (param.city = {
                  code: datas.toCityCode,
                  keyword: 'city',
                  title: datas.toCityName
    })
    : null;
```
I used webstorm + prettier + eslint. `"format": "prettier \"src/views/**/*.{js,vue,json,md}\" --write`
But webstorm tell me `eslint expected indentation of 20 spaces but found 22`
Please help me how to fix it , Thanks everyone.

**Comment by lydell** [comment]
It sounds like Prettier and ESLint disagree on the indentation. We recommend disabling all ESLint rules that conflict with Prettier. See [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier). What you need to do is to find the ESLint config and disable the conflicting rules.

I’m going to close the issue since it does not seem to be an issue with Prettier, but feel free to keep on commenting on this issue if there’s more to it!
