### ISSUE TITLE
 parenthesis around the ternary operator 

### ISSUE THREAD

**Issue by yuritoledo** [prettier/prettier#4714]
Its possible to remove the parenthesis around the ternary operator on JSX code ?

Tks.

**Comment by j-f1** [comment]
Can you give us an example of what you mean?

**Comment by yuritoledo** [comment]
Sure!
![image](https://user-images.githubusercontent.com/18474538/41535340-569b130c-72d8-11e8-8aae-a0780c0254c2.png)

**Comment by yuritoledo** [comment]
nice!

Thanks for attention! :D

**Comment by duailibe** [comment]
@yuritoledo Prettier used to print this by your format and we had a lot of requests to change it when using JSX and we're not gonna change this again now, sorry!

Also, when @j-f1 linked to the original issue and the PR, it wasn't meant for you to go comment on the closed issue/closed PR.

Closing it since it's not something we're gonna do now.

**Comment by yuritoledo** [comment]
ok, tks
