### ISSUE TITLE
not putting in a semi-colon when needed

### ISSUE THREAD

**Issue by Prairie-Falcon** [prettier/prettier#4749]
**Prettier 1.13.6**
```sh
# Options (if any):
--no-semi
```

**Input:**
```js
const a = 1

(function foo() {})()
```

**Output:**
```js
const a = 1(function foo() {})()
```

**Expected behavior:**
Well ... there's an argument that [this question in #1510](https://github.com/prettier/prettier/issues/1510#issuecomment-324394371) creates expectation that where we find need for a semi-colon, we'll add it. So, expected behavior is

```js
const a = 1

;(function foo() {})()
```

Perhaps especially because this similar example does pretty close to that.
```js
let a

(function foo() {})()
```
Above becomes:
```js
let a

;(function foo() {})()
```
Ouch! These edge cases are tough!

I happen to think there's a better argument that the starting code:
```js
const a = 1

(function foo() {})()
```
worked right. The input is bad code. The output (above) is the same bad code, but reformatted reasonably.

I hope this helps somehow. Or earns a chuckle. Or can serve as a useful example of how difficult reformatting can be. I have no idea what to do with this. Maybe it's reason to go back to semi-colons!

**Comment by lydell** [comment]
This is a sad consequence of how Prettier and JavaScript works. Prettier takes valid JavaScript as input, and produces valid JavaScript as output (but formatted differently). Your example _is_ valid. Non-sensical, yes, but _valid._ The JavaScript syntax rules says that you are calling the value `1` with some stuff. Prettier has re-formatted your code to make that clear.

There has been a proposal to make Prettier accept a _superset_ of JS that would treat your example like a human would: #1143. However, that leads us down a very tricky path. We can no longer say "Prettier is 100% safe to use – it never changes the meaning of your code" (which is a reassuring thing to know for new users). Weird stuff always exist in really big code bases. And if we start with the semicolons, where do we stop? Soon we might be formatting "PrettierScript" instead of JavaScript. Also, this would require modifications to the parsers which would be tricky to maintain.

Related issues: #2662, https://github.com/prettier/eslint-config-prettier/issues/30#issuecomment-332240448, #1143, #2901

Finally, if you work on a lot of semicolon-free code bases, it is a good thing to adopt the habit of always typing a `;` before you start a line with `(` or `[`, regardless of whether the project uses Prettier or not.

**Comment by lydell** [comment]
Duplicate of #2662
