### ISSUE TITLE
Functional composition heuristics false positives

### ISSUE THREAD

**Issue by princed** [prettier/prettier#4751]
**Prettier 1.13.6**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEMAWBLAzgOkgWwAcIs4AKAEwEYAaAAgoCYBKAbhBpAkJg2i2SgAhgCcREAO4AFUQgEohANwgYKHEACMRQsAGs4MAMqEdGKAHNkMEQFc4nM6REwp28-iHIAZkIA2pTgArLAAPACFtPQNDIXw4ABkzOG8-AJATESdkTSENAE9faHVCETMYAHVVdGQADgAGThKSOHLtQmySuCdFZM4ROABHGwx+1yF3TyQff3sQUnwMK1tZrDNzXzgARRsIeBSZzhhcyopqpEZD7QxfNYBhCHwPbKhoXpAbUgAVXPlp0gBff5AA)

**Input:**
```js
this.compose(d1, d2);
```

**Output:**
```js
this.compose(
  d1,
  d2
);
```

**Expected behavior:**
Input code is not reformatted. 

As discussed in https://github.com/prettier/prettier/pull/4431#issuecomment-393747847 functional composition heuristics produce some unexpected false positives,  in part because `compose`, `connect`, `flow` terms are too broad and might relate not only to functional context.

Possible solutions:
* Make sure identifiers are originated from certain packages (probably complex and slow as it requires scope)
* Use code shape instead of identifiers list for heuristics 
* At least blacklist obvious edge case, i.e. when `callee` is `MemberExpression` and not `Identifier`

cc @suchipi

**Comment by suchipi** [comment]
Thanks. Not sure how to refine this yet; open to ideas.

I don't think bullet 1 is feasible- we don't have the infrastructure in place to check that right now, and even if we implemented it, it would be very slow.

Bullet 2 was discussed in the original issue and seems like our best bet, but I want to be careful not to introduce regressions.

The MemberExpression thing is intentional, to support eg `import * as R from "ramda"`. But we could filter out `this`, etc.

**Comment by j-f1** [comment]
@suchipi How about checking if the `object` of the MemberExpression is a specific identifier as part of the heuristic?

**Comment by princed** [comment]
Raised https://github.com/prettier/prettier/pull/4758 to filter out at least some straightforward cases.
