### ISSUE TITLE
JSDoc type cast parentheses is removed 

### ISSUE THREAD

**Issue by mohsen1** [prettier/prettier#4799]
**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMIAWArlANY7AA6UOtOA9AFSPWUw6M4ACATnDER5RcwAEYQIqOOigBfHAHcC-ZTxwQ1UCOxjL8xMooCWqVDgLoAbnBzocPEjCMBbOK3aN67i5gBKjlzgACgBKCnc2ADMNHCDIYXYwA1IAcR4IIgAHdUicXSNMADoAfQBzdKzMMKooNjqYenocAHUbaFQATxwoODgAEzyIHCS4MHJdG0ijHkx2aDdamHq+ASFYiKXNpJJUiszCgoBJKCMndFRQnAAyK436pk4uGA7Mm2AAUVgeF4gjWHlPLFtmQ0hlMiFCqV+P5YIFCDtLgBeZF5AgFah0TFYkIAbg2sg2K0ENEi50wcDxiwJchAABoQBBMk5oJhkKB0Dx0goAAochCslBWX59OkgUQ8dBjfgAZUykr+pWQMAccHpf3JPBg3IlpWc6GQpNQ5PpACtMAAPABCEqlMGl6FcABk-nADWTVSA5TM4DxkGL0KIOqhoKLMjw-jBmkY+rpkAAOAAM9LDEHJzQlmT9YbgGusor4AEciNM4Nr0Lr9UhDcaQOTnEYlSr6ZgFVIAIpEbSuqvu+kwANRmMEZAAJj7EpMCrwEGcer9Wh6oqI5IAKgGBdW4LJZEA)
```sh
--parser babylon
```

JSDoc [`@type`](http://usejsdoc.org/tags-type.html) allows casting types of a reference but it requires a pair parentheses around the target reference. Prettier should not remove it.

**Input:**
```jsx
class Chunk {
    /**
	 * @returns {boolean} whether or not the Chunk will have a runtime
	 */
	hasRuntime() {
		for (const chunkGroup of this._groups) {
			// We only need to check the first one
			return (
				chunkGroup.isInitial() &&
				/** @type {Entrypoint} */ (chunkGroup).getRuntimeChunk() === this
            );
		}
		return false;
	}
}
```

**Output:**
```jsx
class Chunk {
  /**
   * @returns {boolean} whether or not the Chunk will have a runtime
   */
  hasRuntime() {
    for (const chunkGroup of this._groups) {
      // We only need to check the first one
      return (
        chunkGroup.isInitial() &&
        /** @type {Entrypoint} */ (chunkGroup.getRuntimeChunk() === this)
      );
    }
    return false;
  }
}

```

**Expected behavior:**

```js
class Chunk {
    /**
	 * @returns {boolean} whether or not the Chunk will have a runtime
	 */
	hasRuntime() {
		for (const chunkGroup of this._groups) {
			// We only need to check the first one
			return (
				chunkGroup.isInitial() &&
				/** @type {Entrypoint} */ (chunkGroup).getRuntimeChunk() === this
            );
		}
		return false;
	}
}
```

**Comment by ikatyang** [comment]
Looks like it's caused by the outer parens:

**Prettier 1.13.7**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTAegCpjMABGATwAc5NgANAX02MMwAoBDASgDoARp1748BMAG4AOlEhQMOfFxJlKtek1bsufISLETekkABoQEGjACW6ZKG4AnRxADuABScI0yENwBuENYAJmYggo7cYADWcDAAyjRR1lAA5sgwjgCucOYpaHCOMO6RqQC23MgAZtwANgXmAFZo2ABCkTFx8dxlcAAyKXDVdQ0gSY4Fjr6C3IJUtdBhNI4pMADqITAAFsgAHAAM5ssQBWuRNL7LcJP+Q+aOcACOWdYPJdzllUg19bkgBWVrBlsn80ClUrU4ABFLIQeDDX7mGCzDbBbbIABMSMi1lq4IAwhAyhVfFBoHcQFkCgAVWY+b4jODMZhAA)
```sh
--parser babylon
```

**Input:**
```jsx
const x = /** @type {X} */ (a).b() === c;
const x = (/** @type {X} */ (a).b() === c);
```

**Output:**
```jsx
const x = /** @type {X} */ (a).b() === c;
const x = /** @type {X} */ (a.b() === c);

```

**Comment by Kovensky** [comment]
This also happens even with only a single set of parens.

https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATOAzOAJ0Lm0wF5MB6AKhswAEYBPABzk2GExLQgBsAbhwAUASiSZBEAJbYA3DzgArOGCwi4kgIZRmEqbLIBfY5hpVMI4MbEgANCAisYM9MlDbiEAO4AFLwQ0ZBBtaTkHEAAjQm0wAGs4GABlVjiZKABzZBhCAFc4RwALGABbfgB1Ipl4NDSwOGSgmplBGuYQsDRgxwy0Ihg-WMzS7WQ8bX5+x2U0AA8AIViEpOTtUrgAGQy4ccnpkFm55IzM-jgARTyIeD2pwpA0wn7CEKjtKOZ+aEjWQgyYBU5DAisgABwABkcfwg-QqsVYIT+cBewkiJAAjnkZCQhtoRmMkBN7o5+qUZDl8g80KdzlcbrsifsHjAPkDsCDkAAmRy5bQyfinADCEFKoxCUGgu0ceX6ABUPsEmfdTEA

**Comment by rsimha** [comment]
The AMP project is considering the use of `prettier` with our closure-compiled JS runtime. During today's design review (https://github.com/ampproject/amphtml/issues/20844#issuecomment-470288213), we encountered a version of this issue, which results in incorrect JSdoc typecasts for closure-compiler:

**Playground link:** [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEATAhjXTAXkwHoAqczAARgE8AHOTYAQgCk1oB5AIwCs4YGAF9M5UpgAUAHSiZMDXACc0cTtCkVytRs2AZlASygBzMROmm4MACL5cUuADcEMAJTuAdGgCuvQykAFk93AG4QABoQCAYYI3RkUBVlCAB3AAUVBDRkEFxnCCNsKJBeZVwwAGsbAGUlMBNTZBhlXzhogAsYAFsAGwB1TqN4NAa4WpyRo2cRujywNFzokzVlGAyK0x7cZAAzXD61aP40AA8AIQrqutweuAAZEzh9w+OQU7Papr64AEVfBB4K8jh0QEpVHBlHleLheHQ+tBSgxjLABsUYJ1kAAOAAM0RREDUAwqDDyKLga1cpWUcAAjr4jLTNrhtrskAdQdE1D0jC02mC0D9-oDgRy3mCCLx0dhMcgAEzRVq4Ix9JoAYQgPR2eSg0Be0V8agAKnDcuLQSIREA)

**Original code:**
```js
const data = /** @type {!JsonObject} */ (
  parseJson(/**@type {string} */ (getData(event)).substr(4)));
```

**Modified code:**
```js
const data = /** @type {!JsonObject} */ (parseJson(
  /**@type {string} */ (getData(event).substr(4))
));
```
Notice how earlier, `(getData(event))` was being cast to `string`, but now, the cast is being applied to `(getData(event).substr(4))`.

/cc @vjeux @cramforce

**Comment by vjeux** [comment]
Interestingly, if it’s not within a function, it works as expected. So we must have some kind of special casing for it that’s not always being ran. I’m on the phone so can’t investigate more right now but that’s promising, we probably just need to fix the fact that it doesn’t always run.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucBDANugFAegFR4ACMAngA5wAEwAzjAE4CWUA5gL6V46VYtwwARVDFRY4ANwQwAlNIB0NAK4AjOvSwAWWQG4AOlH34ipCtTXN2nbr35CRYybFkKVazdJAAaEBDIxG0DTIoKj09BAA7gAKoQhBKKjiEIwAJl4gyvSoYADW-ADKZNkWyAyKcN4AFjAAtugA6pWM8DRFYHD5cc2M4s0kyOA0Qd7MNHD0MFFZLDWoyABmGGPeAFY0AB4AQlm5Bag1cAAyzHALSxUga+v5FuhwAIqKEPBn6MsgRfRj9APKqMokdDQdJkJiweqpGCVZAADgADN5QRAxvUsmQBqC4N9JOl6HAAI6KRh4qaoGZzJCLN4XMY1Rilejlbw0W4PJ4vSnnbwiZQQlJQ5AAJm5WUY6AsAGEIDVZgMoNBTt5FGMACr-eJUsZsNhAA)
```sh
--parser babylon
```

**Input:**
```jsx
call(/**@type {string} */ (getData(event)).substr(4));

/**@type {string} */ (getData(event)).substr(4)
```

**Output:**
```jsx
call(/**@type {string} */ (getData(event).substr(4)));

/**@type {string} */ (getData(event)).substr(4);

```

**Comment by rsimha** [comment]
Here's another case where parentheses are being removed from a JSDoc type cast. (`this.node_` is losing its parentheses when there's no space between `@type` and `{`.)

**Before:**
```
return {node: /**@type{!Text} */(this.node_), offset: idx};
return {node: /**@type {!Text} */(this.node_), offset: idx};
```
**After:**
```
return { node: /**@type{!Text} */ this.node_, offset: idx };
return { node: /**@type {!Text} */ (this.node_), offset: idx };
```
Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAJhQQAmcSuA9AFSUACMAngA5zACEAKnAB4wC+ulcgAoYACwCWAZwB0hEgH0AlABpcEAGbrJGMuKJdeAbgA6UdFhz45pCtTpM4+Dtz4DhYqbOJwlqjVp1cPQMTKBBlEAhGGHFoSWRQAENUVAgAdwAFZIR4lESANwg9cJAAI1REsABrDABlRkrxKABzZBhUTDgI0RgAWwAbAHUJeEkGsDhanPEY-Jn6ZHBJeIim7VQYDIrm3sTkdUT+7QiAK0kuACEK6rrE3rgAGSa4fcPjkDOuWqbm-rgARUwEHgryOXRADVQ60WpUSpXo-WgJUYqCaMEGejEyAAHAAGCIoiDaQYVRiLFFwdb5F4RACOQPgWyiuRAiUkAFooHA4CQiCV0PTxOgtokdnskAcwRFtL1xG0OuDJD8-oDgS8JW9wTA4RiiFikAAmCLtRLifo-ADCEF6u0WhC5JUw2nYcNyku0vF4QA)

**Comment by jridgewell** [comment]
Fix at https://github.com/prettier/prettier/pull/6116

**Comment by rsimha** [comment]
Three more bugs:

**1. Parentheses are stripped if the open parenthesis is on the line after the typedef.**

**Before:**
```
foo = /**@type {!Foo}*/
  (bar);
```

**After:**
```
foo /**@type {!Foo}*/ = bar;
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA6gJ2gcwB0oAzCCDAXg1QCpaABGATwAc4NgBCAMXIF9aqYhgwAKAEYBDHAEoA3MXQYAwhBw44YGMTIVqdRi3adeAoaMkyFu8lRr0mbDtz4RBmMSIzS5iqCAANCAQrDAAltAAzsigMngA7gAKMggxKFIAbhDhACZBIBI4UmAA1nAwAMqsJeFQ+MgwOACucMEAFjAAtgA2WO3h8FE1YHCVaYPhmYPMyOBRMcF1UXA4MEnF+F1SyCRSPSvBAFZRAB4AQsVlFZVSXXAAMnVwu-uHICenlXX4PXAAis0IPBXgc2iAajgVjg5tIJMwetACqwcHUYFg8jB2sgABwABmCKIgK1wUlYcxRcGhmRewQAjkD4BtQukQFIogBaKBwOC5XkFTQM8KaDZSLY7JB7MHBFZdcKNFrgqI-P6A4EvSVvcEwKQSDG5LHIABMwSaUnCPR+ai62zmUGgtJAzRWABVdekpSt+PwgA)


**2. Parentheses are removed if a typedef ends with `**/` instead of `*/`**

**Before:**
```
foo = /** @type {!Foo} **/(bar);
```

**After:**
```
foo = /** @type {!Foo} **/ bar;
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACAIhArgIwBs4MAqDASyjNNQB0p0MB1AJ2gHMGAzCCDALwZUpcgAEYATwAOJYAEIAYnwC+NVAAp8AQ1YBKANwMmAYQitWcMDB59Bw0Rgky5S1WU079RqCAA0IBDSMBTQAM7IoLrsAO4ACroIESjaAG4QFAAm-iD4rNpgANZwMADK0gVUHMgwrLhwAQAWMAC2hMyNFPBhFWBwpUldFKldksjgYREBVGFwrDBx+Rwt2sjc2oSzAQBWYQAeAEL5RSWl2i1wADJUcGsbWyC7e6VVxACKuBDwd5sNIBWsWascY6fCSQjQHLSVhUGDMLIwRrIAAcAAYAtCILM2NppONoXAgalbgEAI6feCLILJEDaMIAWigcDgmRZOUs5IolkW2mWqyQ61+AVmLQoNTqfzCrzgHy+twF9z+MG0+HhmURyAATAFatoKIQqmYWitxlBoCSQLhZgAVFXJQWzFQqIA)


**3. Parentheses removed if  a member access is done on a typedef'd object variable**

**Before:**
```
foo = /** @type {!Foo} */ (/** @type {!Baz} */ (baz).bar );
```

**After:**
```
foo = /** @type {!Foo} */ /** @type {!Baz} */ (baz.bar);
```

Playground link [here](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6VACA8gIwFZxgwYCGYYcAzpRtBjAJ4AOcAJnAGYA6U6GA6gCdoAcx4cIEDAF4MqAFTyMAAUYsMwAIQAxSQF8M8zAAoFS1czgbNAIRIAvA0YzGcDgJQA6N4IzuA3Dx8AMIQgoKEMOKSMnKKKmpWWroQTiam8RbqWnaOhiZu9u5ePn6BUDw8IAA0IBBMMACW0JTIoCThEADuAAodCK0oJABuEI2sNSA4gmQA1nAwAMpMZI1QIsgwggCucLUAFjAAtgA2-PuN8JQrFIsDl43DlwzI4NSTa5RwgjA9MyJHEjIDgkE5fWp4SgADxsMzA8yWJCOcAAMms4MDQeCQJCoYs1iITnAAIrbCDwTFgvYgFaCL6CV5uHAME7QSZMQRrGD8cYwfbIAAcAAZahyIF8hCQmK8OVRvsMMbUAI5k+B-eqDEAkSgAWigcDYbEmERVjQifxIAKBSBBVNqXyOjU2O2plAJRNJ5IxNqx1JgJBwPNYfOQACZalsSI0TgTQkdAa8oNBFSBtl8ACoBwa2r56PRAA)
