### ISSUE TITLE
Codes format unexpected with function "pipe"

### ISSUE THREAD

**Issue by yutent** [prettier/prettier#4858]
![image](https://user-images.githubusercontent.com/11972650/42825010-ab3c41a4-8a13-11e8-9486-0f948c89202a.png)

**Comment by yutent** [comment]
It happens only after v0.13.0

**Comment by j-f1** [comment]
This will be fixed by #4758:

**Prettier pr-4758**
[Playground link](https://deploy-preview-4758--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAbOMAEAzCFMC8mADgJbFwAUAhtQDSYBGjDYYAlADpTpa4QAmQpmoB9VNADmoqNQC2VWg2asO3XjjwBmYY2oAnAHRkKlAIxm6AgVx4ZNEACy6Dx4sXOXrdLVrqPHOgBWIPYQOhAIYhhSaABnZFADfQgAdwAFAwQElGoANwhSABNwkEZ9ajAAawwAZWJK0ihJZBh9AFc4CKa4uH0YdIrJOWpkbGpUXoiAKziADwAhCuq6+TgAGSa4MYmpkAb9Xv1kMupGAE8JKFLifSaYAHVimAALZAAOAAYI24heh4qxBOtzgRzy2wi+jgAEd2qQoYNqMNRkhxpMuiBenJSK0Ohi4k1JOgAIrtCDwHboiIwM5PIqvZACakVUioQkAYQgchGJyg0AhIHavQAKmccmjegBfSVAA)
```sh
--parser babylon
```

**Input:**
```jsx
let foo = pipe(aa, bb, cc)
let foo2 = a_long_name(aa, bb, cc)
let foo3 = bar.pipe(11,22)
let foo4 = bar.ppp(11,22,33,44,55)
```

**Output:**
```jsx
let foo = pipe(aa, bb, cc);
let foo2 = a_long_name(aa, bb, cc);
let foo3 = bar.pipe(11, 22);
let foo4 = bar.ppp(11, 22, 33, 44, 55);

```

**Comment by yutent** [comment]
Thanks a lot.

**Comment by yutent** [comment]
This issue is still alive in version 1.14.2

**Comment by yutent** [comment]
soga…

**Comment by asbjornh** [comment]
Issue still persists in `1.15.3`. I really can't believe code being formatted differently depending on magic strings has remained unfixed for over half a year! 😱

**Comment by evilebottnawi** [comment]
@asbjornh it is open source so PR welcome

**Comment by asbjornh** [comment]
> @asbjornh it is open source so PR welcome

I know :) But as already mentioned [that PR already exists](https://github.com/prettier/prettier/pull/4758). It seems like the maintainers are happy with formatting depending on magic identifier names, so I'm not too eager to duplicate that PR.

**Comment by tiagonapoli** [comment]
I'm having this problem too ([playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBnGAnOBDAtgOgAcBLQuACgBM50AaAAmHoUqXoDNsAbVOegXwCUIWiAiEYxaKmShsGDBADuABXkIZKbADcIxSiJAAjDNjABrODADKhM8SgBzZJgCucUQAsYuLgHVPYnhUOzA4aw0g4m0ggE9kcFQZUQdeDBgVU0dcbGROHg8QACtUAA8AIVMLK2s8OAAZBzg87l5REtLrB0cuOABFVwh4FoLROww0hKNsI1iuaENCDAcYP30YT2QADgAGMcVeP1NCBKWaOAxtZtEAR0H4TPFNEGxUAFooODhqA1EsO+IWEy2GyuSQ+TaaDguGILgw7lEqG6vQGQ2a4NahRgMzWlA2yAATKJMNhiFxugBhCC4HIJKDQa4gVy8AAqM00ELg-H4QA)):
```js
stream.pipe(dest, { end: false })
```
Is changed to:
```js
stream.pipe(
  dest,
  { end: false }
)
```

**Comment by evilebottnawi** [comment]
I think related https://github.com/prettier/prettier/issues/5969
