### ISSUE TITLE
Adds space after `:not` pseudo class in styled-compones

### ISSUE THREAD

**Issue by ericbiewener** [prettier/prettier#4927]
See the last selector below: `${Card}:not (:last-child)`. The space after `:not` is getting added by Prettier.

```js
const Row = styled.div`
  @media (min-width: 650px) {
    display: flex;

    ${Card} {
      width: 50%;

      &:first-child {
        margin-right: ${v.s1};
      }
    }
  }

  @media (max-width: 649px) {
    ${Card}:not (:last-child) {
      margin-bottom: ${v.s1};
    }
  }
`
```

**Comment by hawkrives** [comment]
[Minimalistic playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAlCB3TAXkwwE8AbOAEwDoqBLANwAMAdKTTAAQFtr6AhpgAUPAQA8AtHnpUYACySYAbABYAnAAdxASkzB2nTgBJgAYQEAnKgF8kUCDGFJyAjJLDz65KnoMcjTjFLAHN6KEkAI0cYCB4lU0YaNABGGwBuQyMbLJyoNigQABoQCE0YenRkUCtLfAAFKwQ0ZBABRghZYpBIywEwAGs4GABlTX7wkOQYSwBXOBLwtDhLGHq+kLFkADMBcmWSgCs0cQAhPsHhkYE+ABlwuB29g5Bxy2XLVsiBSIpobs0lnCMAA6rIFMgABwABhKgIgyxBfU0rUBcA+jEeJUscAAjrN6Dj1gJNgInvsFiBljx6NM5pS0JNKABFWaOR5IXYUkowH5guTyZAAJh5fW8kzMcS2KAcUCxIFmywAKj8WpznnAbDYgA)

**Comment by j-f1** [comment]
Slightly more minimal:

**Prettier 1.14.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAlCB3TAXkwwE8AbOAEwDoqBLANwAMAdKTTAAQFtr6AhpgAUAMwgQkmAEYCATgEpMwdp04ASYLIBeAXyRQIMYUgCOAV3MAPJcF2rM9qGyggANCAgAHGPXTJQeTl8AAV5BDRkEAFGCHoqdxBpOQEwAGs4GABlL1T6KABzZBg5czgPfLQ4ORgQlIKeAWRRAXIqjwArNCsAIRT0zKyBPgAZfLhm1vaQXLkquSjZaQpoRK85fJgAdXiYAAtkAA4ABg91iCqtlK8o9bh5xgmPOTgLehe6gQampBa28pAVR49GKpQBaHyBUoAEVzEYJr8pgCYAJpDsqPtkAAmDwlAT0ciQgDCEB4jSihigTxA5iqABVUZFEf9dLogA)
```sh
--parser babylon
```

**Input:**
```jsx
const Row = styled.div`
  @media (foo: bar) {
    ${baz}:not(:quux) {}
  }
`

```

**Output:**
```jsx
const Row = styled.div`
  @media (foo: bar) {
    ${baz}:not (:quux) {
    }
  }
`;

```

Some things to note:
- This only happens if the selector is in a block.
- This only happens if the block has a `()`-wrapped parameter.

**Comment by evilebottnawi** [comment]
Problem in `@prettier-placeholder-*-id`, we replace `${baz}:not(:quux) {}` on `@prettier-placeholder-0-id:not(:quux) {}` and `postcss`(exactly `postcss-media-rules`) parse this as `media` at-rule. 

Possible solution: introduce `css-template-literal` node (what represent `${something}`) and move all logic for `css-in-js` into this node. But it is require a lot of work, i don't think i can find time on this in near future.

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/prettier/prettier/issues/4927
