### ISSUE TITLE
CLI with config option throws  "cannot read property 'sync' of undefined" since 1.14.0

### ISSUE THREAD

**Issue by alexandernanberg** [prettier/prettier#4962]
**Environments:**
- Prettier Version: 1.14.2
- Running Prettier via: CLI 
- Runtime: Node 8.11.3 
- Operating System: MacOS 10.13.6 

**Steps to reproduce:**
Run the following (this expects that you have a `.prettierrc.examples` file and a `examples` dir with code in it)

```
prettier --config .prettierrc.examples --write \"examples/**/*.js\"
```

**Expected behavior:**
Prettier should format my files inside the `examples` dir without any errors

**Actual behavior:**
Throws  this error
```
Invalid configuration file: Cannot read property 'sync' of undefined
```

This worked prior to `1.14.1`. Is there some workaround to this?

**Comment by ikatyang** [comment]
We updated `cosmiconfig` to v5 in #4899 (1.14.1), which should probably be the cause. But a config file with `.examples` extension is not something we [supported](https://prettier.io/docs/en/configuration.html), we only support config files with no extension (written in JSON/YAML) or one of the supported extensions.

I think the issue here is that the error message needs to be improved, we should open an issue there.

**Comment by alexandernanberg** [comment]
I see, in my case simply renaming the file to `.prettierrc` and moving it the `examples` dir solved the problem.

Thanks!
