### ISSUE TITLE
YAML formatting strips document begin

### ISSUE THREAD

**Issue by pbrisbin** [prettier/prettier#5013]
One thing I've noticed with the new YAML formatting (which is awesome btw!) is that it will strip a standalone (not part of frontmatter) document-separator (`---`). For example, you can see it happen [in this PR diff](https://github.com/pbrisbin/bugsnag-haskell/pull/40/files#diff-54eaec2f732ed7ea540163ee133a989fL1) (a commit made by Restyled, which runs prettier).

I don't have a definitive reference that it's good style to include these document delimiters when they're not strictly necessary, but I tend to include them because:

1. [`yamllint`](https://github.com/adrienverge/yamllint#readme) has a rule (by default) that requires them, and
2. I saw a tweet with this justification (paraphrased):

   If you concatenate multiple YAML documents into some process, e.g.

   ```console
   cat one.yaml two.yaml | some-process
   ```

   Having document-separators in the files will ensure they get processed correctly (as multiple documents). Without the separators, you may silently get something unexpected (smashing of objects) or it might just error.

Because of point (1), it's particularly annoying when ALE runs prettier as an auto-fixer, which strips the `---`, then it runs yamllint as a linter, which complains about its omission...

So, is it intentional to strip it? If so, can an option be added to preserve it?

**Comment by ikatyang** [comment]
We did not have special case for it, we currently just print the necessary part so  any unnecessary parts are removed.

According to our [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html), we avoid to add options if possible unless there're some critical reasons, so the only possible way to go here is to preserve them, but I'm not sure if we should do so since it may introduce inconsistency, let's see how people think about it, marked as needs discussions for now.

---

Regarding `yamllint`, we probably need something like [`eslint-config-prettier`](https://github.com/prettier/eslint-config-prettier) but for `yamllint`, we can refer to those rules but we're not intend to follow any linter's rules.

---

Regarding the `cat` use case, the leading [directives end (`---`)](http://yaml.org/spec/1.2/spec.html#marker/directives%20end/) only works for the case that does not contain [directives](http://yaml.org/spec/1.2/spec.html#id2781147), for example the following case won't work:

```yaml
---
content 1
```

```yaml
%YAML 1.2
---
content 2
```

unless we add the explicit document end as well:

```yaml
---
content 1
...
```

```yaml
%YAML 1.2
---
content 2
...
```

but I think nobody wants these unnecessary document ends, at least I didn't see someone wrote this before.

**Comment by suchipi** [comment]
I think most of our users would find it surprising if we added `---` at the top of every yaml file. They'd see it in their travis.yml, their database.yml, bukkit.yml, etc. I think that `cat`ing documents together is significantly less common than loading single files in as config, so we shouldn't optimize for the use-case of `cat`ing documents together.

**Comment by marcofranssen** [comment]
#5029 filed another issue with different example regarding the same topic

**Comment by ikatyang** [comment]
_From @marcofranssen (https://github.com/prettier/prettier/pull/5027#issuecomment-417288738):_

> The comment approach mentioned above is a workarround. Many kubernetes deployment files generated by tools or available in OSS out there don't have those comments. Meaning if I need to do small change I have to add this unnecessary comment all over the place. Can't we just allow these type of document headers?
> 
> E.g.
> 
> ```
> ---
> some_yaml:
>    some_stuff: abcd
>    more_stuff: ecde
> 
> ---
> some_other_yaml:
>    awesomeness: 123
>    cool:
>      - name: daddy
>      - name: mommy
> ```
> 
> This is some pseudo yamls to explain how many of those kubernetes files are usually available.

**Comment by marcofranssen** [comment]
What about above comment? Is it an option to keep those document headers?

**Comment by mrlesmithjr** [comment]
Simply allowing the option to enable or not to include the `---` in the extension should be good enough to account for everyone's needs wouldn't it? This extension is great but it does affect yamllint as already mentioned and Kubernetes manifests.

Keep up the great work on this extension!

**Comment by j-f1** [comment]
Unfortunately, we [try not to introduce new options](https://prettier.io/docs/en/option-philosophy.html). However, it would be possible to detect and preserve this header.

**Comment by Martimiz** [comment]
1 up for at least allowing it. For instance the SilverStripe framework, My platform of choice, depends on those three --- being allowed as first line. So I too have to constantly be aware and use the # workaround (thanks @ikatyang)

One strange thing I noticed: if I use ... (dot dot dot) instead of ---, dots will be converted to hyphens on the first try, then removed on the next, letting you at least save the correct version, a useful tiny bug that I fear to report :)

Thanks for all the great work!

**Comment by bradh11** [comment]
+1 I do not believe that `---` should not be removed from any yaml/yml files.  As shown on yaml.org reference, the `---` is considered a document header.  I am not sure why this would be stripped as it is part of the YAML spec as referenced here http://yaml.org/spec/1.2/spec.html#id2760395  .

i would strongly suggest that prettier no longer remove YAML document headers or at least give the option to strip or allow it...

Thanks much for the great product...  This is my only complaint!

**Comment by j-f1** [comment]
Let’s keep the leading `---` if it’s present.
