### ISSUE TITLE
How should I contribute?

### ISSUE THREAD

**Issue by pauldraper** [prettier/prettier#5043]
Documentation says

> The core prettier package contains JavaScript and other web-focused languages built in. For additional languages you'll need to install a plugin.

I want to contribute an Angular template formatter. (Angular uses an HTML-like language with an embedded JS-like expression language.)

That's "web-focused", so does that mean that I contribute it here? Or do I contribute it to a separate plugin repo?

Is "web-focused" even the right discriminating factor? YAML, Markdown, and GraphQL are not "web-focused" and yet they are in this repo.

**Comment by ikatyang** [comment]
The Angular formatting should be done in this repo.

Ideally, we should build an unified AST just like ESTree for JavaScript/Flow/TypeScript so that we could print all HTML-like languages consistently, but I'm not familiar with Angular so I'm not sure if it should apply here. (Is Angular template a superset of HTML or it just looks like HTML?)

I found [`@angular/compiler`](https://github.com/angular/angular/tree/master/packages/compiler) after a quick search, you should be able to get its AST from the `parseTemplate` method. See [`CONTRIBUTING.md`](https://github.com/prettier/prettier/blob/master/CONTRIBUTING.md) for more info about how Prettier works.

**Comment by pauldraper** [comment]
> I'm not familiar with Angular so I'm not sure if it should apply here

There are two differences between Angular templates and HTML

1. It is case-sensitive
2. It has an embedded JS-like expression language that would ideally also be formatted.

**Comment by ikatyang** [comment]
It sounds like it should be easy if we switch to this fork https://github.com/StarpTech/parse5 after https://github.com/prettier/prettier/pull/4753#issuecomment-419841048 merged, we just need to extract the `{{}}` part and pass them to the babylon/typescript parser. But we should probably improve the HTML part first since the angular template is based on HTML and our HTML formatting isn't finished yet.

**Comment by ikatyang** [comment]
What's the parsing result for something like `<div>{{a<b&&b>c?0:1}}</div>` in Angular? In HTML, it's `<div>` `{{a` `<b&&b>` `c?0:1}}` `</div>`. If the result from Angular is not same as HTML (i.e., parsed as something like `<div>` `{{` `a<b&&b>c?0:1` `}}` `</div>`), we'll have to use the official Angular parser and transform its ast format to ours.

**Comment by pauldraper** [comment]
The first.

In other words, it can always be parsed by an HTML parser, modulo case
sensitivity.

**Comment by voithos** [comment]
As of v1.15.0, I believe Prettier supports Angular template formatting. https://prettier.io/blog/2018/11/07/1.15.0.html
