### ISSUE TITLE
Functional Composition Heuristic Is Too Broad

### ISSUE THREAD

**Issue by bdwain** [prettier/prettier#5060]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0pzDAFAMwhAGgAIAjAQwCcBKEAkCABxgEtoBnZUSiiAdwAVKCDijIA3CMwAmtECQpkwAazgwAyg0XMoAc2QwKAVzh1tbOBRj8FOgLZlkOMgBtzdAFZsAHgCEFy1TUyWzgAGW04Rxc3EE0KcwpkOTISAE9naFkGCm0YAHVpGAALZAAOAAY6bIhzPIUGJOy4BLFIugo4AEdDZg7rMjsHJCdXExBzW2Z9IzG2bR1nOABFQwh4KNG6GBSCqWLkACYthWZneYBhCFt7JKhoNpBDcwAVFJER8wBfT6A)
```sh
--parser babylon
```

**Input:**
```jsx
connect(foo, bar)
```

**Output:**
```jsx
connect(
  foo,
  bar
);

```

**Expected behavior:**
The functional composition heuristic discussed in #4172 is too broad. If I am not using Redux, the above styling is ugly and annoying. And even if I am using redux, if I don't define `mapStateToProps` and `mapDispatchToProps` inline, it's ugly and annoying to split that on multiple lines.

Rather than have prettier assume you are using all libraries, could I not list the libraries I am using in my config file? I'd rather opt in to redux specific styles than have them applied to my non-redux project.

In general though, it seems odd to hard code certain libraries anyway. It will leave prettier in the position of always judging which libraries are popular enough to support, and limits its support for less popular libraries. Why not consider an approach like the one mentioned in [this comment](https://github.com/prettier/prettier/issues/4172#issuecomment-377726296)? It seems like the eventual solution was proposed in the very next comment and no one really ever replied to this one. I think it would be much better than picking and choosing which libraries get full support.

**Comment by suchipi** [comment]
Thanks for opening this issue. This is something that I agree is subpar right now and there are a few different ways of solving it but I don't know which would be the best for prettier.

See also https://github.com/prettier/prettier/issues/4751 and https://github.com/prettier/prettier/pull/4758 for prior discussion. We are hoping that https://github.com/prettier/prettier/issues/4424 can solve this problem but we haven't designed that API yet because it's not clear where the constraints should be.

**Comment by bdwain** [comment]
Cool. Well I'm glad the problem is being thought about. Just wanted to get my thoughts out there. Thanks!
