### ISSUE TITLE
unnecessary parens in while with assign

### ISSUE THREAD

**Issue by evilebottnawi** [prettier/prettier#5070]
**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AFgSwDZwAQAUAJAG4CGATngLx4CMAlHsAL4gA0IEADjJtAGdkoShQioACpQRCUZEhEwATDiABGFMmADWcGAGVuWzFADmyGBQCucTiYFwKMCZtMBbMsgBmZbA84AVgIAHgBCmjp6+mRucAAyJnDevv4gRhQOFMjqZGoAntjQqtwUJjAA6sow6MgAHAAMnCUQDuWa3NklcJkkSZwUcACOVpgDLmTunkg+frYgDm6YFtZzAiamuACKVhDwybOcMLmVStXIAEyHmjjrAMIQbh7ZUNB9IFYOACq5sjMOLCwgA)
```sh
--parser babylon
```

**Input:**
```jsx
while ($var = 1) {}
```

**Output:**
```jsx
while (($var = 1)) {}

```

**Expected behavior:**

```jsx
while ($var = 1) {}
```

-----

Edge case.

**Comment by lydell** [comment]
As far as I remember, this is intended to show that you actually intended to do assignment and not comparison. See also: https://eslint.org/docs/rules/no-cond-assign

**Comment by evilebottnawi** [comment]
@lydell intresting, `switch (i = 1) {}` also add unnecessary string `switch ((i = 1)) { }`

**Comment by lydell** [comment]
And `if`.

**Comment by j-f1** [comment]
Looks like those are already the case:

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB3AFgSwDZwAQAUAJAG4CGATngLx4CMAlHsAL4A6UmAZoaZTfSasOAZ1SYYYdL3JVajZuyjiY04rIELhUEABoQEAA4xM0EclCUKEVAAVKCcyjIkImACZ6QAIwpkwANZwMADKhv6YUADmyDAUAK5w+pEicBQwtn5RALZkyFxk2Kn6AFYiAB4AQn6BwSFk2XAAMpFw+YXFIOEUqRTIPmTeAJ7Y0F6GFJEwAOoeqsgAHAAM+hMQqdN+hv0TcL0kbfoUcACO8ZjHmWQ5eUgFRUkgqdmYsQmPIpFRuACK8RDwdoPfQwQazdzzJAAJhBfhwXwAwhBsrl+lBoIcQPFUgAVQZOe6pFgsIA)
```sh
--parser babylon
```

**Input:**
```jsx
while ($var = 1) {}
if ($var = 1) {}
switch ($var = 1) {}
with ($var = 1) {}

```

**Output:**
```jsx
while (($var = 1)) {}
if (($var = 1)) {
}
switch (($var = 1)) {
}
with (($var = 1)) {
}

```

Closing since this is intended.

**Comment by evilebottnawi** [comment]
@j-f1 hm, why it is expected? Looks very ugly

**Comment by vjeux** [comment]
This is to prevent the mistake of trying to do "a == 1" but writing "a = 1" and subtly getting it wrong. If you see a double parenthesis then it's obvious that you are doing an assignment.
