### ISSUE TITLE
use tabs option (and other options?) not respected in tagged template literals

### ISSUE THREAD

**Issue by dontsave** [prettier/prettier#5124]
In tagged template literals such as gql\`\` and styled\`\`, prettier does not seem to be adhering to formatting options. Specifically "use tabs" doesn't work in either of these template strings. Writing css in a .css file, and writing graphql in a .graphql file works fine, but when the same code is in template literals prettier reverts to using 2-space indentation.

**Comment by dontsave** [comment]
interestingly, I just noticed that this is not the case with generic tagged template literals:

```
const f = (a: TemplateStringsArray) => null;

f`
	test {
		test {
			foo
		}
	}
`;

```

this adheres to the correct tabs formatting, which must mean that the issue is specific to prettier's attempts to format specific ttl's like gql and styled.

**Comment by lydell** [comment]
It seems to be working on the playground. Could you clarify what your issue is?

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBzAjgGwAYB0oAEB6ArnAE4CeBw+RR8AzjDXfUQGYQRtEC+bAVGwgANCAgAHGAEtojZKACG5chADuABRUIFKJQDcIMgCZiQAI3JKwAazgwAypJsyoqZDHJlxbxhRhNa1QAWyVkDiVMf3EAK0YADwAhazsHRyUQuAAZNzgIqJiQF3J-cmRLJQtKTGhzSXI3GAB1UxgAC2QADgAGcQaIf2brSQqGuDKDfPFyOFIZWaClUPCkSOi4cX8QmU9vTZBGN1RMOABFEgh4Ao3xGCrWkw7kACY76xlMY4BhCBCwipQaDTEAkfwAFSqei8ZD4fCAA)
```sh
--parser babylon
--use-tabs
```

**Input:**
```jsx
gql`
  query {
    test {
      foo
    }
  }
`
```

**Output:**
```jsx
gql`
	query {
		test {
			foo
		}
	}
`;

```

**Comment by dontsave** [comment]
The issue happens in VSCode. Have you tested it there?

I just did a new test in which I disable all extensions except prettier.  Then in a blank file, test.tsx:

```
import styled from "styled-components";

styled.div`
	a {
		color:red
	}
`;

```

becomes

```
import styled from "styled-components";

styled.div`
  a {
    color: red;
  }
`;

```

which isn't expected behavior given prettier's use tabs option being enabled. Further, when I then disable prettier and rewrite the above with tabs, vscode leaves the tabs in place. So prettier seems to be ignoring the use tabs option within that t

**Comment by ikatyang** [comment]
@dontsave I'm still not able to reproduce the issue in VSCode/playground, I guess there're some `.editorconfig` or `.prettierrc` in your current/parent directory, which we resolve options from them.

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgGcYBPAGzgBN8AzHCdfAHRGPKoFpItoEZCWAbiZQRbCpQB0lVADcABiKYwAhvmBKYyyGVxIcVTQF8R84VBAAaEBEwxU0QslAqc9AO4AFVwicoVshColFYgAEY4KmAA1nAwAMqYUahQAObIMDgArnDWKYRweJ6RqegqyDQqZAXWAFaEAB4AQpExcfEq6HAAMilwFVU1IEk4BTjIIKSYcIRgOKh2oZjzsADqwTAAFsgAHAAM1ssQBauRmBPLM4Wy-dYGAI5ZqAbFKqXlSJXVuaxw6KgZbI-QgpVIUACKWQg8AG32sqjC60oW2QACZ4ZFUGRQQBhBhlCZQXihLIFAAqKjCfkyOSMRiAA)
```sh
--parser typescript
--use-tabs
```

**Input:**
```tsx
import styled from "styled-components";

styled.div`
	a {
		color:red
	}
`;

```

**Output:**
```tsx
import styled from "styled-components";

styled.div`
	a {
		color: red;
	}
`;

```

If there's no `.editorconfig` or `.prettierrc`, you should probably report this issue to [`prettier-vscode`](https://github.com/prettier/prettier-vscode/issues) as this issue seems VSCode-specific, and this repo only tracks issues that can be reproduced on the playground or from the API/CLI.
