### ISSUE TITLE
A way to make sure that no prettier formatting is done between the symbols

### ISSUE THREAD

**Issue by anishmittal2020** [prettier/prettier#5130]
Prettier supports Commonmark. But some of us do us other markdown (like Pandoc) which has some additional symbols which won't get recognized by prettier leading to broken Pandoc. Almost all of my content follows commonmark, but a small set follows Pandoc.

It would be creat if I could add my Pandoc specific formatting by inserting it between HTML comments like  `<!-- NoPrettier -->`. If prettier doesn't format content between 2 of this comment, it could solve the purpose.

**Comment by ikatyang** [comment]
I guess [`requirePragma`](https://prettier.io/docs/en/options.html#require-pragma) (`<!-- @prettier -->`) should be what you're looking for? though it's about enabling instead of disabling.

**Comment by ikatyang** [comment]
Oops! I guess you meant [`<!-- prettier-ignore -->`](https://prettier.io/docs/en/ignore.html#markdown).

**Comment by anishmittal2020** [comment]
Thanks. Although it might be useful to add another option to disable it (most of the people might like to use Prettier more often and only in small exceptions where they want to disable it).

**Comment by ikatyang** [comment]
@anishmittal2020 Did you mean file-level ignore or the node-level one?

**Comment by anishmittal2020** [comment]
No I meant node level, what you mention should do. But please look at this :
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UAxADocACVJ8cnHC0YATORKkz5LWbIBmjdTj5CcAIQCecPhmz4iJcpRp0GCWZ0y8ofEABoQEPGWiNkoGwEEADuAApsCP4oLABuEKSyHiAARgQsYADWxADKeBmkUNTIMAQArnCehYwUMGHp1AC2LMjqLAA2NZ4AVowAHvrpWbksjXAAMoVwrR1dIPkENQTIIM0EmbKhUMmEhTAA6okwABbIABwADJ6EEDX76XgrhHBLsdOeRACOZaRE9SxNFpINqdSogGqNUglcpgxiFajtOAARTKEHgM1BnlYKUOshOyAATFj0qR2vCAMIQRrNFZ0KDvEBlGoAFRYKWiIJqAF8uUA

**Comment by ikatyang** [comment]
You should probably place leading/trailing newlines arround them so that it won't be parsed as something else. The `<!-- prettier-ignore-end -->` in your example was parsed as a comment in a list, which won't trigger the top-level ignore magic.

**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAhAWkwAgA4BOcMMAlnAZqQOZQRGYDOMAhgTDtgHwA6UfAYgB0OABKk+OTjhaMAJvMnTZClnLkAzRhpyCRAIQCecPnwzZ8REuUo06DBHM6Ze-KCAA0ICHjLRGyKBsBBAA7gAKbAgBKCwAbhCkcp4gAEYELGAA1sQAyniZpFDUyDAEAK5wXkWMFDDhGdQAtizIGiwANrVeAFaMAB76Gdl5LE1wADJFcG2d3SAFBLUEyCAtBFlyYe5ehEUwAOpJMAAWyAAcAAy7IbUHGXirhHDLcTNeRACO5aREDSzNVpIdpdKogWpNUilCpgxhFagdOAARXKEHgs1BXlYqSOclOyAATFiMqQOvCAMIQJotVZ0KDvEDlWoAFRYqRiINqAF8uUA)
```sh
--parser markdown
```

**Input:**
```markdown
<!-- prettier-ignore-start -->

#. Hi
  - asdsd
  - asdsaddfsf 
#. Bye

<!-- prettier-ignore-end -->


```

**Output:**
```markdown
<!-- prettier-ignore-start -->

#. Hi
  - asdsd
  - asdsaddfsf 
#. Bye

<!-- prettier-ignore-end -->

```
