### ISSUE TITLE
Why does Prettier format hexadecimal numbers as lowercase, and can a switch be added to make them uppercase?

### ISSUE THREAD

**Issue by j0hnm4r5** [prettier/prettier#5158]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEAEnADYkQDqEATiQCYAUAlPsADpT7VwzrWcAGAB4BBAEIBhACIBRAGIBuDgF8QAGhAQADrmgBnZKACG1ahADuABRMIDKIwDcIOOupAAjakbABrHgGUtbxwoAHNkGGp0OA0QvThqGEsvUIBbI2RUIxJ4jQArPSExL18Ao1S4ABkQuEzs3JAg6njqZA8jdwBPcig3LWoQmAoXGAALZAAOAQ1+iHiKLy02-rgWh1qNbgBHdBxuZKM0jKQsnJiQeNScCKjzvRDQkjgARXQIeDqzjRgO4box5AAJm+XhwJAeEggqXSbSg0A2IHQ8QAKh07Kd4splEA)
```sh
# Options (if any):
N/A
```

**Input:**
```jsx
function HelloWorld() {
 return 0xABCDEF;
}
```

**Output:**
```jsx
function HelloWorld() {
  return 0xabcdef;
}
```

**Expected behavior:**

Hex values with lowercase letters are harder to read than hex values with uppercase letters (see [here](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/number-literal-case.md) for an ESLint rule explaining it). Prettier's defaulting to lowercase is weird, but if the default won't be changed, a flag should be implemented to allow switching to uppercase.

**Comment by lydell** [comment]
Hi, thanks for the issue! I made the PR that normalizes numbers. Personally I prefer uppercase too, but I was asked to do lowercase: https://github.com/prettier/prettier/pull/498#issuecomment-275856264

These days, Prettier also lowercases hex colors in CSS. I think that Prettier should be consistent and use the same case for both JS and CSS. But changing this would cause a lot of unnecessary churn for all Prettier users.

Unfortunately, this decision has been made and is not going to change. An option won't be added – see our [option philosophy](https://prettier.io/docs/en/option-philosophy.html).

If you care deeply about this you can use [prettier-eslint](https://github.com/prettier/prettier-eslint) to autofix the hex numbers to uppercase using the rule you linked to.

Like I said, personally I also prefer uppercase, but since I started using Prettier I don't care as much any more. I rarely use hex literals anyway.
