### ISSUE TITLE
typescript: unneeded parentheses around type annotation aren't removed

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#5247]
**Prettier 1.14.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgGIQQ7AA6UOOARugE5I4AUDAlDgLwB8Vhqc6UzANxkAviAA0ICAAcYAS2iZkoWjQgB3AAq0ESlOgBuEOQBMJISjXRgA1nBgBladblQA5shg0ArnEmvMOBoYTSs3AFt0ZAAzdFRAyQArTAAPACErW3sHdHC4ABlXOBi4hJBnGkCaZBAYAE9pOEwwGjlZc2lW2AB1UxgAC2QADgAGSU6IQO6raRrOpqCDYskaOABHbzlV0PQIqKRY+L8QQPC5Tx9jzFc3XgBFbwh4EqPJGHRKXpMB5AAmN6sclQNwAwhBwpEalBoMsQN5AgAVD56Q6BEQiIA)
```sh
--parser typescript
```

**Input:**
```tsx
class Foo {
  bar: (() => boolean);
}
```

**Output:**
```tsx
class Foo {
  bar: (() => boolean);
}

```

**Expected behavior:**
```tsx
class Foo {
  bar: () => boolean;
}

```

**Comment by flurmbo** [comment]
This seems to be fixed by removing [this line](https://github.com/prettier/prettier/blob/3de36e3a2b7bda9185458a8fe12ac5b6bb6b4433/src/language-js/needs-parens.js#L342) from src/language-js/needs-parens.js.

This line is basically saying that if a parenthesized type annotation is an annotation of a function type, then the parenthesis should be kept.

Removing this line does not break any of the tests so I've gone ahead and made a PR, but someone more familiar with Pretier's codebase should probably check that this doesn't have any other side effects. Specifically, in printer-estree.js, there are some conditions in which parenthesis are added to a TSFunctionType.
