### ISSUE TITLE
If list-different detects differences, it should print command for fixing

### ISSUE THREAD

**Issue by melissachang** [prettier/prettier#5277]
It would be nice if `list-different` printed the command for fixing (`prettier --write <files>`) if it detected differences. This way, someone doesn't have to hunt down the syntax.

**Comment by daubaris** [comment]
hi! I'd love to work on this!

**Comment by kachkaev** [comment]
@melissachang I agree with you that printing a command for fixing is a good idea! See https://github.com/prettier/prettier/issues/5520 with some thoughts on this.

**Comment by kx-chen** [comment]
Any chance I could pick this up?

**Comment by lydell** [comment]
Sure!

I think we should leave `--list-different` as it is and add this to `--check`.

### Alternative 1

```
prettier --check "**/*.{css,html,js,md,yml}"

Checking formatting...
html/all-types/index.html
html/experiments/viewport/script.js
Code style issues found in the above file(s). Forgot to run Prettier?
Running something like this should fix the issues:
prettier --write "**/*.{css,html,js,md,yml}"
```

### Alternative 2

```
prettier --check "**/*.{css,html,js,md,yml}"

Checking formatting...
html/all-types/index.html
html/experiments/viewport/script.js
Code style issues found in the above file(s). Forgot to run Prettier?
Running something like this should fix the issues:
prettier --write html/all-types/index.html html/experiments/viewport/script.js
```

### Alternative 3

```
prettier --check "**/*.{css,html,js,md,yml}"

Checking formatting...
html/all-types/index.html
html/experiments/viewport/script.js
Code style issues found in the above file(s). Forgot to run Prettier?
Check how your project runs Prettier! Here are some common ways:
prettier --write path/to/file.js
npm run prettier
????
```

### Alternative 4

Anyone has other ideas?

### Things to think about

- Should we prefix the suggested command with `npx` to increase the chance of the command actually working?
- We need to handle file names with spaces in them / shell quoting if we print globs or file names.

/cc @kachkaev since you came up with the nice `--check` flag.

**Comment by kx-chen** [comment]
Awesome! Thank you so much for the fast reply. 

I personally prefer Alternative 1; it seems simpler. 
Additionally, I think prefixing with `npx` for a high chance of it working is a good idea as well.

I can submit a PR with the general changes, and I'm sure we can discuss more then.

**Comment by kx-chen** [comment]
Actually, on second thought, it seems like using approach 2 works better. It feels more explicit, and might have a lower chance of changing files that were not intended on being changed.

**Comment by kachkaev** [comment]
IMO _alternative 1_ (`prettier --write "**/*.{css,html,js,md,yml}"`) is the least evil. Enumerating unformatted files explicitly does not scale (the command can get very long) and listing all alternatives will probably bring more confusion than help.

As far as I understand, there is no way to determine whether prettier was executed via `npx`, via a globally installed CLI command, via a `package.json` script, via `npm prettier` / `yarn prettier` or by typing `path/to/node_modules/.bin/prettier`. All we have access to is the list of applied options (`--config`, `--ignore-path`, etc.). Even if all these options are relayed to the proposed `--write` command, there is no guarantee the command will work because we won't be able to guess how it was called in the first place.

**Comment by lydell** [comment]
@kachkaev That makes a lot of sense.

**Comment by lydell** [comment]
We explored this a little in #6406, but as mentioned there and in the above two comments we decided to leave things as they are.
