### ISSUE TITLE
Support for .html.eex files?

### ISSUE THREAD

**Issue by x-ji** [prettier/prettier#5286]
`.html.eex` is the HTML template for Elixir. It's mostly HTML but with some custom syntax for templating. Currently I can try to format such files as HTML manually, but that sometimes results in syntax errors. Would it be possible for Prettier to also support some HTML templating languages?

**Comment by evilebottnawi** [comment]
@x-ji please use issue template

**Comment by x-ji** [comment]
Sorry. I thought this one doesn't fit either of the templates so I just clicked on "open a regular issue".

**Comment by suchipi** [comment]
Could you show an example of how it looks?

**Comment by x-ji** [comment]
An example:

```
<div id="test-container" data-text="<%= produce_test_content(@test) %>" data-testid="<%= @test.id%>" 
  <%= if assigns[:test_record] do %>
  data-a="<%= @test_record.a%>" data-b="<%= @test_record.b%>"
  <% end %>
>
</div>
```

which would just result in SyntaxError in the [online playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AJPoC8AOiPAM4wC0ksAhplHAE6m7p0x1XwAeMJNAFJCuAA7MI6AK5g4AfQox5teLAAUAASUBKXEIB8bDlx5xKBQahG5t5mADoChtsSi5c10ZgBmuOuTkmADmUOQA2khK8sxwkMzoALrsEPpG7uyc3HRWNnaUMXEQCQ50LiCZpgBGuaL5yrHx6A5V5W4e1rgI6Glu6agA9FjYBiAANCAQYjCY0OTIoHTMkgDuAApLCPModNgQBOMgVcx0YADWcDAAymKnjMHIMMzScBOM5CwwayfBALZ0yB8dAANh8JgArci8ABCJ3OlyudF+cAAMow4ICQWCQLdmB9mMgjnQqgBPYHQQ4SRgwADqBBgAAtkAAOAAMEwkEA+NJOYkJEnMLGwGImsQAjtJMLFvnQ-gCkEDQa8QB9fphHs9lUEoMFgXAAIrSCDwTFKiZcKp09CM5AAJnNJ0wwPuAGEIL9-oSoNARSBpB8ACrE7aKj4AXzDQA)

However if I set the syntax to HTML and run Prettier-vscode, it does produce a result, albeit one with syntax errors:

```
<div id="test-container" data-text="<%= produce_test_content(@test) %>" data-testid="<%= @test.id%>" <%=if
  assigns[:test_record] do %>
  data-a="
  <%= @test_record.a%>" data-b="
  <%= @test_record.b%>"
  <% end %>
  >
</div>
```

I understand that it might not be easy/might not be a priority for Prettier to support new languages. I was just wondering about whether there could be possible future support for template languages such as `.eex` used by Elixir and also `.erb` used by Ruby, etc.

**Comment by claytonrcarter** [comment]
Now that HTML is supported, there seem to be a number of issues opening up about how to use Prettier on HTML templates:

#5286 (this issue, or eex/Elixer & erb/Ruby)
#5556 (PHP)
#5428 (JS?)
https://github.com/prettier/plugin-php/issues/845 (PHP)
https://github.com/prettier/plugin-php/issues/846 (PHP)

@ikatyang & @suchipi would ignoring the contents of some tags (treating them as 0 length strings and leaving them as-is) be a way to handle templates or am I oversimplifing things? For example, ignore everything between `<?php ... ?>` or `<%= ... %>`. This would probably handle most cases, and we would still have `<!-- prettier-ignore -->` to handle some remaining/tricky edge cases. (Like @evilebottnawi example at https://github.com/prettier/plugin-php/issues/845#issuecomment-439933691.)

**Comment by x-ji** [comment]
At least in the case of Elixir indentation is not a part of the syntax and not a concern. Ignoring all Elixir code would be fine as long as the HTML is correctly formatted.

**Comment by ikatyang** [comment]
It should be easy to preserve template language that uses `<? ... ?>`, since `<? ... ?>` is actually treated as comments in the HTML spec. If `<? ... ?>` is placed in some places that violate the HTML spec (e.g., `<a href="<? hello ?>">`), the following section is applied to it as well.

For other template languages (e.g., `eex` or `erb`), it should be just a matter to use placeholders to replace them before formatting and put them back after formatting. Though it's simple to preserve them but we need a parser to parse it and currently there's no plan to fully support them so I think this should not be added in this repo. If you're interested to implement such plugin, you need to:

- find a parser (written in js would be the best, but you could use `child_process` to pass its AST as JSON if it's not js.)
- read this function for how placeholder works in lit-html (`` html`<div>hello ${name}</div>` ``): https://github.com/prettier/prettier/blob/4dd7c79bbf33dcdf189d1fa3c792b8cfcb5ef7bf/src/language-js/embed.js#L567 
- build a plugin: https://prettier.io/docs/en/plugins.html 

NOTE: the indentation for control flow blocks won't be preserved just like what @suchipi mentioned in https://github.com/prettier/prettier/issues/5286#issuecomment-432528587, unless you replace `<%= if %>` with a opening tag and replace `<% end %>` with a closing tag to convince the HTML printer.

**Comment by Hentioe** [comment]
Any progress on support for `.eex`/`.leex`?

In fact, `.eex` doesn't have a custom syntax, just embed the elixir code with <% … %>. This is the simplest type of template for embedding language code.

**Comment by dbishai** [comment]
Just wanted to add that [js-beautify](https://github.com/beautify-web/js-beautify) supports this: https://github.com/HookyQR/VSCodeBeautify/issues/33

Simply add this line to your settings
```
"beautify.HTMLfiles": ["htm", "html", "eex"]
```

**Comment by joshchernoff** [comment]
🙏please, I'd help but not sure where to start.

**Comment by dev-cyprium** [comment]
I quite enjoy prettier, and I would love to have it supported for `.html.eex` files.
Agreed with the discussion upwards, `.eex` the syntax is simple and I think it's a good suggestion to just skip it, and just format the HTML.

Please, support this templating language.

**Comment by thorn0** [comment]
Prettier isn't going to add more languages to the core. This should be implemented as a plugin.

**Comment by joshchernoff** [comment]
Any docs on how to start on a plugin?

**Comment by thorn0** [comment]
https://prettier.io/docs/en/plugins.html#developing-plugins
