### ISSUE TITLE
Vue Formatting Question

### ISSUE THREAD

**Issue by dtrinh100** [prettier/prettier#5385]
**Prettier 1.15.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeAJgSwG6pgA2AhgM5kC8AOuNDCTlHAE60B81U66GAEhAC2cPqgD0nbj35C4AQXGSemAcIAairspnCAmpqkYxuPOxAAaEBAAOMHNDLJQJFiwgB3AAouEjlCTwIHCwLEAAjFhIwAGs4GABlayimAHNkGBYAVzhLAAsYQSIAdVyceDIksDh43zL8MoBPZHAKUKYyVhhPSJTBEmQAMxIiDssAKzIADwAhSJi4+JJhABkmOEHh0ZAJyfjUojgARUyIeA2RnJAklg6WZrxs0OsWJhgi4Jhc5AAOAAZLZ4QDpFSLWZrPOC3PDrSwsOAAR0yODh3RIvX6SCGF0sHUEOHSWUuZH2RxOZ0xm0uDDC7ywn2QACZLBlGERUgBhIR9ZpQaAwkCZDoAFRIYT8WI6AF9JUA)
```sh
--parser vue
```

**Input:**
```vue
  <div class="container">
    <HomeH />
    <HomeA />
    <HomeX />
    <HomeY />
  </div>
```

**Output:**
```vue
<div class="container"><HomeH /> <HomeA /> <HomeX /> <HomeY /></div>

```

**Expected behavior:**
I am not sure if this was intended, but I was expecting the formatting to keep the original input rather than putting them all in a single line.

**Comment by aaaguirrep** [comment]
I had the same issue with the last version. I uninstalled and installed the 1.14.3 version.

**Comment by Xotic750** [comment]
Same issue here

An example is
```
      <span :class="TOOLBAR_BUTTON + '-icon'">
        <i :class="buttonIcon">
        </i>
      </span>
```
Which are the rules we have defined for Vue for use with `eslint-plugin-vue`

And running prettier it changes to
`<span :class="TOOLBAR_BUTTON + '-icon'"> <i :class="buttonIcon"> </i> </span>`

And worse when run with Eslint, which includes `eslint-plugin-prettier` we get
```
      <span :class="TOOLBAR_BUTTON + '-icon'">
<i :class="buttonIcon">
</i>
</span>
```

**Comment by ikatyang** [comment]
The fix is available in [`1.15.2`](https://github.com/prettier/prettier/blob/master/CHANGELOG.md#1152).

**Comment by aaaguirrep** [comment]
Hi, i have installed the last version but the issue continues.

**Comment by ikatyang** [comment]
I guess your issue is different than this one, can you open a new issue?

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACVAeAJgSwG6pgA2AhgM5kC8AOuNDCTlHAE60B81U66GAEhAC2cPqgD0nbj35C4AQXGSemAcIAairspnCAmpqkYxuPOxAAaEBAAOMHNDLJQJFiwgB3AAouEjlCTwIHCwLEAAjFhIwAGs4GABlayimAHNkGBYAVzhLAAsYQSIAdVyceDIksDh43zL8MoBPZHAKUKYyVhhPSJTBEmQAMxIiDssAKzIADwAhSJi4+JJhABkmOEHh0ZAJyfjUojgARUyIeA2RnJAklg6WZrxs0OsWJhgi4Jhc5AAOAAZLZ4QDpFSLWZrPOC3PDrSwsOAAR0yODh3RIvX6SCGF0sHUEOHSWUuZH2RxOZ0xm0uDDC7ywn2QACZLBlGERUgBhIR9ZpQaAwkCZDoAFRIYT8WI6AF9JUA)
```sh
--parser vue
```

**Input:**
```vue
  <div class="container">
    <HomeH />
    <HomeA />
    <HomeX />
    <HomeY />
  </div>
```

**Output:**
```vue
<div class="container">
  <HomeH />
  <HomeA />
  <HomeX />
  <HomeY />
</div>

```

**Comment by aaaguirrep** [comment]
Done, #5441.
