### ISSUE TITLE
Default to template literal strings

### ISSUE THREAD

**Issue by KyleAMathews** [prettier/prettier#54]
This would probably be a controversial decision but template literal strings are just better. No escaping, easy interpolation, multiline when needed, etc.

This article by @bevacqua introduced me to the idea https://ponyfoo.com/articles/template-literals-strictly-better-strings and I've been using straight template literal strings in Gatsby for the past month or so with great success. Can't imagine going back to the morass of single vs. double quotes now.

**Comment by bakkot** [comment]
That would generate a different program, even if it's semantically the same.

Also, it would make this project unusable for people writing ES5.

**Comment by bevacqua** [comment]
I don't see generating a different program as an inherent problem, but @jlongster probably has a better idea of where he wants `prettier` to head.

Regarding ES5, you could just make it an option instead of `singleQuotes`, have a `quotes` option with one of `` [`backtick`, `single`, `double`] ``.

I suppose this tool will only ever support ES6+ due to complexity (if not, do they turn generators into plain functions with `switch` statements, etc? leads to ugly code)

**Comment by bakkot** [comment]
Syntactically ES5 is a subset of ES2015 (modulo some [obscure cases](https://tc39.github.io/ecma262/#sec-additions-and-changes-that-introduce-incompatibilities-with-prior-editions) like the interpretation of `let[a]`), so if it supports ES2015+ it supports ES5. But I agree that this would be solved by providing it as an option.

I maintain that would be bad, though. Template literals aren't strings: ``function f(){`use strict`;}`` is not a strict function, ``import `b`;`` is not valid syntax, etc.

**Comment by bevacqua** [comment]
That's never a problem in actual programs, particularly if you're running build tools like this one, that can and will shout at you for writing incorrect programs. In practice, using template literals by default means you can smoothly add interpolated expressions, something that is a hassle if you're defaulting to single or double quoted strings because of all the back and forth (remove quotes, add backticks, add interpolation, repeat in reverse if you remove all interpolations, etc)

**Comment by demoneaux** [comment]
IMO, this doesn't belong in Prettier. Changes like these will modify the AST, and they probably should be done in a separate step or as part of a Babel plugin or JS codemod, instead of in Prettier which is simply a JavaScript formatter which aims to pretty-print the current AST.

**Comment by jlongster** [comment]
The good thing is that if you write with template literal strings, we will output template literal strings. This formatter is not so opinionated that is overwrites everything into a single authoritative style. It never converts AST nodes into different types, etc.

I don't know exactly where this will head, but I do know that I want to take it slowly. I think it would be surprising to a lot of people if they typed double-quotes and they were automatically converted into a template literal. For now, I'd prefer to keep whatever the original string type was. (We do force either double or single quotes, naturally, because those compile to the same AST node type so the user can choose what to output because it's ambiguous what we should do.)

If there are any problems with template literals, let me know. Simply having the formatter is probably divisive enough so I don't want to make it any more opinionated than it has to be. I think things like this could be aided by other tools. I'm open to making it easier to integrate with other tools that can transform the AST (i.e. pass the AST elsewhere, maybe babel plugins).

**Comment by vjeux** [comment]
We are unlikely going to support this. Closing this in order to clean up the issue list.

**Comment by lydell** [comment]
Also, this can be achieved with `eslint --fix` using the [quotes](http://eslint.org/docs/rules/quotes) rule.

**Comment by jasonkuhrt** [comment]
FYI It looks like [`dprint`](https://dprint.dev/) is going to support this https://github.com/dprint/dprint-plugin-typescript/issues/345.
