### ISSUE TITLE
Strange Vue Formatting when used with :class

### ISSUE THREAD

**Issue by dtrinh100** [prettier/prettier#5437]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeKBDAbgPgDpSoYAEYANhgM6UC8eI8lMAllAOb3FLlW33AByRi3YCuxAITNKAOQgwANMQBGMKEmLSAKnCas2AX04ALAE5wAZnRAB6ejh172qGxnyESPateH7O3Cm9+IV0RNjENKVl5JQsICA1pACEMUyMQYjNLazsQB1D9FzcCF0xcEAUQCAAHFmhKZFBU0wgAdwAFVIQGlGwIZgATCpBlUwwwAGs4GABlavH9ZBhTAFc4SuMYAFsyAHVjZkZ5sDgZ7sPmLEOAT2RwamHWSjhTGHaxti2MZAsMMmfKgArSgADySY0m0xmGC2cAAMqw4D8-gCQMCQTN9GQ4ABFFbyJFIX7-dYgeamZ6mO5YNbDaqmVgwXaDGDGZAADgADJV6RBnrsxtU7vTdC8sEjKuYAI4rZjmd4YT7fIko0nPLbMJarNVY3H4+DIkmVGAYZTMgas5AAJmNY2YZH0AGEIFsvncoNAJSAVs8tKaesTngYDEA)
```sh
--parser vue
```

**Input:**
```vue
<nav>
<a class="testing" :class="{'testing' : !isNot, btn: isTesting}" href="/">Testing</a>
<a class="testing" :class="{'testing' : !isNot, foo: isBar}" href="/">Testing</a>
</nav>
```

**Output:**
```vue
<nav>
  <a class="testing" :class="{ testing: !isNot, btn: isTesting }" href="/"
    >Testing</a
  >
  <a class="testing" :class="{ testing: !isNot, foo: isBar }" href="/"
    >Testing</a
  >
</nav>

```

**Expected behavior:**

I would expect the closing bracket of the a tag to stay with the tag itself, but it's instead pushed down a line.

**Comment by hawkrives** [comment]
It's because `<a>` is an inline tag, so if Prettier added whitespace to the HTML it would show up in your browser – see https://prettier.io/blog/2018/11/07/1.15.0.html#whitespace-sensitive-formatting for more detail

**Comment by ikatyang** [comment]
For example, this is how it looks like with a little css highlighting:

```css
a:first-child {
  background: rgba(128, 128, 128, 0.5);
}
```

![image](https://user-images.githubusercontent.com/8341033/48307706-6ad08500-e58d-11e8-9ae8-df253c1b6b61.png)

```html
<nav>
<a class="testing" :class="{'testing' : !isNot, btn: isTesting}" href="/">Testing</a>
<a class="testing" :class="{'testing' : !isNot, foo: isBar}" href="/">Testing</a>
</nav>

<nav>
  <a class="testing" :class="{ testing: !isNot, btn: isTesting }" href="/"
    >Testing</a
  >
  <a class="testing" :class="{ testing: !isNot, foo: isBar }" href="/"
    >Testing</a
  >
</nav>

<nav>
  <a class="testing" :class="{ testing: !isNot, btn: isTesting }" href="/">
    Testing
  </a>
  <a class="testing" :class="{ testing: !isNot, foo: isBar }" href="/">
    Testing
  </a>
</nav>
```

**Comment by ikatyang** [comment]
There're some good explanation [here](https://medium.com/@patrickbrosset/when-does-white-space-matter-in-html-b90e8a7cdd33) (link from #5382), though we did not take the _"across two separate inline elements"_ part into account at the moment, but since the current formatting is stricter, there shouldn't be any issue about it. We should improve that part in the future.

**Comment by phamhongphuc** [comment]
It's because of `print-width`

**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeKBDAbgPgDpSoYAEYANhgM6UC8eI8lMAllAOb3FLlW33AByRi3YCuxAITNKAOQgwANMQBGMKEmLSAKnCas2AX04ALAE5wAZnRAB6ejh172qGxnyESPateH7O3Cm9+IV0RNjENKVl5JQsICA1pACEMUyMQYjNLazsQB1D9FzcCF0xcEAUQCAAHFmhKZFBU0wgAdwAFVIQGlGwIZgATCpBlUwwwAGs4GABlavH9ZBhTAFc4SuMYAFsyAHVjZkZ5sDgZ7sPmLEOAT2RwamHWSjhTGHaxti2MZAsMMmfKgArSgADySY0m0xmGC2cAAMqw4D8-gCQMCQTN9GQ4ABFFbyJFIX7-dYgeamZ6mO5YNbDaqmVgwXaDGDGZAARgATAAGSr0iDPXZjap3em6F5YJGVcwARxWzHM7wwn2+RJRpOeW2YS1WGqxuPx8GRJMqMAwymZA1ZyE5prGzDI+gAwhAtl87lBoFKQCtnlpzT1ic8DAYgA)
```sh
--parser vue
--print-width 120
```

**Input:**
```vue
<nav>
<a class="testing" :class="{'testing' : !isNot, btn: isTesting}" href="/">Testing</a>
<a class="testing" :class="{'testing' : !isNot, foo: isBar}" href="/">Testing</a>
</nav>
```

**Output:**
```vue
<nav>
  <a class="testing" :class="{ testing: !isNot, btn: isTesting }" href="/">Testing</a>
  <a class="testing" :class="{ testing: !isNot, foo: isBar }" href="/">Testing</a>
</nav>

```
---
Or with `html-whitespace-sensitivity`
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeKBDAbgPgDpSoYAEYANhgM6UC8eI8lMAllAOb3FLlW33AByRi3YCuxAITNKAOQgwANMQBGMKEmLSAKnCas2AX04ALAE5wAZnRAB6ejh172qGxnyESPateH7O3Cm9+IV0RNjENKVl5JQsICA1pACEMUyMQYjNLazsQB1D9FzcCF0xcEAUQCAAHFmhKZFBU0wgAdwAFVIQGlGwIZgATCpBlUwwwAGs4GABlavH9ZBhTAFc4SuMYAFsyAHVjZkZ5sDgZ7sPmLEOAT2QQZjYoCHNh1ko4Uxh2sbYtjGQLBgyO9KgArSgADySY0m0xmGC2cAAMqw4ACgSCQOCITN9GQ4ABFFbyNFIQHA9Ygeamd6mO5YNbDaqmVgwXaDGDGZAADgADJVmRB3rsxtU7szdB8sGjKuYAI4rZjmb4YX7-MkYynvLbMJarLV4wnE+DoimVGAYZTsgac5AAJnNY2YZH0AGEIFs-ncnlAZSAVu8tJaeuT3gYDEA)
```sh
--html-whitespace-sensitivity ignore
--parser vue
```

**Input:**
```vue
<nav>
<a class="testing" :class="{'testing' : !isNot, btn: isTesting}" href="/">Testing</a>
<a class="testing" :class="{'testing' : !isNot, foo: isBar}" href="/">Testing</a>
</nav>
```

**Output:**
```vue
<nav>
  <a class="testing" :class="{ testing: !isNot, btn: isTesting }" href="/">
    Testing
  </a>
  <a class="testing" :class="{ testing: !isNot, foo: isBar }" href="/">
    Testing
  </a>
</nav>

```
