### ISSUE TITLE
Suggestion: add option to retain blank lines

### ISSUE THREAD

**Issue by tqwhite** [prettier/prettier#554]
Since I love prettier so much, I have integrated it into my text editor (bbedit by barebones) as a text filter. This allows me to run it in context with a command key. I don't even try to maintain format while coding. I just hit prettier every fifteen minutes.

However, I use blank lines a lot to help me keep things organized visually. Since prettier does not retain blank lines, I have wrapped it in regular expressions to make blanks lines into comments that I later replace. With that, I get excellent prettier formatting and keep my blank lines.

It would be cooler if prettier had a switch like --retain-blank-lines

Of course, this might not be possible. If so, I have my regular expressions so I can continue to love prettier.

**Comment by vjeux** [comment]
prettier should retain blank lines between lines (not at the top and bottom) and compresses blank lines to at most one. If you see cases where that's not the case, please let me know and we'll fix it :)

https://jlongster.github.io/prettier/#%7B%22content%22%3A%221%5Cn%5Cn2%5Cn%5Cn3%5Cn%5Cnfunction%20f()%20%7B%5Cn%20%20a%5Cn%20%20%5Cn%20%20b%5Cn%20%20%5Cn%20%20c%5Cn%20%20%5Cn%20%20d%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

**Comment by tqwhite** [comment]
You describe the behavior I see but not what I am hoping for.

I often, while coding, set off the chunk I am working on with several blank lines before and after so I can easily see it when scrolling. Since my normal usage is to use prettier constantly, that multiple line grouping goes away. I suggest a switch so that I can keep them.

Maybe the use of blank lines for navigation is peculiar to me. As I say, I can work around it but thought it might be a common use case.

(ps, I also do have a key command that collapses the multiple lines when I am done. I'd have made a good VIM guy in another life. ;-) )

**Comment by lydell** [comment]
Can you set off the chunk you're working on with several lines of empty `//` comments instead? At least in my Vim setup, Vim automatically adds `//` to the next line when pressing Enter in a comment.

**Comment by joefiorini** [comment]
It seems for objects, prettier actually removes blank lines between properties. Is this intentional? (See https://jlongster.github.io/prettier/#%7B%22content%22%3A%22const%20Blah%20%3D%20React.createClass(%7B%5Cn%20%20propTypes%3A%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%2C%5Cn%5Cn%20%20componentWillMount()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%7D)%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D)

**Comment by vjeux** [comment]
@joefiorini I implemented preserving lines for arrays ( https://github.com/jlongster/prettier/pull/448 ) and @jlongster mentioned that we may not want to do it there. All the code I've tested prettier on is using es6 classes where new lines are preserved.

```js
class C {
  propTypes() {
    
  }

  componentWillMount() {
    
  }
}
```

https://jlongster.github.io/prettier/#%7B%22content%22%3A%22class%20C%20%7B%5Cn%20%20propTypes()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%5Cn%20%20componentWillMount()%20%7B%5Cn%20%20%20%20%5Cn%20%20%7D%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Atrue%2C%22trailingComma%22%3Atrue%2C%22bracketSpacing%22%3Atrue%2C%22doc%22%3Afalse%7D%7D

I think that createClass is a good argument for preserving them for objects as well.

**Comment by prettydiff** [comment]
> and compresses blank lines to at most one.

I used to think that way too, but users kept requesting more flexibility.  I originally had an option named `preserve` that took boolean values, which meant preserve 1 empty line when true or 0 when false.  Now the option takes numbers and the boolean values are converted to 1 and 0 respectively.  I found that various users used empty lines to separate sections of code with large separations for greater visual division of code sections.  This was a very minor enhancement to go from boolean to number values and it made my users happy without really sacrificing anything.

**Comment by linocatucci** [comment]
Hello, I was wondering if it possible to turn off empty lines with prettier when you use it in HTML ?

**Comment by vjeux** [comment]
@linocatucci right now HTML is not very well supported with prettier. But the plan is to use the same rules as JSX there: at most one empty line is going to be preserved between children. Not before the first child and after the last one.

**Comment by linocatucci** [comment]
@vjeux thanks for the quick response.

**Comment by thezimmee** [comment]
I'm not sure what was decided here, but I have the same question / request as the OP. @prettydiff described the behavior I would love to see: have an option to allow prettier to preserve 'x' number of blank lines. However, unless I'm missing something, I don't think this is implemented and (imho) it should be...

In my time with prettier (which I love), it seems the whole point is making files more readable ("prettier"), so being able to preserve multiple blank lines, if desired, falls in line with its purpose and really should be supported. Especially when you have larger files, being able to highlight or separate sections with multiple lines of whitespace is extremely helpful in making the file "prettier" and more readable. And if it's a configurable option, you're not sacrificing or losing anything to get there.

Again, love prettier, thank you!

**Comment by lydell** [comment]
@thezimme It was decided to stick with the current "at most one blank line in a row" rule, and that's not going to change. Sorry!

> it seems the whole point is making files more readable

No. I don't think a non-machine-learning program can beat humans when it comes to making readable code (but it does beat humans who don't care). Prettier is all about taking code formatting out of developers' minds. Auto-format instead of manually typing everything. Keep code consistent in teams. Avoid code style discussions. The cost? Slightly worse formatting in a few cases. Worth it? Absolutely! Disagree? Well, then Prettier might not be for you…

**Comment by thezimmee** [comment]
> The cost? Slightly worse formatting in a few cases. Worth it? Absolutely! Disagree? Well, then Prettier might not be for you…

@lydell I don't disagree. To the contrary, this is what I really love about prettier. Consistency, no debates, plus it's simple to use and has wide support. It took some getting used to some of the ways it formats things into multiple lines, but even that I have come to love. I personally think it could be argued that breaking into multiple, narrow lines makes things more readable. But of course everything with code formatting is subjective, and the purpose of prettier is to take out any subjectivity. So please don't get me wrong, **I agree with and love that philosophy**.

What I'm not understanding is why such an emphatic "no" on blank lines / whitespace when other "stylistic"/whitespace rules -- such as semicolons, quotes, tabs/spaces, and even the width of each line -- _are_ configurable. Making the number of blank lines configurable does seem to take away from your above stated goals of prettier. At all. Nor does it sacrifice anything for current users. All it does is add value to users. In fact I think there is more lost by not adding it. However, obviously I haven't worked on the prettier project, so my perspective is limited. So here are my questions to you and any other creators/contributors:

- What were the reason(s) decided to emphatically stick with "at most one blank line in a row"?
- Why are other stylistic rules configurable but this one isn't/"never will be"? What makes the configurable rules different from this one?
- What is lost by adding this feature? Is there a cost or technical challenge to doing this that makes it not worthwhile?
- What is lost by _not_ adding this feature?

I appreciate any insights you or anyone else involved in these decisions might give.

**Comment by lydell** [comment]
Ideally, Prettier would have no options at all. But the JS community is too opinionated for that to work, so the double-vs-single quote option exists, for example. After a lot of requests, `--no-semi` was added. Recently, `--arrow-parens` was added after a lot of discussions and huge demand. In other words, it takes a lot to get a new option into Prettier.

Problems with options are:

- Maintenance. Implementation, tests, docs, fixing bugs, fixing problems when used in combination with other options. The more options, the more combinations.
- Burden on the user. More choices to make. Bikeshedding in teams. "Which code style should we use?" is swapped for "Which Prettier options should we use?"

---

Regarding a configurable amount of allowed blank lines in a row. Let's say you set it to 3. Then in code reviews you'll get comments like "Please remove excessive blank lines here" or "There should be 2 not 1 blank lines after such-and-such". The option is opening the doors for exactly the discussions Prettier is trying to do away with.

Finally, it is not true that this option will _never_ be added. It could be. If there's a lot of demand for it, which there isn't for the time being.

Remember, when a new option is suggested, I'd say it will be rejected 99 times out of 100. After a couple of months of :+1:s, a few miles of GitHub comments and a bunch of duplicate issues, _then_ it might be added. I'm not saying this because I get to decide these things, but from my experience from contributing to this project for about a year.

Thanks for your feedback! But I think that you have to let your blank lines go. Or start some expensive lobbying campaign ;) You can also experiment with using comments, functions and more files instead of blank lines.

**Comment by tqwhite** [comment]
In the meantime, I integrated prettier into my code editor (bbedit). It calls a Nodejs script and keeps the blank lines. Enjoy...

```
#!/usr/local/bin/node
const prettier = require("prettier");
let inString = "";

const customPreprocess = inString => {
	let outString = inString;
	outString = inString.replace(/^[\s]$/gm, "/*linebreak*/");
	return outString;
};

const customPostprocess = inString => {
	let outString = inString;
	outString = outString.replace(/\/\*linebreak\*\//gm, "");
//	outString = outString.replace(new RegExp(" " + " ", "g"), "\t");
	return outString;
};

const writeStuff = function() {
	let outString = "";
	outString = customPreprocess(inString);
	outString = prettier.format(outString, {
		singleQuote: true,
		useTabs:true
	});
	outString = customPostprocess(outString);
	process.stdout.write(outString);
};

//the rest ========================================================
process.stdin.resume();
process.stdin.setEncoding("utf8");
process.stdin.on("data", function(data) {
	inString += data;
});
process.stdin.on("end", writeStuff);

```

**Comment by thezimmee** [comment]
> Let's say you set it to 3. Then in code reviews you'll get comments like "Please remove excessive blank lines here" or "There should be 2 not 1 blank lines after such-and-such". The option is opening the doors for exactly the discussions Prettier is trying to do away with.

Ummm... try communicating? and share the same prettier config file? 😄 But I get the overarching point you are making, and agree it's wise to be choosy about the number of options and which options you make configurable. I just wish this was one of them (gosh, I'd take this one over half the other configurable options!). 😉

> I think that you have to let your blank lines go. Or start some expensive lobbying campaign ;)

Since I don't have the means, I'm afraid you're right (sad face). 😃 Thank you for answering my questions! Much appreciated!

@tqwhite Thank you for posting, I use sublime text with the sublime prettier extension. I'm sure I can integrate this somehow, I'll have to play with it when I have a chance. Thanks again!

**Comment by abimpson** [comment]
Just want to add my voice to this as I would love the option to have more than 1 blank - I've avoided using prettier to date because of this, as being able to give my code my own visual hierarchy using spacing is really important to me, and it seems I'm not alone.
Also, I notice that blank lines are removed completely from the start and end of objects, but not between object properties. Not sure if this is intentional or not, but it seems inconsistent with the rest of the behaviour.

**Comment by lydell** [comment]
> Also, I notice that blank lines are removed completely from the start and end of objects, but not between object properties. Not sure if this is intentional or not, but it seems inconsistent with the rest of the behaviour.

@abimpson Yes it is intended. See https://prettier.io/docs/en/rationale.html#empty-lines

**Comment by tqwhite** [comment]
I use Prettier a hundred times a day. I type a bunch of code without worrying about format then I hit the Prettier button in my editor (bbedit, see my example above) and Voila!, it's effortlessly formatted correctly.

However, when working on preexisting code, I often insert a bunch of lines around the place I am adding code so I can easily see it when scrolling. These get removed when I'm done but it's a great convenience that, without my workaround, is ruined. And it slows down my work because I have to either spend time typing format or paying attention to line numbers after I reformat with Prettier.

Yet another reason it's a mistake to refuse to parameterize the blank lines.

**Comment by lydell** [comment]
@tqwhite You never answered my question about that: https://github.com/prettier/prettier/issues/554#issuecomment-276885340

**Comment by tqwhite** [comment]
@lydell, my apologies. Somehow I missed your question.

I use a program called bbedit and it does not automatically extend comments.

**Comment by j-f1** [comment]
We do keep multiple blank lines inside of multiline comments.

**Prettier 1.14.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAHSt3V2ogA0IEADjAJbQDOyoAhgE5MQDuACswnSgwG4RKAE2IgARkwZgA1nBgBlMtMpQA5shhMArnBKqacJjA5S1AWwbIAZgwA2hkgCsaADwBCU2fIUNzcABlVOBt7RxBlJkMmZAkGcQBPO2gxMiZVGAB1ERgAC2QADgAGEjSIQ0ypMli0uGj+EJImOABHbUpm0wYLKyRbBz0QQ3NKTR1BmlU1OzgARW0IeFCBkhh47OE85AAmValKOymAYQhzS1ioaEaQbUMAFXjefsMAXxegA)
```sh
--parser babylon
```

**Input:**
```jsx
/*



*/
```

**Output:**
```jsx
/*



*/

```

**Comment by tqwhite** [comment]
@primalanomaly, Prettier is too good to allow such things to prevent your enjoying it. Scroll up to see a bit of Node I added to my development kit that retains blank lines but still retains the other Prettier goodness.
