### ISSUE TITLE
YAML: long property names/keys get prefixed with question mark `?`, and colon `:` gets wrapped onto the next line

### ISSUE THREAD

**Issue by deltaidea** [prettier/prettier#5599]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3OAnAngfQDbQDmOUAhgLZw4CWUOAZqWDDS9QM75GY4wAWpOgA4ADDjACMTeBk4BGAEwBmRSuWqN6rWqVIAOlAAEh+hAhJDekACNSGKyAA0ICAAcY1aO2Sg7GCADuAAp2CN4opKgQ1AAmTjZSYADWcDAAyq5MtITIMBgArnDOfDDkeADqfNTw7JlgcGlh1dSo1VjI4OzezrTsmDBBUoTkpMiMeH3OAFbsAB4AQokp6RRwADK0cGOkE0UgM7Np2XhwAIr5EPDbu86ZspgdWBR48a4YtDDlsfzIorf+fXKUlcHTecD6GHQ8QwcAAjvlqDDBqRhqMkONJiA+uRqLkCnt2MczhcruidpiYKRrF8Yj8kApnHlSNQ8NkAMIQcgjDpQaBbZz5PoAFSp4QxcAAvhKgA)
```sh
--parser yaml
```

**Input:**
```yaml
very_long_name_in_fact_it_is_longer_than_80_characters_123123123123123123123123123:
  foo: "bar"
```

**Output:**
```yaml
? very_long_name_in_fact_it_is_longer_than_80_characters_123123123123123123123123123
: foo: "bar"

```

**Expected behavior:**

Doesn't wrap the `:` to the second line, i.e. leaves the whole thing intact.

```yaml
very_long_name_in_fact_it_is_longer_than_80_characters_123123123123123123123123123:
  foo: "bar"
```

This issue looks simple to fix, where would I look for the related code if I wanted to make a PR?

**Comment by j-f1** [comment]
The code for this should be in [`src/language-yaml/printer-yaml.js`](https://github.com/prettier/prettier/blob/master/src/language-yaml/printer-yaml.js).

**Comment by byronluk** [comment]
@deltaidea Are you working on this? I was wondering if I could fix this. Thanks!

**Comment by flurmbo** [comment]
Hey @byronluk are you still working on this?

**Comment by byronluk** [comment]
You can take it. I spent some time looking into it but haven't came up with a solution. https://github.com/prettier/prettier/blob/5847c168e4360727d8e4c160600104191c93dc80/src/language-yaml/printer-yaml.js#L437-L440
This is what adds the "?" and ":" prefix if that helps.

**Comment by flurmbo** [comment]
I have also not been able to find a solution. In particular, the conditional group on line 434 and the ifBreak on 439 of printer-yaml.js seem to behave differently than as described in commands.md.

**Comment by leggsimon** [comment]
I think this label should be changed to `difficulty:hard` personally. Trying to navigate this is not hugely easy.

**Comment by nasht00** [comment]
We are currently having this issue, and it is breaking our YAML.

Some clarification questions:

- Is the `?` syntax that it generates a supported feature of yml? Or is it a prettier bug? I see the issue is flagged as "feature" and not "bug" so I'm wondering why it breaks our code (we use express-openapi).
- What is the suggested workaround?

**Comment by ikatyang** [comment]
`?` is the syntax for explicit mapping keys as described in the [YAML spec](https://yaml.org/spec/1.2/spec.html#id2798425).

**Comment by nasht00** [comment]
> `?` is the syntax for explicit mapping keys as described in the [YAML spec](https://yaml.org/spec/1.2/spec.html#id2798425).

Does it mean that the generated example is valid?

```
? very_long_name_in_fact_it_is_longer_than_80_characters_123123123123123123123123123
: foo: "bar"
```

The yaml documentation is hard to read...

**Comment by ikatyang** [comment]
Yes, it's valid. It seems the library you used only implemented part of the spec.

**Comment by deltaidea** [comment]
@nasht00
One lazy workaround that I've used for this is setting max line length to 999 for Yaml files. Fixes the issue immediately but doesn't look great if you have long lists with commas - they might get inlined.

**Comment by soullivaneuh** [comment]
@deltaidea Does not look to be a good option according to this: https://github.com/prettier/prettier/issues/3468#issuecomment-351333534

It produce not wanted behavior on files part getting in-lined when I don't want to.

This is a quite stuck situation. Apart of totally remove prettier from my tools, I don't see any other workaround.

**Comment by Ben-Setzer** [comment]
Good answer to help with understand https://stackoverflow.com/questions/33987316/what-is-a-complex-mapping-key-in-yaml

**Comment by sankarp-kavach** [comment]
Has anyone found a way to workaround this ? At the worst case, Are there any other tools like prettier to work with yaml files without this ternary operator issue ?

**Comment by mquandalle** [comment]
@sankarp-kavach You can augment the line size for yaml files as a workaround to the issue : https://github.com/betagouv/mon-entreprise/blob/099e754446a9423b5d97af9cc18eae758dae960d/.editorconfig#L24 (we use a .editorconfig, but this could be a prettier config file)

**Comment by pdavies** [comment]
I hit this bug and have fixed it - see PR just above. For anyone interested, there's some real black magic going on which made this pretty hard to figure out, but which feels commensurate to the wolf in sheep's clothing that is the YAML grammar.

The intention of the code was to:

* look at whether the key should break
* if it does, use explicit mapping syntax. The bug was that if a key is long enough that it wants to break, it will trigger this, whether or not it actually can break onto multiple lines
* if not, use implicit (ie normal) syntax

This is all pretty edge case stuff - many people will never know that yaml mapping keys can be multiline entities like arrays or multiline strings!

The extra dose of confusion comes from the pointless-looking call to conditionalGroup. It turns out that conditionalGroup has the undocumented behaviour of forcing the printer into MODE_FLAT, which the yaml formatter extensively relies on to prevent various breaks from occurring. Sensible-looking attempts to rewrite the code can very easily result in tons of line breaks appearing out of nowhere!
