### ISSUE TITLE
HTML Templating requires unquoted attributes

### ISSUE THREAD

**Issue by ntotten** [prettier/prettier#5627]
HTML supports unquoted attributes, we use a template language that uses unquoted attributes for templating and requires template attributes to NOT have templates. It would be ideal to support an option to not surround attributes with quotes.

Alternatively, having a "sub" HTML syntax like is done with Vue would work as well. We'd prefer to avoid forking the entire HTML plugin just to change this single format if possible.

**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4A6UABEagA5GboC8wAhAGoCCAMgKoCiAvrgBJwAbARFQB6MgShiseEABoQEMjEzQAzslABDAE46IAdwAKuhBpRbsEKvJAAjHVrABrODADKZJ5igBzZDA6AK5wCgAWMAC2AgDqYZjwal5gcO5mCTgJAJ7I4GoaCj5qcDowRo6+kVrIAGZaAsUKAFZqAB4AQo4ubu5akXAsPnC19Y0gLa3uPr4CcACKQRDwIw2hIF46xTq5EdG2ZDo+MDFUMGHIABwADAoHEMUxjmS5B3Bb2MMKOnAAjkGY33KWkq1SQdVWCmKkUwAWCazU01mCyWwzBozWMC0dhO6DOyAATApAlpMAJpgBhCCRKq5KDQT4gILFAAqWPM4OKXC4QA)
```sh
--parser html
```

**Input:**
```html
<div>
  <p id={VALUE}>Hello</p>
</div>
```

**Output:**
```html
<div><p id="{VALUE}">Hello</p></div>

```

**Expected behavior:**
The attribute should not be surrounded by quotes.

```html
<div><p id={VALUE}>Hello</p></div>

```

**Comment by ikatyang** [comment]
> We use a template language that uses unquoted attributes for templating

What's the template language you used?

> having a "sub" HTML syntax like is done with Vue would work as well.

It sounds like the template language you used is not compatible with HTML since whitespaces are not allowed to be used in unquoted attributes.

**Comment by ntotten** [comment]
The template language is called Lighting Web Components. It the new way to build apps on the Salesforce Platform. Just announced today: https://developer.salesforce.com/blogs/2018/12/introducing-lightning-web-components.html

I think it is valid HTML. We don’t have white space in the attribute, it’s non whitespace characters like {!value}

**Comment by ikatyang** [comment]
Can you share a reference for what's allowed to be used in `attr={here}`? or is there a way to distinguish it from other frameworks? We could add a special case to not to add quotes for `attr={something}` but it should not affect other frameworks, Angular interpolations (`attr={{ngInterpolation}}`) for example.

**Comment by ntotten** [comment]
Apologies for the delay. 

@ikatyang The expression is any valid javascript expression. The results must evaluate to valid HTML (i.e. no spaces).

I think the only way to determine if the behavior should be allowed would be to do something like angular and have a flag on prettier to tell it to use `lwc` mode. Is that something you think would be possible.

We are planning on shipping prettier as the exclusive formatter inside of all editors used by Salesforce so this would be super helpful. 

If we have to implement our own, it's basically going to be a full fork of the HTML formatter with this single change so obviously a lot of effort and duplication.

**Comment by j-f1** [comment]
You could use something like [`patch-package`](https://github.com/ds300/patch-package).

**Comment by ntotten** [comment]
Yeah, something like that is a possibility, but it feels like a pretty messy hack to ship with the Salesforce core software. Perhaps there is a model of enabling extensibility into the HTML formatter so that developers can override certain settings without forking the whole thing?

**Comment by ikatyang** [comment]
I think it should be better to put it in a separate plugin but currently there's no way to do so without forking the HTML plugin. Since it looks quite easy to implement, should we put it in the HTML plugin (under `--parser lwc`) for now and figure out a way to extract it to a separate plugin in v2?

**Comment by ntotten** [comment]
That would be awesome. I agree that ideally it should be separate later. We’d be happy to help when the time comes to figure out a model where these special cases can be separate plugins but reuse code to avoid duplication. The proliferation of JavaScript frameworks probably isn’t going to stop any time soon so it seems like something worth addressing in v2 as you suggest.

**Comment by ntotten** [comment]
How do we go about deciding this one? I am happy to send a pull request if this solution is acceptable.

**Comment by ikatyang** [comment]
It should be fine to do so given that there's no objection.

**Comment by diervo** [comment]
@ikatyang For the record, the grammar we use in LightningWebComponents is a subset of HTML, and we very purposely did that to be compliant with all parsers. 

I'm a little bit concerned or unhappy that you guys want us to do a plugin rather that making it part of the default parser since by design we really tried to avoid going that route.

I worked on that part of the spec defining parser errors and doing some disambiguation. If you look at the syntax specification:
https://www.w3.org/TR/2017/WD-html52-20170228/syntax.html#attribute-value-unquoted-state
As long as you don't use spaces or any quote or unicode that produce a parse error, it is valid HTML, and all the browser actually do the correct parsing behaviour.

We are fine if we have to do the plugin, but I would love for you guys to reconsider given that we are fundamentally spec compliant.

**Comment by ikatyang** [comment]
@diervo I know it's a bit confusing but what I meant `--parser` here is actually a printer since we do not have `--printer` at this point so we simply use `--parser` as a hint for printers to output something different from the default one, the parser we actually used should be same as the one used by HTML. (The sub-language parsing is happened in the printer.)

Regarding plugins, our current architecture does not support injecting some printer logics to other plugin, so I suggested to put it in the HTML plugin for now (https://github.com/prettier/prettier/issues/5627#issuecomment-451657206), and I hope we could address this issue in v2 so that you can easily write a plugin for it without forking the entire repo.

**Comment by ntotten** [comment]
@ikatyang Just wondering if you have a date in mind for when 1.17 will ship? Not urgent, but just wanted to check so we can align some things on our side.

**Comment by ikatyang** [comment]
No plan at the moment but it should be at least after finishing all the [milestone](https://github.com/prettier/prettier/milestone/27) items.

(FYI, you can `npm install prettier/prettier` if you'd like to use the latest prettier on master for now.)
