### ISSUE TITLE
The formatting of self-closing tags in HTML5

### ISSUE THREAD

**Issue by tshambhavi** [prettier/prettier#5641]
In Visual Studio Code, the Prettier extension appends forward slashes to self-closing tags. Can this specific formatting style be changed?

**Comment by lydell** [comment]
Hi! It was decided during the development of the HTML formatting to go with the slash style for void elements. Since Prettier is an opinionated formatter, this can change ([option philosophy](https://prettier.io/docs/en/option-philosophy.html)). Is there a particular reason you don’t want the slashes?

**Comment by tshambhavi** [comment]
Hi Simon, 

As Prettier formatting does not disrupt code functionality, it will not really matter whether slashes are added to void elements or not. I just wanted to conform to [standards](https://google.github.io/styleguide/htmlcssguide.html) that recommend that void elements shouldn't be closed. There was also the question of consistency because HTML5 code that had been formatted by Prettier were somewhat stylistically different from other HTML5 code, which had been styled by the default Visual Studio Code formatter.

Shamaa
