### ISSUE TITLE
Feature Request: validation

### ISSUE THREAD

**Issue by iamclaytonray** [prettier/prettier#5670]
None of the template applied to the issue I'm filing but if that goes against guidelines, let me know and I'll update!

I'm working on a web app that uses prettier to format an in-browser IDE. Though I _need_ to make sure all input is always valid, I'm sure there will be times when I didn't write a test, etc, and I'll pass an invalid string to prettier. Unfortunately, this just crashes the app.

So my use case would be a `prettier.validate()` API or maybe a `prettier.isValid()` API that I can run before I run `prettier.format()`. Based on the return value, I can gracefully handle errors (gives me more control over UX). If this is something that we could work into prettier, I'd happily poke around the source code and shoot a PR after I get a grip on it 😄 

If this is already done, then can we keep this open so I can add this to the docs?

**Comment by j-f1** [comment]
Why can’t you wrap your call to Prettier in a try-catch?

**Comment by iamclaytonray** [comment]
I could, sure. But that doesn't explicitly tell me anything. The following is an error thrown:

```json
{
  "loc": {
    "start": {
      "line": 3,
      "column": 9
    }
  },
  "codeFrame": "  1 | \n  2 |   # missing type name\n> 3 |   type  {\n    |         ^\n  4 |     id: ID!\n  5 |   }\n  6 | "
} 
```

What happens when these errors change? I need to fix keys to check if those object keys exist, and if they do, that means there was an error? Does `codeFrame` ever provide a value that isn't an error? Also, what happens when I _only_ want to validate if code won't break but not actually format it? Am I forced in needed to format anyways just to check if the string is valid? I think there's a big enough use case to have it. It won't break backwards compatibility and I don't think it would be a super expensive function.

**Comment by duailibe** [comment]
@iamclaytonray 

If `prettier.format` throws any error, it's because the input isn't valid or one of the options passed isn't valid. If `codeFrame` is a key of the error, the code is not valid. We could improve it and/or the documentation.

The API you're suggesting is basically trying to parse the code, which is the 1st thing Prettier does.. it would be fairly easy to implement but it doesn't make much sense to exist in Prettier. Checking if a code is valid is a side effect of what Prettier does, not exactly a feature.

I'm closing it since we won't add this feature, but feel free to comment if you need further help with the error handling.

**Comment by iamclaytonray** [comment]
I'm not sure I understand why this _wouldn't_ be a valid feature to land. I don't want to execute prettier in an app I'm working on. I want to validate it first and the format. If this behavior already exists, I don't see a reason why this couldn't be exposed as a public API.

**Comment by iamclaytonray** [comment]
Either way, this issue should stay open as a discussion to figure out errors, even if you don't support a validation API. I'd rather have some form of an error message than the current errors, which gives me no real sense of handling the error.

**Comment by duailibe** [comment]
First of all, I'm assuming you want to check if the code is valid so you can call Prettier without errors. If you want to check if the code has syntax errors for other reasons, that definitely doesn't belong in Prettier.

So what you're asking is basically checking with Prettier if you can format with Prettier, which isn't very useful since you can just format already and then check if something went wrong.

FTR: all of Prettier editor integrations work like this.. they just call `format(text)` and check the output/error.
