### ISSUE TITLE
Prettier joins nearby `label` & `input` tags

### ISSUE THREAD

**Issue by alexey-kozlenkov** [prettier/prettier#5691]
**Prettier 1.15.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QPgEZUB6LXAgHSlQEsoAHAVxgAIT9rq7GX3Oa5PPgBMpIVSjcG+UjO4T8AZnE5h02SXlSaMuQJ7M2HDQBZ9IADQgIDGLWgBnZKEwAnNxADuABXcJnFEwANwhaABMrEGw3TDAAazgYAGUGOPoAc2QYNyY4awALGABbdAB1Atp4RzSwOGSAqtpgqoBPZHBHZ2t6Rzg3GB9YjOLMZAAzTHQ+6wArRwAPACFYhKTkzGK4ABl6OAmpmZB5heTM9DgARSYIeAPp-JA0tz63DswoDKYsN+sGN3oMDKERgBWQAA4AAx-Tx9MqxBgdf5wV7BfbWNxwACOTFomKGmBGYyQkwe1j6xVo2Vyj0c5yuNzuJMOjxgOGB4VByBE1hymFo6EyAGEIMVRh0oNB0SAmH0ACo4QKkvoAXxVQA)
```sh
--parser angular
```
If there is a pair of `label` & `input` standing next to each other, prettier joins them into a single line during formatting.
This is not happening in combination of `label`/`input` with other tags (i.e. `p`, `div`, etc.).
**Input:**
```html
<label>1</label>
<input />

<input />
<label>2</label>

<p></p>
<label>3</label>
<p></p>

<p></p>
<input />
<p>4</p>
```

**Output:**
```html
<label>1</label> <input />

<input /> <label>2</label>

<p></p>
<label>3</label>
<p></p>

<p></p>
<input />
<p>4</p>

```

**Expected behavior:**
Keep `label` & `input` tags on the separate lines even if they are placed next to each other?

**Comment by ikatyang** [comment]
Hi, this should be fixed by #5596, which will be available in the next release. (You could install from GitHub `npm instsll prettier/prettier` if you'd like to use it for now.)

**Prettier pr-5596**
[Playground link](https://deploy-preview-5596--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeANgQwEZ3QPgEZUB6LXAgHSlQEsoAHAVxgAIT9rq7GX3Oa5PPgBMpIVSjcG+UjO4T8AZnE5h02SXlSaMuQJ7M2HDQBZ9IADQgIDGLWgBnZKEwAnNxADuABXcJnFEwANwhaABMrEGw3TDAAazgYAGUGOPoAc2QYNyY4awALGABbdAB1Atp4RzSwOGSAqtpgqoBPZHBHZ2t6Rzg3GB9YjOLMZAAzTHQ+6wArRwAPACFYhKTkzGK4ABl6OAmpmZB5heTM9DgARSYIeAPp-JA0tz63DswoDKYsN+sGN3oMDKERgBWQAA4AAx-Tx9MqxBgdf5wV7BfbWNxwACOTFomKGmBGYyQkwe1j6xVo2Vyj0c5yuNzuJMOjxgOGB4VByBE1hymFo6EyAGEIMVRh0oNB0SAmH0ACo4QKkvoAXxVQA)
```sh
--parser angular
```

**Input:**
```html
<label>1</label>
<input />

<input />
<label>2</label>

<p></p>
<label>3</label>
<p></p>

<p></p>
<input />
<p>4</p>
```

**Output:**
```html
<label>1</label>
<input />

<input />
<label>2</label>

<p></p>
<label>3</label>
<p></p>

<p></p>
<input />
<p>4</p>

```
