### ISSUE TITLE
html-whitespace-sensitivity strict merges tags to single line

### ISSUE THREAD

**Issue by cokkto** [prettier/prettier#5732]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQARgA2266AvADogQBOA5rgJYBe2Mj0VAfKgPRa4uFKKgBGNISIH4iJclUw0IAMzikOUbIW59pXEABpqmdtHTJQ2GkoDuABSsJzKbADcIjACaGQ47GABrOBgAZRwwRig6ZBgaAFc4IwALGABbQgB1JMZ4ATA4EKccxlccgE9kEHRYxjAYH0j0OBoYOxpsOlTsZGUtJqMAK3QADwAhdsDgkOxUuAAZSLgevsSQIeGQyLpCOABFOIh4ZcJ+kBwaJppK3Do44iujRUiYDK8YJOQADgAGR6UmjLtTCVRRqZquJZGGhwACOcUY0LaHS6x1OTVSjBi8VW6C2O32hyWSF6J1WMGwolenneyAATEZYthGIQtgBhCCpFEoKDQSEgOJNAAqFOcJKaAF9xUA)
```sh
--html-whitespace-sensitivity strict
--parser angular
```

**Input:**
```html
<h1></h1>
<p></p>
<h2></h2>
```

**Output:**
```html
<h1></h1> <p></p> <h2></h2>

```

**Expected behavior:**
Strict option in this case breaks "one tag per line" idea. It should preserve original formatting in this case, shouldn't it?

**Comment by ikatyang** [comment]
Hi, this should be fixed by #5596:

**Prettier pr-5596**
[Playground link](https://deploy-preview-5596--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEAeAFgRgHyoPRbYA6UqADrnhSRgEyXr0gA0IEZMAltAM7KgBDAE5CIAdwAKwhHxQCAbhE4ATFiABGQgWADWcGAGUy2zlADmyGEICucVuhgBbADYB1dJ3g9jYOAZmenPKeAJ7IIDxWnGAwaqY8cEIwElpmjgLIAGYCzgmsAFY8AB4AQlq6+gYCjnAAMqZwWTl5IIVFBqZmznAAitYQ8E25diDGQglC4QLm1s7CamRCpjCuKjDoyAAcAAysixAJrlpk4YtwE-KNrEJwAI7WnDcpAmkZSNnDrAmOnJY2IzxOt0+gNGu9miMYAJ1KtlOtkLRWFYBJxnJ0AMIQRzpcJQaBXEDWBIAFWhsg+CQAvpSgA)
```sh
--html-whitespace-sensitivity strict
--parser angular
```

**Input:**
```html
<h1></h1>
<p></p>
<h2></h2>
```

**Output:**
```html
<h1></h1>
<p></p>
<h2></h2>

```
