### ISSUE TITLE
Does prettier have an API that can show the detail for lint info 

### ISSUE THREAD

**Issue by xtx1130** [prettier/prettier#5753]
**Environments:**
- Prettier Version: 1.15.3
- Running Prettier via: `prettier.check(code, {parser: 'css', tabWidth: 4})`
- Runtime: Node.js v9
- Operating System: macOS

**Expected behavior:**
I wanna use API to scan a file where doesn't match the `prettier` rules and returns me the info, but when I use `prettier.check`, it just return a `Boolean`, or if I use `prettier.format`, it will only prompt where `prettier` can't format the code. I have read the docs in https://prettier.io/docs/en/api.html, but I can't find the API which I needed.

**Comment by ikatyang** [comment]
Basically, `--list-different` is just `prettier.check` with every `false` file printed. What did you mean the _info_?

**Comment by xtx1130** [comment]
@ikatyang I wanna the detail of the error info ,just like this:
```
 { 
    ruleId: 'init-declarations',
    severity: 1,
    message: 'Variable \'test\' should be initialized on declaration.',
    line: 1,
    column: 5,
    nodeType: 'VariableDeclarator',
    endLine: 1,
    endColumn: 9 
}
```

**Comment by j-f1** [comment]
That looks like a different tool than Prettier. Are you sure that’s coming from Prettier?

**Comment by xtx1130** [comment]
@j-f1 I just want to ensure if Prettier has an API like this. :)

**Comment by duailibe** [comment]
@j-f1 That's ESLint.. I think that's an example of what they wanted.

@xtx1130 We don't generate that kind of information and do intend to do it. Since Prettier just parses the code, generates an AST and then prints everything we don't really "monitor" what changed.

The [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) ESLint plugin, which allows you to run Prettier through ESLint, computes a diff and shows a ESLint error. The rule is always the same though

**Comment by xtx1130** [comment]
@duailibe Thanks for you detailed explanation of the problem, I got it.
