### ISSUE TITLE
De-structuring assignment without var/let/const folds current line onto previous line

### ISSUE THREAD

**Issue by adrianmcli** [prettier/prettier#5768]
**Prettier 1.15.3**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAbOMAEAjAhgJwB0p0s8AvYyKAZywDMIJMBeTYAX2IG098AaHLnIBdVpgC2uANZwAKgAsAllADmACgCUIfiAgAHGEug1koAvggB3AAoEEplLgBuEJQBMdIbPlxhZMADK+n4qqsgw+ACucLoKMBKoAOrK8DQhYHCBDkpGzrkAnsjgNKa6KjRw+DA2vqpSyPS4qJW6AFY0AB4AQr7+GIG4EnAAMipwjc2tIB2dgWHoAIpREPCTLbEgIfiV+MV42AWo0F76+CowSR4wCsgAHAAMumcQlUm++sVncLvOE7r4OAARyiSkBtVw9Vw62mlQkSgi0U2NAWcGWqwmSCaG10MFw2Cu7huyAATLjfEpUGEAMIQCQNFBQaD-EBRSpyfGObGVDgcIA)
```sh
--parser babylon
```

**Input:**
```jsx
let bar
let baz
const foo = {}
[bar, baz] = makeThing()
```

**Output:**
```jsx
let bar;
let baz;
const foo = ({}[(bar, baz)] = makeThing());
```

**Expected behavior:**
```jsx
let bar;
let baz;
const foo = {};
[bar, baz] = makeThing();
```

# Description

When assigning previously declared variables with de-structuring, Prettier folds that line onto the previous one, making the whole thing almost un-readable.

**Comment by hawkrives** [comment]
That's because you're that's what the JS engine is actually doing, thanks to ASI (automatic semicolon insertion).

See also https://prettier.io/docs/en/rationale.html#semicolons.

The easy solution is to either write your code with semicolons; to prefix the occasional destructuring or array literal with a semicolon; or (my favorite) to wrap the destructuring lines in parentheses.

**Comment by adrianmcli** [comment]
Thanks, makes sense.
