### ISSUE TITLE
Use elastic tabstops

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#5770]
[Elastic&nbsp;tabstops](http://nickgravgaard.com/elastic-tabstops/) are the&nbsp;perfect solution and the&nbsp;best reason why tabs are infinitely better than spaces for indentation in&nbsp;every single way.

<details>
<summary>
<strong>Rant why tabs are infinitely better than spaces</strong>
</summary>

I utterly despise using spaces for indentation and alignment, partly because they take up huge amounts of space on my harddrive and in memory compared to tabs (>8&nbsp;bytes per line vs&nbsp;just&nbsp;1), and with huge LOC counts, that’s a&nbsp;lot of&nbsp;wasted space on&nbsp;absolutely nothing, but mainly ***BECAUSE I&nbsp;CAN’T CHANGE HOW WIDE A&nbsp;SPACE&nbsp;IS***.

</details>

**Comment by duailibe** [comment]
Hi @ExE-Boss! Similar things have been suggested in the past, like aligning assignments:

```js
var aLongVariableName = 'a',
    foo               = 'b';
```

or object properties, etc.

They've all been rejected because we don't like for a few reasons: it's hard to determine what should be grouped or not, may cause too much diff when changing a single line, and we don't think it's particularly useful.

I don't understand your rant though. Prettier works with tabs, and you are free to use that. But we won't add this kind of alignment that depends on adjacent lines.

**Comment by ExE-Boss** [comment]
Except that elastic tabstops don’t depend on anything except that your example would be:
```js
var→	aLongVariableName→	= 'a';
→	foo→	= 'b';
```
Which would be visually aligned by the IDE.

**Comment by duailibe** [comment]
@ExE-Boss Sorry I misunderstood, I guess I only glimpsed through the text.

This is an interesting solution, but I don't think we're gonna add this in Prettier, because we also count whitespace to know if we need to insert a break.

Look at this contrived example (consider the print width of 40):

```js
var foo = "foo",
    c   = { foo: "foo", bar: "bar" };
//                         print width ends here ^
```

And then this other example:

```js
var aLongerVariableName = "foo",
    c                   = { foo: "foo", bar: "bar" };
//                         print width ends here ^
```

Prettier algorithm needs to know beforehand how much space that tab actually is to know if it needs to break the object or not.

This is a core heuristic of how Prettier works (print width) so this would be a great addition to a formatter that uses a different solution.
