### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#581]

**Comment by nfriedly** [comment]
Goals for this ticket:

Automate the following:

 - [ ] Generate the changelog entry with all the commits
 - [ ] Rebuild the docs website
 - [ ] Publishing to npm
 - [ ] Running prettier on the entire codebase and sending a pull request to see what changed. But we want to soon move to a place where it's being used on every commit.

The publishing to npm one is the easiest, although I can't do that one because it needs your credentials. (Unless you want to grant me both commit access to this repo and package ownership on npm). 

    travis setup npm

That should walk you through it. If not, there's manual instructions at https://docs.travis-ci.com/user/deployment/npm/ - they also explain where to find your API key, which the automated one asked for but didn't explain.

**Comment by nfriedly** [comment]
Now, when you say "rebuild the docs website", do you mean "run `npm run build:docs` and commit the output, updating the library (but nothing else) for https://jlongster.github.io/prettier/ ?

**Comment by vjeux** [comment]
@nfriedly yeah, rebuild the docs website is just running that command and committing the generated file.

**Comment by nfriedly** [comment]
Cool.

I'll put together a script to do something like that then. It may take a little back and forth, but we'll figure it out.

**Comment by vjeux** [comment]
Sorry about this, but since we're releasing so infrequently now and we have so many users, there is less need for automating the release process.
