### ISSUE TITLE
Single space in empty function body: fuction() {}->function() { }

### ISSUE THREAD

**Issue by s-patarinski-epam** [prettier/prettier#5821]
I am wandering if there is a way to configure the following behavior regarding formatting of empty functions (I need a single space in the { } brackets):

**Input:**
```js/ts
function foo() {
  
}
```

**Output:**
```js/ts
function foo() {}
```

**Expected behavior:**
function foo() { }

**Comment by lydell** [comment]
Hi! There isn’t! Is there a specific reason you need a space there?

**Comment by s-patarinski-epam** [comment]
I need to be consistent with the formatting applied by other team members. They are using VSCode, which is not configured with prettier and its default formatting adds this space.

**Comment by kachkaev** [comment]
Hi @s-patarinski-epam! Would not it be easier to configure Prettier in VSCode, other editors and maybe even in a [pre-commit hook](https://prettier.io/docs/en/precommit.html)? Our team has done that and we're all enjoying a 100% consistent code style since then. In addition to that, because we're running `prettier --check` in CI, there is no chance for anyone to commit just spaces and thus break `git blame` for a line that has not really changed.

**Comment by s-patarinski-epam** [comment]
You are correct, It would be.

I was just wondering if there is an option to configure this.

Since there is not, this is OK.

You can consider the matter closed

**Comment by lydell** [comment]
> I need to be consistent with the formatting applied by other team members.

Then unfortunately Prettier isn’t the tool you’re looking for. It’s an opinionated formatter with few options by design. It reformats your entire file. I’d suggest convincing your team to start using Prettier, like @kachkaev mentions.

**Comment by kachkaev** [comment]
@s-patarinski-epam you might find these links useful to help your team understand the value of Prettier:
https://prettier.io/docs/en/why-prettier.html
https://prettier.io/docs/en/option-philosophy.html
