### ISSUE TITLE
Rule error when using styled-components to inline a style with selector for uppercase component name

### ISSUE THREAD

**Issue by Yzrsah** [prettier/prettier#5920]
**Prettier 1.16.4**

When creating an inline wrapper style:

```
const Embellish = styled.span`
	Button {
		background-color: rgb(255, 42, 0);
	}
`
```

The 'Button' selector makes a Prettier rule error:
```
[prettier/prettier] Replace `B` with `b`
```

How can this be resolved?

**Comment by kachkaev** [comment]
If you are referring to a component, should it be `${Button}` instead of `Button`?

**Comment by Yzrsah** [comment]
It's a css selector. Inserting ${Button} there would be a syntax error.

**Comment by Yzrsah** [comment]
That does not work. It's a css selector. Inserting ${Button} there would be a type error.

**Comment by kachkaev** [comment]
In which case do your expect `Button` to actually work? Identifiers in CSS selectors without `.` or `#` at front refer to html tags. Because of this, it's fine to lower-case the selector. Class names (`.Button`) do not get lowercased, because they are case sensitive. If you want to say _change my `Embellish` component when it's inside `Button` component_, the syntax would be `${Button} & {...}` (see [Referring to other components](https://www.styled-components.com/docs/advanced#referring-to-other-components) in styled-component docs).

Prettier seams to deal correctly with all cases, [according to the Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAhArjGaTAXkwwE8AbOAEwDoAjfQqAA0kogCclMvbWAHSjDIUDJgCiAWwZxKlAJZoAFiTIwqtOmgAOAQzbDBMPASLBjMEw31gA1gHMuEXFBoBaDt15dHDAAoAJgBWEIAaTAAWIMiABgBKAG4rAF9jERg6MxZMS0ybOycXN09vHj5-YLDImPjktIyTABJgHOhUvKtCh2dXdy8ITgq-QNCI6NjMRJTM9LZZkHCQCF0YRXRkUH0uFwB3AAUdhDRkEH0ANwhFGiWQBi4iuBgAZQMwRShHZBguXDhlioYNJKAB1FSKeB6OxwF4nSGKC6Q8hnMBoU7LT5oOBcGAHR6OaT6ZAAM30lGxywAVmgAB7YR4OZ4vfTSOAAGU+cFJ5MpIBptJen0c1AAirgIPAeRSASADFxsVwzrY5JQ7rouJ8YKCbjAVMgABxxZYaiDY0GPXRnDVwRUXbnLfgAR1win4+P0hOJSDJMuW2Okih+f1laGFYolUp9vNlMH0DB1ND1yFiIF++kUSi+AGEINIiWcoNAHSBcNiACrx07RmWpVJAA).

**Comment by Yzrsah** [comment]
styled-components can be used to style functional stateless components.

For example

This produces an incorrect style:
```
import Button from '@material-ui/core/Button'
const Embellish = styled(Button)`
	&& {
		background-color: rgb(255, 42, 0);
	}
`;
```

This produces an incorrect style:
```
import ButtonBase from '@material-ui/core/Button'
const Button = styled(ButtonBase)``
const Embellish = styled.span`
	${Button} {
		background-color: rgb(255, 42, 0);
	}
`
```

This produces an incorrect style:
```
import ButtonBase from '@material-ui/core/Button'
const Button = styled(ButtonBase)``
const Embellish = styled(Button)`
	${Button} {
		background-color: rgb(255, 42, 0)
	}
`
```

This produces an incorrect style:
```
import Button from '@material-ui/core/Button'
const Embellish = styled.span`
	button {
		background-color: rgb(255, 42, 0);
	}
`
```

Styled correctly:
```
import Button from '@material-ui/core/Button'
const Embellish = styled.span`
	Button {
		background-color: rgb(255, 42, 0);
	}
`
```

**Comment by Yzrsah** [comment]
styled-components can be used to style functional stateless components.

For example

This produces an incorrect style:
```
import Button from '@material-ui/core/Button'
const Embellish = styled(Button)`
	&& {
		background-color: rgb(255, 42, 0);
	}
`;
```

This produces an incorrect style:
```
import ButtonBase from '@material-ui/core/Button'
const Button = styled(ButtonBase)``
const Embellish = styled.span`
	${Button} {
		background-color: rgb(255, 42, 0);
	}
`
```

This produces an incorrect style:
```
import ButtonBase from '@material-ui/core/Button'
const Button = styled(ButtonBase)``
const Embellish = styled(Button)`
	${Button} {
		background-color: rgb(255, 42, 0);
	}
`
```

This produces an incorrect style:
```
import Button from '@material-ui/core/Button'
const Embellish = styled.span`
	button {
		background-color: rgb(255, 42, 0);
	}
`
```

*Styled correctly:*
```
import Button from '@material-ui/core/Button'
const Embellish = styled.span`
	Button {
		background-color: rgb(255, 42, 0);
	}
`
```

**Comment by Yzrsah** [comment]
Thank you. The issue was resolved. I was using postcss because styled-components didn't work with material-ui in the form of ${Component} selectors.
