### ISSUE TITLE
incorrect prettification of multi-line markdown footnote

### ISSUE THREAD

**Issue by benswift** [prettier/prettier#5958]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAJOAnOByAzgAgEN9cZD4BbBGAbQD0AzCCGKFuAXQDoAdKP+kxZt4HJH3yT86LHiL4KAVwA2MAJYBaZWqhx8Q1u3wB3QsoDWOgOb4ARoTDn8MABZ7CtiADc9pcnCpYABoiKAATEhcIY2sJKSjjfDUYOTNlZxY0gE87CGVlCEdcXigpfBAgkAgAB3VoXGRQQgwMaIAFZoQGlEIvCDUwipBbDAdzOBgAZWqHa2QYDEU4SpcYCmUAdRdkuFwZsDhJruS1L2Ss5HBcBsqdXEwYNtGrCkJkBjN7yoArXAAPABCo0cE0mhCoABkdHB3p9liBfn9JtZlHAAIqKdiw5RfEAzDD3DCXV4YcxhaJQIbVDA6GAbAauZAADgADJVqRB7htRtVLtTdpgfEMsABHRRqLBPQgvN5ID44+H3ChqeaLRUo9GY+DY3FkWz0sKMpAAJkqC0Iam0UCsAGEIBRXpc2Lohop7gAVDzdeX3AC+vqAA)
```sh
--parser markdown
```

**Input:**
```markdown
Here's a statement[^footnote].

[^footnote]:
    Here's a multi-line footnote walking back the above statement, and showing
    how it's all totally bollocks.
    
```

**Output:**
```markdown
Here's a statement[^footnote].

[^footnote]:

  Here's a multi-line footnote walking back the above statement, and showing
  how it's all totally bollocks.

```

**Expected behavior:**

[Kramdown](http://kramdown.gettalong.org) will only parse the multi-line footnote if there's no line between the `[^footnote]:` line and the actual footnote. So the fact that prettier inserts a newline there means that it changes the output of the markdown (using Kramdown, at least).

**Comment by jez** [comment]
I'm seeing the same behavior on 1.18.2. I'm feeding the Markdown to Docusaurus, which uses `remarkable`, a CommonMark compliant implementation, which enables the footnotes extension by default. The behavior is that the footnote appears, but the contents of the footnote are empty. What would have been in the footnote appears as a normal markdown paragraph wherever the footnote was placed in the source.

**Comment by siedentop** [comment]
FYI, *hugo* (the static site generator), only allows footnotes if they are indented by four spaces.

*prettier* formatting breaks documents, by always indenting footnotes, even if they were on a
single line before. Now, since AFAIK footnotes are not specified in the markdown spec, this isn't a bug in prettier.

The **workaround** is to specify `tabWidth: 4` in your `.prettierrc`.

--
Yes, this could have been a separate issue. But I was too lazy ("busy") to fill out all the required fields for a new ticket and create a minimal example. If someone feels like creating a new ticket, please do.
