### ISSUE TITLE
Prettier reformats the content of Markdown code fences unexpectedly

### ISSUE THREAD

**Issue by DavidAnson** [prettier/prettier#5971]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5QA6FUACrnDDAJZy7qNSS51gwA2AnugAUAfgCU6OgDMIuALbYYAZ3QwAFnHSRYCGOghTVGrREKapCMJoBGcXqQA0WtdigBzdm6Oa6SgK68TO7oCgR+AA7oUrgQcugArOi87HAqMBDoAIwAdJSUAAaFAG5+cJSQcuF+8IRI6MCU6OgAJFDYcnDNQhINUE1NdDB+uH3qjErZzYSK2M0tAKIAcgAizQDcjegAvg6UOwWFeVAAkgDkcRDhCJ5G42xK-prQ6LYuvIYG6AAC4bxwalAEOgrqx1JpCOMwH4Hoxnux0AAeNQMcJKJAAenRHnUfms2Qq6OW2CKjEIAEEoEpoOjQkRSFBkrB0eNHkp0ZkAOyZAB8uSgIAcIEuTGgSmQoDwMRI1DwCDFKGJEFJApA1lw2DA+HoAGVwhrPMgYLhSoLkXJeAB1NSMeBKPVWbVym2MEkwfjIcAPFXsJQsGC0bBuBTIKTYXi+wUAKyUAA8AELqzU69pwAAyKRDYYjIGjMe1nj+AEU-BB4Jnw3BBXrcL7cB7acQyCrwrh2DALaT1MgABwABirMV9FvV4Q9LdSLCKcBVdAAjn5GHQA0HsOXs765IxDcbKyAlAW4MXS9OkKGK4KYNhrB3CF2kAAmC-qxiMtwAYViwZQUGg08F0LgAAVK95TPX0ti2IA)
```sh
--parser markdown
```

**Input:**
````markdown
# Markdown

Prettier incorrectly (?) reformats the content of the code fence below, changing the resulting markup from 5 lines to 1.

```vue
computed: {
  $name$() {
    return this.$data$ $END$;
  },
},
```

I'm opening this issue on behalf of @plehnen per the discussion in <https://github.com/DavidAnson/markdownlint/issues/171>.

````

**Output:**
````markdown
# Markdown

Prettier incorrectly (?) reformats the content of the code fence below, changing the resulting markup from 5 lines to 1.

```vue
computed: { $name$() { return this.$data$ $END$; }, },
```

I'm opening this issue on behalf of @plehnen per the discussion in <https://github.com/DavidAnson/markdownlint/issues/171>.

````

**Expected behavior:**
Leave pre-formatted blocks alone - just as HTML does for the content of PRE tags.

**Comment by lydell** [comment]
Prettier intentionally formats code blocks (where a supported language is specified). I think that's a really cool feature!

In your case – that's not really vue code in your code block, is it? It looks like part of a JS snippet. By marking the block with "vue", Prettier treats it like a .vue file. If you'd stick that code in a .vue file, it would be treated as _text,_ wouldn't it? So Prettier normalizes all the weird spaces and line breaks into a more convential sentence – where there's just one space between every "word".

Now, what would happen if you tagged it with `js`? Nothing, in this case. The code isn't valid JS, so Prettier would ignore it. Here are some things I recommend when it comes to code blocks in markdown:

- Use syntactically valid code if you tag the block with a language.
- Don't tag with a language otherwise.
- Use a `<!-- prettier-ignore -->` comment before otherwise.

**Comment by DavidAnson** [comment]
Thanks, @lydell, that’s really detailed!

FYI @plehnen for the underlying scenario here. If this info is helpful, I can close the issue.

**Comment by plehnen** [comment]
@DavidAnson first of all, many thanks for managing this! I understand the answer and yes, choosing "js" will prevent it from being re-formatted. It is a little sad that I cannot put a vue code snippet and have it formatted without adding a bloat of other stuff around just to have a valid and complete vue file for the linter. So the better option would indeed be to use the `<!-- prettier-ignore -->` comment before the code. Which brings me back to my original issue, that markdownlint will complain about this. It would be great if markdownlint could handle this. This prettier issue can of couse be closed, unless @lydell agrees on allowing the vue format to accept code snippets as well.

**Comment by lydell** [comment]
> choosing "js" will prevent it from being re-formatted

In this case, yes. But it will be formatted if it is valid.

> markdownlint will complain about this

We recommend turning all lint rules that conflict with Prettier (or do the same thing as Prettier – don't increase lint time for nothing!) off.

>  allowing the vue format to accept code snippets as well

I don't think that's possible. Humans can easily tell stuff apart, but dumb computers need exact rules to parse.
