### ISSUE TITLE
Closing bracket on new line in .vue file

### ISSUE THREAD

**Issue by marcoeh** [prettier/prettier#5999]
**Prettier 1.16.4**

I can't figure out why prettier formats [my code](https://github.com/wearelucid/vuecid-nuxt/blob/master/components/Examples/Examples/Examples.vue#L120) like this. Any help would be highly appreciated since I cannot rely on prettier to format the code properly now.

- [.eslintrc.js](https://github.com/wearelucid/vuecid-nuxt/blob/master/.eslintrc.js)
- [.prettierrc](https://github.com/wearelucid/vuecid-nuxt/blob/master/.prettierrc)

**Reproduce**
- Clone [repo](https://github.com/wearelucid/vuecid-nuxt)
- `nvm use && yarn && yarn lint --fix`

**Input:**
![image](https://user-images.githubusercontent.com/6922319/54837957-e2df5200-4cc7-11e9-9045-7488a790dcbf.png)

**Output:**
After running `yarn lint --fix`
![image](https://user-images.githubusercontent.com/6922319/54838049-07d3c500-4cc8-11e9-9d17-121cb07c0489.png)

**Expected behavior:**
![image](https://user-images.githubusercontent.com/6922319/54838091-1de18580-4cc8-11e9-8f6b-bea3f2047f52.png)

**Comment by lydell** [comment]
Hi! Can you reproduce this on the [playground](https://prettier.io/playground/)?

**Comment by marcoeh** [comment]
Hi @lydell, I tried, but I couldn't reproduce it there.

**Comment by lydell** [comment]
Thanks! That's an indication that this might not be a problem with Prettier, but rather with your setup. The next steps you need to take is to reduce your setup to find more exactly what is happening. Try removing stuff from ESLint. Try running the `prettier` CLI command directly instead of through ESLint. Try with a smaller file. etc.

Let me know if you find anything!
