### ISSUE TITLE
set configuration for formatting .md

### ISSUE THREAD

**Issue by isoftninja** [prettier/prettier#6001]
Is it possible to set the text editing configuration in .md files? 
`from`
```
        Some (   text )  . 
```
`to`
```
Some (text).
```

If possible, then show an example or at least describe the steps that need to be done to achieve this. I can't Google the solution :(

**Comment by lydell** [comment]
Hi! I'm not entirely sure what you mean, but if you wonder why your "from" code does not change when your run Prettier on it, it's because when you start a line with 4 or more spaces in markdown it becomes a _code block._ Prettier won't change the contents of code blocks, because it cannot know what kind of code you've put in there and Prettier don't want to break it.

If you start your line with fewer spaces, Prettier will collapse the unnecessary runs of whitespace. Note though that you still won't get your "to" code as the result – Prettier cannot know that it is safe to remove the whitespace altogether. If you want that feature you need another tool. Prettier is just a dumb formatter, but that would require knowledge of languages such as English.

**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACdH0GUIFs6oAUG8AHjKgJToA6Ummd2eBx6ZF1qT39vABoJ6oAglAgwAFnABOqAM4BPWAENSqAGYQ5kACYEARgBsIYANby6g-nVtRrAK0t9NAVyhgYAS2ip48mEJqYGEZOBhXGXoaECkveVQ9QxNzVHi-FQBzTLhdBQhUAAUwmG9ZRJV6M3EAd1RJCDqYAq0ZXBUKLxgY4QBfK0EQABoQCAAHb2h5ZFAVGRlGwrmEaZQVADcIL11hkAMZFXNwrDHDryhM5BgZVzgRyRhcIwB1SS64eVOwOCwVrq91l1FMhwPJpiNzvJZDBill2sgNCojFCRk5SAAhA5HGBYFT4AAy5zgCKRKJAaKw50yRjgAEVXBJiUhEci7iBTjIoTIQe0ZGZdI0oLsxjJzjBntspMgABwABhGIogUOeBzGIJFH1k62JIzCAEdXF4wrDMvDmaS2VDcF4rjdLVSafTGSTWSMYCoDBLdFKkAAmN0HLxGKkAYTwZpA4igOpArihABUPasWVDer0gA)
```sh
--parser markdown
```

**Input:**
````markdown
        Some (   text )  
        
  Some (   text )  
  
  
```
   Another syntax for code blocks
```


```js
   function test() {
   return "this code block is tagged so Prettier can know how to format it"
   }
```
````

**Output:**
````markdown
        Some (   text )


Some ( text )

```
   Another syntax for code blocks
```

```js
function test() {
  return "this code block is tagged so Prettier can know how to format it";
}
```

````

Does this answer your question?

**Comment by isoftninja** [comment]
@lydell I wrote an example right here, so do not pay attention to the spaces with which the line begins. I'm more interested in text formatting.

You say "other tools are needed," can you tell which?

**Comment by lydell** [comment]
I'm not sure such a tool exists.
