### ISSUE TITLE
How to STOP jsx/html attributes from wrapping to new line

### ISSUE THREAD

**Issue by joellis13** [prettier/prettier#6029]
**Prettier 1.16.4**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeArgGwARkwQwGdCA5fAWzgF4AdEAJwEsBzACxjoD4apttVMjTqjIA3ADKMoAa2wwItEAHouJOAHdsABXoQAVnDAxUSsZJnClg7r37WR+CVNnzFKkJ3ERm2APLpjU0dzaUtrHj4BIQcnGTkFOndcAmIySkUAIxheLKgAWgAzTAh8GCkfAAdnbEE2eHyARlUSEzNnMKEeEyxOEAAaEAgKsuhCZFB8el11LUmEMZRHCEYAE36QDPp8MGk4GABlCu3y5Bh6dDgB9nJMAHVWRnhCI7A4ffnHxlFHgE9kcGI6ykhDg9BgOnwzHI+GQBXwmBBAz0hAAHgAhLY7Pb7ChwcxwWHwxEgZEo-blTBwACK6Ag8EJCMuICO9BB9H+GXwGR+xSg6wqTFgt1WMFYyAAnAAGAYCiAg25bCr-AVwNmiAkDehwACO6EYWohUJhSDhjIGIPIjFO5yZhAp1Np9JNRKZMC5wpWouQACYBmd8IxBFBmABhCDkaH-KDQDUgdAggAqXIWppBAF800A)
```sh
--parser babylon
--print-width 90
```

**Input:**
```jsx
<ul className="right">
  <li><NavLink to="/">New Project</NavLink></li>
  <li><NavLink to="/">Log Out</NavLink></li>
  <li><NavLink to="/" className="btn btn-floating pink lighten-1">NN</NavLink></li>
</ul>
```

**Output:**
```jsx
<ul className="right">
  <li>
    <NavLink to="/">New Project</NavLink>
  </li>
  <li>
    <NavLink to="/">Log Out</NavLink>
  </li>
  <li>
    <NavLink to="/" className="btn btn-floating pink lighten-1">
      NN
    </NavLink>
  </li>
</ul>;

```

**Expected behavior:**
To stay like I entered it!  The output is NOT "prettier."  It is hideous and much harder to read.  How can I configure my .prettierrc to avoid this?

**Comment by lydell** [comment]
Hi! Thanks for your issue!

There is NOT a way to STOP Prettier from doing this. Prettier is an opinionated formatter. Sometimes you do NOT share the opinion on every code style choice (that happens to me as well!). What happens to many people is that they learn to like certain choices over time, or they choose to accept some formatting they do NOT like as a minor sacrifice for all the other things they like.

When it comes to JSX we've been through many iterations are quite satisfied with the current formatting. In your case, we've had people ask for the reverse – that Prettier should STOP joining multi-line JSX into one line in some cases. So this is unfortunately NOT a clear-cut case where Prettier is obviously making code worse according to the majority of people.

If this is a deal-breaker for you, then it is a sign that maybe Prettier is NOT the tool you are looking for (yet), and should STOP using it.

I hope this answers your question! I'm going to close this, since the JSX formatting is stable and we've got plenty of other issues to work on.

(Side note: I could NOT help myself from mimicking the capitalization game – do NOT take it seriously. I'll STOP here.)
