### ISSUE TITLE
--quote-props=consistent unexpectedly amends class method names

### ISSUE THREAD

**Issue by kachkaev** [prettier/prettier#6063]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAucAbAhgZ0wAgMI7AA6UOOkUmMATgK5gwTUAUAlITjABYCWmAdOhwBeHAG0AujgC+JMugAmC5gA92wTrwHp+AB1qYuq9rNLiAygE8AtgCMIqfj3jV0jahLYdqcGLWqk3HyC-ABu6Ki0cJheptIgADQgELowPNCYyKDo1NQQAO4ACjkImSjooRA8Cokgtq5gANa+5rroYDxQAObINFFJXDDWqADqvPCYbWBw5qXOPKHOlsjg2LWdmHDUMIWuXdboyABmEZtJAFaYKgBCDc0w5ujWcAAynXDHp3AXV+adXag4ABFWgQeCfVBnEBtaibagrWzoWxwVC1XTUTowEbVbjIAAcAAYkuiIJsRq5dCt0dEtqEPkkAI6g+C7FJlcAZPjwRBJHxMng+XbofaHJAnSHfECbaw8Xp0SWYf6AkFgj5ir5JGBI7EKXFIABMmtcPFQ-zwEGsBxWUGg9JABjgABUkWVxZtpNIgA)
```sh
# Options (if any):
--quote-props=consisent
```

**Input:**

_copied from https://stackoverflow.com/a/28744141/1818285_

```jsx
class C {
  constructor() { this.a = [] }
  add(x) { this.a.push(x) }
  [Symbol.iterator]() { return this.a.values() }
}
```

**Output:**
```jsx
class C {
  "constructor"() {
    this.a = [];
  }
  "add"(x) {
    this.a.push(x);
  }
  [Symbol.iterator]() {
    return this.a.values();
  }
}
```

**Expected behavior:**

```jsx
class C {
  constructor() {
    this.a = [];
  }
  add(x) {
    this.a.push(x);
  }
  [Symbol.iterator]() {
    return this.a.values();
  }
}
```

When the above code is in TypeScript and the constructor accepts arguments, replacing `constructor` with `"constructor"` causes TSC errors near `new C(42)`.

> Expected 0 arguments, but got 1.

Looks like TypeScript does not recognise the constructor when its name is surrounded by quotes.

**Comment by j-f1** [comment]
Reported to TypeScript too: https://github.com/Microsoft/TypeScript/issues/31020

**Comment by InExtremaRes** [comment]
What should be the resulting output in that example?

In any case I think symbol property names wouldn't trigger to surround all properties in quotes when `--quote-props=consistent`.

**Comment by duailibe** [comment]
Regardless of this working in TypeScript or not, it seems Prettier should not add quotes because one of the methods, keys, etc. being a member expression.

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzCEAEBeTwA6UmmA2uhAHQCGAukpuQDSHEBGVATvewF6EC+IRiAgAHGAEtoAZ2ShOHCAHcACpwSyUVAG4QJAEyEhWHKmADWcGAGVRZiVADmyGBwCucYQAsYAWwA2AOpeEvDSdmBw1hqhEtqhAJ7I4NKywg7ScBwwKqaOvlTIqFT+mcIAVtIAHgBCphZW1lS+cAAyDnBFJWUglVXWDo7+cACKbhDwXaWeIHYcmRzJ7KwJ-tBGohwOMIEGMF7IABwADMKbEJmBpqLJm3AL2p3CAI7j8LlimuAyEtLwiMIOHBXhIgbkqPlCkhitNhJlfBIXO4ZtJBsMxhNOtDujMYFRWLt9PtkAAmYSuKgSfyDADCEF8BWSUGgTxAbkyABV8ZoYZl+PwgA)
```sh
--parser babylon
--quote-props consistent
```

**Input:**
```jsx
foo = {
  [foo.a]: foo,
  bar: baz
}
```

**Output:**
```jsx
foo = {
  [foo.a]: foo,
  "bar": baz
};

```
