### ISSUE TITLE
--quote-props=consistent doesn't add quotes around number but it is required for consistency

### ISSUE THREAD

**Issue by wincent** [prettier/prettier#6064]
**Prettier 1.17.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTYAHSk0wHIBGAOgAZylMYAnAVzgBoSyAmRl9l1KYiICDAAWcZqP5tOJAL4gOYgA4wAlumSgAhs2YQA7gAUDCNMhB6AbhE0ATFSABGzPWADWcGAGU1T00oAHNkAU4QCRgAWwAbAHUJTXg0QLA4P0sUzVsUgE9rMDQrVWC0aRhTDxCYvWQAMz04itUAKzRsACEPb18-PRi4ABlguEbm1pAO7D9gkLi4AEVWcXGkJpbIwOYK5mtXPVc4OJc1ZmCYBKdJZAAOWlVziAqEjzVrc7g923HVAEdVvBqhA1FYUJAoGhNBgEDAXMw4IDNIjqnpavUNpNIhUYppwvJVNDQosVmsJltVDAjtdHLckDwqR5NHF5gBhCAxOrWKDQP4gVgVAAqR3BmwqikUQA)
```sh
--parser babel
--quote-props consistent
```

**Input:**
```jsx
const x = {
  '1.0': true,
  2: true,
  "other": true,
}
```

**Output:**
```jsx
const x = {
  "1.0": true,
  2: true,
  "other": true
};

```

**Expected behavior:**

Given that we're using `--quote-props consistent`, I would expect the "2" property to be quoted but it is not.

If I [add quotes to the 2](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTYAHSk0wHIBGAOgAZylMYAnAVzgBoSzyAmBpm07dMREBBgALOMzGMW7LlAC+IDuIAOMAJbpkoAIbNmEAO4AFIwjTIQBgG4RtAEzUgARswNgA1nBgAyhre2lAA5sgKnCCSMAC2ADYA6pLa8GjBYHAB1mna9mkAnrZgaDbqoWgyMOZeYXEGyABmBglV6gBWaNgAQl6+-gEGcXAAMqFwza3tIF3YAaFhCXAAiqwSk0gtbdHBzFXMtu4G7nAJbhrMoTBJLlLIABy06pcQVUleGraXcAf2k+oAI7reC1CAaGwoSBQNDaDAIGBuZhwYHaZG1Az1RpbabRKpxbSRITqWHhZZrDZTHbqGAnW7Oe5IXg0rzaBKLADCEDiDVsUGgAJArCqABUTpDtlVlMogA), then Prettier preserves them, but it doesn't add them in the case when they are missing.

**Comment by j-f1** [comment]
This is because the [properties](https://read262.netlify.com/ecmascript-language-expressions/primary-expression#prod-PropertyDefinition) of an [`ObjectLiteral` expression](https://read262.netlify.com/ecmascript-language-expressions/primary-expression#prod-ObjectLiteral) allow [an identifier, string literal, or numeric literal](https://read262.netlify.com/ecmascript-language-expressions/primary-expression#prod-LiteralPropertyName) as the property key. We currently convert literal strings to identifiers (and vice versa), but this doesn’t seem to apply to numeric literals.

**Comment by wincent** [comment]
Yeah, I'm aware of how object literals work. Just wanted to bring this up because it is a formatting bug, and will cause problems with ESLint because the behavior diverges from its [corresponding "quote-props" rule "consistent" setting](https://eslint.org/docs/rules/quote-props).
