### ISSUE TITLE
Add support for dotenv files

### ISSUE THREAD

**Issue by michaeljota** [prettier/prettier#6103]
dotenv files seems something awkward to support, but seems like they even have a [linter](https://dotenv-linter.readthedocs.io/en/latest/pages/violations/). I think all the rules are about format, so it seems like a good thing that prettier support those kind of files. If not, that's ok. Thanks!

**Comment by evilebottnawi** [comment]
It is good idea, but implementation `dotenv` is very difference for difference languages so it can be painful support this in core

**Comment by duailibe** [comment]
I think a formatter for it is a good idea, but I don't think we should add this in core.

**Comment by benatkin** [comment]
I think dotenv should standardize on a subset of TOML and dotenv.

Valid `.env`, `.toml`, and shell (but doesn't export)

```
API_KEY="foo"
DB_URL="postgres://foo:bar@localhost/quux"
```

Valid `.env` but not toml because it has export:

```
export API_KEY="foo"
export DB_URL="postgres://foo:bar@localhost/quux"
```

Valid `.env` but not toml because it doesn't have quotes:

```
API_KEY=foo
DB_URL=postgres://foo:bar@localhost/quux
```

Valid TOML but not .env or bash because it has a section:

```
export API_KEY="foo"
export DB_URL="postgres://foo:bar@localhost/quux"

[section]

test
```

Valid TOML but not .env or bash because it has a space between the key and value:

```
export API_KEY="foo"
export DB_URL="postgres://foo:bar@localhost/quux"
```

**Comment by thorn0** [comment]
Agree.
