### ISSUE TITLE
1.18 release

### ISSUE THREAD

**Issue by duailibe** [prettier/prettier#6126]
ETA sometime next week

**Comment by duailibe** [comment]
Some important issues came up (I tagged some in the milestone), I'll try to fix those over the weekend and release on Monday or Tuesday

**Comment by duailibe** [comment]
Prettier 1.18 is out!
https://prettier.io/blog/2019/06/06/1.18.0.html

**Comment by azz** [comment]
Can't reproduce on the playground, but I noticed this regression:

```ts
-export interface Group<T> {
+export interface Group<T,> {
  label: string;
  options: T[];
}
```

Any idea where it came from?

**Comment by azz** [comment]
Oh, #6115

**Comment by duailibe** [comment]
It's weird that it's not happening in the playground =/

**Comment by lydell** [comment]
We should probably use .tsx in the playground?

**Comment by igorsechyn** [comment]
This release was released as a minor version, which shouldn't contain any breaking changes. This PR https://github.com/prettier/prettier/pull/5979 broke our builds. Was this released as minor version by accident or is prettier not following semantic versioning? I just want to know, in order to decide how to specify the version in our package.json

**Comment by lydell** [comment]
@igorsechyn How is that PR breaking builds for you?

**Comment by igorsechyn** [comment]
We are using eslint-plugin-prettier, which has prettier as a peer dependency. After 1.18.0 release the linting step started failing due to the change in the PR I linked above. I see now, that it is a bit hard to judge in this case, since prettier was used as part of another tool

**Comment by lydell** [comment]
The contract of Prettier is that it takes a string as input (and a bunch of options), and gives _a_ string as output. But what that output string looks like is not specified. Otherwise _every_ release of Prettier would be a breaking change (even the smallest bug fixes). We do however maintain options and API compatibility. I hope this makes sense.

**Comment by igorsechyn** [comment]
Right. I guess we will just have to pin the version in package.json to avoid this. Thank you for clarification.

**Comment by lydell** [comment]
Yes, pinning your Prettier version is a very good idea! Maybe we should emphasize this more in the docs. It is important that all humans and bots in the project use the exact same version to avoid back-and-forth formatting and CI failures.

**Comment by MhMadHamster** [comment]
Dont want to create separate issue for this in main repo, but there is a weird wording in changelog on the prettier site in Typescript section of the changelog:
> The formatted result is valid as TSX, but is invalid as TSX. This is now fixed in 1.19.

**Comment by duailibe** [comment]
@MhMadHamster You can suggest a better wording in a PR

**Comment by azz** [comment]
> Maybe we should emphasize this more in the docs

We already do, it's mentioned in both the install page and the homepage. 🤷‍♂

> We should probably use .tsx in the playground?

Or maybe an option for `typescript` and `typescript (.tsx)` separately?
