### ISSUE TITLE
Readability of constructor (`new`) calls

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#6147]
I believe the input is more legible than the current output. A constructor call has 2 parts: the callee and the arguments, and since one way or another parens must be used to prevent `new` from hijacking the call expression, why not use them to clearly separate those 2 parts? What do you think? Should we change the current behavior? If so, I can try to come up with a PR.

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmyjgHdsAKAD3IEoA6ATxtoG4AdKDHPQ4sq2ozoAvZjXacsuAkVIVq9BoNGsQAGhAQADjACW0AM7JQWTBBIAFLAiMp0qCLoAm6kACNM6MAGs4MAMpaXrpQAObIMJgArnAaABYwALYANgDqcbrwBkFgcP42mbqomQzI4AZGGiEGcJgwFp6hiejIAGboyTUaAFYGlABCnj5+-uiJcAAyIXBtHV0gvZT+IaHJcACKURDws52xIEGYNZhlbuhucMmuWpghMKnOMHHIABwADBo3EDWpnlplNzgx1QMw0AEctvAGtpbCB0AYALTEOBOFGuTBwCG6DENdBNFpIdp7DQ1RK6CLRfYGFZrTbbGaEub7GDnB5OJ7IABMGki6F0yRWAGEIIlmmUoNBQSAojUACrnWxEmoAX2VQA)
```sh
--parser babel
```

**Input:**
```jsx
var a = new (x().y)();
var a = new (x().y.z)();
var a = new (x().y().z)();
```

**Output:**
```jsx
var a = new (x()).y();
var a = new (x()).y.z();
var a = new (x().y()).z();

```

Also I've found a couple of related bugs in the current behavior that can be fixed along the way.

<details>
<summary>Bugs</summary>

### Bug 1: parens are erroneously removed (ES) ###

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmyjgHdsAKAD3IEoADOgOgE8baBuEAGhAgAcYAS2gBnZKCyYIJAApYEYlOlQRBAE24gARpnRgA1nBgBlPnsFQA5shiYArnB4ALGAFsANgHUng+CLNgcMYKvoKovszI4CJiPBYicJgwMrqWrujIAGbo7gk8AFYilABCugZGxuiucAAyFnBZOXkghZTGFpbucACKdhDwjbmOIGaYCZhRWuhacO6afJgWMJ7qME7IABwADDwLEAmeunxRC3DjqA08AI598Cn8iiDoIgC0xHBqH5qYcDeCPyl0GkMkhskMeAlXIIbPZhiIOl1ev0GqCmsMYNMVmo1sgAEw8WzoQTuDoAYQgrnSUSg0EuIDsCQAKtNFGCEgBfdlAA)
```sh
--parser babel
```

**Input:**
```jsx
var a = new (x()``.y)();
```

**Output:**
```jsx
var a = new x()``.y();

```

### Bug 2: parens are erroneously removed (TS) ###
Overlooked this one when working on #6140.

**Prettier pr-6140**
[Playground link](https://deploy-preview-6140--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATuwXmyjgHdsAKAD3IEoBCAOgE8baBuEAGhAgAcYAltADOyUFkwQSABSwJRKdKggCAJlxAAjTOjABrODADKvXQKgBzZDEwBXONwAWMALYAbAOqOB8YabBwRvI+Aqg+TMjgwqLc5sJwmDDSOhYu6MgAZuhu8dwAVsKUAEI6+oZG6C5wADLmcJnZuSAFlEbmFm5wAIq2EPANOQ4gppjxmJEwTLxwwmCYAvwavPOwHmowjsgAHAAM3MsQ8R46vJHLMwmo9dwAjr3wyXwKIOjCALTEcKpfGphwdwI-sl0Kl0kgsoNuPEXAJrHYhsJ2p0en16uDGkMYOhNGtVBtkAAmbg2dACNztADCEBcaUiUGg1xAtniABVsQoIfEAL5coA)
```sh
--parser typescript
```

**Input:**
```tsx
var a = new (x()!.y)();
```

**Output:**
```tsx
var a = new x()!.y();

```

### Bug 3: parens are erroneously added (ES) ###

**Prettier 1.17.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEU4HcAEcDaAzACgEoA6ADwF0SBPYkAGhAgAcYBLaAZ2VAEMAnfhHQAFAQm4peANwhsAJgxAAjfrzABrODADKzdWygBzZDH4BXOIwAWMALYAbAOrW28TvrBwdEt22lu1MjgnNyMhpxw-DAiakZ2vMh4vA6RjABWnGQAQmqa2jq8dnAAMoZwSSlpIJlkOoZGDnAAiuYQ8JWpViD6-JH8wcq8ynAOSsz8hjBOCjDWyAAcAAyMExCRTmrMwRNw-dIVjACObfCxLJIgvJwAtGhw8g9K-HAnbC+xvPGJSMldjJE7GxTBZupwGk1Wu0Kr8qt0YMMZvI5sgAEyMMy8NgOBoAYQgdgSwSg0EOIHMkQAKsNJH9IgBfelAA)
```sh
--parser babel
```

**Input:**
```jsx
new e[f().x].y()
```

**Output:**
```jsx
new e[(f()).x].y();

```
</details>

 **2019-08-08**: The bugs have been fixed in #6148. This issue is only about readability now.

**Comment by bakkot** [comment]
I agree that the input formatting is better. I've opened a [PR](https://github.com/prettier/prettier/pull/6148) addressing the correctness bugs, since those (especially the first two) are higher priority.

The implementation for your suggestion is probably to do the same thing we do for [decorators](https://github.com/prettier/prettier/blob/e7d833966a67c07cf957c4bda3a3f088c502c636/src/language-js/needs-parens.js#L169-L196) and [arrows](https://github.com/prettier/prettier/blob/e7d833966a67c07cf957c4bda3a3f088c502c636/src/language-js/needs-parens.js#L198-L213) and so on: make the decision to add parentheses when looking at a `new` by descending into its children looking for a call, rather than (as [currently](https://github.com/prettier/prettier/blob/e7d833966a67c07cf957c4bda3a3f088c502c636/src/language-js/needs-parens.js#L216-L231)) when looking at a call and walking up its parents looking for a `new`.
