### ISSUE TITLE
Non-standard YAML sequence causes format thrashing with other tools

### ISSUE THREAD

**Issue by MichaelJCole** [prettier/prettier#6170]
This issue here voted to "do indent":  https://github.com/prettier/prettier/issues/4723

However, this is non-standard behavior and causes format thrashing with other tools (for example "kustomize" in Kubernetes which extensively uses YAML).

The [standard](https://yaml.org/spec/1.2/spec.html) shows a clear example in 
- "10.1.1.2. Generic Sequence", 
- "Example 10.2. !!seq Examples"

```
Block style: !!seq
- Clark Evans 
- Ingy döt Net 
- Oren Ben-Kiki  

Flow style: !!seq [ Clark Evans, Ingy döt Net, Oren Ben-Kiki ]
```

Non-standard formatting may be parsable by other tools that use the YAML standard, but Prettier's non-standard output causes format thrashing which isn't helpful.

**Comment by duailibe** [comment]
Just to make sure I understand, you are specifically talking about "Generic sequences" (i.e. tagged with `!!seq`) or any YAML sequences?

**Comment by MichaelJCole** [comment]
Hi Lucas, I looked at the spec here: https://yaml.org/spec/1.2/spec.html#id2802662

[kustomize](https://kustomize.io/) is part of kubernetes.  The homepage shows an image with both styles, but the tooling outputs with fewer indents.  

Because these tools generate config files, it would be nice to have an option for the file to be one way or another.  The spec had a recommended section - that's why I pointed it out.  

Anyways, I had to turn off Prettier for YAML in my toolchain because it was thrashing

Thanks!

**Comment by duailibe** [comment]
@MichaelJCole 

Thanks for answering. English isn't my native language so I didn't understand at first what you meant by thrashing, I thought Prettier was printing invalid code.

The spec specifically about sequences here https://yaml.org/spec/1.2/spec.html#id2797382 shows that the indented sequence is valid YAML, so the Prettier output is "correct". Now I wouldn't call the Prettier output standard or non-standard because there's no definition for that. We could just as well say that kustomize output non-standard because it's thrashing with Prettier.

I'm not familiar with kustomize, but it seems to me that you could simply run Prettier after you run kustomize to "fix" formatting, right?

**Comment by MichaelJCole** [comment]
Yes, both styles are valid syntax.  

The no-indent style is more common, and used as an example in the specification.  

Prettier is adding steps, so easier to remove it.

Do as you like :-)
