### ISSUE TITLE
Issues with printwidth and overriding other extends

### ISSUE THREAD

**Issue by jarkin13** [prettier/prettier#6257]
I want to use prettier to format my `js` using the `google eslint config`. However, it seems as if `prettier` is overriding googles config. 
- When I remove `"plugin:prettier/recommended"` from extends, a error message appears when I go over 80 characters. However, prettier does not format this.
- When I add back `"plugin:prettier/recommended"` — no error appears and it does not format. 
- All I want is for `prettier` to use google's config.

### prettierrc.json
```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": true,
  "singleQuote": true,
  "arrowParens": "always",
  "printWidth": 80
}
```
### .eslintrc.json
```
{
  "root": true,
  "extends": ["eslint:recommended", "google", "plugin:prettier/recommended"],
  "plugins": ["prettier"],
  "parserOptions": {
    "ecmaVersion": 6,
    "sourceType": "module"
  },
  "env": {
    "browser": true,
    "node": true,
    "jquery": true,
    "es6": true
  },
  "rules": {
    "indent": ["error", 2],
    "switch-colon-spacing": 0,
    "no-magic-numbers": [
      "error",
      {
        "ignore": [-1, 0, 1]
      }
    ],
    "no-mixed-operators": "error",
    "no-unneeded-ternary": "error",
    "comma-dangle": ["error", "always-multiline"]
  }
}
```

**Comment by lydell** [comment]
Hi!

You can see what `"plugin:prettier/recommended"` does here:

https://github.com/prettier/eslint-plugin-prettier/blob/4c069bd0f3b907039569964e747479aa06279594/eslint-plugin-prettier.js#L109-L115

```js
    recommended: {
      extends: ['prettier'],
      plugins: ['prettier'],
      rules: {
        'prettier/prettier': 'error'
      }
    }
```

In other words, it registers the eslint-plugin-prettier plugin and enables its only rule – which runs Prettier inside `eslint --fix`, basically. It also adds [eslint-<strong>config</strong>-prettier](https://github.com/prettier/eslint-config-prettier) to `extends` – this is the interesting part.

eslint-plugin-prettier does not help you with getting Prettier and Google’s config to play nice together. It’s just a convenience to run Prettier as if it was a good ol’ ESLint rule.

eslint-config-prettier on the other hand is made exactly for the purpose of making ESLint play nice with Prettier. It _disables_ a bunch of rules that conflict with Prettier. That’s all it does. For example, it disables ESLint’s [max-len](https://eslint.org/docs/rules/max-len) rule.

When you remove `"plugin:prettier/recommended"` you take Prettier out of the picture completely. [eslint-config-google contains the max-len rule](https://github.com/google/eslint-config-google/blob/0c27d3d2a21182a409d4441ac8996806a0b987e1/index.js#L236-L241) so that’s why you then get an error message. Somewhere you have lines with more than 80 chars.

When you add `"plugin:prettier/recommended"` back again, eslint-config-prettier is enabled, which disables max-len by default.

> no error appears and it does not format.

Maybe everything is already formatted as Prettier wants it? Try adding `var x=1.50` and see if it is changed to `var x = 1.5` – then we know that Prettier at least does something.

> All I want is for prettier to use google's config.

So here’s the thing. We generally recommend turning all ESLint rules that conflict with Prettier off. That’s what eslint-config-prettier exists for. You can still configure Prettier’s few options to try to match Google’s rules.

There’s also the option of using [prettier-eslint](https://github.com/prettier/prettier-eslint). It is a tool that runs first Prettier and then `eslint --fix`. This way you can get closer whatever ESLint config you have. I wouldn’t personally recommend this, but it is an alternative that can help in situations where ESLint configs are not allowed to be changed.

Hope this helps!
