### ISSUE TITLE
strange comma 

### ISSUE THREAD

**Issue by zhangenming** [prettier/prettier#6305]
**Input:**
```jsx
;[].map(e =>
    e.map(() => ({
        a: 1
    }))
)
```

**Output:**
```jsx
;[].map(e =>
    e.map(() => ({
        a: 1,
    })), //  <-- this comma so strange
)
```

**Expected behavior:**
```jsx
;[].map(e =>
    e.map(() => ({
        a: 1,
    }))
)
```

**Comment by evilebottnawi** [comment]
Please use issue template, provide your configuration, can't reproduce https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuA2gXQHQFsCGADgBRwAEAvAHwA6UZDZceRxxAlJVWccHYwLL4kZAIz9GAX3bs67EABoQEQjACW0AM7JQ+AE56IAdwAK+hNpT4AbhDUATRSABGe-GADWcGAGVC7tSgAc2QYPQBXOCUACxhcABsAdWi1eE1-MDgfC1S1a1SAT2RwTW0lQM04PRgTNyCCZAAzfHjKpQArTQAPACE3T28ffFw4ABlAuCaWtpBOrp9AoPi4AEVwiHgp1qiQfz1KvWLnfGc4eKdCPUCYRIcYaOQADgAGJUuISsS3QmLLuAPrJMlABHdbwWoqSwgfCaAC0UDgcHsSKcejgoLUaNq+Hq+C2M0quDU+J2mkWyzWG0mSGa2yUMBOt3s92QACZ6W41PFFgBhCC4BooKDQIEgcKVAAqJ0stMqkkkQA

**Comment by zhangenming** [comment]
> Please use issue template, provide your configuration, can't reproduce https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuA2gXQHQFsCGADgBRwAEAvAHwA6UZDZceRxxAlJVWccHYwLL4kZAIz9GAX3bs67EABoQEQjACW0AM7JQ+AE56IAdwAK+hNpT4AbhDUATRSABGe-GADWcGAGVC7tSgAc2QYPQBXOCUACxhcABsAdWi1eE1-MDgfC1S1a1SAT2RwTW0lQM04PRgTNyCCZAAzfHjKpQArTQAPACE3T28ffFw4ABlAuCaWtpBOrp9AoPi4AEVwiHgp1qiQfz1KvWLnfGc4eKdCPUCYRIcYaOQADgAGJUuISsS3QmLLuAPrJMlABHdbwWoqSwgfCaAC0UDgcHsSKcejgoLUaNq+Hq+C2M0quDU+J2mkWyzWG0mSGa2yUMBOt3s92QACZ6W41PFFgBhCC4BooKDQIEgcKVAAqJ0stMqkkkQA

https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuA2gXQHQFsCGADgBRwAEAvAHwA6UZDZceRxxAlJVWccHYwLL4kZAIz9GAX3bs67EABoQEQjACW0AM7JQ+AE56IAdwAK+hNpT4AbhDUATRSABGe-GADWcGAGVC7tSgAc2QYPQBXOCUACxhcABsAdWi1eE1-MDgfC1S1a1SAT2RwTW0lQM04PRgTNyCCZAAzfHjKpQArTQAPACE3T28ffFw4ABlAuCaWtpBOrp9AoPi4AEVwiHgp1qiQfz1KvWLnfGc4eKdCPUCYRIcYaOQADgAGJUuISsS3QmLLuAPrJMlABHdbwWoqSwgfCaAC0UDgcHsSKcejgoLUaNq+Hq+C2M0quDU+J2mkWyzWG0mSGa2yUMBOt3s92QACZ6W41PFFgBhCC4BpWeLnJThSoAFROllplUkkiAA

**Comment by evilebottnawi** [comment]
Because you can have many args https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBuA2gXQHQFsCGADgBRwAEAvAHwA6UZDZceRxxAlJVWccHYwLL4kZAIz9GAX3bsANBIb4ATgHNRXMsEnz6jZSoBMO9iFkgIhGAEtoAZ2ShlSiAHcACsoT2U+AG4QrABNTEAAjJXwwAGs4GABlQkirKBVkGCUAVzgzAAsYXAAbAHUcq3hbRLA4OK8yq18ygE9kcFt7M2TbOCUYNwiVAmQAM3wCrrMAK1sADwAhCOjYuPxcOAAZZLhh0fGQKem45JUCuABFDIh4bbHskESlLqUW0PxQuAKQwiVkmCKgmByyAAHAAGMxfCBdIoRQgtL5wR6+LZmACOF3gfQs3hA+FsAFooHA4IFiSElHA0VZyX18AN8Nddl1cFYGbdbEcTudLlskCMbmYYK8-oEAcgjCB0vgrAUjgBhCC4QY+AofMwZLoAFVe3j5XUkkiAA and use `trailingComma: "all"`
