### ISSUE TITLE
Kotlin Plugin

### ISSUE THREAD

**Issue by Angry-Potato** [prettier/prettier#6306]
Hi, I couldn't think of a better way to communicate this as there's no prettier slack / discord / etc. that I know of.

I've started a [prettier Kotlin plugin](https://github.com/Angry-Potato/prettier-plugin-kotlin), and am starting to get a little out of my depth, just wondering if someone with more experience in this area could take a look and perhaps give some pointers on how to improve what I've done so far.

**Comment by Shinigami92** [comment]
There are two documents that you can change:
- https://github.com/Shinigami92/prettier/blob/master/docs/plugins.md
and
- https://github.com/Shinigami92/prettier/blob/master/website/versioned_docs/version-stable/plugins.md

The second file should be generated, but that did not work the last time because I used the latest version of node.
So open a PR and change it by hand.

This impacts https://prettier.io/docs/en/plugins.html

**Comment by Angry-Potato** [comment]
Thank you, @Shinigami92 https://github.com/prettier/prettier/pull/6309

It's not yet complete and I am sure I haven't implemented it following any best practises, would be good to have more eyes on it.

**Comment by Angry-Potato** [comment]
@Shinigami92 I see, thanks!
