### ISSUE TITLE
Issue with method chaining

### ISSUE THREAD

**Issue by hubitor** [prettier/prettier#6315]
As I see here:
[https://github.com/prettier/prettier/issues/4596](url)
prettier breaks lines in case of method chaining by default.
Why it doesn't work here:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAThAtgSwM5wB0AhgDakAUA2unAI4CuceMFEADjDtHgJSEwAFggoAzCBF4BdfkJEAPAAQBeAHyLgAHSiLFovIQDu6HPABiOUnAqaQEBjHYPCAKzzRbAGkUApAMoA8gByhCwmUADmOKIAnhTy3lAM5N4ATLzeogxQYFzQFLwa2rq6kFDuVoSkEBE2IAAi0HAAhLa8ANzFigC+Hdq97SCedpzc5cigxOiYhqhTCHjIIMQAbhA4ACZDIABG6MRgANZwMH7sBziRyDDoTMOCMFikAOqCpsznYHB+C6Y4K6YYkswHhFsNLgR0DAMMQIlhiMhRGQCMM3PIAEL7I4nPzELBwAAylzgiORcFReHkfkuESsAEUGBB4KTSCiQOd0JClqJqoZtuxwjBnpshMgABwABmGAogBGe+3YSzIhmIMTBIEYTLgGA4ixQxDwAFooHA4BszdtaIwcLQYXCEUgkazySACLhrrcXXgafTGczHWThjBiDthRtRUhUkH9pYaQBhbDwpZQJrbBgEAAqIb1ToI3W6QA)
```sh
--parser flow
--prose-wrap always
```

**Input:**
```jsx
Promise.all([request(options).then(foo)]).then(x => {
  fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
    console.log("Done!");
  });
});
```

**Output:**
```jsx
Promise.all([request(options).then(foo)]).then(x => {
  fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
    console.log("Done!");
  });
});

```

**Expected behavior:**
I would expect something like this:

```
Promise.all([request(options)
.then(foo)])
.then(x => {
  fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
    console.log("Done!");
  });
});
```

**Comment by lydell** [comment]
Hi!

It looks like you've misplaced the `])`. Is this what you meant?

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAFAThAtgSwM5wB0AhgDakAUA2unAI4CuceMFEADjDtHgJQC6vADpRCMABYIKAMwgRhoiVIAeAAgC8APlXARq1dLyEA7uhzwAYjlJwKQkBAYx2TwgCs80ewBpVAKQBlAHkAOUIWMygAcxxpAE8KZV8oBnJfACZeX2kGKDAuaApeHT19VUgoTxtCUggouxAAEWg4AEJ7XgBuUoBfLpE+zpBvB05uSuRQYnRMY1RphDxkEGIANwgcABNhkAAjdGIwAGs4GAD2Q5xo5Bh0JhHxGCxSAHVxc2YLsDgAxfMcVbmOLLMB4JYjK4EdAwDDEKJYYjIaRkAgjDzKABCB2OpwCxCwcAAMlc4EiUXA0XhlAErlEbABFBgQeBk0iokAXdBQ5a7Yi7OK1KA7diRGAvLYSZAADgADCMRRACC8DuxliLmHB0KtSSNGMy4BgOEsUMQ8ABaKBwOCba07WiMHC0WHwxFIZFsikgAi4G53T14WkMpkst3kkYwPnizaSpDpcMHay0gDC2ARyygLR2DAIABU+cb3QQej0gA)
```sh
--parser babylon
```

**Input:**
```jsx
Promise.all([request(options)])
.then(foo)
.then(x => {
  fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
    console.log("Done!");
  });
});
```

**Output:**
```jsx
Promise.all([request(options)])
  .then(foo)
  .then(x => {
    fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
      console.log("Done!");
    });
  });

```

Even better, you can remove `Promise.all` since you only have one promise:

```js
request(options)
  .then(foo)
  .then(x => {
    fs.writeFile("output.json", JSON.stringify(x, null, 2), function() {
      console.log("Done!");
    });
  });
```

**Comment by hubitor** [comment]
The example was based on this project:
[https://github.com/DavideBecker/astera-armory/blob/bf4f3524aac635b4d07490cce76a8cfbac6878bb/scrapper.js](url)
I found it as I was looking for an example for Promise.all.
The code works, so I didn't notice this detail.
Indeed, it seems that ]) is misplaced.
Sorry!
