### ISSUE TITLE
Preserve line breaks at the start and end of child content

### ISSUE THREAD

**Issue by KyleMit** [prettier/prettier#6343]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoBuAtHllieRWaS5bfVjQEZ4BOhVAHpODXgKZsW1GpFgIYTdhVnyYeAJZQ4gkbXVadg6atFzo8WFOaraAMwgR4J2zIDOWPFEIAySFgAngDcZABMAAwAjACcIp7eyjLmjs66SRTS+nQMTCKYuARwTCAANCAQWDCa0O7IoAL8EADuAAoCCHUoeFQQmgAmZSA8-HhgANZwMADKXmDaAObIMPwArnDlABYwGDgA6pua8AlgcNOdR5pUR4HIIJoLUBD8cEPa7rowraMLGHjI9jwOA+5QAVu4AB4AIVGEym0zwGDgABltK8kIDgRsQOCIdNFjg4ABFVZpAFAkEgLz8D78O5UdZDLD8bQwPYDGCbZAADgi5WZEA+e1GWDuzLgtKor3KAEdSfBvpUuiA8O4aDo4P1NUMXnLNC9vnhfv8MRTsR8MJplmtzQTifL0ZjKRoeOz+pzkGFyistDhFgBhCAYP53J46IarD4AFTwPC6TrgAF9E0A)
```sh
--html-whitespace-sensitivity ignore
--parser vue
```

**Input:**
```vue
<template>
  <v-app>
    
    <v-app-bar></v-app-bar>

    <v-content>
      <v-container></v-container>
    </v-content>

    <v-footer>
      <span>&copy; 2019</span>
    </v-footer>
    
  </v-app>
</template>
```

**Output:**
```vue
<template>
  <v-app>
    <v-app-bar></v-app-bar>

    <v-content>
      <v-container></v-container>
    </v-content>

    <v-footer>
      <span>&copy; 2019</span>
    </v-footer>
  </v-app>
</template>
```

**Expected:** *(same as input)*
```vue
<template>
  <v-app>
    
    <v-app-bar></v-app-bar>

    <v-content>
      <v-container></v-container>
    </v-content>

    <v-footer>
      <span>&copy; 2019</span>
    </v-footer>
    
  </v-app>
</template>
```

**Reason Expected:** line breaks are preserved when we process similar html [(playground)](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOuNDEZlHAE7UB8lUuuHXXGO+YmSrgiTdGx68uJCAFs4MABYMA5lL4B6LNnZQNufnkKkK1MGIkg90mfMUqoq3IwDuB1Npx6POwaZELcUlOW1kFZTVcGFcIDy9dKQ5PHT0QABoQCAAHGExoEmRQMSYIVwAFMQRClCJsCEx0DJAAIyYiMABrRQBlbI61ZBgmAFc4TKUYOQIAdRV4En6wOB7qzDzsdYBPZBBMVSgIJjhmhhJmGHL21TkiZAAzIgJzzIArEgAPACF2rt6iBQAGQYJyQj2e4xA7w+PTUBDgAEURhB4A8ni8QP0mOcmLtsGNmtkmAwYDNGspkAAOAAMmSJEHOM3a2V2RLgOOwJ0yAEdkfArjkaiBSABaRhwdAS5rHXmYY5XIg3O5g9GQ85yTBDUZquGIvmg8EYugtMnoClIABMmWG9AIagAwvJbrtDoxmiNzgAVIgtGqGuAAXwDQA)

```html
<div class="container">
  
    <div class="card">
      something
    </div>

    <div class="card">
      something new
    </div>

    <div class="card">
      something two
    </div>
  
</div>
```

**Existing Documentation**
* [Rationale > Empty Lines](https://prettier.io/docs/en/rationale.html#empty-lines) suggests that Prettier attempts "*to preserve empty lines the way they were in the original source code*"
* [`htmlWhitespaceSensitivity`](https://prettier.io/docs/en/options.html#html-whitespace-sensitivity) set to ignore does not resolve the issue

**Similar Issues**
* #4131 **Keep existing line breaks** - issue occurs too many times to use [`// prettier-ignore`](https://prettier.io/docs/en/ignore.html) as suggested
* #5950 **Preserve line breaks before comment** - closed due to inactivity without solution 
* #5472 **Preserve line-breaks on multiline HTML content** - this is about nesting child content that falls below the `printWidth` threshold, not full empty lines
* #5596 **preserve surrounding linebreaks** - fixes #5472, not this issue
* Stack Overflow - [Preserve vertical whitespace in Vue template with Prettier](https://stackoverflow.com/q/53273117/1366033)

**Comment by lydell** [comment]
https://prettier.io/docs/en/rationale.html#empty-lines

> Empty lines at the start and end of blocks are removed.

**Comment by TheThirdRace** [comment]
@lydell 
The problem with that rule is that it only make sens in the **majority of cases**. Meaning there are some edge cases, **notably multi-line blocks**, where it will completely screw you by removing any sense of readability.

Readability should take precedence over pretty much anything, we're not reading a minified code dump...

Prettier defines itself as being opinionated. I'd go as much as saying it boast openly about it.

But the thing that doesn't add up is there are multiple parameters to let programmers and teams to decide which standard they want to adhere to.

Yet, the author(s) absolutely refuse to implement a parameter that would allow to keep empty lines at the start and/or end of a block. And I said **keep**, not always putting them in.

This is what baffles me the most. I don't understand the absolute refusal to have an option for this when Prettier has plenty of parameters for other things that are a lot less important for readability.

I'd ask, why discriminate start and end of blocks empty lines and not the others? What have those two done to merit such a radical purge?

For the same readability reasons you put empty lines between some sections of a same block, you might want to have some empty lines at the start and/or end of a block. It's simple readability...

Imagine if all of the sudden, we would have to forget about using the pattern of a dot + space ". " between sentences. Instead, you'd need to look for the uppercase letter in the middle of a paragraph. That would completely turn upside down the reading capacities of 99.9% of the world population.

I do get why **most** empty lines at the start and end of blocks should be removed, but there are cases where you can see it's unreadable that way, you need the empty lines to give a clear context and minimize errors.

**I love Prettier, absolutely love it**, but I'm seriously considering never using it again because of this single decision. The lack of context readability in some cases is too big to not be acknowledged. It's a shame though, because it could be solved with a simple parameter...

**Comment by KyleMit** [comment]
@lydell, given 

> Empty lines at the start and end of blocks are removed.

Can you comment on why [this playground test case](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4AIwA2AhgM4kC8AOuNDEZlHAE7UB8lUuuHXXGO+YmSrgiTdGx68uJCAFs4MABYMA5lL4B6LNnZQNufnkKkK1MGIkg90mfMUqoq3IwDuB1Npx6POwaZELcUlOW1kFZTVcGFcIDy9dKQ5PHT0QABoQCAAHGExoEmRQMSYIVwAFMQRClCJsCEx0DJAAIyYiMABrRQBlbI61ZBgmAFc4TKUYOQIAdRV4En6wOB7qzDzsdYBPZBBMVSgIJjhmhhJmGHL21TkiZAAzIgJzzIArEgAPACF2rt6iBQAGQYJyQj2e4xA7w+PTUBDgAEURhB4A8ni8QP0mOcmLtsGNmtkmAwYDNGspkAAOAAMmSJEHOM3a2V2RLgOOwJ0yAEdkfArjkaiBSABaRhwdAS5rHXmYY5XIg3O5g9GQ85yTBDUZquGIvmg8EYugtMnoClIABMmWG9AIagAwvJbrtDoxmiNzgAVIgtGqGuAAXwDQA) does *not* do that.

In either case, the request stands in opposition to that edict.  For better or worse, it's just not the way my brain works best to make sense of the code.  I'm certain that I don't account for every single use case, but I'm also certain it's not unique to me either.  

It makes it *harder* for me to group components inside of container when they don't have a physical whitespace buffer.  You don't have to go out of your way to tailor dev work to just me or similar folks, but as a feature request when there's time, I'd really appreciate it.

**Comment by lydell** [comment]
Because as far as I know, Prettier leaves everything outside `<template>`, `<script>` and `<style>` pretty much alone in Vue files.
