### ISSUE TITLE
Disable New line at then end of file

### ISSUE THREAD

**Issue by ziaurrehmanrehmani** [prettier/prettier#6360]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--single-quote
```

**Input:**
```jsx
// code snippet
```

**Output:**
```jsx
// code snippet
```

**Expected behavior:**

**Comment by lydell** [comment]
Hi! Prettier ends all files with a newline by design. Could you elaborate on why you would not want that, please?

**Comment by thorn0** [comment]
Doesn't Prettier respect the editorconfig setting `insert_final_newline`?

**Comment by lipis** [comment]
no :)

**Comment by lipis** [comment]
Prettier is opinionated and there is no setting for it, so we don't respect the editorconfig for that matter.

**Comment by mmiszy** [comment]
@lipis I'm using Prettier API programmatically to format matched code blocks inside larger HTML files. Adding newline at the end of each code block is really problematic in this case.

**Comment by lydell** [comment]
@mmiszy Can’t you programmatically remove the final newline?

**Comment by mmiszy** [comment]
I can. It's just inconvenient :P

**Comment by netlander** [comment]
I need to stop prettier adding a new line at the end of a file.

Did anyone find a decent workaround for this?

**Comment by d9k** [comment]
> I need to stop prettier adding a new line at the end of a file.
> 
> Did anyone find a decent workaround for this?

Found [this](https://github.com/prettier/prettier/issues/2575#issuecomment-319458290):

`prettier(code).replace(/[\r\n]+$/,'')`

**Comment by augusticor** [comment]
@d9k 
```
prettier(code).replace(/[\r\n]+$/,'')
```

Where do I add that ? In the config.json file ?

**Comment by InsOpDe** [comment]
Solved it with
```
 npx prettier --write . | awk '{ print $1 }' | xargs -I{} truncate -s -1 {}
```

**Comment by anteroortiz** [comment]
> Hi! Prettier ends all files with a newline by design. Could you elaborate on why you would not want that, please?

One use case I'm running into. 
1. Prettier adds a new line
2. Salesforce removes the new line whenever a class is uploaded to its cloud
3. Repositories register it as a difference when you pull down classes from the Salesforce cloud

Can't tell Salesforce not to remove it. Can't tell prettier not to add it. Conflicting opinions create an annoying juggling act in my local repo.

**Comment by evilebottnawi** [comment]
> Salesforce removes the new line whenever a class is uploaded to its cloud

Write `Salesforce` support team, removing newline from end of files is potential unsafe operation for some file types, it is bug

**Comment by guisartori** [comment]
why is it closed??? prettier is still adding a final new line!!! why dont you have a config for that?

**Comment by netlander** [comment]
Because they're a bunch of stupid idiots

**Comment by LaurensVanAcker** [comment]
What's the advantage of having this extra line?

**Comment by lydell** [comment]
Google “newline at end of file”. It’s basically a bike shedding thing.

**Comment by ntotten** [comment]
For Salesforce CLI try a hook that formats the file with Prettier on pull/retrieve: https://github.com/forcedotcom/sfdx-plugin-prettier

**Comment by yuhr** [comment]
I'm hosting [here](https://github.com/yuhr/prettier) another version of prettier that it completely same as the original except that it always removes the final newline.

In my opinion POSIX's spec about this should be considered kinda evil, we should go forward, but I understand such stance is always a minority which has no stamina to continuously maintain everything. So we shall stand on the shoulders of giants, at least for now.

**Comment by awarberg** [comment]
> > Salesforce removes the new line whenever a class is uploaded to its cloud
> 
> Write `Salesforce` support team, removing newlines from end of files is potential unsafe operation, it is bug

We have the same issue that `Salesforce` is modifying the files that we upload. (It is also not limited to unwanted insertion of newlines in .html files - they make all kinds of modification, such as inserting new nodes in XML documents.)

Knowing `Salesforce`, I doubt they see this as a problem - at least not _their_ problem ;-)

Having the option to disable newlines in Prettier would prevent a lot of conflicts in `Salesforce` development projects.

**Comment by shliachtx** [comment]
> > > Salesforce removes the new line whenever a class is uploaded to its cloud
> > 
> > 
> > Write `Salesforce` support team, removing newlines from end of files is potential unsafe operation, it is bug
> 
> We have the same issue that `Salesforce` is modifying the files that we upload. (It is also not limited to unwanted insertion of newlines in .html files - they make all kinds of modification, such as inserting new nodes in XML documents.)
> 
> Knowing `Salesforce`, I doubt they see this as a problem - at least not _their_ problem ;-)
> 
> Having the option to disable newlines in Prettier would prevent a lot of conflicts in `Salesforce` development projects.

According to https://github.com/dangmai/prettier-plugin-apex you CAN set an option for the Apex plugin to disable new lines at the end of files.

**Comment by anteroortiz** [comment]
> According to https://github.com/dangmai/prettier-plugin-apex you CAN set an option for the Apex plugin to disable new lines at the end of files. Just set `apexInsertFinalNewline` to `false` in your config.

Thank you. This works.

**Comment by esr360** [comment]
I would really prefer not to add pointless lines at the end of my files JS/Sass. The rationals that warrant adding a new line to the end of files are not relevant to my workflow or my environment. Prettier says it won't allow this because it is "opinionated", but this is contradicted by the existence of configuration options like `singleQuote` and `trailingComma`. It's possible to tell ESLint to enforce no new lines, but really this should be a job for Prettier, not linting.

**Comment by cherryblossom000** [comment]
I've got a different reason for wanting to disable the newline at the end of a file. I use eslint-plugin-prettier to integrate Prettier with ESLint, and I would like to use [eslint-plugin-markdown](https://github.com/eslint/eslint-plugin-markdown) and [eslint-plugin-jsdoc](https://github.com/gajus/eslint-plugin-jsdoc)'s [`check-examples`](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/.README/rules/check-examples.md) rule to lint code blocks in markdown files and examples in JSDocs respectively.

However, Prettier reports missing newlines at the end of the 'file' (the code block/example):

```js
/**
 * Description.
 *
 * @example
 * ```js
 * foo();
 * ```
 */
const foo = () => {};
```

```
6:19  warning  @example warning (prettier/prettier): Insert `⏎`  jsdoc/check-examples
```

I've read the [Option Philosophy](https://prettier.io/docs/en/option-philosophy.html) and I understand that Prettier won't be adding new options, but maybe this use case is worth considering.

**Comment by lydell** [comment]
@cherryblossom000 That sounds like a bug in eslint-plugin-jsdoc to me.

**Comment by cherryblossom000** [comment]
@lydell I guess eslint-plugin-jsdoc and eslint-plugin-markdown could filter out Prettier reports for missing end-of-file newlines. However, it would be a lot easier if Prettier just added an option to disable this, instead of having to do something like parse Prettier's lint messages.

**Comment by lydell** [comment]
The easiest thing would be if the plugins did the right thing out of the box?

**Comment by HiggsWRX** [comment]
Being unopinionated or not is one thing , but just being an ass about it is another @lipis . Keep it with a newline at the end by default, but at least give your users the option to disable it.

**Comment by Dazaer** [comment]
So I guess the "opinion" is to not allow configuration and always add an empty line at end of file because something might go wrong otherwise. However, adding a semicolon at end of line is totally configurable. And so is trailing commas. So... what's the logic behind this?

**Comment by alexander-akait** [comment]
Ideally, we shouldn't have any options at all, you don't need to think about formatting, prettier do job for you

**Comment by lydell** [comment]
@Dazaer See https://prettier.io/docs/en/option-philosophy.html

**Comment by ApplePieGiraffe** [comment]
@esr360 and @Dazaer said it nicely. https://prettier.io/docs/en/option-philosophy.html doesn't say anything about why semicolons at the ends of lines can be configured (but blank lines at the ends of files can't). Seems a lot like the same kind of thing.

**Comment by lydell** [comment]
@ApplePieGiraffe I noticed `--semi` isn’t mentioned on the page, but it would be in this paragraph:

> But other options are harder to motivate in hindsight: --arrow-parens, --jsx-single-quote, --jsx-bracket-same-line and --no-bracket-spacing are not the type of options we’re happy to have. They cause a lot of bike-shedding in teams, and we’re sorry for that. Difficult to remove now, these options exist as a historical artifact and should not motivate adding more options (“If those options exist, why can’t this one?”).

**Comment by ApplePieGiraffe** [comment]
@lydell Oh, okay... I see. 👍

**Comment by PalGenadich** [comment]
For my `Salesforce` fellows.
I found this plug-in as a workaround.
https://marketplace.visualstudio.com/items?itemName=DoCode.vscode-remove-final-newlines
Removes the new line after prettier.

**Comment by benzvan** [comment]
@alexander-akait 
>Write Salesforce support team, removing newlines from end of files is potential unsafe operation, it is bug

I guess I don't understand the logic. Isn't adding newlines also an unsafe operation?

**Comment by tjx666** [comment]
Not every language need end line. for example JSON file, how can I set not to new line to end just for JSON?

**Comment by Yash-Singh1** [comment]
I have `eslint-plugin-markdown` enabled and `eslint-plugin-prettier` requires me to create a newline at the end of my code blocks:

````markdown
```js
function somecode() {
    console.log('hey')
}
// Newline required here. If I don't have it then `eslint-plugin-prettier` reports, else `prettier` itself reports if I have it.
```
````

**Comment by xuld** [comment]
[Workaround here]
I've just published a new package called `prettier-no-newline`, which use the lateset prettier and never insert new line if it's not present in original file.

If you are using the VSCode Prettier plugin, install `prettier-no-newline` as devDependency instead of `prettier`, then:
set the `prettier.prettierPath` option to `node_modules/prettier-no-newline`.

**Comment by kachkaev** [comment]
New lines are necessary for cleaner git diffs. Imagine we have row `a` and add row `b` in a new commit.

**With new lines at the end of file**

```diff
 a ↩
+b ↩
```

**Without new lines at the end of the file**

```diff
-a
+a ↩
+b
```

If you work with tools that remove trailing new lines, it might be worth configuring or fixing things on their end.

**Comment by yuhr** [comment]
> If you are using the VSCode Prettier plugin, install `prettier-no-newline` as devDependency instead of `prettier`, then:
> set the `prettier.prettierPath` option to `node_modules/prettier-no-newline`.

I'd recommend putting an alias in `package.json` instead of modifying the VSCode preference.

```json
    "prettier": "npm:prettier-no-newline",
```

My version of Prettier ([`@yuhr/prettier`](https://www.npmjs.com/package/@yuhr/prettier)) is also available, which **always** removes the EOF newlines.

```json
    "prettier": "npm:@yuhr/prettier",
```

---

> New lines are necessary for cleaner git diffs

If you think this is a problem, you should think it should be solved by Git's side.

From human's point of view, a newline character *appears as* rather the beginning of a newline, than merely the end of the line like POSIX defines. Many people think there's a pointless empty newline, probably that's why they (and me of course) ended up into this issue. Softwares should be implemented as a reflection of how people think.

**Comment by wangrongding** [comment]
I have the same problem and am waiting for a better solution here👀👀

**Comment by Rub4l1to** [comment]
> Solved it with
> 
> ```
>  npx prettier --write . | awk '{ print $1 }' | xargs -I{} truncate -s -1 {}
> ```

For my part this command solves the problem. @wangrongding

**Comment by veritascs** [comment]
> For Salesforce CLI try a hook that formats the file with Prettier on pull/retrieve: https://github.com/forcedotcom/sfdx-plugin-prettier

Praise baby jesus!

**Comment by wangrongding** [comment]
It would be nice if this could be solved by the prettier plugin, I tried it, but it doesn't seem to work, has anyone solved this problem successfully with the prettier plugin?

**Comment by PatrykKuniczak** [comment]
Why, still we don't have a option to disable the new line in EOF????

This's ridiculous

**Comment by cemahseri** [comment]
Whao. I'm just surprised. I'm pretty new at the front-end development and I've rarely used Visual Studio Code. I was just checking if the extension had this feature or not. I couldn't find any option to disabl ethis. Then I just wanted to Google it to see if there was some option that you add to `.editorconfig` or to `.env` or something else and I've came up with this issue.

This is not being "opinionated". It's not like your family would catch a fast spreading flesh eating disease from their breakfast tommorow, if you would have been added an option to enable/disable this. This is about being dumb. My best guess would be the priest in your church which you went to when growing up as a child, always removed the new line at the end of the file. This might have been lead to a trauma.

Why would you want to be retarded like Python and forcing people to use a style? I don't care if removing it is a good practice or a bad practice. I just do not want to include it.

**Comment by JacobWeisenburger** [comment]
> For my `Salesforce` fellows. I found this plug-in as a workaround. https://marketplace.visualstudio.com/items?itemName=DoCode.vscode-remove-final-newlines Removes the new line after prettier.

This worked for me

**Comment by cemahseri** [comment]
> > For my `Salesforce` fellows. I found this plug-in as a workaround. https://marketplace.visualstudio.com/items?itemName=DoCode.vscode-remove-final-newlines Removes the new line after prettier.
> 
> This worked for me

It is a handy solution but it messes up with undo and redo features. If I save the file with this extension installed, it removes the new line at the end of the file. But I have to do undo several times to reverse the last changes. And it compeletely breaks the redo feature. I cannot redo if I save the file.

**Comment by PatrykKuniczak** [comment]
@fisker That's really big issue, to create it optional?

Many people didn't want that line EOF. u want probably loose "fans".

**Comment by xmaxcooking** [comment]
There really should be an option to disable this.
If you're like me using VSCode with "files.autoSave" "afterDelay"and Github Copilot, then it breaks Github Copilot functionality while you're working on the last line. I now have no other option than to change "files.autoSave" from "afterDelay" to "onFocusChange".

**Comment by zsubzwary** [comment]
> What's the advantage of having this extra line?

Well, in terms of version control, including a newline at the end of a file can be beneficial when working with Git or other version control systems. Without a newline, if you add content to the end of a file, it can create a diff that seems to modify the last line rather than simply adding a new line at the end.

Moreover, there are various tools and processes that anticipate files to terminate with a newline character. For instance, certain linters or automated code analysis tools assume the presence of a newline at the end of a file. By including the newline, you ensure compatibility with such tools and avoid any unforeseen issues.

**Comment by yuhr** [comment]
@zsubzwary Then that is a bug of those tools. See [my comment above](https://github.com/prettier/prettier/issues/6360#issuecomment-999393963). Assuming the presence of something necessary without explicitly checking it is just a bug.

**Comment by marcoshevaristo** [comment]
Is there any reason why this isn't an option by now? Saying it ensure compatibility explains why the feature exists, but don't justify why it is mandatory. There are plenty other optional settings on Prettier, why isn't this one of them? All the time invested in this discussion could be used to implement, test and release this feature like 10 times.

**Comment by danijelh** [comment]
Had the same issue, came here and I am amazed that this is discussed but not solved yet. Srsly thought, why is this even open for debate?

**Comment by cemahseri** [comment]
> Had the same issue, came here and I am amazed that this is discussed but not solved yet. Srsly thought, why is this even open for debate?

Pretty easy. Just read @lipis' message on this issue:
> Prettier is opinionated and there is no setting for it, so we don't respect the editorconfig for that matter.


Well, I hate front-end development so much but it's sad to see that Prettier is the best formatter out there that's maintained by worst developers. The funny thing is, it won't take more than few minutes for them to add this feature.

**Comment by elliot41** [comment]
Hi Prettier,

When I'm looking in your documentation, I found examples of configuration files :

![image](https://github.com/prettier/prettier/assets/15812951/5e9805a4-7f73-4264-9035-a584f329cd1c)

When I copy/past the code, i don't see any new lines at the end of the file ? You didn't run Prettier on it ?

![image](https://github.com/prettier/prettier/assets/15812951/ecad2973-f4aa-4d9d-85f1-4508c04b498e)

**Comment by jingidy** [comment]
Another valid use case: Amazon SES's create-template command errors out if a json file has a new line at the end. You can't expect me to tell AWS to change their code to accommodate some third-party code formatter.

Workaround: Add these files to .prettierignore

**Comment by PogromistDev** [comment]
Yeah, i don't need new line at the end of file. It's the end of 2023 come on...

**Comment by Matt-Morrow-Code** [comment]
This is causing issues with Shopify Liquid. When you use the `render` tag to render a snippet it inserts a `<br />` where there are new lines. This is being used to construct a JSON object fora data-* attributes. Using JSON.parse on this string then breaks because the JSON is now invalid due to the inclusion of `<br />`. 

Shopify didn't used to add the `<br />` but they are now. Whether it's logical or not we have no control of removing it because we are using prettier. 

So Prettier's opinion on EOF is breaking many production websites and we have to scramble to fix it. Opinions are only good if they don't force users to find an alternative code formatter.

**Comment by benzvan** [comment]
@Matt-Morrow-Code It sounds like Shopify is breaking production websites, not prettier. Putting unescaped xml in a JSON document isn't valid no matter the reason.

**Comment by Richardinho** [comment]
I'm reading this with amusement because I have the exact opposite problem: I run Prettier (version 3.1.1) and it keeps removing the line at the end of my files, which is annoying since Github complains about files lacking a line at the end of a file

**Comment by Matt-Morrow-Code** [comment]
> @Matt-Morrow-Code It sounds like Shopify is breaking production websites, not prettier. Putting unescaped xml in a JSON document isn't valid no matter the reason.

Hi @benzvan it's in an HTML doc not a JSON doc. This is liquid which is inserting a chunk of HTML. We are constructing an escaped JSON object in a `data-*` attribute which Javascript will parse, like so:
`<div data-config='{"foo": "{% render 'foo' %}"}'>Javascript wil run JSON.parse on data-confg</div>`

The HTML doc is perfectly valid but when Javascript parses the string using JSON.parse it breaks.

We could do a number of things to prevent the failure. The quickest fix to stop the bleeding is to remove new lines at the end of `liquid` files that are used as snippets. Not only can we not do that but it's Prettier that is forcing the new line.

**Comment by Alfystar** [comment]
> I'm reading this with amusement because I have the exact opposite problem: I run Prettier (version 3.1.1) and it keeps removing the line at the end of my files, which is annoying since Github complains about files lacking a line at the end of a file. I don't know if it makes a difference that I'm using NeoVim

What prettier settings are you using?
And what type of file are you applying it to?

**Comment by jazanne** [comment]
It's incredibly frustrating that this can't be disabled

**Comment by cgallonJurisoft** [comment]
> Solved it with
> 
> ```
>  npx prettier --write . | awk '{ print $1 }' | xargs -I{} truncate -s -1 {}
> ```

Works for me but to be able to use awk and xargs on windows needed to add "C:\Program Files\Git\usr\bin" to "Path" Environment variable and also needed to add a space between -I and {} for the script line to work ("npx prettier --write . | awk '{ print $1 }' | xargs -I {} truncate -s -1 {}")

**Comment by forjut** [comment]
Any updates?

**Comment by 20240816** [comment]
This basic functionality is long overdue

**Comment by josephdpurcell** [comment]
Can the prettier team provide guidance on the design behind adding a new line at the end of the file without an option to disable it? I'm referring to this comment: https://github.com/prettier/prettier/issues/6360#issuecomment-518994475

And, should a separate project be created to account for the use cases that require no new line at the end of a file as a technical necessity? Those use cases, based on this thread, seem to be: Salesforce ([link](https://github.com/prettier/prettier/issues/6360#issuecomment-658160027)), GitHub Copilot ([link](https://github.com/prettier/prettier/issues/6360#issuecomment-1522913740)), using prettier on code that are not-files ([link](https://github.com/prettier/prettier/issues/6360#issuecomment-778995613)), and Amazon SES templates ([link](https://github.com/prettier/prettier/issues/6360#issuecomment-1739768366)).

<details>
<summary>More context for my question here...</summary>

I greatly appreciate opinionated tools and frameworks. They often eliminate bikeshedding, as the prettier docs explain. `go fmt` was a great idea for Golang. The option philosophy page for Prettier is excellent, https://prettier.io/docs/en/option-philosophy.html. I love the idea of teams no longer having to bikeshed about format.

When it comes to designing a format for code I don't know how one draws the line between a "technical necessity (e.g. compatibility)" option and "formatting-related" option. I expect that is a difficult thing to decide. The use case I'm struggling with is Salesforce where it is a technical requirement that Salesforce has no new line at the end of the file. And, I'm on a journey to figure out how to get Salesforce to play nicely with prettier. The struggle would be more palatable if there was an easy recipe somewhere that explained how to get them to work well together, because then I could simply follow the recipe.

Instead, I'm in the struggle and I see a comment like this: https://github.com/dangmai/prettier-plugin-apex/issues/1166#issuecomment-1883391781. Which, is what prompted my inquiry in this here comment. There is a reason that prettier cannot even be extended by plugins to remove new lines at the end of files. Why? (Or perhaps that is a false assumption?)

Certainly I understand why no options will be added. That was very well [explained](https://prettier.io/docs/en/option-philosophy.html).

Here I'm looking for the design philosophy behind why new lines at the end of a file are a good choice and should not be done otherwise, even by a plugin.

As an opinionated formatter I presume there is an opinion that explains the design choice that I just haven't found.
</details>

Thank you for this excellent project and everyone who has contributed to making it possible.

**Comment by cabaucom376** [comment]
@josephdpurcell I would also like to chip in and say I have been attempting to figure out why my AstroJS refuses to generate my type-safe schemas for my data models. I've come to the conclusion that when prettier is formatting a newline in my `.md` files it is making Astro think that the `.md` file is of the `content` type and not the `data` type.

```ts
// Import utilities from `astro:content`
import { z, defineCollection, reference } from "astro:content";
// Define a `type` and `schema` for each collection
const categories = defineCollection({
  type: "data",
  schema: z.object({
    title: z.string(),
    sequence: z.number(),
  }),
});
// Export a single `collections` object to register your collection(s)
export const collections = {
  categories: categories,
};
```
Will not generate unless I set the `type` to `content` even though I only intend to store data. I believe the prettier newline at the end of the file is causing this.
```md
---
title: "Test"
description: "example"
sequence: 0
category: personalization
---


```

**Comment by josephdpurcell** [comment]
For the Salesforce use case, there is a recipe that is working for me: https://github.com/prettier/prettier/discussions/16823#discussioncomment-11157504.

**Comment by nkavian** [comment]
It's 6 years later. At this point, here's my solution when working with eslint+antfu: `'format/prettier': ['off'],`. Thanks.

**Comment by brandon-fryslie** [comment]
For anyone still wondering why Prettier doesn't have this option, it is very clearly documented: https://prettier.io/docs/option-philosophy.html

For anyone relatively new to programming who doesn't understand why each line in a text file should end with a newline character: 
- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
- https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file
- https://news.ycombinator.com/item?id=32962854
- https://dev.to/documendous/why-you-should-end-your-source-files-with-a-new-line-156g

To whoever mentioned JSON: JSON does not allow any newlines at all.  Any valid JSON in a file would be on a single line (or in a jsonl file), and that line should end in a newline.  Hope that clears up any confusion.

If Prettier is preventing you from hacking in a quick fix for an unrelated issue in an online platform, I recommend taking a deep breath and going for a short walk.  Software usually benefits from time thinking about the problem and implementing the right solution.  Not necessarily whatever series of keypresses helps you temporarily squelch the current fire.  There is some correlation between "hacking in a quick fix" and "there is fire and we need a quick fix".

I do think Prettier should only run against JavaScript files specifically and not against Markdown or anything else.  Feels like that would solve a lot of these peoples issue.

**Comment by rebane2001** [comment]
@brandon-fryslie i'm not sure where you got that idea from, [the json spec](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf) allows whitespace before or after any token, and that includes both line feed (U+000A) and carriage return (U+000D).

i don't see how the option philosophy applies fully to this feature req though, it's more of a running mode than an opinionated option in many cases. i agree that if you're just writing files as usual it makes sense to add the newline, and in that case it is in fact an opinionated option.

but there is also the case of running prettier on code to be inlined or otherwise processed in a similar way - in those cases you want to run prettier differently precisely for those use cases.

and even in the opinionated cases, prettier's opinions clearly break a lot of tooling and workflows for a lot of people. the philosophy makes sense when it's just a matter of style, so in most cases it makes sense to force a specific style because it's very unlikely to actually break anything. but also i do kind of agree with what brandon said, "Software usually benefits from time thinking about the problem and implementing the right solution", it is a pretty good counter-argument to the opinionated cases.

idk, this issue here still seems like stubbornness over ideals without considering the actual implications to me though.

**Comment by brandon-fryslie** [comment]
Very good points all around.  

You're right about newlined in JSON.  I was thinking of newlines inside a string.  

I completely agree with you that Prettier should have different behavior when being run against a chunk of code embedded in a file vs a separate code file.  It's a totally different use case and not a matter of style there, it's just incorrect behavior.  

I'd personally opt for an "--inline" (or "--embedded" or similar) switch so any differences in behavior necessary for that use case could live behind that toggle.  

That might also be more palatable to the maintainers, who have pretty logical reasons for avoiding functionality that is purely stylistic.  

Every additional option is more complexity in every part of the engineering process.  It makes it harder to work on the project, more testing required to release, more opportunities for bugs and unexpected behavior to creep in.  Keeping conditional options minimal (and ideally deprecating and removing stuff) is critical to the long term health of a project.  

That being said, it doesn't make a whole lot of sense to avoid adding some functionality for a use case you want to support, especially if it's relatively easy and low risk like this.  If you want this to be added, I'd recommend waiting a bit and then opening a new issue where it can be phrased in terms of supporting specific functionality (embedded snippets) rather than aesthetic preference.  This thread does not differentiate between those and i think its a dead end.

**Comment by nkavian** [comment]
First and foremost, this project's readme is very clear: [Opinionated Code Formatter](https://github.com/prettier/prettier?tab=readme-ov-file#opinionated-code-formatter); and we must leave these people alone.

Having said that, I don't like my files being edited for me in ways I did not request. It is overbearing. We could try to advocate `prettier` to change, but that would be itself incongruent to their above statement.

We should move on and find a different way to solve our problem, with or without `prettier`. Could they make a flag for this, yes, but they likely won't.

Here is something I'm sure is relatable. I want to edit a line in the middle of a file, but the editor thinks it knows better than me.

https://askubuntu.com/questions/13317/how-to-stop-gedit-gvim-vim-nano-from-adding-end-of-file-newline-char

Newlines at the end of a file has an antiquated reason for existing. Modern people know how to parse files with or without line endings.

People that like these newlines are probably also the same people that like commas at the end of everything :D

```
const variables = {
    a,
    b,
};
```

It's just a joke, have some levity.

**Comment by anteroortiz** [comment]
> Hi [@brandon-fryslie](https://github.com/brandon-fryslie) I fully understand your position and I totally agree with you!
> 
> Unfortunately, this request arises from the reckless choices of some platforms that prevent us from following these principles on every occasion...
> 
> In my case, I can give as an example the developments on Salesforce Orgs, which unfortunately when you download the code from them, always truncate the final newline. And this causes various headaches to the git-based pipeline, which sees differences and therefore includes these downloaded resources in subsequent packages, creating a positive loop.
> 
> To overcome the problem, I had to implement a small python program that deletes the final newlines with a regex, but as you can imagine it only works if used, so on the pipeline, the devs of my team often forget it and the result is diffs that are larger than necessary.
> 
> I am sure that other devs will have a thousand other examples to give you, and it is not always possible (see salesforce) to bring the culprits to their senses.
> 
> Hence the desperate need to try to solve the problem upstream. And you offer a truly fantastic product, which already solves a thousand problems, hence the simple idea of ​​solving one more...

If useful, I think I installed this and then used ["apexInsertFinalNewline": false] in my .prettierrc file to get it to stop doing it when formatting in VSCode

https://github.com/dangmai/prettier-plugin-apex

**Comment by stephenlf** [comment]
# Salesforce Workarounds

I have found two workarounds for **Salesforce** users--no dependencies required.

## OPTION 1 - Prettify inbound source

As previously stated, you can simply run Prettier *after* retrieving source. Here are a couple of scripts that do that:

```bash
# Git stages retrieved files, then runs `prettier` on them via `lint-staged`
sf project retrieve start
git add force-app/
npx lint-staged  
```

```bash
# Diffs against HEAD and runs prettier on that
sf project retrieve start
git diff --name-only --diff-filter ACMRT | xargs -d '\n' prettier --write --
```

## OPTION 2 - Uglify outbound source

You can also strip trailing whitespaces after running prettier. 

Drop this simple script somewhere in your repo, e.g. `ci/strip-trailing-newline.js`.

[ci/strip-trailing-newline.js gist](https://gist.github.com/stephenlf/387f802d1bd1ef7ddbe0b04623bb5efe)

Then, run it with node.

```bash
node ./ci/strip-trailing-newline.js -- "force-app/**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}"
```

You can configure it to run automatically after prettier in "lint-staged". 

```json
// package.json
  "scripts": {
    // ...
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}": [
      "prettier --write",
      "node ./ci/strip-trailing-newline.js"
    ],
    "**/{aura,lwc}/**/*.js": [
      "eslint --ignore-pattern '**/__tests__/**'"
    ]
  },
```

**Comment by keyvanm** [comment]
Awesome, I just won't be using prettier until this is resolved 👍

In general, `.editorconfig` has a higher authority than prettier so prettier shouldn't do things that go against what is defined in editorconfig. If my editorconfig says no final newlines and prettier inserts one anyway, then prettier gets disabled. 

Thank you for your attention to this matter.

**Comment by deckblad** [comment]
Still need this. Being opinionated isn't useful when you're wrong in the context of a specific language.
