### ISSUE TITLE
Always rewrite numbers in lists in ascending order, not 1. 1. 1.

### ISSUE THREAD

**Issue by yogurtearl** [prettier/prettier#6379]
Prettier 1.17.1 
[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAngDxgHSg2zj0ICYtcCoBmK0mgFgbKgFZ0QAaECABxgBLaAGdkoAIYAnaRADuABRkJxKSQDcIQgCY8QAI2mSwAazgwAyvxNCoAc2QxpAVzi8AFjAC2AGwDqHkLwojZgcJaqwUIawQCeyOCi4rx2onDSMIrG9t6SyABmkr7pvABWojgAQsZmFpaS3nAAMnZwhcWlIBU4lnb2vnAAii4Q8B0l7iA20unSiXnSpjoKUPr80nYw-rowHsgAHAAMvBsQ6f7G-IkbcHMa7bwAjqPw2QJqIJKiALRQcHAdID9NI4C8hKDspJcvkkEVJrx0t4hE5XFNRP1BiMxu04Z0pjBJAYdjo9shyLxnJIhL5+gBhCDePKJKDQR4gFzpAAqRLU8PSAF8BUA)

Would like for formatted number lists to match rendered markdown output, even when they start with "1. 1."

**Input:**
```markdown
1. text
1. text
2. text
3. text
4. text
5.
```

**Output:**
```markdown
1. text
1. text
1. text
1. text
1. text
1.
```

**Expected behavior:**

**Output:**
```markdown
1. text
2. text
3. text
4. text
5. text
6.
```

**Comment by kachkaev** [comment]
Please leave a link to the [Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBGAdAAngDxgHSg2zj0ICYtcCoBmK0mgFgbKgFYsQAaECABxgBLaAGdkoAIYAnaRADuABRkJxKSQDcIQgCY8QAI2mSwAazgwAyvxNCoAc2QxpAVzi8AFjAC2AGwDqHkLwojZgcJaqwUIawQCeyOCi4rx2onDSMIrG9t6SyABmkr7pvABWojgAQsZmFpaS3nAAMnZwhcWlIBU4lnb2vnAAii4Q8B0l7iA20unSiXnSpjoKUPr80nYw-rowHsgAHAAMvBsQ6f7G-IkbcHMa7bwAjqPw2QJqIJKiALRQcHAdID9NI4C8hKDspJcvkkEVJrx0t4hE5XFNRP1BiMxu04Z0pjBJAYdjo9shyLxnJIhL5+gBhCDePKJKDQR4gFzpAAqRLU8PSAF8BUA) and also specify the version of Prettier, according to the [issue template](https://github.com/prettier/prettier/blob/master/.github/ISSUE_TEMPLATE/formatting.md).

---

Because you have two `1.` in the beginning, the output is reasonable and changing this behaviour will breaks someones habits. At our teams, we always go for `1. 1. 1.`  instead of `1. 2. 3.` in order to minimise git diffs if any of list items are reshuffled. IMO the behaviour should remain as is.

**Comment by yogurtearl** [comment]
Updated the description. 

I hadn't consider the benefit of reducing git diffs, interesting. 
If you keep the existing behaviour, maybe it could be documented, if it is not already?

I found the behaviour suprising, but could find any docs about it.

**Comment by evilebottnawi** [comment]
@yogurtearl we don't modify you inout in this case, if you will use `1`/`1`/`1` we keep them, if you use `1`/`2`/`3` we keep them too, you can use remark-link for linting this, i think this rule more related to linter than to prettier because we wan't change your source code
