### ISSUE TITLE
`eslint-disable` or `tslint:disable` comments should be ignored from `printWidth`

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier#6505]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQFtVQQBOAanEQM6rSYB8AvJgGwB0ALAJSbCYD0vmOBQA2BGAFoAJqgoBDAEbC440VDiYAAjACeAByFgiqXRKGqYvQuNyyA5qjDioAV1zzyFADpQAviAA0IBAm1FAUyKCyREQQAO4AClEI4SiyAG4QqJIBIPJEsmAA1nAwAMq6BQS2yDBEznCBABYwuMIA6o2o8BQVYHClyV2oaV3ayOAU4YEEFOQw8fm2NsjossKzgQBWFAAeAEL5RSWlsrhwADIEcCtrGyDbO6VVSgCKzhDwN+sNIBWU5ON5AptMJoDldEZYG0sjBGsgABwABkCEIgsza+V04whQnIaWugQAju94AtgikQLIKE44HBJHSckQ4MTUEyFnZlkhVt9ArN8DU6j8qFBbK8SdcubcfjAFNDJLDkAAmQK1WSoVS2ADCEFwnJAhDUOWcswAKgoUtzZj4fEA)

**Input:**
```ts
if (minorVersion >= 6.4) { // eslint-disable-line @typescript-eslint/no-magic-numbers
}
```

**Output:**
```ts
if (minorVersion >= 6.4) {
  // eslint-disable-line @typescript-eslint/no-magic-numbers
}
```

**Expected behavior:**
```ts
if (minorVersion >= 6.4) { // eslint-disable-line @typescript-eslint/no-magic-numbers
}
```

**Comment by lydell** [comment]
Hi!

This has nothing to do with printWidth. Comments are moved down into the body of block regardless of length:

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAZgAgBQA8CUmwmA9CZmADpQC+IANCBAA4yrQDOyoAhgE58IAdwAK-BFxQ8AbhFQATBiABGfHmADWcGAGVm61FADmyGHwCucRgAsYAWwA2AdWup4HfWDg6Jb1NLcAT2RwDi5GQw44PhgRNSM7HmR0HgcoxgArDlwAITVNbR0eOzgAGUM4ZNT0kCzcHUMjBzgARXMIeCq0qxB9Pii+EOUeZUCHaCVmPkMYJwUYa2QADgAGRimIKKc1ZhCpuAHpSsYAR3b4OJZJEB4OAFooODh5Z6U+ODPUd7ieBKSkFLdRhROyoUwWHocRrNNodSoA6o9GAjObyBbIABMjDMPFQDkaAGEIHZEiEoNBjiBzFEACojSSAqI0GhAA)
```sh
--parser babylon
```

**Input:**
```jsx
if (x) { // c
}
```

**Output:**
```jsx
if (x) {
  // c
}

```

Why? Because comments are one of the trickiest parts of Prettier. Maybe we can support printing them at the same line, maybe not. Either way I think it’s fine that they are moved down in this case. Except that it breaks `// some-tool-do-something-to-this-line` comments of course.

But that’s a known issue. We recommend using `// eslint-disable-next-line` instead for this reason. See #1267 and the issues that link to it. A bit sad, but workable.

**Comment by JounQin** [comment]
@lydell What if I'm using `eslint` with `tslint` together and they complain about same line together?

```ts
// tslint:disable-next-line no-magic-numbers
if (minorVersion >= 6.4) { // eslint-disable-line @typescript-eslint/no-magic-numbers
}
```

What means I cann't use `next-line` comments for `eslint` and `tslint` either at the same time.

**Comment by lydell** [comment]
Why do you use both? TSLint is deprecated in favor of the `@typescript-eslint` plugin, isn’t it?

**Comment by JounQin** [comment]
@lydell `@typescript-eslint` does provide all rules like tslint for now, that's why [eslint-plugin-tslint](https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin-tslint) exists.

**Comment by lydell** [comment]
But surely there’s no need running both TSLint’s `no-magic-numbers` _and_ `@typescript-eslint/no-magic-numbers`? I’d turn remove TSLint’s rule from the configuration and enjoy faster linting.

**Comment by JounQin** [comment]
It's just a simple example, they could be different rules targetting different purposes.

**Comment by lydell** [comment]
ESlint also has a `no-console` rule.

```
 // eslint-disable-next-line @typescript-eslint/unbound-method, no-console
```

But, sure, I totally understand that this is a flaw in Prettier. On the other hand, why worry about a problem you don’t have?

**Comment by JounQin** [comment]
Fine, then I'm going to create something like `tslint-config-eslint` which disables all rules which has been handlered by `eslint` or `@typescript-eslint`.

But I still think it is a `bug` instead of a small `flaw` of `Prettier`.
