### ISSUE TITLE
React.forwardRef + flow

### ISSUE THREAD

**Issue by ValeryStatinov** [prettier/prettier#6518]
Prettier fails working with React.forwardRef and Flow

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhCBbAB0wF5MAlOAQzBgDoAzCAJwHdKmATC+gHgAUmEAmgA0mABIAVALIAZAKIAbOHgQwAfAApNwTAUFEAvmKZx6AShLrMPGJQDmmU-WLBnhzGEWU0aAHKUqq76Qh4A9OrmANwAOlAgIiBCMACW6Mig7IIsfOwIaMgglABuECkcCSAARkzUANZwMADKBNQpUPbIMEwArnCJABYweIoA6gMp8GitYHBN+ZMpxZMAnoVgvpXtaHBMMAIOeJTI9JSKO4kAVmgAHgBCtWANzYFwsu1wJ2cXINc3Te17MoAIo9CDwL7nfogVpMHZMQpVShVFaKaCVfTtGCjcowAbIAAcAAZEiEdqNagRCvo4PDip9EgBHMHwARCAooHwAWigcDgHH5lVMzJSpgO9iOkJ+OzwKS6vWhaEBIJZnyQpyhiTsVRxHDxyAATFrailFIDcHhJSgoNAGSAejtJMiORqdoZDEA)
```sh
--parser babylon
```

**Input:**
```jsx
const Comp = React.forwardRef<Props, HTMLElement>(({ prop }, ref) => <tag ref={ref} className={prop} />);

```

**Output:**
```jsx
SyntaxError: Unexpected token (1:49)
> 1 | const Comp = React.forwardRef<Props, HTMLElement>(({ prop }, ref) => <tag ref={ref} className={prop} />);
    |                                                 ^
  2 | 
```

**Expected behavior:**
Prettier works

**Comment by evilebottnawi** [comment]
hm, maybe we need update flow parser

**Comment by lydell** [comment]
The `babylon` parser is deprecated. It's now called `babel`.

Some Flow syntax is ambiguous. That's why the `babel-flow` parser also exists, to prefer the Flow interpretation of code. You can also use the `flow` parser.

**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBhCBbAB0wF5MAlOAQzBgDoAzCAJwHdKmATC+gHgAUmEAmgA0mABIAVALIAZAKIAbOHgQwAfAApNwTAUFEAvmKZx6AShLrMPGJQDmmU-WLBnhzGEWU0aAHKUqq76Qh4A9OrmANwAOlAgIiBCMACW6Mig7IIsfOwIaMgglABuECkcCSAARkzUANZwMADKBNQpUPbIMEwArnCJABYweIoA6gMp8GitYHBN+ZMpxZMAnoVgvpXtaHBMMAIOeJTI9JSKO4kAVmgAHgBCtWANzYFwsu1wJ2cXINc3Te17MoAIo9CDwL7nfogVpMHZMQpVShVOCKSr6dowUblGADZAADgADIkQjtRrUCIV9HB4cVPokAI5g+ACIQFFA+AC0UDgcA4fMqpiZKVMB3sR0hPx2eBSXV60LQgJBzM+SFOUMSdiq2I4uOQACZNbUUopAbg8BKUFBoPSQD0dpJkez1TtDIYgA)
```sh
--parser babel
```

**Input:**
```jsx
const Comp = React.forwardRef<Props, HTMLElement>(({ prop }, ref) => <tag ref={ref} className={prop} />);

```

**Output:**
```jsx
SyntaxError: Unexpected token (1:49)
> 1 | const Comp = React.forwardRef<Props, HTMLElement>(({ prop }, ref) => <tag ref={ref} className={prop} />);
    |                                                 ^
  2 | 
```

**Comment by ValeryStatinov** [comment]
@lydell thanks for your response!
After changing parser to `babel-flow` I was able to make my file prettier:)

**Comment by evilebottnawi** [comment]
@ValeryStatinov It is great! I think we can close issue
