### ISSUE TITLE
Weird looking breaking with type arrays return type 

### ISSUE THREAD

**Issue by gcazaciuc** [prettier/prettier#652]
The following code:
```js
class Selection extends React.Component<void, PropsType, void> {
    props: PropsType;
    _onItemClick: (ev: SyntheticMouseEvent) => void;
    _removeSelectedItem: (selectedItems: Array<string | number>, resp: number) => Array<string | number>;
    _isSelectedItem: (id: number) => boolean;
     isSelectedRespondent: (type: string, firmId: number, hasRespondents: boolean) => boolean;
}
```

gets formatted to:

```js
class Selection extends React.Component<void, PropsType, void> {
    props: PropsType;
    _onItemClick: (ev: SyntheticMouseEvent) => void;
    _removeSelectedItem: (selectedItems: Array<string | number>, resp: number) => Array<
        | string
        | number>;
    _isSelectedItem: (id: number) => boolean;
    isSelectedRespondent: (type: string, firmId: number, hasRespondents: boolean) => boolean;
}
```

The babel-eslint complains that there is a syntax error around `Array<
        | string
        | number>` 
part.

Also note that this is somewhat inconsistent with how type aliases are being formatted:

```js
type X = | number | string;
```

gets transformed into 
```js
type X = number | string;
```

**Comment by jlongster** [comment]
Babel might not support this Flow syntax yet. I'm pretty sure this is valid. @hzoo do you know if Babel should parse the above code?

**Comment by jlongster** [comment]
> type X = number | string;

It's not inconsistent; for inline types it formats it that way, but when it breaks it up, it forms it like this:

```js
type X =
  | number
  | string
  | number
  | string
  | number
  | string
  | number;
```

I think what you've unconvered is a problem with array function types though, and something else in the arrow function type should break before breaking the return type.

**Comment by hzoo** [comment]
Babylon supports it so might be a bug in babel-eslint (which I haven't updated in a long time). It does use `^` though so maybe you need to make sure you are on the latest version.

**Comment by vjeux** [comment]
Labelling this as a bug, we should be splitting the arguments before the return type.

**Comment by vjeux** [comment]
It seems to have been fixed since this issue was opened. 

```js
class Selection extends React.Component<void, PropsType, void> {
    props: PropsType;
    _onItemClick: (ev: SyntheticMouseEvent) => void;
    _removeSelectedItem: (selectedItems: Array<string | number>, resp: number) => Array<string | number>;
    _isSelectedItem: (id: number) => boolean;
     isSelectedRespondent: (type: string, firmId: number, hasRespondents: boolean) => boolean;
}
```

now looks

```js
class Selection extends React.Component<void, PropsType, void> {
  props: PropsType;
  _onItemClick: (ev: SyntheticMouseEvent) => void;
  _removeSelectedItem: (
    selectedItems: Array<string | number>,
    resp: number
  ) => Array<string | number>;
  _isSelectedItem: (id: number) => boolean;
  isSelectedRespondent: (
    type: string,
    firmId: number,
    hasRespondents: boolean
  ) => boolean;
}
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22class%20Selection%20extends%20React.Component%3Cvoid%2C%20PropsType%2C%20void%3E%20%7B%5Cn%20%20%20%20props%3A%20PropsType%3B%5Cn%20%20%20%20_onItemClick%3A%20(ev%3A%20SyntheticMouseEvent)%20%3D%3E%20void%3B%5Cn%20%20%20%20_removeSelectedItem%3A%20(selectedItems%3A%20Array%3Cstring%20%7C%20number%3E%2C%20resp%3A%20number)%20%3D%3E%20Array%3Cstring%20%7C%20number%3E%3B%5Cn%20%20%20%20_isSelectedItem%3A%20(id%3A%20number)%20%3D%3E%20boolean%3B%5Cn%20%20%20%20%20isSelectedRespondent%3A%20(type%3A%20string%2C%20firmId%3A%20number%2C%20hasRespondents%3A%20boolean)%20%3D%3E%20boolean%3B%5Cn%7D%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D
