### ISSUE TITLE
Better vim support?

### ISSUE THREAD

**Issue by karthikv** [prettier/prettier#658]
I started using prettier recently and ran into troubles with the vim format-on-save support. The recommended approaches don't restore cursor position cleanly (even with the `<C-o>`s), causing the code to jump upon save. Saving code is a reasonably frequent operation for me, and this behavior is fairly disturbing. See the gif below:

![current vim format-on-save](http://g.recordit.co/cFEyg1GW0R.gif)

Other vim plugins that perform format-on-save, like [vim-go](https://github.com/fatih/vim-go) and [elm-vim](https://github.com/ElmCast/elm-vim) don't have any such jumps. They use `winsaveview()` and `winrestview()` to save/restore the window position. I repurposed the vim-go implementation for prettier in my .vimrc file at https://github.com/karthikv/dotfiles/blob/5a289e0/vimrc#L152-L203. It works like so:

![alternate vim format-on-save](http://g.recordit.co/t6zJf806Yz.gif)

If there's interest, I'd be happy to factor this out into a simple vim plugin to help other prettier users. The installation would be a single command with standard vim package managers (vim-plug/vundle/neobundle/pathogen). If not, that's fine too, but I'd love to hear any thoughts.

**Comment by tmcw** [comment]
You might want to try out [Neoformat](https://github.com/sbdchd/neoformat) - it supports prettier by default and is able to keep cursor position while auto-formatting on save.

**Comment by karthikv** [comment]
@tmcw Good call! I just replaced my ad-hoc solution with Neoformat; it has no jumps and works with minimal configuration (see https://github.com/karthikv/dotfiles/blob/9f6b0c8/vimrc#L144-L145). Perhaps we could change the recommended approach on the README to use Neoformat? The experience is just like the second screenshot above, which is significantly better than the current approach.

**Comment by mvolkmann** [comment]
Is there a way to specify options such as --single-quote when running this from Vim?
The docs suggest this Vim setup which works:
````
autocmd FileType javascript set formatprg=prettier\ --stdin
````
But I haven't found a way to specify options.

**Comment by karthikv** [comment]
@mvolkmann If you're using the approach in the current docs, you can add the options directly to `formatprg`, like so:

```vim
autocmd FileType javascript set formatprg=prettier\ --stdin\ --single-quote
```

The spaces in the command must to be escaped, hence the backslashes.

If you're using Neoformat, you can add a custom formatter with the args you'd like; see [their README](https://github.com/sbdchd/neoformat#config-optional).

**Comment by landabaso** [comment]
There's something else that bugs me.

Say you have a long buffer with many functions that has already been saved with prettier.

Then you write yet another function in the middle of that buffer and save so that prettier is run again.

After saving, if you press "u" (for undo) the cursor jumps to the beginning of the file (even if that part did not change). Why is that? I usually press "u <CTRL> r" in order to see which was the last change in that file (even if it was related to formatting only).

Now I cannot do that since the cursor jumps to the top all the time. Why does it happen? Any workaround?

**Comment by lydell** [comment]
@landabaso Try [Neoformat](https://github.com/sbdchd/neoformat) as suggested by @tmcw – it works great!

**Comment by landabaso** [comment]
@lydell thanks, it worked. I did not want to depend on yet another plugin that does a whole more than what I need... Anyway, it works as it should, so thanks!

**Comment by lydell** [comment]
What more than formatting files does Neoformat do?

**Comment by landabaso** [comment]
@lydell, I'm sure a lot of care has been put in that project but it's yet another plugin I will need to update frequently (there are some open issues in that project -some related to prettier-). I'll have to keep track of yet another project in the years to come, ...
And there are always issues... For example, Neoformat conflicts with another plugin I was using (indentLine). When :Neoformat is run, the indent guides are removed.
That said, I am glad that Neoformat exists because it solved my problem brilliantly.

**Comment by vramana** [comment]
@karthikv Can we close this issue?

**Comment by mvolkmann** [comment]
Fine with me to close this.

**Comment by jlongster** [comment]
I'm going to be restructuring the editor info in the readme and `editors` folders and make it easier for people to collaborate on this. Right now the vim section is pretty barebones and probably should have it's own .md file explaining all the different ways to integrate.

If anyone wants to write that file in `editors`, please do!
