### ISSUE TITLE
No space after await in typescript parser (in some cases)

### ISSUE THREAD

**Issue by G-Rath** [prettier/prettier#6608]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA7qgljABAChgCcBXOXAfgB0pc77izclcAzVAGwGc4BKAbhogANCAgAHGFmhdkoVESIR0ABQUJZKVADcIWACYiQAIyKowAazgwAyuPNYoAc2SM4ogBYwAthwDqHjhwXPZgcDYaOFjaOACeyOBcsqKOPEQwKmZO3qjI7NzuIABWXAAeAEJmltY2qN5wADKOcHmcPKIlpTaOThxwAIokEPCtBaL2RGkJMLHiwWBEWJJG4ouwfgYwHsgAHAAM40o8fmbiCavBcETaLaIAjkPwmRKaaFwAtFBwcPo-RkRwB5YAGZVDZXJIfLtEA8bxYVykQpcHp9QbDFqQtqFGCoYwbfRbZAAJlExGwHB6AGEIN4cgkoNBbiASDwACq4zRQuAAX25QA)
```sh
--parser typescript
```

**Input:**
```tsx
await (true ?
      true : false);

```

**Output:**
```tsx
await(true ? true : false);

```

**Expected behavior:**
```tsx
await (true ? true : false);

```

This is an interesting one, as I've found in my IDE if I select just that line and format I'll get the above unexpected output, but if I format the whole file I get the expected output.

**Comment by thorn0** [comment]
Not a bug. TS does not support top level `await`, so this works as expected.

**Comment by kachkaev** [comment]
Indeed, 

```ts
const myFn = async () => {
  await (true ?
    true : false);  
}
```

formats as 

```ts
const myFn = async () => {
  await (true ? true : false);
};
```

[Playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEBbAngMSkwF5MBDNXKMTACgEoSA+TYAHSPIHcyBLLWjABOAVziYA-B0wzMwsZiSYAZmQA2aOPQDcMjgF8OIADQgIABxi90yUGSFCIXAAr2EaZCDIA3CLwAmJiAARkJkYADWcDAAyubhvFAA5sjycKYAFjDYagDqGfxwaPFgcDHu-Lze-LieYGgepomaQjDOYUnYZMiqGukgAFZoAB4AQmGR0TFk2HAAMolwPeqapkPDMYlJanAAiiIQ8Mt9pvFCLZ4wuOZFYEK8lkHm97C5ATAZyAAcAAynjppcmFzJ5nkU4EJvEtTABHA7wdoWDwoCgAWigcDg-ixQSEcDhvDx7TInW6SF6qxAmmwvFSon6aC2O32hyW5JW-RgZGCb38H2QACZTMI+GotgBhCDYLqeKDQaEgESaAAq3ORFLg+n0QA)

**Comment by sosukesuzuki** [comment]
Thank you @thorn0 , @kachkaev . I probably understood.

The following cases is a bug, right?

[Playground Link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDAzgTymABAMwFccYBLaAiCACgEpdgAdKXXVAd1VJl2pgCdCcXAH5cAobiTjBcWswC+IADQgIABzLR0yUKn78I7AAr6EOlKgBuEUgBMVIAEb9UYANZwYAZXVvSUADmyBJwqgAWMAC2ADYA6uHccOh+YHDe5tykVtyYyODoOqoB6HD8MMaugVGoyPioMaWqAFboAB4AQq4eXt6oUXAAMgFwdQ1NIK1t3gGBMXAAioQQ8GONYSB+-KX8+TCY6slg-KSajuonsHH2MOHIABwADKoXEKVxrur5F8llVqOqACOy3glQ0FjQ6AAtFA4HA7PDHPw4MDSMjKqhqrUkPV1qpSlFSCFZPjZvMlitRjjxhsYKgnNc7LdkAAmVQCLgxWYAYQgURq+Sg0ABIEIpQAKvSLLiJq4gnAAKJQBxIACszxAcsC6Tp5VZABYFAogA)

```
--parser=typescript
--range-start=24
--range-end=50
```

**Input:**
```ts
async function foo() {
  await (true ? true : true)
}
```

**Output:**
```ts
async function foo() {
  await(true ? true : true);
}
```

**Comment by thorn0** [comment]
Yep, but given that top-level await is coming anyway, it makes sense to always parse `await` as a keyword. Moreover, in some situations, TS already parses it as a keyword outside async functions, e.g. in front of function calls: `await f()`, see [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA7qgljABAMwAoBKEAGhAgAcYtoBnZUVAJxYnQAVWFGVUAbhCwATciABGLVGADWcGAGUqMrFADmyGCwCucCgAsYAWwA2AdQM449FWDiLeOLAJwBPZOHqMKa+nBYYTml1Y1RkfFRTfwoAK3oADwAhaTkFRVRjOAAZNTgIqJiQeITFNXVTOABFHQh4Auj9EBUWfxZPGDcqGzAWLBpxKj7Yc1EYA2QADgAGCiGIf3NpKk8hmwCBfIoAR1r4YOo+NHoAWig4OBFL8RY4Xaxb4NRQ8KRIxop-YywtXSb6cqVGp1fJvQpNGCoCSjETjZAAJgo2mwpnKAGEIMYwp4oNAtiAdP4ACpQvjvfwAXwpQA), use the "Show AST" checkbox there.

**Comment by kirkwaiblinger** [comment]
I've done some poking around on this, hoping to put a PR, but this has some complex details to iron out. In short, this issue appears to be a consequence of where top-level await is syntactically allowed in typescript. Technically top-level await is only allowed inside module code ([more on this here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#top-level-await)). 

So, prettier correctly handles the snippet in the issue if we make it a module

**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBDA7qgljABAChgCcBXOXAfgB0pc77izclcAzVAGwGc4BKAbhpwAHgAcIRPMAC+IADQgIomFmhdkoVESIR0ABS0J1KTpgCe6hQCMiqMAGs4MAMqoAtnAAyWKHGTtuOGtbBydnUTsfAHNkRiCQHjcsWNJ4kVE4IiwPWE4AFUyoLSw4YwCeBS5ojjgARRIIeH9OCpAAKy5hZ2q6hqakcviARz64PR1RYzQuAFpfOAATRfkQYmwOaIBhCDc3VGQ0Dg4VqqgomoBBGGIsKxJ4PUzvX2bAhQALGDcOAHV3nFKETAcGcRhwWAAbjgzAcwFxLCAIWQAJJQJawZxgLLKC5o5wwMw1V6tUQ6Hg-WyiA6k0qZCF+BQ+HiScaoKJ7YnxCJEZkHAkZLhYrDKFaknwwH5YBYwd7IAAcAAYFEQ4CMsCrWez9gMWvEYKgrJLpbKkAAmBQkHh5A1lXUKOBuKyLJYLTyoM4kNlwABiEj212iB1Q9wgIGk0iAA)

```sh
--parser typescript
```

**Input:**

```tsx
await (true ?
      true : false);
export {}
```

**Output:**

```tsx
await (true ? true : false);
export {};

```

In _non-module_ code, `await x` is still treated as an "AwaitExpression", and therefore still prints as expected, despite being invalid TS. However, `await (/* an expression in parentheses */)` is treated as a "CallExpression". _Technically_, it is valid typescript to create a function called `await` and call it (see [TS Playground link](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAQwO7JlAPAFQHwAUAHgFyI4CUZOiA3ogE4CmUIDSRiAvgNwBQaDFAIEKiALx463CqJ5A)), though, even though this fails at runtime for me in the browser. Therefore, with a bit of mental gymnastics, you can convince yourself the `await` in
```ts
function await<T>(x: T): T { return x };
await(() => { })();
```
_correctly_ does not have a space after it (see also the [typescript-eslint playground](https://typescript-eslint.io/play/#ts=5.2.2&showAST=es&fileType=.tsx&code=GYVwdgxgLglg9mABAQwO7JlAPAFQHwAUAHgFyI4CUZOiA3ogE4CmUIDSRiAvgNwCwAKDQYoBAhUQBePHW4VxPIA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false)). Ditto for some atrocity like this:
```ts
declare const await: any;
await?.property;
```

Speculating a bit, I think that the only time the behavior described in the issue could really happen is with illegal top-level await (outside of module code) that _also_ happens to be followed by parentheses (and perhaps a few other syntactic scenarios apart from simply `await x;`). That seems very unlikely to occur in real-world code.  However, it's quite likely to occur in _code snippets_, where the parser isn't interpreting the snippet as module code. See, for example, [this example in the wild](https://typescript-eslint.io/rules/no-floating-promises/#ignoreiife), whose source is typescript embedded in markdown formatted by prettier. I'm pretty sure this analysis also helps explain the findings in the other comments in this issue, where a range behaves differently than the whole file.

It seems that in order to "fix" the behavior in code snippets, one possibility would be to proactively interpret snippets as module code, which may not be a sound thing to do in general (I'm not sure). Or, maybe prettier is doing it right, and one should just not use top-level await in code snippets without inserting an `export {}`. Looking for guidance on how (or whether!) to proceed with this issue. 

Afterthought - you can also construct a related scenario with the yield keyword, like so
**Prettier 3.1.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBPAlnANgEwAQAUBAlHgLwB8ewAvsQDpSMBmArlGDOtAFR4DmCOACcAhjAjCS1RnjwZs+IqUrU6jGiAA0ICAAcu0AM7JQo4cIgB3AArmEJlKKxXRqEzoBGYsAGs4MADKogC2cAAy6FBwyMzORnBePv5BeqJgUfzIMMKsiSAJIejZuflwAB56IuhhsM4AKiJQ5piOcVgJOkaZWHAAiqwQ8LHx+QBWRuWBPf2Dw0jtnSAAjnNwNpZ6jiCiRgC00XA4R9ogOaLoWJkAwhAhIaLIO1hYp91Q-L0AgjA56J6seA2ESRaIjDr5AAWMBCWAA6pD0PAjGkwHBAg4kegAG5I1BPMBGDwgbF5ACSUGOsECYGE6AMX0pgRgqF64KWeksCThYj0T05cASwmxMR0USFMA2on4D3Z+TSwiFTxZVSMtPpMFOnKiMDh6BwMEhyAAHAAGHTCOCrdCWqUyx4LUY6GCiTx6g1GpAAJh0rAS9VdbSdIDgIU8R2OOHCog+rGlcAAYpIHr9Mk9RICICAaDQgA)

```sh
--parser typescript
```

**Input:**

```tsx
yield (() => {})

function* generator() {
  yield (() => {})
}
```

**Output:**

```tsx
yield(() => {});

function* generator() {
  yield () => {};
}

```

**Comment by abrahamguo** [comment]
@kirkwaiblinger no worries if this was too long ago and you don't remember, but how does this your explanation make sense in light that TypeScript adds `export {};` to the emitted JS, in effect forcing the JS file to be a module even if the TS file wasn't a module?

**Comment by kirkwaiblinger** [comment]
@abrahamguo I'm not quite sure what you're referring to here
