### ISSUE TITLE
this PR need revert

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6719]
this PR 

https://github.com/prettier/prettier/pull/6333

we are  using `globby` , but current version we  are using is not 

> the syntax from the fast-glob module

**Comment by lydell** [comment]
You’re right. We use `globby` 6.1.0 (which uses the `glob` package). `globby` 8.0.0 is the first version that uses `fast-glob` instead.

**Comment by brodybits** [comment]
I think a few things should be clarified for the sake of globby newbies such as myself:

- this would be an inconsistency in the docs, not an issue with the source code or package.json
- globby 8 and 9 are not wanted due to performance issue ref:
  - #6639;
  - sindresorhus/globby#79

Here is a side point from <https://github.com/sindresorhus/globby/issues/79#issuecomment-507018394> that may be off-topic:

> The latest globby v10 is nearing v7 performance. v10 is about 3-4 times faster than v9, and still about twice slower than v7.

I think the revert should be done ASAP to avoid any possible confusion. Anything I can do to help get this done?

**Comment by fisker** [comment]
I did revert this in in Aug https://github.com/fisker/prettier/commit/9acdf952041023729693c0b0e2496d309005af3e, but somehow forgot to submit a PR
