### ISSUE TITLE
Stage 1 decorators error when used with generator functions

### ISSUE THREAD

**Issue by pzuraq** [prettier/prettier#6747]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: CLI, Browser
- Runtime: Node.js v10, Chrome
- Operating System: macOS

**Steps to reproduce:**

When using stage 1 decorators, and specifically adding a decorator to an exported class _before_ the export (e.g. like TypeScript decorators), the Babel parser fails if attempting to decorate a generator function:

```js
@foo
export default class MyComponent {
  @task
  *foo() {}
}
```

This works on the current versions of Babel, but throws a parser error in Prettier.

- [Babel playground example](https://babeljs.io/en/repl#?babili=false&browsers=Last%201%20Chrome%20Version&build=&builtIns=false&spec=false&loose=true&code_lz=AIMw9mBQCmAeAOYBOAXABAE2iAhgVwBt0BjAnAZ3LQFkBPAYTAFtEA7aV9Ab0jTWBQUA1rzQAqcGAAUASjQ8-AX0iKgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=react%2Cstage-1%2Cenv&prettier=true&targets=Node-8.9&version=7.6.4&externalPlugins=)
- [Prettier playground example](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhCAdKcAeADhAE4wAEAJnOgIYCuANhWI7QM7vkCyAngMIQAtsTyxywXOXKoYHANZTyAKkwQAFAEoJSgL65dIADQgIhGAEto7ZKFokSEAO4AFewhspaANwgXKxiAARiS0YPJwMADKhGEWUADmyDAk9HAmABYwQowA6hkW8OyxYHBRHoUW3oW8yOCcgfHscGQuoQlCtMh0jM0mAFbs+ABCoeGRUbRCcAAy8XDdtL3pIIP4UfEJjHAAivQQ8IvLJrEkzSR1QbRBcIyBhCTxMLn+MBnIABwADCeOzbmhQh1B5wc7eBYmACO+3gbTMnhAHAAtHg4NQAiYSHBoRYsW1aB0ukgen0QM0hBZkqkVuxNts9gcFsSlqS5EEXpQ3sgAEwmFK0CyMTaCISdOpQaAQkD0ZoAFWunhJcF0uiAA)

**Expected behavior:**

Prettier should parse and prettify the code

**Actual behavior:**

Prettier is unable to parse the code and throws a syntax error

**Comment by thorn0** [comment]
fixed in 1.19.1

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEABAZhCAdKcAeADhAE4wAEAJnOgIYCuANhWI7QM7vkCyAngMIQAtsTyxywXOXKoYHANZTyAKkwQAFAEoJSgL65dIADQgIhGAEto7ZKFokSEAO4AFewhspaANwgXKxiAARiS0YPJwMADKhGEWUADmyDAk9HAmABYwQowA6hkW8OyxYHBRHoUW3oW8yOCcgfHscGQuoQlCtMh0jM0mAFbs+ABCoeGRUbRCcAAy8XDdtL3pIIP4UfEJjHAAivQQ8IvLJrEkzSR1QbRBcIyBhCTxMLn+MBnIABwADCeOzbmhQh1B5wc7eBYmACO+3gbTMnhAHAAtHg4NQAiYSHBoRYsW1aB0ukgen0QM0hBZkqkVuxNts9gcFsSlqS5EEXpQ3sgAEwmFK0CyMTaCISdOpQaAQkD0ZoAFWunhJcF0uiAA)
```sh
--parser babel
```

**Input:**
```jsx
@foo
export default class MyComponent {
  @task
  *foo() {
  }
}
```

**Output:**
```jsx
@foo
export default class MyComponent {
  @task
  *foo() {}
}

```
