### ISSUE TITLE
设置"proseWrap": "never"属性，格式化后的代码效果依然是“printWidth”：80的效果

### ISSUE THREAD

**Issue by 007GitHu** [prettier/prettier#6766]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#.....)
```sh
# Options (if any):
--parser babylon
--proseWrap never
```

**Input:**
```jsx
    <xx-text title="测试" model="hyTest" placeholder="海颐gt里的text"></xx-text>
```

**Output:**
```jsx
     <xx-text
          title="测试"
          model="hyTest"
          placeholder="海颐gt里的text"
        ></xx-text>
```

**Expected behavior:**
--proseWrap never这个属性的意思是不强制换行，但是设置了这个属性之后，看代码的效果依然是根据--printWidth 80这个属性来格式化代码的，我不想让代码换行，如何写属性呢

**Comment by thorn0** [comment]
[`--prose-wrap`](https://prettier.io/docs/en/options.html#prose-wrap) is an option for Markdown. It doesn't affect how JavaScript is formatted.

If you don't want your code to wrap based on `printWidth`, you should probably use some other formatter, not Prettier. Because `printWidth` is at the core of Prettier's formatting algorithm.
