### ISSUE TITLE
No matching files. Patterns tried: src\app\test\modules\test\ant-test !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

### ISSUE THREAD

**Issue by 007GitHu** [prettier/prettier#6799]
**Environments:**
- Prettier Version: 1.18.2
- Running Prettier via: 
CLI:7.3.8
 Node.js：v12.6.0

- Runtime:  Node.js：v12.6.0
- Operating System: Windows
**Steps to reproduce:**
After configuration, format error

**Expected behavior:**
Formatted code
**Actual behavior:**
Error when formatting code，what should   I  do：
No matching files. Patterns tried: src\app\test\modules\test\ant-test !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**

**Comment by lydell** [comment]
Hi!

Since you use Prettier – do you program? Imagine getting a bug report like this – what would you do with it? Where would you start?

I have no idea what you’re doing. I have no idea what `CLI:7.3.8` is. You didn’t say what command you are running, or what files you have.

Thanks for using Prettier, but this is not helpful – it’s actually just wasting our time :(

**Comment by fisker** [comment]
@lydell issue template says `CLI`

```text
- Prettier Version: 1.18.2
- Running Prettier via: <!-- CLI, Node.js API, Browser API, etc. -->
```

maybe this template is not clear.

@007GitHu have you try `src/app/test/modules/test/ant-test` instead of `src\app\test\modules\test\ant-test`

**Comment by fisker** [comment]
@007GitHu 

you are not using it right, 

```bash
prettier src/app/test/modules/test/ant-test/**/* 
```

we don't support `dirname` yet, only glob.
