### ISSUE TITLE
Enforce Trailing Commas by Default

### ISSUE THREAD

**Issue by btnwtn** [prettier/prettier#68]
I propose that trailing commas should be enabled by default. IE8 is a non issue for most, and this will provide better diffing.

```js
const arr = [
  'multi',
  'line'
]
```

should be formatted as:

```js
const arr = [
  'multi',
  'line',
]
```

I would also suggest not enabling it for function arguments, considering that this is not in the official spec yet and won't be fully supported without a transpiler like babel. e.g.:

```js
foo(
  arg1,
  arg2,
)
```

should be formatted as:

```js
foo(
  arg1,
  arg2
)
```

**Comment by Pomax** [comment]
I'll represent the other camp: clean code does not need trailing commas, as there's nothing following that comma. Actually inserting commas would be a reason for me to not want to use this formatter.

**Comment by leeoniya** [comment]
arrays often have line-level similarity and for editors that have a "duplicate line" functionality, a trailing comma at the end can yield better ergonomics.

/ $0.02

**Comment by jlongster** [comment]
Right now we at least have the option, so you can turn it on. This is a question of if it should be the default. I'm leaning towards not, because it I get the sense that the majority (by a little margin) doesn't use them, but I can let this sit for a while. You can at least turn them on if you want them.

**Comment by demoneaux** [comment]
I think they should not be enabled by default, due to the trailing commas in function parameters as well. In fact, that should probably also be made configurable similar to recast:

```js
trailingCommas: {
  array: true,
  object: true, 
  function: false 
}
```

**Comment by thejameskyle** [comment]
> I get the sense that the majority (by a little margin) doesn't use them

@jlongster That probably has a lot to do with trailing commas being invalid in a number of places which has since changed. I know Airbnb's code style thing changed afterwards @ljharb

**Comment by ljharb** [comment]
Trailing function commas recently hit stage 4, and haven't been published in the standard yet (which it will be this June - although "published" is irrelevant, only "hit master on github" matters).

The airbnb config requires trailing commas anywhere they're allowed to appear, to ensure consistency and to minimize git diffs. Whether it's the default or not is certainly your choice, but my hunch is that the majority of the airbnb config is going to be very close to what most users use, either now, or eventually.

**Comment by mxstbr** [comment]
Related article by @nikgraf: https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8#.ur8s3venv

**Comment by okonet** [comment]
I'm opposed to that. I have tried both styles and thus better ergonomics in the editor is a valid argument but this only matters until I Finish editing it. Same with the diff — if the algorithm can't handle it, algorithm should be improved and not the source code get altered to please the machine. 

The formatting of the code should not be dictated by tools but by readability. Tools should follow what is good for humans and not for robots. A trailing comma has no semantic but represents a visual noise.

**Comment by ljharb** [comment]
Minimal git diffs are good for humans, and consistency is good for readability.

**Comment by potch** [comment]
I expect formatted code to run in browsers without any additional processing, and would prefer any feature that breaks that not be on by default. This rules out trailing commas in functions.

**Comment by ljharb** [comment]
Technically that rules out all forms of trailing commas as well as any unquoted reserved words, or variable names with reserved words - either you're hand coding to ES3, you're breaking browsers, or you're using some additiona processing ¯\\\_(ツ)_/¯

**Comment by mattbasta** [comment]
@potch trailing commas in lists and objects is supported by everything in recent history (IE9 was the last browser affected, and only in compatibility mode; IE8 was the last browser to wholesale shit the bed on trailing commas).

I think, obviously, trailing commas in arg lists is a bad idea for now. I don't think it's reasonable to make it a default until IE11 is dead and gone and ES2017 has settled in all of the evergreen browsers for a few years.

As for why I support trailing commas, I find it prevents many errors when copying and pasting. It's a quality of life thing. If you use the "shift lines" feature in your text editor, you'll know how much of a hassle it is when you've got a missing comma. In particular, if you always use a trailing comma, you'll never have a problem. This is in contrast to, say, leaving off semicolons where you need to remember a handful of rules for when you have to include them.

**Comment by potch** [comment]
@mattbasta yeah, can't say I super care strongly about arrays and object literals for trailing commas. It feels like a violation of principle of least surprise to see characters added like that, but I'd rather have consistent formatting in an easy-to-use tool than it hew exactly to my preferences. 

Just no syntax errors please! I guess I'd be annoyed if I was intentionally writing ES3 to have it ES5ified, but that's a super niche case and the basic config covers it.

**Comment by btnwtn** [comment]
@potch how do trailing commas in an array or object break browsers? Are we targeting IE8 here? And if so... please reconsider.

**Comment by mythmon** [comment]
I hope that tools like prettier wouldn't be concerned about ES3 compatibility. I'd vote for trailing commas in multiline arrays and objects by default, and optionally for parameter lists. As well as making VCS diffs easier, it also makes re-ordering lines easier in an editor, as one doesn't have to worry about the presence or absence of the trailing comma.

**Comment by ljharb** [comment]
(for what it's worth, I agree all this should be configurable; I should be able to use prettier for hand-writing ES3, ES5, ES6, etc, as well as for code intended to be run through babel - we're just talking about the default here)

**Comment by luisherranz** [comment]
I agree. We should be able to use prettier for ES5 code as well, not only trough babel.

Maybe we need `.prettierrc` files for ease of use, so we can add things like @demoneaux said on each project: 
```
trailingCommas: {
  array: true,
  object: true, 
  function: false 
}
```

**Comment by btnwtn** [comment]
I'm actually going to close this issue as I think it completely misses the point of this project. I'm now of the opinion that there should be no config options for how code is formatted. Go fmt works this way and people are fine with it.

**Comment by luisherranz** [comment]
> I'm now of the opinion that there should be no config options for how code is formatted.

I'm going to miss prettier for ES5 projects but yeah, no config is definitively better if everyone ends up using it, which I hope.

**Comment by ljharb** [comment]
That'd be great - but it'll never happen without maximum configurability.

**Comment by btnwtn** [comment]
Then there's no point to this project.

**Comment by luisherranz** [comment]
> That'd be great - but it'll never happen without maximum configurability.

Then fork it.

**Comment by ljharb** [comment]
That's certainly an option, as is continuing to use eslint as the majority of the ecosystem does. Forking,  however, will not likely help achieve the goal of "gofmt for JS"

**Comment by btnwtn** [comment]
Not sure if any project could achieve go fmt status. Maybe this one could
with work!

**Comment by mattbasta** [comment]
I don't want to get wrapped up in an existential crisis for the project, but perhaps this should be less of a discussion about configuration and more of a discussion about extensibility. Certainly, there are folks that would want to use this project in conjunction with ECMA proposals that are beyond what prettier can handle, JSX variants, or other things that simply don't work well with the project out-of-the-box. Being able to easily add support for parsing and formatting non-standard ES would even allow new formatting options to be developed and vetted "in production" without being on a weird branch of a fork somewhere.

Having a system for extensions would allow this discussion to be put to rest, since you could simply add a plugin for trailing commas. On the ES2017 bandwagon and want trailing commas in your arg lists? Plugin. Hate semicolons at the end of your lines? Plugin. I think that's at least a half-decent compromise, especially if there's not going to be a configuration system.

**Comment by btnwtn** [comment]
That's a great idea!!

**Comment by luisherranz** [comment]
If your position is *"there should be no config options for how code is formatted"*, how a plugin/preset system (instead of config options) is better?

Yes, people won't have to fork the project to make its own modifications, but fragmentation will still exist.

**Comment by ljharb** [comment]
Fragmentation already exists. Configuration/extensibility is how you reduce fragmentation by allowing everyone an easy path to get on the same tool, as eslint has done. Adding another opinionated tool to the mix doesn't reduce fragmentation, it increases it.

**Comment by jlongster** [comment]
There are many different goals we could go for, one of them also being like babel which is a build pipeline. That would involve making the system extensible and hooks for handling any node type. That's not a goal for this project.

That can be a powerful technique for some systems, but it spreads complexity to the user. There's a direct relationship to flexibility and complexity. This project aims to be relatively zero config, like babel before version 6. The reason is can work for this project is because we will aggressively support the latest ES standards, and adopt them around the same time people start using them. Additionally, we could even detect when we get an AST node that we don't know what to do with, and simply not format it (that was @vjeux's idea). That way we'd still run on code that we don't know how to handle.

But note that babylon, the parser, still needs to have support for parsing new language extensions. So there's a clear thing we can track: when babylon adds support for something, we can *very quicky* add support for it here. The code for individual AST nodes is so tiny that it's possible.

We can also bundle in things like Flow and TypeScript because the general size of the project is small since the lines per-node type on average is tiny. Doing that removes all needs for a complex plugin system.

Plugins wouldn't really solve the config issue, as instead of `--trailing-commas`, you do `--plugin trailing-comma` or whatever. And a goal of this project is to force a generally consistent style for everyone using it; plugins would make it possible to completely override parts of our system and we're not interested in that.

As I've said elsewhere, never say never. This project is only a few days old and let's give it a month or so with how it currently works. We'll probably add one or two more options, but only things that tweak very small things that help adoption in existing codebases.

**Comment by jlongster** [comment]
> Fragmentation already exists. Configuration/extensibility is how you reduce fragmentation by allowing everyone an easy path to get on the same tool, as eslint has done. Adding another opinionated tool to the mix doesn't reduce fragmentation, it increases it.

I would bet this project will not increase fragmentation if we stay zero config. From what I've seen, many people using small variants of different eslint config have been happy to jump on this and there's been less fragmentation so far. I agree that a few options (like the ones we have) help bring everyone together, but there are still certain ones that we won't include (like semicolons) but the community is already fragmented on those (people can use standard if they want).

**Comment by ljharb** [comment]
standard's choice to eschew semicolons has absolutely hindered its adoption, fwiw.

Thanks for responding so thoroughly. I'd like to see your goals achieved but I think many many people prioritize "It looks the way I like it "over "I don't have to think about how it looks", and if that is true, then any "zero config permitted" approach will not ever achieve enough adoption to become a defacto standard.

**Comment by rattrayalex** [comment]
@jlongster you mentioned an openness to revisiting this. This thread is the seventh-most-upvoted closed thread (most of the others were accepted) and has received few downvotes; making the `"es5"` option the default may make sense. Thoughts?

**Comment by sorahn** [comment]
`--trailing-comma es5` is the only config option I actually use.

Most of the way my shop is writing ES6 code is passing in objects of params.  Then we use destructuring inside the function to pull what we want out.  When destructuring objects, what I like to do is just add in the params as they get used, then come back later and have my editor sort the destructured properties alphabetically.  This works easily with ES5 style trailing commas, and I'd like to throw it in as a different reason than cleaner diffs for why to support trailing commas on multi line objects.

**Comment by klebba** [comment]
It would be great if `prettier` had a strict mode with zero configuration options, and this was the default.

**Comment by duailibe** [comment]
Hi @klebba. That's unlikely to happen now because it would be a breaking change in the Prettier's API and I personally don't think it's worth it.

**Comment by klebba** [comment]
@duailibe breaking changes can be managed using `semver`

**Comment by rattrayalex** [comment]
`trailingComma="es5"` is a candidate for Prettier 2.0; any discussion should move to #3503. If it is rejected we can unlock this issue.

**Comment by j-f1** [comment]
Reopening since the v2.0 issue has almost 100 comments. I don’t think there’s anything else to say here, but I’m reopening this to track our progress on v2.0.

**Comment by hsribei** [comment]
+1 Please default to trailing commas! 

I hate the added diff lines and the little dance to edit the last line then append one after it.

But I hate even more the idea of adding a `.prettierrc` file and *configure* my *zero config* code formatter.

So I'm deferring to whatever default prettier chooses, but hoping we can collectively lobby for the saner default. 🙏

**Comment by kripod** [comment]
I’m not sure why the `es5` option is preferred over `all`. Node.js 8 LTS already supports every type of trailing commas available.

**Comment by j-f1** [comment]
The original rationale was — if I remember correctly — that we don’t want to break ES5 code that people have written by default. If you use arrow functions or destructuring, we’ll preserve them, but we won’t convert ES5 constructs to ES>5 constructs, however `trailingComma: all` does that.

**Comment by kripod** [comment]
Thanks for the nice explanations!

**Comment by wujekbogdan** [comment]
@btnwtn
Totally agree. Reasons to add trailing commas:

- It's easier to refactor the code. When you change the order of object's properties then you don't have to play with adding/removing commas
- It's easier to add new properties. You don't have to worry about adding a coma after the last property because it's already there.

**Comment by ExE-Boss** [comment]
I’m in favour of this because it makes `git diff` a lot cleaner.

**Comment by slikts** [comment]
Trailing commas being off is one of the worst aspects of Prettier, since users tend to take it as a recommendation against a good language feature.

**Comment by Pomax** [comment]
To be clear: the power of prettier is "you don't care about whether it's right or wrong, all you care about is that it's correct javascript that won't error at runtime" and the rest of is 100% irrelevant: you right click, say "format document", and hit save. It's not something you should be placing any more value on than that. People reading Prettier-formatted code in order to learn what good JS style is, is plain crazy. That's not what most people do, they learn _absolutely horrible JS already_ from every online tutorial, and every project that has its own code styleguide. Prettier does not make that any worse, or any better honestly. It's orthogonal.

**Comment by slikts** [comment]
Stripping out trailing commas does make practical difference in the editing workflow and in creating diff churn. Prettier doesn't fix invalid syntax, so appending a line to a list or moving the last line requires manually adding the comma that otherwise would have been there. Appending a line to a list requires editing the previously last line, which shows up as a highlight in diffs and hence code review, so reading the diff requires mentally filtering out the noisy line. Likewise, when looking up blame info, changes to commas need to be stepped through to find the actual author of a line.

**Comment by lydell** [comment]
`trailingComma: es5` is most likely going to be the default in 2.0.

**Comment by slikts** [comment]
Yay for catching up to ES5, but it should be `all`.

**Comment by lydell** [comment]
Yes, some day.

**Comment by sosukesuzuki** [comment]
#6963 has been merged to next branch, can we close this issue?
