### ISSUE TITLE
Vue SFC style not formatted with lang attribute set to "css"

### ISSUE THREAD

**Issue by nimadera** [prettier/prettier#6871]
**Prettier 1.18.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgAhwEMoBzAXgB1x11r91IAHOAEwD5Kon9h9IcEAE5J8AYgBMRCQEEJAMXwBfLqgD0mXHHYgANCAhMYAS2jpkoIkKEQA7gAUrCcyiIA3CMdZ6QAIyFEYADWcDAAykyBxmTIMEIArnD6ABYwALY4AOrJxvDokWBwYc65xm65WMg05vrR6HBCMPYBpGlEyABmRDj1+gBW6AAeAEIBwaFhRGlwADLRcJ3dvSADg2HRpHgAivEQ8Is9SSCRQvVCVW6JPkxC0TCZXjDJyAAcAAz6NxD1mQFMVTc4Gc3At9ABHXbwZqGFwgIjoAC0UDgbDYPiEcAhxgxzSIrXaSC6h309TSxliCSO6A220hC0JSyOMCIvgerCeyAk+jiRGMOA2AGEIGk2lUoNBQSB4vUACoslxE+pKJRAA)
```sh
--parser vue
```

**Input:**
```vue
<style lang="css" scoped>
p { color: #2a2A2F }
</style>
```

**Output:**
```vue
<style lang="css" scoped>
p { color: #2a2A2F }
</style>

```

**Expected behavior:**
```vue
<style lang="css" scoped>
p { color: #2a2a2f }
</style>

```

The output is as expected if the lang attribute is set to "scss" or is removed altogether.

**Comment by evilebottnawi** [comment]
hm, but, because https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzjAngGzgPgB0oAHAAmDMhwgCckyBiAJgENmBBZgMTIF9iqAPSZcBEABoQEEjACW0dMlCtatCAHcACqoRKUrAG4Q5AE0kgARrVZgA1nBgBlErblQA5shi0ArnCkACxgAWxwAdUC5eHRXMDgnPWi5Q2isZHB0JSl3dDhaGC0bDxDWZAAzVhw8qQArdAAPACEbe0cnVhC4ABl3OAqqmpB6hqd3DzwARV8IeAHqgJBXWjzaDMN-CxJadxhwsxhA5AAOAAYpbYg88JsSDO24VcN+qQBHGfgimX0QVnQAWigcDgphBFlocHecghRVYJTKSEqCykeRCcm8fkW6HGUw+-URg0WMFYln2pkOyGYUh8rDkOHGAGEICFShkoNAXiBfHkACok-RIvJ8PhAA works fine

**Comment by evilebottnawi** [comment]
Feel free to send a PR, should be very easy to fix
