### ISSUE TITLE
Unexpected formatting of a return type in TypeScript

### ISSUE THREAD

**Issue by merlinnot** [prettier/prettier#6886]
**Prettier 1.19.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YA1OACwEswAbOAETiLGzoxhzwF48AQyIBPKGDwAKADpQ8eAG60GzAJIATJHhJcopADRyAlNoAK2CAFs6ROAB45CgMIRGzMDDrQiAOjNCuH4WdLBwGs502GAArnQwAEIQgRoAgkR2VgBGjKIA2gDkQjAwXFkx8EQFALp4AD54MVAacABmoeFyAHwCPcAAviAGIBA83sTIoIGWAO4B2AhEyCBCihB0GkMgWdhCYADWFADKGHuhpMilMXDDNDBWjADq9JWnYHBHi-F0ivGiy2AMltQnZcBYhKQrEJkK0hIw7MMAFZENAJXYHY5CKxwAAyHRhcIRIGRaCO52YAEUYhB4AT4TcQKdsKDljBRBh2JxuDAthg9DBHhsYDRkAAOAAMwz5EDsj12GGWfPYcGwyi2AEdqfALKMligRABaKBwcLhLYLTVRODgyHQpCw+nDTJ0S7Ya5O8lwKk0uB0okwIRZQUaYXIABMw1KQjojHOrisUOWUGgvuGMTsABVA3qHUTFNc1M0EDAjlyeKlmkc2cw-XB+v0gA)
```sh
--parser typescript
```

**Input:**
```ts
export const getVehicleDescriptor = async (
  vehicleId: string,
): Promise<
  Collections.Parts.PrintedCircuitBoardAssembly['attributes'] | undefined
> => {}
```

**Output:**
```ts
export const getVehicleDescriptor = async (
  vehicleId: string
): Promise<| Collections.Parts.PrintedCircuitBoardAssembly["attributes"]
| undefined> => {};

```

**Expected behavior:**
```ts
export const getVehicleDescriptor = async (
  vehicleId: string,
): Promise<
  | Collections.Parts.PrintedCircuitBoardAssembly['attributes']
  | undefined
> => {}
```

**Comment by thorn0** [comment]
Looking into this. Because the type inside `<...>` doesn't exceed `printWidth`, it should rather stay as in the input:
```ts
export const getVehicleDescriptor = async (
  vehicleId: string,
): Promise<
  Collections.Parts.PrintedCircuitBoardAssembly['attributes'] | undefined
> => {}
```

**Comment by lydell** [comment]
@thorn0 Sounds good, because that’s how Flow code is printed:

**Prettier 1.19.0**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wHM4YA1OACwEswAbOAETiLGzoxhzwF48AQyIBPKGDwAKADpQ8eAG60GzAJIATJHhJcopADRyAlNoAK2CAFs6ROAB45CgMIRGzMDDrQiAOjNCuH4WdLBwGs502GAArnQwAEIQgRoAgkR2VgBGjKKpMDBcWTHwRHgAPngxUBpwAGah4XIAfAKtwAC+IAYgEDzexMiggZYA7gHYCETIIEKKEHQa3SBZ2EJgANYUAMoY66GkyIUxcD00MFaMAOr0pXtgcNtT8XSK8aIzYBnLoXa4FkJSFYhMg6kJGHYegArIhoBJrTY7IRWOAAGUaoPBkJAMLQ2wOzAAijEIPBMRDTiA9tg-jMskIsnBGMsMHoYFdFjAaMgABwABh6rIgdiuawwM1Z7Dg2GUywAjiT4BY+tMUCIALRQODhcLLSYKqJwAFAkFIMEUnqZOhHbAnS0EuDE0lwcnYmAMjkaLnIABMPUKQjojAOriswJmUGgLp6MTsABUGarzdjFCc1DUEDBtpxuDBUjVtjBRMxXXAOh0gA)
```sh
--parser babel
```

**Input:**
```jsx
export const getVehicleDescriptor = async (
  vehicleId: string,
): Promise<
  Collections.Parts.PrintedCircuitBoardAssemblyAttributes | undefined
> => {}
```

**Output:**
```jsx
export const getVehicleDescriptor = async (
  vehicleId: string
): Promise<
  Collections.Parts.PrintedCircuitBoardAssemblyAttributes | undefined
> => {};

```

**Comment by thorn0** [comment]
Yes, Flow wasn't affected as it was caused by TS-specific code added in #6467.
