### ISSUE TITLE
Is this doc formating right?

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#6889]
docs/rationale.md changes in

https://github.com/prettier/prettier/commit/98d27c7de29891f986aa36af7b1bf0e424619f4e ,  shoudn't it ignored? just double checking changes 

@lydell

**Comment by fisker** [comment]
also is this a bug when formating `decorators after export`?

**Comment by lydell** [comment]
So apparently 1.18 handles both syntaxes, but not at the same time.

```
❯ echo '@decorator export class Foo {}' | prettier --parser babel
@decorator
export class Foo {}

~/src/LinkHints master
❯ echo 'export @decorator class Foo {}' | prettier --parser babel
export
@decorator
class Foo {}

❯ echo '@decorator export class Foo {}; export @decorator class Foo {}' | prettier --parser babel

[error] stdin: SyntaxError: Unexpected token, expected "{" (1:40)
[error] > 1 | @decorator export class Foo {}; export @decorator class Foo {}
[error]     |                                        ^
[error]   2 |
```

But 1.19 handles both at the same time:

```
❯ echo '@decorator export class Foo {}; export @decorator class Foo {}' | prettier --parser babel
@decorator
export class Foo {}
export
@decorator
class Foo {}
```

So previously when running Prettier on docs/rationale.md, Prettier would fail on this code block and thus ignore it. (Prettier always ignores errors in sublanguages, except in debug mode.)

So the change is not wrong. This _is_ how Prettier would format decorators in these cases. But maybe it was easier to understand the difference between the two syntaxes in the old example (if so, we should merge #6890).

Maybe we should also mention in the docs that we only support both syntaxes when using the `babel` and `babel-flow` parsers?

The interesting thing is – why did this change happen in 1.19? I think it is because we enabled error recovery in #6816. If so, is the code trying to parse with four different combinations of Babel options still needed?

https://github.com/prettier/prettier/blob/8c3efeb9df251da800cd118ecb4ddf7b33248ff4/src/language-js/parser-babylon.js#L56-L73

We should dig deeper into this and also see if this helps #6400.
