### ISSUE TITLE
Add `quoteProps: es3`

### ISSUE THREAD

**Issue by ExE-Boss** [prettier/prettier#6936]
When contributing new&nbsp;polyfills to&nbsp;[**ES‑Shims**](https://github.com/es-shims/es-shim-api), which&nbsp;have to&nbsp;use&nbsp;**ES3**, I&nbsp;still&nbsp;want to&nbsp;use&nbsp;Prettier for&nbsp;**ES‑Shim**&nbsp;packages that&nbsp;I&nbsp;own.

Since&nbsp;**Prettier**&nbsp;strips the&nbsp;quotes required by&nbsp;**ES3** for&nbsp;object&nbsp;properties named&nbsp;with&nbsp;keywords, I&nbsp;have&nbsp;to&nbsp;run&nbsp;`eslint ‑‑fix` after&nbsp;running&nbsp;`prettier --write`, which&nbsp;is&nbsp;annoying.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#.....)

**Input:**
```js
function __generator(thisArg, body) {
    var g;
    return g = { next: verb(0), "throw": verb(1), return: verb(2) }, typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        // …
    }
}
```

**Output:**
```js
function __generator(thisArg, body) {
	var g;
	return (
		(g = { next: verb(0), throw: verb(1), return: verb(2) }),
		typeof Symbol === "function" &&
			(g[Symbol.iterator] = function() {
				return this;
			}),
		g
	);
	function verb(n) {
		return function(v) {
			return step([n, v]);
		};
	}
}
```

**Expected behavior:**

```js
function __generator(thisArg, body) {
	var g;
	return (
		// `throw` and `return` are quoted,
		// as they're invalid property names in ES3.
		(g = { next: verb(0), "throw": verb(1), "return": verb(2) }),
		typeof Symbol === "function" &&
			(g[Symbol.iterator] = function() {
				return this;
			}),
		g
	);
	function verb(n) {
		return function(v) {
			return step([n, v]);
		};
	}
}
```

**Comment by j-f1** [comment]
@ExE-Boss I‘d recommend using [`prettier-eslint`](https://github.com/prettier/prettier-eslint-cli) to apply these fixes after Prettier runs.

I don’t think we should add an option for this since ES3 is a super niche usecase, but [IE 11 doesn’t support trailing function commas](https://caniuse.com/#feat=mdn-javascript_functions_arrow_functions_trailing_comma), so the latest version of a major browser requires `trailingComma: es5` to run unmodified Prettierized code.
