### ISSUE TITLE
Force a blank line like refmt with /** */ comment

### ISSUE THREAD

**Issue by vramana** [prettier/prettier#7]
I have observed that this made me document code more often.

**Comment by jlongster** [comment]
Can you expand on this more? I don't remember exactly what this behavior is.

**Comment by vramana** [comment]
refmt would normally remove all the blank lines btween the let declarations. So, 

```rust
let a = 2;

let b = 3;
```
will become 

```rust
let a = 2;
let b = 3;
```
But if you use a comment /** */ between them i.e,

```rust
let a = 3;
/** My Comment */
let b = 4;
```
It inserts a new line above the comment.

```rust
let a = 3;

/** My Comment */
let b = 4;
```

**Comment by jlongster** [comment]
Ah interesting. Today I landed rules for newlines, and it keeps the original newlines. Meaning if you had 

```js
let a = 2;
let b = 3;
```

that's what it would output. However if you had:

```js
let a = 2;

let b = 3;
```

It would output that as well. Lastly, if you have multiple blank lines like:

```js
let a = 2;



let b = 3;
```

It will collapse them into a single newline.

I don't think we can be as opinionated as refmt because there are so many existing JS coding styles. I tried coming up with automatic ways to insert newlines, but it's pretty difficult.

I like the idea that it encourages you to document in order to group things up. I'm open to talking more about this, so I'll leave this open. @vjeux what do you think?

**Comment by vjeux** [comment]
I know about the refmt way of doing things but I still think that it's better to preserve lines inputted by the user. It seems super arbitrary to have to add a comment to make sure lines are displayed the way you want. Also, adding more comments is not a good thing in itself. I'd rather have comments on why things are done this way rather than commenting on how each line works.
