### ISSUE TITLE
inconsistent self-closing tags

### ISSUE THREAD

**Issue by x6ax6b** [prettier/prettier#7038]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeeBbADgGwIbwB8AOlAARmoAmAlgG4nkWUDCArgM4wQYBCbMblEKoAsgE8WPLNAQwyYfBw4BeYuCUd1ZAPQid7Lj36DojZpQBGAoSIlTss2As1qNeZdr2od108NILVD9bMUlpJ3lvXxszQModWgZSH0xcAjhGEAAaEAgsGBpoDmRQPAAncogAdwAFCoQSlDw6CBoqHJBLcrwwAGs4GABlLF6aKABzZBhytjhcgAsYDBwAdQWaeA5RsDghxs36TfFkcGVO8Y44cphanomMPGQAMzwcK9yAKw4AD14e-qDIZ4DBwAAy4zgLzeHxA3x+Q3GExwcAAimwIPBoe95iBRuUruVTnQ5p0sOVxjBVu0YAtkAAOAAMuXJECuqx6WFO5LghLoUNyAEcMfA7vkmiAPABaKBwOBUeWdcpwYU0ZV3PAPJ5IV443JXDA0aazXEcJEo9GYqE6mG4mB4SzUqi05AAJlyMzwNBwSIcj1OUFknU4cAAKg6mrrYSS4ABJKAK2BDMAUgoAQQTQxg4hR2KuAF980A)
```sh
--parser vue
```

**Input:**
```vue
<template>
  <div>
    <CustomButton><MyComponent class="class" /></CustomButton>
    <button><MyComponent class="class" /></button>
    <button><MyComponent /></button>
  </div>
</template>

```

**Output:**
```vue
<template>
  <div>
    <CustomButton><MyComponent class="class"/></CustomButton>
    <button><MyComponent class="class" /></button>
    <button><MyComponent /></button>
  </div>
</template>

```

**Expected behavior:**

><CustomButton><MyComponent class="class"` `/></CustomButton>

Hi,
My guess is that the MyComponent self-closing tags inside button components should all produce the same result.

**Comment by fisker** [comment]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAzgBwIZQHwA6UABMagCYCWAbnqUaWZVJgK4zHYwwBOA9IRJk+VWkVR8suQeKn4MOeczYcuMPBLkbJivCAA0ICJhiVo6ZKGw8eEAO4AFawgsps1CJXIGQAIx7YYADWcDAAyjhgzADmyLyscIYAFjAAtgA2AOpJlPBSYHBhLrk0uQCeyODoFobM6HA8MA4B0anYyABm2On1hgBW6AAeAEIBwaFh2KlwADLMcJ3dvSADg2Ex6XAAiqwQ8Is9iSA4PPU8lSkZPpg8zDCZXjBJyAAcAAyGNxD1mQGYlTc4GdqAtDABHXbwZrGVwgbDoAC0UDgcHIqJ8PDgEMomOa2Fa7SQXUOhnqqUocR4CVJG22kIWRKWRxg2F8D3IT2QACZDLxsJR0jEAMIQVJtSpQaCgkCseoAFVZrmJy2oCQAklA0bAwmBbiYAIKasIwMqbA71AC+FqAA)
```sh
--parser html
```

**Input:**
```html
<span>
  <div>  
   <input attr/>
  </div>
</span>

<span><span><input att></span></span>
```

**Output:**
```html
<span>
  <div>
    <input attr />
  </div>
</span>

<span
  ><span><input att/></span
></span>

```

I did little research on this, somehow this is by design.
I can fix it, but I don't know why this is different at first place.
