### ISSUE TITLE
Ternary formatting is a bit unexpected

### ISSUE THREAD

**Issue by benjaminapetersen** [prettier/prettier#716]
I'm sure this is intentional, but wanted to point it out/ask.  My source:

```JavaScript
let foo = (bar === 0) ?
               baz :
               qux;
```

Which gets reformatted to:
```JavaScript
let foo = (bar === 0)
                ? baz
                : qux;
```
This is a little strange to me, as it seems like the first stanza is the "question" and should keep the `?` token.  The second and third stanzas are "truthy" answer and "falsy" answer.

```JavaScript
let foo = question ?
                truthyAnswer :
                falsyAnswer;
```
I can see where the current formatting is "prettier" in that the `?` and `:` stack neatly, just wondering if it throws the implication of the syntax a bit.

Thx!

**Comment by kjbekkelund** [comment]
In my experience having `?` and `:` on the new line improves the readability (as it's easier to immediately see them while scanning code). This becomes more obvious when you have something more than a single word, e.g. an example with a `require`:

```js
const { configureStore } = process.env.NODE_ENV === `production` ?
  require(`./configureProdStore`) : // eslint-disable-line import/no-commonjs
  require(`./configureDevStore`); // eslint-disable-line import/no-commonjs

// compared to

const { configureStore } = process.env.NODE_ENV === `production`
  ? require(`./configureProdStore`) // eslint-disable-line import/no-commonjs
  : require(`./configureDevStore`); // eslint-disable-line import/no-commonjs
```

(In the former it kinda looks like it's requiring _both_ until I read the code more closely, while in the latter it's immediately obvious while scanning the code that it's a ternary)

Or with jsx:

```js
<button
  onClick={e => this.toggleAdvanced(e)}
  className="advancedOptions-button"
>
  {this.state.showAdvanced ?
    <FormattedMessage
      id="allocator-vacate-index.hide-advanced-options"
      defaultMessage="Hide advanced options"
    /> :
    <FormattedMessage
      id="allocator-vacate-index.show-advanced-options"
      defaultMessage="Show advanced options"
    />}
</button>

// compared to

<button
  onClick={e => this.toggleAdvanced(e)}
  className="advancedOptions-button"
>
  {this.state.showAdvanced
    ? <FormattedMessage
        id="allocator-vacate-index.hide-advanced-options"
        defaultMessage="Hide advanced options"
      />
    : <FormattedMessage
        id="allocator-vacate-index.show-advanced-options"
        defaultMessage="Show advanced options"
      />}
</button>
```

I feel the latter is more obvious when quickly scanning through the code (though, I'm biased as that's the way I've written them for a long time, so might just be because of experience that I scan them quicker).

**Comment by viankakrisna** [comment]
yup, `?` in the next line makes think that the current line needs to be checked and will be replaced with the next line's value if it truthy. reading a long line only to see that it has `?` in the end is slower while scanning.

**Comment by mvolkmann** [comment]
Here's an example of a ternary in my code:
````
      const prop =
        field === 'DurationOfLast1_2Signal' ? 'durationLast12' :
        field === 'DurationOfLast1_4Signal' ? 'durationLast14' :
        field === 'LeakFault' ? 'leakFault' :
        null;
````
And here is how Prettier reformats it:
````
      const prop = field === 'DurationOfLast1_2Signal'
        ? 'durationLast12'
        : field === 'DurationOfLast1_4Signal'
            ? 'durationLast14'
            : field === 'LeakFault'
                ? 'leakFault'
                : null;
````

I know it's subjective, but I think my code is more readable. In my real code there are 9 ternaries, so the Prettier indentation gets pretty extreme.

The default indentation is 2 spaces, so why does it switch to 4-space indentation after the first ternary?

**Comment by dburles** [comment]
@mvolkmann I know it's maybe just an example but you would be way better off just doing something like:

```js
const fieldMap = {
  DurationOfLast1_2Signal: 'durationLast12',
  DurationOfLast1_4Signal: 'durationLast14',
  LeakFault: 'leakFault',
};

const prop = fieldMap[field];
```

that use of ternary's is super confusing

**Comment by mvolkmann** [comment]
Maybe it's micro-optimizing, but I think about the cost of both creating the map object and the cost of the hashmap operation to lookup the value.

I know it gets down to personal preference, but I don't think my use of ternaries is confusing at all and I often see that style used.

**Comment by dburles** [comment]
Definitely micro-optimising 😛  I'd even prefer an if/else block instead of nested ternary, but it is just a style thing for me. Eslint has a rule on nested ternary http://eslint.org/docs/rules/no-nested-ternary.

**Comment by jlongster** [comment]
I don't think we're going to add a new config option for this, and I think it is better to use different code for multiple ternaries. I actually find the prettier code slightly clearer because the other format is kind of abusing ternaries. If you're really after performance:

```js
let prop = null;
switch(field) {
  case 'DurationOfLast1_2Signal':
    prop = 'durationLast12';
    break;
  case 'DurationOfLast1_4Signal':
    prop = 'durationLast14';
    break;
  case 'LeakFault':
    prop = 'leakFault';
    break;
}
```

In many cases it's probably best to abstract this out into a function, then you could just do:

```js
function lookupField(field) {
  switch(field) {
    case 'DurationOfLast1_2Signal':
      return 'durationLast12';
    case 'DurationOfLast1_4Signal':
      return 'durationLast14';
    case 'LeakFault':
      return 'leakFault';
  }
}
```

**Comment by mvolkmann** [comment]
Sad to hear this. I know everyone has their hot button issues. Conciseness of code is very important to me. For me this is likely a deal breaker and means I will not be using Prettier.

---
R. Mark Volkmann
Object Computing, Inc.

**Comment by mvolkmann** [comment]
Why do some people feel that this is "abusing" ternaries?
````
const value =
  condition1 ? value1 :
  condition2 ? value2 :
  condition3 ? value3 :
  value4;
````
I realize opinions vary, but this seems very clear to me.

**Comment by jlongster** [comment]
We need to make a call on how to format things and we can't cater to every style. If we tried to change ternaries it impacts a lot of other places where it should not break that way and is less readable. It's all tradeoffs. I'm sorry it doesn't fit your style, but with this kind of formatter, there are going to be things that's aren't person for each person.

It's "abusing" it because the syntactic feel does not match how it's actually parsed at all, and what you are really looking for will be solved with `do` expressions in JS, coming soon. Then you could do `do{ switch(val) { ... }}` and get something similar

**Comment by jlongster** [comment]
Closing this as we need to make a call. Sorry for those who disagree, we're not going to be able to please everyone :(

**Comment by vramana** [comment]
@jlongster I think you totally need a saved reply for these cases where you reject. It's wasting your precious time.

**Comment by rhengles** [comment]
@mvolkmann I'm willing to support such an option [in my fork](https://github.com/arijs/prettier-with-tabs), if you or someone else can submit a PR 😀

**Comment by danllach** [comment]
I use this format to improve ternary readability:

`export const VersionMatch = (v1, v2) => {
    return parseInt(v1.major) == parseInt(v2.major) || v2.major == '*' ?
      parseInt(v1.minor) == parseInt(v2.minor) || v2.minor == '*' ?
        parseInt(v1.patch) == parseInt(v2.patch) || v2.patch == '*' ?
          parseInt(v1.build) == parseInt(v2.build) || v2.build == '*' ?
          true
          :
          false
        :
        false
      :
      false
    :
    false
}`

How I can get this format on prettier?
