### ISSUE TITLE
Prettier inserts a semicolon before "in" class property

### ISSUE THREAD

**Issue by queicherius** [prettier/prettier#7168]
- Tried searching for this issue, but since the keyword is "in" it's hard to find anything.

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEcAeAHCAnGACMAGwEMBnUvASVgDEBLQ+bPYAHSjzzgEcBXYwqSR4ovALYAjOMwA+I3oULtOdKMNGTpAbQC6eOaMXsAvuxAAaEBAww60UslDFs2CAHcACs4QOUxAG4QdAAmFiAS2MRgANZwMADKGFGqAObIMNi8cJYAFjBihADqOXTwpElgcPE+pXT+pQCeyODkYaqk0jAekSlixMgAZgIdlgBWpGgAQpExcfHEYnAAMqpwg8PZIONo8amEcACKvBDw64KbSdgd2M0wDRhwpGDYdDZhGC+whSEwOcgAHAAGSwfCAdQqRDDND6PaT+NaWPgnODday+EBkAC0UDgcGCeLC2B4vDoRO6xF6-SQQ3Olg6YjoZxGIFIe0Ox1O1I2lhgxAk32Cv2QACYeZEGKkAMIQMR9ZpQaAIkC8DoAFT5vhpzP8WWo+Ng8WerxgAEEoMF4nd9ky4MZjEA)
```sh
--parser typescript
--no-semi
```

**Input:**
```tsx
export class IntFilter {
  equals: number | null
  in: number[] | null
}

```

**Output:**
```tsx
export class IntFilter {
  equals: number | null;
  in: number[] | null
}

```

**Expected behavior:**

```tsx
export class IntFilter {
  equals: number | null
  in: number[] | null
}

```

**Comment by thorn0** [comment]
Please see https://prettier.io/docs/en/rationale.html#semicolons

Imagine there is no semicolon and you added another property:
```ts
export class IntFilter {
  equals: number | null
  x = y
  in: number[] | null
}
```

This is a syntax error because it's parsed as `x = y in: number[]...`. Prettier prevents this by adding the semicolon making the line independent from the preceding line.

See also https://tc39.es/ecma262/#sec-interesting-cases-of-automatic-semicolon-insertion
