### ISSUE TITLE
Move to prettier org

### ISSUE THREAD

**Issue by jlongster** [prettier/prettier#725]
I made the prettier organization this morning and we intend to move this project there: https://github.com/prettier

We will hopefully move other tooling for prettier in the organization and make it easier to maintain and provide an official list of projects, as well as make it easier to manage contributors.

**Comment by vjeux** [comment]
Let's do it!

**Comment by rtsao** [comment]
cc @not-an-aardvark
https://github.com/not-an-aardvark/eslint-plugin-prettier
cc @lydell
https://github.com/lydell/eslint-config-prettier

**Comment by lydell** [comment]
I'd happily move eslint-config-prettier to the prettier org.

**Comment by jlongster** [comment]
Cool! I will move it in the next hour or two. :)

**Comment by tibdex** [comment]
Hi, people are starting to want to customize their `ESLint` config in order to disable the rules handled by `prettier`. See these tweets https://twitter.com/kylemathews/status/836617252543705088 (by @KyleAMathews) and https://twitter.com/kpuputti/status/836549354290831361 following one by @gaearon.

This is exactly what https://github.com/prettier/eslint-config-prettier offers to do in a clean way. Sadly, not everybody knows about this project and I believe they are missing out on something that would save them a lot of time.

There is already a reference to `eslint-config-prettier` in `prettier`'s readme but apparently people don't read that far.

So IMO, moving `eslint-config-prettier` to `prettier` organization would allow more people to stumble into it. Maybe rearranging `prettier`'s section to mention `eslint-config-prettier` and `eslint-plugin-prettier` earlier would also improve things.
