### ISSUE TITLE
Calling of function on multiple lines with 1.19

### ISSUE THREAD

**Issue by daveisfera** [prettier/prettier#7327]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwGEItoECBffAMxzPwHIc4BDMGJgbgB0p8+fmAA2bAM7j8AFTjiCcAB7woAEymlyUSoX6DBAV0yq28AAoNMACj367mSwBpbdwURhscAczgwkhfAA3NhEDOHwaKmcBfQBKAJdXEV98bWUANRCw-ABefABZUwALADpaEQhcKwBqYNC4WL4Y13xUWnwrNJhM+vwAHnwARnjgRJbBLp7svMGm8Yix-Rgi1HES8V8AZQ94KyIAbQcITABdf0ms8KiO+JyAPnxl1ZKjzDXoYiK2KB8rJ7X5KYGo1ElREokYBAvF5khZjlZXiNFoJ-ustjs4FZ8A44IFtkDcg89vhDpYzvgAIQ4vEY0nHE4RWKOG6Ex4rNavd5QT7fX6owHwWIg5oRfT8GggRwgY4wVDQcTIUCeBgAdzMngQCpQbECEFQqklIAARjgOABrLaYDioH7IGA4MJSoowdAiADqK3g4itYDgm01qFlgUDAE9kOBJIabRs8BY2F50GxkLQQhspQArcSKABCprAFpgmzY6DgABkbXBk6m4Bms5sbTC4ABFAwQeBVkRpkBWnAx8NGthGuAiQ1HDZu02YcM4mOBStSgCOrfMli1IAkAFptHBVDvDawl6hWHGE0mkCnOzWQBt0Kg7Q6r+IG8kW23K+fq1KPEa3frlsgABYv1NVARAbTRE3DKAKENAwNmkQctQvLtAjCABJNRKE2MAcFQTAYAAQTUbYQ2SDsuwcG0YF-VR-yQQZBgAVioKggA)
```sh
--parser babel
--print-width 115
--tab-width 4
```

**Input:**
```jsx
import { Component } from 'react';
  
class Test extends Component {
    updateProp(
        prop,
        { target: { value } },
    ) { 
        let nextValue = Math.floor(+value);
        if (nextValue < 1) {
            nextValue = 1;
        }
        this.setState({ [prop]: nextValue }, () => this.props.onChange(this.state));
    }
    
    toggleProp(prop) {
        this.setState( prevState => ({ [prop]: !prevState[prop] }), () => this.props.onChange(this.state));
    }   
} 
```

**Output:**
```jsx
import { Component } from "react";

class Test extends Component {
    updateProp(prop, { target: { value } }) {
        let nextValue = Math.floor(+value);
        if (nextValue < 1) {
            nextValue = 1;
        }
        this.setState({ [prop]: nextValue }, () => this.props.onChange(this.state));
    }

    toggleProp(prop) {
        this.setState(
            prevState => ({ [prop]: !prevState[prop] }),
            () => this.props.onChange(this.state)
        );
    }
}

```

**Expected behavior:**
The change to `updateProp()` [is expected](https://prettier.io/blog/2019/11/09/1.19.0.html#object-destructuring-in-method-parameters-always-broke-into-multiple-lines-6646-by-ericsakmar), but I didn't expect the calls to `this.setState()` to wrap to multiple lines. Is there a change that I didn't see in the release notes or is this a bug?

**Comment by thorn0** [comment]
Not a bug. You seem to have missed [this part](https://prettier.io/blog/2019/11/09/1.19.0.html#use-function-literals-in-arguments-to-detect-function-composition-6033-by-brainkim) (Use function literals in arguments to detect function composition). Feel free to reopen this issue if needed.

**Comment by daveisfera** [comment]
Thanks for the info!

**Comment by dave-nm** [comment]
Actually, after reading through the linked to document again, I don't understand why `this.setState()` is on multiple lines (i.e. there's no chaining going on) and the example is fairly similar to the code snippet I showed but it is multiple lines instead of a single line like the example

**Comment by thorn0** [comment]
It's not about chaining. If a call has more than one argument and the arguments include a function literal or a nested call with function literal arguments, then each argument gets its own line.

**Comment by dave-nm** [comment]
At least to me, `uses the presence of function literals to detect function composition` implies chaining of functions. I guess that passing a function as an argument is "composition", but this means that a lot of uses of `lodash` will be broken onto multiple lines even if they're simple calls like `some(value => matches(value, matchValue), values)`

**Comment by thorn0** [comment]
I stand corrected. The current rule is: if a call has more than one argument and there **at least two** function literals or nested calls with function literal arguments among the arguments, then each argument gets its own line.

**Comment by dave-nm** [comment]
Ok, thanks for the clarification. For whatever my two cents are worth, this change still feels odd in where it decides force multiple lines. It's nice that's it's "based on the code" instead of a set of hard coded names, but it still does things that I wouldn't expect. I understand that this sort of thing will never be "perfect", but here are [some examples](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAgDNUAbeHInCdfAchIgBMBDAZwAsB6Qzb082gG4AOlAzY8+AFYRUUStToMWHbrxlyho8bgLpmmBTXpM2XHp32YtUURqgAKWvgC0dADT4rD1vgC8AHxEuPowPgCUnnKYAK4wAHSsmCSoYbQutOFZIrZQ3gBuzCQxcP5BwPgA7riMSPiFxaUAvp7EZHA4Dg0l-n5+dJXMsHCMtJ5JKWkZUVCxMFnhgiDuIBCYMKjQrMigzDhUlQAKewjbKMz5sozLIABGOMxgANZwMADKmI9yAObIMDglFbsGDoEgAdXYqTgSUecDep1SqHyqQAnshwKxtis5KwOjBDg9vvpkIQiriVlJWAAPABCD2erzezHQcAAMnI4CSyXAKdS3j8SHAAIoxCDwLkkckgT44XE4dG3Zi3OAkG6YHByGBg1CMGDsZAADgADCt1RBcWCHph0eroR18pyVgBHUXwAlrM4gNguKBwEYjG44OAu1BBgnMInMCVS3HoVB-AE8kCsAXC12cpCkyVJmBK7W6-VIABMK3+zFIPwAwtRiSgoNBHSAYriACpKs5ZqX5EoASSgjAQ7zAGvWAEF+28YCjBdG4E0mkA)

**Comment by thorn0** [comment]
As for `join`, I stand corrected again! So the discussed rule is: if a call has more than one argument and there are at least two function literals **or at least one** nested call with function literal arguments among the arguments, then each argument gets its own line.

As for `map`, you forgot to put parens around its body: `value => { word: value }` vs `value => ({ word: value })`, so Prettier thinks `word: value` is a labelled statement and uses its another heuristic/pattern/rule, namely "a `setTimeout`-like call", to format this call.

**Comment by dave-nm** [comment]
🤦‍♂ you're right about the `map()` one, but if you change it to `value => { return { word: value }; }` then it's just a different syntax for the same thing and you get the same weird behavior of multi-line with a single line on the last line

**Comment by thorn0** [comment]
If you ever get an idea on how to improve this heuristic, welcome to https://github.com/prettier/prettier/issues/6921.

**Comment by thorn0** [comment]
> the same weird behavior of multi-line with a single line on the last line

As I already said, it's a different heuristic in play here. "`setTimeout`-like calls". Unlike the one we discussed before ("function composition"), this one seems to have more room for improvement.

**Comment by dave-nm** [comment]
ok, thanks for the info and I'll keep my eye on those potential improvements and throw my 2 cents in, if I come up with any good ideas

**Comment by brainkim** [comment]
@dave-nm Yo. Just seeing this thread. I’m the official punching bag for complaining about calls with function changes since 1.19 (because I’m the one who championed/implemented it). Please do send more examples of behavior you think is sub-optimal/unexpected. I’ve pledged my time to fixing them as they come up. The examples you posted in the playground do seem a little weird, but the first one I think is fine, given that it seems like a function composition API, and the second one is likely a bug where the developer intended to return an object literal but forgot to wrap the brackets in parentheses.

I think there might be some value to treating function literals with blocks differently than functions with concise expressions `(() => {})` vs `(() => whatever)`, and I’m eager to experiment with the new groundwork laid by https://github.com/prettier/prettier/pull/6685. So follow #6921 for updates I guess.
