### ISSUE TITLE
useless brackets when format the string under the template literal

### ISSUE THREAD

**Issue by tjx666** [prettier/prettier#7346]
input:

```markdown
​```javascript
`模板字符串可以直接插入单引号'和双引号"`;
'单引号字符串可以插入反引号`';
​```
```

output:

```markdown
​```javascript
`模板字符串可以直接插入单引号'和双引号"`;
('单引号字符串可以插入反引号`');
​```
```

expect:  no brackets wrap the string：

```markdown
'单引号字符串可以插入反引号`'
```

**Comment by thorn0** [comment]
Reproducible on the Playground:

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEADAZhCqDcAdKAcgCMBDAJ0JxABoQIAHGAS2gGdlQLyIB3ABQoIOKUgDcIzACa0QxcqTABrODADKDRcygBzZDHIBXOHQAWMALYAbAOqnm8NprBw1wh8zEOAnsnBsOOm02OHIYfgUdC1JkdFIrELoAKzYADwAhBWVVNVILOAAZbThY+MSQFNS1bR0rOABFQwh4UoSTEE1yEPI-MmI4K1kGcm0YG2kYU2QADgAGOmGIEJsFBj9huG6xEroARyb4CMYREFI2AFooODgpG9lyOH3mB4jSKJikOLa6EItmfSM7TYNTqjWaJU+ZXaMFIxHGUkmyAATHQDKRmFYagBhCAWaJ+KDQHYgQwhAAqsJEX3KYmMAEkoLdYGowCMmABBRlqGDeOqtEIAXwFQA)
```sh
--parser babel
```

**Input:**
```jsx
`foo`;
'bar';
```

**Output:**
```jsx
`foo`;
("bar");

```

**Comment by armano2** [comment]
this seems to be not a case when order is reversed
```
'bar';
`foo`;
```

this issue is also not present when typescript parser is used instead.

**Comment by bakkot** [comment]
This is intentional. Prettier wraps any string literal which is in statement position in parentheses because otherwise such strings would get interpreted as directives if they occurred at the top of a function or program, which can change the behavior of the program.

To illustrate:
```js
function f() {
  'use strict';
  return this === void 0;
}

function g() {
  ('use strict');
  return this === void 0;
}

f(); // true
g(); // false
```

Now, it is not technically necessary to do this for strings which are not on the first line of a function or program. But doing so anyway is more consistent, and can highlight bugs. See for example [this thread on twitter](https://twitter.com/dan_abramov/status/874601179334017024).

**Comment by tjx666** [comment]
@bakkot wraped with bracket is so ugly...

**Comment by tjx666** [comment]
I think the responsibility of prettier should only format the code, not the code logic. The logic shoult be lint by tools like eslint.

**Comment by bakkot** [comment]
The reason it wraps strings in parentheses is because it is sometimes necessary to do so to preserve the behavior of the program (and the AST), as in my example, which is one of the most important goals for prettier. Since it is sometimes necessary, for consistency it always does it, consistency being another important goal. The fact that it sometimes highlights bugs is just a bonus.
