### ISSUE TITLE
Prettier ignores "--print-width" when function called "test"

### ISSUE THREAD

**Issue by kohver** [prettier/prettier#7386]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUAdKACPAcgBkIAnOAWzwEkAHNAV2oEs080XK6AbATzwATZpQHwAHjDwQAZnhgALOHjpkWsdQHM8AQyiD5fOnDRwYMLXnXCMZPgDpCAGlwFMASjwBeAHx5gAL4uUO4A3CBOIBB0FtBoyKA6ZGQQAO4ACkkI8Sg6AG4QLIIRIABGZDpgANZmAMp0lVrIMGSMcJEKMJQ8AOoKLOgNYHC12QMseQN8yOBo8ZHqpmQw6RWalDrIMjo8ppEAVmjiAEIV1XU6lHDE6nBbO3sgh+K1WjxwAIqMEPD3u+0gBpkJYzUo6UpwHglVTqGA9IqKZAADgADJFVBBTD0KnQZqoTHAyHk7pEAI7feCraI5EA6NAAWigcDgghZJQo5JYFFWOnWmyQ23+kVMlBYzVaAM4UE07y+PzuAoeAJg4PhgkRSAATJEWjoWDwtABhCCUDYzKDQEkgRimAAq4JygseeTaNH0CBgtTAahiAEF9LUYHx3n9TAEAkA).

**Input:**
```js
test(
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  () => {},
);

test(
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  function() {},
);
```

**Output:**
```js
test("Lorem Ipsum is simply dummy text of the printing and typesetting industry.", () => {});

test("Lorem Ipsum is simply dummy text of the printing and typesetting industry.", function() {});
```

**Expected behavior:**

```js
test(
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  () => {}
);

test(
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  function() {}
);
```

It's weird, since if the function not called `test`, prettier works good:

```js
tttt(
  'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  () => {},
);
```

```js
tttt(
  "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  () => {}
);
```

**Comment by evilebottnawi** [comment]
It is expected, because `test` is the special name in many testing tools, why do you use an empty function for `test`, usually it is contains code and looks better for [readability](https://prettier.io/playground/#N4Igxg9gdgLgprEAuE8DOMAUAdKACPAcgBkIAnOAWzwEkAHNAV2oEs080XK6AbATzwATZpQHwAHjDwQAZnhgALOHjpkWsdQHM8AQyiD5fOnDRwYMLXnXCMZPgDpCAGlwFMASjwBeAHx5grgR4cOLGYFgAjO72MBAAQnCYUYEAvi5Q7gDcIE4gEHQW0GjIoDpkZBAA7gAKZQjFKDoAbhAsgjkgAEZkOmAA1mYAynS9WsgwZIxwuQowlDwA6gos6CNgcIP1KyxNK3zI4GjFueqmZDDVPZqUOsgyOjymuQBWaOJxPf1DOpRwxOpwO4PJ4gV7iQZaHhwACKjAg8CBj2mIBGZDOB06Ok6cB4HVU6hgCzaimQAA4AAy5VQQUwLHp0A6qExwMhNQG5ACOcPgl3yDRAOjQAFooHA4IJxR0KFyWBRLjprrckPckblTJQWONJsjOFBNFDYfDAcrgciYFiiYISUgAEy5CY6Fg8LQAYQglBuByg0HZIEYpgAKliGiqQU0pjR9AgYIMwGoCgBBfSDGB8KGI0wpFJAA)

**Comment by kohver** [comment]
Thank you! But it works really weird to be honest.

For example, when I get this output:

```js
test("Lorem Ipsum is simply dummy text of the printing and typesetting indu", () => {
  expect(1).toBe(1);
});
```

(note the string is slightly shorter than before).

I try to wrap it so:

```js
test("Lorem Ipsum is simply dummy text " +
  "of the printing and typesetting indu", () => {
  expect(1).toBe(1);
});
```

and then I get this:

```js
test(
  "Lorem Ipsum is simply dummy text " + "of the printing and typesetting indu",
  () => {
    expect(1).toBe(1);
  }
);
```
Then I'm trying to remove the `" + "` and get... The same as in the beginning.

Anyway, I get your point, closing the issue.
