### ISSUE TITLE
Reopening: Semicolon before arrow IIFE #2800

### ISSUE THREAD

**Issue by Larkenx** [prettier/prettier#7423]
Just wanted to re-open the issue for semicolons before arrow IIFE. I can't find any rule resolutions to removing the inserted colon for the following example
```javascript
;(async () => {})()
```

**Comment by bakkot** [comment]
Did you see the [comment in that issue](https://github.com/prettier/prettier/issues/2800#issuecomment-329139240)? Did you have a question it doesn't answer?

**Comment by Larkenx** [comment]
Sure - more specifically, I'd like to see the semicolon removed when you have your `semi` setting set to true in the `.prettierc`. I'd imagine that would include expanding the AST to properly look ahead and see if the anonymous function is called, and if so, don't add the semicolon. My resolution is to enable semicolons and it works ok, but I really prefer not to use semicolons in my code

**Comment by bakkot** [comment]
The comment in that issue explains why prettier with `--no-semi` inserts semicolons before any line which starts with `(`: you can't avoid all semicolons (for example, that one would be necessary if the preceding line were `let x = y[0]`), and it's more consistent to do so based on the line itself rather than looking at the preceding line. (This is also covered in [the docs](https://prettier.io/docs/en/rationale.html#semicolons).) This [matches](https://standardjs.com/rules.html#semicolons) other common "semicolon-free" style guides.

**Comment by Larkenx** [comment]
I see - thanks for walking through it and explaining it, that makes sense!
