### ISSUE TITLE
nullish coalescing support issue

### ISSUE THREAD

**Issue by ImAbhishekTomar** [prettier/prettier#7428]
![0032978B-59A2-46FF-9C7A-4C2CBC5D52CA](https://user-images.githubusercontent.com/6933841/73102919-e57a8b80-3f18-11ea-9f18-5f5356b0d089.jpeg)

Editor : VS CODE

**Comment by kachkaev** [comment]
👋 @ImAbhishekTomar please use a corresponding [issue template](https://github.com/prettier/prettier/tree/master/.github/ISSUE_TEMPLATE) when reporting bugs.

---

My understanding is that you're using an old version of Prettier. Try upgrading to 1.19+, which [supports TypeScript 3.7 features](https://prettier.io/blog/2019/11/09/1.19.0.html#support-for-typescript-37-6657-by-cryrivers).

**Comment by ImAbhishekTomar** [comment]
package update but issue still same.

"prettier": "^1.19.1",
"typescript": "^3.8.0-beta"
"typescript-eslint": "^0.0.1-alpha.0"

**Comment by sosukesuzuki** [comment]
@ImAbhishekTomar If you are using VSCode plugin for Prettier, please make sure you are running the latest version of the plugin.

**Comment by ImAbhishekTomar** [comment]
yes i have using 3.20.0, but issue is still same.

**Comment by armano2** [comment]
> "prettier": "^1.19.1",
> "typescript": "^3.8.0-beta"
> "typescript-eslint": "^0.0.1-alpha.0"

This issue seems to be with vscode jest plugin, can you try:

1. run prettier from console, eg. `prettier ./**/*.{tsx}`, it should not fail
3. check if there is no updates to vscode plugin
2. check if vscode plugin is using locally installed prettier
https://github.com/prettier/prettier-vscode/blob/master/README.md#prettierprettierpath
![image](https://user-images.githubusercontent.com/625469/73889213-75043080-486f-11ea-8cf8-ff51b23b2c78.png)

------------------

as for `typescript-eslint` did you mean `@typescript-eslint/typescript-estree`?

------------------

> note: typescript@3.8-beta is not officially supported as https://github.com/typescript-eslint/typescript-eslint/pull/1465 is not yet merged (this is beta)

**Comment by acherkashin** [comment]
@armano2 It seems, you are right, it is problem VS Code Extension.

I have chosen package manager (previously npm was chosen)

![image](https://user-images.githubusercontent.com/9947582/74935904-2d96ac00-53fa-11ea-9858-480ecd1d87b4.png)

and set path to `.prettierrc`

![image](https://user-images.githubusercontent.com/9947582/74936048-79e1ec00-53fa-11ea-8f8e-3482f0754582.png)

Now everything works

**Comment by evilebottnawi** [comment]
Yes, the issue not related to prettier, please open issue in VS Code extension
