### ISSUE TITLE
prettier <file> without --write option does not ignore what's in .prettierignore

### ISSUE THREAD

**Issue by ORESoftware** [prettier/prettier#7473]
When I run this:

```
prettier --config .prettierrc.json '**'
```

it echoes a lot of stuff to stdout, for files that are ignored by .prettierignore.
It should ignore what's in .prettierignore when the --write option is not used.

**Comment by cdaringe** [comment]
confirmed.  was quite surprised by this.

**Comment by cdaringe** [comment]
in my case, i have nested `node_modules` in a monorepo. i'm running:

`npx prettier './*.{js,ts}' './packages/**/*.{js,ts}'`

and it skips my ignore. it's as though these globs are taking precedence _over_ the requested ignore files

**Comment by thorn0** [comment]
Prettier doesn't reformat those files. It just outputs them to stdout as is.

@cdaringe You need the `--check` option.

**Comment by lydell** [comment]
I’m curious – what do you use these commands for? What do you do with the stdout?

**Comment by cdaringe** [comment]
`--check` worked.  hmm. ya i suppose i expected more `git`-like behavior.  git will always respect your gitignore unless you pass `-f`, as opposed to _disregarding your ignore_ if you provide an filename.  the problem is that my arg is a _glob_, not a specific filename, and thus i still want the .prettierignore to take. i can see it being reasonable to ignore my `.prettierignore` if one passes an arg--it has the feel of a pure function, a la `npx doWork onThisFIle`.  but, then having it _not_ honor your ignore just by adding `--write` or `--check` is inconsistent.

how do folks feel about adopting the git model? that is always respect the `.prettierignore`, unless some other flag unlocks those ignored files?

**Comment by thorn0** [comment]
Not having `--write` or `--check`  means outputting the result to stdout. If a file formatter, having been asked to format a file and to return the result to stdout, returns nothing, the consumer (e.g. an editor integration that uses the formatter via its CLI) has to suppose that the formatting result is the empty string. So, imagine: the user invokes the "Format" command in their editor, and the editor suddenly deletes the whole content of the file, which was supposed to be ignored by that formatter! Would you call this behavior respecting `.prettierignore`? That's why, if a file is ignored, Prettier outputs it as is instead of printing nothing. It doesn't disrespect `.prettierignore` at all, as you can see. That's just the way it respects it.

Now, what does this all have to do with globs, you ask? That's a good question. It's difficult for me to think of a use case where multiple files matched by a glob would need to be formatted and output to stdout. I wonder whether anybody actually uses Prettier to format multiple files at once and print the concatenated result to stdout. It seems like you, @ORESoftware and @cdaringe, actually do this though. I second @lydell's curiosity, what for?
