### ISSUE TITLE
Panic Nova (formerly Coda) Support?

### ISSUE THREAD

**Issue by ChrisChiera** [prettier/prettier#7531]
Panic's Nova has been under development and they have been accepting plugins over the past couple of months. Panic's Nova will be replacing Coda and more akin to Atom in functionality than the past Codas. Is an extension under development for bringing Prettier to Nova currently? As their is currently no formatter for the Nova betas so the first will presumably be the one most people go towards in beta and once it is publicly released.

**Comment by kachkaev** [comment]
Hi @ChrisChiera 👋

I guess this issue belongs to the the Nova / Coda community. They can look at existing editor integrations for inspiration: https://prettier.io/docs/en/editors.html

This repo is about the core tool, which works on its own or under the hood of any editor extension. Your issue is somewhat outside the scope of this github project.

**Comment by ChrisChiera** [comment]
Oh, on "https://prettier.io" it lists the editors your currently support and says "Got more"? and links to this Github account, so maybe that is just an error on the Prettify website. I can file an issue here to have that removed from the Prettier website.

**Comment by thorn0** [comment]
Actually, it says "Got more? Send a PR" and links to a specific file, from which the list of editor plugins on the main page is generated. So if someone makes a new editor integration, they can add information about it to the site.

**Comment by kachkaev** [comment]
Wondering if the issue can be closed as there is nothing to act on by the Prettier core team 🤔
