### ISSUE TITLE
Spaces are replaced by unintended symbols in JSX

### ISSUE THREAD

**Issue by ahuglajbclajep** [prettier/prettier#7594]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAzArlMMCW0AEqAFAA4BOEJAzgJT7AA6U++ZcM6ZzRTLLAPABMcANwB8vPiwAesufIWKlylQqT1ylKgDppAXwA0+AJ7rgm6tuN7JAgPTDxkmgG4mekAZCVc0KslAAQzIKAHcABWCEfxRAkQgcQU8QACMyQLAAa3YAZRIMnCgAc2QYMnQ4LwALGABbABsAdSqceCp8sDgc6NbRVuNkcCp-L0KqODIYcPSi2sDkVED68a8AKyppACF0rNzA2rgAGUK4BaWVkHXpHMKi+rgARXQIeDPlypB8snGyQZhjEhwKhgMg4EgwZLkQowRqJGBVZAADgADF5NONGukSINyECJiJTl4AI7PeDTLSDQJUAC0UDgcEEDOSbBJODY00Cs3mSEW7y841qOFK5Q+VFu9yeL1OPPOHxggRSsME8OQACYvGVAjh6rcAMIQWpzQZQaCEkDocYAFQVMV5FxEFQAklBGbAciCwTAAIIunL-e5vcZ6PRAA)
```sh
--parser typescript
```

**Input:**
```tsx
function f(props) {
  return (
    <div>
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: {props.x}, y: {props.y}
    </div>
  );
}
```

**Output:**
```tsx
function f(props) {
  return (
    <div>
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: {props.x}, y:{" "}
      {props.y}
    </div>
  );
}

```

**Expected behavior:**
```tsx
function f(props) {
  return (
    <div>
      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx: {props.x}, y: {props.y}
    </div>
  );
}
```

**Comment by hawkrives** [comment]
@ahuglajbclajep This happens because of a difference between the newline handling of JSX and HTML.

```html
<!-- html -->
<div>
    X
    Y
</div>
```

renders as `X Y`, with a space, while 

```jsx
/* JSX */
<div>
    X
    Y
</div>
```

renders as `XY`, with no space.

So, when Prettier needs to wrap a JSX tag to multiple lines, it needs to preserve a space in the text where you would expect one, or else your interface would suddenly lose spaces in the output.

And the way that you preserve spaces is to use a JSX literal, `{" "}`.

Does that make sense?

**Comment by thorn0** [comment]
Thanks, @hawkrives. Yes, this works as expected.
