### ISSUE TITLE
Failed to parse MDX

### ISSUE THREAD

**Issue by gsklee** [prettier/prettier#7658]
**Environments:**
- Prettier Version: 1.19.1
- Running Prettier via: `$ npx prettier --check "src/**/*.mdx"`
- Runtime: Node 13.6.0
- Operating System: macOS 10.14.6

**Steps to reproduce:**

I got this really basic Storybook MDX story:

```mdx
import { Meta, Preview, Story } from "@storybook/addon-docs/blocks";
import { boolean } from "@storybook/addon-knobs";

import Button from "./Button";

<Meta title="Component/Button" component={Button} />

# Button

Yeah.

## Variants

### Primary

<Preview>
  <Story name="basicA">
    <Button disabled={boolean("Disabled", false)}>Label</Button>
  </Story>
</Preview>
```

If I run `$ npx prettier --check "src/**/*.mdx"` I will get this:

```
Checking formatting...
src/component/Button/Button.stories.mdx[error] src/component/Button/Button.stories.mdx: SyntaxError: Unexpected closing tag "Button". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags (3:56)
[error]   1 | import { Meta, Preview, Story } from "@storybook/addon-docs/blocks";
[error]   2 | import { boolean } from "@storybook/addon-knobs";
[error] > 3 | 
[error]     | ^
[error]   4 | import Button from "./Button";
[error]   5 | 
[error]   6 | <Meta title="Component/Button" component={Button} />
All matched files use Prettier code style!
```

But if I remove the button's prop then the parse just works fine:

```mdx
import { Meta, Preview, Story } from "@storybook/addon-docs/blocks";
import { boolean } from "@storybook/addon-knobs";

import Button from "./Button";

<Meta title="Component/Button" component={Button} />

# Button

Yeah.

## Variants

### Primary

<Preview>
  <Story name="basicA">
    <Button>Label</Button>
  </Story>
</Preview>
```

```
Checking formatting...
All matched files use Prettier code style!
```

**Comment by sosukesuzuki** [comment]
Thank you for report. This problem was fixed by #6949, but not released yet. Please look the [result of playground on #6949](https://deploy-preview-6949--prettier.netlify.com/playground/#N4Igxg9gdgLgprEAuEBLAtgBwgJxgAmHwFk4YBDAGnwAUc4A3VOAd2oGUZcBPfAX3wAzHBHT4AOiAACAZy45uAIwgQA1gHpyAEy3QAtLrAz1igDYQwqmZIDc4qBmx5C+ZRFNxyUfkJFjJsvJKKhraulB6qlAQitYgdlD2jrgEAEIArjBc3sKiEiAAdOoZWdC29vYAPKQU+DCoMB4AvJIAwqLYUAgwxZnZkviQWNDdTcAl2QLqAHwVUADE+BNliVAAmp4AFgVz84sAauQ4qF4w1qt7i3QYR9xzlXSMzCyz3viVnDz4UOTocC0gRTkGSoMAAQUkr3w0Pey28WlQMnIZjgWjGbg8XgAFJIACKI5EeLSSaiCcimGRwACUfGmABlkXBTJVeqUoFD3upPgpXizHkxWNMQJQQBBMPVoDJkKAjiIWDQjggpShyAwIKgtMLAThyJYyOxMLrUFAAObIGA4dJwEWbGDoUwAdU2DTgMkNYDg7CVDVQTBg3GQ4BkUpFxspeDo5BN6HIyDJFOtIAAVjIAB6pHV6mDsX5wOnGuBx8mUkUp1PsY0mjwARXSEHgRYTIsNOHDgfQWlTWswx1gDo1ME2yAAHAAGZsiSkOnWYQM911wHAMQsigCOdfgdDFypAwL0XVRqK19HXqHokejsaQ8ZLIEp6FQ5stiZBpprG8L1+LiYoin7WkHZAACYRQtchUFMSt2nQGNA2iLotXSSkABVkWVG9EwYK0AEkoC0bp2DAY5xTBPDOG4DxG0pPg+CAA).
