### ISSUE TITLE
Redundant parens aren't removed in function because of JSDoc

### ISSUE THREAD

**Issue by thorn0** [prettier/prettier#7686]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgAIwJ4AOcmwmAvpuqgDpQBeAFAB6YC8AfCbZpgwGYQIASgYMARgEMATiIBMAagYBmIau6YpcGAFcpUXgEYhAblpkhIADQgIBGAEtoAZ2ShpUiAHcACtIQuUCQA3CHsAEysQMSkJMABrLQBlAlj7KABzZBgpbThrAAsYAFsAGwB1fPt4JxSwOET-KvsgqrxkcCcXazSnOCkYbxj0oolkPgkS3usAKycmACEY+KSJIrgAGTS4MYmpkFmmRLT0krgARW0IeB3JvJAUqV6pdskxOBLIgik0mDLwmHyyAAHAAGaxfCC9MoxAjtL5wJ5BbbWACOl3gg1sARAEicAFooHA4GFiZFNGj7JpBhJhqMkONbtZekV7FkcncnMdThcrtt6bs7jAJGI-mEAchZNZshJ7CVjgBhCBFEbtKDQZEgbS9AAqwoCDL2QVyAEkoCTYIkwN87ABBM2JfCnG69MhkIA)
```sh
--parser babel
```

**Input:**
```jsx
/* @type { } */
z(x => {
  (foo)((bar)(2+(3)))
  return (1);
})
```

**Output:**
```jsx
/* @type { } */
z(x => {
  (foo)((bar)(2 + (3)));
  return (1);
});

```

**Comment by sosukesuzuki** [comment]
@thorn0 Sorry, I'm not familiar with JSDoc. Can this example like code is actually used? Because the target of `@type` must be enclosed in parentheses, I think that the code like the example is not actually used.

We can get the expected output by enclosing it in parentheses.
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVAAgAIwJ4AOcmwmAvpuqgDpQAUAXnQB6YC8AfCbZpnQGYQIASjp0ARgEMATqIBMAajoBmYWp6ZpcGAFdpUPgEZhAblpk1IADQgIBGAEtoAZ2SgZ0iAHcACjISuKJIAbhAOACbWIOLSkmAA1toAygRxDlAA5sgw0jpwNgAWMAC2ADYA6gUO8M6pYHBJAdUOwdV4yODOrjbpznDSMD6xGcWSyPySpX02AFbOzABCsQnJksVwADLpcOOT0yBzzEnpGaVwAIo6EPC7U-kgqdJ90h1S4nClUQTS6TDlETACsgABwABhs3wgfXKsQIHW+cGewR2NgAjld4EM7IEQJJnABaKBwODhElRLTohxaIaSEZjJATO42PrFBzZXL3ZwnM6Xa47Bl7e4wSTif7hQHIOQ2HKSBylE4AYQgxVGHSg0BRIB0fQAKiLAoz9sE8gBJKCk2BJMA-ewAQXNSXwZ1ufTIZCAA)
**Input:**
```js
/* @type { } */
(z(x => {
  (foo)((bar)(2+(3)))
  return (1);
}))
```
**Output:**
```js
/* @type { } */
(z(x => {
  foo(bar(2 + 3));
  return 1;
}));
```

**Comment by thorn0** [comment]
@sosukesuzuki You're right. `@type` comments need special treatment only if they're followed by a parenthesized expression (for reference: [Closure][cl], [TypeScript][ts]). Also they must start with `/**`.

I just tried to isolate the issue, but here is a more practical example where this bug shows up (`@type` applies to the `q` variable):

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEB6AVOgBAARgTwAc4tgoBXAWwCM4AnAXy3VQB0oAbOGLARywC8WAF4AKAB6CAfKXZYsdbuTpQsogIwBKANzsGmkABoQEQjACW0AM7JQAQzp0IAdwAKDhDZR2AbhHMAJkYg1HR2YADW3ADKhOHmUADmyDB05HDGABYwlBwA6pnm8FZxYHDRnkXmPkX4yOBWNsYJVvQwrmGJlHbIAGZ2HK3GAFZW4gBCYZExdpRwADIJcH0DQyCj4tEJiVwAiuQQ8CuDGSBxdK109dR2tBzBhHQJMHmBMJnIABwADMaPEK08mFCPVHnBLj5lsZeAd4B1TF4QHYrABaKBwOABTHBRQw8yKDp2Lo9JD9E7GVqUcwpNKnKzbPaw5ak1anGC3V4Bd7IABMxlSdnMHG2AGEIJRuvUoNAoSByK0ACq3LxktY+dIASSgWNg0TATzMAEFtdECFxjq0GAwgA)

**Input:**
```jsx
/** @type {number} */
let q = z(x => {
  return (1);
})
```

**Output:**
```jsx
/** @type {number} */
let q = z(x => {
  return (1);
});
```

**Expected:**
```jsx
/** @type {number} */
let q = z(x => {
  return 1;
});
```

[cl]: https://github.com/google/closure-compiler/wiki/Annotating-JavaScript-for-the-Closure-Compiler#type-casting
[ts]: https://www.typescriptlang.org/docs/handbook/type-checking-javascript-files.html#casts

**Comment by thorn0** [comment]
fixed by https://github.com/prettier/prettier/pull/7791
