### ISSUE TITLE
SCSS Comments in maps that use mixins break code

### ISSUE THREAD

**Issue by boyenn** [prettier/prettier#7770]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlHntgE4CWWFAngLQA2VA5gBYwMCMATAAz50VAB4EKrAEYF+AGjxyFASnkBifv0xw4AM3kCApCpJkA9KbwBlCOjh5I6W7BN4A7uyrx8qnb7+ySJQBuEhBZEAhsGCpoAGdkUEwKCghXAAUkhHiUTAA3CCoAEzCQSQpMMABrOBhLbAqqKFZkGAoAVzhwznQmAHUPeFj6sDhLLM8qXM86ZHBY+PDG2LgKGDTy1ixkHUwmZfCAK1iRACFyqprLTFsAGUa4bd39kCORS0bWJjgARTaIeEee06IHqFGWFFmsTA8xKlEaMF6RRg7GQAA45CCUsteuVsLNKHBwbkHuEAI5-eDrSLZECYWIMKDaQpwYrhChwclUdnrTCbTCA57LYQtdrA2IfL6-f4PJA7IHhGCYSSIwrI5C8BXlKgsJoAYRsWxQUGgJJAbWWABUldk5c9ch0AJJQZmwSxgahRACCzssMDoXwFwLpMED4UKEDAoYibRg2BjvEDAF9E0A)
```sh
--parser scss
```

**Input:**
```scss
$map: (
  primary-light-120: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
  white: #ffffff,
);

```

**Output:**
```scss
$map: (
  primary-light-120: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment white: #ffffff
);

```

**Expected behavior:**

Don't break map due to `//` comment

**Comment by boyenn** [comment]
Seems to be fixed in master:
master:
```
exports[`maps-with-mixins.scss 1`] = `
====================================options=====================================
parsers: ["css"]
printWidth: 80
                                                                                | printWidth
=====================================input======================================
$map: (
  some-color: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
  white: #ffffff,
);

=====================================output=====================================
$map: (
  some-color: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
    white: #ffffff
);

================================================================================
`;
```

For reference, output when checking out tag v1.19.1:
```
exports[`maps-with-mixins.scss 1`] = `
====================================options=====================================
parsers: ["css"]
printWidth: 80
                                                                                | printWidth
=====================================input======================================
$map: (
  some-color: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
  white: #ffffff,
);

=====================================output=====================================
$map: (
  some-color: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment white: #ffffff
);

================================================================================
`;
```

**Comment by j-f1** [comment]
I think we might want to keep this open because of the change in indentation. cc @prettier/core is this already an issue somewhere?

**Prettier 2.0.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEASAtgQwA5IAQAUAOlHntgE4CWWFAngLQA2VA5gBYwMCMATAAz50VAB4EKrAEYF+AGjxyFASnkBifv0xw4AM3kCApCpJkA9KbwBlCOjh5I6W7BN4A7uyrx8qnb7+ySJQBuEhBZEAhsGCpoAGdkUEwKCghXAAUkhHiUTAA3CCoAEzCQSQpMMABrOBhLbAqqKFZkGAoAVzhwznQmAHUPeFj6sDhLLM8qXM86ZHBY+PDG2LgKGDTy1ixkHUwmZfCAK1iRACFyqprLTFsAGUa4bd39kCORS0bWJjgARTaIeEee06IHqFGWFFmsTA8xKlEaMF6RRg7GQAA45CCUsteuVsLNKHBwbkHuEAI5-eDrSLZECYWIMKDaQpwYrhChwclUdnrTCbTCA57LYQtdrA2IfL6-f4PJA7IHhGCYSSIwrI5C8BXlKgsJoAYRsWxQUGgJJAbWWABUldk5c9ch0AJJQZmwSxgahRACCzssMDoXwFwLpMED4UKEDAoYibRg2BjvEDAF9E0A)
```sh
--arrow-parens avoid
--parser scss
--trailing-comma none
```

**Input:**
```scss
$map: (
  primary-light-120: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
  white: #ffffff,
);

```

**Output:**
```scss
$map: (
  primary-light-120: mix(rgb(0, 0, 0), #00aeef, 20%),
  // Some comment
    white: #ffffff
);

```

**Comment by thorn0** [comment]
yep, #4878
