### ISSUE TITLE
event listener @event in vuejs get multiline format

### ISSUE THREAD

**Issue by jd-0001** [prettier/prettier#7773]
**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeSBbADtBMA6UABEUgJYDOAvPiAOZwwD6mOUeAFAOQCuWANhACGAEwC0AMwgAnDFwCUtQiSRTZTEUJhCaINRg1ahS4qX1M406TOq1zl69IomV5iFhhlotvTIPvPbxciAAE+TXgLKxtdByIqAD4iYCJ7aKd4ojiAXxMAegSQABoQAK8oCmRQIWiAdwAFGoRKlCEANwgyEWKQACNpITAAa0YAZSxBsig6ZBhpHjgSgAsYDH4AdSWyeAoJsDhR5u2yNu2AT2RwCkqSqYpLGHqBugwhZAkhfnuSgCsKAA8AEIDYZjIQYOAAGSmcHen2+ID+-1GUzo-DgAEUeBB4LN5osQBMnJZLm0Fj0sNIpjB1l0YEtkAAOAAMJUpEHu6wGWEulLg92kbVhJQAjtj4E93C0QEIKGJ2HARIqetI4GKyKqnkIXm9VPCCfcMGQ8QsShRUeisTjYUg5qaQNperSRPTkAAmEpzIRkfiogDCEAwr0uUFwPR49wAKkJei0Pl8CWS4ABJKBK2CjMBUjwAQTToxgZ3RcIT2WyQA)
```sh
--jsx-single-quote
--parser vue
--single-quote
```

**Input:**
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="err => { form_errors = err }"
/>
```

**Output:**
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="
    err => {
      form_errors = err;
    }
  "
/>

```

**Expected behavior:**
According to me this `@update_errors="err => { form_errors = err }"` should be in one line.
I am using inline function execution to write less code(& decrease code lines).

Please let me know your thoughts on this.

~ Regards

**Comment by j-f1** [comment]
Does this work?

**Prettier 1.19.1**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeSBbADtBMA6UABEUgJYDOAvPiAOZwwD6mOUeAFAOQCuWANhACGAEwC0AMwgAnDFwCUtQiSRTZTEUJhCaINRg1ahS4qX1M406TOq1zl69IomV5iFhhlotvTIPvPbxciAAE+TXgLKxtdByIqAD4ie2ineKIHEwB6BJAAGhAArygKZFAhaIB3AAUKhFKUIQA3CDIRfJAAI2khMABrRgBlLF6yKDpkGGkeOAKACxgMfgB1ObJ4ChGwOEH69bIm9YBPZHAKUoKxiksYap66DCFkCSF+a4KAKwoADwAhHv6QyEGDgABkxnBnq93iAvt9BmM6Pw4ABFHgQeCTaazEAjJyWU5NGYdLDSMYwZZtGBzZAADgADAVSRBrsselhTqS4NdpE1IQUAI7o+B3dwNEBCChidhwESyjrSOBCsiKu5CB5PVTQnHXDBkLEzAoURHItEYyFIKaGkDaTqUkTU5AAJgKUyEZH4iIAwhAMI9TlBcB0eNcACpCToNF5vHFEuAASSgctggzAZI8AEEk4MYEdkVCYwBfQtAA)
```sh
--jsx-single-quote
--parser vue
--single-quote
```

**Input:**
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="err => form_errors = err"
/>
```

**Output:**
```vue
<component
  :is="get_component('upload-form')"
  :form_data="form_data"
  :form_errors="form_errors"
  :form_options="form_options"
  @update_errors="err => (form_errors = err)"
/>

```

It should do the same thing, except that it returns `err` instead of nothing.

**Comment by jd-0001** [comment]
Hi @j-f1 it works fine and keep the code in one line. But is this the correct approach?

I don't have any issue in using this. If it is fine you can close it. But it won't work for multiple-expressions
```
@update_errors="err => { form_errors = err; my_post_func() }"
```
Let me know your thoughts on this.

~ Regards

**Comment by j-f1** [comment]
Yeah, that’s a standard elsewhere in Prettier. We always put separate statements on separate lines to the best of my knowledge.

**Comment by jd-0001** [comment]
Yes, but prettier is opinionated code formatter so I tought it will help with code length quite a bit.
Let me know should I close this?

**Comment by evilebottnawi** [comment]
@jd-0001 Yes, it is how prettier works
