### ISSUE TITLE
Always add a space after the function keyword for v2.0.1

### ISSUE THREAD

**Issue by hidroo** [prettier/prettier#7845]
Guys, I know that there isn't an option to disable this. But it will most certainly break a lot of code in my projects.

We have about ~1000 files in 20 project and I do not want to take the time now to fix all of them, because it is a days work to prettify them, build new versions and release - to make sure everything is okay.

**Comment by evilebottnawi** [comment]
You can postpone updating prettier, it is breaking change and it can create a lot of changes, we are not going to make an option for this

**Comment by evilebottnawi** [comment]
Spaces do not break code ^^

**Comment by SkeLLLa** [comment]
> Spaces do not break code ^^
 But those making code look uglier.

**Comment by hidroo** [comment]
We are not going to upgrade to 2.X any time soon.

I am not going to go into detail if it is prettier of uglier, I think that a dev should be the one to decide if he or she should use it.

**Comment by jwalton** [comment]
As I've said elsewhere, I don't care about the "prettiness" of it - I'm sure I'd get used to it pretty quickly.  My problem is I need an upgrade path that doesn't churn tens of thousands of line in my project, because I don't even want to think about the resulting nightmare of merge conflicts, and since there's no option to change this behavior, I don't have one.

**Comment by hidroo** [comment]
It seems to be that they think the upgrade path is to upgrade the prettier when you are ready, I don't know. 

What will end up happening is us using different prettier versions across our 30 projects. Will keep you up to speed if we think of something.

**Comment by evilebottnawi** [comment]
@jwalton @hidroo  you can setup eslint rule for it using prettier-eslint or just eslint after and make gradual migration

**Comment by jwalton** [comment]
A gradual migration is an option, but not a great one - we use pretty-quick, so I could just leave pretty-quick turned on and then as people commit files, they'll get upgraded.  This means some files in our repo will be following the "old prettier coding standard" and some the new, and it also adds a lot of pointless noise to PRs for the next several months.  I'm not sure if that's better or worse than doing it all at once.  :(

**Comment by SkeLLLa** [comment]
@evilebottnawi prettier-eslint uses old prettier, so it's not compatible. Also setting up additional eslint rules will result that if prettier and eslint will work at the same time (e.g. if some IDE will do that), then it will result in broken files, cause prettier doesn't check if file was changed, since it was read, before saving.

**Comment by evilebottnawi** [comment]
**Spaces not break code** :smile:

**Comment by SkeLLLa** [comment]
> Spaces not break code smile
Unless you install vscode prettier extension and try to use it with prettier 2.0 :).

**Comment by bakkot** [comment]
@jwalton 

> My problem is I need an upgrade path that doesn't churn tens of thousands of line in my project, because I don't even want to think about the resulting nightmare of merge conflicts

After updating and running prettier in master, run `npx prettier@2.0.1 .` in your branch (or update prettier in the branch and run it however you currently run it), and now there's no merge conflict.

@SkeLLLa We don't generally consider changes to formatting to be breaking. Otherwise almost every release would be major.

**Comment by SkeLLLa** [comment]
@bakkot the thing is not in changes, the thing is in that the change was done is not configurable and it conflicts many styleguides.

**Comment by bakkot** [comment]
@SkeLLLa that is true of most changes.
