### ISSUE TITLE
Odd arrow function printing

### ISSUE THREAD

**Issue by cpojer** [prettier/prettier#800]
This:

```js
const initializeSnapshotState = (
  testFile: Path,
  update: boolean,
  testPath: string,
  expand: boolean,
) => new SnapshotState(testFile, update, testPath, expand);
```

gets turned into this:

```js
const initializeSnapshotState = (
  testFile: Path,
  update: boolean,
  testPath: string,
  expand: boolean,
) =>
  new SnapshotState(testFile, update, testPath, expand);
```

in https://github.com/cpojer/jest/blob/master/packages/jest-snapshot/src/index.js

It looks a bit odd.

https://prettier.github.io/prettier/#%7B%22content%22%3A%22const%20initializeSnapshotState%20%3D%20(%5Cn%20%20testFile%3A%20Path%2C%5Cn%20%20update%3A%20boolean%2C%5Cn%20%20testPath%3A%20string%2C%5Cn%20%20expand%3A%20boolean%2C%5Cn)%20%3D%3E%20new%20SnapshotState(testFile%2C%20update%2C%20testPath%2C%20expand)%3B%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3Afalse%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
Likely related to #680

**Comment by jlongster** [comment]
Honestly I'm not a fan of bumping down contents ever from arrow functions like that. We didn't do that in early version of prettier and I had no idea some people wanted that until they filed bugs. We do it because some people do stuff like

```
func =>
  Promise.resolve((resolve, reject) => {
    // lots of code
  })
```

But in my opinion they really should just make it a block and use `return`. I'm not sure if we can go back on that though?

**Comment by vjeux** [comment]
Turns out there's an easy fix for this one: https://github.com/prettier/prettier/pull/829
