### ISSUE TITLE
trailingComma: none is ignored by v4+

### ISSUE THREAD

**Issue by sbreakey** [prettier/prettier#8000]
**Environments:**

- Prettier Version: 4.1.1 (but any 4+ version is reproducible)
- Running Prettier via: VS Code
- Runtime: No idea. VS Code?
- Operating System: Windows 10

**Steps to reproduce:**

set the rule `"prettier.trailingComma": "none"` in your settings. Write some typescript like:
```
x = {
  'a': 'b'
}
```

**Expected behavior:**
Given the no trailing commas, the above block of code should not be formatted

**Actual behavior:**
The setting is ignored and the code is formatted to:
```
x = {
  'a': 'b',
}
```
thereby creating a mess in git diffs.

NOTE: downgrading to version 3.20.0 fixes the issue for whatever reason.
EDIT: this appears to affect other rules too, e.g. whatever the rule is that wraps single arguments to arrow functions is (I think arrowParens)?

**Comment by fisker** [comment]
Please use [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXncAOlddAcgEMiliAjI-AXxABoQIAHGAS2gGdlQSAnfhADuABQEIeKEgBthJAJ48mlfiTABrODADKLdeygBzZDH4BXOEwAWMALYyA6tfbwu+sHB2TX7AG6uCsjgXMoghlxw-DCiakZ2JMgAZrKRTABWXKgAQmqa2jokdnAAMoZwyalWIJmoOoZGMnAAiuYQ8JUyaSD6-JH8wZQklHAyjD38hjCO7AAmMNbIABwADEwsQpGOaizBG3D9fhVMAI5t8LGsUiAkXAC0UHBws8-j-HBn7O+xJPGJSCkutVInZ2KYLMCGk1Wu0KgCqkwYMMZvNFkgAEyItTsGQNADCEDsCWCUGgxxA5kiABVhlJAd0-JYAJJQF6wHRgSZsACCrJ0MAUTU6kVotCAA) to report issue, otherwise this will be closed.

**Comment by sbreakey** [comment]
> Please use [playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAPABAXncAOlddAcgEMiliAjI-AXxABoQIAHGAS2gGdlQSAnfhADuABQEIeKEgBthJAJ48mlfiTABrODADKLdeygBzZDH4BXOEwAWMALYyA6tfbwu+sHB2TX7AG6uCsjgXMoghlxw-DCiakZ2JMgAZrKRTABWXKgAQmqa2jokdnAAMoZwyalWIJmoOoZGMnAAiuYQ8JUyaSD6-JH8wZQklHAyjD38hjCO7AAmMNbIABwADEwsQpGOaizBG3D9fhVMAI5t8LGsUiAkXAC0UHBws8-j-HBn7O+xJPGJSCkutVInZ2KYLMCGk1Wu0KgCqkwYMMZvNFkgAEyItTsGQNADCEDsCWCUGgxxA5kiABVhlJAd0-JYAJJQF6wHRgSZsACCrJ0MAUTU6kVotCAA) to report issue, otherwise this will be closed.

Sorry, I don't know what that is. And it isn't immediately obvious how to setup a trivial example there.
In my particular case I've downgraded and that fixes it for me. if you don't want to fix the issue, then you can close it.

**Comment by sbreakey** [comment]
Looks like this belongs in https://github.com/prettier/prettier-vscode anyway
