### ISSUE TITLE
Multiple files for --ignore-path

### ISSUE THREAD

**Issue by alfechner** [prettier/prettier#8048]
I use the [--ignore-path](https://prettier.io/docs/en/cli.html#--ignore-path) argument and point it to an exhaustive `.gitignore` file. It's great that I don't have to duplicate the list of ignored files.

However, there are a couple of files I'd like to exclude from prettifying but still want to commit. Is there any way to specify an additonal `.prettierignore` file so that I can add files without copying the entire `.gitignore`?

**Comment by evilebottnawi** [comment]
I have some idea.
- `.gitignore` for basic ignoring setup
- `.prettierignore` for ignoring files for prettier

**Comment by alfechner** [comment]
Yep, this is what I'd need. In the end it's not unlikely that the files which should be ignored from git and Prettiner are partially different. Using `.gitignore` for Prettier is an amazing feature, but useless (for us) if we cannot enhance the ignored files.

**Comment by blaggacao** [comment]
I think this aproach is favourable: https://github.com/prettier/prettier/issues/8506#issuecomment-659604909
See also: kaelzhang/node-ignore#58

**Comment by bennycode** [comment]
Is it difficult to extend the [--ignore-path](https://prettier.io/docs/en/cli.html#--ignore-path) so it can accept a comma-separated list of files?

**Comment by lashchanka** [comment]
+1 for this:
https://github.com/prettier/prettier/issues/8048#issuecomment-1030941915

**Comment by SarcevicAntonio** [comment]
I'd love for prettier to automatically set --ignore-path to .prettierignore _and_ .gitignore.

**Comment by fisker** [comment]
I think we can accept multiple `--ignore-path`.

But when `--ignore-path` is used, maybe we should not search for `.prettierignore` file?

**Comment by remcohaszing** [comment]
I would really like a solution that _just works_ once configured. When I contribute to a project that uses Prettier, I expect the normal Prettier workflow to just work out of the box. I.e. I expect to be able to check the project using `prettier --check .`, format everything using `prettier --format .`, and I expect the editor integration to just work.

If a project relies on a specific command line flag, this is no longer the case. This means the project needs to document this in their contriburing guidelines, which is more effort than duplicating `.gitignore` into `.prettierignore` and is unlikely to happen. This is why I really prefer a solution that involves configuring Prettier using `.prettierignore`, `editorconfig`, and `.prettierrc` files, such as my proposal in https://github.com/prettier/prettier/issues/8506#issuecomment-659604909. Alternatively `ignorePath` could also be allowed in `.prettierrc`.

**Comment by fisker** [comment]
This won't be a problem if we search `.gitignore` and `.prettierignore` by default. Maybe we can do this in v3.

**Comment by fisker** [comment]
> Alternatively ignorePath could also be allowed in .prettierrc.

This make sense.

**Comment by tomdavidson** [comment]
Ive just `--ignore-path <(cat .gitignore .prettierignore)` but would like ignorePath supported in the config.

**Comment by reinzor** [comment]
> Ive just `--ignore-path <(cat .gitignore .prettierignore)` but would like ignorePath supported in the config.

Requires `bash -c 'prettier --ignore-path <(cat .gitignore .prettierignore) .....` when used as script in the `package.json` file.

**Comment by devinrhode2** [comment]
> bash -c 'prettier --ignore-path <(cat .gitignore .prettierignore) --write .'

Just tried this with yarn v1.22.19 and did not work :/

**Comment by devinrhode2** [comment]
Anything ignored by .gitignore, which we want prettier for format, could be negated inside of .prettierignore like so:
```
!public/*.js
```

**Comment by devinrhode2** [comment]
@fisker we need something that _just works_, i.e. [one of remcohaszing's ideas](#issuecomment-1108274919)

Otherwise we'll end up using a fork.... no fun

**Comment by Stephen-ONeil** [comment]
Thirding a "just works" solution, acknowledging that I've got some bias ;). When #8288 was closed I didn't say anything because I thought it was closed in favour of #8506, which was good enough for me. Didn't notice till later it was actually closed in favour of this approach.

**Comment by fullstackjedi** [comment]
Another option could be to modify the [prettier config](https://prettier.io/docs/en/configuration.html) a little bit, so instead of directly adding the config, add some subprops like `rules` (this is where the config will live), and `ignore`, which is where we would be able to put multiple ignore files, and this can be compatible with tools built on top of prettier (IDE extensions, npm packages like `pretty-quick` for example)

### Example JSON config

```json
{
  "rules": {
    "trailingComma": "es5",
    "tabWidth": 4,
    "semi": false,
    "singleQuote": true
  },
  "ignore": [
    ".prettierignore",
    ".eslintignore",
    ".gitignore"
  ]
}
```

^ same as with JS, YAML, TOML, or `package.json` configuration

**Comment by tomdavidson** [comment]
I like the ignore object to configure, but I think .gitignore could still be a just works default.

**Comment by fullstackjedi** [comment]
> 

I agree that `.gitignore` can be a default, but imagine this scenario:

- I am working on an Open Source project, where I automated my release process using any existing tool
- The tool calculates the version and generates a `CHANGELOG.md` file with the latest changes
- The `CHANGELOG.md` file doesn't meet my Prettier config, hence, I have a pipeline error on my CI system
- I can't ignore my `CHANGELOG.md`, since I want it to be on the repo for reference

**Comment by devinrhode2** [comment]
I don't really like the trend of dumping tons of config into package.json, but I can appreciate why it exists: adding 8 different config files to the root of a repo is just not that appealing.

I've setup projects setup where the package.json is _only_ for dependencies, this allows some git pre-commit scripts to do some nifty things, like ff package.json changes, then yarn.lock should also have changed (vast majority of the time). This means you could stage one dependency, commit, and it'll ensure the yarn.lock file only reflects changes due to adding that _one_ dependency. Stage next dependency, commit, same thing. So yarn.lock changes are normalized and predictable.

Overall I do love `.fooconfigrc.js` files. I can use TS type checking via jsdoc annotations, import other files with normal node.js `require` or `import`, etc.

So if we use cosmicconfig then a `.fooconfigrc.js` can also come along with that, whether people put everything into package.json is their own choice ;)

**Comment by devinrhode2** [comment]
Also, first person to re-write cosmiconfig in rust or zig gets a gold star

**Comment by fullstackjedi** [comment]
> I don't really like the trend of dumping tons of config into package.json, but I can appreciate why it exists: adding 8 different config files to the root of a repo is just not that appealing.
> 
> I've setup projects setup where the package.json is _only_ for dependencies, this allows some git pre-commit scripts to do some nifty things, like ff package.json changes, then yarn.lock should also have changed (vast majority of the time). This means you could stage one dependency, commit, and it'll ensure the yarn.lock file only reflects changes due to adding that _one_ dependency. Stage next dependency, commit, same thing. So yarn.lock changes are normalized and predictable.
> 
> Overall I do love `.fooconfigrc.js` files. I can use TS type checking via jsdoc annotations, import other files with normal node.js `require` or `import`, etc.
> 
> So if we use cosmicconfig then a `.fooconfigrc.js` can also come along with that, whether people put everything into package.json is their own choice ;)

@devinrhode2 yep, the good think about Prettier is that it uses Cosmiconfig, so you don't have to dump everything into the `package.json`, you can use any flavor of `.prettierrc` syntax. In my case, I prefer adding them to the `package.json` in order to reduce the number of config files, and if we could also specify the ignore files on that same config, that'll be a plus .

**Comment by davidbludlow** [comment]
On Apr 25, 2022, @fisker said

> This won't be a problem if we search .gitignore and .prettierignore by default.

I disagree. What if you don't want to use .gitignore at all? A strategy using `#!include:.gitignore` (see https://github.com/prettier/prettier/issues/8506#issuecomment-659604909 ) or a strategy like https://github.com/prettier/prettier/issues/8048#issuecomment-1218469292 has more flexibility.

As a sorta compromise with what you said @fisker, what if we make it so that by default, if there is no .prettierignore in the root directory, then it uses all the .gitignore files in the project, but if there is a .prettierignore, then we don't use .gitignore files unless something like `#!include:.gitignore` says otherwise (or unless the mechanism in https://github.com/prettier/prettier/issues/8048#issuecomment-1218469292 says otherwise, if we implement that solution). I just think if we go with a solution like what you said that "we search .gitignore and .prettierignore" then it might be annoying that you can't ignore .gitignore .

But, to be fair, right now I can't think of a situation in which someone would want to not pay attention the .gitignore, especially if they can override the rules somewhere else, like in .prettierignore .

**Comment by davidbludlow** [comment]
If prettier decides to go with the `#!include:.gitignore` Plan ( https://github.com/prettier/prettier/issues/8506#issuecomment-659604909 ), then https://github.com/kaelzhang/node-ignore/issues/58 will likely be implemented, which will be able to help other open source projects that face a similar challenge to this.

**Comment by JaneJeon** [comment]
Ah, so I am to understand that specifying `--ignore-path $file1 --ignore-path $file2` (currently) does not work?

**Comment by fisker** [comment]
I'm going to make `--ignore-path` accept multiple files.

**Comment by karlo-humanmanaged** [comment]
> > bash -c 'prettier --ignore-path <(cat .gitignore .prettierignore) --write .'
> 
> Just tried this with yarn v1.22.19 (inside an npm script) and did not work :/

It is important to wrap it with `bash -c`
Mine works by doing
```
"format": "bash -c 'prettier --config src/libs/eslint-config/.prettierrc.config.js --ignore-path <(cat .gitignore .prettierignore) --write \"**/*.{js,jsx,ts,tsx,md,json,css,scss,yaml,yml}\"'",
```

**Comment by davidbludlow** [comment]
@fisker said
> I'm going to make `--ignore-path` accept multiple files.

IDE prettier plugins can't see that you have an `--ignore-path` command line argument in your prettier npm script. Since 99% of prettier users use a prettier IDE plugin, we should have a solution that all prettier IDE plugins will automatically pick up on.

**Comment by fisker** [comment]
> we should have a solution that all prettier IDE plugins will automatically pick up on.

We can support ignore pathes in .prettierrc.
We can also support patterns in .prettierrc(consider .prettierrc it self is an ignore file).

I think this will solve all related issues.

**Comment by remcohaszing** [comment]
Both those options would be great!

**Comment by tstibbs** [comment]
> > > bash -c 'prettier --ignore-path <(cat .gitignore .prettierignore) --write .'
> > 
> > 
> > Just tried this with yarn v1.22.19 (inside an npm script) and did not work :/
> 
> It is important to wrap it with `bash -c` Mine works by doing
> 
> ```
> "format": "bash -c 'prettier --config src/libs/eslint-config/.prettierrc.config.js --ignore-path <(cat .gitignore .prettierignore) --write \"**/*.{js,jsx,ts,tsx,md,json,css,scss,yaml,yml}\"'",
> ```

@karlo-humanmanaged my issue with this approach is that while it works in your one case where there is a single .gitignore file at the root, it doesn't support the case where there are multiple .gitignore files at multiple levels, because git applies the patterns differently depending on the level, which prettier can't do. (I accept this might be a rare case though)

**Comment by davidbludlow** [comment]
@fisker I am not sure I am understanding the details of what you are proposing, but if I am understanding what you are saying correctly, then I think it is a good solution.

**Comment by fisker** [comment]
> Make a new option that can be put inside .prettierrc called useGitignore and have it be true by default. 

I haven't go through details yet.
My plan is search `.gitignore` and `.prettierignore` by default. But `prettier --ignore-file=.prettierignore` will only check files ignored by `.prettierignore`, not `.gitignore`.

> it may be considered a breaking change

Only if we search `.gitignore` by default.

**Comment by davidbludlow** [comment]
@fisker, and does your plan also allow users to specify multiple ignore files in .prettierrc.json ?

**Comment by fisker** [comment]
> But, to be fair, right now I can't think of a situation in which someone would want to want prettier to pay attention to the .gitignore

I'm sorry, but I'm not sure what do you mean
1) people may want format `.gitignore` file
2) people may want format files ignored by `.gitignore`

**Comment by fisker** [comment]
> 

Yes.

**Comment by fisker** [comment]
Funny things, our codebase need format `.gitignore`d files.

Ignored:

https://github.com/prettier/prettier/blob/cf409fe6a458d080ed7f673a7347e00ec3c0b405/.gitignore#L12

Ignored:

https://github.com/prettier/prettier/blob/cf409fe6a458d080ed7f673a7347e00ec3c0b405/package.json#L159

But not ignored

https://github.com/prettier/prettier/blob/main/.gitignore

**Comment by fisker** [comment]
We put `test.foo` in root and run `node bin/prettier test.foo` to debug, but don't commit and lint/fix.

**Comment by davidbludlow** [comment]
Interesting!

**Comment by dietergeerts** [comment]
> 2. people may want format files ignored by `.gitignore`

What exactly is the value of formatting files that will not be checked in, and thus only you will see and use? I mean, Prettier is here to stop the discussion about code style in a team. If you work on your own, or have files that only you use and need, why would it matter? I don't believe that Prettier should care about this use-case, as it's not the goal of the package like described in the docs.

**Comment by connorjs** [comment]
> This is why it's needed that .gitignore is kind of the default that needs to be used, and .prettierignore for these extra files.

This represents my belief too: `.gitignore` as a sane (and great) default, with alternative mechanisms to replace or opt-out. I am still using `--ignore-file .gitignore` in my `package.json` which fields cumbersome.

> What exactly is the value of formatting files that will not be checked in, and thus only you will see and use?

Readability mostly. For example, consider generated code. You do not check it in, but you may read it. Formatting makes it easier to read.

_That being said, I use other mechanisms to format generated code, usually manual commands after generation or [hooks like graphql-code-generator](https://the-guild.dev/graphql/codegen/docs/config-reference/lifecycle-hooks#afteronefilewrite), so using `.gitignore` still works perfectly for my case._

**Comment by leaumar** [comment]
> If you work on your own

The benefit of making code style an automated, consistent, non-debatable thing doesn't depend on there being teammates, it's just as relevant to solo players.

I love having prettier on my pet projects so that all code (inside and across projects) reads the same and git churn/conflicts are kept to a minimum. You adapt to the tools you use, making working on code without them almost as jarring as being forced to use something other than your normal IDE.

> files that will not be checked in

Formatting is a human reader's concern at least as much as it's a source control concern.

Code is code, it all does something and it all needs to be read/edited from time to time. Consistent formatting helps the reader even if a file isn't committed.

--

I agree prettier should put its main usecases first in conflicts, and its code should be protected from development/maintenance burdens that don't belong. Source control has a certain overlap with formatting (creating a problem to solve and a convenient configuration shortcut to support), but doesn't exclusively determine the need for formatting. The more usecases for formatting that prettier can fulfill without hurting itself or degrading more important usecases, the better for everyone.

**Comment by ehaynes99** [comment]
> Formatting is a human reader's concern at least as much as it's a source control concern.
>
> Code is code, it all does something and it all needs to be read/edited from time to time. Consistent formatting helps the reader even if a file isn't committed.

The entire purpose of source control is to keep track of the files intended to be read/edited by humans. That's why we use the term "source control", because it's the "source code". Compilers take code readable by humans and optimize it to be read by machines. JS happens to be an interpreted language, so the compiled artifacts are also code, but those are NOT intended to be read/edited. Dependencies and myriad other files created by tooling to be read by tooling are all similar

> Consistent formatting helps the reader even if a file isn't committed.

"Not committed" is very different from "explicitly ignored". If you need to change a file in an ignored path, it's in the wrong place.

None of these change whether it's a solo project or has multiple people.

> Funny things, our codebase need format .gitignored files.
Well ok, sure, if you're generating code within the formatting tool's own root directory to test the formatter, that's quite possibly the only exception I can think of. :-)

**Comment by leaumar** [comment]
> but those are NOT intended to be read/edited

I can't begin to count how often I've had to read code "not meant" for reading (js bundles, swagger-generated java, ...) or outside of version control to troubleshoot something.

People want some extra control over _which_ files are in formatting scope, not _how_ they're formatted. File structure and all that follows from it is a matter of all tools and other concerns driving/limiting a project. There's no room for one tool to get dogmatically picky about the context you're using it in when it perfectly _could_ just do its job. It's a file formatter, not the Multiplayer Workflow Police, and git is only a version control tool, it doesn't control other aspects of a project like which files a dev may want to read.

The stated goal of reducing friction for teams doesn't require shoehorning git into a role of permanent authority over formatting. Using and encouraging conventions to reduce configuration is one thing, conflating things and refusing to work outside those conventions is another.

That discussion aside for a second, I don't see what the big deal is against letting people override the conceptual "ignore files list" parameter if they need to for whatever reason. Default to reading .gitignore but let people specify other combinations. It's nothing more than a list with a default value, a pattern that's ubiquitous, easy for everyone, and super flexible. This doesn't infringe on anything else prettier might strive for.

* `prettier .` is shorthand for `prettier --ignore .gitignore .`
* `prettier --ignore .gitignore --ignore .prettierignore .` if some committed files must not be touched (e.g. yarn.lock)
* `prettier --ignore .prettierignore .` if some committed files mustn't be touched and/or people want to format some local-only files (e.g. "run" config, like application-local.yml for spring boot)

Isn't an implicit goal of _every_ project to maximise utility as much as possible without treading on the other goals? Prettier is a formatter first, collaboration tool second IMO. Formatting is also a matter of people growing used to the format and finding it jarring to read a file formatted differently or not having autoformat while writing something, making it important for UX to not be picky about running on otherwise supported files.

**Comment by ehaynes99** [comment]
> That discussion aside for a second, I don't see what the big deal is against letting people override the conceptual "ignore files list" parameter if they've decided they need to for whatever reason

The big deal is that the current behavior is wrong for the *overwhelming* majority of cases. This issue has been open for 3 years and has been under active discussion for ~13 months. Practically every user of the library has had to run into these problems, spend the time figuring out why it happens, and then fiddle around with copy/pasted ignore files or stuffing CLI parameters into npm scripts. I imagine a significant portion of those got frustrated enough to spend time trying to solve it "once and for all" only to realize that you can't do it with a shared config and that CLI params can't be used in a project-agnostic way in editors.

A 5-minute fix that adds `path.resolve('.gitignore')` [here](https://github.com/prettier/prettier/blob/main/src/common/create-ignorer.js#L34) would would be a vast improvement for 99.999% of users. Discussion of that one time 2 years ago when someone needed to not just read a js bundle, but actually format it (a case where I would argue you should probably copy the file somewhere else anyway) is bikeshedding. If we have to choose, put out the house fire and start a new years-long conversation about how to light the candle. The extraordinarily uncommon use-cases should be the ones using hacks to make it work, not the other way around.

> There's no room for one tool to get dogmatically picky about the context you're using it in when it perfectly could just do its job. It's a file formatter, not the Multiplayer Workflow Police, and git is only a version control tool, it doesn't control other aspects of a project like which files a dev may want to read.

"Repository" and "project" are synonyms. If "a dev may want to read" it, *any* dev -- including "me on my other computer" -- is going to have a hard time with that when it's not there. Deviating from that is where all of the "works on my machine" issues come from, why you find projects on GitHub that you can't compile, why people constantly expose secrets in env files that "weren't supposed to be checked in", and why so many companies have a week(s)-long process of onboarding new developers to "get their workspace set up".

> Isn't an implicit goal of every project to maximise utility without treading on other goals, and for tools to be agnostic of things that aren't their immediate business outside of sane defaults?

Often, less is more. Prettier _could_ have had thousands of formatting options. It maximized utility by saying "no" often and unapologetically. `ripgrep` and `fd` maximized utility by honoring `.gitignore` for searching text & files. In fact, "zero configuration" that _Just Works™_ is generally as maximal utility as development tools can get.

**Comment by fisker** [comment]
> > @fisker, and does your plan also allow users to specify multiple ignore files in .prettierrc.json ?
> 
> Yes.

Unfortunately, it seems our config loader don't allow cli flags now.

**Comment by Standard8** [comment]
> > > @fisker, and does your plan also allow users to specify multiple ignore files in .prettierrc.json ?
> > 
> > 
> > Yes.
> 
> Unfortunately, it seems our config loader don't allow cli flags now. Need more work.

I don't understand this comment. When I played around with adding a configuration option for this previously, it would automatically add the CLI flag (stopping it adding a CLI flag didn't seem possible).

**Comment by tstibbs** [comment]
The logical successor to this feature is https://github.com/prettier/prettier/issues/14115 - I suspect many of the 77 voters on this issue are interested in this primarily so they can make prettier ignore everything ignored by git, in which case you might want to put a vote on #14115.
