### ISSUE TITLE
command to generate and export default config

### ISSUE THREAD

**Issue by jzaynal** [prettier/prettier#8053]
This is feature request / question why it hasn't already been done, so ignoring the issue template.

First of all thanks for your work, we're using this tool and get its benefits most of the times. There are also times when it frustrates us; I'm here due to the frustration :)

> Prettier is an opinionated code formatter.

Nothing could've been more true! And it doesn't help that with every version change the opinions change too, leading to build failures for people using prettier in their CI pipeline. When this is the case, why not have a command / option as part of the CLI to export the default configuration so people can save for later, so when versions change one can at least ensure consistency in configs in the project?

Our issue is we have a couple of different folders (one for source code, one for tests) that both use prettier for formatting. And some of us also use the Visual Studio Code extension to format on save.. the obvious solution to that is to have a prettier config file in the shared directory above the two folders which would ensure VS Code extension as well as running CLI commands under any of the two folders would result in the same formatting. But there is no way to generate a default set of config that a particular version of prettier uses. 

Say I'm on 1.19 now, I'd like to generate a config from the current point and ensure any version change would still end up with the same formatting. Other than picking the configs one by one from the documentation and generating a file manually, is there a way to "export" one through the CLI or otherwise?

**Comment by thorn0** [comment]
Thanks for the issue, but we're not going to add this.

> And it doesn't help that with every version change the opinions change too

"Every version change"? If you mean the default values of options, so far this happened only once, in 2.0. These changes were clearly highlighted as breaking changes in the release notes, and that was a major version bump. You shouldn't update software to a new major version without going through release notes anyway. Major versions aren't supposed to happen often. And finally you want Prettier to know how to generate a config file for its **future versions**, which seems to require a time machine.

> Say I'm on 1.19 now, I'd like to generate a config from the current point and ensure any version change would still end up with the same formatting.

Not possible. Prettier may introduce formatting changes (not controlled by options, so having a config file won't help you here) even in patch releases. That's why you should always pin the version. E.g. `"prettier": "1.19.1"`, not `"prettier": "^1.19.1"`. See https://prettier.io/docs/en/install.html

**Comment by jzaynal** [comment]
@thorn0 I'm not surprised by the response.

> you want Prettier to know how to generate a config file for its future versions, which seems to require a time machine

If you re-read my original request I never said anything about future versions, so I don't know where you got that. I clearly said "I'd like to generate a config from the **current** point"

Anyway, just a piece of advice though the main point of open-source projects is so people can contribute to them, and that requires cooperation as well as acceptance. If I were you I'd probably ask feature requesters to feel welcome by creating a PR with the feature they think would be useful and see if it was a viable feature to have, rather than shut them down immediately the way you just have.

**Comment by thorn0** [comment]
> I'd like to generate a config from the current point

But you want the future versions to understand that config, right?

**Comment by jzaynal** [comment]
Well, if options are mostly dictated by configs then as long as future versions refer to the options by the same name then it would work as expected. Having the *values* of those options would then be left to whatever the configs said. For example, if an option with `tabSpace` is set as `4` initially but change to `2` in a future version, as long as option is still called `tabSpace` config would not need to change. Any change of option name would then be included in changelog as part of breaking changes. New options with major version bumps would not be an issue either as new options wouldn't have been accounted for previously anyway.

**Comment by thorn0** [comment]
What if Prettier 3.0 has a completely different configuration format or no configuration at all? When a major version changes, such things are totally possible (it is exactly because of such things that it changes).

But what actually happened in 2.0 is that **3 options changed their default values** for the first (and probably last) time in the project's history. It doesn't happen in every version as you wrote. So indeed, there in no reason to be surprised by the response.
