### ISSUE TITLE
[Documentation] Config precedence 

### ISSUE THREAD

**Issue by RoarkeRandall** [prettier/prettier#8074]
I'm looking at the docs on configuration (https://prettier.io/docs/en/configuration.html). I find the wording confusing in the top section. Which order is the precedence? Is there an "overlaying" effect? Maybe my english is just bad, but I think maybe an example might help.

**Comment by thorn0** [comment]
The list is sorted by precedence. E.g. if you have both `prettier.config.js` and a `"prettier"` key in `package.json`, the key will be used because it's higher in that list. Prettier uses the [`cosmiconfig` library](https://github.com/davidtheclark/cosmiconfig) for config resolution, so you can read more in [cosmiconfig's README](https://github.com/davidtheclark/cosmiconfig#cosmiconfig).

If you have ideas on how to improve this page, feel free to submit a PR. It's here: https://github.com/prettier/prettier/blob/master/docs/configuration.md
