### ISSUE TITLE
HTML: replace non-ASCII whitespace characters with HTML entities

### ISSUE THREAD

**Issue by fisker** [prettier/prettier#8146]
**Prettier 2.0.5**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAeAJgSwG4D4C6gwASAgBIKAEA2qgPRZ4gA0IEADjJtAM7KgCGATnwgB3AAr8EXFDwA2QngE8ujAEZ8eYANZwYAZWbrMUAObIYfAK5xGACxgBbaQHVrmeB31g4Oia5yv5yOAcSiCGHHB8MCJqRnY8yABmMuGMAFYcAB4AQmqa2jo8dnAAMoZwiclWIOkZOoZG0nAAiuYQ8BXSKSD6fOF8gbYODN18hjCOmOgw1sgAHAAMjMyC4Y5qzIHLcH3Y5YwAjq3w0SySIDwcALRQcHDod8N8cIeYT9E8sfFISZ1V4XaYUwWP71RotNrlb6VRgwHjKCZTGZIABMMLUmGk9QAwhA7HFAtsAKzDczhAAqcMkPy62EsAEkoPdYDowKNWABBRk6GDyRodcIAXwFQA)
```sh
--parser html
```

**Input:**
```html
<div>]   [</div> <!-- Note: not `U+0020` inside -->
```

**Output:**
```html
<div>]   [</div>

```

**Expected behavior:**
```html
<div>]&#8195;&#8196;&#8197;[</div>

```

**Comment by fisker** [comment]
Why labelled bug? I think it's feature request.

**Comment by thorn0** [comment]
People who use those characters may not be glad to see them replaced with entities. Without understanding their use cases, we shouldn't change this. After all, if somebody wants entities, they can write entities. Prettier preserves entities.

The fact that those characters look confusing because they're similar to other characters isn't a strong argument. E.g. the Cyrillic А looks the same as the Latin A, but replacing Cyrillic letters with entities sounds like a really terrible idea.

**Comment by fisker** [comment]
@thorn0 You convinced me, let's close it.
