### ISSUE TITLE
prettier 2.5.0 led to critical dependency warnings and undefined dirname errors in Windows 10

### ISSUE THREAD

**Issue by LeungYu** [prettier/prettier#8341]
When I just import prettier.js in a react.js project by:
`import {format} from "prettier";`
The cmd console output warnings like picture below:
![image](https://user-images.githubusercontent.com/33388255/82274237-2c056180-99b2-11ea-8e0c-b1ce00348971.png)

and the browser gave out an error tips like this:
### TypeError: Cannot read property 'dirname' of undefined
(anonymous function)
D:/exmaples/node_modules/prettier/index.js:28185:36
```
   28182 |   return false;
   28183 | };
   28184 | 
>  28185 | var pathPosixDirname = path$2.posix.dirname;
   28186 | var isWin32 = os$1.platform() === 'win32';
   28187 | var slash = '/';
   28188 | var backslash = /\\/g;
```
Then I output the path$2 in console and got information below:
![image](https://user-images.githubusercontent.com/33388255/82275163-9b7c5080-99b4-11ea-87fb-60c8cb3fb850.png)

It seems that value posix were not found in Windows cmd.

Informations:
node.js  --v8.10.0
npm --v5.6.0
webpack --v4.42.0

**Comment by fisker** [comment]
1. `prettier 2.5.0` you mean `prettier 2.0.5`?
2. You should use Node.js [`>=10.13.0`](https://github.com/prettier/prettier/blob/f3e59453cdab031ec7ea9a683b39fee281324d28/package.json#L12)
3. [`path.posix` is available since `v0.11.15`](https://nodejs.org/api/path.html#path_path_posix), so it should be some problem with your webpack

**Comment by kachkaev** [comment]
Node 8 is [no longer supported by the commuity](https://nodejs.org/en/about/releases/), i.e. it has reached _end of life_. Node 8 is slower than more recent versions and may also contain vulnerabilities. Try installing Node 12 and this should fix the issue for you. Not only Prettier will work again, but you may also notice performance improvements during developing.

**Comment by thorn0** [comment]
You can't do `import ... from "prettier";` in a web app. Please see the docs (https://prettier.io/docs/en/browser.html) to learn how to run Prettier in the browser.

**Comment by BFrancoeur** [comment]
Hi,
I am having this same issue on my Macbook Pro. What's odd is that I see a check for 'win32', which should return false since I am on a Mac (please see attached screenshot). 

How can I resolve this on my Macbook Pro (and iMac)? Both run Intel CPUs. 

Thanks in advance!
<img width="1196" alt="Screen Shot 2020-07-22 at 7 37 22 AM" src="https://user-images.githubusercontent.com/6320997/88172119-7a232500-cbee-11ea-967e-fcf20294a103.png">

**Comment by thorn0** [comment]
@BFrancoeur You can't use `import ... from "prettier";` (or `require('prettier')`) in a web app. Please see the docs (https://prettier.io/docs/en/browser.html) to learn how to run Prettier in the browser.
