### ISSUE TITLE
Integrating with Linters documentation, ESLint, what's the correct order of extends array?

### ISSUE THREAD

**Issue by kas** [prettier/prettier#8353]
["Disabled formatting rules" describes adding "prettier" to the end of the extends array.](https://prettier.io/docs/en/integrating-with-linters.html#disable-formatting-rules)

[A little bit further down in the ESLint section, "Recommended configuration" describes adding "plugin:prettier/recommended" to the extends array.](https://prettier.io/docs/en/integrating-with-linters.html#recommended-configuration)

Is there a difference between which string appears last in the array? Should we specify which string should be at the end of the array, since ESLint describes adding them both to the array?

**Comment by lydell** [comment]
Hi!

`plugin:prettier/recommended` comes from [eslint-<strong>plugin</strong>-prettier](https://github.com/prettier/eslint-plugin-prettier), while the first bit of the docs is about [eslint-<strong>config</strong>-prettier](https://github.com/prettier/eslint-config-prettier).

I’ve suggested removing/de-emphasizing eslint-<strong>plugin</strong>-prettier since it’s so confusing: https://github.com/prettier/prettier/issues/7828. I haven’t got around doing that yet, though.

You can see what the `plugin:prettier/recommended` config looks like here:

https://github.com/prettier/eslint-plugin-prettier/blob/cc2979b68258b8545931ce37168adfe17b1d3a7b/eslint-plugin-prettier.js#L109-L114

My suggestion would be to _not_ use eslint-<strong>plugin</strong>-prettier (see #7828) and only use eslint-<strong>config</strong>-prettier – see https://github.com/prettier/eslint-config-prettier for the most comprehensive documentation.

Does this answer your question?

**Comment by kas** [comment]
Thanks, this answers my question. I'm glad I'm not the only one who thought the documentation was a bit confusing here. I appreciate the suggestion to not use eslint-plugin-prettier.
