### ISSUE TITLE
Native ESM support

### ISSUE THREAD

**Issue by sosukesuzuki** [prettier/prettier#8772]
We have documents for ESM import on browser but it needs using some module bundler (e.g. webpack, rollup). (See https://prettier.io/docs/en/browser.html#es-modules)
I thinks we should have native ESM standalone bundled. I hope we can use Prettier like below:
```js
import prettier from "https://unpkg.com/prettier@2.0.5/standalone.m.js";
import parserGraphql from "https://unpkg.com/prettier@2.0.5/parser-graphql.m.js";

prettier.format("query { }", {
  parser: "graphql",
  plugins: [parserGraphql],
});
```
WDYT?

**Comment by Monchi** [comment]
I'll work on this

**Comment by sosukesuzuki** [comment]
Thank you

**Comment by fisker** [comment]
Browser version ESM support added, do we want close this? Or we want add  ESM support for Node.js too?

**Comment by sosukesuzuki** [comment]
When I created this issue, I intended to mention only the browser. But I is better to support Node.js ESM. Let's keep this open.

**Comment by hosseinmd** [comment]
Some modules moved to esm and plugins need to load as esm module, how we could do it?

**Comment by fisker** [comment]
My plan to ship native ESM module.

Bundle `src/index.js` as `index.mjs`.

In order to support `require('prettier')`: 
Add `index.cjs` as proxy to `index.mjs`, something like

```js
module.exports = {
  async formatWithCursor(...args) {
    const {formatWithCursor} =  await import("./index.js")
    return formatWithCursor(...args)
  },
 // ...
};
```

Problems need to solve.

1. `clearCache` should be `async` function to use `import()`
2. `doc.js` should ship both `esm` and `umd` version, and `index.cjs` `module.exports.doc = require('doc.js')`
3. `./common/util-shared.js` the same as above
4. `module.exports.version` easy one.

**Comment by fisker** [comment]
The next branch supports ESM now.
