### ISSUE TITLE
Wrong indents

### ISSUE THREAD

**Issue by iliakan** [prettier/prettier#8963]
Here's the demo in the playground: 
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhrBwEMraAJGVHAYUzgBKWKFDjkawADpQaNVgE8oYGuWEAKYI34AaGgHdmASxgAxCgLhVcMXTEOo4ELDBoBfAJQTps2ZChUXTTJKAEZdYJgAJjd6GlE9GgBZSypmAHM4HgALZhE4HDV3AG5vHwB6Mpp8AEcsMXkAZXy4MBgKNQByAGIScjgAN0M4PQB1CgBrMUTc9LETcmYHDvdS2RgswypCPFR8P3hYEcMoDAg9fDIA5LZZtVWfKRkfZ8hUVFyMbXvn1JOAIwgRC+T2esgMxjM5AsVhwNm+PjsDiccJBPlcwNBNA6ACoOhjQQBtCKRAC692K0lKrmkrhA2hAEBIdmgVGQoGY5HIZwAChyEKyUMwcAZ5Kz6X8FmBJjAGiRmGBjmlkDBVHB6VkuDgRht4FQ5WA4E1-MZDIMYPJkOA2HSQMcqGIYNyFml3sgAGZC+30gBWVCIACFJdKGos4AAZY5wd2etUgX1EBqKvAARSwEHg0ZwXpAcvI9vIlr+zD++RtvWOMCOGHWyAAHAAGem9CD2kYLEiW3qWMT9KP02rpuBOxkCkCsAC0ojgGGnNr6tUMfSd6VdSA9Wdj9tQhmVqvpVCTcFTg8z2ZgxarNaQkXpKqMOEVfDezEtlgArDasPaACrFgXr7N+jqABJE4EBlMByEMJkAEETgac08FPWMFigDIEI5GBkBCAAWAA2elUIyABRE5sIATnrVxXCAA

Try to format and you'll see the problem.

The issue is a spin-off of https://github.com/prettier/prettier-vscode/issues/1473

You can also find some details there, but the playground is self-descriptive.

**Comment by evilebottnawi** [comment]
I think it is fixed in master

**Comment by fisker** [comment]
Yes, fixed by #8410

**Prettier pr-8410**
[Playground link](https://deploy-preview-8410--prettier.netlify.app//playground/#N4Igxg9gdgLgprEAuEBbCATArgGzgOjgA8AHCAJxgGcACAXhrBwEMraAJGVHAYUzgBKWKFDjkawADpQaNVgE8oYGuWEAKYI34AaGgHdmASxgAxCgLhVcMXTEOo4ELDBoBfAJQTps2ZChUXTTJKAEZdYJgAJjd6GlE9GgBZSypmAHM4HgALZhE4HDV3AG5vHwB6Mpp8AEcsMXkAZXy4MBgKNQByAGIScjgAN0M4PQB1CgBrMUTc9LETcmYHDvdS2RgswypCPFR8P3hYEcMoDAg9fDIA5LZZtVWfKRkfZ8hUVFyMbXvn1JOAIwgRC+T2esgMxjM5AsVhwNm+PjsDiccJBPlcwNBNA6ACoOhjQQBtCKRAC692K0lKrmkrhA2hAEBIdmgVGQoGY5HIZwAChyEKyUMwcAZ5Kz6X8FmBJjAGiRmGBjmlkDBVHB6VkuDgRht4FQ5WA4E1-MZDIMYPJkOA2HSQMcqGIYNyFml3sgAGZC+30gBWVCIACFJdKGos4AAZY5wd2etUgX1EBqKvAARSwEHg0ZwXpAcvI9vIlr+zD++RtvWOMCOGHWyAAHAAGem9CD2kYLEiW3qWMT9KP02rpuBOxkCkCsAC0ojgGGnNr6tUMfSd6VdSA9Wdj9tQhmVqvpVCTcFTg8z2ZgxarNaQkXpKqMOEVfDezEtlgArDasPaACrFgXr7N+jqABJE4EBlMByEMJkAEETgac08FPWMFigDIEI5GBkBCAAWAA2elUIyABRE5sIATnrVxXCAA)
```sh
--parser babel
--range-end 190
--range-start 146
```

**Input:**
```jsx
module.exports = class HtmlCodeRunner {
  async run({ code, waitForResult, timeout }) {
    const { port1, port2 } = new MessageChannel();
    // .querySelector('#previewWorkerManagerFrame')
    this.elem.contentWindow.postMessage(
      {
        command,
        sandbox,
        waitForResult,
        timeout,
      },
      '*',
      [port2]
    );

  }
}
```

**Output:**
```jsx
module.exports = class HtmlCodeRunner {
  async run({ code, waitForResult, timeout }) {
    const { port1, port2 } = new MessageChannel();
    // .querySelector('#previewWorkerManagerFrame')
    this.elem.contentWindow.postMessage(
      {
        command,
        sandbox,
        waitForResult,
        timeout,
      },
      "*",
      [port2]
    );
  }
}
```

**Comment by iliakan** [comment]
So it was fixed in master, but not released yet? @fisker

**Comment by fisker** [comment]
Yes, please wait for `v2.1.0`
