### ISSUE TITLE
Support for Tabs

### ISSUE THREAD

**Issue by JedWatson** [prettier/prettier#908]
I know this was already discussed in #34 but after conversation with @vjeux where he said

> Can you open an issue for supporting tabs btw

... I am 😁 

We just applied prettier to a relatively fresh codebase and it switched from our company standard (tabs) to spaces. This caused confusion, conflict, and broken hearts.

I'm not going to reopen the discussion of whether tabs are a good idea, but since they're a well established part of our project standards across _hundreds_ of repos, including that we have programmers who prefer 2 or 4 spaces and like being able to choose, I think tab support for prettier would be a massive improvement and significantly help ease adoption into existing projects.

re line character count, I think that for users with tabs it would be safe to assume a tab is 4 characters for wrapping purposes. 8 will wrap too aggressively, and many* editors default to 4 spaces when displaying tabs.

If people want more precise line wrapping rules, they can always use spaces :wink:

re "but you can reformat the code however you want then format it back when you commit it", that's maybe a thing that could happen, but seems super awkward as a primary workflow to enforce imo.

**Comment by vramana** [comment]
I think you should checkout [prettier-with-tabs](https://github.com/arijs/prettier-with-tabs).

**Comment by JedWatson** [comment]
@vramana I did and with full respect to the work that's gone into that, running from a fork doesn't feel very good. Projects like this are ambitious and long term, and forks are a whole lot of work on top of that with no guarantees they won't end up divergent or broken by changes to the main project if it doesn't embrace what the fork is trying to achieve.

For that reason, despite the spaces we've gone with the vanilla / official `prettier`, and I hope the team will be open to supporting tabs as a first-class option.

**Comment by vjeux** [comment]
I'd like to respond to this in more details (but I'm going to sleep right now...)

**Comment by bakkot** [comment]
> it would be safe to assume a tab is 4 characters

[Still](https://github.com/prettier/prettier/issues/34#issuecomment-271678154) disagree with this. For what it's worth, 8 characters is also the default [on the web](https://drafts.csswg.org/css-text-3/#tab-size-property). I don't know that I object to supporting tabs per se, but I do object to treating them as if they're necessarily 4 characters wide.

That said: prettier is opinionated. If you have an existing code base with a consistent style which differs from prettier's style, and don't want to switch to prettier's, I'm not sure that prettier is the right tool.

**Comment by blargity** [comment]
@bakkot, would it help if treating them as 4 spaces were a default that could also be configured?

**Comment by bakkot** [comment]
@blargity, it being configurable would solve the particular issue I'm raising, yes.

**Comment by rhengles** [comment]
@JedWatson I know what you mean, I also hated it when StandardJS required a fork to have an option to insert semicolons. 😃

**Comment by jlongster** [comment]
We're a bit short on time to work on all the requested features for prettier right now, but I'll say that we mainly wanted to focus on real bugs in the early stages of the project and see how it feels later. Now that we're a little further along, I think we've realized that the core contribution of prettier is it's ability to structure code wisely, and we're more open to tweaking small things like tabs.

I'm still unsure of how this will work out in practice. We'll need to make sure that two team members don't accidentally get different breaking behavior as a surprise because prettier somehow was measuring tabs differently.

> re "but you can reformat the code however you want then format it back when you commit it", that's maybe a thing that could happen, but seems super awkward as a primary workflow to enforce imo.

Once you are working on several projects that are formatted with prettier, I think you'll be surprised at how elegant this will be. In the long term I think you'll see this happen. If the project is formatted with prettier, that means you can always format it back, and I'm already doing this with other projects. They use single quotes while I use double quotes, etc. It's incredible to just dive in, make my changes, and then when committing a git hook reformats everything back automatically.

I know it's a bit different of a workflow, but once you start using prettier, you'll see how viable it is.

With that said, we can look into what it would take to do tabs again.

**Comment by lydell** [comment]
@jlongster How do you diff if you've temporarily switched all single quotes into double quotes?

**Comment by rhengles** [comment]
I've just sent a PR to be considered in this discussion. Thanks 😊

**Comment by JedWatson** [comment]
Thanks @jlongster, really appreciate that you're open to this 😄

> I think you'll be surprised at how elegant this will be. In the long term I think you'll see this happen.

💯 looking forward to it!

In the meantime, sounds like adding a `useTabs` option, and continuing to use the `tabWidth` option to control how many characters are counted for line breaks would resolve most concerns - @rhengles by my read on your PR, that's how it behaves right?

@jlongster could you elaborate on:

> We'll need to make sure that two team members don't accidentally get different breaking behavior as a surprise because prettier somehow was measuring tabs differently.

Would those config options solve for this? The way I understand it, two people could have different `tabWidth` and `printWidth` settings and that would cause different breaking behaviour too?

**Comment by rhengles** [comment]
@JedWatson Yes, it calculates with `tabWidth` even when using `useTabs: true`.

@jlongster Don't spend too much effort trying to protect the users from themselves 😃 - if the code still runs correctly, a different breaking behaviour is a minor issue and should be fixed in their configuration. They aren't complete morons! 😆

**Comment by lydell** [comment]
@josephfrazier That's really cool!

**Comment by rhengles** [comment]
Support for tabs in `Prettier` has been merged in #1026 🎉

**Comment by bakkot** [comment]
@vjeux I think this can be closed?
