### ISSUE TITLE
HTML: trailing semicolon in style attribute

### ISSUE THREAD

**Issue by Mister-Hope** [prettier/prettier#9101]
https://github.com/prettier/prettier/pull/8013 is `locked as too heated and limited conversation to collaborators`

It 's moving the trailing comma in inline HTML tags, while it 's conflict with stylellint rule [declaration-block-trailing-semicolon](https://stylelint.io/user-guide/rules/declaration-block-trailing-semicolon#declaration-block-trailing-semicolon) (https://github.com/stylelint/stylelint/issues/4909)

While I believe there must be some people who likes this change, while at least @pablomaurer @fisker and me dislike it and we all think that a dicussion is better.

I am not sure if it is a breaking change, but a trailing semi in style tags is reasonable (just like the trailing commas). I think at least providing an option will be better (just like the option "Trailing Commas").

**Comment by thorn0** [comment]
> but a trailing semi in style tags is reasonable

Reasonable? What is the reason?

> (just like the trailing commas)

The current behavior fully matches how trailing commas work.
Trailing commas aren't used if the expression fits on one line because there is no reason to use them in that case.

**Comment by thefoxie** [comment]
Because this change broke prettier in my case. When I run project with/since 2.1, it won't build because there's trailing semicolon, but when I delete it the eslint (with prettier plugin) says `insert ;`, thus it changes it back (inserts the semicolon back) on save automatically. Either make sure you follow same rules everywhere or don't force them.
