### ISSUE TITLE
[RFC] Editor Integration

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#918]
Editors are the main place where we want people to use prettier, in order for it to be a great experience it should have the following properties:

- Use the version of prettier that the project uses. If not, fall back to an arbitrary version.
- When saving, use the options specified by the project, otherwise fall back to an arbitrary configuration.
- When reading a file that is inside of a project using prettier, and if an option is enabled, reformat the code using the local user preferences.

## Proposal

Allow people adding their configuration options inside of prettier in `package.json`:

```js
{
  ...

  "prettier": {
    "bracketSpacing": false,
    "trailingComma": "all"
  }
}
```

## How to find a package version of prettier?

Given a file with a path `a/b/c/d/e.js`, we want to crawl up the tree up until we find a file `package.json`.

It should check in this order:

- `a/b/c/d/package.json`
- `a/b/c/package.json`
- `a/b/package.json`
- `a/package.json`
- `package.json`

If it doesn't find one, then the file isn't inside of a prettier repo.

If it finds one in `a/b/package.json`, then look at the file `a/b/node_modules/.bin/prettier`. If it finds one, then use this prettier binary.

## How to deal with caching?

This is a fair amount of io to be done for each invocation. If you want to add caching, you want to be careful, here are the things to watch out for:

- `a/b/package.json` is updated
- `a/b/node_modules/.bin/prettier` is updated
- `a/b/c/package.json` or `a/b/c/d/package.json` is created

## How to find the configuration associated to a package version of prettier?

Given that a package version of prettier is always in `a/b/node_modules/.bin/prettier` and the package configuration is always in `a/b/package.json`, we can inside of prettier check if `../../package.json` exists, and if it does read it and use the prettier key.

If prettier is being used as a CLI with `require('prettier')`, I'm not sure how to find it and if it's even a good idea to.

## How do you resolve conflicting rules?

I suggest that we merge rules one by one and the order they are loaded in/override each other is:
- First load `package.json` rules
- Then load CLI arguments which override the one above

For example,

```js
// package.json
{ "prettier": {"trailingComma": "all", "singleQuote": true} }
```

```js
prettier --trailing-comma es5 --parser flow
```

would result in

```js
{singleQuote: true, trailingComma: 'es5', parser: 'flow'}
```

## How to make it fast?

Because all the integrations now have to use the cli and can no longer just use the local require version, we're going to pay js/node startup time on every single invocation.

I recommend adding an option to prettier bin `--json-rpc`. With this, you can open the prettier process once and send formatting commands through stdin/stdout without having to restart it every time.

A sample connection looks like this:

```js
-->
Content Length: xxx
{"jsonrpc": "2.0", "method": "format", "params": ["abc", {"trailingComma": "es6"}], "id": 1}

<--
Content Length: xxx
{"jsonrpc": "2.0", "result": {"formatted": "abc;", "error": null}, "id": 1}
```

## Conclusion

Let me know what you think :)

**Comment by vjeux** [comment]
cc @jlongster @robwise

**Comment by robwise** [comment]
Wow, great work writing all of this up.

> How to find a package version of prettier?

This is something a number of users are requesting on prettier-atom. We haven't implemented yet, but what you're describing sounds about right to me.

> If prettier is being used as a CLI with require('prettier'), I'm not sure how to find it and if it's even a good idea to.

I believe @kentcdodds solved this issue in a similar case where he needed to find the ESlint configuration for prettier-eslint. He solved it by optionally passing the filepath of the file as an option. Then the tool knows where to start recursively checking from.

> I suggest that we merge rules one by one and the order they are loaded in/override each other is:
>
> First load package.json rules
> Then load CLI arguments which override the one above

I vote for this also.

> How to deal with caching?

This is definitely something we will need to watch out for.

> How to make it fast?

Have we determined that performance is a problem? The `jsonrpc` thing sounds like a good idea when doing multiple files at once, but inside of editors, I assume the use cases are just to do the single file or even only part of the file.

**Comment by kentcdodds** [comment]
> How to find a package version of prettier?

Great way to do that is with [find-up](https://www.npmjs.com/package/find-up)

**Comment by lydell** [comment]
There's also [read-pkg-up](https://www.npmjs.com/package/read-pkg-up).

**Comment by SimenB** [comment]
JetBrains IDE (IntelliJ, WebStorm etc) issue: https://youtrack.jetbrains.com/issue/WEB-25077

**Comment by vjeux** [comment]
Previous discussions on the prettier repo: 
https://github.com/prettier/prettier/pull/753
https://github.com/prettier/prettier/pull/735

**Comment by millermedeiros** [comment]
One thing I added o esformatter was the concept of a [`root` config](https://github.com/millermedeiros/esformatter/blob/master/doc/config.md#root) to avoid merging other settings and to speed up the lookup a little bit (as soon as it finds a config with `root: true` don't need to keep looking up the file tree).

This is basically how I decided to implement it: https://github.com/millermedeiros/esformatter/issues/76#issuecomment-27878603 - cli options always take precedence (assumes user is overriding the defaults on purpose)

The whole user config logic is handled by the [`getRc` method](https://github.com/millermedeiros/esformatter/blob/master/doc/api.md#esformatterrcfilepath-customoptionsobject), I expose it so that plugins and other consumers can reuse it (see: [source](https://github.com/millermedeiros/esformatter/blob/master/lib/options.js))

The package version logic I do inside the [`bin` file using the `resolve` module]( https://github.com/millermedeiros/esformatter/blob/master/bin/esformatter) - it starts looking for the locally installed module based on the config file (if user provides one) or the `cwd`.

`jsonrpc` is a good idea (was going to do the same for esformatter but never found the time), I would implement it as a dedicated bin tho.

**Comment by bakkot** [comment]
Most JS I write does not live in an npm package, so this would do nothing for me.

I know that's kind of unusual, but I thought it worth mentioning - package.json is an npm thing, not a JS thing.

**Comment by gustavnikolaj** [comment]
Instead of implementing a JSON RPC protocol through stdin/stdout you could also just create a programmatic API like the one eslint has.

```js
var eslint = require('eslint')
eslint.lintText(text, options, callback);
```

Both [eslint](https://github.com/eslint/eslint) and [standard-engine](https://github.com/Flet/standard-engine)-based linters implement similar APIs. I wrote [a plugin for integrating standard-engine linters](https://github.com/gustavnikolaj/linter-js-standard-engine/blob/master/lib/worker.js) into Atom which use this API to implement a worker to avoid the node.js startup cost on each lint. 

It allows for the same separation as the stdin/stdout protocol, but is more flexible in my opinion, and probably a bit easier to do as well :-) It also won't rule out the stdin/stdout based solution, but rather be the first step to implement it.

**Comment by SimenB** [comment]
@gustavnikolaj that's only useful for JS editors (so atom and code?), not for emacs, vim, intellij, webstorm etc.

And prettier already has a programatic API, so those integrations can be done today

**Comment by gustavnikolaj** [comment]
@SimenB Oh sorry, I should have checked whether it was already there.

**Comment by vjeux** [comment]
We also need it for atom. It has chrome flags enabled that prevent doing eval(), so you can't just require a js file found in package.json. What the current atom editor plugin does is to use a specific version, which isn't ideal since you may have multiple projects using different versions.

So the workaround is to shell out and use stdio

**Comment by gustavnikolaj** [comment]
@vjeux `child_process.fork` can be used from within atom to sidestep the CSP that prevents use of eval. Had to do the same thing to be able to use the projects linter instead of bundling them in the plugin.

**Comment by kentcdodds** [comment]
Yeah, most atom packages that need to do this use `loophole`. In fact, `prettier-atom` does [this](https://github.com/prettier/prettier-atom/blob/95f3e0172ce8e92fd9693754439d9e16caa11699/src/executePrettier.js#L31) :)

**Comment by jondot** [comment]
@robwise I've bumped into performance issues stacking prettier with eslint --fix. While my mac holds up well and I don't really "feel" sluggish while typing in Vim (as I'm sure no one does with current macs) -- CPU does spike, the laptop heats up, and battery drains much faster.

Today, I'm using neoformat/ALE with Vim using `eslint_d` that spawns only once (like proposed here) and that results in lightning fast lints, and code formats. Out of the lot of the editors I use (VSCode, Atom, Vim) - Vim will take up the least amount of CPU and battery, although it does all integrations out of Javascript land (unlike Atom, for example).

I think using one `server` process or at least supporting that mode is a lesson learned for many IDE architectures by now, and I would personally welcome it even though there's no real 'proof' of lack of performance.

**Comment by robwise** [comment]
@jondot When you say you've run into performance issues stacking prettier with eslint, have you tried https://github.com/prettier/prettier-eslint? We have this integrated inside of https://github.com/jlongster/prettier-atom.

**Comment by jondot** [comment]
Yes, I've tried `prettier-eslint`. Even gave the whole thing another try after reading the thread here. The deal is that with Vim, the integration is running a binary, providing input and taking the output via stdin/stdout. However you look at it - we still incur the startup time and the big CPU spike of spinning up `eslint`. 

With `eslint_d` I finally found solace as it only spins it up once, and latency for linting and fixing becomes near (but not identical to) javascript-native editors such as Atom and VSCode.

I spent a bit of time trying to trick prettier-eslint to use `eslint_d` (essentially becoming `prettier-eslint_d`) however then I found that prettier and eslint would be too tightly integrated. I feel that it can take a few more hours to make the prettier-eslint coupling happen, which can be better than building a client-server architecture from scratch - however I ran out of time.

**Comment by danawoodman** [comment]
I'm sure it's been discussed, but what about a `prettier.ops` file (or  `.prettier`, `prettier.json`, `prettier.config.js`, `prettier.config`, etc) that contains the configuration options? It seems more standard in the JS world to use a config file versus putting configuration in `package.json` which seems a bit like it's obscuring the configuration/requiring developers to know to look there versus seeing the config file in the root of a project. 

Here is an example config `prettier.opts` (similar to `mocha.opts`):
```bash
--no-semi
--single-quote
--trailing-comma
es5
--write
"app/**/*.js"
```

I'm sure this has been discussed before but figured I'd throw the idea out here again.

**Comment by josephfrazier** [comment]
@jondot 

> I spent a bit of time trying to trick prettier-eslint to use eslint_d (essentially becoming prettier-eslint_d) however then I found that prettier and eslint would be too tightly integrated. I feel that it can take a few more hours to make the prettier-eslint_d coupling happen, which can be better than building a client-server architecture from scratch - however I ran out of time.

I'm working on a very similar project: [prettier_d](https://www.npmjs.com/package/prettier_d), which just runs prettier as a server (but without eslint).

> Would be happy to hear about any other altenative Vim configuration that gives out quick lint+fix results.

For linting, I'm trying out eslint-config-standard and eslint-config-prettier ([details here](https://github.com/josephfrazier/prettier_d.js/commit/a3543e7df10f49b6e2bf04fd54c55183d0e8337c#diff-e4403a877d80de653400d88d85e4801a)). Not sure if it alone is faster than anything you've tried, but you might be able to use it in concert with eslint_d to speed things up.

For continuous formatting inside the editor, I'm experimenting with using a local .vimrc file with some autocmds to format using prettier_d ([details here](https://github.com/josephfrazier/prettier_d.js/commit/89cdda8617c8cf7c37c3f6346febb2b5acfdce87)). I'm hoping to be able to move the autocmds into my global vimrc, but I need to make prettier_d clever enough to do nothing if prettier isn't actually intended to be used in the current project.

**Comment by aaronjensen** [comment]
@josephfrazier have you seen https://github.com/sbdchd/neoformat ? Also, it's certainly slower than prettier_d would be, but I'm currently using eslint_d with https://github.com/not-an-aardvark/eslint-plugin-prettier which seems to work well now that prettier has no-semi

**Comment by josephfrazier** [comment]
@aaronjensen Yeah, I'm using neoformat with prettier_d to speed things up a bit.

Now that I think about it, prettier_d might easily be replaced in this context by a combination of eslint_d, eslint-plugin-prettier, and eslint-config-prettier.

**Comment by davidtheclark** [comment]
If any of the reluctance to allow for configuration in standalone files (e.g. `.prettierrc`, instead of only `package.json` properties) comes from a reluctance to introduce into Prettier the complexities that would entail — any interest in considering [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) for finding and parsing configuration?

[stylelint](stylelint.io) uses cosmiconfig to find and parse configuration in `package.json` and standalone files, moving from a starting location up (down?) the file tree. It could also take care of the [global configuration question](#98), because we could put standalone configs in our home directories.

There may be room for performance improvements in cosmiconfig, but it seems to have been serving its purpose pretty well so far for stylelint. And if we can improve a package that other libraries do/can use, everyone wins.

Just an idea to consider. Thanks for working on Prettier!

**Comment by iamstarkov** [comment]
I want to introduce prettier to my colleagues in the office, but it will be hard without config. Because i cant control my colleagues' editor' plugins' configurations.

Config support will help me to maintain config per each project and let prettier-cli and relevant editors' plugins to get configuration from there.

Another usecase is to introduce prettier to my OSS projects, where contributors use all kind of editors, and i need a way to say to those editors' plugins which options of prettier i do use.

**Comment by iamstarkov** [comment]
Third, usecase i have different es5 and es6+ projects, and i want to use the same tooling (cli and pluins), so i can't use `--trailing-comma all` option in my editor plugin, because it would break my old project. Configs will help me a lot, because in old project i would be able to set `--trailing-comma es5` and nothing will be broken

**Comment by danawoodman** [comment]
I think it's pretty clear prettier should support some sort of local/global config file. I've created a simple little bash script that implements it that I called `prettier-with-options`:

```shell
#!/usr/bin/env bash

[ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

if [ -f prettier.opts ]; then
  prettier --stdin $(cat prettier.opts)
elif [ -f ~/prettier.opts ]; then
  prettier --stdin $(cat ~/prettier.opts)
else
  prettier --stdin
fi
```

Now just make it executable (`chmod +x prettier-with-options`), put it on your `$PATH` and then call it within your editor, in my case vim with Neoformat:

```vim
" Use prettier with custom config
autocmd FileType javascript set formatprg=prettier-with-opts

" Shared neoformat config
autocmd BufWritePre *.js Neoformat
let g:neoformat_try_formatprg = 1
let g:neoformat_only_msg_on_error = 1
```

This will always run prettier on any JS code so be aware of that. It would require a bit more work to only turn on projects that have a `prettier.opts` file in them but it's doable. Hope this helps someone.

**Comment by EvNaverniouk** [comment]
There are two important considerations that aren't being discussed that I want to ensure get considered as part of this proposal:

- Not all Javascript projects use a `package.json`
- If you want to share configurations, it is much easier to do so if you're passing around a prettier-specific file (ie. `.prettierrc`) than sharing a `package.json` that might have other project-specific stuff in it.

For those reasons (plus the ones already mentioned) I'd petition to have configuration in a dedicated file rather than inside the `package.json`.

I believe the problem if finding and caching the appropriate config is a problem that's already been solved by projects like `eslint` and `stylelint` and should be easily transferrable to `prettier`.

**Comment by azz** [comment]
`Prettyfile.json` :)

In all seriousness, a `prettier.opts` plus a CLI way to point to it could work.

**Comment by AxelTheGerman** [comment]
Any other tool in this category supports having a config file. There's probably half a dozen issues opened in this regard.

Correct me if I'm wrong but usually you would have any of the following files or use the default settings:
- `.prettier.config` in project root, or to make it simple in the current directory (assuming that you would run prettier from the root of your project?)
- `~/.prettier.config` (home directory)
- possibly even higher up across all users, but I think that's more common for system services such as nginx
Only having those few specific locations safes you the time to walk up the whole file tree.

Command line options are still nice for manually running a one of. Those would obviously override any configuration file.

Also as mentioned above, please make this available to projects that are not npm modules, event though most might be. But a dedicated config file is easier to copy to new projects and makes it more obvious where to look.

Need some examples? In my current project I see `.csscomb.json`, `.eslintrc`, `.rubocop.yml` and `coffeelint.json`. Also a `.ruby-version` to let rvm pick the correct ruby version for this project. In my home folder `.gemrc` for rubygems (which for example supports a `/etc/gemrc` for system wide configuration)


Please let's keep this discussion going. This is a key feature imho

**Comment by josephfrazier** [comment]
For anyone who wants to use `package.json` or `.prettierrc` *right now*, I've added support in my [prettier_d](https://www.npmjs.com/package/prettier_d) wrapper. You can put the JSON configuration in either `.prettierrc`, or as the `prettier` key in `package.json`, then run `prettier_d --pkg-conf [file]` and the configuration will be used. See the [documentation](https://github.com/josephfrazier/prettier_d.js/tree/226c1ebe91093fc8c642ffa0555bd7929acba470#configuration-file) for more details.

**Comment by jondot** [comment]
@josephfrazier very nice! i think it'll alleviate some pains around Vim.

Still, to update on my set up: there's still no polite way to use prettier on Vim (without thrashing CPU and lagging formats). Looks like I can't use eslint for linting such as unused variables, etc., and have prettier format code at the same time. So if I use `standard` rules for the former and prettier for the latter, it wouldn't work for some reason. I've tried all this with `prettier_d` and at some stage with `eslint_d`. 
I'll try again with your update, @josephfrazier.

**Comment by josephfrazier** [comment]
@jondot:

> So if I use standard rules for the former and prettier for the latter, it wouldn't work for some reason.

If you look at the [eslint configuration for prettier_d](https://github.com/josephfrazier/prettier_d/blob/f5d6a5fdba16b42049702f2c384a7604f6ea6437/.eslintrc.js) itself, I think I've gotten this working as you described. I don't have a Vim/ESLint integration set up, but I do use `prettier_d` to format it's own code as I'm typing, as you can see from the [local .vimrc file](https://github.com/josephfrazier/prettier_d/blob/f5d6a5fdba16b42049702f2c384a7604f6ea6437/.vimrc) (note that you need a Vim plugin like [vim-addon-local-vimrc](https://github.com/MarcWeber/vim-addon-local-vimrc) to use local .vimrc files).

Feel free to open an issue at `prettier_d` if you have any trouble/questions/suggestions. I'd love to get feedback!

**Comment by danawoodman** [comment]
@vjeux how about the following as a proposal?:

Command line looks for `./prettier.opts` then `~/prettier.opts` in the following order or a `-c/--config my.custom.prettier.opts`. The flag has highest priority and if non of the above match, prettier falls back to defaults. 

The `prettier.opts` file is read line-by-line into the prettier command line so people don't need to learn a new format or use some special file type (eg `.json`, `.yml`, etc). Plus a `prettier.opts` file is portable and can be moved to any JS project, even ones that don't have `package.json` files.

```shell
prettier -c myprettierconfig.opts
prettier --config myprettierconfig.opts
```

If this is acceptable, is a PR something that would be desired?

**Comment by AxelTheGerman** [comment]
@danawoodman would love to see exactly that!

**Comment by chrisui** [comment]
Been mentioned already but I would push for using something such as [cosmiconfig](https://github.com/davidtheclark/cosmiconfig) which implements the config formats commonly seen across the ecosystem. Imo it gives the most predictable way for writing and consuming configuration for tools in the js world.

**Comment by chrisui** [comment]
Is there anything we can do to help move configuration/editor support along?

We seem to be getting in a bit of a muddle moving around projects with tools using different prettier versions (global vs project vs tool/editor vs ci) and it's causing us some degree of pain.

**Comment by chrisui** [comment]
I reckon we should be able to specify the prettier `"version"` in the config (wherever it lives) so that if someone attempts to use prettier with the wrong version we can fail **loudly**. This is the same as happens with using the incorrect version of `flow` to what is specified in configuration.

**Comment by chrisblossom** [comment]
I think it is fairly important to be able to flag subdirectories with a new prettier config/overrides because not all JS features are supported per directory, specifically ``--trailing-comma all``. The current Node LTS's (4 & 6) do not support this feature. If using it, at least part of your build chain will need an exception of some sort.

IMO don't reinvent the wheel...copy how ``eslintrc.js`` works. Nested ``.eslintrc.js`` inherit from configs further down the line but overwrite any settings.

**Comment by vjeux** [comment]
Fyi, node 8 that was just released supports trailing comma!!

**Comment by chrisblossom** [comment]
@vjeux Yeah it will be nice when it is LTS in October! [nodejs/LTS#lts-schedule](https://github.com/nodejs/LTS/tree/a5b8bc19b5daee58618a034ae80f0b3d59e75df1#lts-schedule) has Node 4 supported until April 2018 and Node 6 until April 2019. 

Because Node's LTS, I don't think Prettier should adopt a configuration style that makes it more difficult to use until April 2019. I think the configuration decisions should follow the Node LTS schedule.

Here is my current configuration...
``.prettierignore``
```sh
.cache
.idea
.vscode
node_modules
build
static
flow-typed
flow
npm-packages-offline-cache
tools
```

``package.json``
```js
    "prettier": "find . -name \"*.js\" | grep -v -f .prettierignore | xargs prettier --tab-width 4 --single-quote --trailing-comma all --write",
    "prettier:tools": "find ./tools -name \"*.js\" | xargs prettier --tab-width 4 --single-quote --trailing-comma es5 --write",
    "precommit": "lint-staged"
  },
  "lint-staged": {
    "./*.js": [
      "prettier --tab-width 4 --single-quote --trailing-comma es5 --write",
      "git add"
    ],
    "tools/**/*.js": [
      "prettier --tab-width 4 --single-quote --trailing-comma es5 --write",
      "git add"
    ],
    "src/**/*.js": [
      "prettier --tab-width 4 --single-quote --trailing-comma all --write",
      "git add"
    ],
    "server/**/*.js": [
      "prettier --tab-width 4 --single-quote --trailing-comma all --write",
      "git add"
    ]
  },
```

Because of the "no configuration" philosophy, there ends up being more hacks/workarounds getting ``Prettier`` to work with a modern build setup. Not to mention the editor's plugin has no idea what config to use. End up having to run ``yarn run prettier:tools`` after saving any file in the ``tools`` directory if I don't commit right away otherwise the trailing comma will error node out.

If anyone has any suggestion on how to better handle this I'd love to hear how.

**Comment by josephfrazier** [comment]
@chrisblossom, since you're already using eslint, you could use [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) and [eslint-config-prettier](https://github.com/prettier/eslint-config-prettier), add your prettier configuration to `.eslintrc.js`files, then have lint-staged run `eslint --fix` instead of `prettier`.

**Comment by rattrayalex** [comment]
I'm a pretty big +1 to allowing `.prettier` config files, if for no other reason than that they function as great marketing on Github. But also because there are many times when there simply isn't a simpler way for people to use it. 

Sharing bash files or "always run it with args --x --y z" within a company really isn't wonderful, and package.json simply doesn't work in all cases.

**Comment by Ciantic** [comment]
Is this thread mostly about agreeing to filename (e.g. .prettierrc package.json) and format in it, like opts or JSON?

If so I think this should be decided by *one maintainer, just do it.* 

There is already a cottage industry of these non-standards, one example from VSCode extension here:

```
{
    "prettier.tabWidth": 4,
    "prettier.typescriptEnable": [
        "typescript",
        "typescriptreact"
    ],
    "prettier.trailingComma": "es5",
    "prettier.printWidth": 100
}
```

This is not good!  We need standard for this, such a simple thing should not be outsourced when in the end it's maintainers that decide these simple things.

**Comment by rattrayalex** [comment]
@Ciantic yes, I am planning on doing exactly that this weekend 😄 and it seems @azz has the same idea

**Comment by rattrayalex** [comment]
Alright, so regarding perf of finding the config file... 

I think there are two main uses of prettier (correct me if I'm wrong!): from the project root, eg in CI/precommit/manually/etc across a whole directory, or via an editor integration while writing. Obviously, the I/O overhead in the first case is probably-usually-fine, as long as it's done once per run instead of once per child file. The perf savings of finding the config file are only important (I take it) for the editor integrations. 

In that case, for editor integrations, I propose we just add a `--config-file` option, which takes a filepath, and when it is provided, use it without checking for others. Editors can then be responsible for caching/providing it. 

It would then presumably also be helpful to expose `prettier find-config FILEPATH` or similar, so that editors don't have to find the config files themselves (and thus keeping it consistent across editors). 

I think this will address the perf concerns while keeping the code within `prettier` quite simple (eg; we can just use cosmiconfig or whatever). 

Thoughts?
