### ISSUE TITLE
Wrapping not working when using placeholders with Styled-components

### ISSUE THREAD

**Issue by tu4mo** [prettier/prettier#9215]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/?source=post_page---------------------------#N4Igxg9gdgLgprEAuEcAeAHCAnGACSKAZ3wGUYBPAGzgBMBhCAWyygXwF48Tq6A6WgEsAbgAMAOlD5VoAczBUAhkSJRFTOHj6KoEGAAs42GVHlKVajVopwYOvYeNyFy1es3aqRCIoCOAV0F4EzNXS01gSUkAXyioABJgABk5ADl3AHkAMwBBcl4GZlZ2aLxElNN0jWy8yhpClmgSsuS0zNz8+sZGtlhS8rbqjrq6buK+vEioGMlREAAaEAgMGEFoImRQRWxsCAB3AAVthA2URSo9xQoNxYAjbEUwAGtbUgxHwVNkGGx-OEW4ExbnRaHQkjpZP5FLI4AAxHBMRQwVZfM7+GAQBYgfQwJhUADq+iCcCI7zAcFIJyCIiCFGQ4BUWM+RCMMAOD1kiOQWXOLMWACsiGgAEIPZ6vdxJT5wbm8-4gQVoUifWQ0ACK-j0MqQPK88ve2BZ2HplAwJLA2EEKyxGEtsHxgloBmQAA4AAyLW0QFn4h4Yem2klGYQyxYBLXs5anEDKAC0bDodCx2DgAUEKfZ0K5OrlixZTEE31+8qIKvVmvgsr1izstwdTv0yAATDWHoIqCrutnUEQAKxY-wsgAqilup11fJAwj+AEkoKDYKQLVaYDl551tRO4NFokA)
```sh
--parser typescript
```

**Input:**
```tsx
export const StyledComponent = styled.div`
.longclassname .anotherlongclassname .yetanotherlongclassname .alsoaquitelongclassname {

}

${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} {

}
`
```

**Output:**
```tsx
export const StyledComponent = styled.div`
  .longclassname
    .anotherlongclassname
    .yetanotherlongclassname
    .alsoaquitelongclassname {
  }

  ${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} ${LongNameOfAStyledComponent} {
  }
`;

```

**Expected behavior:**
Wrapping similar to when not using placeholders.

**Comment by thorn0** [comment]
Prettier can't know whether these substitutions are expected to be formatted as class selectors.

But let's suppose Prettier made such an assumption. After all they are all on the same line and separated with spaces, right? So why not? Okay, let's wrap them like normal class selectors:

```js
export const StyledComponent = styled.div`
  .longclassname
    .anotherlongclassname
    .yetanotherlongclassname
    .alsoaquitelongclassname {
  }

  ${LongNameOfAStyledComponent}
    ${LongNameOfAStyledComponent}
    ${LongNameOfAStyledComponent}
    ${LongNameOfAStyledComponent} {
  }
`;
```

However, what about the next run of Prettier? Now it's become even more difficult to tell what the substitutions stand for. They look like they can be anything. E.g. rules. Or multiple rules per substitution. We can't tell at all. That's why the current behavior makes sense.

I'm going to close this. If anybody has thoughts on how this can be improved, feel free to write here or open a new issue.
