### ISSUE TITLE
Inline comment issue with `html` tagged template

### ISSUE THREAD

**Issue by stephenwade** [prettier/prettier#9274]
If I use a template tag called `html`, Prettier moves my inline comment outside of the curly braces. This does not happen if I change `html` to another function name.

---

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAnOMCuqoAIAWMAtgDYAGAOnrgDwAmAlgG4B8VuHuAJMDPgwGcAdAIy4AZONx9BIjEICGqGIJjtOAegBUuBUwgM6uSFAEQScXHFSoIqAbgYAzXGRnDRMMo4eYodOCcGKDgjLQ0AX3UaDUZWKjIAbioQABoQCAAHFWgBZFAlWwB3AAUlBDyUBRIihQBPPPSAI1QFMABrDABlTLbggHNkGFRMOHS4IibQgLoAGQUofswFfrgAMTsiBRgVReQQBUwYCDSQQlIAdX54AV6wOC6KhhUmZ7r9sAFGkGDRZRLWv0tsgnNVROkAFYCAAeACFWh1ugoiHBZsE4CCwWMQFDoV0BhYAIqYCDwTEkcEgXr2az7JoKKYkU6ZVDBGAXQx8ZAADgADOkWRBRBdWpl9iy4H8mBj0gBHEnwAFZSoHAQAWhCoVCp3Q8oY6ABK2BSFBFOxoiIDCGI3NBLgxNJGJNWPSMAZHLoXKQACZXa0GCQBgBhCBEY0gSUAVlOmFEABUGZVTZSmKMAJL+BAwLpgVnZACC-i6MDqFnJogiESAA)
```sh
--parser babel
```

**Input:**
```js
return html`
  <div>
    ${this.set && this.set.artist
    /* avoid console errors if `this.set` is undefined */}
  </div>
`;

```

**Output:**
```js
return html`
  <div>
    ${this.set && this.set.artist}
    /* avoid console errors if `this.set` is undefined */
  </div>
`;

```

**Expected behavior:**
```js
return html`
  <div>
    ${
      this.set && this.set.artist
      /* avoid console errors if `this.set` is undefined */
    }
  </div>
`;

**Comment by thorn0** [comment]
Turns out this bug is really old. Reproduces even on prettier@1.16.0. Happens with `css` and `graphql` too:

**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBzATgQwA4AsCOANgAYA6UABFRQCTAy4CWAzgHTNwwUBk3FDLdp1aZ0MFjHLUKAegBUFTADcIjACYVIUZhEJwKcdOgjpmFRgDMKxAWw4xi5swFcoauBcZQ4GuTIC+5MQA3OQgADQgENji0MzIoKLGAO4ACqII8SiYhMmYAJ7xkQBGWGAA1pwAytiYYF6oyDDoznCRcAC2xT7uagAymFCozpiocABiJh2YMOJDyCCYzjAQESC4MB2EAOpM8My1YHBVmYziSmf5C2DMRSBeHGKpWKjTyBY5HJEAVswAHgAhMqVGBVTAdOB9Lxwd6fNogX5-KoNPQARWcEHgsMIXxAtVMhgWxUw3UIa2w6C8MG26gYyAAHAAGSIUiAcbZYbALClwR5KGGRfAY+DPaJZRbMAC03h8PjW6DgQsYCueozeSA+OPhHA6jCaLW1KLg6MxMI1cMiMBJNLUdKQACZLVhGIQGgBhCAddUgXkAVjWzg4ABUSVlNbilK0AJJuBCgsCUmIAQTcVRg+T02I4-n8QA)
```sh
--parser babel
```

**Input:**
```jsx
graphql`
    ${this.set && this.set.artist
    /* avoid console errors if `this.set` is undefined */}
`;

```

**Output:**
```jsx
graphql`
  ${this.set && this.set.artist}
  /* avoid console errors if `this.set` is undefined */
`;

```
