### ISSUE TITLE
Prettier gives error when using interface variable name in JS file

### ISSUE THREAD

**Issue by mahdi-farnia** [prettier/prettier#9326]
**Prettier 2.1.2**
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAVOAnAWwEsoBDAG0wF5M84BHAVyLoAoByAOk4Hp2BKADQAdKJlqUadJizgc6pACbkScAQG5RoyFAyYS8PADNSYONQmcwC+AElY+E2dbBR4kgAdGMJJg94IMzQ0TgxFEhExTAhvLx8-AKCQsJiYUQBffk0obXQsGFI0AGs0C1xCEgpORjQ4AEEoAE86vABzFzdMNFJG1m5OAjRW-kxXKPEdNAhyOE5yCFbOUg8Pcl6ANwgiRUwABkFMQeHs8XTI8TICOUu4EbHxCfRp2fn29gJGzBv9UvZMAGovqQrllOukMqCclBJvl8MQyJIvnAAO44OGVcisArFNCQ3K6fKFIpldEIqw2OAAYQgBAIjCgRDApBgRGgWNJFDxsCJnDZ7AQinYBxcXUYYCSB2RAAtGVLMJlqAA+UadSbPOYLVidcQAA2EbmwRN8ABJgNLZelMMjCphTWgxUlMAB+TDse3iuDBIyMch-XzsKAQLDupLe33g0R6qKQzLZUQGRymWZMT0svkAUQceEw1NppCgiiQ+qgQswrHzIyoyvumEM8KqcAAHnAwOWoDHISBBCAIB407pkKBSHgAsiAArDhBoZAgCjWxrT7sAIzwpiKcBgAGUPKYSK1kDA8Iw4N24AQl3BFIpLwAZfOtRikVpwABiEEIzJZUH3KFI3ggXYgFKMAEOQADqMrwGgO5mJuU5ECy6wIY0M5gMEgEkLUeAwGOq6tAQpDICY5C1N2ABWaCNgAQquYDrluwJwDeqhERQpEgBRjabnuMwAIqMEGcCsSRJ4gDueBYTOS6kBe5CAf4BhgdsMBSsgAAc+xiQEtRgauHgzv4nr4OsQndkwgm4b206-mgAC0UBwJel6AdIzB0LhT4EcJ7G1MQB5HqJaA8XA-GCd5okFEuSmKCpyAAEzdoepBECo365l5KCegArIBNRwIaS7WcR7HrMe9jXrAm7WEQfYNIom4wI0Mzhek6RAA)
```sh
--parser babel
```

**Input:**
```jsx
const Terminal = require('../'),
  rl = require('readline');

const interface = rl.createInterface({
  input: process.stdin,
  output: process.stdout
});

const tasks = Terminal.useAnyArg({
  say(...msg) {
    console.log.apply(void 0, msg);
  },
  name(name) {
    console.log('my name is ' + name);
  }
});

const terminal = new Terminal(tasks);

const task = Terminal.createCommunication(terminal);

task.on('end', ({ success, which }) => {
  console.log(
    `\n Task: ${which} was ${success ? 'successful' : 'not successful'}\n`
  );
});

interface.question('Enter Command:\n', (an) => {
  terminal.exec(an);
});

```

**Output:**
```jsx
SyntaxError: Unexpected token (28:10)
  26 | });
  27 | 
> 28 | interface.question('Enter Command:\n', (an) => {
     |          ^
  29 |   terminal.exec(an);
  30 | });
  31 | 
```

**Comment by kachkaev** [comment]
A similar error is shown in the babel parser, because `interface` is a reserve word. See [your code listing in the Babel REPL](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAKgUwE4FsCWYCGAbGBeGJBARwFc0iAKAcgDpaB6agSgBoAoGQ3AosihDSKYAJtgwIWAbnbtQkWBijIAZpmAJ83WsGHKAkmGVI1GygG9OMDAAdSUAFwwbSEBogRa0ERg5cQ9naOzq7unt4BUOwAvswycuDQMFCYEADWEFqIqBg4tKQQCACCYACeRUgA5hZWEJillPS0KBCVzDCWXFzyECDYCLTYIJW0mDY22A0AbiBoIjAADKwwLW0yXNF-MFgogjsI7Z1dPX0DQ9XUKKXbmLvWmdQwANQ3u3FW0THvCQrJyOhYHjbBAAd3g_1y2EoKXSEG-PVgMLSWQhgJ0egQAGEQCgUKQwGhgJgoGhwNDUThvkjaGTqAgwCJqMsLDAIKRgGFliCABaE7kwWL4AB8HSsJ36g2GlCsXAABgAdMDwVJpJwAEnMPL50RgINSMA1bI5CA8MAA_DBqEawipSNhHk5qGAQLBrSaILb7dFFbKrO9YvElKp1AMyCaSbSAKJGZAwbG4zAMhyKpkwSiJ9p4EVHYwAvIIAAeCGA6bA_riQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=).

```txt
/repl.jsx: Unexpected reserved word 'interface' (4:6)

  2 |   rl = require('readline');
  3 | 
> 4 | const interface = rl.createInterface({
    |       ^
  5 |   input: process.stdin,
  6 |   output: process.stdout
  7 | });
```

Also worth checking [JavaScript Reference → Lexical grammar → Keywords](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords). `interface` is listed under _Future reserved keywords_.

**Comment by sosukesuzuki** [comment]
However, I wonder why Prettier throws syntax error that says `SyntaxError: Unexpected token (28:10)`. I think It should say `Unexpected reserved word 'interface'`.

**Comment by sosukesuzuki** [comment]
I created a issue to babel repo: https://github.com/babel/babel/issues/12153
