### ISSUE TITLE
FR: no space after `if`, `for`, `while`, `switch` and `function` in JavaScript

### ISSUE THREAD

**Issue by stla** [prettier/prettier#9347]
Hello,

 I am a fan of such a formatting:

```js
if(x == 2) {
  return 3;
}
```

And not:

```js
if (x == 2) {
  return 3;
}
```

So I would like an option to request no space between `if` and `(`. As well as no space after `for`, `while`, `switch`, `function`.

**Comment by kachkaev** [comment]
Please see https://prettier.io/docs/en/option-philosophy.html

**Comment by stla** [comment]
Ah ok, thank you. Then I will do it myself, with a `replace`.

**Comment by kachkaev** [comment]
That's an option, yes. Alternatively, you can choose to switch to the Prettier’s opinionated style and no longer worry about this problem ever. This will be a bit painful for the first couple of days, but you'll be surprised how quickly your eyes will get used to the new style.

Because Prettier is used very widely, syncing your project’s style with the Prettier’s one will mean that you'll be looking at millions of open source files as on your own, while people from the whole world will find your code familiar. This reduced barrier in collaboration is definitely worth a slight discomfort for a couple of days 🙂 And no `replace` step as a bonus too!

Feel free to close this issue.

**Comment by stla** [comment]
Thanks.
