### ISSUE TITLE
Array line breaks don't work the same as objects?

### ISSUE THREAD

**Issue by radiosilence** [prettier/prettier#9391]
This seems like a feature that allows the user to indicate how something should be formatted using a linebreak.

Current behaviour:

Input:

```ts
const blah = {hi: 1, ho: 2   };
```

Output:

```ts
const blah = { hi: 1, ho: 2 };
```

Great so far, one line, no line break after `{`

Input:

```ts
const blah = {
  hi: 1, ho: 2,
};
```

Output
```ts
const blah = {
  hi: 1,
  ho: 2,
};
```

Amazing! I get to choose (unless it would be too long-a-line) by putting line break after `{`.

So why with arrays:

Input: 
```ts
const x = [ 1,
  3, 2];
```
Output:
```ts
const x = [1, 3, 2];
```

Sweet, it put them on the same line as there was no linebreak after the `[`.

Input:
```ts
await Promise.all([
  await delay(1000), 
  needsFetch ? await playable.fetch() : true,
]);
```

Output:
```ts
await Promise.all([await delay(1000), needsFetch ? await playable.fetch() : true]);
```

Oh no! It's mangled it despite me having a line break after `[` :(

This would be really handy for doing things where you explicitly want stuff to be separated by line,  because it helps readability.

Currently you have to add a `//` or `// prettier-disable` comment which is horrible as we shouldn't really need to be talking to prettier in our code.

```ts
await Promise.all([
  await delay(1000), //
  needsFetch ? await playable.fetch() : true,
]);
```

What I'm asking is if we have this great behaviour for one thing (objects), why can't we have it for another thing (arrays)?

**Comment by radiosilence** [comment]
[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuc0DOMAEAPTBeTYTAQyUwEYAaTAIzICZMBfAbgB0pIoNMBPfQh0wkyVIbQaUOTDhy48AXgIDaVTPQC67TuizEV4sVGH0OGkJRAQADjACW6ZKGIAnFxADuABVcI0yEGIAGw9iXn9LGhdiMABrOBgAZWsYuygAc2QYFwBXOEs4AFsaOAATUrKAGWIMnOJ0uAAxCBdC4hh7DIDiHJgICxAACxhCoIB1Qbt4NBSwOES-KbsANyneALA0CJA0tDgXGC9o9LbkADNgvcsAKzRsACFouITE4kK4SrS4c8v8kFvsIk0ukgnAAIo5CDwH5BK4gFIuPYuAI0YglIIDawuNIwMZ2UowQbIAAcAAZLFiIHsxtFrAEsXAkctvpYAI6Q+BHGz+FDENAAWigcDKZQGLjg7Ls4qO9VOSAusL+e0KdiyuSVwNBEKh33lv0sMDReIJRKQ9AN0TsQWBAGEIIU5SBGQBWAY5PYAFTRPIVcOWeQAklAKrBEmBsbYAILBxIwXigmF7JhMIA)

**Comment by thorn0** [comment]
> Amazing! I get to choose

Leaving formatting choices up to the user is exactly opposite to what Prettier as an automatic code formatter is for. Object literals in this regard are an exception and, in a way, a fail because a good enough heuristic for a fully automatic programming couldn't be found. [Read more](https://prettier.io/docs/en/rationale.html#multi-line-objects). There is no plans to add more workaround like that. The only way forward is to decrease their number. E.g. in feature versions of Prettier line breaks will be preserved not in all object literals, see #8055.

And last but not least, these exceptions cause all sorts or problems for Prettier's core algorithm as it wasn't originally meant to support such tricks. E.g. [another tricky problem](https://github.com/prettier/prettier/issues/9390) caused by object literals was reported just today.
