### ISSUE TITLE
Exponentiation operator is overly aggressive at parenthesing

### ISSUE THREAD

**Issue by vjeux** [prettier/prettier#951]
```js
t.v ** 2
```

is converted to

```js
(t.v) ** 2;
```

https://prettier.github.io/prettier/#%7B%22content%22%3A%22t.v%20**%202%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D

**Comment by vjeux** [comment]
cc @bakkot, I know that there are special rules on the standard for this, you may be interested in taking a look.

**Comment by bakkot** [comment]
Yeah, the [logic](https://github.com/prettier/prettier/blob/f5ede513eb458ff8fe43bf08dd0a54f3d3f036f9/src/fast-path.js#L235-L246) is currently pretty wrong. Will try to put together a fix sometime today.

**Comment by bakkot** [comment]
A much more serious issue is that it treats `**` as left-associative:

```js
(a ** b) ** c
```

should not [codegen as](https://prettier.github.io/prettier/#%7B%22content%22%3A%22(a%20**%20b)%20**%20c%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22%22%2C%22doc%22%3Afalse%7D%7D)
```js
a ** b ** c
```
since that is actually equivalent to
```js
a ** (b ** c)
```

I'll fix this too.

**Comment by vjeux** [comment]
oh wow, this is bad indeed
