### ISSUE TITLE
Double ended sentences

### ISSUE THREAD

**Issue by FayeGibbins** [prettier/prettier#9810]
How do I stop prettier converting "The ball is red.  The ball is round." to "The ball is red. The ball is round." please?  It's currently replacing all my double ended sentences with single spaces in my markdown files (.md) and I can't find an option to stop it.

PS the double space is evident in the source of this message.

**Comment by fisker** [comment]
I don't understand the problem.

Please use <kbd>Report issue</kbd> button on [this page](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAVAFnABAIwIYA2BWAlgM5YBOcAJgHRYbb5GkWUQCuU9IANCAgAHGCWhlkoPJQ4B3AArSEElIVl4AnhIE5KeMAGs4MAMpD9JKAHNkMSpzgC4AWxy0atADJ5rnPFbgAMQhKZzwYUWtkEDxOGAh+EHQYZwIAdXQSeDJzMDgTZSySADcsjWiwMm0QSzI4Shh5PSsw5AAzQjqBACsyAA8AIT1DYxM8ZzhPSzh2zscQXr6TSysCOABFTgh4WYIukHNKOsposMoDGghZKEShSksYNJIaGHRkAA4ABgE7iDq0vRCaJ3ODHYozAQARy28CawhUMTIAFooHBaLREtRoSRqE1-K0kB09vM6s4SLZ7CSVmtNtsZoS5gIYHgcE8Xm8kAAmJl6EgEFYAYQgzgJIFBAFZEpw6qgWSoiftig4AJI8BCmMD3EQAQR4JhgGjWuzqAF8TUA) to report it.

**Comment by thorn0** [comment]
The OP means that 
```
The ball is red.  The ball is round.
```
is printed as
```
The ball is red. The ball is round.
```
This behavior isn't configurable. See here: https://prettier.io/docs/en/option-philosophy.html

**Comment by vermiculus** [comment]
From the above, I'd like to re-open this issue with the expectation that the current behavior is wrong *and* shouldn't be configurable: prose should use two spaces to mark the end of sentences. This is the standard that text editors have used for decades to edit with sentence-based semantics.

@kachkaev, pinging you for your thoughts since you identified my issues as a duplicate.

**Comment by kachkaev** [comment]
I am not a native English speaker, but I have heard about [French and English spacing](https://en.wikipedia.org/wiki/History_of_sentence_spacing) as a somewhat controversial topic.  There is no need to agree on it.

When it comes to markdown source, any number of spaces is always rendered as one, try it yourself:

```md
Hello world. Hello world.
Hello world.  Hello world.
Hello world.   Hello world.
```

> Hello world. Hello world.
> Hello world.  Hello world.
> Hello world.   Hello world.

So even if Prettier did not collapse multiple spaces in markdown _sources_, the end result would be still the same.

---

If you want markdown to be rendered with French spacing, you will need to add [non-breaking spaces](https://en.wikipedia.org/wiki/Non-breaking_space) yourself.

```md
Hello world. Hello world.
Hello world.&#160; Hello world.
Hello world.&#160;&#160; Hello world.
```

> Hello world. Hello world.
> Hello world.&#160; Hello world.
> Hello world.&#160;&#160; Hello world.

Note that this will probably not work that well with word wrapping.  Alternatively, you can customise markdown your markdown processing flow by inserting extra spacing on render.

**Comment by vermiculus** [comment]
I don't particularly care about the rendered content -- I leave that to the stylesheets. Prettier of course isn't involved in the rendering process 😄

It's really the editing experience of writing Markdown that's the impetus here. I do know the current behavior -- and I contend that it's not as beneficial to the source-writer as collapsing to two spaces. My report is really about 'When I run Prettier on a Markdown file, my editor no longer knows where sentences begin/end.'

**Comment by kachkaev** [comment]
If you want to keep sentences separated in the source, you can consider writing them on separate lines:

```markdown
Hello world 1.
Hello world 2.
Hello world 3.

```

Most markdown renderers render `\n` as whitespace:

> Hello world 1. Hello world 2. Hello world 3.

Newlines are created by `[space][space]\n`. Prettier knows about this and does not remove trailing spaces if there is two of them.

If you use a version control system like `git`, keeping each sentence on its own line will help you keep clean diffs and improve `git blame`. I do this in my own markdowns.

Keeping two spaces in the middle of a line will make a lot of other Prettier users upset because they rely on this feature. Detecting whether it’s the end of a sentences or anything else is impossible.

**Comment by vermiculus** [comment]
I'm aware of how Markdown renders newlines and how Git tracks changes -- but I understand you've got to cover your bases.

Tracking Markdown line-by-line in my experience has been a pain. Even with tooling, working with folks who don't have that tooling becomes a 'why are are you making me do this weird thing' conversation -- which admittedly doesn't have a compelling reason behind it.

I really do believe changing how prettier emits Markdown should be considered at face-value.

**Comment by kachkaev** [comment]
> If there was a way to reliably detect the end of a sentence, would this be considered?

What we are looking for here is a detector that reliably works for all human languages, is fast and does not explode the bundle size. Not sure it can exist even in theory.

I’ve been researching detectors for ends of sentences because I wanted to automatically keep one sentence per line (e.g. via [`markdownlint`](https://www.npmjs.com/package/markdownlint)). The detection task is exactly the same as yours for double spaces.

No luck for me in the JavaScript ecosystem, but I have found some solution for [LaTeX](https://en.wikipedia.org/wiki/LaTeX). There is a package called [`latexindent`](https://ctan.org/pkg/latexindent?lang=en) that accepts a lot of options. Here are the relevant ones which I have used in my LaTeX projects:

```yaml
modifyLineBreaks:
  oneSentencePerLine:
    manipulateSentences: 1
    textWrapSentences: 1
```

The experience is... far from ideal. When sentences are detected correctly, it’s kind of cool but not much of a big deal. But when there is a false-positive or false-negative, editing experience becomes a nightmare. It takes time to hack around misdirection by adding comments, playing with `{` `}` and so on. And that is for research papers written in English – I guess other human languages or styles of English will suffer even worse!

My current conclusion is that sentence detection is an impossible task. If you prove me wrong, I’ll be happy to try out something new and re-evaluate my thinking!

**Comment by vermiculus** [comment]
I worked with latexindent output briefly in the past and it's a jarring experience for sure 😄 My hacking around its problems was limited to my understanding of Perl, which is about nil.

I agree with you that, even in theory, a system for detecting grammars for every written language is at least a ridiculous undertaking.  Even Google Translate with its gobs of ML data sometimes can't simply identify what language it's working with, so a single parser for all written languages is at least that hard.

In concept, would a setting for 'grammar parser' be well-received? My understanding is that Prettier wants to make opinionated decisions on what it emits -- I'm not sure what the status-quo is on instructing Prettier to look elsewhere for an AST (which is essentially what we're asking for).

(I recognize this is far beyond the scope of this issue at this point! Creating even a simple AST for written language seems like a large project -- but perhaps not if you limit yourself to CommonMark or some other established markup standard. There's an element of this that is also just me wanting to gauge Prettier's general, open-to-changing stance on this end of the 'configurability' question.)
