### ISSUE TITLE
HTML class line separation should be respected

### ISSUE THREAD

**Issue by pburkindine** [prettier/prettier#9819]
This issue is to draw some attention back to https://github.com/prettier/prettier/issues/7863

This issue continues to be a blocker for upgrade for my project, and there were a number of other parties on the previous issue expressing the same concern, but the issue has gone quiet.

**Comment by thorn0** [comment]
Whose attention are you trying to draw this way? The maintainers are aware of the issue, but there is really little interest from users, which is why we are reluctant to proceed with this potentially drastic change. So that's whose attention is needed.

I guess we can add a link to the issue to the next blog post and invite people to share their opinion. Meanwhile you can try doing something similar too on Reddit, Twitter, etc.
